Foundation/NSArray.swift
=> Fixing whitespace formatting

Foundation/NSString.swift, TestFoundation/TestNSString.swift
namely
```swift
public convenience init?(data: NSData, encoding: UInt)
public convenience init?(bytes: UnsafePointer<Void>, length len: Int, encoding: UInt)
public convenience init?(CString nullTerminatedCString: UnsafePointer<Int8>, encoding: UInt)
```
=> Several NSString constructors implemented

Foundation/NSArray.swift
Completed bounds checking however I need feedback on what should should be done if the index is out of range.
=> [Need Feedback]: Added bounds checking to NSArray subscript

CoreFoundation/Base.subproj/CFRuntime.c
This was fixed in '54a6b46 IRGen: If Objective-C interop is
disabled foreign classes should use Swift reference counting'.
@parkera @phausler
=> Remove workaround for IRGen bug

Foundation/NSCache.swift
mark NSCache() initializer as public to allow instantiate NSCache outside Foundation framework.
=> mark NSCache() initializer as public

Foundation.xcodeproj/project.pbxproj, Foundation/NSRange.swift, TestFoundation/TestNSRange.swift, TestFoundation/main.swift, build.py
Great job with the OSS release! :clap: 
Here's a first attempt at contributing something small.
All strings in the test cases were compared against the result of using `NSRangeFromString` in Foundation today. Some of that behavior I find odd, but I opted to keep it as-is. I'm happy to consider other implementation approaches too.
=> add implementation for NSRangeFromString and testNSRange.swift

Docs/GettingStarted.md
Two small clarifications:
1. peer directory -> sibling directory (I believe this is a standard, common way of saying this)
2. The Xcode target is called "SwiftFoundation", not "Foundation"
=> Clarify GettingStarted.md

Foundation/NSURLError.swift
Added the missing keys required to complete the implementation of NSURLError
=> Added missing keys for NSURLError

Foundation/NSCalendar.swift
Flow is more logical and easy to follow by setting `timezone` immediately after declaration. Additionally, return values more closely follow idioms specified [here](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Functions.html#//apple_ref/doc/uid/TP40014097-CH10-ID528).
=> Clarify where NSCalendar timezone is set and return values

CoreFoundation/NumberDate.subproj/CFNumber.c, TestFoundation/TestNSNumber.swift
During initalization store the number type in the CFInfo bitfield in the
same way that CFNumberCreate does.
NSNumber/CFNumber stores its value in a UInt64 (_pad) with associated type
information as part of the CFInfo bitfield. NSNUmber Initialization is
performed through _CFNumberInit which copies the value bytes into _pad but
does not store the type information. This leads to broken behaviour when
converting between type repesentations. i.e. Double -> NSNumber ->
Integer.
Fixes: https://bugs.swift.org/browse/SR-71
=> [SR-71] Repair NSNumber behaviour

Foundation/NSIndexSet.swift
Some of the TODOs in NSIndexSet regarding bounds checking were already implemented.
=> Remove some TODOs

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
1. NSString values replaced with String values
2. API return type changed to [String : Any]
3. NSFileOwnerAccountName and NSFileGroupOwnerAccountID values are not verified since they are optional. NSFileImmutable and NSFileAppendOnly values are not verified since they are used on iOS and OS X
=> Verify contents of the file attributes dictionary

Foundation/NSIndexPath.swift
In `init(indexes:length:)`, initialize `_indexes` to an `Array` constructed with an `UnsafeBufferPointer` built from `indexes`, instead of initializing it to an empty array and adding each `idx` in `indexes` to it in a loop.
=> Simplify implementation of `init(indexes:length:)`.

Foundation/NSIndexSet.swift
The code snippets in NSIndexSet's comments are currently written in Objective-C. Even though this code does not execute on Swift Foundation, I have tried it with Foundation on OS X in a playground and it executes as you would expect from the Obj-C snippet.
=> Update NSIndexSet enumeration snippets to Swift

TestFoundation/TestNSFileManager.swift
Check only for the existence of file owner's account (user) identifier instead of comparing its numeric value because
- user identifier of `0` are assigned to the superuser in linux
- negative value are valid account identifier. e.g. `nobody` is `-2` (See https://en.wikipedia.org/wiki/User_identifier)
- There's an assumption made here that account identifier are numeric which is reasonable for most system but there's a slim chance that this might not be the case.
Thanks to @lxcid
=> Fixes test case TestNSFileManger.test_fileAttributes

Foundation/NSDecimalNumber.swift, Foundation/NSPort.swift, Foundation/NSRunLoop.swift, Foundation/NSURLProtectionSpace.swift, Foundation/NSUserDefaults.swift
Just a bit of low-hanging fruit.
=> Add string constants

Foundation/NSProgress.swift
Defines the constants for NSProgress
=> Add NSProgress string constants

.gitignore, CONTRIBUTING.md, CoreFoundation/Base.subproj/CFBase.h, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Docs/Design.md, Docs/GettingStarted.md, Foundation.xcodeproj/project.pbxproj, Foundation/NSData.swift, Foundation/NSFileHandle.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSThread.swift, Foundation/NSXMLParser.swift, README.md, TestFoundation/TestNSPipe.swift, TestFoundation/TestNSRange.swift, TestFoundation/TestNSXMLParser.swift, TestFoundation/main.swift, build.py, configure, lib/config.py, lib/script.py
The implementation itself is very simple. In the unlikely event that the
`pipe` system call fails, this implementation will stop with a fatalError.
This seems to be the canonical way of doing it based on my cursory reading of
the rest of foundation.
I've also added a first, simple, unit test to make sure the pipe works as expected.
=> Added `NSPipe` implementation

Foundation/NSDictionary.swift
Implemented isEqualToDictionary and would like some feedback.
=> [Need feedback]: Implemented isEqualToDictionary

Foundation/NSGeometry.swift
Implemented some basic geometry functions
=> Implement basic geometry functions

Foundation/NSString.swift, TestFoundation/TestNSString.swift
This was extracted from https://github.com/apple/swift-corelibs-foundation/pull/44. This adds an implementation of isEqual for NSString, which is necessary for initializing NSCalendar instances.
=> Adds an implementation of isEqual to the NSString class.

Foundation.xcodeproj/project.pbxproj, TestFoundation/TestNSDate.swift, TestFoundation/main.swift
Mucking around with git and rebase and accidentallied all the files. Adding back in from local copy and requesting new PR.
=> Tests for NSDate

CoreFoundation/Locale.subproj/CFCalendar.c, Foundation.xcodeproj/project.pbxproj, TestFoundation/TestNSCalendar.swift, TestFoundation/main.swift
This is copied from #44, which got closed when I reorganized the branches and split up the request into two parts.
This request is to fix a few related bugs in initializing calendars and getting date information out of them:
* It adds a mapping for the "leap month" field
* It adds support for the Chinese calendar, which was disabled in the initial commit but seems to be working now.
* It fixes a bug that occurred when a calendar could not be fully initialized. Some of the fields were being left null, but were later given to CFRelease without a check for nulls.
=> Fixes for calendar initialization

Foundation.xcodeproj/project.pbxproj, Foundation/NSAffineTransform.swift, Foundation/NSGeometry.swift, TestFoundation/TestNSAffineTransform.swift, TestFoundation/main.swift, build.py
As described in the reference for NSAffineTransform, this initializer:
Creates and returns a new NSAffineTransform object initialized to the identity matrix.
Part of this change:
- an initializer for the underlying `NSAffineTransformStruct`'s members has been implemented
- an initializer for creating `Double`s from `CGFloat`s has been added to aid testing. Its signature is identical to the one in `CoreGraphics` in the iOS 9.1 SDK. Tests are implemented in terms of `Double`s since `XCTAssertEqualWithAccuracy` only works with types that implement `FloatingPointType`, which `CGFloat` currently does not.
=> Implemented NSAffineTransform.init() with tests

Foundation.xcodeproj/project.pbxproj, Foundation/NSTimeZone.swift, TestFoundation/TestNSTimeZone.swift, TestFoundation/main.swift
- Add implementation of `NSTimeZone`'s `abbreviation` property getter.
- Add a test case for the above implementation.
=> [NSTimeZone] Add implementation of abbreviation property and tests

CoreFoundation/Stream.subproj/CFConcreteStreams.c
The `dataGetBuffer` function computes the number of bytes that have been read from the stream so far when it should compute the number of bytes remaining, with the following issues:
* A stream that hasn't been read yet reads 0 bytes and sets its status to `AtEnd`.
* A stream that is near its end reads more bytes than it should.
That bug has been affecting CoreFoundation and Foundation on OS X and iOS for a while.
That bug will eventually affect `NSInputStream`'s `getBuffer(:length:)` when it's implemented.
Reference: http://openradar.me/5177598
Unit Test: baarde/swift-corelibs-foundation@81125ffc83051e2ebdca79cb504b51fd389dba5f
=> Fix a bug in CFReadStreamGetBuffer for data streams

Foundation/NSString.swift, TestFoundation/TestNSString.swift
Gives same output as Standard Foundation for the same test values.
=> implement NSString.boolValue

Foundation.xcodeproj/project.pbxproj, Foundation/NSScanner.swift, TestFoundation/TestNSScanner.swift, TestFoundation/main.swift
Copied from commit message:
After writing a simple test case for `NSScanner`, I found that `NSScanner` always returns 0 when scanning numbers. The problem is in `_NSStringBuffer`'s init function, `curChar` was assigned to `buffer[0]` before `buffer` gets characters from scanned string. Changing `curChar` to an optional variable and assign it to `buffer[0]` after `buffer` got all characters from scanned string fixed this.
=> [NSScanner] Fix a bug in the initialization of _NSStringBuffer that makes NSScanner unable to find any number

Foundation/NSCFArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSCFString.swift, Foundation/NSDictionary.swift, Foundation/NSSet.swift, Foundation/NSString.swift
This is a small step towards removing C-style loops in favor of Swift for/in loops as presented in this accepted proposal:https://github.com/apple/swift-evolution/pull/23/commits . Nothing big here, just getting my feet wet and trying help improve code quality :). Note that similar changes in `swift`core have already been merged https://github.com/apple/swift/pull/270
=> A small step towards removing C-style loops

Foundation.xcodeproj/project.pbxproj, Foundation/NSGeometry.swift, TestFoundation/TestNSGeometry.swift, TestFoundation/main.swift
This PR implements the following:
- `NSMake*` functions from `NSGeometry`
- `NSMakePoint`
- `NSMakeSize`
- `NSMakeRect` 
- Simplify the default initializers to delegate to the memberwise initializers
- Unit tests for all additions/changes
I decided to make `CGFloat` implement `Comparable` mostly to simplify testing. (Since `CGFloat(1.0).native` became very verbose and repetitive.) However, I noticed that a PR for [conforming `NSDate` to `Comparable`](https://github.com/apple/swift-corelibs-foundation/pull/19) was declined because it was considered an API change. It's not clear if this is also considered an API change that necessitates following the *Swift evolution process* since `CGFloat` is more or less a a basic type? In any case, I'm happy to make any necessary changes.
=> NSGeometry: add unit tests

Foundation/NSObjCRuntime.swift
To be in sync with value in Foundation on Apple platforms
=> NSComparisonResult.OrderedAscending should be equal to -1

Foundation.xcodeproj/project.pbxproj, Foundation/NSData.swift, TestFoundation/TestNSData.swift, TestFoundation/main.swift
Cleaned up resubmission of #57, powered by awesome feedback™
=> Implement -[NSData writeToURL:options:error:]

Foundation/NSAffineTransform.swift, Foundation/NSGeometry.swift, TestFoundation/TestNSAffineTransform.swift
As part of this change:
- The addition and multiplication operators have been implemented for `CGFloat` so we can compute dot products.
- A private helper function for matrix-vector products has been implemented.
- Tests for the identity transformation have been added. Once we support more operations (translations, rotations, and scales), we can add more tests.
=> Implement NSAffineTransform.transform{Point,Size} with tests

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation.xcodeproj/project.pbxproj, Foundation/NSUUID.swift, TestFoundation/TestNSUUID.swift, TestFoundation/main.swift
* Implement `isEqual` and `hash`
* Do not crash when initialised with `NSUUID(UUIDBytes: nil)`
* Fix `UUIDString` implementation
* Implement a sensible `description`
=> NSUUID improvements

Foundation/NSAffineTransform.swift, TestFoundation/TestNSAffineTransform.swift
- A helper function for multiplying two 3x3 matrices has been implemented. This will also be helpful for implementing scaling and rotation.
- An initializer for creating `NSAffineTransformStruct`s with matrices has been created for convenience.
- Translation has been implemented as multiplication of the current transformation matrix with a translation matrix.
=> NSAffineTransform: implemented support for translation with tests

Foundation/NSString.swift, TestFoundation/TestNSString.swift
Implementation of uppercaseString, lowercaseString, capitalizedString (with localized versions) for NSString. Tests for methods.
I tested it with this tests: https://github.com/apple/swift/blob/master/test/1_stdlib/NSStringAPI.swift and noticed strange behaviour. 
this test fail:
```
XCTAssertEqual(NSString(stringLiteral: "\u{0069}").uppercaseStringWithLocale(NSLocale(localeIdentifier: "tr")), "\u{0130}")
```
this don't
```
XCTAssertEqual(String(stringLiteral: "\u{0069}").uppercaseStringWithLocale(NSLocale(localeIdentifier: "tr")), "\u{0130}")
```
Difference is `NSString(stringLiteral:)` vs. `String(stringLiteral:)`. The result of uppercaseStringWithLocale is correct, though comparison is failing. This may be some issue with NSString.
=> NSString: uppercaseString, lowercaseString, capitalizedString

Foundation/NSAffineTransform.swift, Foundation/NSGeometry.swift, TestFoundation/TestNSAffineTransform.swift
Hi,
The changes in this PR improve the implementation of the transformation methods. The new implementation makes use of the fact that a 2D affine transformation matrix is not an arbitrary 3x3 matrix (see code comments), and is both simpler and more efficient by skipping unnecessary computation steps.
Also included is:
- Implementation of `NSAffineTransformStruct.init()` which initializes all entries to zeros.
- Implementation of `NSAffineTransform.init(transform:)`
- Implementation of `NSCopying` methods for `NSAffineTransform`
=> Implement NSAffineTransform

Foundation/NSAffineTransform.swift, TestFoundation/TestNSAffineTransform.swift
Now that we have a generic matrix multiplication function, this becomes trivial. I have also verified these tests against the `NSAffineTransform` in the 10.11 SDK to ensure consistent results (e.g. order of oeprations).
=> NSAffineTransform: implemented support for scaling with tests

Foundation/NSData.swift
File descriptor is not closed if no error occurs. Eventually they get exhausted after 1000 NSData( contentsOfFile: path )
=> Always close file descriptor (eventually runs out of them)

Foundation.xcodeproj/project.pbxproj, Foundation/NSByteCountFormatter.swift, TestFoundation/TestNSByteCountFormatter.swift, TestFoundation/main.swift
Default values are added.
Unit test for the NSByteCountFormatter added.
Based on comments from the closed pull request #80
=> Implementation of NSBytecountFormatter default values

Docs/Status.md
`NSAffineTransform` was fully implemented in #93, except `NSCoding` support.
=> Update NSAffineTransform implementation status

Foundation.xcodeproj/project.pbxproj, Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift, TestFoundation/main.swift
Added implementation of `isValidJSONObject`.
Testing is currently difficult since `NSArray`, `NSString,` and `NSDictionary` are not yet fully implemented, so I tested this by writing tests using the existing Foundation classes in another project. I added these tests here and commented them out since they cannot yet be used and added a `TODO:` to enable the tests once ready.
Let me know what you think!
=> NSJSONSerialization isValidJSONObject Implementation

CoreFoundation/String.subproj/CFString.c
This fixes CFStringCreateByCombiningStrings' handling of non-ASCII separator strings (radar 23834767).
Test code that reproduces the bug:
```c
int main(int argc, const char *argv[])
{
CFMutableArrayRef arr = CFArrayCreateMutable(kCFAllocatorDefault, 2, &kCFTypeArrayCallBacks);
CFArraySetValueAtIndex(arr, 0, CFSTR("Hello"));
CFArraySetValueAtIndex(arr, 1, CFSTR("World"));
CFStringRef result = CFStringCreateByCombiningStrings(kCFAllocatorDefault, arr, CFSTR("»"));
assert(CFStringGetLength(result) == 11);
UniChar expectedResult[11] = {
0x0048, 0x0065, 0x006C, 0x006C, 0x006F, // Hello
0x00BB,                                 // »
0x0057, 0x006F, 0x0072, 0x006C, 0x0064  // World
};
for (CFIndex i = 0; i < CFStringGetLength(result); i++) {
UniChar ch = CFStringGetCharacterAtIndex(result, i);
if …
```
=> Fix CFStringCreateByCombiningStrings' handling of non-ASCII separators.

Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift
+ Basic initialization
+ Getters / setters
+ Set / add request header functions
+ Tests
I didn't implement this to avoid changing the interface, but I think it would make sense going forward to change NSURLRequest's init(NSURL) method from convenience to required and mark the URL property as non-optional.
=> NSMutableURLRequest implementation

Foundation.xcodeproj/project.pbxproj, TestFoundation/main.swift
- Easier to know where to add new one.
- Avoiding duplications by mistakes (I found 2 `TestNSJSONSerialization `).
=> Rearrange list of all test cases alphabetically.

Foundation/NSGeometry.swift, TestFoundation/TestNSGeometry.swift
Implemented two more functions from NSGeometry: NSIntegralRect and NSIntegralRectWithOptions
Not sure if the function should produce fatalError in case if input is wrong, but it seems to behave like this in objc version of foundation.
Also tried to cover NSIntegralRectWithOptions with tests, but I'm not 100% sure if test covers every possible case. Would be really great to see objc version of the same tests.
=> Implement NSIntegralRect and NSIntegralRectWithOptions

uuid/uuid.c
calculation of `tv->tv_nsec` is broken:
- it's by one order of magnitude more than it should be.
- it should be `now % 1000000000` (now - (now / NSEC_PER_SEC) * NSEC_PER_SEC)
=> Fix nanoseconds calculation in uuid.c

CoreFoundation/Base.subproj/CFUtilities.c
I'm not 100% sure about this one, primarily because it doesn't crash on OS X, however this fixes [this crash](https://github.com/apple/swift-corelibs-foundation/pull/50#discussion_r47550314) on linux for me
Also, looking at the line above (return within `#if TARGET_IPHONE_SIMULATOR`) I see that it actually creates and returns a new copy of a string - just what method's name says.
=> Return copy of path

TestFoundation/TestNSAffineTransform.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSByteCountFormatter.swift, TestFoundation/TestNSCalendar.swift, TestFoundation/TestNSCharacterSet.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSDate.swift, TestFoundation/TestNSDictionary.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSGeometry.swift, TestFoundation/TestNSHTTPCookie.swift, TestFoundation/TestNSIndexSet.swift, TestFoundation/TestNSJSONSerialization.swift, TestFoundation/TestNSNotificationCenter.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSPipe.swift, TestFoundation/TestNSPropertyList.swift, TestFoundation/TestNSRange.swift, TestFoundation/TestNSSet.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSTimeZone.swift, TestFoundation/TestNSURL.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestNSURLResponse.swift, TestFoundation/TestNSUUID.swift, TestFoundation/TestNSXMLParser.swift
This change should be done now in early stage, to prevent new code keep following the old convention.
=> Ditch "-> ()" in favor of "-> Void"

Foundation.xcodeproj/project.pbxproj, Foundation/NSThread.swift, TestFoundation/TestNSThread.swift, TestFoundation/main.swift
The `currentThread` method call returns different values. We should check the `pthread_key_create` result for 0. According to documentation:
> If successful, the pthread_key_create() function shall store the newly created key value at *key and
> shall return zero. Otherwise, an error number shall be returned to indicate the error.
=> The `currentThread` method call returns different values

CoreFoundation/Base.subproj/CFPriv.h
=> Fix pthread warnings on ubuntu

CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/CoreFoundation_Prefix.h, CoreFoundation/NumberDate.subproj/CFDate.c, CoreFoundation/RunLoop.subproj/CFRunLoop.c, Foundation.xcodeproj/project.pbxproj, Foundation/NSRunLoop.swift, Foundation/NSSwiftRuntime.swift, TestFoundation/TestNSRunLoop.swift, TestFoundation/TestNSTimer.swift, TestFoundation/main.swift, build.py, closure/runtime.c
addPort and removePort are not implemented because NSPort implementation is missing.
=> Implement NSRunLoop

Docs/Status.md, Foundation.xcodeproj/project.pbxproj, Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundation.xcscheme, Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme, Foundation/NSNumber.swift, Foundation/NSNumberFormatter.swift, TestFoundation/TestNSNumberFormatter.swift, TestFoundation/main.swift
- Added implementation for attributes.
- Added tests for initial implementation.
- Updated implementation status documentation.
=> Initial implementation of NSNumberFormatter.

CoreFoundation/NumberDate.subproj/CFTimeZone.c, TestFoundation/TestNSTimeZone.swift
The shadowed variable that's being removed in this PR causes the name to fall out of scope as soon as it exits the "if (0 < ret)" block, and the outermost "name" field is left null. This causes the systemTimeZone to always report as GMT.
I'm not sure if the mechanism I'm using to test this is the best way to go. Calling into the C time functions seems like a hack, and something that might get broken by subtle changes to system configurations. It works on both my Mac and Linux installs, and it correctly gives an error when the change to CFTimeZone.c is removed.
=> Fixes a shadowed variable in the system time zone initializer.

TestFoundation/TestNSCalendar.swift
=> Forces the tests for calendar date conversion to use UTC instead of system time.

TestFoundation/TestNSCharacterSet.swift
This test used to take 2 minutes on my (virtual) linux machine. On OS X it used to be 2.5 seconds, which is acceptable.
Also here's a list of tests that are also relatively slow to run:
```
Test Case 'TestNSURL.test_URLStrings' passed (7.307 seconds).
Test Case 'TestNSURLComponents.test_string' passed (14.938 seconds).
```
=> Change TestNSCharacterSet.test_Predefines

Foundation/NSArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSCalendar.swift, Foundation/NSDictionary.swift, Foundation/NSIndexSet.swift, Foundation/NSPathUtilities.swift, Foundation/NSScanner.swift, Foundation/NSString.swift
[Remove the ++ and -- operators](https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md) proposal has been accepted.
++ and -- operators will be removed from Swift 3.0. So, let's change it now :smile:
=> Remove ++ and -- operators

Foundation/NSAffineTransform.swift, TestFoundation/TestNSAffineTransform.swift
Hi,
I just noticed that my implementation of `NSAffineTransform` (added in #93) was applying transformations in the opposite order than Darwin's.
My previous implementation assumed that the properties of `NSAffineTransform` represent a matrix that looks like this
```
[ m11  m12  tX ]
[ m21  m22  tY ]
[  0    0    1 ]
```
and applied transformations by `T * p` where `T` is the transformation matrix and `p` a column vector.
As it turns out, however, the matrix rather looks like that
```
[ m11  m12  0 ]
[ m21  m22  0 ]
[  tX   tY  1 ]
```
and transformation are applied by `p' * T` where `p'` is a row vector.
This has direct influence on the order of application, because `T * p = S * R * p` would apply `R` before `S`, whereas `p' * T = p' * S * R` would apply `S` before `R`.
I've also added …
=> Fix NSAffineTransform

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
Implementing NSFileManager::contentsOfDirectoryAtPath() and NSFileManager::subpathsOfDirectoryAtPath().
Error messages aren't currently an exact match for the standard Foundation library, which throws:
```
Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=260 "The folder “notexist” doesn’t exist." UserInfo={NSFilePath=/Users/euan/Desktop/notexist, NSUserStringVariant=(
Folder
), NSUnderlyingError=0x1007019f0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.1.101.15/src/swift/stdlib/public/core/ErrorType.swift, line 56
(lldb)
```
Whereas this commit throws:
```
fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=260 "The file notexist couldn’t be …
```
=> Implement contentsOfDirectoryAtPath

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift
Added the implementation of this method as well as a test for it
=> Added NSArray.replaceObjectsInRange(range, otherArray, otherRange) 

Foundation/NSIndexSet.swift, TestFoundation/TestNSIndexSet.swift
Fixing a bug where adding neighboring indices would result in an incorrect range being created in the index set.
Example:
```swift
let set = NSMutableIndexSet(index: 0)
set.addIndex(1)
```
In this case, the index set would contain one NSRange (location 2, length 0). 
The correct result should be that the index set contains one NSRange (location 0, length 2).
Added some tests as well.
=> Fix: addIndexesInRange now correctly adds neighbor NSRanges

Foundation/NSScanner.swift, TestFoundation/TestNSString.swift
Previously it would always return just the first character in the string due
to broken location reporting in `_NSStringBuffer`
=> Fix `NSString.stringByTrimmingCharactersInSet` behavior

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift
The `sortedArrayUsingComparator` method doesn't work correctly. Under the hood it uses the `Array`'s sort method. We used to provide wrong elements ordering via `isOrderedBefore` closure.
Fixed the root cause and implemented unit tests.
=> The sortedArrayUsingComparator method doesn't work correctly

Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
Including tests. Note the one `NSNumber(unsignedChar:)` assertion that is commented out for
the same reason as the series of assertions in test_numberWithUnsignedChar
=> Implement NSNumber.compare

Foundation/NSObjCRuntime.swift
This allows these error functions to report the failure as being at the call site, which will make it easier to debug errors caused by trying to call unimplemented methods.
=> Adds file and line context to more error functions.

CoreFoundation/String.subproj/CFString.c, TestFoundation/TestNSString.swift
Currently the CFInfo fields on NSString are being set to 0x80, 0x07, 0x00, 0x00. This means that the flag for __kCFContentsMask is being set to __kCFHasInlineContents, which is not an accurate description of how the data is laid out in an NSString that's created from a  Swift String. This in turn causes the result of `NSString.init(format:arguments:)` to be empty, since it's going through a CFString method that can't properly read the format string.
=> Sets the special flags in the CFType info on NSString to properly indicate its storage type.

Foundation/NSNumber.swift
- Better match Darwin Foundation behavior
=> Add override for `description` on NSNumber

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift
Implemented `sortUsingFunction`, `sortUsingComparator`, `sortWithOptions` methods from the NSMutableArray class.
=> Implemented various sorting methods from the NSMutableArray class

CoreFoundation/Locale.subproj/CFDateFormatter.c
Renamed a private function in CFDateFormatter.c to better reflect its memory semantics.  No functional changes, fixes a static analyzer warning.
=> Renamed CFDateFormatter.c's __CFDateFormatterGetSymbolsArray to __CFDateFormatterCopySymbolsArray

Foundation/NSPathUtilities.swift, TestFoundation/TestNSString.swift
It deletes final path separator now. If the receiver represents the root path it is returned unaltered.
=> Fixes NSString.stringByDeletingLastPathComponent.

Docs/Status.md, Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
I ran 2 benchmarks against the current JSON parser implementation on `master`, comparing it to Darwin Foundation for [large inputs](https://github.com/zemirco/sf-city-lots-json/blob/master/citylots.json) and found it was 5-10x slower. (72s vs 8s for a single decode). This new code reduces this to a factor for 2-4x (17s)
While JSON is a text-based serialization, all control characters are ASCII characters. The data can be most efficiently parsed as a stream of bytes instead of the initial overhead of converting the bytes to a String.
The byte -> string conversion in the current code only accounts for 3s of time but parsing numbers is incredibly expensive (`Double.init?(_ text: String)` converts the string back to bytes to use [`strtod()`](https://developer.apple.com/library/mac/documentatio …
=> Speed up JSON Parsing

Foundation/NSCFDictionary.swift, Foundation/NSSwiftRuntime.swift
CFDictionaryGetKeysAndValues() bridges to _CFSwiftDictionaryGetKeysAndValues()
which accepts parameters in the CF, not Foundation order. The arguments are
transposed in the current code.
[SR-379] CFDictionaryGetKeysAndValues() bridges values and keys in wrong order
CFDictionaryGetKeysAndValues() bridges to _CFSwiftDictionaryGetKeysAndValues()
which accepts parameters in the CF, not Foundation order. The arguments are
transposed in the current code.
[SR-379] CFDictionaryGetKeysAndValues() bridges values and keys in wrong order
=> [SR-379] CFDictionaryGetKeysAndValues() order

Foundation/NSString.swift, Foundation/NSSwiftRuntime.swift
Bridging hash functions crash frequently, I suspect due to integer overflow.
=> [SR-380] NSString.hash.getter crash workaround

CoreFoundation/Base.subproj/CFLogUtilities.h, CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSLog.swift
This implements an NSLog-like API, currently marked internal, that calls CFLog and can be used for displaying Darwin-style log messages
TODO: propose a better solution for platform-dependent cast in NSLog(). Somehow the enum is coming across differently.
=> [SR-386] NSLog() API at least for internal use

Foundation/NSCFDictionary.swift
_CFSwiftDictionaryGetKeysAndValues() crashes with NULL arguguments
It's valid to enumerate a dictionary with CFDictionaryGetKeysAndValues(), only
retrieving the keys or values (or indeed nothing).
=> [SR-391] _CFSwiftDictionaryGetKeysAndValues() parameter validation

Foundation/NSCalendar.swift, Foundation/NSCharacterSet.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSNumber.swift, Foundation/NSTimeZone.swift, Foundation/NSURL.swift
CF bridged objects are not correctly implementing Equatable because they do not provide an isEqual method. Whilst we're at it, implement hash and description.
=> [SR-414] isEqual/hash/description for bridged CF objects

Foundation/NSTask.swift, TestFoundation/TestNSTask.swift
By making the manager thread more generic, we'll now be able to schedule IO on it (eventually, once NSFileHandle and NSPipe are finished).
=> Refactored NSTask's manager thread to be more run-loop friendly

Foundation/NSNumber.swift
Was missing fix for [SR-380] hash overflow and NSNumber type check in isEqual
Sorry @phausler – sloppiness on my part
=> [SR-414] redux: fix NSNumber.hash and isEqual

build.py
This allows Foundation to be installed with a prefix that is not '/usr' and
resolves [SR-422](https://bugs.swift.org/browse/SR-422).
=> Use the prefix for CoreFoundation headers/module data

Foundation/NSSwiftRuntime.swift, Foundation/NSUUID.swift
=> [SR-414] avoid overflow on __NSCFType and NSUUID hash properties

Foundation/NSData.swift, TestFoundation/TestNSData.swift
The current NSData's base64 implementation does not decode data with padding correctly : the output contains the padding. Some of the tests were also wrong because it was testing the String representation instead of the underlying UTF8 data. I started by trying to fix that, but the current implementation makes it really difficult. I ended up by re-implementing most of it with bit shifting operations.
=> fix base64 decode with padding

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/NumberDate.subproj/CFNumber.c
If a bridged CF type is instantiated before __CFInitializeSwift() is called, then those types will not be bridged. This created unusual and unexpected results when initializing floating point numbers containing cached values such as 0.0, 1.0 and NaN: decoding a property list containing these would assert fail but other numbers would be fine.
This patch fixes this bug by moving the initialization of CFNumber constants to a new function, __CFNumberInitialize(), which is called after the Swift bridge is initialized. This patch is enabled but should not regress non-Swift builds.
CFNull and CFBooleans are instantiated before __CFInitializeSwift() is called; if these types are ever bridged then a similar fix must be made.
=> [SR-439] Cached floating-point CF values do not bridge

Foundation/NSPathUtilities.swift
* `getlogin_r` replaced with get `getpwuid_r->name`. According to the manpage it should be more reliable.
* use `sysconf(Int32(_SC_GETPW_R_SIZE_MAX))` to get recommended size of a buffer
* for the current user check `$HOME` environment variable first
=> Improve NSUserName NSHomeDirectoryForUser

Foundation/NSString.swift, TestFoundation/TestNSString.swift
On Darwin we can do
let argument: UInt8 = 75
let string = NSString(format: "%02X", argument)
This is because Darwin NSString has constructor
public convenience init(format: NSString, _ args: CVarArgType...)
This patch adds, implements, and tests this constructor.
=> Add a missing constructor for NSString

configure, lib/config.py, lib/phases.py, lib/product.py, lib/script.py, lib/target.py, lib/workspace.py
Other projects have asked that their Python enabled scripts were refactored to be compatible with Python 2 or 3. This patch continues that vein in the `corelibs-foundation` project.
=> [configure] Refactor to be compatible with Python 2 or 3

Foundation/NSArray.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSDictionary.swift, Foundation/NSNumber.swift, Foundation/NSObject.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSURL.swift
The _cfTypeID property in NSObject was marked internal, which currently breaks subclassing Foundation classes on Linux. Marking it public for now per comment from @jrose-apple in bug report.
=> [SR-272] make _cfTypeID public for now

Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSSet.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSDictionary.swift, TestFoundation/TestNSSet.swift
Implemented `copyWithZone`, `mutableCopyWithZone` methods for the `NSArray`, `NSMutableArray`, `NSDictionary`, `NSMutableDictionary`, `NSSet`, `NSMutableSet` classes
=> Implemented copyWithZone, mutableCopyWithZone methods for various collection classes

Foundation/NSURL.swift, TestFoundation/TestNSURL.swift
Implement `NSURL.fileSystemRepresentation` and `init(fileURLWithFileSystemRepresentation: isDirectory: relativeToURL)`.
Fix `init(fileURLWithFileSystemRepresentation: isDirectory: relativeToURL)`
Reenable tests for `NSURL`.
=> Fixes and improvements for NSURL

CoreFoundation/URL.subproj/CFURL.c
Tiny refactoring of some unneeded code.
=> Remove unneeded CFStringRef allocations in CFURL.

CoreFoundation/NumberDate.subproj/CFDate.c
The implementation of CFGetSystemUptime() for linux return incorrect values, which make NSThread.sleepForTimeInterval() behave incorrectly : 
- clock_gettime already return values in seconds and nano sec, there is no need to scale it by __CF1_TSRRate
- tv_nsec must be divided 1000000000 to get seconds, not multiplied
=> fix CFGetSystemUptime for linux

Foundation/NSPathUtilities.swift, Foundation/NSURL.swift, TestFoundation/TestNSString.swift, TestFoundation/TestUtils.swift
Now it works with relative paths, symlinks etc. 
Fix behavior when string point to a directory and there are other directories and(or) files with similar names. Previously it searches for all items in directory always. Now if there is no trailing `/` it starts from the parent directory.
=> Improve NSString.completePathIntoString

Foundation/NSError.swift
Came upon this when adding some more implementation to NSXMLDocument.
=> Don't lose userInfo when converting CFError to NSError

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift
* the `replaceObjectAtIndex` uses empty range, that is why replacement works as insertion
* typo in the `removeObjectsInArray`
The copy of this [PR](https://github.com/apple/swift-corelibs-foundation/pull/220), that I closed accidentally. Fixed the compiler error related to the `test_removeObjectsInArray` test.
=> The NSMutableArray fixes

Foundation/NSCFString.swift, Foundation/NSString.swift, TestFoundation/TestNSString.swift
On Darwin we can say
```swift
let a = NSMutableString(string: "Foo")
```
This constructor is not present on corelibs-foundation.
* Implement the constructor
* Test coverage
* We have to move NSString's existing version of the constructor (which shares
the name, so we're overriding) out of its extension and into the
class.  This is because overriding an init declared in an extension is
"not yet supported".  This may be why we don't have the constructor
already.
* Marking required, so as to enforce all subclasses support this.
=> Add string constructor for NSMutableString.

Foundation/NSCFString.swift
f1554eb introduced a warning by declaring a public method on an internal class. Also, use remove fatalError() message for consistency (or, we should use NSUnimplemented() for consistency).
=> [SR-568]: fix warning in init(string:)

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
This implementation wraps the existing NSPathDirectoryEnumerator to do
all the heavy lifting.
Add test coverage.
=> Initial implementation of NSFileManager.enumeratorAtPath.

Foundation/NSDateFormatter.swift
General cleanup includes:
- Remove internal properties in favor of property observers.
- Demote remaining internal access control to private.
- Use guard to enforce returns.
=> Tidy up NSDateFormatter

CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Foundation.xcodeproj/project.pbxproj, Foundation/NSSwiftRuntime.swift, Foundation/NSXMLDTD.swift, Foundation/NSXMLDTDNode.swift, Foundation/NSXMLDocument.swift, Foundation/NSXMLNode.swift, TestFoundation/Resources/NSXMLDTDTestData.xml, TestFoundation/Resources/PropertyList-1.0.dtd, TestFoundation/TestNSXMLDocument.swift, build.py
Namespaces are still basically completely unsupported. There are some hack-y things in this one because libxml2 doesn't quite handle things the way Darwin's NSXMLDocument seems to. That said, everything seems to work. There is one thing that is _technically_ an API change; `objectValue` for a `NSXMLNodeKind.ElementDeclarationKind` on Darwin returns a `NSXMLElementDeclarationContent`, but that is private API that I have no access to or knowledge of despite the lack of a leading underscore. Since it's (apparently, it isn't in any public header or documentation anyway) private, are we OK to not use such a structure here?
There are two test functions I had to disable on Linux because they were segfaulting in swift_dynamicCast. This has something to do with `throw`ing an NSError.
Also, on OS …
=> Add NSXMLDTD and NSXMLDTDNode support

Foundation/String.swift, TestFoundation/TestNSString.swift
The version of hasPrefix and hasSuffix originally found in Foundation for Linux does not do well with Unicode strings. The implementations is this PR reproduce those supplied in the standard library in the presence of the Objective-C runtime, namely swift_stdlib_NSStringHasPrefixNFD and swift_stdlib_NSStringHasSuffixNFD. The test results are largely the same, that is the issues appear to be the same (except the issues related to embedded nulls.)
Closing https://github.com/apple/swift-corelibs-foundation/pull/238, as it is superseded by this.
=> Unicode-compatible (mostly) hasPrefix and hasSuffix

Foundation/NSFileManager.swift
The key NSFileGroupOwnerAccountId is a typo as it is later overwritten by an NSNumber on line 381. The correct constant is NSFileGroupOwnerAccountName to correctly add the String of the account's name to the dictionary.
=> Fix key's typo to NSFileGroupOwnerAccountName

Foundation/NSXMLNodeOptions.swift
This patch aims to address the issues with NSXMLNodeOptions on 32-bit platforms in a way that doesn't impact the API.  The current problem (that ```NSXMLNodeOptionRawType``` aimed to fix) is that the assignment of the sign bit of an Int is flagged by Swift as an overflow.  By assigning this bit with the acknowledgement that it is becoming negative quiets the compiler while maintaining the effect.
=> Addressing 32-bit issues with NSXMLNodeOptions

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
This commit adds support for NSNumber to return a PlaygroundQuickLook object
On the OS X Foundation, this works due to a combination of the Swift runtime and the ObjC runtime cooperating (see Reflection.mm in the Swift runtime)
For corelibs Foundation there is no such support. This patch adds it.
=> Add support for NSNumber to return a PlaygroundQuickLook

Foundation/NSString.swift, TestFoundation/TestNSString.swift
Similarly to the NSNumber case, this pull request involves providing reflection support for NSString
=> Add a CustomPlaygroundQuickLookable conformance for NSString

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/RunLoop.subproj/CFRunLoop.c, CoreFoundation/Stream.subproj/CFStream.c
As part of the prep work I'm doing with @dgrove-oss to enable Dispatch, I've done some testing of compiling swift-corelibs-foundation with `__HAS_DISPATCH__` enabled. That's highlighted a number of compile errors which this PR resolves.
Enabling `__HAS_DISPATCH__` will still result in linker errors, which we'll look to resolve once we have the Dispatch overlay built into lib dispatch on Linux ([libdispatch PR #43](https://github.com/apple/swift-corelibs-libdispatch/pull/43), and made the necessary modifications to the foundation build scripts.
=> Fix compilation issues with HAS_DISPATCH on Linux

Foundation/NSCalendar.swift, Foundation/NSObjCRuntime.swift, TestFoundation/TestNSAffineTransform.swift, TestFoundation/TestNSRegularExpression.swift, TestFoundation/TestNSString.swift
Replaces old identifiers with new ones
=> Changes related to SE-0028

build.py, lib/product.py
This PR is a necessary companion to https://github.com/apple/swift/pull/1157 .  swift.ld is used in the build of Foundation, and with the deletion of the script from Swift, Foundation fails to build.  The first commit uses the conformance begin and end objects generated in Swift for manual share library linking.  Also, this commit allows the Swift build scripts to indicate to Foundation whether it should use the gold linker.
**It's very important that this PR only be merged at the same time as the Swift#1157**
~~The second commit addresses some new regressions introduced in ```NSXML*``` on 32-bit systems.  The ```NSXMLNodeOptionRawType``` type was introduced for working with ```NSXMLNodeOption```s in a bit-width independent way.~~
=> Companion PR to Swift #1157 and 32-bit bug fixes

CoreFoundation/Base.subproj/CFBase.h, build.py
If the foundation build script is invoked from build-script-impl
with libdispatch enabled then add includes and define to CFLAGS.
Add another case in which __HAS_DISPATCH__ is set to 1 that will
be enabled by the CFLAGS set in build.py (staging while work in
progress).
=> Next step in connecting libdispatch and foundation builds

TestFoundation/TestNSURL.swift
This is a relatively minor patch that casts the result of sizeof to UInt so that UInt32 (from 32-bit machines) is promoted to match the other logic.
=> Fixes for TestNSURL.swift on 32-bit (NFC)

CoreFoundation/NumberDate.subproj/CFNumber.c, Foundation/NSDateFormatter.swift, Foundation/NSGeometry.swift, Foundation/NSNumberFormatter.swift, Foundation/NSPathUtilities.swift, Foundation/NSXMLElement.swift
This is a collection of fixes that address some edge cases relating to 32-bit systems, differing alignments, uninitialized locales, and incomplete paths.
=> Foundation fixes for 32-bit systems and more

build.py
This is a PR related to the following PR: https://github.com/apple/swift/pull/1429
They should be merged in sync, otherwise foundation builds will fail after the mentioned PR is merged.
=> Add required flags for using the new SwiftOnoneSupport library

Foundation/NSObject.swift, Foundation/NSSet.swift, TestFoundation/TestNSSet.swift
This pull request contains the implementation of `NSCountedSet`. It includes implementation and test cases for `NSCountedSet`. Please let me know if you need any changes in this. Suggestion are welcome. I am not that much expert with system implementation. So please let me know your views or any other changes required.
Thanks to swift team
=> Implementation of NSCountedSet

build.py
As discussed on mailing list over the weekend, more work is needed
on the libdispatch side before it makes sense to enable dispatch
in foundation.  Disable until it is ready.
=> Comment out enablement of libdispatch until it is really ready

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
=> Implement setAttributesOfItemAtPath for NSFilePosixPermissions attribute

TestFoundation/TestNSTask.swift
This makes the comment header more consistent with the other tests.
=> minor change to license header for TestNSTask

Foundation/NSRegularExpression.swift, TestFoundation/TestNSRegularExpression.swift
Added implementation of class method escapedPatternForString() which simply calls
_CFRegularExpressionCreateEscapedPattern(). Also added two tests to
TestFoundation/TestNSRegularExpression.swift.
=> Adding implementation of NSRegularExpression.escapedPatternForString(_:)

Foundation.xcodeproj/project.pbxproj, Foundation/NSDateFormatter.swift, TestFoundation/TestNSDateFormatter.swift, TestFoundation/main.swift
This PR primarily contains tests, but I also added CF attribute setters. I tried to use a wide variety of dates, but more could be added in the future.
More `NSDateFormatter` work coming in future pull requests.
=> Initial NSDateFormatter tests

Foundation/NSBundle.swift, TestFoundation/TestNSBundle.swift
[SR-794](https://bugs.swift.org/browse/SR-794) reports an issue with `NSBundle.pathForResource()` whereby it returns `nil` instead of the expected resource.
It looks like this is cause because the supplied `subpath` value isn't passed down to the underlying `URLForResource()` call.
I've fixed that and added an implementation of the test case to TestNSBundle. I've done that under the existing `test_URLsForResourcesWithExtension()` test as a separate call and check as its a similar test and reuses the same bundle setup/teardown. I can spin it off as a separate test though if it makes sense.
=> SR-794 pass supplied subpath through to URLForResource rather than nil

Foundation/NSNumberFormatter.swift
[SR 765](https://bugs.swift.org/browse/SR-765) reports that `NSNumberFormatter` is missing an implementation for `stringForObjectValue()`.
I've added an implementation for that which follows the [NSFormatter Class Reference](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSFormatter_Class/index.html#//apple_ref/occ/instm/NSFormatter/stringForObjectValue:) by returning `nil` if the class is incorrect, otherwise returning a formatted string. The formatted string is obtained by calling through to `stringFromNumber()`, which also deals with the localisation of the string.
=> [SR-765] Implement NSNumberFormatter.stringForObjectValue()

TestFoundation/TestNSString.swift
This fixes a build break when building the tests under XCode against a fresh toolchain.
=> Use Swift 3 CFStringBuiltInEncodings values

Foundation/NSURL.swift, Foundation/NSXMLDTD.swift
The Objective-C Foundation's NSURL.absoluteString returns non-optional, but SwiftFoundation's is currently an optional. This makes the APIs consistent between eachother so importing Foundation on either platform works the same with this method.
=> Fix API parity to ObjC Foundation NSURL.absoluteString

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/SwiftRuntime/TargetConditionals.h
These are just some small changes that begin to enable building Foundation on 64-bit arm linux.
=> Generalize trap intrinsic and allow aarch64

CoreFoundation/String.subproj/CFRegularExpression.c, TestFoundation/TestNSRegularExpression.swift
Code changes to fix a false match returned by firstMatchInString().
Also include 35 out of 37 tests from  test_complexRegularExpressions
in TestNSRegularExpression. The two tests currently excluded from 
test_complexRegularExpressions() fail due to another defect @mamabusi 
is working on.
=> Fix a false match bug in NSRegularExpression

Foundation/NSTextCheckingResult.swift, TestFoundation/TestNSRegularExpression.swift
CoreFoundation returns a "not found"  range as {-1, 0}.
This needs to be represented as {NSNotFound, 0} in Foundation.
Included all but four tests from test_complexRegularExpression
in TestNSRegularExpression (the excluded depend on PR 278)
Added four new tests as well.
=> Replace NSNotFound for kCFNotFound in NSRange

Foundation/NSTimeZone.swift, TestFoundation/TestNSTimeZone.swift
This adds an implementation of the following NSTimeZone.init() API:
```swift
public convenience init?(abbreviation: String)
```
The implementation does a lookup of the abbreviation in the CFTimeZoneAbbreviationDictionary to generate a name and, if found, uses that to create a NSTimeZone instance. If no entry is found, we return nil.
I've also added two tests, one to check the negative (invalid abbreviation) case, and one to check the valid case using "AST" (the first entry in the dictionary).
=> Add implementation of NSTimeZone.init() with abbreviation

Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift
The [NSNumber reference](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSNumber_Class/index.html#//apple_ref/occ/instm/NSNumber/descriptionWithLocale:) documents the following two APIs which appear not to be implemented (even as calls to `NSUnimplemented`):
```swift
var stringValue: String { get }
func descriptionWithLocale(_ locale: AnyObject?) -> String
```
Additionally `stringValue()` is described as a call to `descriptionWithLocale(nil)`.
I've therefore implemented `descriptionWithLocal()`, and `stringValue()` as a call through to it.
=> Implement missing stringValue and descriptionWithLocale APIs

Foundation/NSUUID.swift, TestFoundation/TestNSUUID.swift
This pull request should fix [SR-865](https://bugs.swift.org/browse/SR-865).
The `UUIDString` property of `NSUUID` should behave the same as the Objective-C counterpart. As the Objective-C version returns an uppercase string, the Swift version should behave the same.
=> Fix inconsistent UUIDString behavior between ObjC Foundation and Swift Foundation

Foundation/NSDateFormatter.swift, TestFoundation/TestNSDateFormatter.swift
[SR-208](https://bugs.swift.org/browse/SR-208) should be resolved with the additions of this PR and recent commit 89556789cf1003dfa137eec9eed43ed965f3ea74 setting of dateFormat.
In this PR:
- Implemented getters and setters on remaining properties missing them
- Added tests for initial values on NSDateFormatter
- Added tests for setting custom `.dateFormat` values
Also, tests will need PR #285 to actually run.
=> Implement remaining NSDateFormatter attributes, with more tests

Foundation/NSPathUtilities.swift, TestFoundation/TestNSString.swift
This is for [SR-999](https://bugs.swift.org/browse/SR-999) which reports that `stringByAppendingPathExtension()` and `stringByDeletingPathExtension()` are failing to add/remove the 'dot' before the extension.
I've implemented tests that match the examples given in the API spec, along with an additional test including a tilda, and the modified the relevant functions in `NSPathUtilities`.
=> [SR-999] Add dot to NSString.stringByAppendingPathExtension() result

CoreFoundation/URL.subproj/CFURLComponents.c, TestFoundation/TestNSURL.swift
Once you've created a `NSURLComponents` object, setting the `port` value has no effect. This is caused by why looks like a copy/paste issue in `_CFURLComponentsSetPort` where the code is calling `_passwordComponentValid` rather than `_portComponentValid`
I've fixed this, and added a test for the setter. Note that the test case sets the expected string explicitly rather than concatenating the `urlString` and the `port` value. This is because of the issue that PR #296 fixes - when converting the port to a string it currently localises it into 8,080.
=> Fix failure in setter for NSURLComponents.port

CoreFoundation/String.subproj/CFRegularExpression.c, TestFoundation/TestNSRegularExpression.swift
This is the proposed fix for https://bugs.swift.org/browse/SR-1003
The function _CFRegularExpressionEnumerateMatchesInString() walks the text
searching for occurrences of the pattern. For every occurrence, it populates
a CFRange array. If the number of capture groups is not greater than 7, it
uses an array on the stack (instead of mallocing one). However, the total
number of CFRanges inserted is (number of capture groups + 1). The last
insert can corrupt the stack if the number of capture groups is 7 and change the
values of other locals leading to unexplained behaviour.
=> Fix a stack corruption issue in CFRegularExpression (SR-1003)

Foundation/NSString.swift, TestFoundation/TestNSString.swift
[SR-929](https://bugs.swift.org/browse/SR-929) covers the need to implement the following NSString API:
```swift
public convenience init(format: String, locale: AnyObject?, arguments argList: CVaListPointer)
```
This PR adds an implementation that:
- Allows the for `locale` parameter to be a `NSLocale`,  `NSDictionary` or `nil`.
The parameter type is checked, checking `NSLocale` first as its the expected type
- Casts the type to `CFDictionary` for use in `CFString`
Here I've used `unsafeBitCast` as casting to a CFDictionary directly doesn't work on Linux and there doesn't appear to be a "safer" was of casting that works. The underlying functions check to see if the actual type is a `CFLocale` or a `CFDictionary` and handles as appropriate.
- Throws a `fatalError()` for invalid locale …
=> [SR-929] Implement NSString.init() with locale

Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
This implements `NSJSONSerialization`'s `dataWithJSONObject(_:options:)`, providing a JSON serializer and associated tests.  It is RFC 7159 compliant, I hope.
There is another pull request implementing this API, which has been unmerged for some time.  I believe this approach is superior, because
1. It implements the serializer using the same code structure as the existing deserializer.
2. It doesn't use generics unnecessarily.
3. It correctly handles string escaping, as per the JSON spec.
4. It leaves the existing API signature unchanged, so is more interoperable with the existing Objective-C implementation.
5. The handling of pretty-printing is simpler, and also correct.
Feedback wanted please!
=> JSON serializer and tests.

Foundation/NSOrderedSet.swift, TestFoundation/TestNSOrderedSet.swift
Added implementation of reversedObjectEnumeration() (on the lines of objectEnumerator()) and read-only property reversedOrderedSet in the NSOrderedSet class along with a few tests exercising
the same with NSOrderedSet and subclass NSMutableOrderedSet.
=> Implementing reversedObjectEnumeration() and reversedOrderedSet in NSOrderedSet

TestFoundation/TestNSRegularExpression.swift
Uncommenting tests from TestNSRegularExpression which were inadvertently commented out when PR 282 and PR 278 were created.
=> Uncommenting tests from TestNSRegularExpression 

Foundation.xcodeproj/project.pbxproj, Foundation/SwiftFoundation.h
Currently, building `SwiftFoundation.framework` in Xcode generates a couple of distracting warnings. In an attempt to reduce pain points for contributors working on corelibs Foundation and XCTest using Xcode, these changes fix the warnings, so the all targets build without producing any issues.
=> Clean up Xcode warnings

TestFoundation/TestNSNotificationQueue.swift
The tests for `NSNotificationQueue` predate the introduction of swift-corelibs-xctest's own API for asynchronous testing, and instead use a private method in the test case for spinning the run loop and waiting for an event to have occurred. It would be nice to migrate to the built-in XCTest functionality for this.
I have done my best to stress-test the test suite on my machine in both OSX and Linux environments and haven't encountered a single failure, however I do still have a slight concern that this could re-introduce test flakiness because it remove the explicit locking added by @phausler in https://github.com/apple/swift-corelibs-foundation/commit/735d33bfed54157c66f7ae89823d8837643bd902. If it turns out to be problematic, I would consider it to be a shortcoming in XCTest, though, …
=> Use XCTest's async waiting functionality instead of a hand-rolled method

Foundation/NSData.swift, Foundation/NSFileManager.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSPathUtilities.swift, Foundation/NSURL.swift, TestFoundation/TestNSBundle.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSString.swift, TestFoundation/TestUtils.swift
API names of NSFileManager are modified to match with Darwin version. Files modified are NSFileManager.swift and and other files (including TestFoundation) that use NSFileManager APIs
=> Changing NSFileManager API names to match Darwin version

Foundation/NSURLResponse.swift, TestFoundation/TestNSURLResponse.swift, TestFoundation/main.swift
This implements both the trivial attributes (`statusCode` and `allHeaderFields`), and also parses the headers in order to set the following attributes:
```
public var mimeType: String? { get }
public var expectedContentLength: Int64 { get }
public var textEncodingName: String? { get }
public var suggestedFilename: String? { get }
```
Added tests for these.
The
```
public class func localizedStringForStatusCode(statusCode: Int) -> String { NSUnimplemented() }
```
method on `NSHTTPURLResponse` is still unimplemented.
=> Implement NSHTTPURLResponse

Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift
Change code comments to *Swift Documentation Markup*.
Rework how attributes are stored.
Refactor header field code into existingHeaderField().
=> Cleanup NSURLRequest. Implement copy / mutableCopy.

Foundation.xcodeproj/project.pbxproj, Foundation/NSAttributedString.swift, TestFoundation/TestNSAttributedString.swift, TestFoundation/main.swift
Implemented and tested the following methods (and properties):
- `public var string: String`
- `public var length: Int`
- `public init(string str: String)`
- `public init(string str: String, attributes attrs: [String : AnyObject]?)`
- `public init(attributedString attrStr: NSAttributedString)`
The implementation is based on CFAttributedString.
=> Implement basic initializers of NSAttributedString

Foundation/NSRegularExpression.swift, Foundation/NSString.swift, TestFoundation/TestNSRegularExpression.swift
Includes changes to TestNSRegularExpression and a small change to NSString.
=> Changing the NSRegularExpression API to match the Darwin version

Foundation/NSCalendar.swift, Foundation/NSDate.swift, Foundation/NSDateFormatter.swift, Foundation/NSTimeZone.swift, TestFoundation/TestNSDate.swift, TestFoundation/TestNSDateFormatter.swift, TestFoundation/TestNSTimeZone.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apple/swift-corelibs-foundation/325)
=> Changed NSDate, NSTimeZone, NSDateFormatter API to match Darwin version

Foundation/NSData.swift
Fixed it in same way as Darwin/Glibc is imported
`#if os(OSX) || os(iOS)
bytesWritten = Darwin.write(fd, buf.advanced(by: length - bytesRemaining), bytesRemaining)
#elseif os(Linux)
bytesWritten = Glibc.write(fd, buf.advanced(by: length - bytesRemaining), bytesRemaining)
#endif
`
=> Fix NSData to use cross platform write function

Foundation/NSCFString.swift, Foundation/NSCalendar.swift, Foundation/NSData.swift, Foundation/NSHTTPCookie.swift, Foundation/NSJSONSerialization.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSLock.swift, Foundation/NSOperation.swift, Foundation/NSPathUtilities.swift, Foundation/NSRange.swift, Foundation/NSRegularExpression.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSURLResponse.swift, Foundation/NSXMLNode.swift, Foundation/String.swift, TestFoundation/TestNSCharacterSet.swift, TestFoundation/TestNSFileManager.swift
This PR contains adjustments for SE-0065 "A New Model for Collections and Indices".
=> [swift-3-indexing-model] porting Foundation to the new indexing model

Foundation/NSKeyedUnarchiver.swift, Foundation/NSLock.swift, Foundation/NSOperation.swift, Foundation/NSSwiftRuntime.swift, Foundation/String.swift, TestFoundation/TestNSFileManager.swift
Not sure if this change is unwelcome, considering that [proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0049-noescape-autoclosure-type-attrs.md) says:
> The Swift 3 migrator should move these over, and has the information it needs to do a perfect migration in this case.
Anyways the warnings are annoying and I wanted to silence them.
=> fix warnings for SE-0049 (Move @noescape ...)

Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
currently for strings that had spaces at the start, the spaces were ignored during deserialisation process. e.g "{\"title\" : \" hello world!!\" }" would deserialise into ["title" : "hello world!!"] instead of ["title" : " hello world!"] skipping the space at the start of hello world. This was due to `func consumeStructure(ascii: UInt8, input: Index) throws -> Index?` consuming white spaces at the start and end of every structure. The fix is  just to consume the starting whitespace sequence in case of QuotationMark Structure.
=> [swift-corelibs-foundation]-- Fixed JSON Deserialisation of string values with spaces at the start String

Foundation/NSDictionary.swift
-removed nested "if let" statements
-removed explicit casting in favor of conditional casting (discussable)
=> Code improvements in NSDictionary

Foundation/NSHTTPCookie.swift
Updates to NSHTTPCookie
* Fixed setting version from NSHTTPCookieVersion, was NSHTTPCookieSecure
* Fixed string format when setting expires date
* Fixed creating expiresDate from timeInterval. Docs state must be integer.
* Fixed setting discard to match documentation
* Replaced internal struct with private properties, serve the same purpose
* Created internal properties dictionary that is returned by properties get. Closer to Cocoa compatibility
* Added "Created" key and value to properties dictionary for Cocoa compatibility.
The documentation of NSHTTPCookie and the Cocoa implementation of NSHTTPCookie differ. Not sure if it's a bug or if it's proper, yet undocumented behavior.  The question is, do we want to be compatible with Cocoa or more closely follow documentation.
* Certain values …
=> Updates to NSHTTPCookie

Foundation/NSJSONSerialization.swift
`consumeStructure` should be simple with no knowledge of the special
requirements for string parsing. We'll handle it directly in `parseString`
instead.
=> Treat JSON string parsing as a special case

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
This is for [SR-789](https://bugs.swift.org/browse/SR-789) which reports that `NSNumber.description` is providing a localised string whereas it didn't do so previously.
In order to be behaviour compatible I've made a slight modification to the existing implementation to use a number formatter style of `kCFNumberFormatterNoStyle` rather than `kCFNumberFormatterDecimalStyle`.
At the same time I've done some refactoring to improve the delegation between `description` and `descriptionWithLocale()` as suggested in PR #277 and added tests for both `description` and `descriptionWithLocale()`
=> [SR-789] Remove localization of NSNumber.description

Foundation/NSOperation.swift, TestFoundation/TestNSOperationQueue.swift, TestFoundation/main.swift
NSOperationQueue maintain different queues based on priority and a queue 'all' to maintain operations of all priorities. 
NSOperationQueue.operationCount is nothing but the no.of operations in 'all' queue. However, addOperation() doesn't add Operations to 'all' queue and thereby NSOperationQueue.operationCount is always 0.
Currently, there is no testsuite for NSOperationQueue. I've added test case for this scenario (partially, as it would require Dispatch support to add more scenarios to it).
=> NSOperationQueue.operationCount always return 0

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/RunLoop.subproj/CFRunLoop.c, build.py
This makes some minor changes that gets us closer to having Dispatch built and included in CoreFoundation and Foundation, including:
* Switching CFRunLoop to use the new `4CF` functions in libdispatch  
Note that these APIs are only available in the `experimental/foundation' branch of libdispatch.
* Adding a basic implementation for `pthread_main_np()`  
There isn't an implementation in Glibc and there isn't a shim today. We should potentially move the implementation to the Glibc overlay. 
* Updated the build scripts to include Dispatch in Foundation as well as CoreFoundation  
This is still commented out as there's a number of compile errors in NSOperation and the incoming NSURLSession code - we should fix those up before uncommenting this code.
The changes should allow anyone to build a …
=> Further integration of Dispatch into Foundation

CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h, Foundation.xcodeproj/project.pbxproj, Foundation/NSAttributedString.swift, TestFoundation/TestNSAttributedString.swift, TestFoundation/main.swift
Different from #297, this time I'm trying to implement the NSAttributedString to be a is-a relationship to CFAttributedString.
=> Basic implementations of NSAttributedString

Foundation/NSOperation.swift
After https://github.com/apple/swift-corelibs-foundation/pull/340,  NSOperationQueue.operationCount is decremented as soon as task is dispatched for execution. This is because dequeue() method is modified to delete operation from 'all' queue.
=> fix NSOperationQueue to retain operation in 'all' queue once it is dispatched

Foundation/NSBundle.swift, Foundation/NSData.swift, Foundation/NSDateFormatter.swift, Foundation/NSFileManager.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSNumber.swift, Foundation/NSNumberFormatter.swift, Foundation/NSString.swift, Foundation/NSTask.swift, Foundation/NSThread.swift, Foundation/NSTimer.swift, Foundation/NSURL.swift, Foundation/NSXMLNode.swift, Foundation/NSXMLParser.swift, TestFoundation/TestNSURL.swift, Tools/plutil/main.swift
This commit fixes up swift-corelibs-foundation for when SE-0054 is merged into swift master. See apple/swift#2322. The two PRs are to be merged in conjunction.
=> Fix up swift-corelibs-foundation for abolition of IUO type in SE-0054

Foundation/NSTask.swift, TestFoundation/TestNSTask.swift
Currently the environment is deallocated before the task is launched. This results in memory being overwritten, and a corrupt environment. @ddunbar suggested moving the `defer` up a scope. I've added a few tests to verify the correctness of the environment.
=> [NSTask] Cleanup environment after task is launched

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
=> NSFileManager.moveItem - destination path should not exist before moving

Foundation/NSTask.swift, TestFoundation/TestNSTask.swift
* Helper function to reduce TestNSTask test case duplication
* Fix issue capturing stdout and stderr to same pipe + test case
* Pass complete path as argv[0]  
This allows executables to derive their own absolute path. SwiftPM relies on this value to derive the compiler path and fake toolchain path.
=> [NSTask] Change argv[0] to full path + fixes combining stdout+stderr

lib/target.py
This change expands on the work by @hpux735 to support ARMv6, not just ARMv7.
While making the change I noticed the ArchSubType class (which already has a bunch of ARM architectures listed).  That might be a more robust change...but ArchSubType doesn't look like its used anywhere, so I did this quicker solution that I know works.
Thoughts on whether it is worth it to try an implementation with the `arm` ArchType, and manage the v6 or v7 in the `ArchSubType`?  It makes things more complicated (have to add a `subarch` to `Target`, etc), so maybe better just use ArchType only (as I have done here)?
=> Adding support for ARMv6 on linux

build.py
Add the Dispatch overlay to the Foundation compile flags so that Foundation can access the dispatch types.
This is still commented out until we fix a number of compile errors that occur in NSOperation and NSURLSession on Linux.
=> Make Dispatch overlay available to Foundation

Foundation/NSOperation.swift, TestFoundation/TestNSOperationQueue.swift
Recreate:
----------------------------------------------------------------------------------------------------
let operation1 : NSBlockOperation = NSBlockOperation (block: {
sleep(1)
print("Operation1")
})
let operation2 : NSBlockOperation = NSBlockOperation (block: {
sleep(1)
print("Operation2”)
})
var operations = [NSOperation]()
operations.append(operation1)
operations.append(operation2)
let queue = NSOperationQueue()
queue.maxConcurrentOperationCount = 1
queue.addOperations(operations, waitUntilFinished: true)
----------------------------------------------------------------------------------------------------
Above code was tested with OpenSource Foundation on Mac.
=> Creation of a serial queue in NSOperationQueue fails on setting property maxConcurrentOperationCount to "1"

CoreFoundation/Stream.subproj/CFStream.c
The use of QOS isn't supported on Linux, so needs to be wrapped in a guard.
=> Remove use of pthread qos on Linux

CoreFoundation/Base.subproj/CFInternal.h
The two cases are identical.  Merge them to avoid the unnecessary duplication.
=> Base: merge two identical CPP cases

CoreFoundation/Collections.subproj/CFStorage.c
`__restrict` is the reserved extension.  It avoids the need for the use of the
preprocesor on Windows, but has the same results on compilers which support
restrict (though, some like MSVC support __restrict though not restrict).
=> CFStorage: use the reserved spelling of restrict

Foundation/NSGeometry.swift
Apply fixit for '_toBitPattern()' deprecation.  NFC.
=> NSGeometry: update accessors

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSOperation.swift
`NSOperation.currentQueue()` makes a call to `pthread_main_np()`, which isn't supported on Linux. There's already a shim in CoreFoundation that implements the function under `_CFIsMainThread()`, so this PR:
1. Externalizes `_CFIsMainThread()`
2. Imports `CoreFoundation` and creates a `pthread_main_np` function that calls it
The implementation of the `pthread_main_np()` function in `NSOperation` is done as a top level function - that's probably not the right thing to do, but it allows it to be groups with the import of `CoreFoundation`, which is only required to expose `_CFIsMainThread()`. This way its a little more clear why the function is there, and makes it easier to clean up the code if we implement the `pthread_main_np()` shim a better way.
=> Use _CFIsMainThread as a shim for pthread_main_np on Linux

Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSFileManager.swift, Foundation/NSGeometry.swift, Foundation/NSIndexSet.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSLock.swift, Foundation/NSNumber.swift, Foundation/NSPathUtilities.swift, Foundation/NSRange.swift, Foundation/NSString.swift, Foundation/NSThread.swift, Foundation/NSURL.swift, Foundation/NSXMLParser.swift
This just cleans up a set of unused-return-value warnings in the Foundation
implementation.  NFC.
=> Foundation: clear up some unused return value warnings

Foundation/NSString.swift, Foundation/String.swift, TestFoundation/TestNSString.swift
Major work in terms of api refactoring of NSString to align with Darwin version was done as part of https://github.com/apple/swift-corelibs-foundation/pull/332. However below API's got missed.
init(contentsOfURL url: NSURL, encoding enc: UInt)
init(contentsOfURL url: NSURL, usedEncoding enc: UnsafeMutablePointer<UInt>?)
This PR updates above api's to match Darwin version..
=> change NSString(contentsOf:encoding:) to align with Darwin version

CoreFoundation/Base.subproj/CFBase.c, CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Collections.subproj/CFArray.c, CoreFoundation/Collections.subproj/CFBag.c, CoreFoundation/Collections.subproj/CFBinaryHeap.c, CoreFoundation/Collections.subproj/CFBitVector.c, CoreFoundation/Collections.subproj/CFData.c, CoreFoundation/Collections.subproj/CFDictionary.c, CoreFoundation/Collections.subproj/CFSet.c, CoreFoundation/Collections.subproj/CFTree.c, CoreFoundation/Locale.subproj/CFDateFormatter.c, CoreFoundation/Locale.subproj/CFNumberFormatter.c, CoreFoundation/NumberDate.subproj/CFNumber.c, CoreFoundation/Parsing.subproj/CFPropertyList.c, CoreFoundation/Parsing.subproj/CFXMLNode.c, CoreFoundation/Parsing.subproj/CFXMLParser.c, CoreFoundation/Parsing.subproj/CFXMLTree.c, CoreFoundation/Preferences.subproj/CFApplicationPreferences.c, CoreFoundation/Preferences.subproj/CFPreferences.c, CoreFoundation/RunLoop.subproj/CFMachPort.c, CoreFoundation/RunLoop.subproj/CFMessagePort.c, CoreFoundation/RunLoop.subproj/CFRunLoop.c, CoreFoundation/RunLoop.subproj/CFSocket.c, CoreFoundation/String.subproj/CFAttributedString.c, CoreFoundation/String.subproj/CFCharacterSet.c, CoreFoundation/String.subproj/CFString.c, CoreFoundation/URL.subproj/CFURL.c
Rather than defining the various flavours of CFAssert requiring the user to
count the number of substituted parameters, collapse them to CFAssert.  The C99
variadic macro expansion permits us to ensure that the arguments are all
passable.  At the same time, the compiler validation of the printf conversion
will still catch the missing arguments (which could still be possible to have in
the previous case by just using the wrong count).
=> CoreFoundation: use C99 macro expansion

CoreFoundation/Base.subproj/CFInternal.h
HALT is used in various places without a check for the target.  There is nothing
which is architecture specific.  Remove the unnecessary architecture check.
=> Base: always define HALT

CoreFoundation/Base.subproj/CFInternal.h
https://github.com/apple/swift-corelibs-foundation/pull/379 simplified the usage of the `CFAssert` macro, however it introduced a regression when Foundation is built in the `DEBUG` configuration such that `CFAssert` can no longer be used if no variable arguments are passed after the assertion description, because a trailing comma ends up being produced once the macro is expanded. This is causing build failures for the Corelibs XCTest CI on OS X.
Using `##__VA_ARGS__` (already being used elsewhere in this CoreFoundation) invokes compiler magic which removes the trailing comma in this situation.
=> Fix the CFAssert macro when used with no format string parameters

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/SwiftRuntime/TargetConditionals.h, CoreFoundation/String.subproj/CFString.h, CoreFoundation/String.subproj/CFUnicodeData.S, CoreFoundation/StringEncodings.subproj/CFUniChar.c, Foundation/NSRange.swift, build.py, lib/target.py
- Add initial support for Linux on IBM z Systems
- Fix endianess issues in CFString (https://bugs.swift.org/browse/SR-1548)
=> Support Linux on z

Foundation.xcodeproj/project.pbxproj, Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme
Currently when building the `TestFoundation` scheme in Xcode with a clean build directory, the build fails because it attempts to build `SwiftXCTest` before `SwiftFoundation`. This fixes the build order in the scheme.
=> Fix TestFoundation build order issue in Xcode 

Foundation/NSAttributedString.swift, TestFoundation/TestNSAttributedString.swift, TestFoundation/main.swift
This pull request contains the following NSAttributedString and NSMutableAttributedString method implementations:
- `attributesAtIndex(_ location: Int, longestEffectiveRange range: NSRangePointer, inRange rangeLimit: NSRange) -> [String : AnyObject]`
- `attribute(_ attrName: String, atIndex location: Int, longestEffectiveRange range: NSRangePointer, inRange rangeLimit: NSRange) -> AnyObject?`
- `init(string str: String)`
- `mutableString: NSMutableString`
- `addAttribute(_ name: String, value: AnyObject, range: NSRange)`
=> Implement some methods for NSAttributedString and NSMutableAttributedString

Foundation/NSTextCheckingResult.swift, TestFoundation/TestNSTextCheckingResult.swift, TestFoundation/main.swift
Also added test case to TestFoundation. 
Sample output from the implementation:
If Range(5,2)
then: 
.resultByAdjustingRangesWithOffset(5) -> Range(10,2)
.resultByAdjustingRangesWithOffset(-3) -> Range(2,2)
.resultByAdjustingRangesWithOffset(0) -> Range(5,2)
.resultByAdjustingRangesWithOffset(-10) -> NSError
.resultByAdjustingRangesWithOffset(NSNotFound) -> NSError
If Range(NSNotFound,0)
.resultByAdjustingRangesWithOffset(5) -> Range(NSNotFound,0)
.resultByAdjustingRangesWithOffset(-3) -> Range(NSNotFound,0)
.resultByAdjustingRangesWithOffset(0) -> Range(NSNotFound,0)
=> Implementation of the api 'resultByAdjustingRangesWithOffset' in NSTestCheckingResult

Foundation.xcodeproj/project.pbxproj, TestFoundation/TestNSTextCheckingResult.swift
I've also reordered some of the files in the Tests group within TestFoundation to keep the alphabetical order consistent.
@modocache Also, somewhat unrelated, there are a lot of unused value warnings when running these tests. Is this something we don't usually worry about?
=> Add TestNSTextCheckingResult file to Xcode project

build.py
When Dispatch is added into the toolchain it adds the libdispatch library into the `/usr/lib/swift/linux` directory, which is where the other libraries such as libFoundation are located.
Applications built using `swiftc` have `/usr/lib/swift/linux` added to their library search path, so anything using Dispatch directly can find the library at runtime and runs correctly. The Foundation library however doesn't, so fails to find Dispatch at runtime if its not added to the LD_LIBRARY_PATH.
This PR adds a RPATH of ORIGIN to the Foundation library so that it can link to Dispatch at runtime without the need for the path to be explicitly set using LD_LIBRARY_PATH.
=> Add rpath of ORIGIN on Linux in order to pick up libdispatch

lib/script.py
`./configure -DFOO=BAR -DBAZ=QUX` used to emit `ninja.build` as
```
FOO=BARBAZ=QUX
VERBOSE_FLAGS =
...
```
This PR fix it to:
```
FOO=BAR
BAZ=QUX
VERBOSE_FLAGS =
...
```
=> Add new lines for each variable definition in build.ninja

build.py, configure, lib/config.py, lib/script.py
Support for cross-compiling:
- Replace `icu-config` with `pkg-config`. Even ICU [recommends](http://userguide.icu-project.org/howtouseicu) to use pkg-config these days.
- Include sysroot in include directories
- Added `linker` flag, which gets passed through as the `-fuse-ld` option (so it accepts either a linker name or absolute path, as clang does)
- Added `resource-dir` flag to swift. Similarly to https://github.com/apple/swift/commit/f7353a73ceb2e23af1404155dc0db85adc40200b
- Check for presence of binaries in the toolchain folder before appending `bin`. Our toolchain might just be a folder full of binaries.
=> Support cross-compiling Foundation

Foundation/NSLocale.swift, TestFoundation/TestNSLocale.swift
Only UnImplemented api is copy(). This PR added implementation for the same.
=> add missing implementation for NSLocale

Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSTimeZone.swift
Use `guard` statements to exit early with `NSRequiresConcreteImplementation()`. This approach is more succinct, and has the added safety of `guard` requiring a transfer of program control.
=> Guard clauses for NSRequiresConcreteImplementation

CoreFoundation/Base.subproj/CFBase.c, CoreFoundation/Base.subproj/CFBase.h, CoreFoundation/Base.subproj/CFFileUtilities.c, CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Collections.subproj/CFData.c, CoreFoundation/PlugIn.subproj/CFBundle.c, CoreFoundation/Preferences.subproj/CFApplicationPreferences.c, CoreFoundation/Preferences.subproj/CFPreferences.c, CoreFoundation/Stream.subproj/CFStream.c, CoreFoundation/String.subproj/CFString.c, CoreFoundation/StringEncodings.subproj/CFStringEncodingConverter.c, CoreFoundation/StringEncodings.subproj/CFUniChar.c, CoreFoundation/StringEncodings.subproj/CFUnicodeDecomposition.c, CoreFoundation/StringEncodings.subproj/CFUnicodePrecomposition.c
This adjusts the headers and the definitions to ensure that the export
decorations match.  This enables building CoreFoundation with hidden visibility
by default on Linux targets.
=> CoreFoundation: correct export attributes

build.py
This adds a further update to build.py to make the libdispatch libraries available to TestFoundation.
This is done using adding the libdispatch build path to `LD_LIBRARY_PATH`, extending the approach that's already used to provide access to the XCTest libraries during build time.
=> Enable libdispatch usage in TestFoundation

Foundation/NSThread.swift
Prior to `pthread_create` call there is an opportunity to set the thread's attributes with `pthread_attr_set*` routines.  This PR sets both the scope of the thread to SYSTEM and the detached state to CREATE_DETACHED which allows the thread to exit and cleanup its resources upon `pthread_exit` without waiting for a `pthread_join`.
=> SR-1908 Set detach state on creation to DETACHED

build.py
@parkera @phausler This uncomments the block that configures the use of libdispatch by Foundation in build.py, activating the `__HAS_DISPATCH__` guard.
The block includes guards to check that libdispatch is being built, which means that the toolchain builds in the CI environment won't be affected by this yet. 
It will affect the libdispatch CI build, which also builds Foundation, XCTest and Swift PM, so we'll start to exercise the use of libdispatch via TestFoundation and the XCTest and Swift PM unit tests.
If the libdispatch CI builds run clean/stable, we'll then look at adding libdispatch into the toolchain builds via the "buildbot_linux" preset.
=> Activate the ability to integrate libdispatch

Foundation/NSBundle.swift, TestFoundation/TestNSBundle.swift
Also includes the fix for segmentation fault issue when the NSBundle is created with an invalid path
=> Implementing preflight(),loadWithErrorin NSBundle

Foundation/NSHTTPCookie.swift, TestFoundation/TestNSHTTPCookie.swift
This is for an initial implementaion of HTTPCookie.cookies(withResponseHeaderFields:forURL:).
In addition to the contributed unit tests, I have also tested this code against cookies
returned by some of the twenty most popular websites. 
Kindly review and provide feedback.
=> Implementation of HTTPCookie.cookies(withResponseHeaderFields:forURL:)

TestFoundation/TestNSNotificationQueue.swift
rdar://problem/26611147 Swift names for… expectation APIs don't match API guidelines
This reacts to swift-corelibs-xctest pull request 129. That needs to be merged at the same time as this.
=> Update expectation based API names for API guidelines

TestFoundation/TestNSAffineTransform.swift
Ground work for [SE-0060](https://github.com/apple/swift-evolution/blob/master/proposals/0060-defaulted-parameter-order.md).
[SE-0060] enforces order of arguments regardless they have default arguments.
This PR eliminates existing out-of-order arguments in `swift-corelibs-foundation` source tree.
=> Prepare for SE-0060: Eliminiate existing out-of-order arguments

CoreFoundation/Collections.subproj/CFData.c
This is fix for bug https://bugs.swift.org/browse/SR-1552
Memory held by NSData._bytes never gets reclaimed as __kCFDontDeallocate is set on NSData always.
=> [SR-1552] Fix memory leak in NSMutableData and NSData

Foundation/NSData.swift, TestFoundation/TestNSData.swift
NSMutableData(length:) allocates a memory of 'length' bytes and initialises NSMutableData with the same malloced bytes as buffer. And, capacity is 16 (default). And, any further appends to NSMutableData actually happens outside malloced region corrupting the memory next to it.
Fix is to avoid reusing malloced region as buffer. Instead, create new buffer with capacity and copy contents of malloced region into the buffer and free malloced region after copy.
=> Fix memory corruption with NSMutableData(length:)

Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
Implementation for NSCalendar.copy() is required to use API NSCalendar.components(in timezone:fromDate:)
since NSCalendar is mutable, we cannot simply return 'null'. Create new copy, update fields like 'locale', 'timezone' and return copy.
=> implementation for NSCalendar.copy()

Foundation/NSURL.swift, TestFoundation/TestNSURL.swift
This PR has below implementations along with testcase
NSURL.copyWithZone()
NSURLQueryItem.copyWithZone()
=> Add implementation for NSURL copy()

Foundation/NSURL.swift, TestFoundation/TestNSURL.swift
Implementation for NSURL.standardizedURL and NSURL.filePathURL is added and enabled tests for NSURL.standardizedURL in TestNSURL.swift
=> implementation for NSURL.standardizedURL and NSURL.filePathURL properties

build.py
PR#424 introduced the use of the `LIBS_DIRS` variable as part of the configuration for TestFoundation. Unfortunately as a local variable it doesn't get passed down to ninja.build.
Adding `LIBS_DIRS` to the configuration dictionary adds it to ninja.build so that `ninja test` works correctly.
=> Fix use of LIBS_DIRS in build.ninja file for ninja test

Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
Third attempt to match Darwin. Please excuse my inadvertence.
=> [NSCalendar] Updated to match Darwin version

Foundation/Date.swift
Fixed some typos found in Date.swift.
=> Fix some typos in Date.swift

Foundation/IndexPath.swift, Foundation/NSDictionary.swift, Foundation/NSNumber.swift, Foundation/NSObject.swift, Foundation/NSOrderedSet.swift, Foundation/NSString.swift
In accordance with SE-0115 and apple/swift#3474.
=> Rename *LiteralConvertible conformances to ExpressibleBy*Literal

CoreFoundation/RunLoop.subproj/CFRunLoop.c, Foundation/NSOperation.swift, build.py
Swift code compiles against current master branch of Dispatch,
with Swift3 wrapping overlay, but doesn't link
(need to port dispatch_get_main_queue_eventfd_4CF
and dispatch_main_queue_drain_4CF from experimental/foundation
to master).
Note: this pull request is not ready to merge; posting just for documentation and to have it available
when we are ready to merge.
=> WIP on port to Swift3 Dispatch API

Foundation/IndexSet.swift, TestFoundation/TestNSIndexSet.swift
Earlier in the week, I opened a [PR](https://github.com/apple/swift/pull/3486) to fix IndexSet intersection and symmetric difference in the apple/swift repo. I guess it should be fixed here too. I've ported over the salient tests as well.
=> Fix IndexSet intersection and symmetric difference

Foundation/NSArray.swift, Foundation/NSCFString.swift, Foundation/NSDictionary.swift, Foundation/NSFileManager.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSURL.swift
This depends on swift PR:
https://github.com/apple/swift/pull/3601
=> Update for SE-0107, rename initialize(with:) to initialize(to:).

Foundation/NSArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSCoder.swift, Foundation/NSConcreteValue.swift, Foundation/NSDictionary.swift, Foundation/NSFileHandle.swift, Foundation/NSFileManager.swift, Foundation/NSHost.swift, Foundation/NSJSONSerialization.swift, Foundation/NSKeyedCoderOldStyleArray.swift, Foundation/NSLock.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSTask.swift, Foundation/NSURL.swift, Foundation/NSUUID.swift, TestFoundation/TestNSKeyedArchiver.swift
Depends on Swift PR:
https://github.com/apple/swift/pull/3608
=> Update for SE-0107: UnsafeRawPointer, rename allocate/deallocate.

Foundation/URL.swift
Update swift-corelibs-foundation to syntax introduced from [SE-0095](https://bugs.swift.org/browse/SR-1938), merge once [the compiler support is merged](https://github.com/apple/swift/pull/3293).
=> Update protocol compositions to SE-0095 syntax

Foundation/NSProcessInfo.swift
As part of [SE-0086](https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md), we decided to rename the `NSTask` class to `Process`. This PR changes `Swift.Process` to `Swift.CommandLine` to make that possible.
See [Swift PR 3598](https://github.com/apple/swift/pull/3598).
=> Rename Process to CommandLine

Foundation/NSCalendar.swift
These operators will be removed as part of SE-0121 and apple/swift#3637.
This use site was discovered by CI: https://ci.swift.org/job/swift-PR-Linux/2900/console
=> [SE-0121] remove uses of optional comparison operators

Foundation/NSKeyedArchiver.swift
_Note: I have not had a chance to test this fix, I just noticed it whilst glancing through the code recently._
_writeXMLData() in NSKeyedArchiver invokes CFPropertyListWrite() with kCFPropertyListOpenStepFormat, which not only does not make sense (given the name of the calling function) but will also assert fail in CF. Presumably it should be changed to kCFPropertyListXMLFormat_v1_0.
=> [SR-2133] archive to streams in XML, not OpenStep, format

Foundation/NSXMLNode.swift
Necessary for https://github.com/apple/swift/pull/3637. cc @parkera
=> Fix use of optional pattern

Foundation/IndexSet.swift
Found another. These things are out to get me.  for https://github.com/apple/swift/pull/3637
=> [SE-0121] remove use of optional comparison operators

Foundation/Boxing.swift, Foundation/Data.swift, Foundation/IndexPath.swift, Foundation/IndexSet.swift, Foundation/NSAttributedString.swift, Foundation/NSGeometry.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSNotification.swift, Foundation/NSOrderedSet.swift, Foundation/NSTask.swift, Foundation/NSURL.swift, Foundation/NSXMLNode.swift, Foundation/NSXMLParser.swift, Foundation/String.swift, Foundation/URL.swift, Foundation/URLComponents.swift, Foundation/URLRequest.swift
[SE-0025](https://github.com/apple/swift-evolution/blob/master/proposals/0025-scoped-access-level.md) makes `private` restrict access to a lexical scope; the Swift 2 behavior is now named `fileprivate`. At the time of this pull request, the compiler treats both `private` and `fileprivate` as having `fileprivate` semantics, but that will soon change.
Supersedes #413; the latest amendment to SE-0025 permits some accesses that the original model (or at least our interpretation of it) would have forbidden. This was done by hand, so it's possible I missed a few cases, but it's at least a smaller diff.
=> Update for SE-0025 ('private' and 'fileprivate')

Foundation/Boxing.swift, Foundation/IndexSet.swift, Foundation/URLRequest.swift
The API calls to `isUniquelyReferencedNonObjC` need to be replace by the new API call `isKnownUniquelyReferenced `.
This needs to be merge in sync with the stdlib changes for SE-0125 in apple/swift#3638
=> Changes for SE-0125: Remove NonObjectiveCBase and isUniquelyReferenced

Foundation/NSAttributedString.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSURLRequest.swift, Foundation/NSURLResponse.swift, Foundation/Unit.swift
Since I didn't finish the implementation of [SE-0025](https://github.com/apple/swift-evolution/blob/master/proposals/0025-scoped-access-level.md) quite fast enough to avoid these creeping in. This time I have a real implementation in hand, so no further changes should be necessary.
(Some of the diffs actually change what I did in #445. I don't think these changes should strictly be necessary in the model—i.e. there's still bugs in my implementation—but I don't want to block landing the main feature and flipping the switch.)
=> A few more 'fileprivate's for SE-0025.

Foundation/NSCFString.swift, Foundation/NSNotification.swift, Foundation/NSObject.swift, Foundation/NSOperation.swift, Foundation/NSURLResponse.swift
Use Unmanaged.passUnretained(x).toOpaque() instead.
These changes are due to the [SE-0127](https://github.com/apple/swift-evolution/blob/master/proposals/0127-cleaning-up-stdlib-ptr-buffer.md)
=> Migrate from the removed unsafeAddress(of:) API.

Foundation/NSCalendar.swift, Foundation/NSPropertyList.swift, Foundation/NSThread.swift
Groundwork for removing withUnsafe[Mutable]Pointers from stdlib.
=> [SE-0127] Remove calls to withUnsafe[Mutable]Pointers

Foundation/DateInterval.swift, Foundation/NSArray.swift, Foundation/NSAttributedString.swift, Foundation/NSBundle.swift, Foundation/NSCalendar.swift, Foundation/NSCoder.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSDateFormatter.swift, Foundation/NSDictionary.swift, Foundation/NSFileManager.swift, Foundation/NSKeyedCoderOldStyleArray.swift, Foundation/NSLock.swift, Foundation/NSNumber.swift, Foundation/NSNumberFormatter.swift, Foundation/NSPropertyList.swift, Foundation/NSScanner.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSThread.swift, Foundation/NSTimer.swift, TestFoundation/TestNSPropertyList.swift
SR-1937
rdar://problem/26529498
=> [SE-0127] changes to withUnsafe[Mutable]Pointer

Foundation/NSArray.swift, Foundation/NSData.swift, Foundation/NSHTTPCookie.swift, Foundation/NSJSONSerialization.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift
This silences compiler warnings that occur in the latest development snapshot of Swift.
=> Silence warnings from SE-0099

TestFoundation/TestNSXMLParser.swift
Needs to be committed simultaneously with apple/swift PR implementing SE-0134.
=> Use utf8CString instead of nulTerminatedUTF8

Foundation/Unit.swift
Members satisfying protocol requirements cannot be private, since they are necessarily available to call from outside the type.
=> More updates for SE-0025 ('fileprivate' and 'private')

CoreFoundation/Base.subproj/CFAsmMacros.h, CoreFoundation/String.subproj/CFCharacterSetData.S, CoreFoundation/String.subproj/CFUniCharPropertyDatabase.S, CoreFoundation/String.subproj/CFUnicodeData.S, Foundation.xcodeproj/project.pbxproj, build.py, lib/phases.py
This ensures that we get the user label prefix correct for the references to the
symbol in the rest of CoreFoundation.
=> Strings: make the assembly slightly more portable

Foundation/NSUUID.swift, TestFoundation/TestNSBundle.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSJSONSerialization.swift, TestFoundation/TestNSKeyedUnarchiver.swift, TestFoundation/TestNSStream.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSUUID.swift
=> update NSUUID.UUIDString to uuidString to match Darwin version

Foundation/Data.swift, Foundation/DateInterval.swift, Foundation/IndexPath.swift, Foundation/NSArray.swift, Foundation/NSCFString.swift, Foundation/NSCoder.swift, Foundation/NSGeometry.swift, Foundation/NSHost.swift, Foundation/NSNumber.swift, Foundation/NSObjCRuntime.swift, Foundation/NSRange.swift, Foundation/NSSwiftRuntime.swift
Depends on https://github.com/apple/swift/pull/3854
[SE-0101](https://github.com/apple/swift-evolution/blob/master/proposals/0101-standardizing-sizeof-naming.md) removes `sizeof`, `sizeofValue` and related functions from the stdlib.
This PR is migrating them to newly introduced `MemoryLayout<T>` values.
=> [SE-0101] Migration

Foundation/Measurement.swift, Foundation/NSArray.swift, Foundation/NSCharacterSet.swift, Foundation/NSData.swift, Foundation/NSDictionary.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSNotification.swift, Foundation/NSNumber.swift, Foundation/NSObject.swift, Foundation/NSOrderedSet.swift, Foundation/NSPropertyList.swift, Foundation/NSSet.swift, Foundation/NSSpecialValue.swift, Foundation/NSString.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSTimeZone.swift, Foundation/NSURL.swift, Foundation/NSURLRequest.swift, Foundation/NSURLResponse.swift, Foundation/NSValue.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSDictionary.swift, TestFoundation/TestNSKeyedArchiver.swift, TestFoundation/TestNSSet.swift, Tools/plutil/main.swift
This can go in any time after apple/swift#3878.
=> Update for SE-0096

Foundation/NSRegularExpression.swift
Fixes some instances of the stop pointer being rebound in the migration to RawPointer.
=> Fix NSRegularExpression on OS X

Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSError.swift, Foundation/NSIndexSet.swift, Foundation/NSJSONSerialization.swift, Foundation/NSXMLNode.swift, Foundation/NSXMLParser.swift, TestFoundation/TestNSCompoundPredicate.swift
Reverts apple/swift-corelibs-foundation#497. The changes to higher-order functions are not correct. See apple/swift#3922.
=> Revert "Updates for SE-0110 Part I"

Foundation/NSData.swift, Foundation/NSFileManager.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSPathUtilities.swift, Foundation/NSTask.swift, Foundation/NSURL.swift, TestFoundation/TestNSBundle.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSJSONSerialization.swift, TestFoundation/TestNSStream.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSURL.swift, TestFoundation/TestUtils.swift
to match Darwin version as of Xcode 8
=> change FileManager.default() class function to static let

Foundation/ExtraStringAPIs.swift, TestFoundation/TestNSString.swift
Ranges of String.UTF16View.Index have negative count 
Resolving bug number: 1988 (https://bugs.swift.org/browse/SR-1988)
=> [SR-1988] Ranges of String.UTF16View.Index have negative count

Foundation/NSHTTPCookie.swift, TestFoundation/TestNSHTTPCookie.swift
As mentioned in https://developer.apple.com/library/ios/qa/qa1480/_index.html, the correct locale to use when parsing "Internet-style dates" is "en_US_POSIX", which is strongly specified, and date- and time-invariant. We should *not* be defaulting to using the user's current locale, which is what DateFormatter currently does.
This fix also side-steps an issue where the test and cookie expiration parsing were failing on macOS because the bundled version of CFLite defaults to a locale identifier of "", failing to parse the "MMM" format specifier. This test did not fail on Linux or on the regular CoreFoundation project because on those platforms, CFDateFormatter defaults to a locale of "en_US" (still wrong, but it works); here, a locale of "" caused the failing test. A fix for this incorrect …
=> Sets correct locale for date parsing in HTTPCookie

Foundation/Boxing.swift, Foundation/IndexPath.swift, Foundation/IndexSet.swift, Foundation/NSCoder.swift, Foundation/NSData.swift, Foundation/NSEnumerator.swift, Foundation/NSError.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift
Apply the fix-its from the compiler to adopt the new `where` clause syntax.
=> Move where clauses to end to adjust to new syntax

Foundation/NSURLCache.swift
`CachedURLResponse`'s `userInfo` dictionary re-typed `[NSObject : AnyObject]` → `[AnyHashable : Any]`
=> Foundation API Conformance Update: CachedURLResponse

Foundation/NSDecimal.swift, Foundation/NSDecimalNumber.swift
* Move `Decimal.RoundingMode` and `Decimal.CalculationError` → `NSDecimalNumber.RoundingMode` and `NSDecimalNumber.CalculationError`
* Add unimplemented `Decimal` API to match Foundation
* Add `NSExceptionName` type and move raw exception names to be instances of that type
* `open class func zero() -> NSDecimalNumber` and co → `open class var zero: NSDecimalNumber`
* `NSDecimalNumberBehavior`'s default behavior getter and setter → `open class var defaultBehavior`
* `NSDecimalNumberHandler`'s `open class func defaultDecimalNumberHandler()` → `open class func default()`
=> Foundation API Conformance Update: Decimal/NSDecimalNumber

Foundation/CharacterSet.swift, Foundation/NSAffineTransform.swift, Foundation/NSCFCharacterSet.swift, Foundation/NSCharacterSet.swift, Foundation/NSHTTPCookie.swift, Foundation/NSScanner.swift, Foundation/NSString.swift, TestFoundation/TestNSAffineTransform.swift
Does the following:
1. brings AffineTransform value type over (changing name of previous struct)
2. de-NS's NSAffineTransform
3. apply new naming guidelines to NSAffineTransform
4. add hash tests
5. profit
=> Swift 3: Value Types and Naming

Foundation/CharacterSet.swift, Foundation/NSAffineTransform.swift, Foundation/NSCFCharacterSet.swift, Foundation/NSCharacterSet.swift, Foundation/NSHTTPCookie.swift, Foundation/NSScanner.swift, Foundation/NSString.swift, TestFoundation/TestNSAffineTransform.swift
Reverts apple/swift-corelibs-foundation#508. It broke on Linux.
=> Revert "Swift 3: Value Types and Naming"

CoreFoundation/Locale.subproj/CFLocale.c, CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/NSDateFormatter.swift
The root cause of the problem is missing logic in the CFTimeZone.c file
to handle "GMT" (no offset) as a time zone, which Darwin Foundation
handles. Also, CFLocale.c was using an empty string for the current locale, due
to not checking the AppleLocale preference. For now, we hard code en_US
as the current locale, although obviously this should be fixed to use
CFPreferences if possible.
=> Additional fixes for macOS test failure in TestHTTPCookie.

CoreFoundation/Locale.subproj/CFLocale.c, CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/NSDateFormatter.swift
Reverts apple/swift-corelibs-foundation#523
This caused a test failure on Linux that I'll need to investigate further.
=> Revert "Additional fixes for macOS test failure in TestHTTPCookie."

Foundation/IndexPath.swift, Foundation/IndexSet.swift, Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSIndexPath.swift, Foundation/NSIndexSet.swift, Foundation/NSObjCRuntime.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, TestFoundation/TestNSIndexSet.swift
* Integrate `IndexPath` implementation from overlay
* `Array<Element>` → `[Element]`
* Add missing unimplemented `NSIndexPath.getIndexes()` in extension
* Trivial whitespace changes
* `UnsafePointer<Int>` → `UnsafePointer<Int>!` to match Foundation and uses throughout framework/tests
* Integrate `IndexSet` implementation from overlay
* Trivial whitespace changes
* Rewrite `firstIndex` and `lastIndex` implementations from overlay to return correct values for empty sets (and fix associated crashes in tests due to incorrect implementation)
* Trivial whitespace changes
* Add `options:` labels where necessary
* `public` → `open` where necessary
Integrates/relies on changes submitted in [pr-enumerationoptions](https://github.com/apple/swift-corelibs-foundation/pull/530) (`EnumerationOptions` → …
=> Foundation API Conformance Update: [NS]Index{Set,Path}

Foundation/NSByteCountFormatter.swift
`stringFromByteCount(...)` → `string(fromByteCount ...)`
=> Foundation API Conformance Update: ByteCountFormatter

Foundation/NSDateComponentsFormatter.swift, Foundation/NSDateFormatter.swift, Foundation/NSEnergyFormatter.swift, Foundation/NSFormatter.swift, Foundation/NSLengthFormatter.swift, Foundation/NSMassFormatter.swift, Foundation/NSNumberFormatter.swift, Foundation/NSPersonNameComponentsFormatter.swift
All formatters should now accept `Any` instead of `AnyObject`
=> Foundation API Conformance Update: Formatter (AnyObject → Any)

Foundation/NSHTTPCookie.swift, Foundation/NSHTTPCookieStorage.swift, TestFoundation/TestNSHTTPCookie.swift
* Raw strings → `HTTPCookiePropertyKey`
* Method naming
=> Foundation API Conformance Update: HTTPCookie[Storage]

Foundation/NSDateIntervalFormatter.swift
* Naming
* `NSDateInterval` → `DateInterval`
=> Foundation API Conformance Update: DateIntervalFormatter

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
* `public static let default` → `open class var default`
* `URLRelationship` → `FileManager.URLRelationship`
* `NSFileManagerDelegate` → `FileManagerDelegate`
Where appropriate:
* `String` → `URLResourceKey`
* `String` → `FileAttributesKey`
* `NSError` → `Error`
=> Foundation API Conformance Update: FileManager

Foundation/NSHost.swift, Foundation/NSProcessInfo.swift
`Host.currentHost()` → `Host.current()`
=> Foundation API Conformance Update: Host

Foundation/NSHTTPCookie.swift
This addresses the improvements suggested to https://github.com/apple/swift-corelibs-foundation/pull/423/files viz. 
1) Using an array slice instead of (array, start, end) 
2) Keeping the String extension (3 utility methods) private to the defining file
Thanks!
=> Improvements suggested to PR 423

Foundation/NSData.swift, TestFoundation/TestNSData.swift
The wrong instance was being updated
=> Fix NSMutableData.replaceBytes(in:withBytes:length:)

CoreFoundation/Base.subproj/ForFoundationOnly.h, Foundation.xcodeproj/project.pbxproj, Foundation/NSArray.swift, Foundation/NSCoder.swift, Foundation/NSDictionary.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedArchiverHelpers.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSNotification.swift, Foundation/NSOrderedSet.swift, Foundation/NSPropertyList.swift, Foundation/NSSet.swift, Foundation/NSSwiftRuntime.swift, build.py
This also contains another kind of fix for the NSKeyedArchiver tests for macOS, which were failing because of assumptions made in the implementation about AnyObject. To help reduce the amount of casting in the implementation, this commit adds a private NS "toll free bridged" type for the private
CF type used as a keyed archiver UID in CFPropertyList.
=> NSKeyedArchiver, NSKeyedUnarchiver now use Any instead of AnyObject.

Foundation/NSDictionary.swift
The allocation of `NSDictionary` will now make use of the capacity and count parameters provided in the constructors.
For `NSMutableDictionary`'s `init(capacity:)` we need to reinstantiate the storage with a new `minimumCapacity` due to the lack of a `reserveCapacity` instance method like the one that `Array` provides.
An option considered was to change the required initializer of `NSDictionary` to a method that creates the underlying `Array` with the desired capacity, but this won't make any sense in the immutable `NSDictionary` context.
=> Reserve capacity when creating the storage Dictionary for NSDictionary.

TestFoundation/TestNSTask.swift
Please see [this note](https://github.com/apple/swift-corelibs-foundation/commit/afe26ffcb53525e6fdc9a758d571a86702542127#commitcomment-18298543).  This is a rough fix; I don't have confidence that the test's overall approach won't fail in some environments even with this change, but it should work in more places.
=> Attempt to address test resilience issue

Foundation/NSCFString.swift
Previous s390x PR #386 has a change to make the `_length` field of `CF_CONST_STRING` to `uint64_t`.  This requires a subsequent change to access the field correctly in `_NSCFConstantString`.
This change has been tested and verified to have no regression on x86-64.  On s390x, we see a good pass rate jump including TestNSURL, TestNSCalendar and TestNSNotificationQueue
=> Fix _length access on CF_CONST_STRING for s390x

Foundation/NSDateFormatter.swift
swift-corelibs-foundation only supports modern 10.4+ behavior.
=> Remove DateFormatter behavior

Foundation/NSXMLNode.swift, TestFoundation/TestNSXMLDocument.swift
Resolve crash when _CFXMLNodeGetName returns an empty string.
For some reason and empty pointer causes a crash during the String init.
=> Fix crash when running test_xmlpath

CoreFoundation/build.py
Not sure how these trailing quotes crept in, but the file doesn't parse unless you remove them.
Also, the standalone build still doesn't work for me unless I add some hackery to bring `<CoreFoundation/CFAsmMacros.h>` into the search path. I've worked around it in my build but I don't know what the proper solution is so I'm only including the syntax fixes until that's sorted out.
cc @phausler @CodaFi
=> Fix CoreFoundation standalone build syntax errors

Foundation/NSCache.swift, Foundation/NSConcreteValue.swift, Foundation/NSData.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSLock.swift, Foundation/NSNotification.swift, Foundation/NSOperation.swift, Foundation/NSTask.swift, Foundation/NSValue.swift, TestFoundation/TestNSThread.swift
* `Locking` → `NSLocking`
* `Lock` → `NSLock`
* `tryLock()` → `try()`
* `ConditionLock` → `NSConditionLock`
* `lockWhenCondition(_ condition: Int)` → `lock(whenCondition condition: Int)`
* `tryLock()` → `try()`
* `tryLockWhenCondition(_ condition: Int)` → `tryLock(whenCondition condition: Int)`
* `unlockWithCondition(_ condition: Int)` → `unlock(withCondition condition: Int)`
* `lockBeforeDate(_ limit: Date)` → `lock(before limit: Date)`
* `lockWhenCondition(_ condition: Int, beforeDate limit: Date)` → `lock(whenCondition condition: Int, before limit: Date)`
* `RecursiveLock` → `NSRecursiveLock`
* `tryLock()` → `try()`
* `Condition` → `NSCondition`
* `waitUntilDate(_ limit: Date)` → `wait(until limit: Date)`
Additional changes across files which use these classes.
=> Foundation API Conformance Update: Locking

Foundation/Date.swift, Foundation/DateComponents.swift, Foundation/DateInterval.swift, Foundation/NSCalendar.swift, Foundation/NSDate.swift, Foundation/NSDateComponentsFormatter.swift, Foundation/NSDateFormatter.swift, Foundation/NSDictionary.swift, TestFoundation/TestNSDate.swift, TestFoundation/TestNSDateFormatter.swift
* Add missing `addingTimeInterval(_ timeInterval: TimeInterval)` and `addTimeInterval(_ timeInterval: TimeInterval)`
* Move operators into struct
* Add missing mirror type, and bridging from overlay
* Whitespace fixes
* Integrate custom mirror from overlay
* Whitespace fixes
* Move operators into struct
* Integrate custom mirror from overlay
* Naming fixes
* `description(withLocale locale: Locale?)` → `description(with locale: Locale?)`
* Fix type of `distantPast` and `distantFuture`
* Add `brief` unit style
* `string(for obj: Any)` → `string(for obj: Any?)`
* Shorten formatter style names
Update tests and names as used throughout.
=> Foundation API Conformance Update: Datetime

build.py
The printed debugging command is missing `Foundation` path:
```
**** RUNNING TESTS ****
execute:
LD_LIBRARY_PATH=../build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation/:/swift.org/build/Ninja-ReleaseAssert/xctest-linux-x86_64: ../build/Ninja-ReleaseAssert/foundation-linux-x86_64/TestFoundation/TestFoundation
**** DEBUGGING TESTS ****
execute:
LD_LIBRARY_PATH=/swift.org/build/Ninja-ReleaseAssert/xctest-linux-x86_64: lldb ../build/Ninja-ReleaseAssert/foundation-linux-x86_64/TestFoundation/TestFoundation
```
This will require the user to manually insert something like `../build/Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation/` in the command to make it work.
This pull request fixes this issue. The result will look like this:
```
**** RUNNING TESTS ****
execute: …
```
=> Fix the "DEBUGGING TESTS" command

TestFoundation/TestNSJSONSerialization.swift
- The capacity passed was larger than the buffer length causing
NSOutputStream.write() to write past the end of the buffer
- Found using AddressSanitizer
=> Fix heap overflow in TestNSJSONSerialization

Foundation/CharacterSet.swift, Foundation/NSCharacterSet.swift
1) we don't actually impl NSCoding methods, so NSUnimplement them
2) punctuationCharacters was incorrectly migrated as punctuation
=> CharacterSet: minor improvements to match darwin

Foundation/NSBundle.swift, Foundation/NSData.swift, Foundation/NSFileHandle.swift, Foundation/NSFileManager.swift, Foundation/NSPathUtilities.swift, Foundation/NSURL.swift, Foundation/NSURLRequest.swift, Foundation/NSURLResponse.swift, Foundation/NSUserDefaults.swift, Foundation/NSXMLDTD.swift, Foundation/NSXMLParser.swift, Foundation/String.swift, Foundation/URL.swift, Foundation/URLComponents.swift, Foundation/URLRequest.swift, TestFoundation/TestNSBundle.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSKeyedArchiver.swift, TestFoundation/TestNSKeyedUnarchiver.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSTask.swift, TestFoundation/TestNSURL.swift
* Add resource values API
* `fileURLWithPathComponents(_ components: [String])` → `fileURL(withPathComponents components: [String])`
* `AnyObject` → `Any`
* Add missing URL resource keys
* `stringByAddingPercentEncodingWithAllowedCharacters(_ allowedCharacters: CharacterSet)` → `addingPercentEncoding(withAllowedCharacters allowedCharacters: CharacterSet)`
* `stringByRemovingPercentEncoding: String?` → `removingPercentEncoding: String?`
* Integrate work from overlay (with nullability/throws changes)
* Update tests to remove now missing elements (e.g. `resourceSpecifier`)
* Update auxiliary usages to match new nullability/throws
* Integrate work from overlay
* Update types in `NetworkServiceType`
=> Foundation API Conformance Update: URLs

Foundation/NSCalendar.swift, Foundation/NSCoder.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSError.swift, Foundation/NSGeometry.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSLocale.swift, Foundation/NSNotification.swift, Foundation/NSPersonNameComponents.swift, Foundation/NSRange.swift, Foundation/NSTimeZone.swift, Foundation/NSURL.swift, Foundation/NSUserDefaults.swift, TestFoundation/TestNSKeyedArchiver.swift, TestFoundation/TestNSKeyedUnarchiver.swift, TestFoundation/TestNSUUID.swift
Brings NSCoder and NSKeyed{A,Una}rchiver to Swift3 compliant API.
=> Migrate Swift 3 Darwin for Coder/Archival

Foundation/Dictionary.swift, Foundation/NSArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSDictionary.swift, Foundation/NSError.swift, Foundation/NSLocale.swift, Foundation/NSObjCRuntime.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, Foundation/Set.swift, TestFoundation/TestNSArray.swift
Update the labels for methods using options in the collections to match Darwin. Additionally rename SortOptions to NSSortOptions to match Darwin names
=> Sort and enumeration labels

Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift
NSKeyedArchiver uses an internal struct, NSUniqueObject to box unhashable objects so they may be used as dictionary keys. AnyHashable, if my understanding is correct, obviates the need for this.
=> [SR-2384] remove NSUniqueObject

Foundation/NSJSONSerialization.swift, Foundation/NSNumber.swift, TestFoundation/TestNSJSONSerialization.swift
Resolved bug number:SR-2151 (https://bugs.swift.org/browse/SR-2151)
Implementation 
Tests (note all tests are done on NSJSONSerialization due to access lvl protection )
**Problem :** 
NSJSONSerialization.data produces illegal JSON code
**Cause :** 
NSJSONSerialization ```func serializeNumber(_ num: NSNumber) throws ```
uses NSNumber ```open override var description: String``` which calls 
```open func description(withLocale locale: Locale?) -> String```  with a nil locale.
The nil locale case is handled by setting the format style to kCFNumberFormatterNoStyle & kCFNumberFormatterMaxFractionDigits
the leading zero does not show up which results in the incorrect format.
``` ["foo": 0.123] ```
should be
```
{
"foo": 0.1234
}
```
but is 
```
{
"foo": .1234
} …
```
=> [SR-2151]NSJSONSerialization.data produces illegal JSON code

Foundation/NSArray.swift, Foundation/NSCache.swift, Foundation/NSComparisonPredicate.swift, Foundation/NSCompoundPredicate.swift, Foundation/NSError.swift, Foundation/NSExpression.swift, Foundation/NSFileHandle.swift, Foundation/NSFileManager.swift, Foundation/NSMeasurementFormatter.swift, Foundation/NSNotification.swift, Foundation/NSNumberFormatter.swift, Foundation/NSPersonNameComponents.swift, Foundation/NSPersonNameComponentsFormatter.swift, Foundation/NSPredicate.swift, Foundation/NSString.swift, Foundation/NSThread.swift, Foundation/NSTimer.swift, Foundation/NSUserDefaults.swift, Foundation/PersonNameComponents.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSCompoundPredicate.swift, TestFoundation/TestNSDictionary.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSNumberFormatter.swift, TestFoundation/TestNSPredicate.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSTimer.swift, TestFoundation/TestNSUserDefaults.swift
* `FirstEqual` → `firstEqual`
* `LastEqual` → `lastEqual`
* `InsertionIndex` → `insertionIndex`
* `Cache` → `NSCache`
* Make `NSCache` generic for type safety
* `func` → `var`
* `String` → `RunLoopMode`
* `AnyObject` → `Any`
* `expressionValueWithObject(_ object: AnyObject?, context: NSMutableDictionary?)` → `expressionValue(with object: AnyObject?, context: NSMutableDictionary?)`
* `Predicate` → `NSPredicate`
* Add missing `public init(format predicateFormat: String, arguments argList: CVaListPointer) { NSUnimplemented() }` and `public convenience init(format predicateFormat: String, _ args: CVarArg...) { NSUnimplemented() }`
* Update `filter`/`filtered` extensions for collection classes
* `ComparisonPredicate` → `NSComparisonPredicate`
* `CompoundPredicate` → …
=> Foundation API Conformance Update: Miscellaneous

Foundation/Data.swift, Foundation/NSConcreteValue.swift, Foundation/NSData.swift, Foundation/NSFileHandle.swift, Foundation/NSFileManager.swift, Foundation/NSString.swift, Foundation/NSXMLDocument.swift, Foundation/NSXMLParser.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSJSONSerialization.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSXMLParser.swift
Brings the Data and NSData API in s-cl-f to match the public version of Swift3 on Darwin. Reorganizes the implementation of Data/NSData to be a bit saner (versus somewhat vestigially matching the Objective-C categories on Darwin).  Also brings a whole host of tests over from our overlay (some disabled for now, since the real focus of this PR is the API parity, which we should have now).
=> Swift 3 API Parity:  Data & NSData

Foundation/Unit.swift
Access control for overrides is being refined and enforced by apple/swift#4404.
=> [NFC] Overrides must be at least fileprivate

Foundation/NSJSONSerialization.swift, Foundation/NSNumber.swift, TestFoundation/TestNSJSONSerialization.swift
Old PR https://github.com/apple/swift-corelibs-foundation/pull/540 reverted due to build break after merge. 
Was asked to refile against master
=> [SR-2151]NSJSONSerialization.data produces illegal JSON code #2

TestFoundation/TestNSOperationQueue.swift
After you merge #551 and Dispatch is enabled by default, both of these tests will now pass and can be enabled.
=> enable Dispatch tests in TestNSOperationQueue

Foundation/NSData.swift, Foundation/NSJSONSerialization.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSKeyedArchiver.swift
This function was removed on purpose and should not be re-introduced.
=> NSData and struct Data should not have a function called bridge

Foundation/Data.swift
There was a missing protocol and a few overrides that didnt come in right before
=> Re-import a few things for struct Data

Foundation.xcodeproj/project.pbxproj, Foundation/CGFloat.swift, Foundation/NSGeometry.swift, build.py
There were a few new protocol conformances and annotations to CGFloat that had not yet been imported to swift-corelibs-foundation. This expands the definitions to be more in-line with how CGFloat is defined in the standard library.
=> Extract CGFloat definition into it’s own file and re-build the full conformance list for CGFloat

Foundation/FoundationErrors.swift, Foundation/NSDate.swift, Foundation/NSError.swift, Foundation/NSFileManager.swift, Foundation/NSJSONSerialization.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSString.swift, Foundation/NSUUID.swift, TestFoundation/TestNSData.swift
* `NSCocoaError` → `CocoaError`
* Reimplement top-level error values in terms of consistent definitions
* Import new error types (`RecoverableError`, `LocalizedError`) from overlay
* Import URL errors and POSIX errors from overlay
* Import error bridging from overlay
* Update error code usage throughout project
=> Foundation API Conformance Update: Errors

Foundation.xcodeproj/project.pbxproj, Foundation/NSURLSession/EasyHandle.swift, Foundation/NSURLSession/MultiHandle.swift, Foundation/NSURLSession/NSURLSession.swift, Foundation/NSURLSession/NSURLSessionTask.swift
un-buildable changes were pushed to the project were introduced from URLSession. This broke the builds for Darwin hosts since the Xcode project could no longer build. This adds the URLSession and associated files in as per required for the Xcode project, links libcurl, and renames the nested class which does not work on the latest binary drop of the swift toolchain (the support for which is still pending on master)
=> Make Darwin targets buildable after merge

Foundation/NSURLSession/EasyHandle.swift, Foundation/NSURLSession/MultiHandle.swift, TestFoundation/TestNSURLSession.swift
I saw some intermittent failures and crashes in the URLSession tests. Fixing a test and doing some cleanup here. I have also reduced one particular crash to a test case failure here. I will continue working on eliminating that particular failure.
=> PR 426 - Fixing a test and removing debug prints

Foundation/NSURL.swift, TestFoundation/TestNSURL.swift
This PR has following:
1. Implementation for NSURLComponents.copy(with:). Approach is to create default NSURLComponent and update fields one by one.
2. Override isEqual() function. Since copy is not 'self', it is required to override isEqual to compare properties instead of object references. 
3. Unit test for copy(). I've used NSURLComponents class in testcase instead of URLComponents structure because it doesn't have mapping for copy() function.
=> implementation for NSURLComponents.copy(with:)

Foundation/NSOrderedSet.swift, Foundation/NSPredicate.swift, TestFoundation/TestNSPredicate.swift
Our updated collections store boxed values as `_SwiftValue` objects. All implementations of `filtered(using:)` for our other collections use methods which automatically unbox those stored objects (e.g. `self.enumerated()` in mutable variants, `allObjects` in `NSArray` and `NSSet`) before passing to a predicate. The method for `NSOrderedSet` did not, causing the predicate to receive an unexpected box instead of the contained value (crashing when the predicate attempted to force cast the box instead of the value).
This was caught while uncommenting unit tests for `NSPredicate`; there's now no longer a reason to keep them commented out.
=> Correct NSOrderedSet filtering by unboxing objects

Foundation/NSOperation.swift
Testing with malloc scribble, guard edges, and guard malloc revealed this failure on Darwin builds. Evidently it alters the timing enough to show the race on un-gated operations
=> ensure the concurrency gate is present for all variations of OperationQueue (irregardless of the queue width)

Foundation/NSLocale.swift, TestFoundation/TestNSKeyedArchiver.swift
`NSLocale`'s `encode(with:)` encodes the locale's identifier as a `CFString`, which causes a crash in `NSKeyedArchiver`'s `_haveVisited` ref map, since `CFString` cannot be forcibly cast to `AnyHashable`. Encoding the identifier as an `NSString` fixes the issue.
In decoding, a different `NSLocale` instance is returned. Since `NSLocale` no longer has value semantics (which were ported to `Locale`), it needs an `isEqual` implementation to compare two `NSLocale` instances as equal.
These changes combined allows us to uncomment the keyed archiving test and have it pass.
=> Enable NSLocale keyed archiving unit tests

Foundation/NSURLResponse.swift, Foundation/NSURLSession/HTTPMessage.swift, Foundation/NSURLSession/NSURLSessionDelegate.swift, Foundation/NSURLSession/NSURLSessionTask.swift, Foundation/NSURLSession/TransferState.swift, TestFoundation/TestNSURLResponse.swift, TestFoundation/TestNSURLSession.swift
The Swift 3 API changes dropped the `NS` prefix from `NSHTTPURLResponse`, but that was missed in the `URLSession` code drop.
This remove the `NS` prefix from the declaration and where its used in both Foundation and TestFoundation.
=> Swift 3 API Parity: Drop NS prefix from NSHTTPURLResponse

Foundation.xcodeproj/project.pbxproj, Foundation/NSURLRequest.swift, Foundation/NSURLSession/Configuration.swift, Foundation/NSURLSession/NSURLSession.swift, Foundation/NSURLSession/NSURLSessionConfiguration.swift, Foundation/NSURLSession/NSURLSessionDelegate.swift, Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/TestNSURLSession.swift, TestFoundation/TestURLRequest.swift, TestFoundation/main.swift
A number of the URLSession APIs should now take `URLRequest` rather than `NSURLRequest` or `NSMutableURLRequest` as parameters. Examples of this include:
```
open func dataTask(with request: URLRequest) -> URLSessionDataTask
open func uploadTask(with request: URLRequest, from bodyData: Data) -> URLSessionUploadTask
open func downloadTask(with request: URLRequest) -> URLSessionDownloadTask
```
This PR switches over to using `URLRequest` rather than the existing use of `NSURLRequest`.
I've additionally added tests for `URLRequest` in addition to `NSURLRequest` (which still exists) by duplicating the existing `NSURLRequest` tests. 
Whilst doing this I hit a crash when trying to mutate a value in a copied `URLRequest`. This is caused because, when we call `_appyMutation` for a non-uniquely …
=> Swift 3 API Parity: Use URLRequest rather than NSURLRequest in APIs

Foundation/Calendar.swift, Foundation/NSCalendar.swift
=> Foundation API Conformance Update: Calendar

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSDateFormatter.swift, Foundation/NSTimeZone.swift, Foundation/TimeZone.swift, TestFoundation/TestNSTimeZone.swift
Done:
* Renamed members for `NSTimeZone` to align with Darwin Foundation API.
* Implemented `init(forSecondsFromGMT:)`, `localizedName(_:locale:)`.
* Implemented properties `abbreviationDictionary` (getter only), `secondsFromGMT`, `isDaylightSavingTime`, `daylightSavingTimeOffset`, `nextDaylightSavingTimeTransition`.
* Removed `fatalError()` from helper function for `TimeZone.current` and plumbed through to `NSTimeZone.system`.
* Aligned `TimeZone` API to Swift 3, restoring/adding `TimeZone.autoupdatingCurrent` (now plumbed through to `NSTimeZone.local`, which is unimplemented) and updating conformance to `Equatable`, `CustomStringConvertible`, etc., by copying over newer code from apple/swift.
Not done:
* `NSTimeZone.local` should return an auto-updating member; this one is non-obvious …
=> Swift 3 API parity and new implementations for NSTimeZone

Foundation/NSTimeZone.swift
A minor fix-up, discussed in #609, for consistency with how things are done with elsewhere in the project for raw values associated with `NSNotification.Name` constants.
=> Make empty NSNotification.Name.NSSystemTimeZoneDidChange.rawValue

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/Calendar.swift, Foundation/NSCalendar.swift, Foundation/NSDateFormatter.swift, Foundation/NSTimeZone.swift, Foundation/TimeZone.swift, TestFoundation/TestNSTimeZone.swift
Pulls #602 and #608 into swift-3.0-branch
=> Swift 3 API parity for [NS]TimeZone & [NS]Calendar

Foundation/Bridging.swift, Foundation/NSArray.swift, Foundation/NSAttributedString.swift, Foundation/NSCalendar.swift, Foundation/NSCharacterSet.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSDictionary.swift, Foundation/NSError.swift, Foundation/NSKeyedArchiverHelpers.swift, Foundation/NSLocale.swift, Foundation/NSNumber.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSTimeZone.swift, Foundation/NSURL.swift, Foundation/URLComponents.swift
=> Fixing a typo in internal bridging protocol names (NFC)

Foundation/NSValue.swift, TestFoundation/TestNSValue.swift
NSNumbers are not added to the side table, so we can't find them.
I don't think that `NSValue.isEqual()` is correct in general, but this gets us closer to the correct implementation and unblocks https://github.com/apple/swift/pull/4621 . For example, subclasses that have custom storage -- like NSNumber -- should compare equal to an NSValue as long as they have the same bytes and the same type, but the current implementation of `NSValue.isEqual()` can only return true if two references are equal.
Note: this issue blocks https://github.com/apple/swift/pull/4621 (after we change the hashing algorithm, the test TestNSKeyedArchiver.test_archive_set starts to compare NSValue to NSNumber where it previously wasn't doing that just because we got lucky in the hash table order).
=> Fix crash in NSValue.isEqual() when it is passed an NSNumber

Foundation/Unit.swift
The provided values were not as exact as they could be. In fact the value for "revolutions" was completely wrong (2π instead of 360°).
=> Changed coefficients of UnitAngle to more exact values

Foundation/NSCalendar.swift, Foundation/NSConcreteValue.swift, Foundation/NSDate.swift, Foundation/NSGeometry.swift, Foundation/NSLocale.swift, Foundation/NSRange.swift, Foundation/NSSpecialValue.swift, Foundation/NSURL.swift, TestFoundation/TestNSDate.swift
The two NSUnimplemented functions in Date relate to a class property
`timeIntervalSinceReferenceDate` which matches an instance property
of the same name, and methods relating to the unkeyed coder.
Implement the `timeIntervalSinceReferenceDate` by instantiating a
new instance and delegating to the instance property, and change
the unkeyed coder implementations to a fatalError indicating that
they are unsupported.
=> Implement missing functions in Date

Foundation/NSArray.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSDictionary.swift, Foundation/NSError.swift, Foundation/NSGeometry.swift, Foundation/NSNotification.swift, Foundation/NSNumber.swift, Foundation/NSOrderedSet.swift, Foundation/NSPersonNameComponents.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSTimeZone.swift, Foundation/NSUUID.swift, Foundation/Unit.swift
Instead of having non-keyed encoding supported by some but not
all foundation types, remove the non-keyed encoding everywhere
and make passing a non-keyed encoder a preconditionFailure.
=> Remove non-keyed encoding for data objects

Foundation/NSURLCredential.swift, TestFoundation/TestNSURLCredential.swift
This PR has Implementation of NSURLCredential.copy(with:) along with the unit test case.
=> Implementation of NSURLCredential.copy(with:)

Foundation/NSDictionary.swift, TestFoundation/TestNSDictionary.swift
Also includes fix for displaying nested dictionaries properly
=> Implementing NSDictionary.descriptionInStringsFileFormat

Foundation/NSURLSession/Configuration.swift
`NSURLSessionConfiguration.httpAdditonalHeaders` is declared to accept `[AnyHashable:Any]`, but internally this maps to `[String : String]`.
Currently the code assumes that the `[AnyHashable:Any]` actually only contains `NSString`s, whereas on macOS/Darwin its acceptable for either `NSString`s or `String`s to be used.
I've therefore updated `URLSession._Configuration.convertToStringString()` to allow either and coerce to String if needed.
=> Allow httpAdditionalHeaders to contain Strings or NSStrings

Foundation/NSGeometry.swift, TestFoundation/TestNSGeometry.swift
`CGFloat.NativeType` is `Float` on 32bit platforms.
=> [NSGeometry] Use CGFloat.NativeType instead of hardcoded Double

Foundation/NSScanner.swift, TestFoundation/TestNSScanner.swift
Migrate from internal `_FloatLike` protocol to `BinaryFloatingPoint`.
Incidentally fix a subtle bug and align to Darwin Foundation:
* We don't want to return `FLOAT_MIN` when the string has a negative number with magnitude too great to be representable in a `Float` (`FLOAT_MIN` isn't like `Int.min`!)
* Actually, we don't even want `-Float.greatestFiniteMagnitude`, since Darwin Foundation returns `-Float.infinity`
I've adjusted the behavior accordingly and written a test.
Annoyingly, one test is currently failing on my machine, but it fails both with and without this patch and must be unrelated (i.e., it is failing with a freshly checked-out copy of swift-corelibs-foundation on XCode 8 GM):
```
error: TestNSData.test_replaceBytes : XCTAssertEqual failed: ("<0008090a 00>") is not equal to …
```
=> Update NSScanner to use BinaryFloatingPoint

Foundation/NSURLSession/NSURLSessionDelegate.swift, Foundation/NSURLSession/NSURLSessionTask.swift
SR-2638 reports that the following URLSessionDelegate callback is never triggered:
```
func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)
```
This is actually caused by a function signature issue - I'm not sure why the compiler isn't picking it up.
On Linux, the function signature for the callback is currently using the old style:
```
internal func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: NSError?)
```
ie. its specified as an `NSError` instead of `Error`.
This PR switches over the API, and coerces the `NSError` to an `Error` before calling the callback.
=> SR-2683 URLSessionDelegate didCompleteWithError callback never triggered

Foundation/NSURLSession/NSURLSessionTask.swift
The test case provided in SR-2617 has highlighted multiple differences between Darwin and Linux, the second of which is that POST requests are automatically set to have a header value of `Content-Type : application/x-www-form-urlencoded` on Darwin, but don't on Linux.
The behaviour on Darwin is that:
1. The value is set, but doesn't appear in the `URLRequest.allHTTPHeaderFields`
2. The value is overridden by any call to `req.setValue(value, forHTTPHeaderField: "Content-Type" )`
This PR mimics that behaviour by setting the header as we pass it to the underlying libcurl implementation, if and only if Content-Type isn't already set.
=> [SR-2617] POST requests should have Content-Type : application/x-www-form-urlencoded by default

Foundation/NSURLSession/NSURLSessionTask.swift
I am abstaining from adding the tests from SR-2630 to TestFoundation because the reach out to external URLs and I saw them hang on a few instances.
=> Fix for a URLSession crash (SR-2630)

Foundation/NSURLSession/NSURLSession.swift, Foundation/NSURLSession/NSURLSessionTask.swift, Foundation/NSURLSession/TaskRegistry.swift
This PR primarily addresses the premature URLSession object cleanup reported in[ SR-2631](https://bugs.swift.org/browse/SR-2631). 
As a solution to SR-2631, we now maintain a reference to the session object from the task object creating a retain cycle. So, this PR also takes care of breaking such cycles on task completion. 
Another type of retain cycle can exist between session objects and the delegates registered with them (see point 15 [here](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/NSURLSessionConcepts/NSURLSessionConcepts.html)), the ```finishTasksAndInvalidate``` method breaks these cycles per the URLSession specification.
=> Fix for SR-2631 and implementing URLSession.finishTasksAndInvalidate

Foundation/NSURLSession/NSURLSession.swift
See https://developer.apple.com/reference/foundation/nsurlsession/1409763-uploadtask
=> Swift 3 API for NSURLSession's uploadTask 'from' parameter

Foundation/NSOperation.swift
- Description: Fixes an issue where adding tasks to an OperationQueue has a race condition which may cause them to execute without regard to priority order.
- Scope of the issue: Currently causing stochastic public CI build failures.
https://ci.swift.org/view/swift-3.0-branch/job/oss-swift-3.0-incremental-RA-linux-ubuntu-15_10/182/consoleFull#-289045209ee1a197b-acac-4b17-83cf-a53b95139a76
- Risk: Low.
- Tested: Fixes existing test.
- Reviewed by: 
- Radar: rdar://problem/28178534
- Jira: https://bugs.swift.org/browse/SR-2569
=> Fix for NSOperationQueue race condition causing public CI failures

Foundation/Data.swift
- Set Foundation.Data.SubSequence to be RangeReplaceable
RangeReplaceableCollection.SubSequence should be a RangeReplaceableCollection.  Data implements RangeReplaceableCollection, but sets SubSequence to MutableRandomAccessSlice that is not a RangeReplaceableCollection.
This commit changes Foundation.Data.SubSequence to MutableRangeReplaceableRandomAccessSlice.
Fixes rdar://problem/28330713.
- Change Data.Indices to be a CountableRange<Int>, that is much faster than the default.
=> Fixes for associated types of Data

Foundation/NSNumberFormatter.swift, TestFoundation/TestNSNumberFormatter.swift
Reported by https://bugs.swift.org/browse/SR-2477
In the absence of coercion of Swift types to Foundation types on Linux, this is to bring about functional similarity with Darwin.
=> Allow numeric types in NSNumberFormatter.string(for:)[SR-2477]

CoreFoundation/Base.subproj/CFAsmMacros.h, CoreFoundation/String.subproj/CFCharacterSetData.S, CoreFoundation/String.subproj/CFUniCharPropertyDatabase.S, CoreFoundation/String.subproj/CFUnicodeData.S
The use of the hand written assembly files could potentially introduce
executable stacks.  Since these files do not require the executable stacks,
ensure that we add the special marker to indicate that executable stacks are not
required.
=> String: prevent executable stacks on GNU targets

Foundation/NSSwiftRuntime.swift, TestFoundation/TestNSAttributedString.swift
Previously, the `test_longestEffectiveRange` was not added to `allTests`.
Also some of the asserts were miscalculated.
=> Fix a missing test case in NSAttributedString

Foundation/NSURLResponse.swift, TestFoundation/TestNSURLResponse.swift
Change type of HTTPURLResponse.allHeaderFields to [AnyHashable : Any] to match Darwin.
=> Swift 3 API parity: Change type of HTTPURLResponse.allHeaderFields

Foundation/NSFileManager.swift
On macOS, `DT_DIR` is imported as an `Int`. `Int` and `Int32` cannot be compared via `==`, so on macOS the comparison results in a build failure. Cast the variables to `Int32` to resolve.
---
This fixes a Foundation build failure on XCTest's macOS CI. Unblocks https://github.com/apple/swift-corelibs-xctest/pull/172 and https://github.com/apple/swift-corelibs-xctest/pull/174.
=> [NSFileManager] Cast file types as Int32

Foundation.xcodeproj/project.pbxproj, TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift, build.py
This is a very basic HTTP server for loopback tests for URLSession. I have borrowed some implementation aspects from the HTTPServer.swift in PR 299. The server currently, listens, reads and writes only once. It is possible to test data tasks and download tasks. Opening this PR for review and comments. 
I also had to make a small change to build.py to get TestFoundation built with Dispatch.
=> Loopback tests for URLSession

CoreFoundation/Base.subproj/CFUtilities.c
Minor change mopping up PR https://github.com/apple/swift-corelibs-foundation/pull/622 to check a calloc return value by popular demand.
=> Check return from calloc

Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
https://bugs.swift.org/browse/SR-2694
=> [SR-2694] Cannot JSON serialize array with boolean value 

Foundation/NSJSONSerialization.swift
Currently the JSON Serializer only handles the "common" numbers types: `Int`, `Double` and `NSNumber`.
Trying to serialise the other number types: `UInt`, `Int8`, `UInt8`, etc as well as `Float` results in an Error.
This PR adds support for the wider set of standard types.
=> Support JSONSerialization of more number types

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h, CoreFoundation/Base.subproj/ForFoundationOnly.h
This changes a few `#import` statements to `#include`. This is because Clang's MSVC compatibility does not handle `#import` statements outside of of objc.
#import of type library is an unsupported Microsoft feature
=> Don't use #import when #include will do

Foundation/Data.swift
Cherry picked for <rdar://problem/28330713> Foundation.Data sets SubSequence to an incorrect type
=> Data associated type fixes 3.0

Foundation/NSURLSession/NSURLSession.swift, Foundation/NSURLSession/TaskRegistry.swift, TestFoundation/TestNSURLSession.swift
The problem is in the current implementation of `finishTasksAndInvalidate`, if there're executing tasks in session - it will create a semaphore, that will block session work queue, but to release, it has to enter that queue again.
Resolves [SR-2798](https://bugs.swift.org/browse/SR-2798).
=> [SR-2798] Fix deadlock in URLSession.

TestFoundation/TestNSArray.swift, TestFoundation/TestNSDictionary.swift
Calling XML validation results in hitting the Apple web servers
to load a DTD for plists http://www.apple.com/DTDs/PropertyList-1.0.dtd
to correctly validate the XML file.
Given that this test is not about whether it is possible to read
or write property lists, but they're just being used to validate
that they can read and write arrays from them, remove this part
of the test. The property list gets parsed from the subsequent
PropertyListSerialization call anyway, which will do the same error
checking as if the document is valid (but probably with a hard-coded
DTD instead of a network accessible one)
Issue: SR-2793
=> Remove XML validation from NSArray/NSDictionary tests

Foundation/DateComponents.swift, Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
This PR has fixes for DateComponents and Calendar which were causing date manipulations to fail, resolving [SR-2846](https://bugs.swift.org/browse/SR-2846):
- DateComponents no longer returns isLeapMonth = false when isLeapMonth wasn't set (in situations where isLeapMonth is irrelevant, for example using DateComponents to add 1 day to another date).
- NSCalendar's `_convert()` is fixed for the character set for isLeapMonth to align with expected value from `UCalendarDateFields` ('l' instead of 'L').
- NSCalendar's `date(byAdding:to:options:)` is fixed to do math on the passed-in date, rather than the reference time 0.0.
A test for this is included.
=> Fixes for Date Manipulations

Foundation/DateComponents.swift, Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
Fixes for Date Manipulations, see #668.
=> Cherry-pick important fixes for 3.0.1 (#668)

build.py, lib/script.py, lib/target.py
1. Modified `lib/Target.py` for Cygwin
2. Add compile and linker options in `build.py` for Cygwin
3. Changed the order of '-lFoo' type option in `lib/script.py`.  
This is related to #381
=> Modified build scripts for Cygwin

CoreFoundation/Locale.subproj/CFCalendar.c
The Calendar destructor releases stored values when the
Calendar is being deallocated, including releasing the localeID.
By default this is an empty string (kCFEmptyString) which results
in multiple Calendars causing a fault when it is over-released.
Ensure that instead the localeID is retained to balance the
release when it is cleaned up.
Issue: SR-2879
=> Retain localeID when constructing a Calendar

CoreFoundation/Locale.subproj/CFCalendar.c, CoreFoundation/Locale.subproj/CFLocaleKeys.c, Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
The list of valid keys did not include the ISO8601 calendar, which
meant that code running on Linux that used it would fail. Fix this
by adding the kCFISO8601Calendar and others into the list of known
constants valid for calendars, and add tests for the Gregorian
calendar, as well as for creating all other calendars.
Issue: SR-2551
=> Add support for ISO8601 calendar and others

Foundation/NSHTTPCookie.swift, Foundation/TimeZone.swift, Foundation/URLComponents.swift, Foundation/URLRequest.swift, TestFoundation/TestNSHTTPCookie.swift, TestFoundation/TestNSTimeZone.swift
Addressing build-time warnings of possibly nil values being used as Any [SR-2737] (https://bugs.swift.org/browse/SR-2737)
Some whitespace fixes too
=> Fix Any? -> Any build warnings

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Collections.subproj/CFBasicHash.c, CoreFoundation/Collections.subproj/CFData.c
This is because Clang's MSVC compatibility does not handle `#import` statements outside of of objc.
#import of type library is an unsupported Microsoft feature
This is a follow up to a similar change in #663.
=> Use #include over #import in C souce

Foundation.xcodeproj/project.pbxproj, Foundation/NSDecimal.swift, TestFoundation/TestNSDecimal.swift, TestFoundation/main.swift
Although not yet fully covered by tests, this is a nearly complete implementation of NSDecimal. There are cases where dealing with large and small numbers will overflow that isn't implemented yet (there is one remaining NSUnimplemented) but it can be used for simple mathematical operations.
=> Implement Decimal

CoreFoundation/Locale.subproj/CFCalendar.c, CoreFoundation/Locale.subproj/CFLocaleKeys.c, Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
These fix a crashing bug with Calendar when more than four instances are created and destroyed, and adds support for ISO8601 Calendars and others.
=> Add Calendar fixes for Swift 3

Foundation/NSFileManager.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/Notification.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSTimeZone.swift, TestFoundation/TestNSURL.swift, TestFoundation/TestNSXMLDocument.swift
Suppresses new warnings from https://github.com/apple/swift/pull/5195
- Avoid optional where no impact w/IUO
- Mostly cast to Optional
- Change in Notification description() to avoid issue
=> Suppress string interpolation warnings

Foundation.xcodeproj/project.pbxproj, TestFoundation/TestObjCRuntime.swift, TestFoundation/main.swift
I've add simple test coverage for NSStringFromClass and NSClassFromString
=> Add tests for NSClassFromString and NSStringFromClass

TestFoundation/TestNSRange.swift
I've add more tests to cover NSRange implementation. They are pretty straight forward, but anyone can remember because the one for NSRangeFromString is commented out? On macOS it pass just fine, there is some issues on Ubuntu?
=> Add more NSRange tests

Foundation/NSDecimal.swift, Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift, TestFoundation/TestNSDecimal.swift
This extends the normalisation routines to be able to handle
mismatched size elements, and division of decimals that are larger
than short values correctly. It adds tests that are the same coverage
as for NSDecimal on Darwin.
=> Final implementation of Decimal

Foundation/NSDecimal.swift
This warning has been showing up for a while now:
```
Foundation/NSDecimal.swift:1389:44: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
fatalError("Locale not supported: \(locale)")
```
=> Fix a build warning in NSDecimal

Foundation/NSLock.swift
Fix for [SR-2962](https://bugs.swift.org/browse/SR-2962)
=> Correct NSConditionLock busy-wait on thread

Foundation/NSString.swift, TestFoundation/TestNSData.swift
`"".data(using: .utf8)` should return empty `Data` (instead of `nil`).
In Darwin, `"".data(using: .utf8) == Data()`
=> Return empty data when converting from empty string

Foundation.xcodeproj/project.pbxproj, Foundation/Notification.swift, TestFoundation/TestNotification.swift, TestFoundation/main.swift
Please review!
I've reverse engineered the reflectable behaviour to be effectively:
1. Translate NSNotification.Name types to Strings
2. Only include userInfo and object in children when the properties are non-nil
3. Provide them in the order of name, object, userInfo
This PR implements tests and the implementation to provide this.
For reference, this code can be dumped into a playground to see how Apple do it.
```
//: Playground - noun: a place where people can play
import UIKit
let thisObject = NSObject()
let anotherObject = NSObject()
let userInfo = ["something": 1, "anotherObject": anotherObject] as [String : Any]
let notif = Notification(name: .UIScreenDidConnect, object: thisObject, userInfo: userInfo)
let customMirror = notif.customMirror
let mirror = …
```
=> [Notification] Implement CustomReflectable for Notifications

Foundation/NSString.swift, TestFoundation/TestNSString.swift
Replaced a forced optional unwrapping (`!`) of `UnicodeScalar` which resulted in crash if there was an emoji symbol at start or end of the string with `let` constraint.
Issue: https://bugs.swift.org/browse/SR-3101
=> Fix for SR-3101 - crash on `.trimmingCharacters(in:)`

Foundation/CharacterSet.swift, TestFoundation/TestNSCharacterSet.swift
https://github.com/apple/swift/pull/5603
credit to @JaSpa
=> Apply fix for SR-2988 from overlay.

Foundation/NSCFString.swift, TestFoundation/TestNSString.swift
Fixes Issue: https://bugs.swift.org/browse/SR-3052
Added tests that cover this issue. 
Implemented possible fix by providing correct UTF8-length for `_CFStringCreateByAddingPercentEncodingWithAllowedCharacters` and `_CFStringCreateByRemovingPercentEncoding`
Also switched to `CFStringGetLengthUTF8` method for string length where UTF-8 encoding is used.
=> SR-3052. Incorrect string result for String methods with non latin symbols

Docs/Status.md, Foundation/NSURLCredential.swift, TestFoundation/TestNSURLCredential.swift
Implemented a Keyed coding for URLCredentials. Non keyed is not supported in MacOS Foundation, so it's wasn't implemented.
Added test to cover `NSCoding` changes.
Overriden `isEqual` method to match MacOS Foundation.
=> Implementation of NSCoding for URLCredential

Foundation/NSURLSession/HTTPMessage.swift
`headersAsDictionary` didn't support duplicate header fields; if there are multiple occurrences of one field, only one of them was returned.   However, [duplicate header fields are valid](http://stackoverflow.com/q/4371328/3476191), and are equivalent to one comma-separated field.
=> Duplicate HTTP headers should be joined with a comma

Foundation/NSURLSession/HTTPMessage.swift
In case of Darwin,  response headers with empty value are not ignored .So  through this PR we are handling the headers with empty value  and writing them with to the response header with empty value to match Darwin behavior
=> [URLSession] Data, response not returned when headers are set [SR-2983]

Foundation/NSURLSession/NSURLSessionTask.swift
In `startNewTransfer(with:)` though we first set currentRequest property to the incoming request [here](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSURLSession/NSURLSessionTask.swift#L462), the update happens asynchronously on the `taskAttributesIsolation` queue. Subsequently, in `curlHeaders(for: URLRequest)` we use the `currentRequest` property assuming it has been set to get the HTTP headers. 
If we end up picking up the HTTP headers before async block runs, we can get into problems. For new requests, the `currentRequest` property could still be nil, meaning the expected headers will not passed to libcurl. For redirections, we may pick up headers from the previous request. 
I think it must be acceptable to use the incoming URLRequest parameter instead of …
=> Fix for SR-2913 - HTTP headers not picked up

Foundation/NSFileHandle.swift, TestFoundation/TestNSFileHandle.swift
Not sure if the unit test is needed. I may be testing OS functionality instead of Foundation.
=> Implement FileHandle.nullDevice

Foundation/NSJSONSerialization.swift, Foundation/NSNumber.swift, TestFoundation/TestNSJSONSerialization.swift
Please review!
This pull request resolves [SR-3013, "JSONSerialization coerces booleans to numbers on Linux"](https://bugs.swift.org/browse/SR-3013)., relates to [SR-72](https://bugs.swift.org/browse/SR-72)
The prevailing bug was due to a prior kludge: if the value could be coerced into an NSNumber, coerce to an NSNumber and encode. NSNumbers were (before this PR) type-opaque, so an `NSNumber(value: true)` -> `"1"`.
I resolved this by first rewriting the type checking code to use a pattern match so the intention was clearer, then added a special case for the primitive bool case. The switch statement should be a clear set of entry points for future maintainers, following the JSON spec.
Next, I implemented objCType for NSNumber. This allows us to correctly discover when an NSNumber is in …
=> [NSJSONSerialization] SR-3013 Fix incorrect boolean coercion and enhance NSNumber encoding

Docs/Status.md, Foundation/NSData.swift, Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift
Implemented `NSCoding` for `NSURLRequest` and `NSMutableURLRequest`.
Overriden `isEqual(_:)` method to conform to macOS Foundation.
Also fixed `NSData.bytes` crash when empty data was decoded. `test_NSCoding_2()` tests this crash.
=> Implementation for NS(Mutable)URLRequest NSCoding.

Foundation/NSPredicate.swift, TestFoundation/TestNSPredicate.swift
Implementation and test for `NSPredicate's` `NSCoding`, `NSCopying`.
Additionally implemented `.predicateFormat`
=> NSPredicate partial implementation

TestFoundation/TestNSArray.swift, TestFoundation/TestNSBundle.swift, TestFoundation/TestNSDictionary.swift, TestFoundation/TestNSFileManager.swift, TestFoundation/TestNSJSONSerialization.swift, TestFoundation/TestNSStream.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNSURL.swift
NSTemporaryDirectory properly checks the environment variable TMP.
=> Use NSTemporaryDirectory helper function instead of hard coding /tmp

Foundation/NSPropertyList.swift
- Going off:
https://developer.apple.com/reference/foundation/propertylistserialization/1418309-data
The `plist` in data(fromPropertyList plist: Any, format: PropertyListFormat, options opt: WriteOptions)  should be Any not AnyObject
- Also removed a seemingly unnecessary CFPropertyList cast
=> PLIST to Data alignment with Foundation

Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
This change improves the performance of serializing objects to a Data, by using String concatenation to build the result, and then convert to a Data once.  This change was developed by @shmuelk and myself.
We may want to revisit this in the future as the performance of appending to Data improves.
Note, we initially used `jsonStr.cString(using: .utf8)` to create the Data, but in testing this seemed to leak memory (perhaps this is a bug): https://github.com/IBM-Swift/SwiftyJSON/pull/22
I've provided a microbenchmark to demonstrate the effect of these changes:
Before:
```
TestFoundation/TestNSJSONSerialization.swift:760: Test Case 'TestNSJSONSerialization.test_serialization_perf' measured [Time, seconds] average: 0.463, relative standard deviation: 3.143%, values: [0.485122, 0.469292, …
```
=> Improve JSON serialization performance on Linux

TestFoundation/TestNSRange.swift
Uncommented the NSRangeFromString test, on macOS it works fine, on Linux it has to be seen if there will be issues.
=> Enable NSRangeFromString test

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSXMLParser.swift, TestFoundation/TestNSXMLDocument.swift, TestFoundation/TestNSXMLParser.swift
XMLParser was completely broken, even though the bridging was available and things are 99% complete. This PR adds a number of tests to show the problem, and fixes a number of issues:
- The contract was different from Foundation. Methods were not optional and NSError was still in use.
- There was an incorrect nullability annotation on the C Shim between libxml2. This was causing a crash when processing namespaces.
- The `bomChunk` parsing was broken. There was no way for the parser to actually be constructed.
- Some of the logic as to what values get reported to `startElement` and `endElement` I believe was wrong. I had trouble fixing the logic for the nullability changes and decided that it was easier to re-write things.
There's a lot of code in this file hasn't been spruced up in a while …
=> SR-2301 - Fix XMLParser

TestFoundation/TestNSURL.swift
When running on Darwin, the /private/ is not stripped from the
URL and so the test fails. Change the logic so that this is only
run when running on Linux platforms.
=> Fix tests when running in Darwin

Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
NSCalendar was passing the incorrect time interval for determining if a date is on the weekend.  Ucal was expecting the time interval since 1970 while NSCalendar was passing the time interval since the reference date.
That requirement is documented [here](http://www.icu-project.org/apiref/icu4c/utypes_8h.html#ace1704e9e77d407d1eaaa2e73ec0c039).
=> SR-3193, Fix NSCalendar.isDateInWeekend

Foundation/NSAttributedString.swift, TestFoundation/TestNSAttributedString.swift
This pull request implements the following `NSAttributedString` methods:
- `enumerateAttribute(_:in:options:using:)`
- `enumerateAttributes(in:options:using:)`
=> Implement attributes enumerating in NSAttributedString

Foundation/NSData.swift
The return UnsafeRawPointer constant for empty Data objects added in #710 (discussed [here](https://github.com/apple/swift-corelibs-foundation/pull/710/commits/2c198bbad663a1387be2242fb1dd9df801e18805)) is breaking 32bit compilation.
This PR fixes the issue.
=> Replacing error constant for empty NSData byte representation to a 32bit compatible value.

Foundation/NSDecimal.swift, Foundation/NSDecimalNumber.swift, TestFoundation/TestNSDecimal.swift
This fixes a couple of bugs in NSDecimal that were exposed in the implementation of NSDecimalNumber, and implements the remainder of the functionality required in order to implement the NSDecimal.scan that allows strings to be converted to wider decimals.
=> Implement remainder of NSDecimal/NSDecimalNumber

Foundation.xcodeproj/project.pbxproj, Foundation/Process.swift, TestFoundation/TestProcess.swift, TestFoundation/main.swift, build.py
=> [SR-3279] Renaming Task to Process

build.py
extra_ld_flags is overwritten in build.py
Appending the value should keep whatever value was passed at
configuration time.
=> Build LDFLAGS overwrite issue

Foundation/NSJSONSerialization.swift
Following on from #718, this change further improves performance of JSON serialization:
- In `JSONWriter.serializeJSON`, move the expensive NSNumber case (which invokes `_SwiftValue.store`) below the cases for Array, Dictionary and primitive types.
- add fast paths for Int and UInt types, which can be converted directly to a String rather than going via NSNumber.
- Equivalent changes for `isValidJSONObject`
These changes were developed by @shmuelk and myself.
Additional performance can be gained by adding similar fast paths for Double and Float, however doing so fails the tests that expect a whole number to be serialized without decimal places (eg. `Double(1.0)` -> `1`).  For that reason, I have not included a fast path for Double or Float in this PR, but I included the performance …
=> Further improve performance of JSON serialization on Linux

Foundation/NSNumberFormatter.swift, TestFoundation/TestNSNumberFormatter.swift
This PR addresses two issues that were recently raised while using the decimal style of NumberFormatter: [SR-3391](https://bugs.swift.org/browse/SR-3391) and [SR-3385](https://bugs.swift.org/browse/SR-3385). I found discrepancies in the behavior using Foundation vs what I observed in an Xcode Playground:
* The leading 0 in numbers was being dropped, as in .03 (vs 0.03 in the Playground).
* Large numbers like 987654321 were being formatted as 987,654,000 (vs 987,654,321 in the Playground).
I added a new case for `.decimal` that set attribute values to match what I observed in the NumberFormatter decimal style in the playground. I also added the above scenarios into existing test cases.
=> SR-3385 and SR-3391: NumberFormatter - update default attributes for decimalStyle

Foundation/NSURLSession/NSURLSession.swift
It should have the same completion handler type as the other two `downloadTask` methods
=> downloadTask(withResumeData: ...) signature fixed

Foundation/NSThread.swift
On macOS the threadDictionary is an NSMutableDictionary, so the objects are of type Any. For consistency, it seems this should also use Any instead of AnyObject.
I stumbled upon this when looking at making [this Regex library](https://github.com/sharplet/Regex) work on Linux. [This particular line](https://github.com/sharplet/Regex/blob/27b3aab37a6935ef7370dd06b4e47e932621e94e/Source/Regex.swift#L147) along with [this one](https://github.com/sharplet/Regex/blob/27b3aab37a6935ef7370dd06b4e47e932621e94e/Source/ThreadLocal.swift#L27) fails because `MatchResult` is a `struct` so it cannot be converted to `AnyObject`.
=> Change type of threadDictionary objects to Any

Docs/Status.md, Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/TestNSURLSession.swift
Added an implementation for `.error` property and `NSCopying` for `URLSessionTask`
Added tests.
`.cancel()` is implemented in: #689
=> Implementation of URLSessionTask '.error', NSCopying

Docs/Status.md, Foundation/NSURL.swift, TestFoundation/TestNSURL.swift
Added `NSCoding` to `NSURLQueryItem`.
Added tests.
Overriden `isEqual(_:)` to conform to MacOS Foundation.
=> [NSURLQueryItem] NSCoding Implementation

CoreFoundation/Base.subproj/CFInternal.h
HALT is only defined on i386 and x86_64 with recent changes.  This breaks the build on s390x.
=> Fix build error on s390x

Foundation/NSCFSet.swift
An upcoming change in the type checker will result in this call to
fetch() becoming ambiguous, so we need to explicitly cast the argument
to make it unambiguous.
The overloads for fetch are:
fetch(_ object: AnyObject?) -> Any?
fetch(_ object: AnyObject) -> Any
but the current call here is taking an AnyObject and returning it as an
Any? which means that both overload options would result in a
value-to-optional conversion. A current quick of the type checker
disambiguates this by chosing the version that returns an optional, but
that quirk will go away (at least under -swift-version 4).
=> Cast a function argument in order to disambiguate the intended overload.

Foundation.xcodeproj/project.pbxproj, Foundation/NSPersonNameComponents.swift, TestFoundation/TestNSPersonNameComponents.swift, TestFoundation/main.swift
- Followed pattern of `NSCalendar.swift`
- Ignored `zone` parameter, which appears to be the pattern across Foundation classes
=> [NSPersonNameComponents] Implementation of copy() and test

Foundation/NSCFDictionary.swift
Apply the same fix that went into
d9cdc7ecdb91fdfd738b7347c69a6fa3b6d5d2be to another location.
After an upcoming type checker change the previous code would be
considered ambiguous.
=> Fix another case of potential overload ambiguity.

Foundation.xcodeproj/project.pbxproj, Foundation/NSLengthFormatter.swift, TestFoundation/TestNSLengthFormatter.swift, TestFoundation/main.swift
- Implementation of all unimplemented functions in `NSLengthFormatter.swift`
- Test cases covering all functions, including paths for US, metric system, and `isForPersonHeightUse`
- Includes workaround for [issue](https://bugs.swift.org/browse/SR-3202) in which Locale attributes are not populated
=> [LengthFormatter] Implementation of LengthFormatter and tests

Foundation/Bridging.swift, Foundation/Dictionary.swift, Foundation/NSArray.swift, Foundation/NSCFArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSCFSet.swift, Foundation/NSDictionary.swift, Foundation/NSOrderedSet.swift, Foundation/NSPropertyList.swift, Foundation/NSSet.swift, Foundation/NSUserDefaults.swift
Back out the changes from d9cdc7ecdb91fdfd738b7347c69a6fa3b6d5d2be and
15769584ce4b4e450e893f33a550e2c23f55db30, and instead use an argument
label to disambiguate calls to `fetch`.
=> Use an argument label to disambiguate calls to _SwiftValue.fetch.

Foundation/NSDateFormatter.swift, TestFoundation/TestNSDateFormatter.swift
I've implemented the missing method in DateFormatter.
I've only two questions:
1. I've called the relative class method using explicitly the `DateFormatter` class, it is better using the new `type(of:)`?
2. There are no tests for the class method `dateFormat(fromTemplate:opts:locale:)`to get inspiration any guidance on how to add for both the class and the instance method?
=> Implemented setLocalizedDateFormatFromTemplate

CoreFoundation/Base.subproj/CFSortFunctions.c, CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/NumberDate.subproj/CFTimeZone.c, CoreFoundation/PlugIn.subproj/CFBundle_InfoPlist.c, CoreFoundation/PlugIn.subproj/CFBundle_Resources.c, Foundation/NSHost.swift, Foundation/NSPlatform.swift
This PR fixes a few issues when trying to compile for Android target.
Adding comments inline.
=> Android target issues

Foundation/Calendar.swift, Foundation/NSTimer.swift, Foundation/URLRequest.swift
Invalid syntax in `parameter` comment for quick help.
=> Fix comment for parameters

lib/product.py, lib/target.py
* SDK name added for Android. The OSType remains as linux, but the platform specific files should be retrieved from the `android` directory instead of `linux`.
* conformance_begin/end was using a hardcoded `linux` directory. Now it's pulling `swift_being.o`/`swift_end.o` object files from the correct directory. 
This last point should probably be double checked in FreeBSD. I'll try to set up an environment for testing, but is there anyone I can reach to confirm this last point?
=> Android SDK name changes.

Foundation/NSURLProtocol.swift
=> Update URLProtocolClient.urlProtocol(_:didFailWithError:) to match the Darwin version

CoreFoundation/Base.subproj/CFAsmMacros.h
libFoundation.so is flagged as requiring an executable stack on Linux, although it does not. This is due to GNU as behavior.
Please see discussion at https://bugs.swift.org/browse/SR-2700?jql=text%20~%20%22executable%20stack%22
This was already intended to be solved by https://github.com/apple/swift-corelibs-foundation/pull/649/, but did not work as intended in Ubuntu. Checking for \_\_GNUC\_\_ in addition resolves the issue.
=> Fix libFoundation.so being flagged as requiring executable stack

Foundation/Data.swift
This is a coordinated change with [this PR](https://github.com/apple/swift/pull/6601) on the Swift repo.
Since `UnsafeMutablePointer.initialize(from:)` is memory-unsafe with collections that underreport their count, it is being migrated to be on `UnsafeMutableBufferPointer` to avoid buffer overruns.
As part of this, `Sequence. _copyContents(initializing:)` is being altered to take a buffer not a pointer. This is an internal underscore protocol so not user-impacting, but corelibs-foundation does use it and needs to change at the same time.
=> [stdlib] Implement SE-147: Move initialize(from:) from Pointer to BufferPointer

Foundation/NSURLSession/NSURLSessionTask.swift
- https://developer.apple.com/reference/foundation/urlsessionstreamtask/1411604-readdata
- https://developer.apple.com/reference/foundation/urlsessionstreamtask/1411602-write
=> [URLSessionStreamTask] Update `readData` and `write` methods to match the Darwin version

Foundation/Data.swift
Referencing private or internal declarations from an @inline(__always)
body can lead to SIL verifier and linker failures, so now we diagnose
and prohibit it.
Mark the entity in question public, or if it is not part of user-visible
API, internal and @_versioned.
See <https://github.com/apple/swift/pull/6669>.
=> Update for new rules on @inline(__always) function bodies

Foundation/Data.swift
Reverts apple/swift-corelibs-foundation#772
=> Revert "Update for new rules on @inline(__always) function bodies"

Foundation/CGFloat.swift, build.py, lib/target.py
These changes enable building on the powerpc family of targets - powerpc (32bit BE), powerpc64 (64bit BE) and powerpc64le (64bit LE).  Only tested on powerpc64le since that's the only target properly supported in Swift overall.
=> Enable building on powerpc

Foundation/NSURLSession/NSURLSessionTask.swift
https://developer.apple.com/reference/foundation/urlsessiontask/1660699-url_session_task_priority
=> URLSessionTaskPriority... constants should be class properties

Foundation/NSLocale.swift, Foundation/NSOperation.swift, Foundation/NSURLCredentialStorage.swift, TestFoundation/TestNSLocale.swift
- `NSLocale.currentLocaleDidChangeNotification`
- `OperationQueue.defaultMaxConcurrentOperationCount`
- `Notification.Name.NSURLCredentialStorageChanged`
=> Change some global constants to type properties to match the Darwin version

Foundation/CharacterSet.swift, TestFoundation/TestNSCharacterSet.swift
This is a PR that parallels apple/swift#5201.
Execution is interrupted when `CharacterSet.subtracting(_:)` is invoked. The underlying reason is that `subtracting(_:)` is a default implementation that calls `symmetricDifference(_:)`, but `CharacterSet.symmetricDifference(_:)` invokes `subtracting(_:)`. This PR implements `CharacterSet.subtracting(_:)` and `CharacterSet.subtract(_:)`.
A new test has been added for this code; however, as reported in [SR-2509](https://bugs.swift.org/browse/SR-2509), `CharacterSet.union(_:)` is not currently working in corelibs-foundation, so the test must be disabled in this repo until that entirely separate issue is resolved.
Resolves [SR-2503](https://bugs.swift.org/browse/SR-2503).
=> [SR-2503] Implement subtraction for CharacterSet

Foundation/NSNotificationQueue.swift, TestFoundation/TestNSNotificationQueue.swift
`Coalescing` itself should be renamed as well in a separate pull request.
=> [NotificationQueue] Rename Coalescing constants to match the Darwin version

Foundation/NSFileHandle.swift, TestFoundation/TestNSFileHandle.swift
I'm not sure why only `readCompletionNotification` is defined in Foundation APINotes on Darwin: https://github.com/apple/swift/blob/swift-DEVELOPMENT-SNAPSHOT-2017-01-05-a/apinotes/Foundation.apinotes#L1356-L1357.
=> [FileHandle] Update NSFileHandleReadCompletion to match the Darwin version

Foundation/IndexSet.swift, Foundation/NSCache.swift, Foundation/NSCoder.swift, Foundation/NSConcreteValue.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSUUID.swift, Foundation/NSValue.swift, Foundation/String.swift
Using
- `unsafeDowncast`
- `UnsafeRawPointer` initializer
- `UnsafeMutableRawPointer` initializer
- `assumingMemoryBound`
according to the warnings.
=> [gardening] Address some unsafeBitCast warnings

Tools/plutil/main.swift
`fileHandleWithStandardInput()` has been renamed to `standardInput`.
=> [plutil] Fix build failure

Foundation/NSNotificationQueue.swift
(Renaming `NotificationCoalescing` to `Coalescing` on Darwin might be an option but I'm not sure)
=> [NotificationQueue] Rename Coalescing to NotificationCoalescing to match the Darwin version

CoreFoundation/Base.subproj/CFRuntime.c
The symbol does exist in `libSystem.B.dylib` on 10.12 but does not on 10.11 (which was introduced in #709).
The issue should have been happening in https://github.com/apple/swift-corelibs-xctest/pull/176 and https://github.com/apple/swift-corelibs-xctest/pull/182.
~~The fix is based on this: https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html.~~
=> Delete `_os_log_set_nscf_formatter` related lines to make the framework run on macOS 10.11

Tools/plutil/main.swift
- `ExecutionMode`
- `ConversionFormat`
- `OptionParseError`
- `DisplayType`
=> [plutil] Rename enum cases to follow API Design Guidelines

Foundation/NSNotificationQueue.swift, TestFoundation/TestNSNotificationQueue.swift
- `defaultQueue()` -> `default`
- `enqueueNotification()` -> `enqueue()`
- `dequeueNotificationsMatching()` -> `dequeueNotifications()`
=> [NotificationQueue] Rename APIs to match the Darwin version

Tools/plutil/main.swift
=> [plutil][gardening] Use `switch` for type casting

Foundation/Data.swift, TestFoundation/TestNSData.swift
=> Correct sequence initializers for Data when repeating:count: is called and add a memset fast-path

Foundation/NSAffineTransform.swift, TestFoundation/TestNSAffineTransform.swift
This is based on https://github.com/apple/swift/pull/6802.
=> [AffineTransform] Replace `M_PI` with `CGFloat.pi`

Foundation/Boxing.swift
Found related errors at https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-xctest-PR-osx/154/consoleFull#-824480375ee1a197b-acac-4b17-83cf-a53b95139a76.
This is the same as #772.
/cc @slavapestov
=> Add `@_versioned` attribute to _MutableHandle._pointer

Foundation/NSScanner.swift, TestFoundation/TestNSString.swift
https://bugs.swift.org/browse/SR-3366
=> Fix `String.getLineStart(_:end:contentsEnd:for:)` returns wrong start

Docs/Status.md, Foundation/NSKeyedUnarchiver.swift, Foundation/NSPropertyList.swift, Foundation/NSStream.swift, TestFoundation/TestNSPropertyList.swift
Currently toll-free bridging between `InputStream` and `CFReadStream` is not implemented, so `InputStream._stream` is exposed and used instead.
=> [PropertyListSerialization] Possible implementation of `propertyList(with:options:format:)`

CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h, Foundation/NSHost.swift
Related to #638.
- Import `<ifaddrs.h>` in `SwiftRuntime/CoreFoundation.h`
- Use `sa_family_t` which is `UInt8` on macOS instead of explicit `UInt16`
=> Fix building NSHost.swift on macOS

Foundation/NSFileHandle.swift
=> add `@discardableResult` to `seekToEndOfFile()`

Foundation/NSFileManager.swift
=> add `@discardableResult` to `changeCurrentDirectoryPath(_:)`

Foundation/NSError.swift
Formerly the return value is always empty.
=> [CocoaError][URLError] Return correct userInfo from `_nsUserInfo`

Foundation/NSObject.swift
This pull request adds documentation comments for the following **public**/**open** declarations:
_Classes:_
_Protocols:_
_Functions:_
All the comments have been carefully reviewed. The terms referring to Objective-C semantics
have been substituted with ones more appropriate for Swift semantics (e. g. "receiver" → "instance" etc.).
| [Jazzy](https://github.com/realm/jazzy) | Percentage of documented declarations in Foundation |
|:---------------------------------------:|:----------------------------------------------------:|
| Before                                  | 23%                                                  |
| After                                   | 27%                                                  |
=> [Documentation] Add doc comments for NSObject

Foundation/NSCalendar.swift, TestFoundation/TestNSCalendar.swift
With basic single-component (second) test
Issue reported by Malcolm Barclay via swift-corelibs-dev
=> Calendar components from:to: date fix

Foundation/NSCoder.swift
This pull request adds documentation comments for the following **public**/**open** declarations:
_Classes:_
_Protocols:_
_Enums:_
All the comments have been carefully reviewed. The terms referring to Objective-C semantics
have been substituted with ones more appropriate for Swift semantics (e. g. "receiver" → "instance" etc.).
| [Jazzy](https://github.com/realm/jazzy) | Percentage of documented declarations in Foundation |
|:---------------------------------------:|:----------------------------------------------------:|
| Before                                  | 27%                                                  |
| After                                   | 29%                                                  |
=> [Documentation] Add doc comments for NSCoder

Foundation/NSError.swift
Reverts apple/swift-corelibs-foundation#833
=> Revert "[NSError] Use Error for user info providers to match the Darwin version"

Foundation/NSLocale.swift
Reverts apple/swift-corelibs-foundation#827
=> Revert "[gardening][NSLocale] Move operators into types"

CoreFoundation/Base.subproj/CFBase.h
SR-3658 – Fix error in importing Foundation under Linux. This commit may resolve the described error.
Honestly, I have no idea if this'll work. My machine does not have the horsepower to compile this project, but at the very least maybe the CI can take a crack at it. From a cursory review this line seems unnecessary.
=> SR-3658 – Fix error in importing Foundation

Foundation/NSKeyedArchiver.swift
This pull request adds documentation comments for the following **public**/**open** declarations:
_Classes:_
_Protocols:_
All the comments have been carefully reviewed. The terms referring to Objective-C semantics
have been substituted with ones more appropriate for Swift semantics (e. g. "receiver" → "instance" etc.).
| [Jazzy](https://github.com/realm/jazzy) | Percentage of documented declarations in Foundation |
|:---------------------------------------:|:----------------------------------------------------:|
| Before                                  | 29%                                                  |
| After                                   | 29%                                                  |
=> [Documentation] Add doc comments for NSKeyedArchiver

Foundation/FoundationErrors.swift
This pull request adds documentation comments for the following **public**/**open** declarations:
_Global constants:_
| [Jazzy](https://github.com/realm/jazzy) | Percentage of documented declarations in Foundation |
|:---------------------------------------:|:----------------------------------------------------:|
| Before                                  | 29%                                                  |
| After                                   | 30%                                                  |
=> [Documentation] Add doc comments for Foundation errors

CoreFoundation/Base.subproj/CFUtilities.c
[SR-3662](https://bugs.swift.org/browse/SR-3662): Restore `NSLog` functionality on linux
=> SR-3662: Restore NSLog functionality on linux

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/RunLoop.subproj/CFMachPort.c
`os_log` calls back into CF on Darwin (for the ability to print `NSObject` types). However, this CF that we're testing in `swift-corelibs-foundation` is not the system one, and the types don't implement the expected forwarding protocols. Better to just disable this on all platforms.
Fixes SR-3703.
=> Make sure that os_log is turned off for both Darwin and Linux

CoreFoundation/Base.subproj/CFUtilities.c
[SR-3662](https://bugs.swift.org/browse/SR-3662): Restore `NSLog` functionality on linux
=> SR-3362: Restore NSLog functionality on linux [Regression]

Foundation.xcodeproj/project.pbxproj, Foundation/NSError.swift, TestFoundation/TestNSError.swift, TestFoundation/main.swift
This should return an appropriate value instead of the fixed "The operation could not be completed".
=> [Error] Implement `localizedDescription` using `_swift_Foundation_getErrorDefaultUserInfo`

Foundation/NSURLSession/HTTPBodySource.swift
I came across this bug while investigating another URLSession failure. URLSession uses the CURLOPT_READFUNCTION callback to write data to a socket during uploads. This writing happens in chunks of 16K. The `getNextChunk` is used to split the body which is wrapped in DispatchData into a writable chunk (typically 16K with libcurl) and the remaining data. When the remaining data is lesser than 16K, we do not split the data and send it as is, making sure that the next call to `getNextChunk` will indicate completion (return length = 0). However, because we set data to `nil`, the last call to `getNextChunk` in a large transfer is bound to crash [here](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSURLSession/HTTPBodySource.swift#L79). 
Instead of setting data to …
=> [URLSession]Fix a crash in _HTTPBodyDataSource.getNextChunk()

Foundation/NSHTTPCookie.swift, TestFoundation/TestNSHTTPCookie.swift
In porting some code from macOS to Linux, I noticed that the API signatures in this method do not match [the documentation](https://developer.apple.com/reference/foundation/httpcookie/1393011-cookies).
=> [HTTPCookie] Make cookies(withResponseHeaderFields:for:) signature match Darwin

Docs/Status.md, Foundation/NSAffineTransform.swift, TestFoundation/TestNSAffineTransform.swift
Implemented `NSCoding` protocol and `isEqual` to match macOS Foundation.
=> [NSAffineTransform] NSCoding implementation

CoreFoundation/Base.subproj/ForFoundationOnly.h
A change made in #663 was overwritten by #709. This change restores the switch from `#import` to `#include`.
The reason for this change is: Clang's MSVC compatibility does not handle `#import` statements outside of of objc.
> `#import` of type library is an unsupported Microsoft feature
=> Restore use of #include

Foundation/NSObject.swift
Reverts apple/swift-corelibs-foundation#839
https://github.com/apple/swift-corelibs-foundation/pull/833#issuecomment-277047371
=> Revert "Revert "[gardening][NSObject] Move operators into types""

Foundation/NSError.swift
Reverts apple/swift-corelibs-foundation#838
https://github.com/apple/swift-corelibs-foundation/pull/833#issuecomment-277047371
=> Revert "Revert "[NSError] Use Error for user info providers to match the Darwin version""

Foundation.xcodeproj/project.pbxproj, Foundation/NSError.swift, TestFoundation/TestNSError.swift, TestFoundation/main.swift
Cherry picks #810.
This should return an appropriate value instead of the fixed "The operation could not be completed".
=> [3.1][Error] Implement `localizedDescription` using `_swift_Foundation_getErrorDefaultUserInfo`

Foundation.xcodeproj/project.pbxproj, Foundation/NSEnergyFormatter.swift, TestFoundation/TestNSEnergyFormatter.swift, TestFoundation/main.swift
Implemented all EnergyFormatter functions and created tests. Tested on macOS and Ubuntu 16.04.
=> [EnergyFormatter] Implementation and tests

TestFoundation/TestNSString.swift
=> [TestNSString] Fix a failure of `comparisonTests` on macOS

TestFoundation/TestNSNumber.swift
The default C char on powerpc is unsigned (as on arm).
Add powerpc64 and powerpc64le as extra conditions to the
logic that already disabled the problematic test cases
for arm.
=> Disable failing TestNSNumber cases on powerpc64

Foundation/NSRange.swift
Add missing powerpc64 and powerpc64le cases to NSRange's objCType func.
=> add powerpc architecture variants in objCType()

Foundation/NSFileManager.swift, TestFoundation/TestNSFileManager.swift
Fixed group owner name assigned to `.groupOwnerAccountID` instead of `.groupOwnerAccountName` in `FileManager.attributesOfItem(atPath:)`
=> Fixed file's groupOwnerName in attributesOfItem()

CoreFoundation/Collections.subproj/CFData.c
PR which addressed the memory leak in NSMutableData  through  apple/swift-corelibs-foundation#380  is missing in the latest code as well as the Swift-3.1 branch.Hence it resulted in the regression with latest code base.Please merge this on priority .
=> Performance regression in NSMutableData[SR-3966]

Docs/Status.md, Foundation.xcodeproj/project.pbxproj, Foundation/NSCache.swift, TestFoundation/TestNSCache.swift, TestFoundation/main.swift
An attempt to fix an issue with `NSCache` storing every key-value pair that's been set with `.setObject(...)` method. I've tried to implement an Darwin's Foundation behavior as much as possible.
Added some unit tests that check `NSCache` work.
Also changed default values for `.totalCostLimit` and `.countLimit` to match Darwin's Foundation.
Issue: [SR-3904](https://bugs.swift.org/browse/SR-3904)
=> [NSCache] [SR-3904] Fix for object storage.

CoreFoundation/URL.subproj/CFURLComponents.c, CoreFoundation/URL.subproj/CFURLComponents.h, Foundation/NSURL.swift
PR for master branch : #897
Commit Hash for master branch PR : ba78d522f89b64936ccaab647ee4536fab3718cf
=> [SR-3481] Fix for memory leak in NSURLComponents

TestFoundation/main.swift
URLSessions tests had been disabled because of a libkqueue failure seen in CI. See: https://bugs.swift.org/browse/SR-3464
Given that we've done away with libkqueue in Dispatch and SR-3464 is no longer relevant, can we re-enable the URLSession tests in TestFoundation? 
cc @gparker42
=> Enable URLSession tests in TestFoundation

Foundation/NSByteCountFormatter.swift, TestFoundation/TestNSByteCountFormatter.swift
Implemented ByteCountFormatter and created tests. 
All tests run and pass on MacOS.
=> Initial implementation of ByteCountFormatter

Foundation/NSString.swift, TestFoundation/TestNSString.swift
I think this is just one way to fix: https://bugs.swift.org/browse/SR-2483 
I've documented some additional findings in the bug report.
=> Fix for a crash in String.substring(with:) [SR-2483]

Foundation/NSURLSession/NSURLSessionTask.swift
There is only one place in URLSession where we are printing a warning message during normal execution. We've had a user complain about this message creating a `lot of noise`. I'm moving this warning message under the control of the `URLSessionDebug` env variable.
=> [gardening]print warning only if URLSessionDebug is set

Foundation/NSData.swift, TestFoundation/TestNSData.swift
Came across this using NSMutableData on Linux. Replace range with nil pointer and length 0 does nothing when it should delete bytes in the range.
=> NSMutableData compatiblity with macOS

Docs/Status.md, Foundation/NSURL.swift, Foundation/URL.swift, TestFoundation/TestNSURL.swift
Implemented and renamed method for `NSURL` to match Darwin's version.
Added method `. checkResourceIsReachable` to `URL` that matches Darwin's Foundation.
=> [NSURL] Implementation of '.checkResourceIsReachable'

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/NumberDate.subproj/CFNumber.c, Foundation.xcodeproj/project.pbxproj, Foundation/Bridging.swift, Foundation/NSCFBoolean.swift, Foundation/NSCoder.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSNumber.swift, Foundation/NSSwiftRuntime.swift, TestFoundation/TestNSNumber.swift, build.py
This converts kCFBooleanTrue and kCFBooleanFalse into true and false and adds subclassing callout hooks for CFNumber to invoke swift routines.
Additionally it corrects the class callouts for cluster types when archiving plist types such that it invokes the class for coder instead of relying on the distinct type of the object being passed.
=> Account for kCFBooleanTrue and kCFBooleanFalse being present in bridged payloads

TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift
As discussed in #911, I've commented out the actual test (It's fail otherwise), but all needed functionality is included.
=> [Test][NSURLSession] Chunked response

Foundation/NSURLSession/EasyHandle.swift, Foundation/NSURLSession/MultiHandle.swift, Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift
Currently, we use the `URLSessionConfiguration.timeoutIntervalForRequest` value to trigger a timeout. https://bugs.swift.org/browse/SR-2681 reported a bug in which the timeout counter is not reset on every data transfer. 
This is from the API doc:
```
The request timeout interval controls how long (in seconds) a task should wait for additional data to
arrive before giving up. The timer associated with this value is reset whenever new data arrives. 
When the request timer reaches the specified interval without receiving any new data, it triggers a timeout.
```
This patch tries to reuse the `_TimeoutSource` class which is currently used to trigger timeouts in MultiHandle, with some modifications. We reset the timer every time data is available.
=> [URLSession]Fix for a timeout bug(SR-2681)

Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift
=> Master merge for #915

Foundation/NSOrderedSet.swift, TestFoundation/TestNSOrderedSet.swift
`NSMutableOrderedSet` has a subscript setter imported to Darwin platforms, but the setter doesn't exist on Linux. 
This PR adds a subscript setter to `NSMutableOrderedSet` as a shortcut to `replaceObject(at:with:)`
=> [SR-4242] Add NSMutableOrderedSet subscript setter that is missing from non-Darwin

TestFoundation/TestNSNotificationQueue.swift
These tests are failing intermittently in CI.
=> [test] Temporarily disable TestNSNotificationQueue pending rdar://31106944

Foundation/NSOperation.swift, TestFoundation/TestNSOperationQueue.swift
Following on from the discussion on the swift-corelibs-dev mailing list, here's a PR to add `willChangeValue()` and `didChangeValue()` to `Operation`, in support of operations that are asynchronous from an operation queue.
=> [Operation] add willChangeValue() and didChangeValue()

Foundation/NSRegularExpression.swift, TestFoundation/TestNSRegularExpression.swift
According to the [documentation](https://developer.apple.com/reference/foundation/nsregularexpression/1410900-init), the `options` parameter to the `NSRegularExpression` initializer should have a default value of `[]`.  This was not correct in swift-corelibs-foundation.
Correct the signature of the initializer and update one of the existing tests to cover this case.
=> NSRegularExpression: Add default value to init() `options` parameter

Foundation/Progress.swift
Looks like it should be called when we are already paused instead.
=> Bugfix: newly assigned pausingHandler was called if the Progress is already cancelled

Foundation/NSError.swift
This PR removes `final` from a few `var`s in the `__BridgedNSError` protocol. SR-1762 / apple/swift#8010 will generate a warning or error when `final` is present in a protocol extension. This PR will remove the warning, and will not modify dispatch behavior in any way.
=> Remove final from vars in error related protocol extensions

Foundation/NSOrderedSet.swift, TestFoundation/TestNSOrderedSet.swift
Bug in NSOrderedSet index check
=> Fix bug [SR-4391]: index check should be `||` instead of `&&`

Foundation/Data.swift, TestFoundation/TestNSData.swift
Addresses the following issues:
https://bugs.swift.org/browse/SR-4462
https://bugs.swift.org/browse/SR-4473
rdar://problem/31361522
This also brings Data.swift on par with the implementation in the Foundation overlay. Making the slice of Data to be Data.
=> Address slice regions that incorrectly fetched from the wrong offset of the backing buffers

CoreFoundation/String.subproj/CFCharacterSet.c
The code was originally shifting a 32-bit value by 32 bits in
some cases, which is undefined behavior. The intent was that
all bits would be shifted out, leaving a value of 0 to perform
computation with. We now treat the value as 64-bits for the shift
and re-cast to 32-bits for the computation.
=> Fix bit shift math in CFCharacterSet equality code

CoreFoundation/URL.subproj/CFURLComponents.c
Addresses a few leaks:
* during deallocation of a CFURLComponentsRef, _portComponent was leaked
* _CFURLComponentsCopyURLRelativeToURL failed to CFRelease a local
* _CFURLComponentsCopyQueryItems failed to CFRelease a local
Incomplete copy in _CFURLComponentsCreateCopy:
* failed to transfer _passwordComponentValid along with _passwordComponent
* failed to transfer _parseInfo
=> Fix a few leaks and an incomplete copy in CFURLComponents

Foundation/Data.swift, TestFoundation/TestNSData.swift
this cherry picks the Data fixes for indexing and slicing:
Address slice regions that incorrectly fetched from the wrong offset of the backing buffers (#929)
* Update Data to be in sync with Foundation overlay
* Account for slice starts in appending, replacing subranges and fetching unsafe byte pointers
Correct Data slice iteration to be indexed by the startIndex to the endIndex
=> Swift 3.1 branch data fixes

Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
As a follow on from #723 I've created fast path options for Int and UInt to further improve the performance of JSON Serialization. 
Below are some results I obtained by using a slightly modified version of the [benchmark](https://github.com/djones6/swift-corelibs-foundation/commit/867109e253550e4d1bcb99cfc681fdb02ce0f566) @djones6 developed, increased to 1000 repetitions and varying the payload size. I've included times for `String(describing:)` as that was the original proposed solution in #723 and felt it would offer a good comparative view.  
| Payload type:              |  Average Time (2 digit numbers) | Average Time (10 digit numbers)        | 
|------|:-------:|:------:|
| Baseline (current `master`)     | 1.932 | 2.631
| With String(describing:) (as rejected in #723 ) | 0.877 | …
=> Added fast path for Int and UInt

TestFoundation/TestNSXMLDocument.swift
Plist DTDs were recently moved from
http://www.apple.com/DTDs/PropertyList-1.0.dtd to
https://www.apple.com/DTDs/PropertyList-1.0.dtd (note the https).
libXML, however, is not setup to request DTDs from secure domains and
fails.  This causes a spurious failure in the validation test checking
for failure and a real failure in the validation test checking for
success.  In either case, these tests introduce a hard dependency on
the internet into the test suite.  I’ve disabled them for now and filed
rdar://31567922 about this.
=> Disable tests that use the internet

Foundation/NSHTTPCookie.swift
This PR is relating to [SR-3821](https://bugs.swift.org/browse/SR-3821)
The comment seems to suggest that supplying a value for `path` is optional and if a value isn't provided it'll either infer from `HTTPCookiePropertyKey.originURL` or use a default of "/". None of those seem to be the case though, and `HTTPCookie([...])` will return `nil` if you haven't provided a value for `path`. 
Tracked down some [documentation](https://developer.apple.com/reference/foundation/httpcookie/1392975-init) to support this as well.
=> Update HTTPCookiePropertyKey.path comment

CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/CharacterSet.swift, Foundation/Measurement.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSMeasurementFormatter.swift, Foundation/NSString.swift, Foundation/ReferenceConvertible.swift, Foundation/UUID.swift, TestFoundation/TestNSURL.swift, TestFoundation/TestNSURLSession.swift, TestFoundation/TestNSXMLDocument.swift
Reduce the noise from excessive warnings. Most of these are based on the fixits emitted by the compiler
=> Minor warning fixes

Foundation/NSUUID.swift
Cherry-pick #906 for Swift 3.1.
=> [3.1] Fix for memory leak in NSUUID

build.py
Ubuntu on Raspberry Pi reports "arm-linux-gnueabihf". Since it still needs to link curl, I added the check for this triple ending.
=> Fix building on RasPi

CoreFoundation/Locale.subproj/CFLocale.c
* Adds missing mutex unlock in an error path
* Fixes use of an incorrect local variable
* Addresses a few areas where _prefs member was assumed to be non-NULL
* Fix to __CFLocaleGetMeasurementSystemGuts and __CFLocaleCopyTemperatureUnit
modelled after __CFLocaleCopyCollatorID
* Fix to __CFLocaleEqual handles the case where one or both CFLocales
have NULL _prefs.
=> Fix a few small bugs in CFLocale

Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/TestNSURLSession.swift
Fix for https://bugs.swift.org/browse/SR-3463
=> [SR-3463][URLSession] config.httpAdditionalHeaders isn't picked up

Foundation/NSURLSession/MultiHandle.swift
This race condition is a result of a unique sequence of events in the *Foundation-libcurl-libdispatch* interplay. Details of the issue can found [here](https://bugs.swift.org/browse/SR-4567). This PR proposes a way to fix that race condition. This wouldn't have been possible without @dgrove-oss 's work on this issue, from the Dispatch angle, and his help on narrowing down on the actual problem at hand. 
**Short description of the issue**
The URLSession implementation in swift-corelibs-foundation uses libcurl for HTTP support and libdispatch as the events library. There is a unique way in which Foundation, Dispatch and libcurl function and they interplay can lead to race conditions which could cause  a hang or URLSessionTasks timing out with no response. I try to explain this problem in …
=> [URLSession](SR-4567) Fix for a race condition in URLSession

Foundation/NSDecimal.swift
Since `Decimal` does not conform to `FloatingPoint` protocol, [this fix](https://github.com/apple/swift/pull/3796/commits/192c11217fe0c1a1821004b34434ffe523875707) does not apply.
=> Arithmetic methods for Swift 3 compatibility

CoreFoundation/Base.subproj/CFInternal.h
Restore workaround for android initially introduced int https://github.com/apple/swift-corelibs-foundation/pull/622
https://github.com/SwiftJava/swift-corelibs-foundation/commit/6213cbabce1a4c3d9ac1573aef4aaaa8b102953b
Refix: 
https://bugs.swift.org/browse/SR-2587 
https://bugs.swift.org/browse/SR-2588
same as #957 but for swift-3.1-branch
=> Restore android workaround for CONST_STRING_DECL [swift-3.1]

CoreFoundation/Base.subproj/CFInternal.h
Restore workaround for android initially introduced int https://github.com/apple/swift-corelibs-foundation/pull/622
https://github.com/SwiftJava/swift-corelibs-foundation/commit/6213cbabce1a4c3d9ac1573aef4aaaa8b102953b
Refix: 
https://bugs.swift.org/browse/SR-2587 
https://bugs.swift.org/browse/SR-2588
=> Restore android workaround for CONST_STRING_DECL

Foundation.xcodeproj/project.pbxproj, Foundation/NSISO8601DateFormatter.swift, TestFoundation/TestNSISO8601DateFormatter.swift, TestFoundation/main.swift
This is a class that was recently added to Darwin and would be great if it was added into swift-corelibs-foundation as well to keep Darwin and Linux more in sync.
=> Add NSISO8601DateFormatter stub

lib/phases.py
This is a prerequisite for: https://github.com/apple/swift/pull/8861
=> Force use of Swift 3 compatibility mode to compile sources.

TestFoundation/TestNSURLSession.swift, TestFoundation/main.swift
@parkera @phausler 
URLSession tests seem to be breaking the CI frequently - [SR-4647](https://bugs.swift.org/browse/SR-4647) and [SR-4655](https://bugs.swift.org/browse/SR-4655)
While working on [SR-4647](https://bugs.swift.org/browse/SR-4647), I've seen some very intermittent failures (reproducing almost 1/100 runs). Initial investigation did not lead me to suspect any of the recent fixes - #949, #927 or #916 - so, I can't be sure we are seeing a regression.
Would it be acceptable to disable URLSession tests while we investigate  [SR-4647](https://bugs.swift.org/browse/SR-4647) and [SR-4655](https://bugs.swift.org/browse/SR-4655) ?
=> Disable URLSession tests (SR-4655)

CoreFoundation/Base.subproj/CFFileUtilities.c, CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation.xcodeproj/project.pbxproj, Foundation/NSHTTPCookieStorage.swift, TestFoundation/TestNSHTTPCookieStorage.swift, TestFoundation/XDGTestHelper.swift, TestFoundation/main.swift, build.py, lib/phases.py
This is an unpolished implementation of the XDG File specification. Have referred to related work started by Tony Parker in the repo: https://github.com/parkera/swift-corelibs-foundation/tree/parkera/xdg_implementation
Note that the tests for the API implementation have been done on my local build setup. The same are not available in the committed changes here as they involve adding API in the Foundation to access the CoreFoundation implementation that is done. 
Please suggest if there is an alternate way of adding tests.
=> Implementation of XDG File specification and a basic implementation of HTTPCookieStorage

Docs/Status.md, Foundation/Process.swift, TestFoundation/TestProcess.swift
This is needed before #963 can be backported to the 3.1 branch. It is a cherry-pick of #844.
=> [3.1] [Process] Implement `terminationReason`

CoreFoundation/Base.subproj/CFFileUtilities.c, CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation.xcodeproj/project.pbxproj, Foundation/NSHTTPCookieStorage.swift, TestFoundation/TestNSHTTPCookieStorage.swift, TestFoundation/XDGTestHelper.swift, TestFoundation/main.swift, build.py, lib/phases.py
Now that #889 is merged to `master` we would like to add this to the 3.1 branch too.
=> [3.1] Backport HTTPCookieStorage

lib/phases.py
This technically changes anything that uses the SwiftExecutable to build
as Swift 3 as well.
=> Force tests to build as Swift 3.

CoreFoundation/Base.subproj/CFRuntime.c
AnyObject is now a special type and no longer a protocol, which changes the mangling as soon as the associated Swift PR is merged. There is no functional change here.
=> Update for AnyObject nukage

CoreFoundation/Base.subproj/CFRuntime.c
Swift changed the mangling for AnyObject in master, but not yet in swift-4.0-branch.
Foundation recently did not have a swift-4.0-branch. Now that it does, revert the change so that Foundation matches Swift across the two swift-4.0-branch branches.
=> Revert "Update for AnyObject nukage"

Foundation/NSData.swift
Delete 2 constraints causing warnings in NSData.swift introduced from https://github.com/apple/swift/commit/ddc2775530bb45cd3231677909ee4d06361ebd0d
Compiler warnings suggest redundant last 2 constraints are implied by Collection:
~~~~
Foundation/NSData.swift:590:253: warning: redundant same-type constraint 'T.Iterator.Element' == 'T.SubSequence.Iterator.Element'
private static func searchSubSequence<T : Collection, T2 : Sequence>(_ subSequence : T2, inSequence seq: T,anchored : Bool) -> T.Index? where T.Iterator.Element : Equatable, T.Iterator.Element == T2.Iterator.Element, T.SubSequence.Iterator.Element == T.Iterator.Element, T.Indices.Iterator.Element == T.Index {
^
Foundation/NSData.swift:590:47: note: previous same-type constraint 'T._Element' == 'T.Iterator.Element' implied here …
=> Delete redundant constraints in NSData.swift causing warnings

CoreFoundation/NumberDate.subproj/CFNumber.c
CoreFoundation assumed the size of a `struct __CFNumber` (which contains a `CFRuntimeBase` and an `int64_t`) would be the size of a `CFRuntimeBase` plus 8 bytes.
This assumption may be true on some platforms, but on my Raspberry Pi, the size of a `CFRuntimeBase` was 20 bytes.  The compiler inserted four bytes of padding before the `int64_t` to align it to an 8-byte boundary, causing the structure to take up 32 bytes instead of the 28 bytes the code allocated.  Writing to the `int64_t` overwrote some of `malloc`'s internal bookkeeping information and caused a crash.
I changed the code to use a couple of `sizeof`s to calculate the extra space to allocate, like the rest of CoreFoundation does (see [this search](https://github.com/apple/swift-corelibs-foundation/search?utf8=✓&q=_CFRuntimeCreat …
=> Don't assume the size when allocating a CFNumber

Foundation/FileManager.swift, Foundation/NSDecimalNumber.swift, Foundation/NSHTTPCookie.swift, Foundation/NSLocale.swift, Foundation/NSNotification.swift, Foundation/NSRunLoop.swift, Foundation/NSStream.swift, Foundation/NSURL.swift, Foundation/Progress.swift
Now that automatic `Comparable` inference for swift_wrapper types is removed.
https://github.com/apple/swift/commit/de969c66c62bf42ee271ed4c27868fa31ee99c7b
Removed `Comparable` and `func <` from:
* `FileAttributeKey`
* `FileAttributeType`
* `NSExceptionName`
* `HTTPCookiePropertyKey`
* `NSLocale.Key`
* `NSNotification.Name`
* `RunLoopMode`
* `Stream.PropertyKey`
* `StreamSocketSecurityLevel`
* `StreamSOCKSProxyConfiguration`
* `StreamSOCKSProxyVersion`
* `StreamNetworkServiceTypeValue`
* `URLResourceKey`
* `URLFileResourceType`
* `Progress.FileOperationKind`
* `ProgressKind`
* `ProgressUserInfoKey`
=> Remove `Comparable` conformance from several types

Foundation/NSURLSession/NSURLSession.swift
Refer to the API document that mentions URLSession's delegateQueue should be serial:
https://developer.apple.com/reference/foundation/urlsession/1411597-init
=> URLSession's delegateQueue should be serial as per the spec.

Foundation/NSURLSession/EasyHandle.swift, Foundation/NSURLSession/MultiHandle.swift, Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift
Please don't merge for now. URLSession tests are disabled. We'll first have to get them enabled.
Cherry-picking led to some conflicts which have been manually fixed.
=> Cherry-picking some URLSession fixes on to 3.1

TestFoundation/main.swift
After enabling URLSession tests through #982 we still saw two CI failures yesterday:
1. A [timeout](https://ci.swift.org/job/oss-swift-4.0-incremental-RA-linux-ubuntu-16_04/442/) - reason still unknown because this is not reproducible locally even in ~20k runs
2. [A crash](https://ci.swift.org/job/oss-swift-4.0-incremental-RA-linux-ubuntu-16_04/449/) - the reason may be this [open dispatch bug](https://bugs.swift.org/browse/SR-4677). 
To avoid CI failures, disabling seems to be our only resort for now.
=> Disable URLSession tests (SR-4677 and timeouts)

Foundation/NSError.swift, TestFoundation/TestNSError.swift
Because `NSError` is not `LocalizedError` and `_swift_Foundation_getErrorDefaultUserInfo` does not handle `NSError` instances, `(nsError as Error).localizedDescription` didn't return expected output. So let's handle `NSError` case in `Error.localizedDescription` implementation.
=> Fix `(nsError as Error).localizedDescription` output

Foundation/NSError.swift, TestFoundation/TestNSError.swift
Backport #967 into `swift-3.1-branch`.
=> [3.1] Fix `(nsError as Error).localizedDescription` output

build.py
- The blocks runtime is already contained in libdispatch
so removing this 2nd copy from libFoundation removes duplicate
code.
- The libdispatch version is also slightly more optimal as it
doesnt compile functions only needed when HAVE_OBJC is defined.
This is also needed to avoid duplicate symbol errors when statically linking Foundation using https://github.com/apple/swift-corelibs-foundation/pull/873
Also see discussion about blocks runtime in https://github.com/apple/swift-corelibs-foundation/pull/874
An alternative, which I did test, is just to remove `data.c` and `runtime.c` although this means `libdispatch` always has to be linked in and Im not sure if it is guaranteed to always be a dependancy.
=> Remove blocks runtime when building with libdispatch

TestFoundation/TestNSScanner.swift
Finish up [SR-4398](https://bugs.swift.org/browse/SR-4398) by adding tests for Scanner's atEnd property.
=> Add tests for Scanner.atEnd.

TestFoundation/TestNSData.swift
This patch adds a test for [SR-1547](https://bugs.swift.org/browse/SR-1547), which is now fixed on Linux, and ensures an error is thrown when an `NSData` instance is created from a non-existent file.
=> Ensure error is thrown when NSData is created from a non-existent file

TestFoundation/TestFileManager.swift
Add a test for [SR-4298](https://bugs.swift.org/browse/SR-4298) to ensure calling `FileManager.createDirectory` does not crash if the directory already exists.
The underlying issue is already fixed in tip-of-tree Swift.
=> Ensure FileManager.createDirectory does not crash if directory already exists on Linux.

Foundation/Thread.swift
In Swift, (Void) -> Void is actually a function that takes
a single value of empty-tuple type, and not a function that
takes no arguments.
Swift 3 largely ignored the distinction because of the implicit
'tuple splat' behavior; in Swift 4, this behavior has been
eliminated as part of implementing SE-0110, so calling a function
of type (Void) -> () now requires passing in an empty tuple,
like foo(()).
I believe this is not intended behavior, so this patch changes
the functions in question to be written as () -> Void.
=> Small cleanup: Use () -> ... instead of (Void) -> ... for no-argument closures

Foundation/NSDecimal.swift, Foundation/NSError.swift
- Replace truncatingBitPattern: with extendingOrTruncating:
- IntMax() -> Int(), UIntMax() -> UInt()
Compatible with swift 3 & 4
=> swift4: Fixes for integer initializers

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSDictionary.swift
When `NSArray` are compared for equality, `NSArray` only checks if the element can be casted as `AnyHashable`. Therefore, the result was incorrect when the `NSArray` contained instances which are not `Hashable` but are subclasses of NSObject (eg `NSArray` and `NSDictionary`) .
This PR fixes that.
Fixes [SR-4903](https://bugs.swift.org/browse/SR-4903)
=> [NSArray] Add check to `isEqual(to:)` whether values is `_ObjectBridgeable`

build.py, configure, lib/product.py, lib/script.py
the first commit introduces a `StaticAndDynamicLibrary` product (sorry about the multiple inheritance 😨, more than happy to change if someone has a better idea) and which builds `libFoundation.a` on top of `libFoundation.so`.
The other commit is just a simple fix, the `ar` command shouldn't be given the compiler flags.
=> build static foundation

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSDictionary.swift
When `NSArray` are compared for equality, `NSArray` only checks if the element can be casted as `AnyHashable`. Therefore, the result was incorrect when the `NSArray` contained instances which are not `Hashable` but are subclasses of NSObject (eg `NSArray` and `NSDictionary`) .
This PR fixes that.
Fixes [SR-4903](https://bugs.swift.org/browse/SR-4903)
Same with #990
=> [Swift 3.1][NSArray] Add check to `isEqual(to:)` whether values is `_ObjectBridgeable`

TestFoundation/TestNSURLSession.swift
We want to start enabling URLSession tests iteratively and monitor the CI for failures. I'm creating this PR for enabling URLSession tests that use a completion handler only, with two changes that will help us understand any CI failures better:
1. Some extra XCTAssert* calls, printing out errors if they occur
2. Elimination of all forced unwraps
=> TestURLSession - remove some forced unwraps

lib/product.py
Changes of #873 produce these warnings in ninja for each target:
```
ninja: warning: multiple rules generate ../Ninja-ReleaseAssert/foundation-linux-x86_64/Foundation/Foundation/Date.swift.o. builds involving this target will not be correct; continuing anyway
```
The problem is that in the process of generating a static library and a dynamic library, we're generating compile rules for all the targets twice. The right thing to do is to generate them once (for the static library) and simply reuse the objects in the rule to generate the dynamic library.
=> Eliminate duplicate rules in generated build.ninja caused by PR #873

Foundation/NSHTTPCookieStorage.swift, TestFoundation/TestNSHTTPCookieStorage.swift, TestFoundation/XDGTestHelper.swift
[3.1]Cherry picking Separate cookie-storage by application
=> [3.1]Cherry picking Separate cookieStorage by application

Foundation/DateInterval.swift, Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/Process.swift, TestFoundation/TestNSData.swift
Convert unsafeBitCast() to bindMemory()/withMemoryRebound()
Convert deprecated initialize(from:) to UnsafeMutableBufferPointer.initialize(from:)
=> Fix more warnings for deprecation and unsafeBitCast()

Foundation/NSScanner.swift
- Bitshift operators were moved from FixedWidthInteger to
BinaryInteger making the _BitShiftable and _IntegerLike
protocols incorrect.
- Remove _BitShiftable and _IntegerLike and just use
FixedWidthInteger for constraining the return type
of scan() and scanHex().
Tested on swift 3 and 4
=> swift4: Integer fixes for new integer protocols

Foundation/NSURLResponse.swift, Foundation/NSValue.swift, Foundation/Process.swift
- Fix 'Cannot call value of non-function type 'UnsafePointer<Int8>'
by fully qualifying type(of:) in NSValue.swift
Compatible with swift 3 & 4
=> swift4: Minor fixes

Docs/Status.md, Foundation.xcodeproj/project.pbxproj, Foundation/NSLengthFormatter.swift, Foundation/NSMassFormatter.swift, TestFoundation/TestMassFormatter.swift, TestFoundation/main.swift
Implemented MassFormatter and created tests.  
Tests pass 100% on macOS and in a sample iOS project against Objective-C Foundation.
=> Initial implementation of MassFormatter.

Foundation/CGFloat.swift
It looks like that `arch(powerpc)` is not available anymore (and it's never used in swift or any other repository).
Using it in the first of these two conditionals was breaking the build (swift-4.0-branch, this is not an issue when compiling swift-3.1.1-RELEASE) on ARM because NativeType was never being defined.
I've verified that *powerpc* is not available also with the Swift 3.1.1 build shipped with Xcode on macOS with this simple example:
```swift
#if arch(powerpc)
print("test")
#endif
```
This is the output of swiftc:
```
ppc.swift:1:10: warning: unknown architecture for build configuration 'arch'
#if arch(powerpc)
^
ppc.swift:1:10: note: did you mean 'powerpc64'?
#if arch(powerpc)
^~~~~~~
powerpc64
```
I wonder why this wasn't a problem for other platforms.
=> Fix build on ARM: Undefined NativeType

CoreFoundation/Base.subproj/CFRuntime.c
Reverts apple/swift-corelibs-foundation#976
After the rebranch of swift-4.0-branch from master, we need this update.
=> Reapply "Update for AnyObject nukage"

Foundation/NSURLSession/http/HTTPMessage.swift, TestFoundation/HTTPServer.swift
- Failable String initialiser has been obsoleted in swift4.
- Subscripts returning String were obsoleted in Swift 4,
explicitly construct a String from subscripted result.
Tested on swift 3 and 4.
=> swift4: String fixes

CoreFoundation/Parsing.subproj/CFXMLInterface.c, TestFoundation/TestNSXMLDocument.swift
fixes https://bugs.swift.org/browse/SR-4860
=> fix two non-owned strings being freed

CoreFoundation/Base.subproj/SymbolAliases
Fixing:
~~~~
ld: warning: undefined base symbol '__TMC15SwiftFoundation19_NSCFConstantString' for alias '___CFConstantStringClassReference'
Undefined symbols for architecture x86_64:
"__T015SwiftFoundation21__CFSwiftGetBaseClassyXlXpyF", referenced from:
___CFInitialize in libCoreFoundation.a(CFRuntime.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~~
Split from https://github.com/apple/swift-corelibs-foundation/pull/988 (this has somewhat higher risk of breaking on some Macs, maybe)
=> Update Swift-mangled NSCFConstantString class name

Foundation.xcodeproj/project.pbxproj
- The code is still using version 3 syntax so pass the
-swift-version 3 flag
=> Make Foundation compile in Xcode again

CoreFoundation/Base.subproj/CFRuntime.c, Foundation.xcodeproj/project.pbxproj
Also fix some project file oddities around the names of a few test cases.
=> Update the mangled name of CFSwiftGetBaseClass

CoreFoundation/Base.subproj/CFRuntime.c, Foundation.xcodeproj/project.pbxproj
Reverts apple/swift-corelibs-foundation#1034
=> Revert "Update the mangled name of CFSwiftGetBaseClass"

TestFoundation/TestNSHTTPCookieStorage.swift, TestFoundation/XDGTestHelper.swift
@parkera Thanks for merging the last PRs
Some NSHTTPCookieStorage seem to have been mismerged, however. This fixes on Linux for me.
I hope to push a fix for the macOS tests too, but if this blocks swift PRs, I think this should have Linux tests work.
Looking forward to watching the videos from WWDC!
=> Incorporate NSHTTPCookieStorage changes

Foundation.xcodeproj/project.pbxproj, Foundation/Process.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSHTTPCookieStorage.swift
- The paths to the built frameworks needed updating so that
TestFoundation will now correctly build in Xcode and link
with XCTest.
- Use the correct name to the xdgTestHelper which is different on
Linux and macOS.
- The test HTTP server now listens on 127.0.0.1 instead of 0.0.0.0
so that the firewall dialog doesnt popup on macOS if the firewall
is enabled.
This PR works in conjunction with https://github.com/apple/swift-corelibs-xctest/pull/192 for swift-corelibs-xctest
This will fix building SwiftFoundation and then running TestFoundation in Xcode, correctly linking to SwiftXCTest. It requires the xctest PR listed above to work. Some of the tests are still broken on macOS but this should make it easier to fix them now. Also one bug was found by the malloc debugger so that fix is included …
=> build: Fix TestFoundation to build and run in Xcode

CoreFoundation/Base.subproj/CFRuntime.c, Foundation/NSSwiftRuntime.swift
__CFSwiftGetBaseClass and __CFInitializeSwift no longer need mangled names!
=> Remove a few mangled magic items

Foundation/NSCache.swift, TestFoundation/TestNSCache.swift
- Use AnyHashable instead of Hashable for non NSObject that
conforms to Hashable.
- Fixes "Protocol 'Hashable' can only be used as a generic constraint
because it has Self or associated type requirements".
Tested on swift 3 and 4
=> swift4: NSCacheKey fix for hashable AnyObject

build.py
This may fix the bad permission of CoreFoundation on Linux.
https://bugs.swift.org/browse/SR-2783
https://bugs.swift.org/browse/SR-2929
https://bugs.swift.org/browse/SR-4423
Even if this won't fix, this is harmless.
=> [build.py] Change the option of rsync to the same one used in other projects

Foundation/NSURLProtocol.swift, Foundation/NSURLSession/http/HTTPURLProtocol.swift, TestFoundation/TestNSURLSession.swift
This regression was revealed by #1042 . Every URLSession object maintains a registry of URLSessionTasks. When a task completes, it must be removed from the registry. We missed this during the refactoring attempt in #968 
I am not enabling any test here since #1042 is anyway going to do it.
=> [regression]Fix for test_finishTaskAndInvalidate failure

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/SymbolAliases, build.py
- This has the same effect as the  
- defsym=__CFConstantStringClassReference=_T010Foundation19_NSCFConstantStringCN
option but does it in code which allows simplifying the linker arguments.
This will help with the -static-stdlib option since less linker arguments will need to be provided by swiftpm
=> Replace the --defsym linker argument with an alias in code

Foundation/NSLengthFormatter.swift, Foundation/NSMassFormatter.swift, TestFoundation/TestNSLengthFormatter.swift
With the help of #1020 I believe we can safely remove the workaround here.
CC @jszumski
=> Remove temporary workaround for SR-3202

Foundation/NSURLSession/http/HTTPURLProtocol.swift
```
Foundation/NSURLSession/http/HTTPURLProtocol.swift:19:30: warning: 'override' is implied when overriding a required initializer
public override required init(task: URLSessionTask, cachedResponse: CachedURLResponse?, client: URLProtocolClient?) {
^
Foundation/NSURLSession/http/HTTPURLProtocol.swift:29:30: warning: 'override' is implied when overriding a required initializer
public override required init(request: URLRequest, cachedResponse: CachedURLResponse?, client: URLProtocolClient?) {
~~~~~~~~~         ^
```
You do not write the override modifier when overriding a required designated initializer.
=> Fix a compiler warning in URLSession

Foundation/NSCache.swift, TestFoundation/TestNSCache.swift
Fix and optimize the logic for maintaining the internal priority queue NSCache.
Currently when multiple objects are set and removed in an NSCache object, the internal priority queue is not maintained correctly. The logic for maintaining the queue is correct now.
=> [NSCache] Fix incorrect priority queue operation in NSCache

Foundation/NSString.swift, Foundation/NSURLSession/http/HTTPBodySource.swift, Foundation/NSXMLParser.swift
Remove more uses of unsafeBitCast()
- NSXMLParser.swift: Remove all calls to strlen() except for a
single use in UTF8String().
- Replace _colonSeparatedStringFromPrefixAndSuffix() with direct
string construction.
- Replace a call to strncpy() with String._fromCodeUnitSequence()
to simplify extracting a non-null terminated string from a
buffer.
swift4: DispatchData(bytes:) is deprecated
- Use init(bytes: UnsafeRawBufferPointer) instead.
Tested on Linux and macOS
=> Fix some more warnings

TestFoundation/TestNSURLSession.swift
Enabling the remaining URLSession tests. These had been disabled following some CI failures that we couldn't reproduce locally. Late last month we enabled the tests with completion handlers with some extra diagnostic messages. It looks like the CI has been stable for a while (fingers crossed!). This PR enables the remaining tests that use delegates.
=> Enable URLSesssion tests

Foundation/Data.swift
There were some unfortunate slower than expected initializers on Data that were inherited from Collection adoption. This allows Data initialization to take the fast path in a select group of initializations; previously it would create a Data and then iterate byte by byte appending. Albeit that was relatively quick, we have faster options available.
=> Add fast paths for Data initialization for common sequences

Foundation/NSConcreteValue.swift, Foundation/NSGeometry.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSRange.swift, Foundation/NSScanner.swift, Foundation/NSSpecialValue.swift, Foundation/NSString.swift, TestFoundation/TestNSScanner.swift
This has two factors that are updated;
NSRange.swift had a number of changes to handle String range conversions in the Darwin overlay. This commit imports the latest changes to NSRange in but also makes it mergeable back to the Darwin overlay so that we can keep the same source between the two repositories.
This change requires NSScanner for key functions to be updated to be in parity with their Darwin counterparts. Note: not all of NSScanner was updated (and seems to have more work to be done to make the naming updates be in sync)
=> Import NSRange from the Darwin overlay

Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSIndexSet.swift
This implements concurrent enumeration options so that they no longer claim un-implemented.
Ideally we should use a more efficient locking mechanism like stdatomic.h style but the best we have in swift is NSLock/allocated mutex
=> Implement concurrent enumeration for NSArray, NSDictionary and NSIndexSet

CoreFoundation/NumberDate.subproj/CFNumber.c, Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
This is to fix https://bugs.swift.org/browse/SR-90?jql=text%20~%20%22unsigned%22
**I'm not sure if my reasoning is correct**, but as far as I understand, `CFNumber` operates only on signed integers, which caused problems for large unsigned values.  
The solution here is to promote big unsigned values to wider signed types.
There was also an issue with `NSNumber(value: Int64.min).boolValue` returning `true` while on Darwin it returns `false`.
This seems to be a bug on Darwin, but I added this exception for consistency.
=> [SR-90] Fixed NSNumber with large unsigned integers

TestFoundation/TestNSURLSession.swift
Previously any test that needed a server would create it's own. While not an issue at the moment it's clear this wouldn't scale very well. This change creates a single server at the start of the tests, and then all the tests use this server. 
This PR addresses [SR-4676](https://bugs.swift.org/browse/SR-4676).
I've run the tests on both Mac and Linux to confirm they all pass.
=> Refactor URLSession tests to only run with a single instance server

lib/product.py
This fixes a build behaviour change caused by #1012 which in turn was created to fix a behaviour change caused by #873 
#873 enabled building a static Foundation library. In the build scripts parlance, with this change we had two "products" - the dynamic library (`libFoundation.so`) and a new static library (`libFoundation.a`). Build rules for all the "phases" and "dependencies" were generated both these products and we hence ended in duplicates. This is what #1012 attempted to eliminate.
But there was an issue with #1012. With this, build rules for the various dependencies and phases were generated only in  the context of the static library product `libFoundation.a`. These objects generated by these for reused for the dynamic library product `libFoundation.so`. This unintended …
=> [regression]libFoundation.so must also be built on issuing 'ninja test'

Foundation.xcodeproj/project.pbxproj, Foundation/Calendar.swift, Foundation/NSArray.swift, Foundation/NSData.swift, Foundation/NSError.swift, Foundation/NSIndexSet.swift, Foundation/NSNotificationQueue.swift, Foundation/NSOrderedSet.swift, Foundation/NSURLSession/http/HTTPBodySource.swift, Foundation/NSXMLNode.swift, TestFoundation/TestNSCompoundPredicate.swift, TestFoundation/TestNSRange.swift, TestFoundation/TestNSURLSession.swift, lib/phases.py
Changes only compatible with swift 4.
Depends on:
~~https://github.com/apple/swift-corelibs-foundation/pull/995~~ (but requires SE-110 to be reverted)
~~https://github.com/apple/swift-corelibs-foundation/pull/1023~~
~~https://github.com/apple/swift-corelibs-foundation/pull/1024~~
=> Update to Swift 4

Foundation/Data.swift
The RangeExpression variants of slicing incorrectly passed 0..<R.Bounds.max which should be the slice region of the Data.
This resolves the issues:
rdar://problem/32982494
rdar://problem/32983214 aka [SR-5292]: Another Data slice-related crash
=> slices of slices that use range expressions incorrectly calculated relative indexing

Foundation/JSONEncoder.swift
See also https://github.com/apple/swift/pull/10619
CC: @itaiferber
=> JSONEncoder: Typo in documentation of encode<T>(T)

Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/TestNSURLSession.swift
Custom URLProtocols using task delegates doesn't deliver data and response received to the URLSession delegates. This fix would delegate the data and response to url session delegates.
=> URLProtocolClient doesn't deliver response and data to URLSession delegates

Foundation/NSDecimalNumber.swift
The change is shown at https://developer.apple.com/documentation/foundation/nsdecimalnumberhandler/1407825-default?changes=latest_minor
I haven't been able to test this yet because the Xcode build is currently broken.  But it looks fairly simple.
=> NSDecimalNumberHandler: default is now a property

Foundation/Codable.swift, Foundation/JSONEncoder.swift
The swift-corelibs-foundation side of apple/swift/pull/10667.
=> Optionality updates to Codable API

Foundation/Codable.swift, Foundation/JSONEncoder.swift, TestFoundation/TestJSONEncoder.swift
Applies apple/swift#10728 to `swift-corelibs-foundation`.
As laid out in a [proposed update to SE-0166 and SE-0167](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170619/037672.html), there are changes to unkeyed containers and coding paths that we want to introduce to the Codable API. This implements the remainder of those updates which had not yet been implemented:
* For the benefit of unkeyed containers, coding paths currently contain optional `CodingKey`s — unkeyed containers are allowed to report a `nil` key in a path. However, this is unhelpful for debugging purposes, or inspecting the coding path for context, since any unkeyed container simply reports `nil`, whether it’s at index 1 or 1000
Now all containers are required to report a …
=> Make coding paths non-optional [DO NOT MERGE]

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/JSONEncoder.swift, Foundation/NSCFBoolean.swift, Foundation/NSJSONSerialization.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSNumber.swift, Foundation/NSValue.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSPredicate.swift
This replaces #1025 by further utilizing the Factory Initializer Method ([SR-5255](https://bugs.swift.org/browse/SR-5255)).
---
- Change `NSNumber.init(value:)` to returning instance created by `CFNumberCreate()`
- Remove `NSNumber._objCType`
- Add `TestNSNumber.test_objCType()` reproducing crash
Expected results are sampled from macOS
- Fix crash on accessing `objCType` property of `NSNumber`  
- Change `NSNumber.objCType` to returning same values with darwin
- Change `NSNumber.init(value: Bool)` to returning `__NSCFBoolean` by using `_Factory` protocol
Since `NSNumber.objCType` returns `c` with both of `Bool` and `Int8` on darwin platform, `NSNumber.init(value: Bool)` is changed to returns `__NSCFBoolean` by using `_Factory` protocol, and it changed to use `_cfTypeID` to distinguish …
=> Use `CFNumberCreate()` as factory initializer on `NSNumber`

Foundation/Operation.swift, TestFoundation/TestNSOperationQueue.swift
Calling `OperationQueue.main` would
instantiate an `OperationQueue`,
set an `Unmanaged` reference to it as **main queue specific**
and return `OperationQueue`.
Subsequent calls to `OperationQueue.main` would
get the `Unmanaged` reference to `OperationQueue` from **main queue specific**
and return `OperationQueue` wrapped in `Unmanaged`.
However, there's nothing stopping the `OperationQueue` from being deallocated, so the `Unmanaged` reference from subsequent call would in fact return garbage.
=> OperationQueue.main dangling pointer fix

TestFoundation/main.swift
(POSIX sends `SIGPIPE` when writing to a closed fd which will then kill your project unless you ignore it or handle it properly)
=> fix tests dying because of SIGPIPE

CoreFoundation/Base.subproj/CFRuntime.c
- This was a duplicate function also provided in libdispatch.
libdispatch is now a dependancy so this duplicate can be removed.
This is the followup PR to https://github.com/apple/swift-corelibs-libdispatch/pull/258
=> Remove objc_retainAutoreleasedReturnValue()

Foundation/NSURLSession/http/HTTPURLProtocol.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift
also add tests for misbehaving HTTP servers.
we discovered that if the server is just returning random bytes, the whole app would crash with `fatalError("Received body data, but the header is not complete, yet.")` . The reason we can get into that state is that CURL support HTTP/0.9 [simple-responses](https://www.w3.org/Protocols/HTTP/1.0/spec.html#Message-Types) which are just the body bytes...
The issue is [also discussed on CURL's github](https://github.com/curl/curl/issues/467).
To make sure we don't regress and to document the current behaviour, I also wrote tests for a few other cases when the HTTP server is misbehaving or behaving oddly.
=> fix URLSession crashing on HTTP/0.9 simple-responses

Foundation/NSCharacterSet.swift, TestFoundation/TestNSCharacterSet.swift
`CFEqual` for `CFCharacterSet` would call `NSCharacteSet.isEqual` which would again call `CFEqual` and so on.
=> Fixed infinite recursion in NSCharacterSet.isEqual

Foundation/FileManager.swift
`FileManager` already uses `FileAttributeKey` instead of `String` as key type for attribute dictionaries for all methods except `createFile`. I changed it there to make the method compatible with the Darwin version.
This is a small but API breaking change. How are such cases handled usually?
=> Change type of the file attributes dictionary key to match the Darwin version

Foundation/NSJSONSerialization.swift, TestFoundation/TestNSJSONSerialization.swift
This implements the new `sortedKeys` constant in `JSONSerialization.WritingOptions` and adds some tests.  This constant is documented at https://developer.apple.com/documentation/foundation/jsonserialization.writingoptions - it is new in the macOS 10.13 SDK.
This option is used by the new Swift 4 `JSONEncoder` which has been [recently implemented](https://github.com/apple/swift-corelibs-foundation/pull/1048).
**Note: I am still doing performance testing on this to check it doesn't regress the non-sorted case, but I'm opening the PR for review and comment now.**
CC: @bubski @itaiferber
=> JSONSerialization: add WritingOptions.sortedKeys

Foundation/NumberFormatter.swift
I think it's safe to uncomment this shiny new Swift 4 API now. Tested on macOS & Ubuntu.
=> Uncomment NumberFormatter roundingBehavior

Foundation/NSURLSession/http/EasyHandle.swift
Hi, just wondering whether you would consider merging this change to allow https: fetches using NSURLSession to work on Android. It turns out there is a root certificate authorities file required by libcurl for SSL to work.
This PR gives the user the opportunity to provide one and specify it’s location in the environment variable “URLSessionCAInfo” for it to be configured correctly. As providing an absolute path to anything is spectacularly difficult in Android or if the user’s servers are self-signed it also gives the user the option to specify the value “UNSAFE_SSL_NOVERIFY” and SSL hostname verification will not be performed at all.
The advantage of an environment variable over increasing the API surface is that the value can come all the way from the Java side of the application where …
=> For https: to work on Android

Foundation/Data.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSIndexPath.swift
Several compilation warnings resolved
=> Several compilation warnings resolved

Foundation/NSJSONSerialization.swift, Foundation/NSLocale.swift
As documented at https://developer.apple.com/documentation/foundation/nslocale/1407691-system
=> Locale: rename systemLocale() to system

TestFoundation/TestNSURLSession.swift
Some of the expectation descriptions did not make sense.
=> Better descriptions for XCTestExpectations in TestURLSession

Foundation/ExtraStringAPIs.swift, Foundation/NSRange.swift, Foundation/NSStringAPI.swift, Foundation/URLComponents.swift
https://github.com/apple/swift-evolution/blob/master/proposals/0180-string-index-overhaul.md
Must be merged with https://github.com/apple/swift/pull/10852
=> Updates for acceptance of SE-0180 [parallel merge required]

lib/product.py
- swift_begin.o and swift_end.o should only be added to dynamic
libraries and to the executable, which covers any static libraries
that are linked in.
=> [Linux] Remove swift_begin/swift_end from libFoundation.a

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Currently the optional `attributes` parameter is ignored in `createFile`.  
I added a call to `setAttributes` (if applicable) to the implementation and some test code to the existing `test_createFile` case.
=> Use the file attribute dictionary passed to createFile

Foundation/NSRange.swift
When build on LinuxOne (s390x) found the error : 
"Foundation/NSRange.swift:133:5: error: missing return in a function expected to return 'Int'"
Please also update branch "swift-4.0-branch"
Thanks,
=> add support to s390x platform 

Foundation/NSXMLDTD.swift, Foundation/NSXMLDTDNode.swift, Foundation/NSXMLDocument.swift, Foundation/NSXMLElement.swift, Foundation/NSXMLNode.swift, Foundation/NSXMLParser.swift, TestFoundation/TestNSXMLDocument.swift
This PR improves the accuracy of the public API signatures in the XML classes, in comparison with Darwin.
https://developer.apple.com/documentation/foundation/archives_and_serialization/xml_processing_and_modeling was used as a reference.
CC: @rothomp3
=> XML: correct API signatures

Foundation/NSCFString.swift
The type checker is particularly slow on these expressions. I've opened
`https://bugs.swift.org/browse/SR-5322` to investigate the type checker
issue, but in the meantime it would be nice to speed up builds. This
cuts more than a minute from my unoptimized asserts-enabled build.
=> Split up a couple expressions to work around slow type checking.

CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme, Foundation/NSXMLDTD.swift, Foundation/NSXMLDTDNode.swift, Foundation/NSXMLDocument.swift, Foundation/NSXMLElement.swift, Foundation/NSXMLNode.swift, TestFoundation/TestNSXMLDocument.swift
So I wrote most of this to begin with, and when I went to actually try and use it for a little project (playing around with WebDAV), it crashed! Turns out I never went back and did namespace support. Well, here is more of (but still not all of) namespace support.
Fix one place was still expecting C String
XPath works with namespaces
implement XMLElement(xmlString:)
Add some tests, re-enable all tests
Implement more namespaces support
=> Better namespace support for XML

Foundation.xcodeproj/project.pbxproj, Foundation/CGFloat.swift, Foundation/CharacterSet.swift, Foundation/IndexPath.swift, Foundation/Locale.swift, Foundation/NSAffineTransform.swift, Foundation/NSDecimal.swift, Foundation/PersonNameComponents.swift, Foundation/UUID.swift, TestFoundation/TestCodable.swift, TestFoundation/main.swift
This PR mirrors _some_ changes apple/swift#9715
- PersonNameComponents
- UUID
- URL
- NSRange
- Locale
- IndexSet
- IndexPath
- AffineTransform
- Decimal
- DateInterval
- CGFloat (unit tested indirectly)
- Calendar
- CharacterSet
- DateComponents
- Measurement
- TimeZone
=> Codable conformance to some Foundation types

Foundation/NSSortDescriptor.swift
There are new KeyPath APIs in `NSSortDescriptor` which needed stubbing out in swift-corelibs-foundation. This PR adds those stubs using the declarations found [here](https://developer.apple.com/documentation/foundation/nssortdescriptor?changes=latest_minor)
=> Stub out new KeyPath APIs in NSSortDescriptor

Foundation/ExtraStringAPIs.swift
This is consistent with what we've done in the foundation overlay for
OSX.
=> Drop RandomAccessCollection conformance for String.UTF16View

Foundation/NSString.swift
This is in support of apple/swift#11088
=> Simplify substring(with:), provide resilience

TestFoundation/TestNSString.swift
=> NSString: add test for substring of unpaired surrogate

Foundation/NSURLSession/NSURLSessionTask.swift, TestFoundation/TestNSURLSession.swift
Fixes https://bugs.swift.org/browse/SR-5548
=> [SR-5548] Remove invalid cast in URLSessionTask

Foundation/NSSortDescriptor.swift
Fixes incorrect access controls with the new keyPath APIs in NSSortDescriptor.
=> Update access controls in NSSortDescriptor

Foundation/Process.swift, TestFoundation/TestProcess.swift
This patch adds support for the `currentDirectoryPath` property on `Process`
Since `posix_spawn` doesn't make it easy to change the working directory, a
call to `chdir` is issued just before the process executes. It looks like
`lldb` follows a similar pattern in one of its tools
(`tools/darwin-debug/darwin-debug.cpp`).
This also addresses [SR-3524](https://bugs.swift.org/browse/SR-3524)
=> Add support for currentDirectoryPath in Process class

TestFoundation/TestNSDecimal.swift
This expression became too complex due to the changes introduced in
https://github.com/apple/swift/pull/11044
=> [test] Simplify expression in a test

Foundation/NSGeometry.swift, TestFoundation/TestCodable.swift
This PR mirrors some changes from https://github.com/apple/swift/pull/10404
---
- CGPoint
- CGSize
- CGRect
- CGVector 📝
- CGAffineTransform 📝
📝 I've stumbled across [this](https://github.com/apple/swift-corelibs-foundation/pull/135), which leads me to believe that `CGVector` is not supposed to be implemented in `swift-corelibs-foundation`.
I suppose same goes for `CGAffineTransform`, since we already have `AffineTransform`/`NSAffineTransform` implemented.
=> Codable conformance added to some CG types

Foundation/CharacterSet.swift, TestFoundation/TestCodable.swift, TestFoundation/TestNSCharacterSet.swift
Continuation of #1108
This PR mirrors _some_ changes from apple/swift#9715
---
- CharacterSet
`CharacterSet : Equatable` was not working correctly in some cases and was fixed to make `Codable` unit tests for `CharacterSet` work.
- Calendar
- DateComponents
- Measurement
- TimeZone
- PersonNameComponents
- UUID
- URL
- NSRange
- Locale
- IndexSet
- IndexPath
- AffineTransform
- Decimal
- DateInterval
- CGFloat (unit tested indirectly)
=> CharacterSet : Codable implementation

Foundation/FileHandle.swift
This was causing an error when trying to get the remaining amount of data.
=> Match types when calculating remaining in FileHandle's _readDataOfLength

Foundation/NSURLSession/http/HTTPURLProtocol.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSURLSession.swift
https://bugs.swift.org/browse/SR-5516
Upload tasks must invoke the `urlSession(_:task:didSendBodyData: totalBytesSent:totalBytesExpectedToSend)` delegate method every time data is uploaded.
=> [URLSession] Fix for SR-5516

Foundation.xcodeproj/project.pbxproj, TestFoundation/TestNSHTTPCookieStorage.swift
At some point the Xcode project on the Swift 3.1 branch got hosed. This fixes it up so the tests can be run again.  Tested with Xcode 8.3.3.
=> [3.1] Fix Xcode build

Foundation/NSGeometry.swift, TestFoundation/TestCodable.swift, TestFoundation/TestNSGeometry.swift
=> Special values and initializers for some CG types

CoreFoundation/NumberDate.subproj/CFTimeZone.c
- The timezone directory changed on macOS 10.13 so get the os version
at runtime and set the timezone directory dynamically. This allows
the tests to be on 10.12 and 10.13
- Added __InitTZStrings() for both Linux and macOS to work the same way as Windows.
Tested on Linux and 10.12 but not 10.13
=> Determine the Timezone directory to use at runtime on macOS.

Foundation/NSError.swift, TestFoundation/TestNSError.swift
Pull default CustomNSError implementation from https://github.com/apple/swift/blob/master/stdlib/public/SDK/Foundation/NSError.swift
=> Provide CustomNSError default implementation

Foundation/NSDecimal.swift, Foundation/NSNumber.swift, Foundation/ProgressFraction.swift
Based on the [latest revision of SE-0104](https://github.com/apple/swift-evolution/blob/91f8ed0620e438712e5d72b20a65a68d6e0a8a1d/proposals/0104-improved-integers.md).
See https://github.com/apple/swift/pull/11203.
=> Reflect changes to the integer types

CoreFoundation/Preferences.subproj/CFPreferences.h, Foundation/NSUserDefaults.swift
The compiler no longer crashes for this method. Tested on macOS & Ubuntu 16.04
=> Uncomment NSUserDefaults dictionaryRepresentation

Foundation/NSXMLElement.swift
The implementation of `setAttributesAs` was deprecated bfeore the API was
copied over to the Linux implementation, and won't be implemented. By
adding an availability marker coupled with a new name, we allow for a
fix-it to run and use the new name in future compiled code.
=> Add availability indicator to XMLElement to indicate correct function

Foundation.xcodeproj/project.pbxproj
When building the `TestFoundation` target in Xcode 9 beta 4, `ld` reports the following warning:
```
Ld /Users/ipartrid/Library/Developer/Xcode/DerivedData/Foundation-dlbuoxyagtlausbjtyopapynebeb/Build/Products/Debug/TestFoundation.app/Contents/MacOS/TestFoundation normal x86_64
cd /Users/ipartrid/swift-corelibs-foundation
export MACOSX_DEPLOYMENT_TARGET=10.11
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/ipartrid/Library/Developer/Xcode/DerivedData/Foundation-dlbuoxyagtlausbjtyopapynebeb/Build/Products/Debug -F/Users/ipartrid/Library/Developer/Xcode/DerivedData/Foundation-dlbuoxyagtlausbjtyopapynebeb/Bu …
```
=> Fix ld warning

Foundation/NSNumber.swift
Previously NSNumber.encode would call NSUnimplemented when you try to
do a keyed coding. Whilst it is true that this wasn't implemented it was
due to not being possible rather than not yet implemented.
With this patch we call preconditionFailure which is more consistent
with the rest of the project. We also use a guard so can remove a level of
indentation.
=> Replace precondition if with guard in NSNumber.encode.

build.py
- Mirrors use for foundation.LDFLAGS, allowing libicu to be
used if installed in non-default include directory
=> Use PKG_CONFIG for libicu foundation.CFLAGS

TestFoundation/TestDateFormatter.swift
- The tests were broken for timestyle .full and failed on macOS.
Fix the tests so that they work correctly on macOS.
- DateFormatter is still broken on Linux so disable the tests for
now until the Linux implementation can be fixed.
=> SR-5591: Update broken DateFormatter tests

Foundation/NSURLSession/NSURLSession.swift, Foundation/NSURLSession/NSURLSessionTask.swift, Foundation/NSURLSession/http/EasyHandle.swift, Foundation/NSURLSession/http/HTTPURLProtocol.swift
This is a kind of an extension to #1121 
We had defined three private properties in URLSessionTask to track upload & download progress and make delegate calls. It turns out that the URLSessionTask API defines [four properties](https://developer.apple.com/documentation/foundation/urlsessiontask/1410663-countofbytesexpectedtoreceive) to do the same. This PR replaces the uses of the private properties with these.
Also, the constant `URLSessionTransferSizeUnknown` is changed to `NSURLSessionTransferSizeUnknown` to match Darwin.
=> Use URLSessionTask.count* properties to track upload/download progress 

Foundation/TimeZone.swift, TestFoundation/TestNSTimeZone.swift
~`TimeZone.init(secondsFromGMT:)` made not failable.~
~Aligns with https://developer.apple.com/documentation/foundation/nstimezone/1387199-init~
Fixed `TimeZone.init(secondsFromGMT:)` failability
=> Fixed TimeZone.init(secondsFromGMT:) failability

Foundation/URLSession/http/MultiHandle.swift
Fixes warning:
```
'scheduleRepeating(deadline:interval:leeway:)' is deprecated: renamed to 'schedule(deadline:repeating:leeway:)'
Use 'schedule(deadline:repeating:leeway:)' instead
```
@pushkarnk
=> URLSession: fix compile warning

Foundation.xcodeproj/project.pbxproj, Foundation/NSString.swift
- Add the NSString-UTF32-{LE,BE}-data.txt tests to the copy resources.
- Add the BOM marker 0xFEFF to the start of the comparison string.
Im not sure if it is correct to have the BOM as the first character in a string but with this change the tests now work on macOS and still work ok on Linux. 
string.character(at: 0) returns the BOM on macOS, does that sound correct?
The UTF32 changes were merged in https://github.com/apple/swift-corelibs-foundation/pull/928
=> Make NSString(contentsOf:usedEncoding:) tests work on macOS

Foundation/NSNotification.swift, Foundation/Notification.swift, Foundation/NotificationQueue.swift
Reverts apple/swift-corelibs-foundation#1153
=> Revert "Fix Notification API signatures to match Darwin"

Foundation/NSObjCRuntime.swift
As suggested in https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20170724/001254.html it would be desirable to have a differential macro (rather than `NSUnimplemented()`) to indicate whether the functionality is missing by design in this library, to distinguish it from things that are not yet implemented.
This change adds `NSUnsupported()` as a variant of `NSUnimplemented()` that has a different error message, and allows the code to be differentiated at the point of definition, as well as uses availability macros on specific methods and types known to not exist on other platforms.
Note that marking the APIs as `unavailable` instead of `deprecated` would mean that they would cause compile-time errors. We may want to do that in a future release.
=> Adds support for NSUnsupported to indicate non-availiability, and use annotations

Foundation/XMLParser.swift
Use String.decodeCString() instead of bitcasting. Fixes a warning.
=> Use String.decodeCString() instead of bitcasting.

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/ForFoundationOnly.h, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Parsing.subproj/CFXMLInterface.h, CoreFoundation/PlugIn.subproj/CFBundle.c, CoreFoundation/PlugIn.subproj/CFBundle_Internal.h, CoreFoundation/String.subproj/CFBurstTrie.h, CoreFoundation/URL.subproj/CFURLComponents.h, CoreFoundation/URL.subproj/CFURLSessionInterface.h
- Update prototype() to prototype(void).
Xcode9/Clang includes new warnings for C function prototypes which are declared with an unspecified number of arguments `()` instead of with `(void)`. Fixing these warnings will allow updating the Xcode project to the latest recommended settings.
I broke this into 2 PRs for easier review, a 2nd PR will follow to fixup the rest.
=> Fix C function prototypes for functions that take no arguments.

Foundation/Bundle.swift
Since NSBundle's unload mechanism is a Mach-specific concept, which
is not relevant on non-Darwin platforms, mark it as deprecated
and change the unavailability macro so that they are distinguishable
from implementations that are not yet available.
=> Mark Bundle.unload as unsupported

Foundation/NSRegularExpression.swift, TestFoundation/TestNSRegularExpression.swift
Brings it into line with the signatures @ https://developer.apple.com/documentation/foundation/nsregularexpression
=> NSRegularExpression: Make options: default to empty to match Darwin

Foundation/NSRegularExpression.swift, Foundation/NSString.swift, TestFoundation/TestNSRegularExpression.swift, TestFoundation/TestNSTextCheckingResult.swift
- NSMatchingOptions -> NSRegularExpression.MatchingOptions
- NSMatchingFlags -> NSRegularExpression.MatchingFlags
=> Rename NSRegularExpression options

CoreFoundation/NumberDate.subproj/CFTimeZone.c
- The length passed to CFStringCreateWithBytes() included an extra
random byte after the NUL. This meant the string was sometimes
interpreted as non-ASCII (if the byte was >= 0x80) and the
timezone would come back as NULL thus defaulting to GMT.
This was broken in https://github.com/apple/swift-corelibs-foundation/pull/1126 which dealt with the macOS timezone directory
=> SR-5596: TimeZone.current returns wrong value

Foundation/FileHandle.swift
`dynamicBuffer` will never be freed if `total > 0`. Fix this by giving the underlying Data a "free" destructor. This is covered by existing tests.
=> Foundation: FileHandle.swift: memory leak in _readDataOfLength

Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
[SR-1702](https://bugs.swift.org/browse/SR-1702) NSJSONSerialization.data(withJSONObject:options:) should fatalError on bad input not throw
-removed the `throw` in the case of using a stream: in both cases in objc it is an `NSInvalidArgumentException`
-removed the test checking for the `throw` in the case of the stream (and, AFAIK, there's no good way to test for fatalErrors, but happy to be corrected on that fact)
=> [SR-1702] NSJSONSerialization.data(...) fatalErrors on bad input

CoreFoundation/String.subproj/CFRegularExpression.c, Foundation/NSRegularExpression.swift, TestFoundation/TestNSRegularExpression.swift
- The error dictionary in CFRegularExpression was failing with the
error key being a CFSTR inside an array so initialiase it outside
of the array.
I removed the `_nsObject` as I think throwing the error dictionary is more useful as it gave a better error message when stringified.
Should a description be added to the error dictionary to eliminate the '(null)'?
=> SR-5557: Fix NSRegularExpression errors with invalid pattern

Foundation/ExtraStringAPIs.swift, TestFoundation/TestNSString.swift
I've noticed the following discrepancy in the behaviour of Range/CountableRange.
macOS:
```
$ swift
Welcome to Apple Swift version 4.0-dev (LLVM 2dedb62a0b, Clang b9d76a314c,
Swift 6b4756bd93). Type :help for assistance.
1> import Foundation
2> "abc".range(of: "a")!.lowerBound..<"abc".range(of: "a")!.upperBound
$R0: Range<String.Index> = {
lowerBound = {
_compoundOffset = 0
_cache = utf16
}
upperBound = {
_compoundOffset = 4
_cache = utf16
}
}
```
Linux:
```
$ swift
Welcome to Swift version 4.0-dev (LLVM 2dedb62a0b, Clang b9d76a314c, Swift
6b4756bd93). Type :help for assistance.
1> import Foundation
2> "abc".range(of: "a")!.lowerBound..<"abc".range(of: "a")!.upperBound
$R0: CountableRange<String.Index> = {
lowerBound = {
_compoundOffset = 0
_cache = utf16
}
upperBound = {
_compoundOffset …
```
=> Remove Strideable conformance from String.UTF16View.Index

build.py, configure, lib/__init__.py, lib/pkg_config.py
This allows linking swift-corelibs-foundation to packages with flags
defined by `pkg-config`, rather than hardcoded ones. There are a couple
of structural changes as well, namely that `pkg-config` will now be
executed during `configure` rather than later by `ninja`. This seems
acceptable as it's how cmake and autoconf work, but means a reconfigure
will be required if any transitive dependency of a package we depend on changes.
The other structural change is that `-lcurl` will be passed
unconditionally on platforms without pkg-config support (technically the
`pkg_config_required` variable set). This makes curl a harder dependency
on those platforms, but that seems unavoidable given that it's the only
implementation of `URLSession`.
=> Use pkg-config to find libxml2 and libcurl on Linux [SR-5603]

Foundation/NSURL.swift, TestFoundation/TestURL.swift
=> NSURL: Dont leak the result of dataRepresentation

Foundation/NSNotification.swift
This is a pickup of https://github.com/apple/swift-corelibs-foundation/pull/1060 which has gone stale.
Correct the API signature of 
https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver
=> Notification: fix addObserver(forName:object:queue:using:) signature

CoreFoundation/Parsing.subproj/CFXMLInterface.c
Fixes https://bugs.swift.org/browse/SR-5256.
=> Fix memory leaks by using more specialized xml*Free functions.

Foundation/HTTPCookie.swift, Foundation/JSONSerialization.swift, Foundation/NSPathUtilities.swift, Foundation/NSStringAPI.swift, Foundation/NSURL.swift, Foundation/ProcessInfo.swift, Foundation/XMLNode.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSString.swift, TestFoundation/TestPipe.swift, TestFoundation/TestStream.swift
Already deprecated in Swift4 so this just tidies up the warnings.
=> Remove deprecated (Sub)String .characters and CharacterView

CoreFoundation/Parsing.subproj/CFXMLInterface.c
Fixes https://bugs.swift.org/browse/SR-5256 for Swift 4.  Cherry-pick of https://github.com/apple/swift-corelibs-foundation/commit/cf17ae7c6e959ec37c77cb76377d135aed2c4540.
=> 4.0: Fix memory leaks by using more specialized xml*Free functions.

Foundation.xcodeproj/project.pbxproj, Foundation/Data.swift, Foundation/NSSwiftRuntime.swift
This change enables building the TestFoundation executable in Release mode so that it can be profiled in Instruments.
Some symbols have been changed to `public` as they need to be exported to CoreFoundation and used for ObjCBridging.
To profile, the TestFoundation scheme needs to be edited and the 'Profile(Release)' scheme set to 'Ask on Launch' for the executable. The Xcode project has not been updated as Xcode adds the full path to the executable and the path it adds in `TestFoundation.xcscheme` is an absolute path including my homedir so it would not be applicable to anyone else.
=> Enable building TestFoundation for profiling in Xcode

Foundation/URLSession/URLSessionTask.swift
`URLSessionTask` now conforms to `ProgressReporting` protocol. 
Also added the 3 other, new instance properties to it too, namely `earliestBeginDate`, `countOfBytesClientExpectsToRecieve` and `countOfBytesClientExpectsToSend`.
=> URLSessionTask conforms to ProgressReporting protocol, added new instance properties.

Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionDelegate.swift
Added `DelayedRequestDisposition` enum to `URLSession` and added stub method called `urlSession()` that uses the enum in `URLSessionTaskDelegate`.
=> Add DelayedRequestDisposition enum to URLSession 

Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionTask.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
this is really only the beginning to prevent everything from breaking with the simplest test that does use more than one thread. Thread-safely seems to be large absent in this part of foundation 😢. 
Unfortunately, I seem to be going down a rabbit hole here but it's a start.
=> improve threading correctness in URLSession

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Docs/Status.md, Foundation/NSLock.swift, Foundation/Operation.swift, Foundation/Thread.swift, TestFoundation/TestThread.swift, TestFoundation/main.swift
- Eliminate _compiler_crash_fix() as no crashes are observed anymore.
- Re-enable TestThread.swift test cases.
I exposed `_CFMainPThread` since `pthread_main_thread_np()` is a `#define` and not a real function on linux and so doesn't export to swift correctly.
I used `_CFIsMainThread` instead of `pthread_main_np` for consistency and to avoid the local definition of `pthread_main_np()` in `Operation.swift` not having the same semantics as `pthread_main_np()` on macOS where it can return -1.
=> Thread: Implement more functionality

Foundation/NSData.swift, TestFoundation/TestNSData.swift
- Some files (eg in /proc) report a filesize of zero and need to
be read into a buffer instead of using mmap().
=> SR-4993: Read zero length files on Linux

Foundation/NSStringAPI.swift
Over time, `NSStringAPI.swift` has diverged from the [version in the overlay](https://github.com/apple/swift/blob/master/stdlib/public/SDK/Foundation/NSStringAPI.swift).
This PR brings them back into sync, by copying the overlay version into `swift-corelibs-foundation`, then fixing the resulting breakages so it builds and passes TestFoundation on Linux and in Xcode.
Hopefully this will make it easier to port changes between the two in future.
This is a second attempt after #1167
=> SR-5727: Sync NSStringAPI.swift from overlay

Foundation/JSONSerialization.swift, Foundation/NSNumber.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestNSNumber.swift
This is a workaround rather than a full fix. However it should make it easier to create the correct fix.
- NSNumber(value: UInt.max).stringValue was returning "-1"
instead of "18446744073709551615" because NSNumber holds any
value > Int64.max as a 128Bit quantity using a high Int and
low UInt. It marks this type as an 'SInt128Type'.
- CFNumberFormatterCreateStringWithNumber() uses CFNumberGetType()
to get this type however CoreFoundation wants to hide SInt128Type
(probably for backwards compatibilty) and instead returns it
as an SInt64Type. Thus only the low part of the NSNumber is used
for the number and this is interpreted as an Int64.
- The workaround is simply in NSNumber.description(withLocale:)
to test to see if the value is of type SInt128Type and if so
use String(format: "%@") to …
=> SR-5640:  JSONEncoder misrepresents UInt.max

Foundation.xcodeproj/project.pbxproj, Foundation/Measurement.swift, Foundation/Unit.swift, TestFoundation/TestCodable.swift, TestFoundation/TestUnit.swift, TestFoundation/TestUnitConverter.swift, TestFoundation/main.swift
Continuation of #1108, #1127 & #1148 
This PR mirrors _final missing_ changes from apple/swift#9715
---
- Measurement
=> Codable conformance for Measurement

TestFoundation/TestOperationQueue.swift
- Use an NSRecursiveLock() as didChangeValue() will call isFinished
when the key is 'isFinished'.
This test was failing under Xcode when running in Release mode.
=> Fix AsyncOperation test by adding locking around flags.

Foundation/HTTPCookieStorage.swift, TestFoundation/TestHTTPCookieStorage.swift, TestFoundation/TestProcess.swift, TestFoundation/TestXMLParser.swift
Fix these warnings:
`Warning: 'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' operator.`
`Warning: 'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.`
Personally I don't think this looks like an improvement, but it's what https://github.com/apple/swift/commit/fc0cf33bdc3cdf02513cb058f086603ad5c1fdcb implements.
I think a lot of people are going to reimplement `substring(from:)` and `substring(to:)` in their own extensions.
=> Fix String.substring() deprecation warnings

TestFoundation/TestURLSession.swift
this is to show that `test_httpRedirectionTimeout` isn't actually working. I want to disable it and open an issue to fix it (I can do that after my holiday). I reckon that'll require quite a few more concurrency fixes.
=> test_httpRedirectionTimeout not working, disable it

TestFoundation/HTTPServer.swift
the loop to find a free port is ugly, error-prone and makes the tests less robust
let start = 21961
for port in start...(start+100) { //we must find at least one port to bind
fixing this here
=> make TestHTTPServer choose the port automatically rather than guessing

Foundation/JSONSerialization.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestJSONSerialization.swift
- Add support for Int8/Int16/Int32/Int64, UInt8/UInt16/UInt32/UInt64,
Decimal and NSDecimalNumber.
- Improve serializeInteger performance to avoid overall speed regression.
- Move JSONSerialization tests into correct testfile and use Int64 to stop tests
breaking on 32bit platforms.
- Add tests for isValidJSONObject() to test the support of new types.
- Add tests for Float, Double, Decimal and NSDecimalNumber.
This PR does not address the output format of `Float` and `Double`, which are not currently the same as `Foundation`. That will be addressed in a follow-up PR
=> JSONSerialization: Add missing numeric types

Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/http/HTTPURLProtocol.swift
HI Apple,
I’ve noticed a memory leak using NSURLSessionTasks to fetch a URL in Swift 4 that wasn’t present in Swift 3.1.1. This is for Vanilla Linux as well as Android. This PR seems to resolve it.
There was a retain cycle between the URLSessionTask and its protocol handler resulting in it never being deinit’d and the internal data container never being freed up. This PR nils out the pointer to the protocol handler when the task completes, breaking the retain cycle and allowing both to deinit.
Fixes [SR-5472](https://bugs.swift.org/browse/SR-5472)
=> URLSessionTask retain cycle and memory leak fix - all Linuxies

Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/http/HTTPURLProtocol.swift
This PR fixes a retain cycle in URLSessionTask which is causing memory to leak by the amount of data returned by the request. See: https://github.com/apple/swift-corelibs-foundation/pull/1195
=> URLSessionTask retain cycle fix

Foundation/URLSession/http/MultiHandle.swift
This reverts commit 015ded4d70a7cf4b2741d7206fc60a3d1ceffe03.
The reason to revert this is that it this pretty certainly works around another bug ([SR-5759](https://bugs.swift.org/browse/SR-5759)) and IMHO introduces two new bugs instead.
Dispatch Sources should be cancellable independently. If you have two DispatchSources watching for events on one and the same PR, the should be independent. That was seemingly the problem that was seen here, see the [original bug](https://bugs.swift.org/browse/SR-4567) and the discussion in #949.
The two new bugs introduced:
- a blocking wait `self.cancelInProgress?.wait()` is introduced when creating a `_MultiHandle`. Creating a large number of `_MultiHandle`s concurrently could lead to a lot of threads being blocked in the wait. That might exhaust …
=> Revert "Fix for a race condition in URLSession (#949)"

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
- Fix isEqual to work with NSNumbers initialised with different types
(eg, float and UInt).
- Match the behaviour of Darwin where true can only equal an NSNumber
with a value of exactly 1.
I essentially added tests that worked correctly on Darwin and then fixed the current code until all of the tests passed.
=> SR-5803: NSNumber no longer equates 1 and true

Foundation/DateFormatter.swift, TestFoundation/TestDateFormatter.swift
In a playground if you do the following: 
```swift
let f = DateFormatter()
f.dateStyle = .long
f.timeStyle = .long
f.dateFormat
```
`f.dateFormat` at this point is equal to "MMMM d, y 'at' h:mm:ss a z" 
However if you do the same in Foundation the f.dateFormat is equal to "" this is because whenever you set the Style properties dateFormat is being set to nil but it's not then reassigned a new value at that point. The code handles this nil value by assigning dateFormat the value of "" but this is not the correct value.  
The expected behaviour is that when you set the Style properties the dateFormat property is then also reassigned the correct value based on the value you assigned to the Style properties. 
This PR fixes this behaviour and ensures dateFormat is being set whenever the the …
=> SR-5837: Fix dateFormat bug in DateFormatter

Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
On macOS, pretty-printing JSON results in a space before the colon, e.g.:
{
"key" : 4
}
Addresses [SR-5570](https://bugs.swift.org/browse/SR-5570).
=> Make JSON pretty-printing consistent with Darwin.

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/Thread.swift
I was reading through `Thread.swift` and found the name of an internal function to be confusing. After some head scratching, it's pretty clear that `_CThreadSpecificSet` should be `_CFThreadSpecificSet`. This PR updates the name so as to improve clarity.
=> Correct a typo for thread-specific set [NFC]

Foundation/URLSession/URLSession.swift
Hi Apple,
I’ve been seeing assertion failures using a URLSession from multiple threads on [this line](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/URLSession/TaskRegistry.swift#L63). This PR makes a small change so allocation of the taskIdentifier in URLSession is thread safe.
Thanks.
=> Thread safety for URLSession

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
- When comparing signed/unsigned integers, always compare both
as SInt128.
- Add special handling for comparing values with Float.nan and
Double.nan.
=> NSNumber: More Darwin compatibility fixes

Foundation.xcodeproj/project.pbxproj, Foundation/NSNumber.swift, Foundation/Stream.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSNumberBridging.swift, TestFoundation/main.swift
`Int(truncating: NSNumber)` is missing in swift-corelibs-foundation. This function was added as part of SE-0170.
This PR implements the `init(truncating:)` and `init?(exactly:)` APIs from SE-0170, and also deprecates `init(_:)` appropriately.
It seems we also lacked implementations of `init(_:)` for many of the primitive number types (e.g. `Int8`) to begin with so this PR also adds those.
=> NSNumber: update API for SE-0170

Foundation/NSKeyedUnarchiver.swift, TestFoundation/TestNSKeyedArchiver.swift
This makes the init function match up to the Darwin version, found as part of getting the swift-corelibs-foundation tests running against the system Foundation and XCTest.
https://developer.apple.com/documentation/foundation/nskeyedunarchiver/1410862-init
=> NSKeyedUnarchiver: Rename init(forReadingWithData:) -> init(forReadingWith:)

Foundation/NSString.swift, TestFoundation/TestNSString.swift
- This is a misspelt duplicate of init?(cString:encoding:)
=> NSString: Remove incorrect init?(CString:encoding:) method

Foundation/JSONEncoder.swift, TestFoundation/TestJSONEncoder.swift
- DataEncodingStrategy.base64Encode -> .base64
- DataDecodingStrategy.base64Decode -> .base64
=> JSONEncoder: Rename data coding enum values to align with SE-0167

TestFoundation/HTTPServer.swift, TestFoundation/TestCalendar.swift, TestFoundation/TestNSGeometry.swift, TestFoundation/TestNumberFormatter.swift, TestFoundation/TestProcess.swift, TestFoundation/TestXMLDocument.swift, TestFoundation/main.swift
As part of getting the swift-corelibs-foundation tests running against the system Foundation and XCTest, some issues have shown up with module imports.
- Fix `Glibc` and `Darwin` to only be imported on the appropriate OS.
- Remove unneeded `import CoreFoundation`.
=> Fix TestFoundation Imports

Foundation/URLSession/URLSession.swift
In wake of some recent fixes to improve thread safety in URLSession, I found one of the queues in URLSession not used anymore. We can remove it.
=> Remove unused queue from URLSession

TestFoundation/TestThread.swift
- Lock the NSCondition variable before creating the thread,
otherwise the thread could broadcast on the condition variable
before the parent has waited on it.
=> SR-5871: TestThread.test_threadStart failing sporadically on Ubuntu 14.04

Foundation/FileManager.swift, Foundation/NSAttributedString.swift, Foundation/NSDictionary.swift, Foundation/NSIndexSet.swift, Foundation/NSPathUtilities.swift, Foundation/NSSet.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSURL.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestHTTPCookieStorage.swift, TestFoundation/TestUtils.swift, TestFoundation/XDGTestHelper.swift
- Update uses of Bool to ObjCBool where appropriate
Found after testing Darwin compatibility where the ObjCBool type has a `boolValue` property
=> ObjCBool: Add boolValue property

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/Data.swift, Foundation/JSONEncoder.swift, Foundation/NSData.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSNumber.swift
Mutation of Data slices had issues when it comes to re-indexing to the base slice region. Previously when a slice of Data was mutated the re-calculation of the slice region was incorrectly assigned to a relative region to the previous backing. Now the slice region will copy the specific region out creating a new data upon CoW semantics and offset the index region upon access. Mutating a non CoW slice will retain the previous region backing but adjust the remaining allocation buffer accordingly. To validate this I have added tests for combinations that should approximate all possible combinations of mutations, backing storages and CoW scenarios.
This fixes the following issues:
rdar://problem/34206043
SR-5887
SR-5873
SR-5810
tl;dr – Slicing a CoW should result in fillet mignon not ground …
=> Import changes from the overlay for Data mutation of slices

Foundation/AffineTransform.swift, TestFoundation/TestAffineTransform.swift
1. Implement `NSAffineTransform.hashValue` and enable two tests which were previously disabled.
2. Add `test_rotation_compose()` to test composition of rotation. Test taken from [here](https://github.com/apple/swift/blob/d2926cfb05177d4db0ec89e8609cad1aee14fba1/test/stdlib/TestAffineTransform.swift#L376).
=> AffineTransform: implement hashValue and improve tests

CoreFoundation/Preferences.subproj/CFApplicationPreferences.c, CoreFoundation/Preferences.subproj/CFPreferences.c, CoreFoundation/Preferences.subproj/CFXMLPreferencesDomain.c, Foundation.xcodeproj/project.pbxproj, Foundation/UserDefaults.swift, TestFoundation/TestUserDefaults.swift, build.py
- the register(defaults:) function now ensures that values are stored in the internal registration dictionary as NSObject objects which allows object(forKey:) and friends to actually find those values
- the bool(forKey:), integer(forKey:), double(forKey:) and float(forKey:) functions now implicitly convert string represetations to the requested type
- the set(_:forKey:) function now ensures that values of type String, Int and Double are first converted to the proper CFType before they are stored in the CFPreferences object
- register(defaults:) and set(_:forKey:) now cause a fatalError() if an attempt is made to pass an unsupported type. This more closely resembles what the ObjC Foundation does and makes bugs in the code obvious
- added unit tests to cover the above problems
- added the …
=> Align the UserDefaults implementation with Darwin Foundation

TestFoundation/TestNSNumber.swift
Fixed multiple occurrences of "Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions" errors which the Xcode 9 (9A235) tool chain generates while trying to compile the unit tests on a 2013 MacBook Pro.
=> Fixed "Expression too complex" build failures.

Foundation/HTTPCookieStorage.swift, TestFoundation/TestHTTPCookieStorage.swift
`HTTPCookieStorage` isn't thread-safe at all but should be.
=> fix HTTPCookieStorage threading issues

Foundation/NSNotification.swift
Per [Apple docs](https://developer.apple.com/documentation/foundation/notificationcenter), `addObserver` and `post` use `NSNotification.Name`
=> NotificationCenter should us NSNotification.Name per docs

Foundation/NSDictionary.swift
I noticed this method doesn't exist on Linux however apparently this was deliberately omitted from sclf as it relies on KVC which is not supported on Linux.
This PR stubs out the method as NSUnsupported().
=> Stub out value(forKey key: String)

Foundation/NSSwiftRuntime.swift
This resolves https://bugs.swift.org/browse/SR-6018 and restores Xcode builds for Mac development.
=> Automatically forward imports of Dispatch and only define ObjCBool in non objc contexts for compatability layers

Foundation/NSStringAPI.swift
When a substring gets bridged to NSString, it loses the initial offset,
therefore APIs that accept or return StringIndex ranges should handle
this case explicitly by adding/subtracting the substring start offset.
Similar to https://github.com/apple/swift/pull/12151
=> Fix Foundation extensions to Substring

Foundation/NSKeyedArchiver.swift, TestFoundation/TestNSKeyedArchiver.swift
Hi Apple,
a minor fix to NSKeyedArchiver for when objects being archived are not “AnyHashable”. Without the fix the following code does not work:
```Swift
let session = URLSession( configuration: .default )
let url = URL(string: "https://httpbin.org/get")!
_ = session.dataTask( with: URLRequest( url: url ) ) {
(data, response, error) in
if let data = data {
do {
let json = try JSONSerialization.jsonObject(with: data)
let archive = NSKeyedArchiver.archivedData(withRootObject: json)
let object = NSKeyedUnarchiver.unarchiveObject(with: archive)
let text = try JSONSerialization.data(withJSONObject: object)
NSLog( String(describing: String( data: text, encoding: .utf8 )) )
}
catch let e {
NSLog( "\(e)" )
}
}
else {
NSLog( "\(String(describing: error))" )
}
}.resume()
```
It crashes during the …
=> Fix to NSKeyedArchiver when object not AnyHashable

Foundation/Operation.swift, TestFoundation/TestOperationQueue.swift
- calling cancel() or operationQueue.cancelAllOperations() from inside Operation.main() no longer crashes the app when the operation returns from main()
- start() now skips the call to main() if the Operation is already in cancelled state
=> Aligned Operation cancel behavior with Darwin Foundation

Foundation/NSDictionary.swift, TestFoundation/TestNSDictionary.swift
The initialiser `init?(ContentsOfFile: String)` and `init?(contentsOf: URL)` were incorrectly defined in NSMutableDictionary. According to the [docs](https://developer.apple.com/documentation/foundation/nsdictionary) it should be defined in NSDictionary instead, this PR resolves this. 
I've also updated the tests to check for this initialiser in NSDictionary rather than NSMutableDictionary.
=> Moving init?(ContentsOfFile:) to NSDictionary

Foundation/NSString.swift, TestFoundation/TestNSString.swift
- passing nil to the usedEncoding: parameter no longer causes the NSString(contentsOf:usedEncoding:) to terminate with an error.
- implemented NSString(contentsOfFile:usedEncoding:)
- String(contentsOfFile:) now works too
=> NSString(contentsOfFile:usedEncoding:) fixes.

Foundation/Stream.swift
change StreamDelegate protocol signature to match https://developer.apple.com/documentation/foundation/streamdelegate/1410079-stream
Issue: https://bugs.swift.org/browse/SR-6088
=> Change StreamDelegate signature to match Darwin's

Foundation/JSONSerialization.swift, Foundation/NSNumber.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestNSNumber.swift
Cherry-pick of #1173 to `swift-4.0-branch`.
=> [4.0] SR-5640: JSONEncoder misrepresents UInt.max

Foundation.xcodeproj/project.pbxproj, Foundation/NSNumber.swift, Foundation/Stream.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSNumberBridging.swift, TestFoundation/main.swift
The four commits in this PR bring across the recent `NSNumber` fixes to the 4.0 branch.  They are:
- https://github.com/apple/swift-corelibs-foundation/pull/1213 NSNumber: More Darwin compatibility fixes
- https://github.com/apple/swift-corelibs-foundation/pull/1201 SR-5803: NSNumber no longer equates 1 and true
- Part of https://github.com/apple/swift-corelibs-foundation/commit/7bf00ded574ca5c720b935717f26278446b543c5. Work around a compiler complexity error
- https://github.com/apple/swift-corelibs-foundation/pull/1204 NSNumber: update API for SE-0170
=> [4.0] NSNumber fixes

Foundation/JSONSerialization.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestJSONSerialization.swift
Cherry-pick https://github.com/apple/swift-corelibs-foundation/pull/1197 to 4.0 branch.
=> [4.0] JSONSerialization: Add missing numeric types

Foundation/NSStringAPI.swift
Cherry-pick https://github.com/apple/swift-corelibs-foundation/pull/1244 to the 4.0 branch.
This has already been committed to the 4.0 branch in the overlay in https://github.com/apple/swift/commit/3e4a9d86a891f66fabbf75e0bc199ef9b67e7254
CC: @moiseev
=> [4.0] Fix extensions to Substring

Foundation/NSObject.swift
Hi Apple,
With apologies for the rash of controversial PRs this week, I’m getting to the end the preparation of a release candidate for the Android/Swift toolchain that I’ve been working on and testing with a wide range of Open Source packages (Alamofire, Moya, RxSwift etc.) for portability. One assumption that commonly comes up in these projects is that importing Foundation is enough to have Dispatch classes available to the Swift source i.e it is imported implicitly when you import Foundation.
You must have considered this, and for compatibility with Darwin I would have thought this was the way to go so I’ve added an @_exported import of Dispatch to NSObject.swift in the toolchain for want of a better place to put it. I had also experimented with exporting CoreFoundation but functions …
=> Implicit import of Dispatch when importing Foundation?

Docs/Status.md, Foundation.xcodeproj/project.pbxproj, Foundation/NSLock.swift, TestFoundation/TestNSLock.swift, TestFoundation/main.swift
- Implemented for NSLock and NSRecursiveLock.
- Use pthread_mutex_timedlock() where available (eg Linux).
- For macOS / iOS, emulate a timed lock using a condition
variable/mutex pair and use pthread_cond_timedwait().
- Add timeSpecFrom(date:) helper function and update
NSCondition.wait(until:) to use it, eliminating two calls
to gettimeofday().
The testing just consists of creating 1000 threads and then have each thread trying to get the lock in a loop along with some other contrived lock activity. Some more testing will probably need to be added to try and force some errors and also stress the thread/lock system.
`getOrAllocateTimedLockData()` needs the most attention as that uses `_stdlib_atomicCompareExchangeStrongPtr` to atomically set the shared mutex/cond pair used on macOS and the …
=> NSLock: Implement lock(before:)

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
This is reopening of #888 PR. Please read conversation there.
=> Implemented FileManager.attributesOfFileSystem()

Foundation/URLSession/URLSessionConfiguration.swift
New properties per [the API](https://developer.apple.com/documentation/foundation/urlsessionconfiguration?changes=latest_minor) doc. Though they may be irrelevant in the Linux server context, they may make sense in the Android context.
=> Stub out new properties/enum in URLSessionConfiguration

TestFoundation/TestNSLock.swift
This should prevent a race where the main thread completes its tests before the 2nd thread has obtained the lock.
=> NSTestLock: Obtain lock before waking up main thread for test

Foundation/Data.swift, Foundation/JSONEncoder.swift
Remove remaining references to SR-5206 hack by bringing the implementation inline with the Foundation overlay.
Applies apple/swift#11315 to swift-corelibs-foundation. This will go into the swift-4.0-branch as well.
=> Remove previous hack for SR-5206

Foundation/Data.swift, Foundation/HTTPCookieStorage.swift
```
Foundation/HTTPCookieStorage.swift:80:29: warning: 'init(contentsOfFile:)' is deprecated
guard let cookies = NSMutableDictionary(contentsOfFile: cookieFilePath) else { return }
```
and
```
Foundation/Data.swift:1593:13: warning: initialization of immutable value 'length' was never used; consider replacing with assignment to '_' or removing it
let length = count
```
=> Fix warnings in the Foundation build

Foundation/NSTimeZone.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestCodable.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestHTTPCookieStorage.swift, TestFoundation/TestISO8601DateFormatter.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestNSAttributedString.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSLocale.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSString.swift, TestFoundation/TestNumberFormatter.swift, TestFoundation/TestProcess.swift, TestFoundation/TestThread.swift, TestFoundation/TestTimeZone.swift, TestFoundation/TestURL.swift, TestFoundation/TestURLSession.swift
Changes I had to make to be able to test Foundation on Android. Results are good considering the differrences of the platform to vanilla Linux:
Executed 956 tests, with 15 failures (0 unexpected) in 20.926 (20.926) seconds
There seems to be some problem with TestNSAttributedString.test_enumerateAttributes. An invalid dictionary is returned from CFAttributedStringGetAttributesAndLongestEffectiveRange. I couldn’t puzzle out more than that. I’ve also disabled TestURLSession.test_cancelTask as it seems to result in intermmittent crashes though I’m running Foundation from a week ago and I see related commits. Other changes (to TestNSNumber.swift for example) might be useful for other 32 bit platforms.
Thanks!
=> For testing Foundation on Android

Foundation/NSString.swift
=> NSLocalizedString stub

CoreFoundation/URL.subproj/CFURLSessionInterface.c, CoreFoundation/URL.subproj/CFURLSessionInterface.h, Foundation/NSString.swift, Foundation/URLSession/http/EasyHandle.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, Foundation/URLSession/http/MultiHandle.swift
Hi Apple,
At the moment any network error using a URLSession contains only the default "The operation could not be completed” as its NSLocalizedDescription. This PR conveys the value of curl_easy_strerror through the implementation so something more specific is reported such as "Foundation.URLError(_nsError: Peer certificate cannot be authenticated with given CA certificates)"
Thanks.
=> NSLocalizedDescription for http errors taken from libcurl

CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/Locale.subproj/CFDateFormatter.c, CoreFoundation/RunLoop.subproj/CFRunLoop.c, CoreFoundation/String.subproj/CFString.c
- Merge function prototypes with the declaration that follows
on the next line to simplify declaration when the arguments
differ due to preprocessor arguments.
- Fix use of comma in while statement.
This is the second PR of C fixes along with https://github.com/apple/swift-corelibs-foundation/pull/1157 after which the Xcode project can be updated to recommended settings to include the latest Clang warnings.
The `while` statement definitely needs checking, I went with `&&` instead of `||` but a 2nd opinion would be good.
=> Fix more C warnings

Foundation/AffineTransform.swift, TestFoundation/TestAffineTransform.swift
- init(): Return a matrix with identity values.
- NSAffineTransform: Fix constructor
convenience init(transform: NSAffineTransform) ->
convenience init(transform: AffineTransform)
- Add NSAffineTransformStruct type and use for
NSAffineTransform.transformStruct
- NSAffineTransform: Store a private AffineTransform to use as
backing.
- Fixup tests.
=> AffineTransform: Align with Darwin and misc fixes

TestFoundation/TestNSNumberBridging.swift
A fix in the behavior of FloatingPoint.init(exactly:) means that the NSNumber bridging tests need to be updated. That fix is in apple/swift#11311, this PR replaces #1273.
=> Update NSNumberBridging test for init(exactly:)

TestFoundation/TestNSNumberBridging.swift
This reverts #1274. That change parallels apple/swift#11311, but that Swift-side change is causing other test failures.
=> Revert "Update NSNumberBridging test for init(exactly:)"

Foundation/NSString.swift, TestFoundation/TestNSString.swift
=> [4.0] NSString: Fix malformed string test and re-enable other disabled tests

Foundation/NSAttributedString.swift, TestFoundation/TestNSAttributedString.swift
- Add struct NSAttributedStringKey and use for the attribute key
instead of String.
=> NSAttributedString: Align methods with Darwin.

Foundation/Data.swift
This pulls in the fixes for:
Guard Data access to NSData._isCompact under availability guards
Ensure that hashing data with zero bytes avoids empty allocations and fix bridged empty data hashes from de-referencing null values (#12509)
=> Synchronize Data.swift from the overlay

Foundation/NSLocale.swift
Resolves  [SR-5989](https://bugs.swift.org/browse/SR-5989)
Added `deinit` to NSLocale that calls to `_CFDeinit` to release identifier and other resources.
I also wanted to add test cases for this, but could not figure it out how to do it.
I wanted to create a `weak` reference to an identifier of the locale and check if it becomes nil after `Locale` goes out of scope, but ...
`Locale` / `NSLocale` returns `Swift String` and as its a `struct`, we won't be able to test with it.
Another idea was to get this directly from `CFLocaleGetValue` but as CoreFoundation objects are automatically memory managed in Swift, I am not sure if this would work. 
Any ideas ?
=> [SR-5989] Added missing call to _CFDeinit for NSLocale

Foundation/DateInterval.swift
Comment of the function says:
> /// - precondition: `end >= start`
but it actually uses `if -> fatalError` instead of `precondition`,
Other functions of `DateInterval` use `precondition`-s, only this one uses 'fatalError', probably makes sense to change it as well.
=> Use precondition instead of fatalError in DateInterval initializer

Foundation/NSGeometry.swift, TestFoundation/TestNSGeometry.swift
```swift
CGRect(x: 0, y: 0, width: -5, height: -5) == CGRect(x: -5, y: -5, width: 5, height: 5)
// used to return false
// should standardize before comparison first
```
```swift
let a = CGRect(x: CGFloat.infinity, y: 1, width: 2, height: 3)
let b = CGRect(x: 1, y: CGFloat.infinity, width: 2, height: 3)
a == b
// used to return false
// should return true if both `a` and `b` have any origin's value set to +∞
```
=> Implemented some CGRect's missing APIs

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/Thread.swift, TestFoundation/TestThread.swift
- _CFThreadSetName(): Take the thread ID, as Linux allows setting
the name of another thread. On macOS just check that it is the
same as pthread_self().
- On Linux, trim the name to 15 characters as that is the maximum
that can be set.
- When starting a thread, set it's name in pthreads if the name is
non-nil.
- On Linux, make _thread an Optional initialised to nil instead of setting
it to pthread_t(), which gives it the value 0. This matches macOS
behaviour.
- TestThread.swift: Add some more tests.
=> Thread: Fixes to thread name

Foundation/NSKeyedArchiverHelpers.swift
SE-0054 (Abolish ImplicitlyUnwrappedOptionalType) substantially reduced
the number of places that '!' can be used, but the implementation missed
certain cases like this one. That implementation is being overhauled to
catch all the illegal cases.
=> Fix cast that is disallowed by SE-0054.

TestFoundation/TestCodable.swift
Having tests abort via `fatalError()` is not as useful as just failing the tests in situations where further tests can still be run.
=> TestCodable: Replace fatalError() with XCTFail

TestFoundation/TestNSNumberBridging.swift
This test change goes with the fix in https://github.com/apple/swift/pull/12739.
=> Fix NSNumber bridging test for FloatingPoint(exactly:) fix

CoreFoundation/URL.subproj/CFURLComponents.c, Foundation/URLComponents.swift, TestFoundation/TestCodable.swift, TestFoundation/TestURL.swift
Continuation of #1108, #1127, #1148 & #1192
This PR mirrors final missing changes from https://github.com/apple/swift/pull/11368
---
- URLComponents
---
I had problems with `NSCFConstantString` being overreleased (`CFString` constants bridged from CoreFoundation's `CFSTR("")`).
I don't know how to properly fix this, so any advice is welcome.
I took the inspiration for a `CFStringCreateCopy` workaround from https://github.com/apple/swift-corelibs-foundation/pull/144/files
=> Codable conformance for URLComponents

TestFoundation/TestNSNumberBridging.swift
Exact conversions are succeeding on 64-bit Linux.
=> Disable failing NSNumber bridging tests

Foundation/URLSession/http/HTTPBodySource.swift, Foundation/URLSession/http/MultiHandle.swift
Changed dispatch_data_t to DispatchData
Changed dispatch_io_t to DispatchIO
Changed dispatch_source_set_timer to DispatchSourceTimer
=> Documentation changes

CoreFoundation/Base.subproj/ForFoundationOnly.h, Foundation.xcodeproj/project.pbxproj, Foundation.xcodeproj/xcshareddata/xcschemes/CoreFoundation.xcscheme, Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundation.xcscheme, Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme, Foundation.xcodeproj/xcshareddata/xcschemes/plutil.xcscheme
- This enables more clang warnings which finds some issues
in the CoreFoundation code. Fix some of these.
=> Upgrade xcode project to latest Recommended Settings

TestFoundation/TestCharacterSet.swift
It seems like [SR-2509](https://bugs.swift.org/browse/SR-2509) is already fixed. I added a couple of additional tests to make sure that the CharacterSet.union() works as expected. 
I tested it on **macOS 10.12.6 + Xcode 9.0 + Swift 4.0** and also on **Ubuntu 14.04 + swift-4.0.2-RELEASE-ubuntu14.04**
=> [SR-2509] Add tests to assure that the issue is fixed

Foundation/NSURL.swift, TestFoundation/TestURL.swift
Consider this program
```swift
let nsurl = NSURL(string: "http://google.com")!
let url = URL(string: "http://amazon.in")!
print(url)
print(nsurl)
```
Output on Darwin
```
http://amazon.in
http://google.com
```
Output on Linux
```
<CFURL 0x8eb3ed0 [0x7f7f63d54c38]>{string = http://amazon.in, encoding = 134217984, base = (null)}
<CFURL 0x8e41620 [0x7f7f63d54c38]>{string = http://google.com, encoding = 134217984, base = (null)}
```
This PR makes the output on Linux same as that on Darwin.
=> Change NSURL.description to match Darwin

TestFoundation/TestHTTPCookieStorage.swift
- Merge 2 tests that had to be run in specific order.
- Clear the cookie storage before each test.
=> TestHTTPCookieStorage: Remove order dependancy of tests

Foundation/Data.swift, TestFoundation/TestNSData.swift
Solves [SR-6361](https://bugs.swift.org/browse/SR-6361) 
This code snippet:
```
var data = Data(bytes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])[4..<6]
data.withUnsafeMutableBytes { (ptr: UnsafeMutablePointer<UInt8>) in
ptr.advanced(by: 1).pointee = 0xFF
}
```
crashes with:
`fatal error: UnsafeMutableRawBufferPointer with negative count`
because `count` was not calculated correctly (`_offset` was not taken into account)
The existing tests were not covering this case because it works correctly for data slices when _length > range.lowerBound.
I created new tests for this exact situation but I can also update the existing ones by adding one more check to them.
Please, let me know what you think.
=> [SR-6361] Fix Data.withUnsafeMutableBytes() for slices with length < range.lowerBound

Docs/Proposals/0001-jsonencoder-key-strategy.md
Add a proposal for handling snake and camel case keys in JSONEncoder.
=> Add SCLF-0001: JSON Key Strategies

Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
Fixes [SR-6401](https://bugs.swift.org/browse/SR-6401)
=> Change JSONSerialization to escape solidus like macOS does

Foundation/NSCFString.swift
This will allow `TestNSString.test_swiftStringUTF16` and a few TimeZone related test cases to pass.
=> Fix CFSwiftStringGetBytes on big endian

Foundation/NSError.swift
This reverts commit 14e9a795ac0baa82daeae2ffe588310007a9008d. We don't want this change in the 4.1 branch, since the corresponding Swift runtime change is not there yet either.
=> Revert "Adapt to renaming of _getDefaultErrorCode() SPI."

Foundation/AffineTransform.swift, Foundation/Data.swift, Foundation/Dictionary.swift, Foundation/FileManager.swift, Foundation/Host.swift, Foundation/JSONSerialization.swift, Foundation/NSArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSCFSet.swift, Foundation/NSCoder.swift, Foundation/NSConcreteValue.swift, Foundation/NSDictionary.swift, Foundation/NSGeometry.swift, Foundation/NSKeyedCoderOldStyleArray.swift, Foundation/NSLock.swift, Foundation/NSOrderedSet.swift, Foundation/NSRange.swift, Foundation/NSSet.swift, Foundation/NSString.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSUUID.swift, Foundation/Process.swift, Foundation/Set.swift, Foundation/String.swift, Foundation/Thread.swift, TestFoundation/TestNSKeyedArchiver.swift
Patch for [SE 0184a](https://github.com/apple/swift/pull/12200)
=> Fix against se-0184a

Foundation/NSData.swift, TestFoundation/TestNSData.swift
- Remove 'convenience' from:
init()
init(bytes:length:)
init(bytesNoCopy:length:)
init(bytesNoCopy:length:freeWhenDone:)
init(bytesNoCopy:length:deallocator:)
init(contentsOfFile:options:)
init?(contentsOfFile:)
init(data:)
init(contentsOf:,options:)
init?(base64Encoded base64String:options:)
init?(base64Encoded base64Data:options:)
- Add:
init?(contentsOf:)
(deprecated) base64Encoding()
- Add (unimplemented):
(deprecated) init?(contentsOfMappedFile:)
(deprecated) class func dataWithContentsOfMappedFile()
contains()
contains(where:)
NSMutableData:
- Remove 'convenience' from:
init?(capacity:)
init?(length:)
- Add:
init(bytes:length:)
- Add description documentation to public methods.
- Update tests.
=> NSData: Align methods with Darwin

TestFoundation/TestBundle.swift, TestFoundation/TestHTTPCookieStorage.swift, TestFoundation/TestNSData.swift, TestFoundation/main.swift
This small change is part of the Darwin compatibility testing https://github.com/apple/swift-corelibs-foundation/pull/1286 to allow pointing at different test bundles more easily.
`testBundle` was moved from `main.swift` as that file is not included in the DCT unit tests.
=> Replace Bundle.main with testBundle() for consistency.

build-android
copying libFoundation.so to armv7 was not recognized by the ld tool
=> copying libFoundation.so to android directory and not to armv7

Foundation.xcodeproj/project.pbxproj, Foundation/Host.swift, TestFoundation/TestHost.swift, TestFoundation/main.swift
This commit ensures that the `resolve` functionality only calculates
addresses and names once, as appears to be originally intended.
Furthermore, this mitigates a bug where addresses would be endlessly
appended to the `addresses` array, causing long term unbounded heap
growth.
--
Am I correct in thinking this needs to go to master, then cherry-picked into 4.1 and 4.0? I couldn't find any docs in the contributing guidelines about branch structure.
=> Fix heap growth in Host.swift

Foundation/HTTPCookieStorage.swift, TestFoundation/TestHTTPCookieStorage.swift
Implementation of the description property for HTTPCookieStorage, to remain as close as possible to its behavior on darwin.
For this program:
```
print(HTTPCookieStorage.shared)
print(HTTPCookieStorage.sharedCookieStorage(forGroupContainerIdentifier: "test"))
```
... the output on Darwin is:
```
<NSHTTPCookieStorage cookies count:12>
<NSHTTPCookieStorage cookies count:1>
```
With this PR the output on Linux will be
```
<HTTPCookieStorage cookies count:12>
<HTTPCookieStorage cookies count:1>
```
=> Implementing HTTPCookieStorage.description

Foundation/NSNotification.swift
Fixes [SR-6419](https://bugs.swift.org/browse/SR-6419).
=> [SR-6419] Use `@available(*, unavailable)` instead of inappropriate `@available(*, obsoleted: 4.0)`

Foundation/NSError.swift
`CFError` conforms to `Error` and contains a `public var _userInfo`.
In https://github.com/apple/swift/commit/77a360907f7d04f253c8a707f61a3de55516a887 the type of this var was changed from `Any?` to `AnyObject?` but this change was not made in SCLF too.
Consequently there is currently a compiler warning:
> Var '_userInfo' nearly matches defaulted requirement '_userInfo' of
> protocol 'Error'
Fix this warning by adjusting the type of the `_userInfo` var.
=> CFError: fix compile warning

Foundation/NSLock.swift
In https://github.com/apple/swift-corelibs-foundation/commit/6476c4fdae88e00688d743af5130179a5b2329d8 changes were made for compatibility with SE-0184.
A function in `NSLock` was missed though, probably because it is only compiled when building the project in Xcode on macOS.
Fix these warnings too.
=> NSLock: fix warnings on macOS

Foundation/NSString.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSString.swift
A potential fix for this issue: 
https://bugs.swift.org/browse/SR-6139
Before, the method that is responsible to create the immutable copy of NSString was simply
returning self, that’s why copying didn’t happen and this test was failing: 
```
func test_constructorWithCopyItems() {
let foo = "foo" as NSMutableString
let array1 = NSArray(array: [foo], copyItems: false)
let array2 = NSArray(array: [foo], copyItems: true)
XCTAssertEqual(array1[0] as! String, "foo")
XCTAssertEqual(array2[0] as! String, "foo")
foo.append("1")
XCTAssertEqual(array1[0] as! String, "foo1")
// The below test fails on sclf
XCTAssertEqual(array2[0] as! String, "foo")
}
```
Please, let me know what you think.
=> [SR-6139] Implement NSString.copy() method

TestFoundation/TestDateFormatter.swift
Currently, some of the `DateFormatter` tests fail on High Sierra because the format of the `.medium` date style has changed.  This is likely due to changes in the underlying platform ICU.
@parkera expressed the opinion to me that we shouldn't be testing the appearance of the `DateFormatter` presets because they are subject to change and not precisely documented.
I don't entirely agree with that point of view as if the format does change on Darwin platforms then we want to reflect those changes in SCLF, and having our tests start failing is the best way to detect that.
However, there is a whole separate discussion about whether Swift on Linux should use the platform ICU at all, or whether we should ship Apple's fork of ICU (which is used on Darwin) with Swift on Linux to sidestep all these …
=> DateFormatter: disable testing of medium date style

Foundation/NSCalendar.swift, TestFoundation/TestNSData.swift
> Warning: Overlapping accesses to 'self', but modification requires exclusive access; consider copying to a local variable
There are more of these in the codebase, but here's a fix for a few.
=> Fix warning: overlapping access to 'self'

CoreFoundation/Locale.subproj/CFCalendar.c, Foundation/NSCalendar.swift, TestFoundation/TestDate.swift
Resolves: [SR-6303](https://bugs.swift.org/browse/SR-6303)
Running this code:
```
let components = DateComponents(calendar: Calendar(identifier: .gregorian),
timeZone: .current,
era: 1,
year: 2017,
month: 11,
day: 5,
hour: 20,
minute: 38,
second: 11,
nanosecond: 40)
guard let date = Calendar(identifier: .gregorian).date(from: components) else {
return
}
let recreatedComponents = Calendar(identifier: .gregorian).dateComponents(in: .current, from: date)
```
causes Thread 1: EXC_BAD_ACCESS (code=1, address=0x608a12c5cd78)
in: CFCalendar._CFCalendarComposeAbsoluteTimeV() 
on the line: ucal_set(calendar->_cal, field, value);
After investigating the issue, I found out that -1 is returned for UCalendarDateFields for nanoseconds and quarter calendar components. Also, one typo for the “era” …
=> [SR-6303] Handle non-existing UCalendarDateFields without crashing

Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestURLRequest.swift
Darwin performs normalization of `httpMethod` for 6 specific HTTP methods. Match this behaviour.
=> SR-6405: URLRequest: Implement normalization for httpMethod

Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestURLRequest.swift
Implement `NSURLRequest.description` to match Darwin. Add tests.
Also add a test for `URLRequest.description` which was already correct but untested.
=> SR-6403: NSURLRequest: implement `description` and add tests

Foundation/Measurement.swift
https://github.com/apple/swift-corelibs-foundation/pull/1349/files?w=1
=> [gardening][Measurement] Move operators into types

lib/product.py
The new ELF registration scheme uses linker tables and only requires a
single object to be added to the link.
=> build: migrate to the new ELF registration scheme

Foundation/Measurement.swift
A follow up for #1349.
Once this is merged, I will sync the file with the overlay.
=> [Measurement] Group operators into just two extensions

Foundation/Measurement.swift, Foundation/MeasurementFormatter.swift
This is a subsequent PR of #1349 and #1350.
This contains the changes from https://github.com/apple/swift/pull/4167.
=> Synchronize Measurement.swift from the overlay

TestFoundation/TestDecimal.swift, TestFoundation/TestNSAttributedString.swift, TestFoundation/TestNSKeyedArchiver.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNumberFormatter.swift, TestFoundation/TestURLSession.swift, TestFoundation/TestXMLDocument.swift, TestFoundation/TestXMLParser.swift
I noticed that the tests were taking quite a while to compile.
Using the "-warn-long-expression-type-checking" flag, I measured the compile time of the test project. The total of types over 100ms was around 27 seconds before this change and around 25 seconds after (on my build configuration), so it shaves off a few seconds there.
I also took the opportunity to reduce the number of attempted threads in the URL test from 640 to 10. There isn't much value add in going above the number of cores we're going to find on most machines, and that dramatically reduces the run time of that test.
The tests still take quite a while to build, so I'd like to continue this investigation. But this is a reasonable start.
=> Reduce test compile times.

Foundation/NSIndexSet.swift, TestFoundation/TestNSArray.swift
- These methods are implemented as (relevant NSIndexSet).enumerate(options: options…), so the fix goes in NSIndexSet.
- Includes NSArray tests.
=> Restore .concurrent for block-based enumerateObjects(…) methods in NSArray
