Foundation/NSIndexSet.swift, TestFoundation/TestNSArray.swift
(Let's try this again. The previous attempt had an issue in the test for enumerateObjects(at:options:using:) where it could've set the stop flag to true before all indexes corresponding to our expectation had been set to true, which could lead it to inconsistently failing.)
NSArray implements these methods as: `someIndexSet.enumerate(options: options) { block(self[$0]…) }`, so the fix goes in NSIndexSet.
Includes NSArray tests.
=> Restore the .concurrent option for NSArray's enumerateObjects(…)

TestFoundation/TestCalendar.swift
While validating https://bugs.swift.org/browse/SR-3193, observed that Linux is behaving as expected. The current test-cases in TestFoundation checks for Sunday and Wednesday of the week. Adding test-data inputs for the rest of the days of the week for completeness.
=> Added more test-data to Calendar.isDateInWeekend api testcase.

Foundation/NSPathUtilities.swift, TestFoundation/TestNSString.swift
The following code behaves differently on macOS and Linux:
```swift
NSString(string: "..").deletingPathExtension
```
On Linux, the resulting value is `.` while on macOS, it's `..`.
I think the latter make far more sense since `..` mean parent directory,
treating the last dot as "extension" is a bit of a stretch. Plus, this
logic existed on macOS longer (therefore has more existing users). So it
make sense to align Linux Foundation's behavior to that of macOS.
JIRA: https://bugs.swift.org/browse/SR-6647
=> Fix String.deletingPathExtension Inconsistency

Foundation.xcodeproj/project.pbxproj, Foundation/URLSession/Message.swift, Foundation/URLSession/http/HTTPMessage.swift, build.py
Moving the common Header parsing code to Message.Swift which will be aligned under NativeProtocol Class in next PR.
=> Carving out common code out of HTTPMessage

Foundation/IndexPath.swift, Foundation/IndexSet.swift, Foundation/NSIndexSet.swift, Foundation/NSRange.swift, Foundation/NSString.swift
- Fixes for the following warnings:
'BidirectionalSlice' is deprecated: renamed to 'Slice'
'DefaultRandomAccessIndices' is deprecated: renamed to 'DefaultIndices'
'index(_:offsetBy:)' is deprecated: all index distances are now of type Int
initializer for struct 'CFRange' must use "self.init(...)" or "self = ..." because the struct was imported from C
deinitialize()' is deprecated: the default argument to deinitialize(count:) has been removed, please specify the count explicitly
'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
=> Misc warnings fixes

Foundation/HTTPCookie.swift, Foundation/JSONEncoder.swift, Foundation/ProcessInfo.swift, Foundation/XMLElement.swift, TestFoundation/TestJSONSerialization.swift, TestFoundation/TestXMLDocument.swift
`flatMap()` is renamed to `compactMap()` (initially for `Sequence`).
See [SE-0187](https://github.com/apple/swift-evolution/blob/master/proposals/0187-introduce-filtermap.md) for more details.
=> Replace deprecated Sequence.flatMap() with Sequence.compactMap()

Foundation/HTTPCookie.swift, Foundation/JSONEncoder.swift, Foundation/ProcessInfo.swift, Foundation/XMLElement.swift, TestFoundation/TestJSONSerialization.swift, TestFoundation/TestXMLDocument.swift
This reverts commit 4c8932b44762413da37533145ae2c6ed42134557, reversing
changes made to 9cb8ca1029650c0f3b3933210d61a6f3efe7f7b7.
This was auto-merged onto the `swift-4.1-branch` but that branch doesn't support `compactMap`. This is breaking the build for swift-4.1, so revert it from the `swift-4.1-branch`
=> Revert "Merge pull request #1379 from spevans/pr_flatmap_to_compactmap"

CoreFoundation/Base.subproj/CFInternal.h
`xlocale.h` was removed in glibc 2.26 so any version of Linux with that or later versions will not be able to compile successfully. This change adds a guard to check that if we're *not* compiling on Linux, to go ahead and include it.
=> Added guard around #include <xlocale.h> for Linux

TestFoundation/TestHTTPCookieStorage.swift
Per the guidance in https://github.com/apple/swift-corelibs-foundation/pull/1313 this PR splits out the test for `HTTPCookieStorage.description`
cc @ianpartridge
=> Add a testcase for HTTPCookieStorage.description

Foundation.xcodeproj/project.pbxproj, Foundation/URLSession/Message.swift, Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/http/HTTPMessage.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, build.py
Moving  protocol agnostic implementation under NativeProtocol.
eg: Header parsing code is common to HTTP and FTP.In both cases the HEADERS are split based on CRLF characters.
HTTPURLProtocol.swift has some common  implementation which will be moved to NativeProtocol.swift in the next PR.
=> Move common protocol implementation to NativeProtocol

Foundation/URLProtocol.swift, Foundation/URLSession/URLSession.swift, TestFoundation/TestURLSession.swift
Basic users of URLSession may want to use the shared URLSession instance`URLSession.shared`. 
The shared URLSession instance uses shared instances of HTTPCookieStorage, URLCache and URLCredentialStorage, the last two still remain unimplemented. It is likely that some of the users that want to use `URLSession.shared` aren't interested in using the shared storages and cache! So, we need not wait for URLCache and URLCredentialStorage to be fully available here (we can plug them in later, see the TODOS). In that way, we are offering `URLSession.shared` to at least those users!
=> Add initial implementation of URLSession.shared

lib/script.py
The build scripts for foundation bypass the Swift driver and use
the -frontend mode directly. The command line interface for
-frontend is not officially supported and is subject to change.
A recent change was that when merging partial modules to form a
final module file, the -sil-merge-partial-modules flag must be
passed in so that serialized SIL can be preserved in the final
module file.
Preserving serialized SIL is now a requirement, since soon
default argument generators and stored property initializers
will be emitted with non-public linkage, requiring clients to
deserialize SIL when calling these entry points.
=> Pass -sil-merge-partial-modules flag

Foundation/NSData.swift, TestFoundation/TestNSData.swift
- When aligning the init() methods with Darwin in PR #1287,
converting the NSData `convenience` methods to designated
initialisers stopped them from being inherited by NSMutableData
as it declared its own designed initialisers.
- Add in all of the missing initialisers and add tests to ensure
their presence is checked at compile time.
- Fix init(data: Data) to use the correct length of the data
argument when copying the bytes.
=> NSMutableData: Restore missing initialisers

CoreFoundation/Base.subproj/CFSortFunctions.c
These two defines, similar to the int64 variants already present, are required on 32bit systems (e.g. linux-arm).
=> Added missing __checkint macros for 32bit systems

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Base.subproj/module.modulemap, CoreFoundation/PlugIn.subproj/CFBundle.c, CoreFoundation/PlugIn.subproj/CFBundlePriv.h, CoreFoundation/PlugIn.subproj/CFBundle_Executable.c, CoreFoundation/PlugIn.subproj/CFBundle_Internal.h, TestFoundation/TestBundle.swift
This is an implementation that tracks the proposal at <https://github.com/apple/swift-corelibs-foundation/pull/1392>.
=> [FHS bundles] Initial implementation.

Docs/FHS Bundles.md
Please leave comments here or at the thread I'm about to start on the swift-corelibs-dev list.
=> [FHS bundles] Proposal

Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/http/HTTPURLProtocol.swift
This PR is part of #1355 , moving the common implementation to NativeProtocol.
Along with the movement I had to  implement a ```validateHeaderComplete```  method which basically checks whether the header is  complete or not .However,in  HTTP/0.9  , we received the body data before CURL tells us that the headers are complete and  this behavior is specific to HTTP.
Hence ,I have moved the common code to NativeProtocol and overridden the specific behavior in ```HTTPURLProtocol```.
=> Moving common implementation to NativeProtocol.swift

Foundation/UserDefaults.swift
If we’re running this version of Foundation, there is no MCX nor configuration profiles that can force a defaults key. Therefore, by definition, unless in the future we want to introduce such a facility in non-Apple OSes, this is always false.
=> Implement forced keys in UserDefaults.

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Bail early if after calling `deletingLastPathComponent` the path is empty. There is
no point in doing a traversal and trying to create an empty directory at the parent
path. In addition, this ends up tripping a pre-condition when we try finding the next
parent path component again.
This addresses SR-4570.
=> Fix crashes when creating directories at single component relative paths

CoreFoundation/Base.subproj/CFFileUtilities.c, CoreFoundation/Base.subproj/CFKnownLocations.c, CoreFoundation/Base.subproj/CFKnownLocations.h, CoreFoundation/Base.subproj/CFPriv.h, CoreFoundation/Preferences.subproj/CFPreferences.c, CoreFoundation/build.py, Foundation.xcodeproj/project.pbxproj, build.py
On FHS/XDG systems, the paths for UserDefaults are now:
- `/usr/local/etc` for AnyUser preferences (replaces `/Library/Preferences`)
- `$XDG_CONFIG_DIR` for CurrentUser preferences (replaces `$HOME/Library/Preferences`)
(`$XDG_CONFIG_DIR` is typically, and defaults to, `$HOME/.config/`.)
=> Use FHS/XDG paths for UserDefaults on Linux & BSD-y OSes

CoreFoundation/Parsing.subproj/CFXMLInterface.c, TestFoundation/TestXMLDocument.swift
Check before dereferencing `nodesetval` because it may be `NULL` if an XPath query
returns no results (but is a valid query).
Fixes SR-4628.
=> Avoid crashing when XPath queries return no results.

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift
- The methods in NSMutableArray were NSUnimplemented but the NSArray
versions were fully implemented so inherit those.
- Add tests for init?(contentsOfFile:) and init?(contentsOfURL:)
=> NSMutableArray: remove init?(contentsOf{File,URL}:) override

CoreFoundation/RunLoop.subproj/CFRunLoop.c
=> Fix a typo in logging

TestFoundation/TestAffineTransform.swift
<SR-3941: AffineTransform.rotate(byRadians:) can be wrong> looks fixed already.
Add a test for it.
=> Add test for SR-3941.

Foundation/Calendar.swift
The `compare` method on `Calendar` said `orderedAscending` twice, when it meant to say `orderedAscending` and `orderedDescending`. 
This PR supercedes #1417.
cc @alblue & @parkera
=> Fixed comment on Calendar's compare method.

Docs/Status.md
Follow up to #1368, did a deeper review to find entries that are out of date
=> Update status doc

Foundation/NSError.swift, TestFoundation/TestNSError.swift
A convenience method to create a Swift `Error` from an error code has been added to stdlib `NSError.swift` (https://github.com/apple/swift/blob/master/stdlib/public/SDK/Foundation/NSError.swift#L644) some time ago. This PR also adds this method (and a unit test) to corelibs `NSError.swift`.
=> Sync stdlib CocoaError convenience method

Foundation/Data.swift
Needed to keep master compiling against the Swift 5.0 branch. To be reverted once the Swift repo rebranches 5.0.
=> Restore Data.Indices to be a CountableRange

Foundation/IndexSet.swift
Similar to #1423 to keep compatibility with both the 5.0 branch and master. To be reverted once swift rebranches 5.0.
=> Restore two more instances of CountableRange

Foundation/Data.swift
That's apple/swift#14484. This only affects the Apple-platform implementation anyway.
=> Sync with the Swift repository on the _silgen_name thing

README.md
The FAQ, as formatted on GitHub, presents questions smaller than answers to the point that it's a little hard to read. Let's fix that.
=> [gardening] Enlarge question headings in README.md

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/CFPriv.h, Foundation/FileManager.swift, Foundation/NSPathUtilities.swift, Foundation/ProcessInfo.swift
- Added ProcessInfo.userName and ProcessInfo.fullUserName as in Darwin Foundation
- Added NSFullUserName() as in Darwin Foundation
- Added underlying implementation in Core Foundation CFCopyFullUserName() for POSIX OS.
=> Added userName and fullUserName to ProcessInfo

TestFoundation/TestNSString.swift
We can un-xfail this test due to https://github.com/apple/swift/pull/13877
=> remove an xfail from a test that will now pass

TestFoundation/TestNSString.swift
Revert string comparison changes to see if it fixes the linux bots
=> revert string comparison changes

Foundation/RunLoop.swift, TestFoundation/TestRunLoop.swift
At the Swift layer, if one of the known RunLoopMode constants is used, substitute a pointer to the real CFStringRef it refers to.
=> RunLoop.add(_ timer…) doesn't add the timer to common modes on Linux

CoreFoundation/PlugIn.subproj/CFBundle_Executable.c, Foundation/Bundle.swift, TestFoundation/TestBundle.swift
- Fixed prefix path for FHS Installed Bundles in Core Foundation
- Updated Bundle.url(forAuxiliaryExecutable:) return type as URL
- Added FindExecutable test in TestBundle
- Cleaned TestBundle.swift
Unified version of Pull Request [#1436](https://github.com/apple/swift-corelibs-foundation/pull/1436).
=> Fixed prefix path for FHS Installed Bundles

Foundation/NSDictionary.swift, TestFoundation/TestNSDictionary.swift
Hi Apple,
Using a String as a key when setting a value in an NSDictionary causes a crash on Linux. This minor fix brings it into line with Darwin Foundation where this is possible.
```
Could not cast value of type 'Swift.AnyHashable' (0x1027b3b10) to 'SwiftFoundation.NSObject' (0x101a56668).
2018-02-16 14:30:46.355774+0000 TestFoundation[7306:8715333] Could not cast value of type 'Swift.AnyHashable' (0x1027b3b10) to 'SwiftFoundation.NSObject' (0x101a56668).
(lldb) up
frame #9: 0x000000010165b114 SwiftFoundation`NSMutableDictionary.subscript.setter(newValue=some, key=Swift.AnyHashable @ 0x00007fff5fbfcd88, self=0x000060800e181fe0) at NSDictionary.swift:649
646 	        }
647 	        set {
648 	            if let val = newValue {
-> 649 	                setObject(val, forKey: key)
650 …
```
=> NSDictionary fix when key is a String rather than NSString.

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- FileManager.fileSystemRepresentation returns a heap allocated
pointer that needs to be freed by the caller.
=> [4.1] SR-6449: FileManager.removeItem(atPath) leaks

Foundation/ProcessInfo.swift, TestFoundation/TestProcessInfo.swift
- Reparse the environment variables each time ProcessInfo.processinfo.enviroment is read.
- Use _CFEnviron() instead of environ as it is more portable.
- Use more portable string decoding, dont assume UTF-8.
=> [4.1] SR-6968: ProcessInfo.processInfo.environment only gets once

Foundation/Codable.swift, Foundation/JSONEncoder.swift, TestFoundation/TestJSONEncoder.swift
- If an NSNumber was initialised from a boolean then dont allow it
to be converted to a numeric value.
- Use same boolean check as Foundation overlay method.
=> [4.1] SR-7017: JSONDecoder will decode booleans as numbers.

Foundation/NSIndexSet.swift, TestFoundation/TestIndexSet.swift
Fixes wrong IndexSet range merging. Currently, all range extension collapse this range with next.
Bug introduced here https://github.com/apple/swift-corelibs-foundation/commit/fa68db074506d05d9015048c084d0bf2b9ae5cc9#diff-e7f44555b2cc650b187ee9d2cb0e9132R596
Affects 4.0, 4.1 and master
=> Fix IndexSet/NSIndexSet range merging

Foundation/ProcessInfo.swift, TestFoundation/TestProcessInfo.swift
- Reparse the environment variables each time
ProcessInfo.processinfo.enviroment is read.
=> SR-6968: ProcessInfo.processInfo.environment only gets once

closure/runtime.c
Windows x86_64 is a LLP64 environment.  `unsigned long` is not `size_t`.
Adjust the parameter to be the correct size for the allocator.  This is
compatible with the previous implementation on LP64 environments.
Prefer to use the `__sync_bool_compare_and_swap` over the MSVC
intrinsic which is overly strong.  While in the area, remove an unused
compare and swap method.
=> closure: make it build on Windows x86_64

Foundation/Codable.swift, Foundation/JSONEncoder.swift, TestFoundation/TestJSONEncoder.swift
- If an NSNumber was initialised from a boolean then dont allow it
to be converted to a numeric value.
Tested against native Darwin Foundation.
=> SR-7017: JSONDecoder will decode booleans as numbers.

CoreFoundation/Collections.subproj/CFData.c, Foundation/NSData.swift
Test case:
```
for _ in 0..<10 {
let data = Data(base64Encoded: "UE9TVCAvIEhUVFAvMS4wDQpDb250ZW50LUxlbmd0aDoNCg0K")!
}
```
Valgrind memcheck tool output before the fix (as reported in SR-6849):
```
==7078== LEAK SUMMARY:
==7078==    definitely lost: 360 bytes in 10 blocks
```
Valgrind memcheck tool output after the fix:
```
==20265== LEAK SUMMARY:
==20265==    definitely lost: 0 bytes in 0 blocks
==20265==    indirectly lost: 0 bytes in 0 blocks
==20265==      possibly lost: 0 bytes in 0 blocks
```
Summary:
This is a regression from the https://github.com/apple/swift-corelibs-foundation/commit/df3ec55fe6c162d590a7653d89ad669c2b9716b1 commit  for the High Sierra changes. 
Previously, PR: https://github.com/apple/swift-corelibs-foundation/pull/380 had a fix for NSData leak …
=> Fix for SR-6849 and SR-6962 leak in NSData and NSMutableData

Foundation/NSDictionary.swift, TestFoundation/TestNSDictionary.swift
Taken from https://github.com/apple/swift-corelibs-foundation/pull/1438
Otherwise you can get the following crash:
Could not cast value of type 'Swift.AnyHashable' (0x1027b3b10) to 'SwiftFoundation.NSObject' (0x101a56668).
2018-02-16 14:30:46.355774+0000 TestFoundation[7306:8715333] Could not cast value of type 'Swift.AnyHashable' (0x1027b3b10) to 'SwiftFoundation.NSObject' (0x101a56668).
(lldb) up
frame #9: 0x000000010165b114 SwiftFoundation`NSMutableDictionary.subscript.setter(newValue=some, key=Swift.AnyHashable @ 0x00007fff5fbfcd88, self=0x000060800e181fe0) at NSDictionary.swift:649
646 	        }
647 	        set {
648 	            if let val = newValue {
-> 649 	                [4ms[0metObject(val, forKey: key)
650 	            } else {
651 	                removeObject(forKey: …
=> [4.1] Fix for when key is a String rather than NSString.

lib/script.py
https://github.com/apple/swift/pull/14243 changes paths for libraries to `oldpath/arch/libxyz`. This path adds a search path to account for it.
Requires
https://github.com/apple/swift/pull/14243
=> add a linker search path to account for library path changes to platforms without fat binaries

Foundation/NSURL.swift, TestFoundation/TestURL.swift
On Linux , the URL.description seems to be incomplete with respect to Darwin, when the URL has a component string associated with it .
=> Changes done to align NSURL.description with Darwin code

Foundation/NSDictionary.swift, Foundation/NSIndexSet.swift
The block must not escape the withoutAcutallyEscaping closure parameter scope.
With https://github.com/apple/swift/pull/15046 such loose usages of withoutActuallyEscaping are no longer allowed. The ``block`` must not escape the scope of the withoutActuallyEscaping closure parameter.
=> NSDictionary, NSIndexSet: Fix withoutAcutallyEscaping usage

TestFoundation/TestNSDictionary.swift
It looks like the order in which things are getting printed was flipped. So we are getting this error in the swift build:
20:53:48 TestFoundation/TestNSDictionary.swift:49: error: TestNSDictionary.test_description : XCTAssertEqual failed: ("{
20:53:48     foo = bar;
20:53:48     baz = qux;
20:53:48 }") is not equal to ("{
20:53:48     baz = qux;
20:53:48     foo = bar;
20:53:48 }") -
I would just fix this, but I don't work often in this codebase so I think
disabling is the right way to go.
https://bugs.swift.org/browse/SR-7166
=> Disable test to unblock swift PR testing.

TestFoundation/TestNSCache.swift, TestFoundation/TestNSDictionary.swift
Hash values are now randomly seeded, and the hash algorithm may change between any two releases of the standard library — code should not depend on specific hash values or Set/Dictionary orderings.
=> Fix and reenable tests that depend on specific hash values

Foundation/NSString.swift, TestFoundation/TestNSString.swift
Needs coordination with apple/swift#14390, which introduces the `String` versions.
=> Remove hasPrefix/Suffix as they are now on String for Linux 

Foundation/Calendar.swift, Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- Fix Calendar.customMirror() to match behaviour on Darwin native
Foundation (10.13.3) for firstWeekDay.
- Update NSCalendar._symbol() to cast the CFDateFormatterCopyProperty()
to a NSString not a CFString to fix NSCalendar.{amSymbol,pmSymbol}.
This also allows un-XFAILing test_currentCalendarRRstability() which
was failing on Linux because of this cast, not a refcounting issue
as mentioned in SR-320.
=> Calendar fixes.

Foundation/NumberFormatter.swift, TestFoundation/TestNumberFormatter.swift
- Set groupingSize default to 0.
- When setting numberStyle to .decimal, set minimumIntegerDigits to 1
and groupingSize to 3 unless they are not zero.
- Fixup tests to match macOS native Foundation.
- Tested against 10.13.3
=> [DarwinCompatibility] NumberFormatter fixes

Foundation/Calendar.swift, Foundation/Data.swift, Foundation/HTTPCookieStorage.swift, Foundation/JSONEncoder.swift, Foundation/NSStringAPI.swift, Foundation/URLComponents.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestJSONSerialization.swift, TestFoundation/TestNSArray.swift
Ref: https://github.com/apple/swift/pull/15230
=> [gardening] Prefer macOS over OSX for `#available`

Foundation/NSString.swift, Foundation/String.swift, Foundation/XMLParser.swift
String._fromCodeUnits is about to disappear; use already existing
String.init calls instead.
=> [string] Wean off of non-String-API.

Foundation/LengthFormatter.swift, TestFoundation/TestLengthFormatter.swift
- Fix symbol used for inches to match Darwin.
- Un-XFAIL test case for SR-3391.
=> LengthFormatter fixes

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- Use a common subfunction to read directory contents in
contentsOfDirectory(atPath:) and subpathsOfDirectory(atPath:).
- Use readdir_r() instead of readdir().
- Call fileSystemRepresentation(withPath:) on the requested directory
to match behaviour on Darwin.
- Replace the test case of a bad directory using "" with "/..." which
now fails the precondition (to match Darwin).
=> FileManager fixes

Foundation/Process.swift, TestFoundation/TestProcess.swift
=> Added URL API to Foundation.Process

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- FileManager.fileSystemRepresentation returns a heap allocated
pointer that needs to be freed by the caller.
=> SR-6449: FileManager.removeItem(atPath) leaks

Foundation/NSString.swift
String's _core disappeared, but we kept around a mock-up of it as a
faux-SPI to avoid breaking Foundation. However, it does not fully
model String, and the illusion is broken from small string support.
=> [string] Wean off of no-longer-supported String non-API

build.py
- This path is shown when 'ninja test' is run.
- The LD_LIBRARY_PATH passed to TestFoundation via manual testing is
inherited by xdgTestHelper. If the path is relative and the
current directory has been changed then libraries will not be
found. This is the case if compiled with debug and libFoundation
is linked to libswiftSwiftOnone.
=> Display absolute path for Foundation lib dir during manual testing.

DarwinCompatibilityTests.xcodeproj/project.pbxproj, DarwinCompatibilityTests/DarwinShims.swift, TestFoundation/TestBundle.swift, TestFoundation/TestCodable.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSError.swift, TestFoundation/TestObjCRuntime.swift, TestFoundation/TestProcess.swift, TestFoundation/TestProcessInfo.swift, TestFoundation/TestUserDefaults.swift
- un-XFAIL some Darwin tests that run on 10.13.3
- Process.executableURL only available on 10.13
- Dont deallocate an autoreleasing pointer on Darwin.
- Add TestBundle.testBundleName() to handle 'TestFoundation' v
'DarwinCompatibiltyTests' naming.
=> [DarwinCompatibility] Minor fixes for DarwinCompatibility tests

Foundation/NSPathUtilities.swift, TestFoundation/TestNSKeyedArchiver.swift
Test case:
```
let filePath = NSTemporaryDirectory() + "testdir\(NSUUID().uuidString)"
let result = NSKeyedArchiver.archiveRootObject("Hello", toFile: filePath)
print(result)
```
Expected Result:  `true`
Actual result on Linux: `false`
Actual result on Darwin: `true`
=> Fix for NSKeyedArchiver.archiveRootObject api failure on Linux

lib/script.py
- If building in debug mode, add an RPATH to the build lib dir of
swift so that libFoundation.so can find libswiftSwiftOnone.so,
required when using -Onone.
- See discussion in https://github.com/apple/swift-package-manager/pull/1544
=> SR-7154: Make swiftpm tests work when building with --debug-foundation

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- propertyKeys and options arent fully implemented.
- Only works on Linux and macOS.
=> FileManager: Implement mountedVolumeURLs(includingResourceValuesForKeys:options:)

Foundation/Boxing.swift, Foundation/Data.swift, Foundation/IndexSet.swift, Foundation/NSStringAPI.swift, Foundation/NSSwiftRuntime.swift
Reverts apple/swift-corelibs-foundation#1497 as it [caused problems](https://ci.swift.org/job/oss-swift-4.2-incremental-RA-linux-ubuntu-16_04/516/) for Linux builds with swift-4.2-branch, where new attributes are not yet available.
corelibs-foundation code should be compatible with both swift-4.2-branch and master branches of the main Swift repo.
=> Revert "[SE-0193] Rename the attributes to their final names"

CoreFoundation/Locale.subproj/CFLocale.c, Foundation/NSLocale.swift, TestFoundation/TestNSLocale.swift
- Fixed NSString/Swift.String Bridging in Locale 
- Added support for Preferred Languages in Linux
- Added tests for Locale static properties and methods
=> Fixed NSString/Swift.String Bridging in Locale 

Foundation/NSData.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestNSData.swift
`NSData (contentsOf :)` was always initialized with length 0.
Also, Testing `NSData (contentsOf :)` on a test HTTP server(`_HTTPServer`) will cause deadlock, so I changed it to work on sub thread.
=> Fix nsdata fails to access contents of url

Foundation/JSONEncoder.swift
An idiom used in JSONEncoder is violating Swift's rules about exclusive
access to memory. The 'with(pushedKey:)' family of mutating functions
on EncodingContainers modify 'self' by pushing a key, executing a
passed-in closure, and popping the key. However, when the passed-in closure
refers to 'self' this violates the rules for exclusive access since the
closure reads self while with(pushedKey:) has an already in-progress
modification of 'self'.
return self.with(pushedKey: _JSONKey(index: self.count - 1)) {
// Referring to 'self.codingPath' violates rules for exclusive access.
...
}
The compiler is warning about this. To address these warnings, change
the callback to with(pushKey:) to accept an additional parameter: the
modified encoding container. This enables the closure to safely refer …
=> Address exclusivity warnings in JSONEncoder

TestFoundation/TestNSData.swift
Fix an exclusivity warning in TestNSData by moving assertions outside
outside of a withUnsafeMutableByte() closure. This mirrors the approach
taken by https://github.com/apple/swift-corelibs-foundation/pull/1337
to avoid the analogous warning in a similar test in this file.
=> [Tests] Fix exclusivity warning in TestNSData

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- When copying directories dont recurse into copyItems() just iterate
through the results of subpathsOfDirectory().
- Copy the contents of the symlink not the file that it points to,
creating a new symlink.
Found during testing of https://github.com/apple/swift-corelibs-foundation/pull/1510
=> FileManager: Fix copyItem(atPath:toPath:) for directories and symlinks.

TestFoundation/HTTPServer.swift, TestFoundation/TestXMLDocument.swift
- Serve the DTD from the built in HTTPServer so the tests
will work without internet access.
- Resolves rdar://31567922.
=> TestXMLDocument: Un-XFAIL DTD tests.

Foundation/FileManager.swift
- Enumerate a directory directly instead of using
subpathsOfDirectory(atPath:) and creating an array.
- When copying a regular file, use a buffer sized to st_blksize instead
of doing a whole file read/write.
=> FileManager: Reduce memory usage of copyItem(atPath:toPath:)

Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
URLComponents expects relative string to either begin with "/" or to be an empty string.
=> SR-7196: Fix for Redirects crash in HTTPURLProtocol

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- Requires some more tests, especially for comparing directories.
=> FileManager: Implement contentsEqual(atPath:andPath:)

TestFoundation/TestDate.swift, TestFoundation/TestTimer.swift
Similar to #1516 but in cases where simply removing the `XCTAssertNotNil` would not bring any benefit or even harm the test suite.
=> Replace XCTAssertNotNil with enhanced tests on TestDate and TestTimer

Foundation/NSIndexSet.swift, TestFoundation/TestIndexSet.swift
Current version not even use an input parameter
Just comparing self with itself
=> Fix IndexSet.contains(integersIn indexSet:)

Foundation/Boxing.swift, Foundation/Data.swift, Foundation/IndexSet.swift, Foundation/NSStringAPI.swift, Foundation/NSSwiftRuntime.swift
- @_inlineable => @inlinable
- @_versioned => @usableFromInline
- @inlinable @usableFromInline => @inlinable
=> Update for SE-0193

configure, lib/target.py
This commit just changes the default to require gold. The user can still override from the command line if they choose to.
The reason why I am making this change is to match Swift's behavior here. There
really isn't any good reason to have separate linkers compiling separate parts
of the same build.
rdar://39456714
-----
In terms of review, my main interest is in am I missing anything in terms of integrating this fix into your build system.
=> Require gold on linux and freebsd by default.

Foundation/NumberFormatter.swift, TestFoundation/TestNumberFormatter.swift
- For the numberStyle .currency, use a minimumIntegerDigits of 1.
- If minimumIntegerDigits is set to any value (including 0) before
the numberStyle is set, preserve the original value.
=> SR-7481: NumberFormatter inconsistency on Linux

Foundation/NSPathUtilities.swift
Details of the bug: https://bugs.swift.org/browse/SR-7526.
Tested on Linux 16.04 under Debug configuration.
=> Fix bug of "/" crashing `NSPathUtilities.resolvingSymlinksInPath`

CoreFoundation/String.subproj/CFBurstTrie.c
CFNumber is a public header in the CoreFoundation framework.  Reference
it as `<CoreFoundation/CFNumber.h>` rather than `"CFNumber.h"`.
=> CoreFoundation: reference CFNumber by the canonical name

Foundation/NSArray.swift, Foundation/NSOrderedSet.swift, Foundation/NSRange.swift, TestFoundation/TestNSData.swift
- Replace NSRange.toCountableRange() with Range.init?(_:)
- Update Test cases.
=> CountableRange is deprecated, renamed to Range

TestFoundation/TestNumberFormatter.swift
- Cause could be ICU issues.
This looks to be causing the build to fail here https://ci.swift.org/job/oss-swift-package-linux-ubuntu-14_04/1594/console
=> NumberFormatter: Disable test for currencyPlural that breaks on Ubuntu 14.04

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- Recurse into any directories found in the source.
- Copy any symlinks that are found. Only regular files are hard linked.
=> FileManager: Fix linkItem(atPath:toPath) for directories and symlinks

CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Foundation/XMLDocument.swift, TestFoundation/TestXMLDocument.swift
- Converting the options to an Int32 caused an overflow, so make
_CFXMLDocPtrFromDataWithOptions() take the options as an
unsigned int instead.
=> SR-7570: Initializing XMLDocument crashes on Linux with nodePreserveAll

TestFoundation/TestNSData.swift
This ensures that:
- We produce a well scoped stable pointer for the duration of the use.
- We aren't attempting to do an implicit conversion from an array to
pointer in an argument position which is an autoclosure result,
which is now disallowed in
https://github.com/apple/swift/pull/16623.
=> Use withUnsafeMutableBufferPointer in NSData test.

TestFoundation/TestNSData.swift
This ensures that:
- We produce a well scoped stable pointer for the duration of the use.
- We aren't attempting to do an implicit conversion from an array to
pointer in an argument position which is an autoclosure result,
which is now disallowed in
https://github.com/apple/swift/pull/16623.
(cherry picked from commit b1a9c732066ab61ff241ef0033deee9b08292e48)
=> [4.2] Use withUnsafeMutableBufferPointer in NSData test.

DarwinCompatibilityTests.xcodeproj/project.pbxproj
- The imports for unit tests were centralised in TestImports.swift,
update the DarwinCompatibilityTests Xcode project to import this
file.
- This was a result of the change in https://github.com/apple/swift-corelibs-foundation/pull/1528
=> DarwinCompatibilityTests: Fix the test imports

Foundation/URL.swift
The documentation for `deleteLastPathComponent()` and `deletePathExtension()` both currently say "Returns a URL".
This commit brings the documentation of these two methods into line with other `mutating func`s in `URL`.
=> Documentation: Fix description for mutating funcs in URL

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
- For integerAddition, propogate the carry if set.
- For integerSubtraction, compute the borrow and set .underflow
on error.
- When initialising a Decimal() from an Int or UInt dont convert via
a double.
=> SR-7650: Incorrect result adding and subtracting Decimals

Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestURLRequest.swift
A lot of fields not copied
It works very bad when `Content-Length` set but `httpBody` loosed after COW
=> Fix URLRequest copying

Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- Fix init(mantissa:exponent:isNegative:) to set the mantissa
correctly.
=> NSDecimalNumber: Add missing init(value:) initialisers.

CoreFoundation/Base.subproj/CFRuntime.h, CoreFoundation/String.subproj/CFString.h
Resolve a bug that affects ARMv7 system
https://bugs.swift.org/browse/SR-6812
=> https://bugs.swift.org/browse/SR-6812

DarwinCompatibilityTests.xcodeproj/project.pbxproj, Foundation.xcodeproj/project.pbxproj, TestFoundation/TestBundle.swift, TestFoundation/xdgTestHelper/main.swift, build.py, lib/phases.py
- For Linux, set the output executable from the swiftc to go into
the TestFoundation application directory.
- For DarwinCompatibiltyTests, build xdgTestHelper as a command
line tool then add a build phase to copy it to the 'Executables'
destination.
- For TestFoundation.app, build xdgTestHelper as a cocoa .app so
that Xcode doesnt statically link it to the Foundation from the
Swift toolchain, then copy the binary.
This is a followup to https://github.com/apple/swift-corelibs-foundation/pull/1562 which made `xdgTestHelper` into a standalone single `.swift` file.
=> Add xdgTestHelper into the TestFoundation bundle as an auxiliaryExecutable

CoreFoundation/PlugIn.subproj/CFBundle_Executable.c, TestFoundation/TestBundle.swift
Fixes https://bugs.swift.org/browse/SR-3077
We were doing nothing with the executable path here unless the platform was Darwin or Windows. Use the PLATFORM_PATH_STYLE macro here instead to ensure all platforms execute this.
=> [SR-3077] Bundle.main.executableURL returns incorrect values on Linux

CoreFoundation/Locale.subproj/CFCalendar.c, CoreFoundation/Locale.subproj/CFLocale.c, CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/build.py, lib/script.py
Expand Linux platforms supported under DEPLOYMENT_RUNTIME_SWIFT=0 umbrella.
=> Build Foundation with DEPLOYMENT_RUNTIME_SWIFT disabled

Foundation/NSString.swift, TestFoundation/TestNSString.swift
There were some cases which were being evaluated to `true` but on Darwin/Objective-C they evaluate to `false`.
=> Fix NSString.boolValue not matching Darwin Foundation

Foundation.xcodeproj/project.pbxproj, Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme
- Add an xdgTestHelper scheme so that it is built correctly as
a dependancy of TestFoundation.
- When copying the xdgTestHelper binary use a cp relative to
the $BUILD_ROOT
=> XdgTestHelper: Build and copy correctly into TestFoundation.app on Xcode

Foundation/URLSession/http/HTTPURLProtocol.swift
Codepaths in `HTTPURLProtocol` missed to assign the port for the new redirect request which leads to the failure in redirection.
=> [SR-7861] Fix for HTTP redirect failure on Linux

Foundation/Bridging.swift, Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSError.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSSet.swift
The new primitives are only available if Objective-C isn't. Guard them with `#canImport(ObjectiveC)`.
(Additionally, see below for discussion.)
Resolves [SR-7865](https://bugs.swift.org/browse/SR-7865).
=> [SR-7865] swift-corelibs-foundation does not compile on macOS after 'as' bridging was merged

Foundation/Bridging.swift, Foundation/NSArray.swift, Foundation/NSDictionary.swift, Foundation/NSError.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSSet.swift
Cherry picked from commit c91c99d565c604b12efd6eaeaa095565942e8149; this patch cherry-picks build fixes for Foundation on the 4.2 branch. Discussion is available at https://github.com/apple/swift-corelibs-foundation/pull/1579.
=> [4.2][SR-7865] swift-corelibs-foundation does not compile on macOS after 'as' bridging was merged

CoreFoundation/String.subproj/CFCharacterSet.c, TestFoundation/TestCharacterSet.swift
_CFCharacterSetInitWithCharactersInString crashed on strings with surrogate characters. Now _CFCharacterSetInitWithCharactersInString is semantically equivalent to CFCharacterSetInitWithCharactersInString from core foundation.
=> Fixed SR-5971

TestFoundation/TestCodable.swift
There were 16 failing tests on Darwin (more specifically on Decodable).
This PR removes the #if statements that were checking for linux only.
=> make tests on darwin run the same way as linux

Foundation/NSString.swift
Fixed the code accessing outside the range of the character string.
When running the test in Xcode, Guard Malloc (libgmalloc) detected it and caused a runtime error.
=> SR-7112: Fixed access to memory out of range

Foundation/ISO8601DateFormatter.swift, TestFoundation/TestISO8601DateFormatter.swift
This fixes [SR-7079](https://bugs.swift.org/browse/SR-7079).
=> Add support for .withFractionalSeconds to ISO8601DateFormatter. 

TestFoundation/TestIndexSet.swift
This PR namely adds tests to `NSMutableIndexSet.removeAllIndexes()` and `NSMutableIndexSet.remove(indexSet:)`.
=> Add more tests to NSMutableIndexSet's removal APIs

Foundation/FileManager.swift, Foundation/NSURL.swift
replace structures like:
``` swift
for i in 0..<len {
buf.advanced(by: i).initialize(to: 0)
}
```
with:
``` swift
buf.initialize(repeating: 0, count: len)
```
should bring small performance improvements
=> replace for-loop based initialization

Foundation.xcodeproj/project.pbxproj, Foundation/FileManager.swift, Foundation/FileManager_XDG.swift, Foundation/NSPathUtilities.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift, build.py, lib/phases.py
Implement urls(for:…) as the primitive directory method:
- In Darwin, match paths with the Objective-C implementation wherever possible.
- On platforms that use FHS/XDG, implement reading user-dirs.* files to determine XDG directories;
This patch also enables the `@testable import` syntax in TestFoundation in the Debug configuration.
=> Implement FileManager.url{s,}(for:…) and NSSearchPathForDirectoriesInDomains.

Foundation/URLSession/Configuration.swift, Foundation/URLSession/URLSessionConfiguration.swift, TestFoundation/TestURLSession.swift
Have the property name match Darwin
=> [SR-6396] URLSessionConfiguration, renamed discretionary to isDiscretionary

Foundation/NSString.swift
Looks like once this is merged https://github.com/apple/swift/blob/526632c4aa04bf83f507b45d690827dfeeb363f0/stdlib/public/core/StringGuts.swift#L1314-L1320 can be removed.
=> Remove deprecated `String._core` usages

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
- For integerAddition, propogate the carry if set.
- For integerSubtraction, compute the borrow and set .underflow
on error.
- When initialising a Decimal() from an Int or UInt dont convert via
a double.
Backport to 4.2 of https://github.com/apple/swift-corelibs-foundation/pull/1550
=> [4.2] SR-7650: Incorrect result adding and subtracting Decimals

Foundation.xcodeproj/project.pbxproj, Foundation/FileManager.swift, Foundation/FileManager_XDG.swift, Foundation/NSPathUtilities.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift, build.py, lib/phases.py, lib/script.py
This re-proposes the patch at #1456 — see there for discussion.
Unlike that patch, this one changes the test setup and build so that `NS_FOUNDATION_ALLOWS_TESTABLE_IMPORT` is defined iif the build product can be used in a `@testable import` expression, and conditionalizes white-box tests to the presence of that flag. That flag is never available if `DEPLOYMENT_RUNTIME_OBJC`, since macOS's Foundation will never be usable with `@testable import`.
=> [Attempt 2] Implement FileManager.url{s,}(for:…) and NSSearchPathForDirectoriesInDomains.

Foundation/Data.swift
This synchronizes the latest version of Data from the overlay to swift-corelibs-foundation
=> Synchronize the latest revision of Data.swift from the overlay

Foundation/NSURL.swift, Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionTask.swift
fixes `'let' properties are implicitly 'final'; use 'public' instead of 'open'` warnings
=> Fix open let properties

Foundation/Process.swift, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift
- Implements suspend(), resume(), interrupt() and terminate().
- Add --signal-test to xdgTestHelper for testing signals.
=> Process: Implement signal sending functions.

closure/runtime.c
This adjusts the initialization path to ensure that the lookup for
`_Block_destructInstance` is portable to Windows.
=> closure: port use of dlsym to Windows

Foundation/IndexSet.swift
Removed double loop insert, leveraged swift struct copy. Should achieve performance improvement.
=> Improve the performance of IndexSet.union

CoreFoundation/build.py, build.py
The linker script was unused at this point.  Remove the linker script to
simplify the build.
=> build: remove Linux linker script

Foundation/IndexSet.swift, Foundation/JSONSerialization.swift, Foundation/URLSession/BodySource.swift, Foundation/URLSession/URLSession.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, Foundation/URLSession/libcurl/EasyHandle.swift, TestFoundation/TestJSONEncoder.swift
The codebase _seems_ to not make much use of `.some`/`.none` explicit syntax.
So the main idea of this PR is just to make it more consistent.
=> [gardening] Remove explicit use of .some & .none when dealing with optionals

Foundation/HTTPCookie.swift, Foundation/NSURL.swift, Foundation/NSURLRequest.swift, Foundation/URLSession/Configuration.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/TestBundle.swift, TestFoundation/TestHTTPCookie.swift, TestFoundation/TestHTTPCookieStorage.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestURL.swift, TestFoundation/TestURLRequest.swift, TestFoundation/TestURLSession.swift
HTTPCookie fixes for version 0 cookies
- For expiry date, prefer maximum-age over expires-date but only
use maximum-age for version 1 cookies.
- For version 0 cookies only return the first port number,
if available.
NSURLRequest: Capitalise header names
- Correctly override httpAdditionalHeaders headers with
allHTTPHeaderFields.
NSURL fix checkResourceIsReachable()
- If URL is a file, throw error with code .fileReadUnsupportedScheme
instead of .fileNoSuchFile to match Darwin.
Disable tests that wont work on native Foundation
=> Fix more tests to run correctly on Darwin's native Foundation

Docs/Status.md, Foundation/URLSession/URLSessionTask.swift
This is an attempt at resolving the implementation for `URLSessionDownloadTask.cancel(byProducingResumeData:)`.
This function seems to represent an edge case in portability. After communicating with @phausler, it appears the Objective-C implementation of this relies on an Apple-maintained XPC process to manage the bookmarking of partially downloaded data. Of course, this behavior is not portable to the framework project.
One approach that was considered was serializing the `URLSessionDownloadTask` instance and returning _that_ to the caller as the opaque blob given to the completion handler. However, the Objective-C implementation of `URLSessionTask` does not implement any `NSCoding` flavor publicly, so conformance would need to be implemented in this framework with `internal` or greater …
=> Add URLSessionDownloadTask.cancel(byProducingResumeData:)

Foundation/HTTPCookie.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestHTTPCookie.swift, TestFoundation/TestURLSession.swift
- Disable test_cancelTask() as this seems to be the failing
task causing the others to fail, re-enable test_taskTimeout().
- Ensure the HTTP server is ready before starting a test function
that uses it.
This is a followup to #1599 . Its not a complete fix as `test_cancelTask()` still shows up issues and needs to be fixed. 
Tested ok on Ubuntu 18.04
=> TestURLSession: Fixes for Ubuntu18.04

DarwinCompatibilityTests.xcodeproj/project.pbxproj, Foundation.xcodeproj/project.pbxproj, Foundation/URLProtectionSpace.swift, TestFoundation/TestURLProtectionSpace.swift, TestFoundation/main.swift
Hi, first-time contributor here—_hoping this PR is useful_. It was actually harder to implement than I was expecting.
=> [SR-7938] Add URLProtectionSpace.description

CoreFoundation/NumberDate.subproj/CFTimeZone.c, TestFoundation/TestTimeZone.swift
- TimeZone.knownTimeZoneIdentifiers was returning time zone names
that could not be instantiated by TimeZone(identifier:) due to
CFTimeZone.c:__nameStringOK() filtering out some names.
- Make CFTimeZoneCopyKnownNames(), used by .knownTimeZoneIdentifiers,
also filter these names using __nameStringOK().
- __nameStringOK calls ICU function ucal_getCanonicalTimeZoneID
which ultimately decides if the time zone is valid.
https://bugs.swift.org/browse/SR-8078
=> SR-8078: Some time zone identifiers are not supported by TimeZone on Linux

Foundation/NSIndexPath.swift, TestFoundation/TestIndexPath.swift
- init(indexes:length:): Fix method signatue and allow nil pointer
with 0 length to match Darwin.
- Implement copy(with:)
- Mark getIndex(_:range:) as unavailable (deprecated in Darwin).
=> NSIndexPath: Make compatible with Darwin.

closure/Block_private.h
The Blocks ABI v1 used `unsigned long int` for the `size` and `reserved`
fields.  On LLP64 targets (e.g. Windows x86_64), `uintptr_t` is larger
than `unsigned long int`.  Adjust the types to make the definition
conform to the ABI specification.
=> closure: make `Block_descriptor_1` conform to the ABI

TestFoundation/TestNSError.swift
=> NSError: add a test for bridging an NSDictionary containing an NSError to a Dictionary containing an Error.

Foundation/NSString.swift
=> [4.2] Remove deprecated `String._core` usages

Foundation/JSONEncoder.swift, Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
This PR removes the undocumented internal serialization option `useReferenceNumericTypes` and aligns behavior with Darwin Foundation. (Note: there remains a divergence between platforms when it comes to 128-bit integers.)
The parsing logic is simplified and tests are expanded to ensure that `"[10]"` is deserialized to a value that can be cast to `Int` or `Double`.
=> [JSONSerialization] Always use reference numeric types to match Darwin behavior

Foundation/JSONEncoder.swift, Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
Cherry picking #1634, as requested.
=> [4.2][JSONSerialization] Always use reference types to match Darwin behavior

build.py
This allows libdispatch to build BlocksRuntime shared.
=> build: link against shared BlocksRuntime

Foundation/URLAuthenticationChallenge.swift, Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
This PR is based on  #1407 . I have picked up the implementation from #1407  PR and added HTTPServer changes which are required for testing this functionality.
@pushkarnk please review
=> HTTP Basic Auth implementation

Foundation/HTTPCookie.swift, Foundation/HTTPCookieStorage.swift, TestFoundation/TestHTTPCookieStorage.swift
Fix an issue when HTTPCookie domain starts with ".", cookies are
not being sent with HTTP requests. Also, force domain matching to
be in all lower case.
=> Ensure HTTPCookie domain matching conforms to RFC6265

Foundation/Scanner.swift, TestFoundation/TestNSString.swift
- Dont require a digit before a leading decimal separator.
- Support exponent specified by 'e' and 'E'.
=> SR-1674: NSString.doubleValue doesn't support a few formats supported by Darwin

Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
- If the new location includes a host but no port number, then DONT add
the port number.
=> When redirecting with a relative Location, add the port number to the new url

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSNumberBridging.swift
- NSNumber as? Bool should only work for NSNumber values 0 and 1 to
match Darwin.
=> [4.2] SR-8407: NSNumber as? Bool should only work for 0 or 1

lib/pkg_config.py
This makes Foundation build on platforms where the `python` executable is Python 3.
=> Fix configure script Python 3 compatibility

Foundation/NSLocale.swift, TestFoundation/TestNSLocale.swift
`NSLocale` inherits hash from `NSObject`, but overrides `isEqual(_:)` to compare contents. The default hash uses object identity, so two `NSLocale` instances that compare equal under `isEqual(_:)` can produce non-equal hash values. This also breaks hashing for `Locale`, which calls into `NSLocale.hash`.
Add an implementation for `NSLocale.hash` that matches `isEqual(_:)`.
Resolves https://bugs.swift.org/browse/SR-8448
=> NSLocale.hash: Implement

build.py
This commit fixes a header-not-found build error when Foundation is
built with --install-prefix other than "/usr".
=> Fix Foundation build error with --install-prefix

Foundation.xcodeproj/project.pbxproj, Foundation/NSCalendar.swift, Foundation/NSURL.swift, Foundation/NSURLRequest.swift, TestFoundation/TestCalendar.swift, TestFoundation/TestDateComponents.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestURL.swift, TestFoundation/TestURLRequest.swift, TestFoundation/Utilities.swift, TestFoundation/main.swift, build.py
This PR collects fixes previously submitted separately as #1645, #1646 and #1648, fixing the implementation of hashing for the following Foundation types:
- `DateComponents`
- `NSDateComponents`
- `URLRequest`
- `NSURLRequest`
- `URLComponents`
- `NSURLComponents`
Note that this isn't a full audit of Foundation hashing -- this was the bare minimum necessary for #1649. I suspect there may be more types with issues similar to these.
Resolves:
- https://bugs.swift.org/browse/SR-8441
- https://bugs.swift.org/browse/SR-8449
- https://bugs.swift.org/browse/SR-8450
=> DateComponents, URLRequest, URLComponents: Fix hashing

Foundation/DateComponents.swift
Typo fix. Changed `356` to `365`.
=> Fix doc typo on `yearForWeekOfYear` case in `DateComponents`

Foundation/XMLNode.swift, TestFoundation/TestXMLDocument.swift
- When returning an XMLNode, take a reference to the parent
XMLDocument to prevent the underlying libxml xml document
from being freed.
- This prevents the document being freed if a reference is still
held to a XMLNode but not the XMLDocument.
=> SR-8560: XMLDocument on Linux crashes with a Segmentation Fault

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Collections.subproj/CFStorage.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h
By replacing `namspace` with `name_space` and changing the `restrict` into `__restrict__` in C++ mode, the headers can now be parsed by clang++ as well as clang.
=> Allow header files to be parsed by C++ parsers

Foundation/FileManager.swift
- Filemanager should not use attributesOfItem(atPath:) internally
when only the file type of the path is required, to avoid
unnecessary getpwuid() and getgrgid() calls.
=> SR-8519: Linux standardizingPath syscall performance

Foundation/NSData.swift, TestFoundation/TestNSData.swift
- CFHash() doesnt see objects of type NSMutableData as CF objects
so calls back to NSObject.hash which causes infinite recursion.
- Directly call _CFNonObjCHash() to bypass this check.
=> SR-936: NSMutableData.hash() causes a segmentation fault on Linux

Foundation/Operation.swift, TestFoundation/TestOperationQueue.swift
Reverts apple/swift-corelibs-foundation#1665
Let's get this done on the master branch first, and target it at the next major release instead of the next dot release for 4.2.
=> Revert "SR-8572: Rework OperationQueue.isSuspended to stop suspending underly…"

Foundation/Codable.swift, Foundation/HTTPCookieStorage.swift, Foundation/JSONEncoder.swift, Foundation/NSError.swift, Foundation/NSLocale.swift, Foundation/NSPathUtilities.swift, Foundation/Operation.swift, Foundation/URLCredentialStorage.swift, Foundation/URLSession/BodySource.swift, Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/libcurl/EasyHandle.swift, Foundation/Unit.swift
This patch aims at making corelibs-foundation adapted to [this PR](https://github.com/apple/swift/pull/18623),  which warns for redundant access-level modifiers.
@phausler Hi Philippe, would you help take a look at this, please?
=> Fix redundant access-level modifiers.

build.py
Rather than relying on the system having a copy of the blocks runtime headers,
use the headers from our local copy.
=> build: use the block headers from internal copy

CoreFoundation/Base.subproj/ForFoundationOnly.h, TestFoundation/TestNSNumber.swift
In 32 bits platforms, for some doubles the hash result could be
incorrectly zero (or whatever undefined behaviour happens to be).
The problem happens when the non fractional part of the double is high
and the fractional part is between 0 and 0.5 and high enough to make the
sum of both not fit into 32 bits. In that case, the use of += promotes
result to double to add it to the fractional double, but when it gets
converted back into CFHashCode, since it is outside the 32 bit range, it
might end up as zero.
Casting fractional to CFHashCode avoids the hidden promotion, and should
not fail, since fractional is at most ULONG_MAX/2.
The problem doesn't exist in 64 bits, since CFHashCode is 64 bits wide
there.
=> Fix UB when hashing some doubles in 32bits.

CoreFoundation/NumberDate.subproj/CFTimeZone.c
I'm not 100% sure this is the correct fix, but the `__nameStringOK` static function gets used even if `DEPLOYMENT_RUNTIME_SWIFT` is unset, so this just breaks the build (linkage) if this block of code gets excluded. It also just doesn't seem very Swift-specific, to my uneducated eye.
cc @DougGregor or anyone willing to suggest a better fix
=> Fix unnecessary (and broken) preprocessor exclusion

CoreFoundation/build.py
The SwiftRuntime header has a big warning in it saying not to use it unless you're building with the swift runtime, which this build.py doesn't do.
cc @millenomi 
Also, as a related aside: does this CoreFoundation/build.py get exercised by @swift-ci? I couldn't find any information on how to affect its behavior but I'd love to add a skeleton build to avoid it getting broken in future
=> Fix CoreFoundation.h header in standalone CF build

Foundation/NSString.swift, TestFoundation/TestNSString.swift
- Also implement .caseInsensitive option.
Current implementation was buggy and would crash for some strings.
Tests now match Darwin
=> SR-5829: Fix NSString.commonPrefix(with:options:)

Foundation/NSString.swift, TestFoundation/TestNSString.swift
- "\r\n" is treated as a single character, but so are "\r" and "\n"
so use rangeOfComposedCharacterSequence(at:) to find the range of the
decomposed character.
=> SR-8689: Fix crash with NSMutableString.replaceOccurrences(of:with:options:)

CMakeLists.txt, CoreFoundation/CMakeLists.txt, CoreFoundation/cmake/modules/CoreFoundationAddFramework.cmake, Docs/GettingStarted.md, cmake/modules/FindUUID.cmake, cmake/modules/SwiftSupport.cmake
Add a CMake based build system for CoreFoundation.  This helps moves to
a single unified build for swift and the corelibs.  It also makes it
easier to cross-compile.
=> build: add CMake build system

Foundation/Unit.swift, TestFoundation/TestUnit.swift, TestFoundation/main.swift
The encoding method and the decoding method used slightly different
keys. The incorrect key made Dimension (and the subtypes) impossible to
decode (and with Swift Foundation a crash since decoding cannot fail).
Includes a test to check for correctly encoding/decoding cycle.
=> Fix Dimension.encode(with:) to use same key as init(coder:).

CoreFoundation/Base.subproj/CFAsmMacros.h
The old one would actually trigger GNUisms on macOS in some circumstances.
Credit to @yorickdowne as seen in this comment:
https://github.com/apple/swift-corelibs-foundation/commit/dcc7db1fa3167c6dca1fef18dd38b820952faa49#commitcomment-30473459
=> Improve CFAsmMacros platform checking

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Tried to best match the suggested implementation from the [Swift Forum](https://forums.swift.org/t/swiftfoundation-filemanager-isdeletablefile-implementation/13465/7).
I wasn't exactly sure how to write tests for these methods. My tests attempt to check that the result of `isReadableFile`, `isWritableFile`, `isExecutableFile` match the value one would receive by directly checking the file's permission bits.
=> isDeletableFile Implementation + Tests

CoreFoundation/Base.subproj/CoreFoundation.h, CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
I think this might have been an artifact of the old CFLite redactions? Either way, these headers are now available in this repository. The real CoreFoundation guards these includes with `#ifndef CF_OPEN_SOURCE` but that doesn't seem relevant here. There are also other includes guarded
by that which are not (yet? 😆) available in this repository, so I did not include them here.
cc @millenomi @parkera it's hard for me as an outsider to know the "right" thing to do around `CF_OPEN_SOURCE` avoidance. I see a little bit of it still in this repo, but it's hard for me to know if that's appropriate here (in order to be more similar to the official CF) or if it's just going to be unconditionally available from now on. Any advice if I encounter more stuff like this?
Edit: I'm also unclear on how I …
=> Add back unnecessarily redacted headers that now exist

CoreFoundation/Base.subproj/CFRuntime.c
Without this, you get some really fun to debug segfaults at runtime because (among other things I assume) `CFRunLoopGetCurrent` queries TSD to avoid doing the heavier `_CFRunLoopGet0` (which then sets the TSD to avoid later work). But if we don't initialize the TSD machinery, the `_CFGetTSD` function returns garbage and we never get a valid `CFRunLoopRef`.
cc @parkera @millenomi 
For context, I have the standalone framework working just fine for most things, but was getting some really weird runtime crashes whenever someone used a `CFRunLoop` 😄
=> Initialize TSD on macOS even without Swift runtime

Foundation/Decimal.swift
This PR applies [a minor edit](https://github.com/apple/swift/pull/18486/commits/89b26a7f653e3fca1830dd33909ac71ba024cd0c) to swift-corelibs-foundation to synchronize with the overlay. No functional change is intended.
Although it ought to be purely cosmetic, the original motivation for the change was that the Swift compiler that day on the master branch refused to accept `UInt64(abs(value))`. Therefore, since there's a cleaner way to express the operation anyway, I made minor edits mostly for the sake of allowing compilation to proceed. Now, these changes are made here for the sake of synchrony.
No new tests are required.
=> [Decimal] Make a minor edit to synchronize with overlay

Foundation/NSURLRequest.swift, TestFoundation/TestNSURLRequest.swift, TestFoundation/TestURLRequest.swift
Cherry pick from https://github.com/apple/swift-corelibs-foundation/pull/1554
This fixes [SR-8759](https://bugs.swift.org/browse/SR-8759).
=> Fix SR-8759

Foundation/HTTPCookie.swift, Foundation/URLSession/Configuration.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, Foundation/URLSession/libcurl/EasyHandle.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestHTTPCookie.swift, TestFoundation/TestURLSession.swift
- Add support for additional Set-Cookie formats that web servers can return
- Properly handle HTTP header parsing to extract values since values can contain colons
- Make sure to set cookies on redirect requests
- Use setValue instead of addValue when applying cookies to requests otherwise,
Cookie header might contain: cookie1=value1,cookie1=value1; cookie2=value2
- New unit tests for cookie formats and redirect with Set-Cookie
=> Various Cookie fixes

Foundation/Array.swift, Foundation/Bridging.swift, Foundation/Bundle.swift, Foundation/Data.swift, Foundation/Dictionary.swift, Foundation/HTTPCookieStorage.swift, Foundation/JSONEncoder.swift, Foundation/JSONSerialization.swift, Foundation/NSArray.swift, Foundation/NSAttributedString.swift, Foundation/NSCFArray.swift, Foundation/NSCFDictionary.swift, Foundation/NSCFSet.swift, Foundation/NSDictionary.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSLocale.swift, Foundation/NSNotification.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, Foundation/Notification.swift, Foundation/NotificationQueue.swift, Foundation/NumberFormatter.swift, Foundation/PropertyListSerialization.swift, Foundation/Set.swift, Foundation/UserDefaults.swift
Swift is renaming some classes that are visible to Objective-C to avoid conflicts between older versions and ABI-stable versions. Change those names here as well.
This goes with this Swift PR: https://github.com/apple/swift/pull/19295
rdar://problem/35768222
=> Rename various ObjC-visible classes

Foundation/UserDefaults.swift
Remove the duplicate value check `value is Float` in method `UserDefaults._isValueAllowed` .
=> Remove duplicate value check in UserDefaults

Foundation/Data.swift, Foundation/NSRange.swift
…'SignedInteger'
Remove the redundant conformance constraints on `Data[RangeExpression]`
and `NSRange.init<RangeExpression>(_:)`, silencing the compiler warning.
=> SR-8915: Remove redundant conformance constraints

Foundation/NSDictionary.swift, TestFoundation/TestNSDictionary.swift
In [NSDictionary](https://developer.apple.com/documentation/foundation/nsdictionary) the `value(forKey)` method is currently unsupported. 
This PR aims to implement part of this method based on the following [documentation](https://developer.apple.com/documentation/foundation/nsdictionary/1410210-value). That is the non-KVC path which calls out to the already implemented `object(forKey)` method. 
I've added a unit test for the new method which tests that `value(forKey)` does return the value we expect. I've also added a test for nested dictionaries. 
The KVC path, where the key has a `@` prefix, has been left unsupported.
=> Implement part of the value(forKey) method

TestFoundation/TestNSError.swift, TestFoundation/TestNSString.swift
A couple build break fixes for 10.14 + Xcode 10. Doesn't get Darwin completely building at master, but really helps clear out the noise. 
- NSString(_:) is internal, use NSString(string:) instead. Probably a better test as well.
- Clean up the cast for NSError.
=> Fix a Couple Darwin Build Breaks on Xcode 10

Foundation/FileHandle.swift, TestFoundation/TestFileHandle.swift, TestFoundation/TestPipe.swift
- Pipe does not have a failable or throwable initializer but currently
calls fatalError() for all errors returned from pipe().
- If pipe() returns EMFILE or ENFILE then set the fileDescriptor
to -1 for both .fileHandleForReading and .fileHandleForWriting.
For all other errors call fatalError().
- TestFileHandle.swift: Remove duplicate test_pipe().
- TestPipe.swift: Add extra test to try and exhaust the process's pipes.
- Test the file descriptor is valid and open for certain methods
and properties to match Darwin.
=> SR-7608: Pipe() crashes when the underlying system call fails.

Foundation/NSCalendar.swift
Removed code seems to be a wrong copy-paste inside each function.
=> [gardening] Remove duplicate code in NSCalendar

Foundation/FileManager.swift, Foundation/NSData.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSString.swift, TestFoundation/TestBundle.swift, TestFoundation/TestCodable.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestJSONSerialization.swift, TestFoundation/TestNSArray.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSDictionary.swift, TestFoundation/TestProcess.swift, TestFoundation/TestStream.swift, TestFoundation/TestUtils.swift, Tools/plutil/main.swift
- Remove wildcard pattern matching
- Refactor catches with empty body
- Prefer using try? to ignore errors instead of empty catch body
- Prefer not assigning a variable name
=> [gardening] Clean up do catch blocks

Foundation.xcodeproj/project.pbxproj, Foundation/FileManager.swift, Foundation/FileManager_XDG.swift, Foundation/NSPathUtilities.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift, build.py, lib/phases.py, lib/script.py
This re-reproposes the patch at #1597 that was reverted by #1598. It should fix the issues from the previous two attempts. (Whoops.)
=> [Attempt 3] Implement FileManager.url{s,}(for:…) and NSSearchPathForDirectoriesInDomains.

CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/DateFormatter.swift, TestFoundation/TestCalendar.swift, TestFoundation/TestDateFormatter.swift, TestFoundation/TestTimeZone.swift
Because of the use of 'timeZone' instead of 'newValue' in the setter, setting the timeZone of a DateFormatter doesn't actually work. Instead, it winds up re-setting the old value, which happens to be whatever was originally set, usually what we get from copying the default down in CoreFoundation.
A good fix here is to avoid any ambiguity with the property name in the setter and getter.
Also adds a unit test to help prevent breaks like this again.
=> Fix DateFormatter TimeZone Setter

CoreFoundation/Locale.subproj/CFCalendar.c, TestFoundation/TestCalendar.swift
Currently, initializing a calendar with `.persian` identifier results in  segmentation fault error on linux.
This PR aims to remedy that.
=> Fixed persian calendar segmentation fault

CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/DateFormatter.swift, TestFoundation/TestCalendar.swift, TestFoundation/TestDateFormatter.swift, TestFoundation/TestTimeZone.swift
Reverts apple/swift-corelibs-foundation#1704
Test test_expectedTimeZone is failing in CI.
=> Revert "Fix DateFormatter TimeZone Setter"

Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
- Use .description property of numbers to encode as String
instead of using CFNumberFormatter for Float/Double,
and serialising integers explictly.
=> SR-7195: JSONSerialization encodes Double differently on Darwin and Linux

CoreFoundation/Base.subproj/CFFileUtilities.c
On some old systems readdir does not fill correct filetypes. Tasks like loading CFBundle will fail on these systems since _CFIterateDirectory relies on readdir. Adding a second check with stat when readdir returns unknown filetype.
=> Fix _CFIterateDirectory behavior on some old file systems

CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/DateFormatter.swift, TestFoundation/TestCalendar.swift, TestFoundation/TestDateFormatter.swift, TestFoundation/TestTimeZone.swift
This is a fix for PR #1704, which was reverted by #1721 due to a break in the test I added in the original PR. 
This includes rebased versions of the commit history of #1704, plus a new commit that disables Case 1 of the test which was failing in the case of GMT, because DateFormatter was spitting out UTC as the abbreviation. I've opened https://bugs.swift.org/browse/SR-8994 to track the issue of TimeZone's abbreviation and DateFormatter not agreeing on GMT vs UTC.
=> Reapply "Fix DateFormatter TimeZone Setter"

lib/target.py
This enables build support for 32-bit Linux, specifically tested on Debian Stretch, which uses 'i686' as the architecture triple.
=> Add Support for i686 Targets

Foundation/NSGeometry.swift, TestFoundation/TestAffineTransform.swift, TestFoundation/TestNSGeometry.swift
- replaces *Make constructors with swift initializers
- replaces NSZeroPoint/Size/Rect with .zero
=> Update legacy constructors, functions, and constants

CoreFoundation/Base.subproj/CFRuntime.h, CoreFoundation/String.subproj/CFString.h
The original fix being reverted was #1557 made _cfinfoa 32-bit, which is generally correct, but it was really attempting to fix the same issue that #1525 had fixed. Historically, _cfinfoa has been 64-bit on Linux dating back to at least Swift 3.
In the short term, because forward fixing the issues with #1557 uncover other lurking 32-bit alignment issues on Linux, it is safer to revert #1557. But because it did make for some cleaner ifdefs on the Darwin side as well, the Darwin pieces are being left alone. Going forward, it will take some investigation to uncover the reasons behind the other 32-bit alongment issues.
Original context around this problem and previous attempted fixes/reverts:
#1689 
#1693 
This does not attempt to fix PPC Big-Endian Issues also present here, brought up in …
=> Revert Attempted Fix of SR6812

Foundation/NSOrderedSet.swift
Consolidates several index checks into object(at:) and adds a few index
checks where it makes sense.
=> Consolidates index checking in NSOrderedSet

CMakeLists.txt
When setting up CoreFoundation for the Foundation build, we need to
strip out any preset DESTDIR to ensure that the installation is not
redirected to the install location for the Foundation build.
=> build: strip DESTDIR when performing subinstall

Foundation/UUID.swift
This updates UUID to use `withUnsafePointer` for `let`s
Now that SE-0205 has landed, we don't need to make local copies of the uuid byte tuples, in order to get pointers to them. We can use the new `withUnsafePointer` that works with `let`s.
This matches apple/swift#19775
=> Update UUID to take advantage of SE-0205

CoreFoundation/CMakeLists.txt, CoreFoundation/RunLoop.subproj/CFRunLoop.c, CoreFoundation/String.subproj/CFBurstTrie.c
I noticed these things when trying to build CoreFoundation with the CMake based system.
=> CoreFoundation build clean ups

build.py
Use the proper output location from CMake for linking.  This will allow us to
clean up the staging from the libdispatch build system.
=> build: do not consult the legacy staging location for libdispatch

Foundation/NSOrderedSet.swift, TestFoundation/TestNSOrderedSet.swift
Also adds documentation comments for the method.
=> Refactors NSOrderedSet.objects(at:) to use map(_:)

Foundation/Scanner.swift
On Darwin public methods with out parameters not produce "result call unused" warning
So using @discardableResult here is behave more like Darwin Foundation
=> Add @discardableResult to Scanner

cmake/modules/SwiftSupport.cmake
Ensure that the dependencies are wired up to the build commands.  We
would previously not track them correctly.
=> build: correctly handle dependencies

Foundation/FileHandle.swift, Foundation/NSData.swift, TestFoundation/TestNSData.swift
- Modify FileHandle._readDataOfLength(untilEOF:options:) to ignore
stat.st_size and just use the result of read() to determine whether
to keep reading.
- Also convert syscall error handling to throw instead of calling
fatalError().
- NSData.readBytesFromFileWithExtendedAttributes(options:) now uses
FileHandle._readDataOfLength(untilEOF:options:) to read from a file
rather than duplicating the file reading logic.
- (Linux) Add a test to read a file in /sys which reports
stat.st_size > size of the file's contents.
=> SR-8999: NSData contentsOf expects st_size to be the size of the file.

Foundation/FileManager.swift
- Added `FileManager.delegate` functionality
- Updated `FileManagerDelegate` default implementation method signature to match protocol methods.
- Fixed TODO: Implemented cross-device move in `moveItem()`
- Fixed TODO: Error handling if fts_read fails in `removeItem()`
=> Implemented FileManager.delegate and cross-device move

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/CMakeLists.txt, CoreFoundation/String.subproj/CFString.h, build.py
This gets the swift-corelibs-foundation implementation closer to the Darwin implementation by making the compiler lay out constant CFStrings produced by CFSTR(). It requires a [corresponding clang patch](https://github.com/apple/swift-clang/pull/213) to work.
This is only enabled for not-`TARGET_OS_MAC` for now, since the clang used to build Swift here is not the same as the one used by Xcode when using a Swift toolchain. When Xcode gets the new clang, we can enable this for `TARGET_OS_MAC` as well.
rdar://42898576
=> Add support for compiler-managed CFSTR() on non-Darwin systems

CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/CoreFoundation_Prefix.h, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/CMakeLists.txt, CoreFoundation/Stream.subproj/CFStreamPriv.h, build.py
Symbols using `CF_PRIVATE` are meant to be available outside the compilation unit where they're declared, but not outside Core Foundation. Headers that use `CF_PRIVATE` thus mean to declare, not define, these symbols. Match Darwin by adding `extern` to the `CF_PRIVATE` definition, and then add `-fno-common` to also match how Darwin compiles and detect double symbol definitions.
This fixes Linux crashes in CFString encoding introduced by the Mojave merge.
=> Fix linkage for Linux and BSD symbol declarations that use `CF_PRIVATE`

Foundation/FileManager.swift
On iOS / macOS this API comes from Objective-C which is implicitly
@discardableResult, this means it doesn't warn on those platforms, but
previously did on Linux
=> Mark FileManager.createFile as @discardableResult

CMakeLists.txt, CoreFoundation/Base.subproj/module.map, CoreFoundation/Base.subproj/module.modulemap, CoreFoundation/CMakeLists.txt, Tools/plutil/main.swift, cmake/modules/FindICU.cmake
These set of changes are needed to build with the CMake system.
=> CMake based build

CMakeLists.txt
CMake 3.4.3 does not support the <files>... <directory> pattern for
copy_if_different.  Adjust for that.
=> build: repair the build on 14.04

cmake/modules/SwiftSupport.cmake
CMake 3.4.3 does not support the copy files... <directory> pattern.  Add
compatibility for it.
=> build: compatibility for CMake 3.4.3

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/Base.subproj/CoreFoundation_Prefix.h, CoreFoundation/Collections.subproj/CFBasicHash.c, CoreFoundation/Collections.subproj/CFData.c, CoreFoundation/Parsing.subproj/CFPropertyList_Private.h, CoreFoundation/RunLoop.subproj/CFMachPort_Lifetime.c
`#import` when building for Windows will be treated as the import of a
type library rather than the semantics of Objective-C style `#import`
which does an include once type of operation.  Convert to the `#include`
syntax instead to allow this to be built on Windows as well (e.g. via
clang-cl).
=> CoreFoundation: use #include instead of #import

Foundation/JSONSerialization.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestJSONSerialization.swift
- Check the number looks like a JSON number and exit early if not.
- Use the native Int64(), UInt64(), Double() parsers to avoid creating
a C string and passing to strtol()/strtod(). This also eliminates a
memcpy() and removes the 63 digit restriction which would fail to
parse numbers expressible by Double's full exponent.
- For numbers with a leading '-' sign, parse using Int64() falling
back to Double(), otherwise parse using UInt64() failling back to
Double().
=> JSONSerialization: Improve parsing of numbers

CMakeLists.txt, CoreFoundation/CMakeLists.txt, CoreFoundation/cmake/modules/FindICU.cmake
Reverts apple/swift-corelibs-foundation#1746
=> Revert "[cmake] Find ICU in CoreFoundation."

cmake/modules/FindICU.cmake
=> [cmake] Fix capitalization in find_path argument.

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
Fix for https://forums.swift.org/t/severe-decimal-error-in-foundation-on-linux-needs-workaround/14359/6
=> Decimal: Fix .doubleValue to use _length to only index valid mantissa elements.

Foundation/Unit.swift
Possible resolution of blocking adoption of `-swift-version 5`:
https://github.com/apple/swift/pull/20374
=> Mark subclasses of Dimension final.

CoreFoundation/Locale.subproj/CFNumberFormatter.c, Foundation/NumberFormatter.swift
- When using NumberFormatter with .nostyle (UNUM_PATTERN_DECIMAL) the
default pattern '#;#' omits the '-' symbol when formatting negative
numbers using ICU versions 62 or later.
- Use a default pattern of '#' which lets ICU automatically set the
format for negative numbers. This pattern is the default used by
ICU62.
- Tested on Ubuntu14.04 with ICU 52 and Ubuntu18.04 with ICU 63.1.
=> NumberFormatter: Fix the pattern default .nostyle pattern for ICU62+

Foundation/URLSession/Message.swift
Needed to build Foundation with Swift 5.
=> Remove deprecated (now an error) conversion to Range.

Foundation/Date.swift, Foundation/NSRange.swift, Foundation/URL.swift
Also remove conformances to deprecated CustomPlaygroundQuickLookable.
Needed for migration to Swift 5.
=> Conform URL, NSRange, and Date to CustomPlaygroundDisplayConvertible.

Foundation/Unit.swift
Swift 5 treats this as an error, since the subclasses are final.
=> Change ‘open’ to ‘public’ for overrides of baseUnit()

Foundation/Unit.swift
Needed to build with Swift 5 mode.
=> isEqual needs to be declared public in final classes.

CMakeLists.txt
`libFoundation.so` does not have `$ORIGIN` in its `RUNPATH` so it cant find the ICU libraries installed in `usr/lib/swift/linux`
With this PR the path now looks like : 
```
$ readelf -aW ~/swift-install/usr/lib/swift/linux/libFoundation.so |grep RUNPATH
0x000000000000001d (RUNPATH)            Library runpath: [/home/spse/swift-source/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:/home/spse/swift-source/build/buildbot_linux/libdispatch-linux-x86_64/src:$ORIGIN]
```
=> SR-9251: Add $ORIGIN into libFoundation.so RUNPATH

Foundation/IndexSet.swift, Foundation/NSCFString.swift
Under Swift 5 mode we currently get the following error:
```
IndexSet.swift:154:18: error: type referenced from a '@usableFromInline' property must be '@usableFromInline' or public
01:12:50     internal var _handle: _MutablePairHandle<NSIndexSet, NSMutableIndexSet>
```
This change is technically ABI impacting for corelibs-Foundation.
=> Mark _MutablePairHandle and _MutablePair as @usableFromInline

Foundation/NSNumber.swift
Needed to build in Swift 5.  This enforces an invariant using a
runtime check.
=> Use forced ‘cast’ in NSNumber convenience initalizer.

Foundation/NSNumber.swift
This enforces requirement of Self return value; addresses an error in Swift 5 mode.
=> Change another convenience initializer to use a runtime cast.

TestFoundation/TestURL.swift
When 'try?' has an optional sub-expression, it no longer produces a nested optional.
=> Adjust for 'try?' changes in Swift 5

Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, TestFoundation/TestNSSet.swift
Improve performance by exiting early if self is larger than the potential containing set, since a larger set cannot be contained by a smaller set.
=> Improved performance of isSubset for NSOrderedSet and NSSet

CoreFoundation/CMakeLists.txt, CoreFoundation/cmake/modules/CoreFoundationAddFramework.cmake
Setup the build for targeting Windows.  This cleans up the configuration
by unifying the behaviour for FreeBSD and other non-Darwin unices.
=> build: clean up build and enable Windows

CoreFoundation/CMakeLists.txt
Fix the variable name in CMake to correctly identify the compiler.
=> build: fix variable name

CMakeLists.txt
- Currently libFoundation.so exists in 2 places in the distribution
tarfile:
./usr/lib/swift/linux/x86_64/libFoundation.so
./usr/lib/swift/linux/libFoundation.so
- ld.so will load the first one located in x86_64 subdirectory which
will then set $ORIGIN to this directory. Consequently, the libICU
shared libraries required by libFoundation.so will not be found.
- Update CMakeLists.txt to not install libFoundation.so in the x86_64
directory.
- Also remove an unneeded RUNPATH pointing to the build directory for
libdispatch. This is already reached using LD_LIBRARY_PATH during
testing.
=> Remove extra installed copy of libFoundation.so

CMakeLists.txt
Removing libdispatch build directory from the RUNPATH was causing `lang/swift/foundation/TestSwiftFoundation.py ` in lldb tests to fail.
=> SR-9193: Add libdispatch back into the RUNPATH to allow the lldb tests to run.

Foundation/NSStringAPI.swift
In the `NSStringAPI.swift` there was still a reference to the old `rangeOfString()` method. This method was renamed to `range(to:)` so I fixed the documentation otherwise it can create some confusion 🙂
I did the same fix here https://github.com/apple/swift/pull/20860
=> Change `rangeOfString(other)` to `range(of: other)` in the docs

Foundation/Progress.swift, Foundation/Thread.swift, Foundation/XMLParser.swift
This PR changes type of `Thread.threadDictionary` to `NSMutableDictionary` from `Dictionary<String, Any>`.
The reasons are below.
1. Because apple's implementation for macOS/iOS is so.
A current implementation is hard to write code which can be shared between Linux and iOS.
I need to do for my project which has server side and client app.
2. `Key` which has `String` type is hard to avoid conflict among some independent modules.
Though I can do by giving prefix like domain, 
but this needs more runtime access cost to test equality of key in dictionary.
With `NSMutableDictionary`, I can use `ObjectIdentifier` or `UnsafeRawPointer` of static key object.
It is more safe from unexpected key conflict and cheap to test equality.
In original source, comment what about a implementation differs …
=> Change threadDictionary to NSMutableDictionary

CoreFoundation/String.subproj/CFString.c, Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSString.swift
- Use Swift's stringification of numbers for .description and .stringValue
- Use String(format:locale:...) with the correct format for the
NSNumber type if locale is not nil.
- Enable use of __CFStringFormatLocalizedNumber() on
DEPLOYMENT_TARGET_LINUX.
=> SR-1464: NSNumber.description is not compatible between OS X and linux

CoreFoundation/Base.subproj/CFPlatform.c
We were calling pthread_key_create more than PTHREAD_KEYS_MAX times
(1024 on the version of Linux I tested with). It should only need to be
called once.
Fixes https://bugs.swift.org/browse/SR-9241
=> Only call pthread_key_create once in __CFTSDInitialize

Docs/GettingStarted.md
Ubuntu 16.04 was dropped back in swift/55d907fbee29 (Drop support for Ubuntu 16.10, 2018-09-05)
=> Docs: update the list of supported Linux distributions

Foundation/NSNumber.swift, TestFoundation/TestNSNumberBridging.swift
See PR #1703 for the original details around the fix.
Work for 4.2 originally regressed this behavior from 4.1 and earlier, so this really should be fixed in 4.2 for Linux as well as the original commit to master.
=> Cherry Pick Conditional Bridge Behavior for Swift 4.2 Branch

Foundation/URLSession/URLSession.swift
Replace using:
```swift
`self`
```
which is relying on a [compiler bug](https://github.com/apple/swift-evolution/blob/master/proposals/0079-upgrade-self-from-weak-to-strong.md#relying-on-a-compiler-bug) with `strongSelf`.
Unwrapping `self` by using `strongSelf` is already used in [other places](https://github.com/search?q=org%3Aapple+strongSelf&type=Code) so this will make the code consistent across the projects.
=> Use strongSelf instead of `self`

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Locale.subproj/CFCalendar_Internal.h, CoreFoundation/Stream.subproj/CFStream.c
Splinter off more of the Windows port with feedback addressed from @parkera
=> Windows Port Continuation

CoreFoundation/String.subproj/CFRegularExpression.c, CoreFoundation/String.subproj/CFRegularExpression.h, Foundation/NSRegularExpression.swift
The Swift function
`NSRegularExpression.enumerateMatches(in:options:range:using:)` receives
a `NSRegularExpression.MatchingOptions`, but the `using:` block receives
a `NSRegularExpression.MatchingFlags`. At one point in the code of
CoreFoundation, the results of a call the obtained `Flags` were shoved
into an `Options` variable, instead of a `Flags` one. This error was
perpetuated in the function points signature in the header, which Swift
imported, forcing Swift to do a conversion between
`_CFRegularExpressionMatchingOptions` into
`NSRegularExpression.MatchingFlags` using the raw value.
=> Fix mixup with _CFRegularExpressionMatchingOptions and Flags.

Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
The triggering JSON:
```json
[
"\uDFF3"
]
```
I've also added some tests. However, I couldn't run them, because the test suite crashes on this line:
https://github.com/apple/swift-corelibs-foundation/blob/b5d216e2ef7299faed12f404654f1f514eb8138a/TestFoundation/HTTPServer.swift#L581
And I have no idea why, but pretty sure my fix has nothing to do with it.
(In fact, in order to build TestFoundation, I needed to dance around a bit, because the `xdgTestHelper` target requires Swift 3 compatibility mode, which is not supported in the latest development snaphsot that I've been using.)
=> JSONSerialization: fix a crash when an escape sequence contains low-surrogate code point without the corresponding high-surrogate code point

CoreFoundation/Base.subproj/CFRuntime.c
_cfinfoa field of CFRuntimeBase is an _Atomic(uint64_t), but for some
reason it was being accessed from a uint32_t pointer (which I think
violates strict aliasing rules). This was working for little endian
architectures, but would have failed for big endian architectures when
writing the value back into the MSB instead of the LSB.
The fix uses the right size (64 bits) and removes the castings where
possible. However, to avoid the _Atomic to be honored, the field is
still casted to an uint64_t, which might hide future errors (like the
situation this is trying to fix).
=> [CoreFoundation] Fix incorrect cast in _CFRuntimeCreateInstance.

Foundation/NSString.swift, TestFoundation/TestNSString.swift
The second branch of NSString.substring(with:) creates a buffer where
the contents of the substring are copied. However, instead of returning
the contents of the buffer, the result was the pointer value of the
UnsafeMutablePointer. This commit changes to use
String(utf16CodeUnits:count:) to return the contents.
=> Fix NSString.substring returning an address.

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFOverflow.h, CoreFoundation/Base.subproj/CFPriv.h, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/CFRuntime.h, CoreFoundation/Base.subproj/CFSortFunctions.c, CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/Base.subproj/SwiftRuntime/TargetConditionals.h, CoreFoundation/Collections.subproj/CFBasicHash.c, CoreFoundation/Collections.subproj/CFData.c, CoreFoundation/Locale.subproj/CFNumberFormatter.c, CoreFoundation/NumberDate.subproj/CFBigNumber.c, CoreFoundation/NumberDate.subproj/CFBigNumber.h, CoreFoundation/NumberDate.subproj/CFNumber.c, CoreFoundation/Parsing.subproj/CFBinaryPList.c, CoreFoundation/Parsing.subproj/CFOldStylePList.c, CoreFoundation/PlugIn.subproj/CFBundle.h, CoreFoundation/PlugIn.subproj/CFBundle_Binary.c, CoreFoundation/PlugIn.subproj/CFBundle_Executable.c, CoreFoundation/PlugIn.subproj/CFBundle_Grok.c, CoreFoundation/RunLoop.subproj/CFMessagePort.c, CoreFoundation/String.subproj/CFString.c, CoreFoundation/String.subproj/CFString.h, CoreFoundation/StringEncodings.subproj/CFUniChar.c
Adjust the various sites that consider LP64 to also consider LLP64
environments.  This is needed to support Windows x86_64.  Normalize the checks
across the code base to use `TARGET_RT_64_BIT` which is defined in
TargetConditionals.h.
=> CoreFoundation: handle LLP64 as LP64

Foundation/NSNull.swift, TestFoundation/TestNSNull.swift, TestFoundation/main.swift
Fixes SR-9503.
NSNull has `<null>` as description on Darwin.
It had `<NSNull: 0x00000000075ce1c0>` elsewhere.
Overridden description method to match Darwin's behaviour.
I've also noticed that `testCase(TestNSNull.allTests)` was listed twice in `TestFoundation/main` and removed extra entry.
=> [SR-9503] Match NSNull's description to Darwin's

Foundation/NSSwiftRuntime.swift
__NSCFType has been using Int32 for _cfinfo. More recently in Swift 4, it’s been noticed that this can cause problems on 32-bit ARM and should be aligned with _CFInfo instead.
Currently, there are no known issues on 32-bit ARM because of this. However, it'd be nice to fix this before some future change breaks because _cfinfo is an Int32.
=> Align __NSCFType with CFRuntimeBase / _CFInfo

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Locale.subproj/CFDateFormatter.c, CoreFoundation/PlugIn.subproj/CFBundle.c, CoreFoundation/PlugIn.subproj/CFBundle_Internal.h, CoreFoundation/PlugIn.subproj/CFBundle_Main.c, CoreFoundation/PlugIn.subproj/CFBundle_Tables.c, CoreFoundation/RunLoop.subproj/CFRunLoop.c
Introduce the `_CFMutex` and `_CFRecursiveMutex` types to allow us to
differentiate between recursive and non-recursive mutexes and be able to replace
them on different platforms.  This codepath does not use `CFLock_t` as these are
expected to be full mutexes rather than unfair locks.
=> CoreFoundation: introduce `_CFMutex`, `_CFRecursiveMutex`

CMakeLists.txt, Foundation/UUID.swift, TestFoundation/TestUUID.swift, TestFoundation/main.swift
Report for NSUUID: https://bugs.swift.org/browse/SR-865
=> UUID.uuidString should return an upper String like on Darwin

CMakeLists.txt, uuid/uuid.c
Setup the build to build the bundled UUID and port to windows in preparation for supporting Windows as a build target.
=> Use bundled UUID

CMakeLists.txt
Update the flags handling to enable building for the Windows target which does not support `-rpath` and requires an indication that the shared C library is being used.
=> Improve flags handling for Windows build

Foundation.xcodeproj/project.pbxproj
This addresses the warning of "Skipping duplicate build file in Copy Headers build phase: /Users/ikesyo/swift-source/swift-corelibs-foundation/CoreFoundation/Locale.subproj/CFDateFormatter.h (in target 'CoreFoundation')".
=> [Xcode] Remove duplicated CFDateFormatter entries

Foundation/NSPathUtilities.swift, Foundation/NSSet.swift, Foundation/Operation.swift, Foundation/ProcessInfo.swift, Foundation/URLProtocol.swift, Foundation/URLSession/http/HTTPMessage.swift, Foundation/URLSession/libcurl/MultiHandle.swift, Foundation/XMLNode.swift
Update use of `index(of:)` to `firstIndex(of:)` and `index(where:)` to
`firstIndex(where:)`.  NFCI.
=> Foundation: update for API change

Foundation/FileManager.swift, Foundation/NSCFString.swift, Foundation/NSCalendar.swift, Foundation/NSString.swift, Foundation/URLSession/libcurl/EasyHandle.swift, Foundation/URLSession/libcurl/MultiHandle.swift
LLP64 causes the `Int` type to be different on LLP64 hosts and LP64 as
Swift does not have `intptr_t`.  This prepares for some of those changes
by using `numericCast` to hide the type checks.
=> Foundation: use `numericCast` in places for LLP64

CMakeLists.txt, CoreFoundation/Collections.subproj/CFData.c, Foundation.xcodeproj/project.pbxproj, Foundation/Collections+DataProtocol.swift, Foundation/ContiguousBytes.swift, Foundation/Data.swift, Foundation/DataProtocol.swift, Foundation/DispatchData+DataProtocol.swift, Foundation/NSData+DataProtocol.swift, Foundation/NSData.swift, Foundation/Pointers+DataProtocol.swift, Foundation/URLSession/BodySource.swift, TestFoundation/TestNSData.swift, TestFoundation/TestURL.swift
This brings in the new 2-word implementation of Data which adds numerous performance improvements that reduce the overhead of using Data. Particularly certain optimized scenarios will instead of using heap allocations for Data it now uses a stack switching implementation (similar to the smol String implementation). Additionally this brings in a new protocol called DataProtocol which unifies Data like types to be usable in a generic fashion. This codifies a concept of contiguous byte storage so that types such as DispatchData which represent a collection of contiguous regions can share a similar interface to those with full contiguous storage like Data or Array<UInt8> etc.
=> Import Data and DataProtocol from the overlay (and correct some incorrect CFData and NSData usages)

Foundation/XMLParser.swift
Remove a reference to a SR and a comment that no longer apply and the SR has
been closed as WONTFIX/NOTABUG.
=> Foundation: remove an out of date comment (NFC)

Foundation/AffineTransform.swift, Foundation/Data.swift, Foundation/DataProtocol.swift, Foundation/FileHandle.swift, Foundation/FileManager.swift, Foundation/FoundationErrors.swift, Foundation/Host.swift, Foundation/JSONSerialization.swift, Foundation/NSConcreteValue.swift, Foundation/NSData.swift, Foundation/NSDate.swift, Foundation/NSGeometry.swift, Foundation/NSLock.swift, Foundation/NSPathUtilities.swift, Foundation/NSPlatform.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSURL.swift, Foundation/NSUUID.swift, Foundation/Process.swift, Foundation/ProcessInfo.swift, Foundation/Progress.swift, Foundation/Thread.swift, Foundation/XMLParser.swift
This is preliminary setup for enabling the Windows port.  Ensure that we
import MSVCRT in all the locations where we are importing the C library.
Take the opportunity to homogenise the import for linux/android/cygwin
as well.
=> Foundation: homogenise importing C, add MSVCRT

Foundation/NSString.swift
Use the `UnsafePointer<Int8>` constructor rather than the
`unsafeBitCast`.  NFCI.
=> Foundation: replace `unsafeBitCast` (NFC)

Foundation/NSRange.swift
Remove the duplicated conformance specification which causes a warning
to be emitted.
=> Foundation: remove duplicated conformance (NFC)

Foundation/NSLock.swift
This is the NSLock specific bits of the Windows port.  It is dependent on a previous change (#1842), but, this at least splits up the change into a digestible change.
=> port NSLock to Windows

Foundation/NSStringAPI.swift, TestFoundation/TestNSString.swift
Fixes [SR-9454](https://bugs.swift.org/browse/SR-9454)
=> SR-9454: StringProtocol.lineRange(for:) returns invalid range on Linux

Foundation/FileHandle.swift, Foundation/NotificationQueue.swift, Foundation/Port.swift, Foundation/Process.swift, Foundation/RunLoop.swift, Foundation/Stream.swift, TestFoundation/TestNotificationQueue.swift, TestFoundation/TestRunLoop.swift, TestFoundation/TestTimer.swift
Cherry-picks #1836 into swift-5.0-branch.
=> [5.0] Convert RunLoopMode to RunLoop.Mode as with Darwin Foundation

CMakeLists.txt, CoreFoundation/Collections.subproj/CFData.c, Foundation.xcodeproj/project.pbxproj, Foundation/Collections+DataProtocol.swift, Foundation/ContiguousBytes.swift, Foundation/Data.swift, Foundation/DataProtocol.swift, Foundation/DispatchData+DataProtocol.swift, Foundation/NSData+DataProtocol.swift, Foundation/NSData.swift, Foundation/Pointers+DataProtocol.swift, Foundation/URLSession/BodySource.swift, TestFoundation/TestNSData.swift, TestFoundation/TestURL.swift
This releases [this PR](https://github.com/apple/swift-corelibs-foundation/pull/1834) to Swift 5.0 (cherry picked from commit 4a255655c298450416d388a58c2b50f4057c3346).
=> [5.0] Import Data and DataProtocol from the overlay (and correct some incorrect CFData and NSData usages)

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
- NSNumber.description: Second kCFNumberFloatType should have been
kCFNumberFloat32Type in case statement.
- Remove extra kCFNumberCGFloatType as it is handled seperately.
=> SR-9685: Accessing NSNumber(value: 1.2 as Float).description crashes

Foundation/Host.swift
This ports the NSHost functionality to Windows.
=> Foundation: port NSHost to Windows

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
- NSNumber.description: Second kCFNumberFloatType should have been
kCFNumberFloat32Type in case statement.
- Remove extra kCFNumberCGFloatType as it is handled seperately.
- Temporarily disable some extra tested caused by SR-9699 issue
=> [5.0] SR-9685: Accessing NSNumber(value: 1.2 as Float).description crashes

Foundation/NSStringAPI.swift, TestFoundation/TestNSString.swift
Cherry-picks #1841 into `swift-5.0-branch`.
=> [5.0] SR-9454: StringProtocol.lineRange(for:) returns invalid range on Linux

Foundation/JSONSerialization.swift
The JSON serialiser wrote the JSON data via an intermediate `Array<CChar>`. This was unnecessary as we can access the bytes from the underlying UTF8 view via `withCString()` and avoid an allocation and copy.
=> JSONSerialization: avoid intermediate buffer copy

Foundation/FileHandle.swift, Foundation/NSSwiftRuntime.swift
This ports the FileHandle interfaces to Windows.
=> Foundation: port FileHandle to Windows

Foundation/NSStringAPI.swift
Over time, `NSStringAPI.swift` has diverged from the overlay.  Bring it back in sync.
Most of these changes are whitespace, but there are important functional changes included, like the port of https://github.com/apple/swift/commit/a088e1322495316203c95b40fc4b3e984ca5c82c which adds fastpaths for `Data` -> `String` conversions.
The diff with whitespace removed is +79 −46. You can hide whitespace changes on GitHub using the "Diff settings" dropdown in the Files changed tab.
=> NSString: sync with overlay

Foundation/AffineTransform.swift, Foundation/NSCache.swift, Foundation/NSCalendar.swift, Foundation/NSError.swift, Foundation/NSObject.swift
This is cherry picked from @ikesyo's PR #1820 (commit 9ee6b02367a79b742566b575e7b9c7da36a19651).
This PR fixes an NSObject API inconsistency between Swift 5's SDK overlays on Darwin and swift-corelibs-foundation. It also fixes several NSObject subclasses to customize hashing through the correct API, `NSObject.hash`.
`NSObject.hashValue` is currently declared `open`, which matches Darwin SDK overlays in Swift 4.2 and below. Unfortunately, `hashValue` was never supposed to be overridden -- `NSObject` subclasses are expected to customize hashing by overriding `NSObject.hash`, which is a distinct property. To help clear up the confusion resulting from this subtle gotcha, last year we decided to change `NSObject.hashValue` to be non-overridable.
- The Swift 4.2 compiler started emitting …
=> Make NSObject.hashValue non-overridable

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSLock.swift, Foundation/Thread.swift
Implement the Thread interfaces for Windows.  Extend the CoreFoundation
interface to support thread stack reservation sizing.
=> Foundation: port NSThread to Windows

Foundation/JSONSerialization.swift
Cherry-pick of #1862 to `swift-5.0-branch`.
=> [5.0] JSONSerialization: avoid intermediate buffer copy

Foundation/CGFloat.swift, Foundation/FoundationErrors.swift, Foundation/NSDate.swift, Foundation/NSPathUtilities.swift, Foundation/NSPlatform.swift, Foundation/NSSwiftRuntime.swift, Foundation/NSURL.swift, Foundation/Stream.swift, Foundation/URLSession/Configuration.swift, Foundation/URLSession/libcurl/EasyHandle.swift, Foundation/URLSession/libcurl/MultiHandle.swift
Adjust the source for LLP64 (Windows x64/AArch64) and account for
non-POSIX environment.  Collect them into a single change as they are
small enough to not be a problem to really inspect in a single batch.
=> Foundation: sundry fixes for Windows port

Foundation/XMLParser.swift, TestFoundation/TestXMLParser.swift
As [the Apple's document says](https://developer.apple.com/documentation/foundation/xmlparser/1411778-parse), `parse()` should return false in there is an error or if the parsing operation is aborted.
Resolves [SR-9758](https://bugs.swift.org/browse/SR-9758).
=> SR-9758: `XMLParser.parse()` should return `false` if `abortParsing()` is called.

Foundation/AffineTransform.swift, Foundation/NSCache.swift, Foundation/NSCalendar.swift, Foundation/NSError.swift, Foundation/NSObject.swift
This is @ikesyo's change that previously landed on master in #1850.
Original description:
This PR fixes an NSObject API inconsistency between Swift 5's SDK overlays on Darwin and swift-corelibs-foundation. It also fixes several NSObject subclasses to customize hashing through the correct API, `NSObject.hash`.
`NSObject.hashValue` is currently declared `open`, which matches Darwin SDK overlays in Swift 4.2 and below. Unfortunately, `hashValue` was never supposed to be overridden -- `NSObject` subclasses are expected to customize hashing by overriding `NSObject.hash`, which is a distinct property. To help clear up the confusion resulting from this subtle gotcha, last year we decided to change `NSObject.hashValue` to be non-overridable.
- The Swift 4.2 compiler started emitting deprecation …
=> [5.0] Make NSObject.hashValue non-overridable

Foundation/FileManager.swift
- Parse /etc/default/useradd to find the default home directory,
falling back to /home.
=> SR-9550: xdgURLs assumes home directory location for .userDirectory

Foundation/NSData.swift
We would attempt to remove the temporary file.  However, that will
result in calls which can destroy the original errno.  Save the previous
errno before performing the cleanup.
=> NSData: fix an errno stomp

Foundation/NSString.swift
A bug in the standard library allowed conversion between different pointees just using the `UnsafePointer.init` but this should not have been allowed. Updating to the correct form in order to permit apple/swift#22288 to land.
=> Switch to using correct form for unsafe type cast

CoreFoundation/Base.subproj/CFBase.h
CoreFoundation built statically for Foundation is used as an objects
library.  We want to re-export the symbols.  This requires that exports
are enabled for the target, but CMake defines _EXPORT symbols only for
shared libraries and `-rdynamic` executables.  Use the custom macro for
the static case for Foundation.
=> CoreFoundation: fix CoreFoundation for Foundation static builds

Foundation/FileHandle.swift
- Add private _checkFileHandle() to validate the file handle to
simplify the validation in the public API calls.
=> FileHandle: Refactor file descriptor precondition checks in API calls

Foundation/FileHandle.swift
Fix capitalisation for OS parameter `@available`.
=> FileHandle: fix OS spelling for `@available`

Foundation/Host.swift, Foundation/NSPlatform.swift, Foundation/Thread.swift
Fix various casting issues.  Fix the dereferencing code in Host to
be more correct.  Clean builds revealed a number of issues, including an
insufficiently complete modulemap.
=> Foundation: fix build on Windows

Foundation/NSPathUtilities.swift
Correct the handling of a temporary string in the temporary path
creation handling on Windows.
=> Foundation: fix unsafe string handling in Win32 path

Foundation/NSString.swift, TestFoundation/TestNSString.swift
- "\r\n" is treated as a single character, but so are "\r" and "\n"
so use rangeOfComposedCharacterSequence(at:) to find the range of the
decomposed character.
- master PR: #1687
=> [4.2] SR-8689: Fix crash with NSMutableString.replaceOccurrences(of:with:options:)

CoreFoundation/Locale.subproj/CFCalendar.c, Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- _CFCalendarGetComponentDifferenceV() doesn't support a component
character of 'l' (leap year) as it make no sense for the difference between two dates.
- Dont add 'l' to the component string or parse the result into the .isLeapMonth property when called
from NSCalendar.components(_:from:to:options)
- _CFCalendarGetComponentDifferenceV: Add validation of datetime
format character and bounds check multiple_table array lookup.
- Allow -1 as a component value.
- Reorder datetime fields from largest to smallest when creating
datetime format and constructing components from response.
- Add tests validated against Darwin's Foundation.
master PR #1658
=> [4.2] SR-7011: Fatal Error when Using Calendar.current.dateComponents(_:from:to:)

CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Foundation/XMLDocument.swift, TestFoundation/TestXMLDocument.swift
- Converting the options to an Int32 caused an overflow, so make
_CFXMLDocPtrFromDataWithOptions() take the options as an
unsigned int instead.
(cherry picked from commit fb6c82ee3eb5ce97e1b96afcee770bc48b2fba8b)
=> [4.2] SR-7570: Initializing XMLDocument crashes on Linux with nodePreserveAll

Foundation/XMLNode.swift, TestFoundation/TestXMLDocument.swift
- When returning an XMLNode, take a reference to the parent
XMLDocument to prevent the underlying libxml xml document
from being freed.
- This prevents the document being freed if a reference is still
held to a XMLNode but not the XMLDocument.
(cherry picked from commit aabed33c1695e1e607a603394f908e9b92554bca)
=> [4.2] SR-8560: XMLDocument on Linux crashes with a Segmentation Fault

Foundation/NSString.swift, TestFoundation/TestNSString.swift
- Also implement .caseInsensitive option.
(cherry picked from commit 944c1093e2473c4d9134adb638f9e8b93bbf3f2c)
(cherry picked from commit 908ffcb94ca517b86d438899129443e9e4fdea1b)
=> [4.2] SR-5829: Fix NSString.commonPrefix(with:options:)

Foundation/JSONEncoder.swift, TestFoundation/TestJSONEncoder.swift
- Implement .convertToSnakeCase key encoding.
=> [5.0] SR-9828: JSONEncoder keyEncodingStrategy does not work on Linux

Foundation/NSIndexPath.swift, TestFoundation/TestIndexPath.swift
- init(indexes:length:): Fix method signatue and allow nil pointer
with 0 length to match Darwin.
- Implement copy(with:)
- Mark getIndex(_:range:) as unavailable (deprecated in Darwin).
(cherry picked from commit c0bac193c3f9abd2c34139acd946bb8fe7fe6581)
=> [4.2] NSIndexPath: Make compatible with Darwin.

Foundation/FileHandle.swift, TestFoundation/TestFileHandle.swift, TestFoundation/TestPipe.swift
- Pipe does not have a failable or throwable initializer but currently
calls fatalError() for all errors returned from pipe().
- If pipe() returns EMFILE or ENFILE then set the fileDescriptor
to -1 for both .fileHandleForReading and .fileHandleForWriting.
For all other errors call fatalError().
- TestFileHandle.swift: Remove duplicate test_pipe().
- TestPipe.swift: Add extra test to try and exhaust the process's pipes.
- Test the file descriptor is valid and open for certain methods
and properties to match Darwin.
(cherry picked from commit 870d4259c9d6a7f33a0eadc0c0c214f53f9c550d)
NSPipe: make fileHandleFor{Reading,Writing} mutable
In Objective-C, the fileHandleFor{Reading,Writing} property is mutable even on a
const instance.  Change the property to read/write.
(cherry picked from …
=> [4.2] SR-7608: Pipe() crashes when the underlying system call fails.

Foundation/FileHandle.swift, Foundation/NSData.swift, TestFoundation/TestNSData.swift
- Modify FileHandle._readDataOfLength(untilEOF:options:) to ignore
stat.st_size and just use the result of read() to determine whether
to keep reading.
- Also convert syscall error handling to throw instead of calling
fatalError().
- NSData.readBytesFromFileWithExtendedAttributes(options:) now uses
FileHandle._readDataOfLength(untilEOF:options:) to read from a file
rather than duplicating the file reading logic.
- (Linux) Add a test to read a file in /sys which reports
stat.st_size > size of the file's contents.
(cherry picked from commit 5733313eef587d400980ba1aeb40134dd8357b0a)
SR-8999: Ensure the FileHandle read methods call fatalError() on error
- readDataToEndOfFile(), readData(ofLength length: Int) and
.availableData should call fataError() if there are IO errors,
not return an …
=>  [4.2] SR-8999: NSData contentsOf expects st_size to be the size of the file.

Foundation/DateFormatter.swift, TestFoundation/TestDateFormatter.swift
- When parsing a date, return nil if the date to be parsed was not
fully consumed by the parse format.
=> SR-9322: DateFormatter difference between macOS and Linux

CoreFoundation/String.subproj/CFString.c
When building Foundation test on s390x, there is a warning:
CoreFoundation/String.subproj/CFString.c:6030:36: warning: result of comparison of constant -1 with expression of type 'char' is always false [-Wtautological-constant-out-of-range-compare]
The debugging shows  `(disableLocalizedFormatting == -1)` is never `true` because `disableLocalizedFormatting` is defined as `char`, and  then the logic of format localized number is not correct on s390x.
Changing `disableLocalizedFormatting` to `short` to make the logic works on all platforms
=> Fix a bug in format localized number on s390x

Foundation/FileHandle.swift, TestFoundation/TestFileHandle.swift
- Accepting truncating to any position, not just 0.
- Reposition to the truncate offset.
- Darwin throws exceptions on error so we use fatalError() instead of silently failing.
(cherry picked from commit fb1e71bbe58329267b799695ff8ea1d307a752d2)
=> [4.2] FileHandle.truncateFile should reposition on truncate

Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- Fix init(mantissa:exponent:isNegative:) to set the mantissa
correctly.
(cherry picked from commit 641e2cb52ee8fc9e75971f7a2cc030c4f1239eac)
=> [4.2] NSDecimalNumber: Add missing init(value:) initialisers.

Foundation.xcodeproj/project.pbxproj, Foundation/FileHandle.swift, Foundation/FoundationErrors.swift, TestFoundation/TestPipe.swift
Adds API to FileHandle that allows clients to catch and handle errors, rather than panic with `fatalError` on I/O issues. This API will be supported going forward and is not experimental.
=> Supported FileHandle API for Swift

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- chmod() failing should throw an error and not call fatalError().
- Behaviour now matches Darwin.
=> FileManager: setAttributes(ofItemAtPath:) should throw if chmod fails.

Foundation/FileHandle.swift, Foundation/FileManager.swift, Foundation/NSData.swift
- Remove makeTemporaryFile(inDirectory:) in favour of using
_NSCreateTemporaryFile(path).
- FileHandle: Add internal _write(buf:length) method to write out memory
buffers.
- FileHandle: Add a throwing _synchronizeFile(), use it in synchronizeFile().
=> NSData: Refactor write(toFile:options) using FileHandle methods.

Foundation/NSURL.swift, Foundation/Stream.swift
These changes will be needed in the future.  They accidentally snuck
into the previous changes.  They are caused by running a custom build of
clang with changes from the future in the past.
=> Foundation: remove future fixes

Foundation/Process.swift
This was being constructed twice as possibly an accident.  Preserve a
single instance of the constructor.
=> Process: remove some duplication in RunLoop setup

CoreFoundation/String.subproj/CFRegularExpression.c, CoreFoundation/String.subproj/CFRegularExpression.h, Foundation/NSRegularExpression.swift, Foundation/NSTextCheckingResult.swift, TestFoundation/TestNSRegularExpression.swift, TestFoundation/TestNSTextCheckingResult.swift
- Added the missing range(withName:) and corresponding CF function.
The implementation relies on uregex_groupNumberFromName which is
available as a draft API from ICU 55.
- Added tests related to named capture groups.
=> Implement NSTextCheckingResult.range(withName:)

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- chmod() failing should throw an error and not call fatalError().
- Behaviour now matches Darwin.
(cherry picked from commit 5995272b8f80a3910eef4fe8e00237f097fdc9eb)
=> [5.0] FileManager: setAttributes(ofItemAtPath:) should throw if chmod fails.

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- chmod() failing should throw an error and not call fatalError().
- Behaviour now matches Darwin.
(cherry picked from commit 5995272b8f80a3910eef4fe8e00237f097fdc9eb)
=> [4.2] FileManager: setAttributes(ofItemAtPath:) should throw if chmod fails.

Foundation/Data.swift
`malloc_good_size` is not available on Windows.  Additionally, `munmap`
is spelt `UnmapViewOfFile`.
=> Data: adjust for Windows

Foundation/FoundationErrors.swift
`GetLastError` returns a `DWORD` rather than `Int32`.  Adjust the
signature to avoid the need for the explicit cast as it is an internal
helper.
=> Windows: make _NSErrorWithWindowsError easier to use

Foundation/Decimal.swift, Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- Decimal: Add an internal .int64Value and .uint64Value.
- NSDecimalValue: For the .int*Value and .uint*Value properties
use a truncated value from .int64Value and .uint64Value.
- Using .doubleValue lost information when returning large numbers
> 2e53 due to Double to Int conversion.
- The returned values mostly match Darwin, moreso than just returning 0
when an exact conversion cannot be made.
=> NSDecimalValue: Dont use .doubleValue for integer properties.

Foundation/AffineTransform.swift, Foundation/Calendar.swift, Foundation/CharacterSet.swift, Foundation/DateComponents.swift, Foundation/IndexSet.swift, Foundation/Locale.swift, Foundation/NSCache.swift, Foundation/NSCalendar.swift, Foundation/NSError.swift, Foundation/NSObject.swift, Foundation/Notification.swift, Foundation/PersonNameComponents.swift, Foundation/TimeZone.swift, Foundation/URL.swift, Foundation/URLComponents.swift, Foundation/URLRequest.swift
There are some remaining warnings, but this should be a good start.
=> Use `Hashable.hash(into:)` over `hashValue` to silence the deprecation warnings

Foundation/DateFormatter.swift, TestFoundation/TestDateFormatter.swift, TestFoundation/TestUtils.swift
- When parsing a date, return nil if the date to be parsed was not
fully consumed by the parse format.
(cherry picked from commit 8747de5134aba1281d5c641ea1bcb0d6b5f6e31d)
=> [4.2] SR-9322: DateFormatter difference between macOS and Linux

Foundation/NSRange.swift, TestFoundation/TestNSRange.swift
Prior to Swift 5, String uses UTF-16 for its Index and encodedOffset. However, this assumption is no longer valid and encodedOffset might be in UTF-8 for native contents in Swift 5.
This change should make the initializer work as expected under either circumstances.
=> NSRange: fix init from region RangeExpression in target String

Foundation/Decimal.swift, Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- Decimal: Add an internal .int64Value and .uint64Value.
- NSDecimalValue: For the .int*Value and .uint*Value properties
use a truncated value from .int64Value and .uint64Value.
- Using .doubleValue lost information when returning large numbers
> 2e53 due to Double to Int conversion.
- The returned values mostly match Darwin, moreso than just returning 0
when an exact conversion cannot be made.
(cherry picked from commit f369d31f91b267b2a57141eb610cf1cbda5bedde)
=> [5.0] NSDecimalValue: Dont use .doubleValue for integer properties.

Foundation/FileHandle.swift, Foundation/Process.swift
This implements the `NSTask` API for Windows.
=> Process: port to Windows

TestFoundation/TestProcess.swift
This test fails frequently in CI and has been preventing us from being
able to release packages. Disable the part affected by SR-9930 for now.
rdar://48045782
=> Workaround SR-9930 to prevent CI failures in test_passthrough_environment

Foundation/FoundationErrors.swift, Foundation/Process.swift
FoundationErrors does not depend on NSSwiftRuntime and thus does not
transitively get the WinSDK import when not building in whole program
mode.  Add an import to get a definition of `DWORD`.
Remoe the `private(set)` from the computed `processIdentifier` property
which is already readonly due to the definition of the computed
property.
=> Foundation: fix a couple of compile errors

Foundation/Operation.swift
Some implementations use these methods for implementing their `Operation`s. We probably still need generalized shims, but these are important to the functionality of the class.
=> Add additional shims for Operation that mimic the KeyPath<> KVC methods.

Foundation.xcodeproj/project.pbxproj, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift
https://bugs.swift.org/browse/SR-9930:
Some environment variables can contain \n. Instead of trying to parse env’s output, have the helper tool return the environment as a property list and deserialize that.
=> <SR-9930> Swift CI: TestProcess.test_passthrough_environment : failed - Test failed: InvalidEnvironmentVariable("swift_xcode")

CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, Foundation/Decimal.swift, Foundation/Scanner.swift, Foundation/ScannerAPI.swift, TestFoundation/TestScanner.swift, TestFoundation/Utilities.swift
Add API on Scanner that's more idiomatic for use in Swift. This promotes some of the existing experimental API and deprecates the rest. The new API is intended to operate on graphemes, not single UTF-16 code units. This API is not experimental and will be supported going forward.
=> Supported Scanner API for Swift

Foundation/DateFormatter.swift, TestFoundation/TestDateFormatter.swift
- When parsing a date, return nil if the date to be parsed was not
fully consumed by the parse format.
(cherry picked from commit 8747de5134aba1281d5c641ea1bcb0d6b5f6e31d)
=> [5.0] SR-9322: DateFormatter difference between macOS and Linux

CMakeLists.txt
Use /MD and /MDd mode compilation rather than /MT or /MTd as per
Microsoft's recommendation.  This allows us to use a shared C runtime.
The static MSVCRT/ucrt cannot be intermingled with a dynamic one.
=> Foundation: build CoreFoundation as /MD

Foundation.xcodeproj/project.pbxproj, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift
Reverts apple/swift-corelibs-foundation#1920
=> Revert "<SR-9930> Swift CI: TestProcess.test_passthrough_environment : failed - Test failed: InvalidEnvironmentVariable("swift_xcode")"

Foundation/Decimal.swift, Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- Decimal: Add an internal .int64Value and .uint64Value.
- NSDecimalValue: For the .int*Value and .uint*Value properties
use a truncated value from .int64Value and .uint64Value.
- Using .doubleValue lost information when returning large numbers
> 2e53 due to Double to Int conversion.
- The returned values mostly match Darwin, moreso than just returning 0
when an exact conversion cannot be made.
(cherry picked from commit f369d31f91b267b2a57141eb610cf1cbda5bedde)
=> [4.2] NSDecimalValue: Dont use .doubleValue for integer properties.

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- Use fchmod() to set the file permissions after opening.
- Ensure all file permissions are correctly masked using ~S_IFMT.
=> SR-6531: FileManager copyItem() does not preserve permissions

CoreFoundation/String.subproj/CFString.c, Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSString.swift
- Use Swift's stringification of numbers for .description and .stringValue
- Use String(format:locale:...) with the correct format for the
NSNumber type if locale is not nil.
- Enable use of __CFStringFormatLocalizedNumber() on
DEPLOYMENT_TARGET_LINUX.
(cherry picked from commit 6450221c7fea77b8c458ca7baac953cc939c41ae)
- Add NSDecimalNumber.description
(cherry picked from commit 7cb608f2d0d666223f5fd340eaa686c769b30bb4)
=> [4.2]  SR-1464: NSNumber.description is not compatible between OS X and linux

Foundation/Scanner.swift, TestFoundation/TestNSString.swift
- Don't require a digit before a leading decimal separator.
- Support exponent specified by 'e' or 'E'.
(cherry picked from commit acb8cf74898775024f0269ff3dff171d80a6203f)
=> [4.2] SR-1674: NSString.doubleValue doesn't support a few formats supported by Darwin

CoreFoundation/Base.subproj/CFBase.h, CoreFoundation/CMakeLists.txt
`_USRDLL` is used to indicate that you are building a MFC DLL while
`_WINDLL` is specified for **ALL** DLL builds. Use the correct macro.
=> CoreFoundation: switch to `_WINDLL` from `_USRDLL`

CMakeLists.txt
This sets up the dependencies we need on Windows.  It helps reduce the
spew from the linker when building for windows.
=> build: link in dependencies on Windows

Foundation/FileManager.swift
This leaves a few functions unimplemented and the DirectoryIterator unimplemented as they need to match the semantics of FTS which is not present on Windows.  The remainder of the API surface has been reimplemented in terms of the Windows API.
=>  Foundation : partial port of NSFileManager for Windows

Tools/plutil/main.swift
plutil uses the C runtime, make sure that we import `MSVCRT`.
=> plutil: make `plutil` build on Windows

Foundation/NSData.swift, Foundation/NSSwiftRuntime.swift
The `bzero` implementation is unnecessary as it is trivially
implementable by the "modern" `memset` API.  Additionally, the use of
the type `size_t` causes trouble for Windows which tries to interpret it
as `Foundation.size_t` rather than `ucrt.size_t` which results in a
horrific deserialisation fatalError.
=> Foundation: remove deprecated `bzero`

Foundation/PropertyListSerialization.swift
These are meant to be public so that they can be passed when reading a
plist. Previously they were accessible on macOS, but not Linux.
=> Make PropertyListSerialization.MutabilityOptions constants public

CMakeLists.txt, CoreFoundation/CMakeLists.txt
SR-9138 has not yet been resolved, so work around the spew.
Additionally, we do not yet have /MT and /MD supported in the frontend,
so manually control that (as is done in the swift repo).
=> build: add some workarounds for Windows

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- Use fchmod() to set the file permissions after opening.
- Ensure all file permissions are correctly masked using ~S_IFMT.
(cherry picked from commit aa5f75c30e98e7096c162d6e1aaf72aaac6cbc5c)
- Check the file copy worked in the tests
(cherry picked from commit a16c18c4bb2b12772d2717ee2f22872e24e0baf5)
=> [5.0]  SR-6531: FileManager copyItem() does not preserve permissions

Foundation/NSPathUtilities.swift
Windows provides `GetTempPath` for getting the temporary directory which
consults the environment variables and falls back through a cascading
set ultimately ending up at `%SystemRoot%\Temp` if nothing else is
found.  The last path is not exactly great, but, we do not expect to end
up there as modern Windows will use `%UserProfile%\Local Settings`
before that.
=> Foundation: adjust `NSTemporaryDirectory` for Windows

CMakeLists.txt, CoreFoundation/CMakeLists.txt
This reverts commit 021533bcc19e49cb7f373ed096caa1adfd03b862.
It broke lldb PR testing, as the version of `ubuntu` on the builders is 55.
It looks like I have an `icu` directory in my checkout, so I think the build might have moved to build its own version of `libicu` (although I'm not confident about this).
cc ing: @spevans
=> Revert "Add ICU version check to ensure minimum of version 61 is used."

Foundation/NSDate.swift, Foundation/RunLoop.swift
Foundation does not re-expose CoreFoundation interfaces on Windows.
This is desirable on Linux as well, however, in the interest of not
breaking existing applications, we have not yet done this.  For now
interfaces required are only available on Windows.
=> Foundation: add SPI for XCTest

CoreFoundation/String.subproj/CFString.c, Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSString.swift
this reverts #1929 from `swift-4.2-branch`. See the discussion in #1929 for the rationale.
=> revert #1929

CoreFoundation/String.subproj/CFString.c
(cherry picked from commit f9f75d25acd91741b9833c4697b8a47fcecad457)
Please see #1871  for details.
=> [5.0] Fix a bug in format localized number on s390x

CMakeLists.txt, CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/CFRuntime_Internal.h, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/CMakeLists.txt, CoreFoundation/Locale.subproj/CFDateIntervalFormatter.c, CoreFoundation/Locale.subproj/CFDateIntervalFormatter.h, Foundation.xcodeproj/project.pbxproj, Foundation/DateIntervalFormatter.swift, TestFoundation/TestDateIntervalFormatter.swift, TestFoundation/main.swift
(cherry picked from commit 988d5f89126bd79d705584fb8ae19a086d230c07)
Add the new files to the `CMakeLists.txt`s.
(cherry picked from commit 0eed327211feaa131a28590b5a28a286130a15e8)
Fix boundary styles outside of Darwin.
(cherry picked from commit ff070d603405ace93adbb13f6362707141f5021d)
Guard the tests as well.
(cherry picked from commit 32cfcf1d8ed62e0877b7247d70558ba66f1f81cf)
Make tests fuzzier so they work on both Darwin and Linux ICUs.
(cherry picked from commit b342e5f05c3288ee50758f7792523fb55f339bd2)
Better assertion failure messages in the fuzzy matching.
(cherry picked from commit 0c69d1a049e50e9e198bbe3f104fa63464b2e8f2)
Even more info.
(cherry picked from commit e395327f358fa8a5c709f674a04caf702705d3a9)
Actually fix all the missed copy-paste changes after fuzzification. …
=> [5.0] Implement DateIntervalFormatter.

Foundation/NSRange.swift, TestFoundation/TestNSRange.swift
Cherry pick #1894 to swift-5.0-branch
=> [5.0] NSRange: fix init from region RangeExpression in target String

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager.swift, Foundation/ProcessInfo.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestProcessInfo.swift
- Linux kernel >= 4.11.0 has a statx() call for extended file stat
information and this can be used to set .creationDate
=> FileManager.attributesOfItem(atPath:) - use statx() on Linux if available.

Foundation/ProcessInfo.swift
Fix the build after the recent changes to the ProcessInfo which
attempted to use `utsname` on Windows which does not provide that
interface.
=> Foundation: support OS version query for Windows

Foundation/NSPathUtilities.swift
Use the shlwapi API `PathIsRelative` to determine if the path is
absolute or not.
=> NSPathUtilities: correct `isAbsolutePath` for Win32

CMakeLists.txt
Correct the dependencies for the Foundation build (it depends on UUID for CoreFoundation).  Specify the deployment target to enable building the foundation tests for Windows.
=> build: improvements for building the tests on Windows

Foundation/NSAttributedString.swift, TestFoundation/TestNSAttributedString.swift
- Also add an `@available()` deprecate the old name.
- Matches Darwin for Swift 5.0
=> NSAttributedString: Rename NSAttributedStringKey to NSAttributedString.Key

CoreFoundation/String.subproj/CFString.c
Windows now provides this part of C99.  Unconditionally enable this
support now.
=> CoreFoundation: `va_copy`, `va_end` are availble on Win32

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Collections.subproj/CFData.c, Foundation/NSData.swift, Foundation/NSSwiftRuntime.swift, TestFoundation/TestPropertyListSerialization.swift
In 4.x, bridging `Data` to an object produces a `_NSSwiftData`, a `NSData` subclass. `CFData…` functions weren’t set up for it, so now they must be. Unfortunately, due to the way the implementation of s-c-f differs from Darwin’s — since we have no class clusters in Swift — there’s some wrangling needed in NSMutableData to prevent infinite recursion when its base class’s methods are invoked. rdar://48420798
=> [4.2] Fix PropertyListSerialization not doing a roundtrip of Data correctly.

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
- The difference of the expoents could exceed Int8.min / Int8.max, so
convert to Int first.
- This avoids a crash if comparing numbers with a large exponent
difference.
=> Decimal: NSDecimalNormalize() - avoid overflow/underflow on exponent difference

Foundation/Decimal.swift, Foundation/JSONEncoder.swift, TestFoundation/TestCodable.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestJSONEncoder.swift
- Decoding Decimal was going via Double / NSNumber but this loses
information for numbers with lots of digits that cant be represented
by Double but can be by Decimal.
- TestCodable.swift: Re-enable some tests that were broken due to
trying to JSON encode non-toplevel types.  Wrap them in an array
to satisfy the requirement.
=> Decimal: Enable bridging between Decimal / NSDecimalNumber for Codable fix.

Foundation/FileHandle.swift
Use the FileHandle(handle:closeOnDealloc:) initializer rather than
passing the fd as `-1` which causes a failure in the C runtime due to an
invalid fd being passed to `_get_ofshandle`.
=> FileHandle: create invalid handle properly on Windows

Foundation/FileHandle.swift
The parameters to `DuplicateHandle` were in the wrong order.  Correct
the order.  Fixes a failure to duplicate the handle.
=> FileHandle: correct `DuplicateHandle` invocation

CoreFoundation/String.subproj/CFString.c
(cherry picked from commit f9f75d25acd91741b9833c4697b8a47fcecad457)
This should fix the issue that broke #1929 on ARM
=> [4.2] Fix a bug in format localized number on s390x and ARM

CoreFoundation/String.subproj/CFString.c, Foundation/NSDecimalNumber.swift, Foundation/NSNumber.swift, TestFoundation/TestDecimal.swift, TestFoundation/TestNSNumber.swift, TestFoundation/TestNSString.swift
- Use Swift's stringification of numbers for .description and .stringValue
- Use String(format:locale:...) with the correct format for the
NSNumber type if locale is not nil.
- Enable use of __CFStringFormatLocalizedNumber() on
DEPLOYMENT_TARGET_LINUX.
(cherry picked from commit 6450221c7fea77b8c458ca7baac953cc939c41ae)
- SR-1464: Add NSDecimalNumber.description
(cherry picked from commit 7cb608f2d0d666223f5fd340eaa686c769b30bb4)
=> [4.2] SR-1464: NSNumber.description is not compatible between OS X and linux

Foundation/NumberFormatter.swift, TestFoundation/TestNumberFormatter.swift
- For the numberStyle .currency, use a minimumIntegerDigits of 1.
- If minimumIntegerDigits is set to any value (including 0) before
the numberStyle is set, preserve the original value.
(cherry picked from commit c8c16eb0e69afd073554c9ae7a959d8ec7d61af6)
NumberFormatter: More fixes for numberStyles
- Fix rawValue for Style.{currencyISOCode,currencyPlural,currencyAccounting}
- Fix minimumIntegerDigits for .currencyPlural
- Fix usesSignificantDigits, minimumIntegerDigits and groupingSize for
.percent
(cherry picked from commit 3fef3a857d0302a7a919e857635601d1d31969d5)
=> [4.2] SR-7481: NumberFormatter inconsistency on Linux

Foundation/NSNumber.swift, TestFoundation/TestNSNumber.swift
- NSNumber.description: Second kCFNumberFloatType should have been
kCFNumberFloat32Type in case statement.
- Remove extra kCFNumberCGFloatType as it is handled seperately.
- Temporarily disable some extra tested caused by SR-9699 issue
(cherry picked from commit 786ec348a011a9ed91af32cb0ccba71096c4d522)
=> [4.2] SR-9685: Accessing NSNumber(value: 1.2 as Float).description crashes

CoreFoundation/RunLoop.subproj/CFRunLoop.c
This has the wrong signature and is available directly.  Just use it
rather than create a macro.
=> RunLoop: remove incorrect usage of libdispatch queue

Foundation/DateFormatter.swift, TestFoundation/TestDateFormatter.swift
The locale and timeZone properties of DateFormatter seems to be "null
resetteable" in macOS, but the Swift Foundation behaviour differs.
Before this patch, setting locale to nil would segfault the program the
next time the formatter is used, while timeZone will incorrectly return
nil. After this patch a nil locale will simply reset to the current
locale and a nil timeZone will reset to the system one.
The tests check that the initial defaults are also correctly set.
(cherry picked from commit 1965003fd062915279353a1afc0a25fae1abbff3)
=> [4.2] Fix DateFormatter behaviour for nil locale and timeZone. (#1681)

CoreFoundation/NumberDate.subproj/CFTimeZone.c, TestFoundation/TestTimeZone.swift
- TimeZone.knownTimeZoneIdentifiers was returning time zone names
that could not be instantiated by TimeZone(identifier:) due to
CFTimeZone.c:__nameStringOK() filtering out some names.
- Make CFTimeZoneCopyKnownNames(), used by .knownTimeZoneIdentifiers,
also filter these names using __nameStringOK().
- __nameStringOK calls ICU function ucal_getCanonicalTimeZoneID
which ultimately decides if the time zone is valid.
(cherry picked from commit 7972ce4bd18b2b42bfa42bcbbbe76855ebf5cba5)
=> [4.2] SR-8078: Some time zone identifiers are not supported by TimeZone on Linux

CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/DateFormatter.swift, TestFoundation/TestCalendar.swift, TestFoundation/TestDateFormatter.swift, TestFoundation/TestTimeZone.swift
Because of the use of 'timeZone' instead of 'newValue' in the setter, setting the timeZone of a DateFormatter doesn't actually work. Instead, it winds up re-setting the old value, which happens to be whatever was originally set, usually what we get from copying the default down in CoreFoundation.
Also adds a unit test to help prevent breaks like this again.
(cherry picked from commit 9f3e050bf26a1c8fe7e94849c8e0183f6ee10b39)
Fix Off-By-One Error With System TimeZone
This one is nasty, since it creates problems for DateFormatter, while appearing to behave correctly. (Mostly)
By copying 1 too many bytes, we wind up with the null terminator in the CFString. This breaks DateFormatter in an annoying way that the system TimeZone is always considered to be GMT by the formatter. You can ask for …
=> [4.2] Fix DateFormatter TimeZone Setter

Foundation/FileHandle.swift
The readability and writability handlers are not yet implemented on
windows, and cannot be assigned to.  A SOCKET is not a file descriptor
on Windows which means that the shared implementation does not work for
Windows.
=> HACK: make FileHandle build on Windows again

Foundation/FileManager.swift
As per the MSDN documentation, `GetFileAttributesExW` returns a non-zero
value on success.  Correct the boolean logic here.
=> FileManager: `GetFileAttributesExW` returns `FALSE` on failure

Foundation/Data.swift, TestFoundation/TestNSData.swift
Applies apple/swift#23244 to here as well.
=> Fix off-by-one when initializing Data with discontiguous, underestimated Sequences

uuid/uuid.c
Windows does not have a `/dev/urandom` source.  Provide a wrapper around
the `BCryptGetRandom` interface to provide the equivalent functionality.
=> uuid: make `read_random` work on Windows

Foundation/Data.swift, TestFoundation/TestNSData.swift
Cherry-picks #1995 to swift-5.0-branch
=> [5.0] Fix off-by-one when initializing Data with discontiguous, underestimated Sequences

Foundation/NSTimeZone.swift
Convert `UTC` and `GMT` to `GMT+0000` for the CFTimeZone construction on
Windows as we do on Android.  This allows the Calendar tests build/run
on Windows.
=> NSTimeZone: use the android path on Windows

cmake/modules/SwiftSupport.cmake
Windows uses the NeXT-ish layout with a different resource dir
(`<TARGET>.resources`) rather than `Resources`.  Account for that in the
build.
=> build: correct the resource layout for Windows

TestFoundation/TestTimeZone.swift
There is no equivalent for tm_zone on Windows.  Simply ignore the test.
=> TestFoundation: tm_zone does not exist on Windows

Foundation/NSPathUtilities.swift
The path size changing to a smaller value is acceptable.  Furthermore,
the return value will not account for the trailing null, so the count
was off by one.  This fixes the temporary path construction for Windows.
=> NSPathUtilities: relax the constraint for Windows

CoreFoundation/StringEncodings.subproj/CFUniChar.c
This fixes the bitmap loading on Windows.  Windows uses the "Unicode"
(UTF-16) file paths as that is the native representation.  However, we
were using `strcmp` which would not yield the correct check.  This
allows us to load the bitmap data on Windows as well.
=> StringsEncoding: correct bitmap loading

Foundation/NSGeometry.swift, TestFoundation/TestNSGeometry.swift
See [SR-10056](https://bugs.swift.org/browse/SR-10056) for a summary of this issue with example. The floating point arithmetic in `CGRect.intersection(_:)` results in a rectangle not equal to its intersection with `CGRect.infinity`.
=> Avoid FP arithmetic if unnecessary in CGRect.intersection(_:)

Foundation/FileHandle.swift
Replace the `NSUnavailable` with `NSUnimplemented` as there is no
`NSUnavailable` function.  This repairs the Windows build.
=> FileHandle: there is no `NSUnavailable`

CMakeLists.txt
- The findICU  was not finding the libicu{uc,i18n}swift libraries so
libFoundation.so was still being linked to the system ICU libraries.
In the master branch, `ICU_UC_LIBRARY_DEBUG` `ICU_UC_LIBRARY_RELEASE` `ICU_I18N_LIBRARY_DEBUG` and `ICU_I18N_LIBRARY_RELEASE` are passed in by build-swift-impl, directly set them in CMakeLists.txt here.
=> [5.0] Link to the ICU61 libraries that are built for Linux

CoreFoundation/String.subproj/CFBurstTrie.h, CoreFoundation/URL.subproj/CFURLComponents.h, TestFoundation/TestURLSession.swift
- Use correct function prototype for functions taking no arguments.
- Remove an undeed defer {} wrapper as call occurs at end of block.
=> Fix more compile warnings

Foundation/FileManager.swift
Uses `FindFirstFileW` repeatedly to enumerate the directories. The unix implementation via fts does a preorder traversal, though the order that the children are visited in seems random. The Windows implementation also shares this behaviour: `FindNextFile` isn't guaranteed to be alphabetical depending on the file system.
=> Implement NSURLDirectoryEnumerator for Windows

TestFoundation/TestProcess.swift
Rather than use `realpath` which is not universally available, use
`.standardizingPath` which should normalize the path as `realpath` on
all the targets since we are testing `Process` rather than
`FileManager`.
=> TestFoundation: use `.standardizingPath` for normalization

Foundation/NSURL.swift
Not all platforms are POSIX.  Use the platform URL style when converting
the paths.  This was possible in CoreFoundation through the
`PLATFORM_PATH_STYLE` macro, but, unfortunately, that is unavailable to
us in Swift.  Emulate that and use it.
=> NSURL: Use the platform path style

Foundation/FileManager.swift
`CreateDirectoryW` returns `FALSE` on failure, not on success.
=> FileManager: correct boolean logic

Foundation/JSONSerialization.swift, TestFoundation/TestJSONEncoder.swift, TestFoundation/TestJSONSerialization.swift
- Check the number looks like a JSON number and exit early if not.
- Use the native Int64(), UInt64(), Double() parsers to avoid creating
a C string and passing to strtol()/strtod(). This also eliminates a
memcpy() and removes the 63 digit restriction which would fail to
parse numbers expressible by Double's full exponent.
- For numbers with a leading '-' sign, parse using Int64() falling
back to Double(), otherwise parse using UInt64() failling back to
Double().
(cherry picked from commit ff5f81e42402bd425810466a6e5d8756006e99b5)
- Fully validate that the number conforms to the JSON number
specification.
- Determine if the number should be parsed as a UInt64, Int64 or
Decimal before falling back to Decimal.
(cherry picked from commit 1e32417299c577be1fb94d4ef9da92e0b3f99bd8)
Update …
=> [4.2] JSONSerialization: Improve parsing of numbers

Foundation/JSONSerialization.swift, TestFoundation/TestJSONSerialization.swift
- Use .description property of numbers to encode as String
instead of using CFNumberFormatter for Float/Double,
and serialising integers explictly.
(cherry picked from commit 72e7bbdd370a26b0d59ea067317ba5709fc19e30)
- Add round-trip serialisation test case.
(cherry picked from commit ad620ff781374e740dadbaff4c159f74fb01368b)
=> [4.2] SR-7195: JSONSerialization encodes Double differently on Darwin and Linux

TestFoundation/TestProcessInfo.swift
Windows does not have `setenv`, but it does have a `putenv`, which we
can use in its stead.
=> TestFoundation: emulate `setenv` using `putenv` on Win32

Foundation/FileManager.swift
Windows doesn't have lstat, but it still can be implemented. This should
help remove some of the Windows specific codepaths.
This is based off the [lstat in llbuild](https://github.com/apple/swift-llbuild/blob/master/lib/Basic/PlatformUtility.cpp#L57)
Also depends on https://github.com/apple/swift/pull/23342
=> Implement _lstatFile on Windows

TestFoundation/TestNSNumberBridging.swift
- This still works on Linux so disable it conditionally.
=> TestNSNumber: Disable testNSNumberToBool() that breaks on Darwin.

Foundation/URL.swift
It's my first PR so if there's something wrong (name of the branch, commit message, etc) please let me know.
Next time I'll to make something more impactful. 🙇
=> Refactor if statements in URL.swift

TestFoundation/TestNumberFormatter.swift
test_currencyPluralMinimumIntegerDigits does not and did never work on
Ubuntu 14.04. In Swift 5 it works because a newer ICU is vendored which
fixes the issue. But in Swift 4.2.x we don't vendor ICU so we can't get
this test to work on Ubuntu 14.04, hence removing as it's no worse than
Swift 4.2.3.
=> [4.2] disable test_currencyPluralMinimumIntegerDigits

TestFoundation/TestProcess.swift
- TestProcess: Replace use of DispatchSource.makeReadSource() with
FileHandle.readabilityHandler to increase test coverage.
=> FileHandle: Increase testing of .readabilityHandler

Foundation/HTTPCookie.swift, TestFoundation/TestHTTPCookie.swift
The HTTPCookie  initializer takes values as ```Any ```  but fails to create cookie when Substring is passed to it. Casting from ```Substring``` to String returns ```nil``` due to which the initializer is failing silently.
=> [SR-9887] HTTPCookie on Linux does not accept Substring values

CMakeLists.txt
plutil is not installed on Windows becuase ".exe" extension is missing in CMakeLists.txt.
=> Fix plutil installation failure on Windows

CoreFoundation/Locale.subproj/CFDateIntervalFormatter.c
The enum name was probably autocompleted wrong. There should be no
functional change. LLVM 8 seems to raise a new warning here.
=> [CoreFoundation] Fix enum name in function body.

CMakeLists.txt, DarwinCompatibilityTests.xcodeproj/project.pbxproj, DarwinCompatibilityTests.xcodeproj/xcshareddata/xcschemes/xdgTestHelper.xcscheme, Foundation.xcodeproj/project.pbxproj, TestFoundation/TestFileHandle.swift, TestFoundation/TestNSCalendar.swift, TestFoundation/TestPipe.swift, TestFoundation/TestProgressFraction.swift, TestFoundation/TestScanner.swift, TestFoundation/TestStream.swift
- DarwinCompatibility: TestStream.seek(to:) is internal API
- DarwinCompatibility: Disable tests that use new API not yet in Foundation
- Update Swift version to 5.0 and target deployment version to 10.14.
- Rename TestNSProgressFraction.swift to TestProgressFraction.swift
to reflect name of test class.
- Wrap file in NS_FOUNDATION_ALLOWS_TESTABLE_IMPORT as the type is
internal and cant be tested by DarwinCompaitibilityTests.
- Add TestPropertyListEncoder.swift and TestDateIntervalFormatter.swift
to DarwinCompatibilityTests.
=> Update DarwinCompatibilty tests and Xcode project

Foundation/FileHandle.swift, Foundation/FileManager.swift
`FileHandler` APIs used to replace the curret implementation of the private method
`_compareFiles(withFileSystemRepresentation:andFileSystemRepresentation:size:bufSize:)`
Bug Link: https://bugs.swift.org/browse/SR-9979
=> [SR-9979] FileHandle class used to implement FileManager._compareFiles

TestFoundation/TestNumberFormatter.swift
test_currencyAccountingMinimumIntegerDigits does not work with Ubuntu
14.04's libICU and therefore we can't run it in CI.
This will be fixed with Swift 5 because Swift 5 vendors libICU which is
the right solution but too big of a change for Swift 4.2.
test_currencyISOCodeMinimumIntegerDigits has to be disabled too even
though the code does not crash on Swift 4.2.3 on Ubuntu 14.04. The
reason is that commit 3290d07 corrects
the NumberFormatting styles. Previously, currencyISOCode used to map to
`7` which is incorrect. Now it correctly maps to `8` but unfortunately
that is unsupported by 14.04's libICU...
=> disable test_currencyAccountingMinimumIntegerDigits & test_currencyISOCodeMinimumIntegerDigits

Foundation/ProcessInfo.swift
At Windows 8.1, Microsoft changed the default behavior of
GetVersionEx not to return actual version number for preventing
compatibility isseus. I think it's better to use the product version
retrived from kernel32.dll as an alternative as Microsoft described in
a document:
https://docs.microsoft.com/en-us/windows/desktop/SysInfo/getting-the-system-version
=> Corecct ProcessInfo.operationSystemVersion on Windows

Foundation/FileHandle.swift
fileDescriptor should be an Int32, not an Int
=> Fix FileHandle Compilation on Windows

Docs/Status.md, TestFoundation/TestURLResponse.swift
This is my first rather small contribution to the swift project.
I tried to start with updating/adding a few tests for URLResponse.
Since I am still on High Sierra I was working on the 4.2 branch.
Please let me know if there is anything wrong or things I can do better next time.
=> Extend URLResponse tests

TestFoundation/TestProcess.swift
- TestProcess.runTask() uses a pipe to read the stdout of a subprocess
during tests however sometimes the data read from the pipe is
truncated causing issues with the testing of the response.
- Use .readabilityHandler to read the data whilst the sub-process is
running and then drain the pipe after the process has terminated.
=> TestProcess: Improve reading from a pipe with a sub-process

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSSwiftRuntime.swift
Windows requires the networking subsystem (WinSock) to be initialized.
However, the user expects to be able to use the networking APIs in
Foundation without performing any one-time initialization.  Furthermore,
due to the macro usage in the initialization path, it is easier to
perform the initialization in C than in Swift.  CoreFoundation has a SPI
for this (`__CFSocketInitializeWinSock`).
=> Foundation: initialize CFSocket on startup

CoreFoundation/Base.subproj/CFFileUtilities.c
Simplify the Windows implementation for `_CFIterateDirectory`.
Additionally, we were passing an absolute path for the full path which
is meant to be the prefixed path (with `stuffToPrefix`).  For now pass
the `fileName` itself.  This corrects the
`-[NSURL urlForResource:withExtension:]` implementation for Windows.
=> CoreFoundation: simplify and fix `CFIterateDirectory`

Foundation/Stream.swift, Foundation/URLSession/BodySource.swift, Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/URLSessionTask.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestStream.swift, TestFoundation/TestURLSession.swift
>Allows using InputStream in _URLRequest_ as `httpBodyStream`. Also, implement `seekInputStream` in _NativeProtocol_.
This is a cherry-pick of the #1629
=> [5.0] URLSessionTask: implement InputStream.

Foundation/NumberFormatter.swift, TestFoundation/TestNumberFormatter.swift
- Re-enable TestNumberFormatter.test_en_US_initialValues()
- Convert internal ivars to private
- Also remove Number Formatter Styles constants defined only for macOS.
=> NumberFormatter: Get properties as attributes

Foundation/Host.swift, TestFoundation/TestHost.swift
This is my first rather small contribution to the swift project.
I implemented Host.isEqual method and test.
=> Implement Host.isEqual and Test

CoreFoundation/CMakeLists.txt, CoreFoundation/CoreFoundation.rc, CoreFoundation/NumberDate.subproj/CFTimeZone.c, CoreFoundation/OlsonWindowsMapping.plist, CoreFoundation/Tools/OlsonWindowsDatabase.xsl, CoreFoundation/Tools/WindowsOlsonDatabase.xsl, CoreFoundation/WindowsOlsonMapping.plist, CoreFoundation/WindowsResources.h, CoreFoundation/cmake/modules/CoreFoundationAddFramework.cmake
Refactor the initialization codepath a bit to make it more obvious how to modify this to support Windows and alter to query the information from the system.
=> Refactor the CFTimeZone initialization

Foundation/NSSwiftRuntime.swift
#2026 seems to be calling wrong function.
=> Fix build falure by calling unexisting function __CFInitializeWinSock

TestFoundation/TestXMLDocument.swift
Test Case 'TestXMLDocument.test_xpath' started at 2019-03-29 17:27:41.139
0% tests passed, 1 tests failed out of 1
Total Test time (real) =  23.90 sec
The following tests FAILED:
1 - TestFoundation (SEGFAULT)
https://bugs.swift.org/browse/SR-10098
=> Disable TestXMLDocument.test_xpath which crashes sometimes in CI

Foundation/URLSession/BodySource.swift
- init(fileURL:workQueue:dataAvailableHandler:) was using the closure
argument for the buffer pointer outside of the closure, after
.deallocate() was called.
(cherry picked from commit 21549ff34a9cc0137ee48d842bcc28cbb675deb5)
=> [5.0] _BodyFileSource: Fix use after free in init()

Foundation/FileManager.swift
Requires https://github.com/apple/swift-corelibs-foundation/pull/2015
=> Windows: Implement attributesOfItem with _lstat

Foundation/URLSession/URLSessionTask.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
Basically the  crash  in URLSession code is due to the invocation of ```TaskRegistry.remove``` twice with the same ```taskIdentifier```  from ```urlProtocolDidFinishLoading```. While handling basic authentication,  if the response code is ```401``` and authentication headers are missing  then   call should fail with error ```urlProtocol(_ protocol: URLProtocol, didFailWithError error: Error) ```  which  a is performing the removal of ```task`` from ```TaskRegistry```. Hence, adding the ```return``` statement after the above call should resolve the issue.
=> [SR-10281] URLSession crash while handling basic authentication

Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- Nanoseconds were originally disable in #1658 to fix SR-7011,
however the CF/NSCalendar rewrite in #1755 fixed them to
work correctly so they can now be re-enabled.
=> SR-9439: Calendar.dateComponetns: Enable .nanoseconds

Foundation/XMLParser.swift, TestFoundation/TestXMLParser.swift
XMLParser swaps the prefix with the local name. This behavior is apparently a bug. This PR fixes it.
Resolves [SR-10157](https://bugs.swift.org/browse/SR-10157).
=> SR-10157: XMLParser shouldn't swap the parts of the element name.

Foundation/XMLParser.swift, TestFoundation/TestXMLParser.swift
(cherry picked from commit e724ba0a04b6bfb2257ab308b7f0f7d4a9febcb8)
XMLParser: Handle the parse result.
(cherry picked from commit 2fe37a22157503bd8ddd046a4da150344c3e07cb)
XMLParser: Simplify the code in `func _handleParseResult() -> Bool`.
(cherry picked from commit 8314ceef9d256107db15bb45ebc657aadf9bb2ab)
=> [5.0] XMLParser.parse()` returns different values between macOS and Linux when `abortParsing()` is called.

Foundation/URLSession/BodySource.swift
- init(fileURL:workQueue:dataAvailableHandler:) was using the closure
argument for the buffer pointer outside of the closure, after
.deallocate() was called.
(cherry picked from commit 21549ff34a9cc0137ee48d842bcc28cbb675deb5)
=> [4.2] _BodyFileSource: Fix use after free in init()

Foundation/FileHandle.swift, TestFoundation/TestPipe.swift
This doesnt actually crash in `master` as the region passed has a non-nil `baseAddress` and `bytes.count` = 0, but eliminate the force unwrap anyway incase the `baseAddress` ever becomes `nil` in the future.
=> SR-10240: Dont try to write an empty Data() if it has a nil baseAddress.

CMakeLists.txt, CoreFoundation/CMakeLists.txt
This switches the CoreFoundation sub-build to use `add_subdirectory`.
This has a few **MAJOR** benefits:
- CoreFoundation changes get tracked and cause compile/link triggers
- CoreFoundation warnings are surfaced in the build
- CoreFoundation dependencies are reflected in the right location
- Foundation dependencies are reflected in the right location
- The overall build is simpler
Eventually, it should be possible to further simplify this.
Unfortunately, a couple of hacks are needed to make this work.  The
sub-projects properties must be cached, but they were just passthrough
previously, so this is not too terrible.  Additionally, the library
control know needs to be saved/restored around it.  The worst thing here
is the need to manually collect the dependency as we do not have a
proper …
=> build: use `add_subdirectory` instead of `add_external_project`

TestFoundation/TestDateIntervalFormatter.swift, TestFoundation/TestFileManager.swift, TestFoundation/TestImports.swift, TestFoundation/TestStream.swift, TestFoundation/xdgTestHelper/main.swift
Alter the importing to use `canImport` and prefer the Swift prefixed
variants of the modules.  This avoids us from maintaining an ever
growing list of OSes, particularly when the Swift variants are less
widely available.
=> TestFoundation: give preference to SwiftFoundation, SwiftXCTest

Foundation/Bundle.swift
`.classNamed(_:)` can now be used, though with a limitation noted in the comments. `.principalClass` is now implemented in terms of `.classNamed(_:)`.
Fixes [SR-10362](https://bugs.swift.org/browse/SR-10362).
=> Parity: Bundle.classNamed(_:) and Bundle.principalClass.

CMakeLists.txt
We currently emit a symbol multiply when building a single module.
Ideally, we would ensure that they are marked for COMDAT and given
LinkOnceODR linkage to ensure that they are preserved.  This makes
errors in the link step more visible.
=> build: silence linker warning (SR-9138)

CMakeLists.txt
This fixes the installation for the static build on Linux as well as the
Windows installation to ensure that the import library is also
installed and that the DLL is located correctly.
=> build: fix installation of files on Windows

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/PlugIn.subproj/CFBundle.c, Foundation/Bundle.swift
Implement this as a function of `CFBundleGetAllBundles()`. Add `.allFrameworks`, which is API that was missed.
Fixes https://bugs.swift.org/browse/SR-10360
=> Parity: Bundle.allBundles/.allFrameworks

TestFoundation/TestNSString.swift
Rather than explicitly requesting the default allocator or the default system
allocator, use `nil` which will result in the use of the default system
allocator.  This avoids the need for use of the internal symbols of
CoreFoundation which are not exposed through Foundation.
=> TestFoundation: use `nil` for the allocator

Foundation/URLSession/TaskRegistry.swift, Foundation/URLSession/URLSession.swift, TestFoundation/TestURLSession.swift
- `invalidateAndCancel` method implemented.
- `getAllTasks` methods implemented.
- New computed property `allTasks` added in `URLSession._TaskRegistry`, to return an array of all the existing tasks added in `_TaskRegistry`.
Update:
Bug Link: https://bugs.swift.org/browse/SR-10428
=> [SR-10428] URLSession: Methods invalidateAndCancel and getAllTasks implemented

Foundation/NSSet.swift, TestFoundation/TestNSSet.swift
- Remove unnecessary `extension` blocks that break up the main
class.
- Group the init() methods together.
=> NSSet: Add missing init(set: NSSet) and .customMirror

Foundation/FileManager.swift, Foundation/NSPathUtilities.swift, TestFoundation/TestFileManager.swift
- Add __fileSystemRepresentation(withPath:) which is a throwing version
to allow validating filenames and throw if invalid or cannot be converted
to FSR.
- Update _fileSystemRepresentation<ResultType>(withPath:_:) and
_fileSystemRepresentation<ResultType>(withPath:andPath:_:) to throw,
and update callers to catch or propagate the error as required.
- .attributesOfFileSystem: Call statfs()/statvfs() using the FSR.
- NSString.deletingLastPathComponent: Fix crash if string is empty.
- Add tests for calling FileManager methods with empty filename and
handle the response more gracefully by throwing an exception.
=> SR-10277: FileManger: Handle invalid filenames including "" more gracefully

TestFoundation/TestNSNumber.swift
In the file "TestFoundation/TestNSNumber.swift" I could see several sections of code having XCTAssertEqual within conditional checks for architectures and OS. For e.g.:-
#if !(os(Linux) && (arch(arm) || arch(powerpc64) || arch(powerpc64le)))
// Linux/arm and Linux/power chars are unsigned, so Int8 in Swift, until this issue is resolved, these tests will always fail.
XCTAssertEqual(NSNumber(value: Int8(-37)).floatValue, Float(-37))
#endif
I have introduced this PR with similar checks for powerpc64le(followed by SR number in comments) for the 2 test failures reported in this SR. This would help move ahead and make some more progress on powerpc64le, until this issue is resolved by the original contributor of the 2 tests or any other member familiar with the changes.
=> Platform check for TestFoundation failures for Apple Swift 5 Toolchain on PowerPC64LE(SR-10255)

.gitignore
AppCode is a popular IDE from https://www.jetbrains.com/objc/ and it uses the `.idea` folder like many other JetBrains products.
=> ignoring AppCode artifacts

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/NSTimeZone.swift, Foundation/TimeZone.swift, TestFoundation/TestTimeZone.swift
Add `__NSLocalTimeZone`; the name is chosen so as to be `NSCoding`-compatible with Darwin. Make sure `NSTimeZone.local` and `TimeZone.autoupdatingCurrent` return it.
Implement `.timeZoneDataVersion` the same way as it is in Darwin.
Re-enable the setter for `.abbreviationDictionary`. We'll fix its bugs rather than crashing.
Fixes https://bugs.swift.org/browse/SR-10348, https://bugs.swift.org/browse/SR-10349
=> Parity: TimeZone.local, TimeZone.timeZoneDataVersion

Foundation/Bundle.swift, TestFoundation/TestBundle.swift
The FHS bundles are an extension for the CoreFoundation implementation
for Swift.  Expose the interface through Bundle interface so that we do
not need to use private CF interfaces in the tests.
=> Bundle: add SPI for FHS style bundles for testing

Foundation/URL.swift
Same as https://github.com/apple/swift/pull/23926.
When `appendingPathComponent(:isDirectory:)` is falling back from an **NSURL**.appendingPathComponent() to an **NSString**.appendingPathComponent(), it's forgetting to take into account the `isDirectory` parameter.
=> appendingPathComponent(:isDirectory:) should account for isDirectory

Foundation/NSArray.swift, TestFoundation/TestNSArray.swift
- Group all of the init() methods together.
=> NSArray: Add missing init(array: NSArray) initializer.

Foundation/NSString.swift
Foundation provides a string enumeration as `StringTransform` which
affords the developer to access the ICU string transformations.  Add
this missing enumeration.
=> NSString: implement `NSString.StringTransform`

TestFoundation/TestURLSession.swift
Windows does not have a `sleep` function but does have `Sleep`.  Rather
than conditionalise the path, use `Thread.sleep(forTimeInterval:)` which
makes the path uniform for all the targets.
=> TestFoundation: replace `sleep` with `Thread.sleep(forTimeInterval:)`

CMakeLists.txt
We need to link against the WinSock library on Windows since we use the
WinSock library for the HTTPServer.  Silence some warnings on Windows
for the linker to make errors easier to spot.
=> build: adjust flags for TestFoundation on Windows

Foundation/FileHandle.swift, TestFoundation/TestPipe.swift
5.0 version of #2053. This crashes in 5.0 as the region has `baseAddress = nil`
=> [5.0] SR-10240: Dont try to write an empty Data() as it has a nil baseAddress.

Foundation/NSKeyedArchiver.swift
`NSUnimplemented()` is a marker for yet-to-be-implemented functionality. We do not support `.openStep` as a format at all; move this to `fatalError()` instead, since setting `.openStep` is a programmer error on Darwin.
https://bugs.swift.org/browse/SR-10416
=> Parity: NSKeyedArchiver: Consider response to setting an output format other than .xml or .binary

TestFoundation/HTTPServer.swift
Make the test HTTPServer build on Windows.  This is needed for the
Windows test suite.
=> TestFoundation: port HTTPServer to Windows

Foundation/Thread.swift, TestFoundation/TestThread.swift
This makes the `name` property use the CoreFoundation SPI to query the
thread name to avoid having to have this interface be used directly in
the tests.
=> Thread: make `Thread.name` return the current thread name

CoreFoundation/RunLoop.subproj/CFRunLoop.c
Rather than masking the function with a macro, now that it is exposed on
all targets, just use it directly.
=> RunLoop: use `_dispatch_get_main_queue_port_4CF`

DarwinCompatibilityTests.xcodeproj/project.pbxproj, TestFoundation/TestProcess.swift, TestFoundation/TestStream.swift
- Add TestFoundation/FixtureValues.swift
- TestProcess: Add fallback to .availableData as new FileHandle
API isnt in Foundation yet.
- TestStream: Wrap @testable import in NS_FOUNDATION_ALLOWS_TESTABLE_IMPORT.
=> DarwinCompatibiltyTests: Update for recent changes

Foundation/NSObject.swift
`_swift_class_getSuperclass` is a standard library internal interface.
Since we have `_getSuperclass()` available, use that rather than
promoting the private interface to SPI.
=> NSObject: use `_getSuperclass()` instead of a SPI

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/PlugIn.subproj/CFBundle.c, Foundation/Bundle.swift, TestFoundation/TestBundle.swift
- Added Windows support
- Added both executable and library main executable layouts
- Added test for reverse bundle lookup (required for all implicitly loaded bundles, eg. Bundle.main)
=> Extended Bundle layout testing

CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, Foundation/FileManager+POSIX.swift, Foundation/FileManager+Win32.swift, Foundation/FileManager.swift
Splits the Windows and POSIX specific File Manager implementations into their own files. See https://github.com/apple/swift-corelibs-foundation/pull/2002#issuecomment-477242876
Not sure if there's a way to make the diff more readable, but in general, what I've done is copy over the function to win32/POSIX, prefixed the name with an underscore, removed the non applicable #if branch, and have the FileManager version pass through to it.
=> Split FileManager into Platform Dependent Files

TestFoundation/HTTPServer.swift
The `lpFlags` parameter is not optional, ensure it is set.
=> TestFoundation: correct `WSARecv` invocation

Foundation/NSPathUtilities.swift
Android Bionic uses /data/local/tmp as the temporary writable directory.
TMPDIR is rarely set and /tmp doesn't exist.
There's some usage of /tmp/ in the tests that might be wrong and might
need to be fixed in the future, but I have to check one by one and right
now I don't have a device to test on.
=> [android] Provide correct temporary directory path.

Foundation/NSDictionary.swift
- Add init(dictionary:copyItems:).
- Add .customMirror
- ExpressibleByDictionaryLiteral: init(dictionaryLiteral: (Any, Any)...)
already existed, just add the conformance to the class declaration.
- Group the init() methods together.
Fixes https://bugs.swift.org/browse/SR-10449
=> NSDictionary: Add customMirror and missing init() method.

Foundation/NSError.swift, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, TestFoundation/TestNSKeyedArchiver.swift, TestFoundation/TestNSKeyedUnarchiver.swift
- Added missing API: `NSDebugDescriptionErrorKey`
- Added secure initializers and one-shot factory methods to `NSKeyed{A,Una}rchiver`
- Deprecated existing initializers and factory methods
=> Parity: NSKeyedArchiver: Secure initializers

Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
When the server answers with a compressed response (with
Content-Encoding header), cURL is configured to automatically decompress
the response. However, there was some inconsistencies with the
Foundation implementation in Darwin platforms, and some bugs in the
handling of compressed responses.
- In Darwin Foundation, the expected number of bytes is -1 for
compressed responses. This is because Content-Lenght will report the
length of the compressed content, but the total bytes written reports
uncompressed lengths. The code is changed to set the expected number
of bytes to -1 if the response includes a Content-Encoding header
different to "identity".
- Since the expected number of bytes is unknown, the data received
callback cannot check for the total bytes received to be equal to
close the …
=> [URLSession] Fix handling of compressed responses.

Foundation/Operation.swift, TestFoundation/TestOperationQueue.swift
- `remove()` and `dequeue()` methods time complexity reduces to **O(1)** from **O(n)**.
- All arrays, veryHigh, high, normal, low, veryLow, all, converted to _DoubleLinkedList_.
- New internal class `_IndexedOperationLinkedList` introduced specifically to work with `Operation`.
- _HashMap_ used to index, node by it's operation, in the linked list, in order to avoid traversing the list to find a node, which in return reduces the time complexity to **O(1)**.
- Unit Test added to test cancel one operation and cancel operations of a specific queue priority
**Discussion Link**
https://forums.swift.org/t/operationqueue-dequeue-and-remove-operations-performance-improvement/20370/9
=> [IMPROVEMENT] Double linked list used to improve performance of dequeue and remove operations in OperationQueue

Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- Override _NSCopyOnWriteCalendar._cfObject to return the backingCalendar created
from CFCalendarCopyCurrent().
=> SR-10333: Calendar.current.dateComponents([.weekday], from: Date()).weekday segfaults

CoreFoundation/PlugIn.subproj/CFBundle_Executable.c, CoreFoundation/PlugIn.subproj/CFBundle_Internal.h, TestFoundation/TestObjCRuntime.swift
While Android does not follow FHS, and it doesn't seem to have something
similar published, it follows some conventions of Unix. One of them
is that libraries are normally named prefixed with "lib" and suffixed
with ".so" like Linux. Executables are also normally named without any
prefix nor suffix.
The changes in this commit lift up restrictions that were in place for
Android, and allow some of the Bundle tests to pass on Android (and lift
another restriction in TestObjCRuntime).
While bundles might never be a common construct in Android, these
changes at least allow to test some of the scenarios, in case someone
needs this behaviour.
This allows `TestBundle`, `TestNSError`, `TestPropertyListSerialization`, `TestObjCRuntime`, and `TestNSKeyedUnarchiver` to pass on Android devices.
=> [android] Fix some parts of Bundle in Android.

Foundation/Scanner.swift, TestFoundation/TestScanner.swift
Fixes https://bugs.swift.org/browse/SR-10389
=> Scanner: Implement scanning for hexdecimal floating point numbers.

Foundation/NSCoder.swift, Foundation/NSKeyedUnarchiver.swift, TestFoundation/TestNSAttributedString.swift, TestFoundation/TestNSKeyedArchiver.swift
- Added missing API: `DecodingFailurePolicy.raiseException`. It is now the default like on Darwin.
- Match Darwin behavior while decoding if you decode without raising exceptions.
- `decodeTopLevel…` variants are noted unavailable on swift-corelibs-foundation, with rationale and replacement directions.
Swift doesn’t have exceptions, and it used to define `.setErrorAndReturn` as the defaults. However, until very recently `failWithError(_:)` was unimplemented and trapped with a fatal error, effectively meaning that all coding failures were behaving as if `.raiseException` was set in a Darwin Swift-only app: by crashing.
Since code written to 4.x-5.0 may be relying on this behavior, we make it explicit and consistent with Darwin: there is now a `.raiseException` constant, it’s the default, …
=> Parity: NSCoder miscellanea

Foundation/NSSwiftRuntime.swift, Foundation/Timer.swift
Foundation.Timer is not currently implemented with a compatible memory layout
so attempt to bridge these classes will fail. Disabling bridging allows
code using CFRunLoopTimer to work until Foundation.Timer is reimplemented.
Fixes https://bugs.swift.org/browse/SR-10465
=> Disable toll-free bridging for CFRunLoopTimer

Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionTask.swift, TestFoundation/TestURLSession.swift
* New private property `hasTriggredResume` introduced to track whether the task actually move past the `suspendCount` in execution
* New internal property `isSuspendedAfterResume` introduced to find the accurate state reason for `.suspend` state
Bug Link: https://bugs.swift.org/browse/SR-10428
=> [SR-10428] URLSession.getTasksWithCompletion method implemented

Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- Nanoseconds were originally disable in #1658 to fix SR-7011,
however the CF/NSCalendar rewrite in #1755 fixed them to
work correctly so they can now be re-enabled.
(cherry picked from commit d8f09b6234a94838cd0c5b917d4cc136f6dc9004)
=> [5.0] SR-9439: Calendar.dateComponetns: Enable .nanoseconds

Foundation/NSOrderedSet.swift, TestFoundation/TestNSOrderedSet.swift
- Add copy() and mutableCopy().
- Add .set and .array to return immumtable views of the current
contents.
- Implement index(of:inSortedRange:options:usingComparator cmp:)
by calling NSArray()'s version on ._orderedStorage.
- Implement description(withLocale:), description(withLocale:indent:),
.description and .customMirror.
- NSCoding still needs to be implemented.
=> NSOrderedSet: Implement more functionality

Foundation/NSError.swift
Right now `POSIXError` is broken on Linux, with Foundation defining `POSIXError.Code` that is valid for Darwin, not Linux.
=> Fixed `POSIXError.Code` for Linux

TestFoundation/TestTimeZone.swift
Bridge the return CFString object to NSObject via the private
`_nsObject` and use the `length` property to get the length rather than
using the `CFStringGetLength` method in the tests.  This reduces the use
of CoreFoundation private interfaces in the tests, which is needed for
Windows.
=> test: use bridging rather than CoreFoundation

TestFoundation/TestNSString.swift
Rather than use CoreFoundation interfaces, use bridging more
aggressively to call the CoreFoundation methods.  This reduces the
dependency on CoreFoundation for the test suite.
=> TestFoundation: use bridging for CFStringGetLength

Foundation/DateComponentsFormatter.swift, Foundation/DateFormatter.swift, Foundation/DateIntervalFormatter.swift, Foundation/EnergyFormatter.swift, Foundation/Formatter.swift, Foundation/LengthFormatter.swift, Foundation/MassFormatter.swift, Foundation/NumberFormatter.swift, Foundation/PersonNameComponentsFormatter.swift
swift-corelibs-foundation’s Formatter subclasses do not have working funnel methods at the moment. Rather than advertise an experimental API that has no implementation, retire the experimental API for now and provide source compatibility stubs that aid in porting code at compile time.
Fixes https://bugs.swift.org/browse/SR-10353, https://bugs.swift.org/browse/SR-10354
=> Parity: objectValue(…)

Foundation/NSError.swift
These are not available on Windows, do not use them.
=> Foundation: remove a number of non-portable POSIX codes

Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundation.xcscheme, Foundation/NSString.swift
See https://github.com/apple/swift-corelibs-foundation/pull/1928
=> [5.0] Cherry-pick: Speedup for NSString -getCharacters:range

TestFoundation/TestOperationQueue.swift
`sleep` is not portable; use `Thread.sleep(forTimeInterval:)`.
=> TestFoundation: use `Thread.sleep(forTimeInterval:)` rather than `sleep`

TestFoundation/TestFileHandle.swift, TestFoundation/TestProcess.swift, TestFoundation/TestUtils.swift
`mkstemp` is not available on Windows.  Replace the two sites with a
GUID temporary path instead.
=> TestFoundation: remove `mkstemp` usage

cmake/modules/SwiftSupport.cmake
Enable parallel compilation when building Foundation.  We were
previously building Foundation in single threaded mode.  This should
significantly improve builds.
=> build: parallelise build

Foundation/Thread.swift, TestFoundation/TestThread.swift
This adds a missing property that is a available on macOS.
Like the corresponding properties on `Operation` and `Process`, it does nothing. It simply improves source compatibility between operating systems.
This was first mentioned in the forums [here](https://forums.swift.org/t/qualityofservice-for-thread/23359).
=> “qualityOfService” for “Thread”

TestFoundation/TestFileHandle.swift, TestFoundation/TestProcess.swift
A previous change replaced the usage of mkstemp for creating files with
UUID file names, but was missing the unlink call present in the previous
version.
This change will take care of cleaning after the tests and try not to
pile garbage files in the temporary directory.
=> [test] Remove temporary files after test.

Foundation/NSError.swift
Fixes the difference between what NSError on Darwin prints and what we are currently printing.
=> Match Darwin implementation of `NSError.localizedDescription`

Foundation/ProcessInfo.swift
Windows does not support `getpid`.  Add a Windows specific path for
this.  Thanks to Lily Vulcano for pointing out that this was missed.
=> Foundation: port `ProcessInfo.processIdentifier` to Win32

TestFoundation/TestNSArray.swift
This test uses CoreFoundation methods.  However, CoreFoundation is only
available on Darwin and Linux.  Limit the test to those environments
specifically.
=> TestFoundation: limit `test_arrayUsedAsCFArrayInvokesArrayMethods`

CMakeLists.txt
Declare `_DLL` when building TestFoundation to ensure that the system
functions are imported correctly with the proper DLL storage.
=> TestFoundation: add `-D_DLL` to the build

Foundation/FileManager+POSIX.swift, Foundation/FileManager+Win32.swift, Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Implement in terms of canonicalized paths.
=> Parity: FileManager.getRelationship(…)

TestFoundation/TestNSString.swift
In Android, the home directory is the root directory. Foundation returns
the right one, but the tests where checking against having a final
trailing slash, which is not true if the home directory is the root
directory.
The change adds an extra check to avoid the failure in case the
resulting tilde expansion is just the root directory. The comment
explains why the change is needed.
Additionally, instead of using `+` to add two strings,
`appendingPathComponent` is used to build an expected value from the
result of `NSHomeDirectory()`, in order to deal with cases where the
`NSHomeDirectory()` has a trailing slash.
=> [android] Fix tilde/home directory tests.

Foundation/NSError.swift
Add missing error messages for known CocoaError codes.
Generated from [playground](https://gist.github.com/colemancda/9f80ff08505d96821380c0b74622e58c) on macOS 10.14.4
=> Added `CocoaError` messages

CMakeLists.txt
Enable optimizations also for RelWithDebInfo builds.
=> [foundation] RelWithDebInfo should build the same as Release.

Foundation/ProcessInfo.swift, TestFoundation/TestBundle.swift
Add the `_processPath` computed property on `ProcessInfo` to allow the
tests to access `_CFProcessPath`.  This removes the last CoreFoundation
API usage in the test suite, allowing it to build on Windows which does
not provide the CoreFoundation APIs to users.
=> Foundation: add ProcessInfo SPI for tests

Foundation/Data.swift
`_withStackOrHeapBuffer` is used in multiple functions in Data which are
marked as `@inlineable`.  Since `_withStackOrHeapBuffer` is inlined into
the body, this results in the users getting references to
`_CFThreadIsMain` which is SPI in CoreFoundation for Foundation.
Furthermore, since the CoreFoundation interfaces are not exported from
Foundation, we cannot fulfill the dependency.  Create a wrapper over
`_withStackOrHeapBuffer` to allow the dependency to be contained.
=> Foundation: wrap `_withStackOrHeapBuffer`

TestFoundation/TestNSNumber.swift
- Remove tests checking the NSNumber integer values of Float.nan and
Double.nan. These values are CPU dependant and not really useful and
only .isNaN needs to be tested anyway.
=> SR-10435: test_numberWithFloat / test_numberWithDouble` failing on AArch64

Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- Override _NSCopyOnWriteCalendar._cfObject to return the backingCalendar created
from CFCalendarCopyCurrent().
(cherry picked from commit e8c5f7a9bf3518415fdc5ce6cc5085fc82cd229e)
=> [5.0] SR-10333: Calendar.current.dateComponents([.weekday], from: Date()).weekday segfaults

TestFoundation/TestURL.swift, TestFoundation/Utilities.swift, TestFoundation/main.swift
The catches _are_ exhaustive, and the cast to `NSError` will never fail, but since it is `SwiftFoundation.NSError` (and not ObjC `NSError`) the macOS build cannot detect that; at least, that's my hypothesis. Fix trivially by catching all errors instead.
=> Build Fix: TestURL

Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
- date(from:) was setting the timezone before calling
_CFCalendarComposeAbsoluteTimeV() but was not restoring it afterwards.
=> SR-10515: Calendar.date(from:) unexpectedly mutates Calendar instance

Foundation/NSTimeZone.swift, TestFoundation/TestTimeZone.swift
- Check the result of CFTimeZoneGetNextDaylightSavingTimeTransition()
as 0 indicates no time transition will occur.
=> SR-10516: TimeZone.nextDaylightSavingTimeTransition does not return nil

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
- Decimal: Add support for the Locale in init(string:locale:)
- Update the Decimal scanner to match the Scanner helper functions.
- Add tests for compatibility with Darwin.
=> SR-10525: Decimal(string:locale:) different results macOS vs Linux

CMakeLists.txt, CoreFoundation/CMakeLists.txt
If CoreFoundation is built statically, the resources will be dropped.
Instead, create an OBJECT library for CoreFoundationResources for the
Windows target.  This allows the resources to be incorporated into an
external consumer of CoreFoundation (i.e. Foundation).  This corrects
the resources handling for the timezone tests.
=> Foundation/CoreFoundation: correctly link resources

TestFoundation/TestURL.swift, TestFoundation/main.swift
- Ensure that the temporary directory has a unique name per run.
- Fix error checking in `setup_test_paths()`
=> Un-XFAIL TestURL

Foundation/FileManager+Win32.swift, Foundation/FileManager.swift
- Reparse points should be checked to ensure they are actually symlinks
- A regular file may not have FILE_ATTRIBUTE_REGULAR set. It may have
alternative attributes like FILE_ATTRIBUTE_ARCHIVE or
FILE_ATTRIUBTE_HIDDDEN and should still count as a regular file.
=> [Windows] Modify What Counts as a Regular File

Foundation/FileManager.swift, Foundation/HTTPCookie.swift, Foundation/NSAttributedString.swift, Foundation/NSCalendar.swift, Foundation/NSDecimalNumber.swift, Foundation/NSLocale.swift, Foundation/NSNotification.swift, Foundation/NSString.swift, Foundation/NSURL.swift, Foundation/Progress.swift, Foundation/Stream.swift, Foundation/StringEncodings.swift, TestFoundation/TestNSCache.swift
This implements @millenomi's review note in https://github.com/apple/swift-corelibs-foundation/pull/2118#discussion_r275510020.
Remove explicit definitions for == and `hash(into:)` from Foundation's enum-like RawRepresentable types. The stdlib provides identical definitions in conditional extensions of RawRepresentable.
Note: This would be an ABI-breaking change in Darwin's Foundation overlays because it removes these symbols; but it seems a reasonable simplification for corelibs-foundation, where AFAIK we don't have to be compatible with Swift 5's ABI.
Note also that RawRepresentable's definitions are inlinable, while the original definitions weren't. The corresponding definitions on Darwin are already inlinable, so this is unlikely to cause *new* issues.
=> Remove explicit ==, hashing definitions from RawRepresentable types

CMakeLists.txt
Windows requires explicitly setting up the C library that you link
against and the flags for building against it as they share the same set
of headers.  Replicate the behaviour of the C frontend for the build to
ensure that we link against the symbols properly and use the correct
library at link time.
=> build: replicate `/M{T,D}{,d}` flag support

TestFoundation/TestNumberFormatter.swift
The original commit doesn't state why the test in particular was
disabled, but in my tests (AArch64), the test seems to work.
/cc @johnno1962
=> [android] Enable NumberFormatter test that actually works on Android.

TestFoundation/TestNSLocale.swift
Maybe the test was disabled because ICU wasn't available then, but
currently the test simply works.
This should not affect Darwin or Linux in any way.
=> [android] Enable locale test which actually works on Android.

Foundation/FileManager+Win32.swift, Foundation/FileManager.swift
I was a terrible, awful person in https://github.com/apple/swift-corelibs-foundation/pull/2164 and didn't cleanup my handles.
I also found another one while trying to figure out why calling things twice failed the second time.
=> Ensure an unclosed handle gets closed

Foundation/FileHandle.swift
Remove the NSSecureCoding conformance with a rationale comment.
=> Parity: NSCoding: FileHandle

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Implement displayName(atPath:) insofar as is possible in a cross-platform manner, and componentsToDisplay(forPath:) as a function of that.
=> Parity: FileManager: File display names.

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Glibc >= 2.28 provides statx() as a wrapper for the kernel syscall
(added in Linux 4.11) which conflicts with the kernel headers. This
allows compilation on systems which provide a recent glibc
(Fedora 30 etc).
=> [SR-10086] Use glibc-provided statx() wrapper if available

Foundation/JSONEncoder.swift, TestFoundation/TestJSONEncoder.swift
Using `keyEncodingStrategy` or `keyDecodingStrategy`, there is a difference of key name case between platforms.
|| Darwin | Linux |
|:-:|:-:|:-:|
| Encode | `"camelCase"` -> `"camelCase"` | `"camelCase"` -> `"camel_case"`|
| Decode | `"snake_case"` -> `"snake_case"` | `"snake_case"` -> `"snakeCase"`|
To sync this behavior to be same as Darwin, I just imported this PR changes https://github.com/apple/swift/pull/16238
=> Sync key coding behavior from Darwin

Foundation/NSStringAPI.swift
Currently, str.data(using:allowLossyConversion:) always bridges via
NSString.
As String is now natively UTF-8 we can fastpath this conversion in the
case where the user requests UTF-8 encoding.
Port of apple/swift@a6fbc40 from the overlay.
=> NSStringAPI: perf: UTF8 String -> Data

Foundation/HTTPCookieStorage.swift
Removed access to `sharedStorage` through `sharedSyncQ` because the static constants are initialized lazily and in a thread-safe.
=> HTTPCookieStorage: rewrite access to shared storage

CoreFoundation/NumberDate.subproj/CFTimeZone.c
To allow easier adoption of the Android code, this duplicated piece of
code is moved into its own function, since it will need to change
significantly for Android.
As requested in #2168.
=> Move duplicated code into its own function.

Foundation/URLSession/URLSessionTask.swift
The current code in ```URLSessionTask.urlProtocolDidFinishLoading```   casts ```URLResponse``` to ```HTTPURLResponse```. and fails with ```FatatlError``` if the response is not cast-able to ```HTTURLResponse```
=> Crash in URLSessionTask while handling non HTTPURLResponse

Foundation/FileHandle.swift, Foundation/FileManager+Win32.swift, Foundation/FileManager.swift, Foundation/Host.swift, Foundation/NSLock.swift, Foundation/NSPathUtilities.swift, Foundation/Process.swift, Foundation/Thread.swift, TestFoundation/HTTPServer.swift
Now that `BOOL` is bridged to `WindowsBOOL` and `Bool`, clean up the
instances of `BOOL` values since they will no longer be available.
=> Foundation: update for `BOOL` bridging

CoreFoundation/Locale.subproj/CFDateFormatter.c, TestFoundation/TestDateFormatter.swift
DateFormatter with Japanese calendar does not parse Japanese era name and years correctly on Linux environment.
This changes fix it and adds small tests related to Japanese calendar for DateFormatter.
=> DateFormatter: Fix date string parse with Japanese calendar

Foundation/NSStringAPI.swift
Currently, str.data(using:allowLossyConversion:) always bridges via
NSString.
As String is now natively UTF-8 we can fastpath this conversion in the
case where the user requests UTF-8 encoding.
Port of
https://github.com/apple/swift/commit/a6fbc40e761f106cae7192288d920a17c7351669
from the overlay.
Backport of https://github.com/apple/swift-corelibs-foundation/commit/7704c94c212e76db4db1a718268e64c171a5e788.
=> [5.0] NSStringAPI: perf: UTF8 String -> Data

Foundation/NSURLRequest.swift, TestFoundation/TestURLRequest.swift
- URLRequest.init(url:cachePolicy:timeoutInterval:): Assign the absolute
URL to .url
=> SR-9900: NSURLRequest .url differs between Darwin and Linux for relative URLs

Foundation/XMLElement.swift, TestFoundation/TestXMLDocument.swift
According to [the document of Darwin Foundation](https://developer.apple.com/documentation/foundation/xmlelement/1388336-addattribute)  of `XMLElement.addAttribute(_:)`,
> If the receiver already has an attribute with the same name, `anAttribute` replaces the old attribute.
and actually it replaces the old attribute on Darwin.
However in swift-corelibs-foundation, `addAttribute(_:)` do nothing when the attribute with the same name exists.
This patch fixes the behavior and improves compatibility with Darwin Foundation.
=> Fix: existing attributes are not replaced

TestFoundation/TestNSNumber.swift
Fixes SR-7469.
Seems that the explicit castings are not longer needed in the current
tree compiling for Android.
=> [android] Removing explicit castings for unsigned integers.

CoreFoundation/NumberDate.subproj/CFTimeZone.c
We would release a value obtained through a `CFDictionaryGetValue` which
would result in the value being over-released as the returned object is
returned at `+0`.  This fixes the use-after-free on Windows.
Thanks to Gwynne Raskind for identifying the mismanagement of the retain
counts!
=> CoreFoundation: correct an over-release in `CFTimeZone`

Foundation/FileManager+Win32.swift
This removes the attribute on a function which is now implemented.
=> Foundation: remove stale NYI

Foundation/FileManager+Win32.swift
The path being removed may not exist.  Permit the `attributes(of:)` to
fail and propagate the exception.
=> Foundation: allow failure in attribute query

CoreFoundation/NumberDate.subproj/CFTimeZone.c
Use `CFDataCreateWithBytesNoCopy` to avoid the memory copy for the
construction of the `CFData`.
Thanks to Gwynne Raskind for educating me on the fact that
`CFDataCreate` will actually perform a copy which I was trying to avoid.
=> CoreFoundation: optimize TimeZone PLIST loading on Windows

CoreFoundation/NumberDate.subproj/CFTimeZone.c
It is in theory possible to hit a race condition with the CFTimeZone
PLIST loading as there was a small window where the object was accessed
unsynchronised.  Although unlikely, protect against it anyways.
Thread A                               | Thread B
CFTimeZoneCopyWinToOlsonDictionary()   |
Lock                                 |
__CFTimeZoneWinToOlsonDict != NULL |
Unlock                               |
|   CFTimeZoneSetWinToOlsonDictionary()
|     Lock
|       retain new dictionary
|       release old dictionary
retains "old" (invalid) dictionary   |
|       swap
|     Unlock
=> CoreFoundation: fix a rare, possible race on Windows

Foundation/NSDictionary.swift, TestFoundation/TestNSDictionary.swift
Shim these out for this release. This technically obeys all parts of the contract, modulo obviously the performance increase.
Fixes https://bugs.swift.org/browse/SR-10397
=> Parity: NSDictionary: Shared key sets

Foundation/FileManager+POSIX.swift, Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Many tests were disabled in Android, but they actually work without
almost changes.
- Android uses /proc/mounts as Linux. Enabling that code path gives good
results in Android.
- `attributesOfFileSystem` works on Android once glibc.modulemap
includes the right headers (see apple/swift#24286).
- However, since Process is still not available in Android, the test
that relies on xdgTestHelper tool will not work, and have been
disabled (but instead of causing the test to fail, they are simply not
run in Android, which probably will never conform to XDG).
=> [android] Enable tests for FileManager in Android.

Foundation/FileManager+Win32.swift, Foundation/Host.swift
Replace unsafe mutable pointer allocations for strings, opting to use
arrays.  This avoids unnecessary raw malloc/free handling.
=> Foundation: avoid unsafe allocations

TestFoundation/TestNSString.swift, TestFoundation/TestURL.swift
In some cases in the tests, even if an API returns an optional, we know
that it should never be optional, and it might create warnings in later
code when the optional is interpolated into a string (for example).
Change those cases into using `.unwrapped()` to get a non-optional type,
and create a big error if a nil is actually received.
This should remove a bunch of warnings while compiling the tests.
=> [gardening] Remove some optional usage from the tests.

TestFoundation/TestIndexPath.swift, TestFoundation/TestNSData.swift, TestFoundation/TestStream.swift
The mutability is not necessary in any of these cases, according to the
compiler.
Should remove a lot of warnings while compiling the tests.
=> [gardening] Switch non mutated vars into lets.

Foundation/FileManager+POSIX.swift, Foundation/FileManager+Win32.swift, Foundation/FileManager.swift, Foundation/NSURL.swift
Windows should use `SetFileTime` for adjusting the file times.  More
importantly, it does not support `time_t` so the signature of the POSIX
functions are different.  Factor out the file time adjustment into a
helper that is implemented in the POSIX/Win32 layer and use that
instead.
=> Foundation: make FileManager build on Windows again

TestFoundation/TestNotificationQueue.swift
The compiler was warning about this assign to a weak variable, where the
value was going to be released immediately. Modify the code to hold the
value in a strong variable during the block to avoid the warning (and
probably a failing test).
This test is actually disabled, so nothing should change.
=> [gardening] Fix assign to a weak variable releasing immediately.

TestFoundation/HTTPServer.swift, TestFoundation/TestJSONSerialization.swift, TestFoundation/TestNSData.swift, TestFoundation/TestNSString.swift
The old signature for withUnsafeBytes/withUnsafeMutableBytes is
deprecated but it is used in the tests. Remove all the usages of the
deprecated signature and use the newer signature instead.
Should remove a lot of deprecation warnings while compiling the tests.
=> [gardening] Replace usages of deprecated withUnsafeBytes.

Foundation/FileManager+POSIX.swift
`fts_read` calls `stat` internally to determine the type of each file that is visited. If `URL(fileURLWithPath:)` is called with a path that doesn't end with a slash, it calls `stat` to determine whether the path represents a file or a directory. The `FTSENT`'s `fts_info` field tells us whether the entry represents a file or a directory, so we can instead use `URL(fileURLWithPath:isDirectory:)` and avoid the second `stat`.
Additionally, the `FTS_NOSTAT` flag indicates to `fts_read` that the caller is not interested in the `fts_statp` field of the `FTSENT` structure, allowing `fts_read` to skip calling `stat` in some circumstances.
These two changes reduce the runtime of `FileManager.enumerator(at:includingPropertiesForKeys:options:errorHandler:)` by around 55%.
=> Avoid unnecessary calls to stat within NSURLDirectoryEnumerator

CoreFoundation/String.subproj/CFString.c
- Use a variable of type long long variable not int64_t as they may be
different sizes.
- Fixes "warning: incompatible pointer types passing 'int64_t *' (aka 'long *')
to parameter of type 'long long *' [-Wincompatible-pointer-types]"
=> Fix __builtin_{smulll,saddll}_overflow() usage

Foundation/FileManager+Win32.swift
- Get the fsr of the passed in path before using it
- Add the correct path to the directory stack
=> [Windows] Fix FileManager.removeItem

Foundation/FileManager+Win32.swift
- Don't error out if the target doesn't exist
- Check the correct path when determining if it's a directory
=> [Windows] Fix Symbolic Link Creation

TestFoundation/TestNSData.swift
In order to delete a directory on Windows, all handles to its children must be
closed.
=> Fix TestNSData on Windows

CMakeLists.txt, Foundation/Process.swift, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift
- If .standardInput, .standardOutput or .standardError are set to
FileHandle.nullDevice then dup the filedescriptor to '/dev/null'.
Fixes https://bugs.swift.org/browse/SR-10564 and https://bugs.swift.org/browse/SR-10566
=> SR-10565: Process crashes when setting standardOutput = FileHandle.nullDevice

Foundation/Process.swift
Rather than use `inet_pton` which cannot be used inline to initialise
the SOCKADDR, initialise the octets manually.  This should correct the
type constructor.
=> Foundation: expand out `inet_pton`

TestFoundation/xdgTestHelper/main.swift
Windows does not have `kill` but it does have `TerminateProcess`.  This
utility is poorly named at this point and is used as a test helper
utility rather than XDG helper specifically.
=> TestFoundation: make xdgTestHelper build on Windows

Foundation/DateFormatter.swift, TestFoundation/TestDateFormatter.swift
- Ensure the setting of .dateStyle and .timeStyle isnt dependant on the
current setting of .locale.
=> SR-10619: Order in which DateFormatter settings are set up matters on Linux

Foundation/Process.swift
The socket should be set to be non blocking _after_ we attempt to
connect to it.
=> [Windows] Fix socket creation in Process.swift

CMakeLists.txt, CoreFoundation/Base.subproj/CFUtilities.c, CoreFoundation/CMakeLists.txt
- On Linux, use sched_getaffinity() falling back to
sysconf(_SC_NPROCESSORS_ONLN) as this should provide a better
value for ProcessInfo.activeProcessorCount when running under
cgroups (eg Docker).
Not sure if this is the best solution and will need an offline test in a Docker environment.
=> SR-10611: ProcessInfo.activeProcessorCount too high in containerised Linux

TestFoundation/TestProcess.swift
Failure is blocking 5.0 CI.
https://bugs.swift.org/browse/SR-10640
=> [5.0] XFAIL TestProcess.test_passthrough_environment()

Foundation/NSGeometry.swift
This fixes an issue in NSGeometry on 32bit platforms selecting the `(x: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat)` overload, that will just cast a `CGFloat::NativeType` to, again, a `CGFloat::NativeType`, platform dependent (either Float or Double).
The error I'm getting right now:
```
/mnt/buildSwiftOnARM/swift-corelibs-foundation/Foundation/NSGeometry.swift:689:12: error: cannot invoke initializer for type 'NSRect' with an argument list of type '(x: Float, y: Float, width: Float, height: Float)'
return NSRect(x: x, y: y, width: w, height: h)
^
/mnt/buildSwiftOnARM/swift-corelibs-foundation/Foundation/NSGeometry.swift:689:12: note: overloads for 'NSRect' exist with these partially matching parameter lists: (x: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat), (x: Double, …
```
=> Fix NSRect init invocation on 32bit platforms

TestFoundation/TestFileManager.swift, TestFoundation/Utilities.swift
The FileManager implementation currently does not provide some
attributes.  Disable the tests on Windows.
=> TestFoundation: disable a couple of FileManager tests on Win32

Foundation/FileHandle.swift
Since getting an fd from a handle transfers ownership, we duplicate the
handle before getting an fd from it.
=> Duplicate the Handle instead of the fd on Windows

TestFoundation/TestPipe.swift
Windows does not provide `fileDescriptor` for file handles as it uses
HANDLEs underneath and it is not possible to provide a non-owning file
descriptor value.  Make this contingent on testable imports and use the
internal `_isPlatformHandleValid` method to check instead.
=> TestFoundation: make TestPipe pass on Windows

Foundation/Host.swift
Rewrite the host address resolution to be easier to follow.  The old
path obfuscated pointers to the point where the invalid memory access
could not be found (probably due to the incorrect handling with the
unsafe pointer).  This now passes the Host tests.
=> Foundation: tweak address resolution on Windows

TestFoundation/TestNSKeyedArchiver.swift
No allocation was made to perform the explicit deallocation.  Doing so
causes a double free which the Windows C library caught.
=> TestFoundation: fix a double free

TestFoundation/TestNSKeyedArchiver.swift
Extend the lifetime of the `NSValue` object as we retrieve a pointer to
the data owned by it.  Since the data is owned by the `NSValue`
instance, we need to ensure that the `NSValue` has its lifetime extended
throughout the usage.
=> TestFoundation: ensure that `NSValue` is preserved

TestFoundation/TestFileHandle.swift
This adjusts the fileDescriptor test to be more portable so that we can
run it on Windows.
=> TestFoundation: make `test_fileDescriptor` more portable

CMakeLists.txt, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Collections.subproj/CFArray.c, Foundation.xcodeproj/project.pbxproj, Foundation/NSArray.swift, Foundation/NSCFArray.swift, Foundation/NSDate.swift, Foundation/NSIndexPath.swift, Foundation/NSOrderedSet.swift, Foundation/NSSet.swift, Foundation/NSSortDescriptor.swift, Foundation/NSSwiftRuntime.swift, TestFoundation/TestNSSortDescriptor.swift, TestFoundation/main.swift
- Implement the parts that can be implemented and annotate the rest with diagnostics.
- Add a partially source-compatible version of `init(keyPath:ascending:)` that works with Comparable values.
- A limited set of Cocoa model classes (the ones that have a `compare(_:)` method) now conforms to Comparable and can be used with the source-compatible initializer.
- Implement the sort methods that take sort descriptors on the collection classes.
- Add `_SwiftBridgeable`  protocol conformance to a couple classes that had it missing.
- Fix `_CFSwiftArrayReplaceValues` to actually work, and ensure `CFArraySort()` can detect that the array is actually mutable.
- Ensure that `NSOrderedSet` invokes `__SwiftValue`’s fetching setup instead of returning internal storage.
=> Parity: NSSortDescriptor & _CFSwiftArrayReplaceValues

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/CMakeLists.txt, CoreFoundation/String.subproj/CFCharacterSet.c, Foundation/NSCharacterSet.swift, TestFoundation/FixtureValues.swift, TestFoundation/TestCharacterSet.swift
- Split initialization for CFCharacterSet so we can use it in init?(coder:)
- Make CFCharacterSetPriv.h available to Swift so we can use its helpers to encode and decode as we do on Darwin.
=> Parity: NSCoding: NSCharacterSet

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/PlugIn.subproj/CFBundle_Binary.c, Foundation/Bundle.swift, TestFoundation/TestBundle.swift, TestFoundation/Utilities.swift
- Use dladdr() with a symbol guaranteed to be in the source image of the class.
- We cannot replace the Bundle object init() returns, but we can implement equality correctly so that at least `==` can compare bundles correctly if they refer to the same CFBundle.
- Add testExpectedToFailOnWindows() and associated infrastructure.
=> Parity: Bundle(for: AnyClass)

Foundation/URLSession/URLSessionTask.swift, TestFoundation/TestURLSession.swift
The basic authentication implementation fails a URLSessionTask with an error if
a status code of 401 is received but we aren't able to build a
URLProtectionSpace, possibly due to the absence of a the WWW-Authenticate
response header. A valid HTTP response object is received in this case. It may
not possible to go ahead with the `urlSession(_,task: task, didReceive:)`
callback, either because a delegate isn't being used or because the
`WWW-Authenticate` response header is absent. In such cases, the completion
handler is invoked with the received response, NOT with an error.
Note that basic authentication (https://github.com/apple/swift-corelibs-foundation/commit/4c1e8c4) wasn't available with Swift 4.x. It was first made available in development builds for Swift 5.
Initially, when we …
=> [SR-10602]Don't fail a URLSessionTask on a 401 response

TestFoundation/Utilities.swift
It’s blocking PR testing on the 4/24 branch, which doesn’t appear to have the feature.
=> [5.1] Add back some elided returns

Foundation/Thread.swift
We were computing the duration incorrectly, using the time since the
Cocoa epoch rather than now resulting in what appeared to be an infinite
sleep.  Correct the duration which is relative to *now* in 100ns
intervals.  This allows the NSLock tests to succeed.
=> Foundation: correct `Thread.sleep(until:)` on Windows

Foundation/HTTPCookieStorage.swift, Foundation/URLSession/URLSessionConfiguration.swift, TestFoundation/TestURLSession.swift
The difference between `default` and `ephemeral` `URLSessionConfiguration`s
is in the storage aspect. There are three kinds of stores related to a `URLSession`
- a `URLCache`
- a `URLCredentialStorage`
- an `HTTPCookieStorage`
While the `default` configuration mandates persistent stores, the `ephemeral`
configuration mandates only in-memory, ephemeral stores. As of today, `URLCache`
and `URLCredentialStorage` are unimplemented and not configured in the `default`
configuration. `HTTPCookieStorage` is implemented and we use the `shared` storage
in the `default` configuration.
This commit includes:
- an ephemeral `HTTPCookieStorage` that does not read from, and write to, a persistent
store
- an initial `URLSessionConfiguration.ephemeral` implementation which configures an
ephmeral …
=> Implement URLSessionConfiguration.ephemeral

CoreFoundation/Base.subproj/CFSystemDirectories.c
Fold `TARGET_OS_OSX || TARGET_OS_IPHONE` to `TARGET_OS_MAC`.
=> CoreFoundation: simplify target computation

CMakeLists.txt
When building Foundation, ensure that we build CoreFoundationResources
as we need to incorporate the build artifacts.
=> build: correct dependencies for Windows

TestFoundation/TestFileHandle.swift
This test seems to sometimes fail, which can make it hang forever. Give it a still-generous-but-not-infinite timeout so it at least fails gracefully when it fails.
Fixes [SR-10680](https://bugs.swift.org/browse/SR-10680) and rdar://problem/50735595.
=> Place a time limit on TestFileHandle.test_readWriteHandlers()

CoreFoundation/Base.subproj/CFInternal.h, CoreFoundation/Base.subproj/CFLocking.h, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, Foundation/NSLocale.swift
`NSLocale` is toll-free bridged to `CFLocale`.  The types must match.
On many targets, the backing store for `_lock` was being elided as the
value was conditionally defined.
Extract the locking macros/types into a `CFLocking.h` and then include
that into `CFInternal.h` and `ForSwiftFoundationOnly.h`.  This allows
the underlying type information to be shared into Swift permitting the
`__CFLocale` type to be reconstructed without guessing as to the
underlying type.
This repairs the bridging of `NSLocale` on Windows and allows us to get
further in the test suite.
=> Foundation/CoreFoundation: repair bridging for `NSLocale`

Foundation/FileHandle.swift, Foundation/Process.swift
Correct the Windows error domain and modernise some code.
=> Improve Windows error handling

Foundation/Process.swift
Adjust the Windows environment creation to ensure that we properly form
the string that represents the child's environment.
=> Process: correct environment block handling on Windows

TestFoundation/TestProcess.swift
When debugging the process tests on Windows, the failure to
`Process.launch` would silently be ignored.  The tests do not expect the
`launch()` call to fail so ensure that the child process is launched.
This ensures that we get a proper indication of the failure.
=> TestFoundation: force `process.run()` to succeed

Foundation/URLSession/URLSessionTask.swift, TestFoundation/TestURLSession.swift
Cherry-picked from master, for inclusion in 5.0.2
Original MR description:
--
The basic authentication implementation fails a URLSessionTask with an error if
a status code of 401 is received but we aren't able to build a
URLProtectionSpace, possibly due to the absence of a the WWW-Authenticate
response header. A valid HTTP response object is received in this case. It may
not possible to go ahead with the `urlSession(_,task: task, didReceive:)`
callback, either because a delegate isn't being used or because the
`WWW-Authenticate` response header is absent. In such cases, the completion
handler is invoked with the received response, NOT with an error.
Note that basic authentication
(https://github.com/apple/swift-corelibs-foundation/commit/4c1e8c4271c4e21000528 …
=> Don't fail a URLSessionTask on a 401 response

Foundation/FileHandle.swift
Ensure that we check the handle type before querying the file
information.  It is not permissible to invoke that with a handle to a
pipe.
=> Foundation: avoid `GetFileInformationByHandle` on a pipe

Foundation/Process.swift
Do not close both sides of the pipe.  The pipes are half-duplex and the
parent side of the pipe need to be valid to permit communication with
the child.
=> Foundation: fix `Process.run()` handle handling for Windows

TestFoundation/Utilities.swift
You can now define tests as follows:
```
func testCrashes() {
assertCrashes {
fatalError()
}
}
```
These tests will spawn a child process and will assert that the child process crashes while executing the code in the block. Wrap the entire body of the test this way.
=> TestFoundation: Add infrastructure to assert that a test should crash

Foundation/NSLock.swift
Looks like timeout condition variable and corresponding mutex are not initialized in `RSMRecursiveLock` implementation. Noticed random but often crashes in our test code. Best reproduced with nested lock/unlock calls
```
let lock1 = NSRecursiveLock()
let lock2 = NSRecursiveLock()
lock1.lock()
lock2.lock()
lock2.unlock() // <- crash or hang here
```
Not sure if there is no additional issues though, still getting very rare crashes. But success rate changed from, like, "1 success per 100 failures" to "1 failure per 100 success runs".
=> [windows] NSRecursiveLock: missing initialization of mutex/condition variable

TestFoundation/FTPServer.swift, TestFoundation/TestURLSessionFTP.swift, TestFoundation/main.swift
The FTP Server is not well structured to make it easy to port to
Windows.  Simply excise all of the FTPServer for the time being until it
can be restructured to support cross-platform networking.
=> TestFoundation: excise FTPServer

CoreFoundation/Base.subproj/CFSortFunctions.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/NSArray.swift
Replace the approximate implementation with one that matches Darwin’s and supports all the options by using CFSortIndexes from NSArray.swift.
=> Parity: NSArray.sortedArray(…)

Foundation/NSComparisonPredicate.swift, Foundation/NSCompoundPredicate.swift, Foundation/NSExpression.swift, Foundation/NSPredicate.swift, TestFoundation/TestNSPredicate.swift
- Add diagnostics for features not supported by swift-corelibs-foundation, including format strings (which rely on key-value coding for most of their usefulness).
- `NSComparisonPredicate` relies on `NSExpression`, which is not going to be available. Mark it as unavailable.
- Predicate archival relies on format strings. Remove the `NSSecureCoding` conformance of `NSPredicate`, since we cannot safely assert to be able to encode or decode arbitrary predicates.
=> Parity: NSPredicate and NSExpression

TestFoundation/TestFileHandle.swift
It times out occasionally in CI. rdar://problem/50860781
=> Temporarily mark test_readWriteHandlers test as expected to fail

CoreFoundation/NumberDate.subproj/CFTimeZone.c, Foundation/NSTimeZone.swift, TestFoundation/TestCodable.swift, TestFoundation/TestISO8601DateFormatter.swift, TestFoundation/TestTimeZone.swift
The time zone database in Android sits in a non-standard place, and it
can be overriden by a second location. Besides not sitting in a standard
place, it differs from other Unixes in that the database is bundled into
one binary file, and there are no folders with small files for each time
zone. Luckily the database is generated from Olson, so most of the
CFTimeZone code already handles the details.
The code implements a generic enumeration of the time zones contained in
the database (checking for both the override and the standard location).
The enumeration code is used for both enumerating the known time zones,
as well as creating time zones by name.
At many points there was code blocking the usage of time zones in
Android that has been removed.
This allows the tests in …
=> [android] Support for time zones in Android.

CMakeLists.txt
We no longer use `ExternalProject` to build CoreFoundation and opt to
use `add_subdirectory` for it to get better dependency resolution.
Remove the vestigial include.
=> build: remove unnecessary CMake include

CMakeLists.txt
This sets up the build to link via the new `-libc` option so that we get
the correct MSVC runtime library.
=> build: use the new `-libc` option

TestFoundation/TestFileHandle.swift
This makes test_nullDevice more portable so that we can run the test
on Windows as well.
=> TestFoundation: make `test_nullDevice` test more portable

Foundation/NSURL.swift, Foundation/URL.swift
Windows uses wide paths (UTF16).  Expose a similar internal API to the
CoreFoundation interfaces to aid in writing code locally and avoid
having to do the unicode conversions everywhere.
=> Foundation: add an extension to deal with Win paths

Foundation/NSLock.swift, TestFoundation/TestNSLock.swift
I was going to suggest a test for NSRecursiveLock fix in #2269, as promised. But test turned out extremely useful from first run. Found that pthread-based implementation is also missing some initialization.
I suppose it will be ok to add this new fix and test in one PR, right?
=> Initialize pthread mutexes in NSRecursiveLock

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
`interface` is a problematic name on Windows where the Windows headers
will replace it with `struct` with preprocessors which break parsing of
the header.  Remove the names as they are not needed, but leave them as
comments for documentation.
=> CoreFoundation: remove names in function pointer (NFC)

CoreFoundation/URL.subproj/CFURLSessionInterface.c, CoreFoundation/URL.subproj/CFURLSessionInterface.h
The socket type on Windows is `SOCKET`, not `int`.  This was mismatched
with CURL.
The timeout value is an alias for invalid socket which is of type
`SOCKET` not `int`.  Adjust the type accordingly and plumb it through.
=> CoreFoundation: make CFURLSessionInterface Win32 friendly

CMakeLists.txt, CoreFoundation/Base.subproj/CoreFoundation_Prefix.h, CoreFoundation/CMakeLists.txt
Clean up the libdispatch handling in CoreFoundation.  All deployments of CoreFoundation have libdispatch and CoreFoundation has required libdispatch for some time now.  Now that libdispatch is available on all the deployments even under the swift deployment, remove the option to disable libdispatch portions.  This enables us to remove the dependency of the prefix header on the `-DDEPLOYMENT_ENABLE_LIBDISPATCH` flag which means that we no longer need to pass that as a CFLAG to the clang importer when building Foundation.  This also reduces the complexity in the build of CoreFoundation.
As a result of the flag no longer being needed by the clang importer, we can now simplify the build rules for Foundation, passing the `DEPLOYMENT_ENABLE_LIBDISPATCH` flag to exactly the location that needs …
=> Clean up libdispatch handling for CoreFoundation/Foundation

TestFoundation/TestFileHandle.swift
Writing to a pipe can block if an internal buffer fills up, and the size of the buffer varies by platform and even kernel version, which may be causing the `TestFileHandle.testWritingWith*()` tests to hang. Address this by ~~writing from a background queue and imposing a timeout on the write~~ writing to a temporary file and then reading it back.
=> Prevent pipe-based FileHandle tests from hanging

TestFoundation/TestDateInterval.swift
Adds some functionality tests for the DateInterval interface.
* This is my first pull request to this project, so let me know if there are any issues!
=> TestFoundation: TestDateInterval: Add tests for functionality

Foundation/NSError.swift
Resolves [SR-4405](https://bugs.swift.org/browse/SR-4405)/rdar://problem/36911792 by adding `@escaping` to `resultHandler`.
[This mirrors apple/swift#16182]
=> RecoverableError's resultHandler needs @escaping

Foundation/DateFormatter.swift
Those are not IUO on Darwin. And also addresses "Treating a forced downcast to '[String]' as optional will never produce 'nil'" warnings.
=> [DateFormatter] Fix symbols property optionality

Foundation/URLSession/URLSessionTask.swift
This property only applies to background session tasks. If it’s being used once it’s made available, it may be in error on Linux. Warn; also ensure that properties are open as they are on Darwin.
Fixes https://bugs.swift.org/browse/SR-10382
=> Parity: URLSessionTask.earliestBeginDate

CoreFoundation/CMakeLists.txt
CoreFoundation's build broke on Windows due to the missing curl headers.
Linux and macOS have the curl headers available and so they did not
notice it.
=> CoreFoundation: repair the build after the URLSessionInterface

Foundation/HTTPCookieStorage.swift
Change the implementation of `HTTPCookieStorage` to use
`FileManager.default.url(for:in:)` instead of the internal
_CFXDGCreateDataHomePath` method.  Now that `HTTPCookieStorage` is moved
off to its own library (FoundationNetworking), it no longer has access
to the internal function.  Use the URL query to get the path to the
storage location.
=> Foundation: change `HTTPCookieStorage` to use `FileManager`

CoreFoundation/CMakeLists.txt
This has been isolated to CFURLInterface, remove the duplicated code.
=> CoreFoundation: remove CFURLSessionInterface from CF

Docs/ReleaseNotes_Swift5.md
Only documentation is changed in this patch.
=> Add release notes for NSCoder and NSSortDescriptor.

Foundation/HTTPCookieStorage.swift, TestFoundation/TestHTTPCookieStorage.swift
Now that NSSortDescriptor is available, just forward to NSArray.sortedArray(…). Test and clean up a little.
=> Parity: Network: HTTPCookieStorage.sortedCookies(using:)

CoreFoundation/URL.subproj/CFURLSessionInterface.c, CoreFoundation/URL.subproj/CFURLSessionInterface.h, Foundation/URLSession/libcurl/MultiHandle.swift
This causes a reference to `CFStringCreateWithBytes` and
`kCFDefaultSystemAllocator` in `CFURLSessionInterface` which requires
linking against CoreFoundation.  Since the swift deployment uses
CoreFoundation statically, this would require a second instance of
CoreFoundation OR that private CoreFoundation interfaces are re-exposed
through Foundation which is explicitly undesired.  Perform the String
construction in Swift and instead just have a trivial wrapper for
`curl_easy_strerror`.
=> CoreFoundation: avoid `CFString` construction in `CFURLSessionINterface`

CoreFoundation/URL.subproj/CFURL.c, Foundation/FileManager+Win32.swift, Foundation/NSPathUtilities.swift, Foundation/NSURL.swift, TestFoundation/TestFileManager.swift
- Windows directory enumerator now doesn't look in a directory it
returns until nextObject is called again
- Fixed some path handling platform issues
- Properly calculate level
See SR-10738
=> Fix Up FileManager Tests on Windows

CMakeLists.txt
- libFoundationNetworking was not being installed into the final output
directory and was missing from the tarfile.
=> build: Install libFoundationNetworking.so as part of the build

Foundation/Thread.swift, TestFoundation/TestThread.swift
Foundation was correctly setting the thread name, but it would only ever
read the name that was stored in the thread object. This meant that if
the thread name was set elsewhere (e.g. by Linux, or by SwiftNIO) that
name would not be reflected in Thread's name property.
=> Foundation: correctly read thread name

Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionConfiguration.swift
Implement reset(…) and flush(…) per their contracts. Note that URLCredentialStorage is unimplemented right now; invoking reset(…) will thus crash if a credentials storage is set.
Ensure that URLSessionConfiguration users do not attempt to use init(), leading to non-portable code.
=> Parity: URLSession.reset(…)/.flush(…)

Foundation/Data.swift, Foundation/DataProtocol.swift
Cherry-pick https://github.com/apple/swift/pull/25065 from the overlay.
=> Fix `DataProtocol.lastRange(of:)` (and cherry-pick Data.swift changes from the overlay)

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager+POSIX.swift, Foundation/FileManager.swift, TestFoundation/TestFileManager.swift, TestFoundation/Utilities.swift
- Instead of returning nothing from .url(for: .itemReplacementDirectory…), produce a path the same way Darwin does.
- Implement replaceItems(…) for POSIX-y platforms. We try to use Darwin and Linux swap syscalls to ensure race-free atomicity if available, and if these fail we fall back to an implementation that has different degrees of atomicity depending on what object is replaced with what object.
- Add tests.
=> Parity: FileManager.replaceItem(…)

CMakeLists.txt
xdgTestHelper was building before FoundationNetworking finished and wasn't finding the import.
=> Added missing cmake dependency on FoundationNetworking

Foundation/NSCalendar.swift, TestFoundation/TestCalendar.swift
Despite `CFDateFormatterCopyProperty(_:_:)` returns `CFArrayRef` when the key is `kCFDateFormatterEraSymbolsKey`, the compiler on Linux assume that the type is `_NSCFArray` and fails to cast even though they are compatible. 
Resolves [SR-10638](https://bugs.swift.org/browse/SR-10638).
Note: This bug is blocking [PR#2200](https://github.com/apple/swift-corelibs-foundation/pull/2200).
=> SR-10638: Change the type of force casting in `NSCalendar`.

CMakeLists.txt, CoreFoundation/URL.subproj/CFURLSessionInterface.c, CoreFoundation/URL.subproj/CFURLSessionInterface.h
Allow FoundationNetworking to find CFURLSessionInterface when imported by third-party code.
=> Functional break fix: import FoundationNetworking

TestFoundation/FTPServer.swift, TestFoundation/TestURLSessionFTP.swift
- Replace CFSwapInt16HostToBig(port) with port.bigEndian and
Remove 'import CoreFoundation'.
- Gate imports of Darwin and Glibc on canImport().
- Remove unnecessary imports.
=> Test FTP Server: Simplify imports

Foundation/XMLNode.swift, TestFoundation/TestXMLDocument.swift
It is unnecessary to encode entities when the node is comment or text. They will be encoded when XML is put out.
Resolves [SR-10759](https://bugs.swift.org/browse/SR-10759).
=> SR-10759: Avoid double encoding in `stringValue` of XMLNode.

Foundation/Operation.swift, Foundation/Thread.swift, TestFoundation/TestOperationQueue.swift
This brings in the new barrier APIs as well as progress reporting to OperationQueue
=> Refactor Operation, and OperationQueue to be closer to the objc implementation

Foundation/FileManager+Win32.swift
unlink on posix ignores if a file is read only since it only needs write
permissions on the parent directory to remove it. To emulate this on
Windows, if a file is read only, unset the read only bit and then remove
it.
=> Force file removal in Windows _removeItem

CoreFoundation/Base.subproj/CFPlatform.c
- Handle the O_CREATE | O_TRUNC case
- Read only should be set if _write_ permissions are not set
=> Fix Flags in NS_open

Foundation/FileManager+Win32.swift
dst is where the link is created, src is what it points to.
=> Fixed order of arguments to CreateHardLinkW

Foundation/NSCoder.swift, TestFoundation/Utilities.swift
- See https://developer.apple.com/documentation/foundation/nscoder/1642984-decodingfailurepolicy
- NSKeyedUnarchiver overrides it to be read-write, but NSKeyedArchiver
does not.
=> NSCoder.decodingFailurePolicy should be read-only.

CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Docs/Status.md, Foundation/XMLElement.swift, Foundation/XMLNode.swift, TestFoundation/TestXMLDocument.swift
Implement `XMLElement.attribute(forLocalName:uri:)`.
Also fix some other incompatibilities between Linux and Darwin about attributes with namespace.
In the added test case, all expected values are actual ones on Darwin (macOS 10.14.4).
=> XML: Add namespace support for XML attributes

Foundation/FoundationErrors.swift
Added some translation to Cocao errors for a number of commonly seen
Windows error codes
=> Translate between Windows Errors and Cocoa Errors

Docs/Testing.md, Tools/GenerateTestFixtures/GenerateTestFixtures.xcodeproj/xcshareddata/xcschemes/GenerateTestFixtures.xcscheme, Tools/GenerateTestFixtures/GenerateTestFixtures/Utilities.swift, Tools/GenerateTestFixtures/GenerateTestFixtures/main.swift
* Copy information critical to producing useful tests from my head onto words on disk. 
* Simplify the instructions for GenerateTestFixtures by making the version strings used match the expectations of the Fixture extensions, and by making the executable default to its current location for output if not specified.
* Remove a path that is local to my machine from the repository.
=> Add extensive testing documentation

CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, Foundation/URLCache.swift, Foundation/URLResponse.swift, TestFoundation/TestCachedURLResponse.swift, TestFoundation/TestURLResponse.swift, TestFoundation/main.swift
Simple implementation for CachedURLResponse. The type seems to mostly be
a data container with little behaviour.
Implement the missing equality and hashing for URLResponse, which is
used by CachedURLResponse.
Implement tests for CachedURLResponse and the missing tests for
equality and hashing in URLResponse.
https://bugs.swift.org/browse/SR-10373
=> Implement CachedURLResponse.

TestFoundation/TestURLSessionFTP.swift
Looks like the same issue as test_ftpDataTask, so marking with the same cause.
https://bugs.swift.org/browse/SR-10922
=> Disable test_ftpDataTaskDelegate crashing occasionally in CI

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
This function from the header was not being used anywhere.
=> Remove unused function.

TestFoundation/FTPServer.swift
In Android the last element of the sockaddr_in struct is actually called
__pad instead of sin_zero, so a special codepath is needed.
/cc @saiHemak
=> [android] Provide implementation for Android Bionic.

Foundation/NSURL.swift
Android has timespec like Linux, so it can use the Linux codepaths just
fine. The proposed code path actually fail because those accessors are
actually macros in the Android sysroot.
=> [android] Use timespec like in Linux for URL c/m/atime.

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Android has the newer syscalls available but the declarations were not
being pulled in.  Add the appropriate handling.
=> Base: include headers appropriately for android

CMakeLists.txt
Use `target_include_directories` rather than `target_compile_options`
This should be entirely equivalent.  NFCI.
=> build: use `target_include_directories` (NFC)

Foundation/FileManager+POSIX.swift, Foundation/FileManager.swift
These seem unnecessary, at least when building android aarch64.
=> Foundation: remove & overload for android

cmake/modules/SwiftSupport.cmake
This mirrors the `CMAKE_SWIFT_FLAGS` allowing control over the flags
passed to the linker.  This is needed until the libraries are built
with a newer CMake which supports Swift properly.  This enables
cross-compiling libdispatch for Android on Windows.
=> build: allow passing Swift specific link flags

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager+POSIX.swift, Foundation/FileManager.swift
Add a check that the system call is defined and the kernel version is high enough.
=> Check renameat2() is available on Linux

CoreFoundation/Base.subproj/CFKnownLocations.c
Add support for android to KnownLocations.  Assume that only current
user is supported as all applications in android are isolated and single
user.  For now, place all files in ~/Apple/Library/Preferences.  This is
the last piece needed in CoreFoundation for Android support.
=> Base: implement KnownLocations for android

CoreFoundation/Base.subproj/CFKnownLocations.c
The empty string check was accidentally doing an assignment.  Correct
the typo.
=> CoreFoundation: fix incorrect check

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Windows has a specific attribute to mark a file as hidden as opposed to
prefixing ".". This allows setting and getting the attribute. On POSIX,
it will return based on the "." prefix and setting it does nothing.
=> Implement ._hidden on Windows

CMakeLists.txt, Tools/plutil/main.swift
Add an explicit TARGET for executable targets, to allow cross
compilation and fix plutil to import Glibc also in Android.
=> [cmake] Allow cross-compilation of add_swift_executable targets.

Foundation/FileManager+POSIX.swift, Foundation/FileManager.swift
```
D:/a/1/s/swift-corelibs-foundation/Foundation/FileManager.swift:563:50: error: cannot convert value of type 'UInt32' to expected argument type 'mode_t' (aka 'UInt16')
let type = FileAttributeType(statMode: s.st_mode)
~~^~~~~~~
mode_t(         )
```
=> Foundation: repair android ARMv7 builds

Foundation/FileManager+POSIX.swift
```
D:/a/1/s/swift-corelibs-foundation/Foundation/FileManager+POSIX.swift:987:41: error: cannot convert value of type 'UInt64' to expected argument type 'dev_t' (aka 'UInt32')
return _dev_major(file1.st_rdev) == _dev_major(file2.st_rdev)
~~~~~~^~~~~~~
dev_t(       )
```
=> Foundation: repair build for android ARMv7

Foundation/CGFloat.swift
This PR is just a continuation of similar PR made in Swift repository (already merged): https://github.com/apple/swift/pull/25502
Swift forum discussion: https://forums.swift.org/t/android-crosscompilation-on-macos-is-swift-float80-support-really-needed-for-android-intel-x86-and-x86-64-targets/25835
=> [Android]: Fix for compile error addressed Float80 data type.

CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, TestFoundation/TestProcess.swift
- plutil requires an rpath of '$ORIGIN/../lib/swift/${swift_os}'
so set this specificaly for plutil.
- Add a test for running plutil, which relies on LD_LIBRARY_PATH
being set when the tests are run to point to the build directories.
=> plutil: Add a specific rpath for plutil and use it when linking.

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
_This PR corresponds to apple/swift#25698._
It fixes `Decimal.magnitude` so that `Decimal.nan.magnitude` is no longer incorrectly `0`.
The corresponding PR in the apple/swift repository also incorporates changes from #1759; here, minor edits (NFC), including one suggested on review, are back-propagated so as to help the two versions of `Foundation.Decimal` remain in sync.
Resolves [SR-10938](https://bugs.swift.org/browse/SR-10938).
=> Fix two Decimal members with respect to NaN

CoreFoundation/CMakeLists.txt
This PR fixes install step failure:
```
...
-- Installing: /Install/armv7a/swift-corelibs-foundation/lib/swift/CoreFoundation/ForSwiftFoundationOnly.h
-- Installing: /Install/armv7a/swift-corelibs-foundation/lib/swift/CoreFoundation/module.map
-- Installing: /Install/armv7a/swift-corelibs-foundation/lib/swift/CFURLSessionInterface
-- Installing: /Install/armv7a/swift-corelibs-foundation/lib/swift/CFURLSessionInterface/CFURLSessionInterface.h
-- Installing: /Install/armv7a/swift-corelibs-foundation/lib/swift/CFURLSessionInterface/module.map
-- Installing: /Install/armv7a/swift-corelibs-foundation/usr/lib/libCoreFoundation.a
-- Installing: /Install/armv7a/swift-corelibs-foundation/usr/lib/libCFURLSessionInterface.a
CMake Error at CoreFoundation/cmake_install.cmake:73 (file):
file called …
```
=> Fixes Cmake error "file called with network path DESTINATION"

README.md
Fixes a very small nit: Whether you're reading "URL" or "uniform resource locator," the correct article is "a."
=> [NFC] Grammar: a URL, not an URL

Foundation/FileHandle.swift
Windows indicates an EOF for a pipe by returning ERROR_BROKEN_PIPE as a
result from ReadFile.
=> [Windows] Handle EOF with Pipes

CMakeLists.txt
CoreFoundation is an internal implementation detail of Foundation.
Prevent CoreFoundation from being installed.
=> build: prevent CoreFoundation from being installed

Foundation/FileHandle.swift
Getting an ERROR_BROKEN_PIPE shouldn't be an error in any case, not just
when we're reading untilEOF.
=> Always Handle Broken Pipes on Windows

TestFoundation/TestFileHandle.swift
This fixes the `FileHandle` construction on Windows so that we can
continue to execute more of the tests.
=> TestFoundation: construct `FileHandle` properly on Windows

Foundation/Decimal.swift, TestFoundation/TestDecimal.swift
Reorganize Decimal.swift, bringing the two implementations back into alignment where it makes sense to do so. Even the organization of the two files has fallen out of sync, making it increasingly difficult to ensure parity.
A [corresponding PR](https://github.com/apple/swift/pull/25745) has been drafted for the Darwin overlay.
The major functional change here is incorporation of the function `pow(_: Decimal, _: Int)`, which is present in the Darwin overlay but not found in swift-corelibs-foundation.
=> Synchronize Decimal with Darwin overlay

Foundation/FileHandle.swift, Foundation/Process.swift
- The Security Attributes should allow handle inheritance
- The Startup info should indicate the child should use the passed in
pipes for stdin/stdout/stderr
- The write end of stdin and read end of stdout/stderr shouldn't be
inherited by the child
=> Fix Pipe Inheritance on Windows

Foundation/HTTPCookie.swift, TestFoundation/TestHTTPCookie.swift
While the previous parser dealt with commas, some cases were not
correctly handled, like when a comma was in the last attribute before a
second cookie.
Also trim the names of the cookies to allow spaces before the equal.
=> Improve cookie parsing algorithm.

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager+POSIX.swift
This patch adds a fallback in the `_stat_with_btime` function to `lstat`, in the case where the `statx` system call is available, but is denied (`EPERM`).
In https://github.com/apple/swift-corelibs-foundation/pull/1837 the `statx` system call was introduced to be used - when available - to get file attributes including creation time.  If the call isn't available (eg. on older kernels) then the `_stat_with_btime` function falls back to `lstat`.
However, the call may be available but fail for permission reasons: if running under Docker, both Docker's security profile and `libseccomp` need to know about (and permit) the new system call. `libseccomp` added support [in version `2.3.3`](https://github.com/seccomp/libseccomp/commit/5cbecad4e885d63ed6fd174b846b6aee09749cdc), and Docker [in …
=> Fallback if statx syscall is not permitted

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
The inline code in this file has started using the errno symbol, which
was included correctly in Linux, but not included in Android. This
commit adds the include to allow compiling the code.
@compnerd: this breakage haven't reach yet the Azure CI, but it will tonight, I think.
=> [android] Add errno.h header to the Android branch.

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
The SwiftRuntime has a modified CoreFoundation.h which has additional
includes.  Synchronise it with the base CoreFoundation.h which should
remove the use of the private headers.
=> SwiftRuntime: synchronise CoreFoundation.h

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
This is needed to ensure that CoreFoundation is built with the correct
visibility to enable re-export of symbols from Foundation.  The
adjustment to the sources are needed to synchronize the headers with the
sources.
The changes to the locale constants are needed as variable declarations
cannot be aliases according to clang.
=> CoreFoundation: synchronize CF_EXPORT and CF_PRIVATE decorations

CoreFoundation/Base.subproj/CFPlatform.c, TestFoundation/TestThread.swift
Enable most of the Thread test for Android. The only tests that cannot
pass right now are the ones related to backtraces, which do not use the
Linux API backtrace and would need an specific implementation.
And while Android did not get pthread_getname_np until API 26, the low
level prctl(PR_GET_NAME) works with the same restriction as in Linux
(only 15 characters). With that change, the test about thread names also
passes in Android.
=> [android] Enable Thread tests were possible.

Foundation/FileManager+Win32.swift, Foundation/FoundationErrors.swift, TestFoundation/TestFileManager.swift
- _copyOrLinkDirectoryHelper should throw on errors
- Accounting for that Windows permissions aren't compatible with posix ones
- When given `""` as a file name, most Windows apis return file not found, not invalid filename
=> Fixing up Windows TestFileManager

Foundation/Process.swift
Since child processes use `Path` for their dll search path, `Path`
should always be passed to children if not already specified.
=> Also pass Path to the Child Process on Windows

CMakeLists.txt
Previous inlining had diverged the flags handling and we were no longer
enabling optimizations or testability on FoundationNetworking.  Correct
the flag evaluation.
=> build: correct flags for FoundationNetworking

TestFoundation/TestFileManager.swift, TestFoundation/TestThread.swift, TestFoundation/TestURLSession.swift, TestFoundation/Utilities.swift
Implement support for marking test as expected to fail in Android
similar to what Windows has already. Use the helper function to mark
the tests that were already disabled in Android (there are some others
with extra checks that should be done more carefully).
Additionally, mark one of the tests of TestFileManager as failing in
Android. Android doesn't allow normal programs to use the link syscall,
and it always fails with insuficient permissions. The test will never
work. Disable the test in Android completely. Users should deal with the
always failing API, since errors are always possible for other reason.
Also, remove a disabled test in TestURLSession because I cannot make it
fail in my setup. It might have fail before, but it not longer fails.
=> [android] Mark link test in TestFileManager as failing for Android.

Foundation/NSNotification.swift
I'm rewriting the NotificationCenter API for myself to use associated types and my performance tests have to be boosted on Linux because of the low performance. This should increase performance when NotificationCenter has a lot of observations.
You can find the performance tests in this repo: https://github.com/Cyberbeni/TypedNotificationCenter
=> refactored NotificationCenter to use hash based storage for faster filtering

CMakeLists.txt
Similar to Darwin, use autolinking on Windows to pick up dependent
libraries.  This simplifies the build rules.
=> build: use autolinking on Windows

CoreFoundation/cmake/modules/CoreFoundationAddFramework.cmake
The CMake `file(COPY` will only copy files during the initial
configuration, so changes in the headers of CF will not be propagated to
the build directory and will make for confussing compilation errors.
Using custom commands should keep the dependencies between files
correctly updated and Ninja should copy the modified headers during each
build if necessary.
@compnerd: There might be something about `file(COPY` that I was misunderstanding, but I found that the headers weren't updated with my changes, and I needed to do this change for #2397 to work.
=> [cmake] Use custom command for copying files

TestFoundation/TestHost.swift
Ideally the test suite should not depend on external factors. TestHost
was doing DNS requests to turn Host names into Host addresses.
To try to avoid external factors, one can use localhost, which should be
resolved locally all the time, and the check should work the same.
There's an usage of another external name in the test. Sadly there's no
guarantees of another name being defined locally. Some machines have an
IPv6 specific name, but it is not as standard as localhost. Luckily, the
test will work with an external name, even if it cannot be resolved,
since it should not be the same as localhost for most people.
=> [test] Remove external networking in TestHost

Foundation/Process.swift, TestFoundation/TestProcess.swift, TestFoundation/xdgTestHelper/main.swift
Changes to make TestProcess compatible with Windows.
This fixes all the tests except for `test_current_working_directory` which is having issues with path formatting -- the different ways to get a temp directory give different things (`"C:\Users\gwenm\AppData\Local\Temp"`, `"C:\Users\gwenm\AppData\Local\Temp\"`, and `"/C:/Users/gwenm/AppData/Local/Temp"`). Since the cause is not Process.swift related I'd like to get the other path changes merged first to avoid gratuitous rebasing when fixing that.
=> Fix TestProcess on Windows

Foundation/FileManager+Win32.swift
The POSIX implementation will overwrite the destination so the Windows
version should do the same.
In addition, since we are copying a symlink, we know the type of the
target, so we can specify this to createSymlink. This is useful when
copying directories and you copy a symlink before you copy its target.
This allows you to create a (temporarily) broken symlink of the right
file type rather than having to copy the target first.
=> [Windows] Overwrite the destination if it exists in _copySymlink

Foundation/FileManager+Win32.swift
A relative link should be determined from the path that it is in, not
the current working directory
=> [Windows] Fix _fileExists for relative links

CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, Foundation/NSKeyedArchiver.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSURLRequest.swift, Foundation/URLCache.swift, Foundation/URLProtocol.swift, Foundation/URLRequest.swift, Foundation/URLResponse.swift, Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionConfiguration.swift, Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/TestURLCache.swift, TestFoundation/main.swift
⚠️ Needs extensive testing and adding many of the fixes discussed in the comments of the PR linked below.
- Includes the changes from previous PR: <https://github.com/apple/swift-corelibs-foundation/pull/2341>. They introduce an implementation of `URLCache`.
- Store and provide the storage date for cached responses, for internal use only.
- Implement protocol properties.
- `URLSessionConfiguration` now configures the shared and ephemeral sessions with caches of appropriate size and storage setup. Each ephemeral session has a new in-memory-only cache, and the shared session used the shared `URLCache .
- The `URLProtocolClient` that drives `URLSession` tasks now asks its delegate for caching, and if a cacheable response is determined, uses the `URLSession`’s cache to store it. It will also …
=> Parity: URLCache adoption for HTTP and FTP invocations.

Foundation/Decimal.swift, Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- This allows using an optional Locale to localise the output.
- Update Decimal.description, NSDecimalNumber.description and
NSDecimalNumber.description(withLocale) to call NSDecimalString().
=> Use NSDecimalString(_:_) for Decimal -> String conversion.

Foundation/HTTPCookie.swift, TestFoundation/TestHTTPCookie.swift
When the domain field is specified, the cookie is intended for the
domain and subdomains, so the value of domain has to be prefixed by a
dot.
Added tests to check for this behaviour and modified the incorrect
tests.
NOTE: I checked this behaviour in macOS 13.14.5, and it matches Foundation there.
=> HTTPCookie: parse domain according to RFC

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/FileManager+Win32.swift
_destinationOfSymbolic should return a relative path if the symlink is a
relative symlink. Now instead of returning the resolved symlink path, we
read the ReparsePoint to get the path it contains.
=> Fix _destinationOfSymbolicLink behaviour on Windows

Foundation/FileManager+Win32.swift, Foundation/FileManager.swift
On Windows, symlinks to directories are both symlinks and directories.
To emulate posix, we should treat them as only symlinks and not
directories.
=> [Windows] Mark Symlinked Directories as Symlinks

TestFoundation/TestProcessInfo.swift
- The Executable name should have .exe
- Windows doesn't have setenv, so make putenv work more like it and accept keys with `=` in them.
=> Fix TestProcessInfo on Windows

Foundation/HTTPCookie.swift
Import WinSDK to enable import of networking APIs for Windows.
=> FoundationNetworking: repair the build on Windows

Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
- This just wraps replaceItem(at:withItemAt:backupItemName:options:)
=> FileManager: Add missing replaceItemAt(_:withItemAt:backupItemName:options:)

Foundation/NSDecimalNumber.swift, TestFoundation/TestDecimal.swift
- Call NSDecimalMultiplyByPowerOf10() instead of NSDecimalPower() to
multiply the number by 10 raised to the given power, not raise
the number to a given power.
=> SR-11150: NSDecimalNumber .multiplying(byPowerOf10:) produces incorrect results.

TestFoundation/TestURL.swift
On Windows, `|` is a valid character in a URL (as a replacement to `:`,
e.g. `/C|/Users/gwenm`. This causes a test testing
`http://test.com/unescaped|pipe` which is expected  to not parse to
parse successfully on Windows. The test then tries to parse the `<null
url>` in the expected result and crashes.
This changes the test to check to make sure it can parse the expected
result instead of force casting so that the test fails instead of
crashing.
This allows TestURL to run to completion in the mean time while working
on URL for Windows.
=> [Windows] Fix TestURL.swift crash

CMakeLists.txt, Foundation/URLCredential.swift, Foundation/URLCredentialStorage.swift, TestFoundation/TestURLCredentialStorage.swift, TestFoundation/Utilities.swift
A basic implementation of URLCredentialStorage, mainly oriented to
credentials for the session. It is an in-memory storage and ignores any
usage of permantent or synchronizable persistency. This should cover
many usage cases, and should allow to built on top of it.
Includes tests.
**Known differences with macOS:**
I tried to run the set of test against macOS (10.14.5) and found a couple of weird results (I run the tests in a playground, so that might cause interesting behaviours).
- `.permanent` credentials are only stored in-memory (so they are equivalent to `.forSession`). Each operating system might have their own permanent storage, so each implementation might be different (or not exist at all). This can be tackled after this basic implementation is reviewed, and in a per-OS strategy. …
=> Basic implementation of URLCredentialStorage

Foundation/JSONSerialization.swift
I realized that one of the test related to CharacterSet was very slow in
constrained devices, but also relatively slow in beefy Linux machines
(taking a couple of seconds to perform back and forth JSON
encoding/decoding trips in memory). The test in question have to embed
relatively large Data in the JSON string (around 128KB, if I remember
correctly), which are serialized as Base64.
When serializing the data, the serializer asks for the String
representation of each object, and then appends all of them into a
String, to later transform into an UTF-8 C string copied into a Data.
One can improve performance by appending the UTF-8 representation of
each piece of the JSON serialization instead of the String building
code, since appending [UInt8] without doing all the checking that String …
=> [perf] JSON encoding can be faster by skipping string building.

CoreFoundation/Base.subproj/CFKnownLocations.c
The usage of CFKnownLocations from Swift Foundation seems to be reduced
to both _kCFKnownLocationUserAny and _kCFKnownLocationUserCurrent. From
the public API of Swift Foundation there's no way to get to
_kCFKnownLocationUserByName. Supporting UserAny is, therefore,
necessary.
There are some ways of accessing _kCFKnownLocationUserByName from the CF
API, but it seems that the API only allows Current or Any, even if they
are not enforced. In any case, Android do not have Unix usernames, so
ByName doesn't make sense, and should be always the same as UserCurrent.
The change in code makes every code path fall back to the current user
(which should be also any user, and any user by name, because the
platforms limitations).
Additionally, instead of picking up a CFFIXEDUSE_HOME, request the home …
=> [android] Improve CFKnownLocations.

CMakeLists.txt
Reverts apple/swift-corelibs-foundation#2406
=> Revert "build: don't link C++ runtime on android"

Foundation/URLSession/URLSessionTask.swift, TestFoundation/TestURLSession.swift
A callback/delegate call could have been called twice for the same task
if the task error happened during the task initialization and the task
was cancelled shortly after. The error was delivered first, but the
state of the task do not change to completed until after the completion
block has been called, which allows the cancellation to happen and
enqueue another failure callback.
The solution is checking for the task not being already completed before
the completion callbacks are invoked again. Basically the state machine
was allowing a transition from .completed to .completed, when it should
not allow it.
Includes a test that uses a bogus protocol to fail the task quickly and
being able to check for the double callback. The test will have fail
before this change is applied, and passes …
=> [URLSession] Avoid calling completion callbacks/delegates twice.

TestFoundation/HTTPServer.swift
Not specifying this causes closesocket() and shutdown() to hang.
=> [Windows] Pass WSA_FLAG_OVERLAPPED when making sockets

Foundation/FileManager+POSIX.swift, Foundation/FileManager+Win32.swift, Foundation/FileManager.swift, TestFoundation/TestFileManager.swift
Compared to the POSIX implementation, this:
- Uses the same _compareFile and _compareDirectory utilities.
- Implements Symlink comparison with `_destinationOfSymbolicLink`
- Doesn't handle devices since there's no reasonable way to check for
that equivalence on Windows (as far as I'm aware). If given a device, it
will instead always return false. This is probably fine since devices
tend to be less file like on Windows anyways.
=> Implement _contentsEqual on Windows

CoreFoundation/URL.subproj/CFURLSessionInterface.c, CoreFoundation/URL.subproj/CFURLSessionInterface.h, Foundation/URLSession/libcurl/EasyHandle.swift, Foundation/URLSession/libcurl/MultiHandle.swift
When you create an event source for a handle in dispatch, dispatch
assumes it owns it, however, when curl finishes with the socket, it
closes it, which leaves dispatch with an invalid handle.
This sets the curl close callback to do nothing which allows us to close
the socket after cancelling the dispatch sources.
=> [URL Session] Avoid Closing Sockets Before Cancelling Event Sources

Foundation/URLSession/URLSessionTask.swift, TestFoundation/TestURLSession.swift
A cancelling or completed task might have been resumed (or suspended)
because the implementation didn't check for the state of the task to be
valid.
Includes a small test that reproduces the problem when this patch is not
applied and that doesn't fail when it is.
=> [URLSession] Do not allow resuming cancelled/completed tasks.

Foundation/JSONSerialization.swift
Array.append(contentsOf:) supports any Sequence, and String.UTF8View is
a sequence, so there's no need to create an Array from it to append it.
From a post-merge feedback in #2393.
=> Remove unnecessary Array copy.

CoreFoundation/Base.subproj/CFRuntime.h, CoreFoundation/String.subproj/CFString.c
The atomic typed reference count is a 64-bit value.  We need to ensure
that any statically allocated structure is 8-byte aligned.  This comes
up in the case of CFString where CFConstantString types are emitted into
`__cfstring` on ELF, which can end up 4-byte aligned on ARMv7.  When
accessed at runtime, the offset becomes underaligned, resulting in a bus
error due to the unaligned access.
Although the attribution of `CFRuntimeBase` to 8-byte alignment should
enforce the alignment of `__CFString` due to the member alignment
requirement, just be extra cautious and mark both as requiring 8-byte
alignment.
=> CoreFoundation: enforce 8-byte alignment on CFRuntimeBase

Foundation.xcodeproj/project.pbxproj, Foundation/URLCredential.swift, Foundation/URLCredentialStorage.swift, Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionConfiguration.swift, Foundation/URLSession/URLSessionTask.swift, TestFoundation/TestURLCredentialStorage.swift, TestFoundation/main.swift
- Do not crash when a synchronizable credential is added. Instead, act as Darwin does in similar situations (do not store). To make sure the difference is visible, diagnose uses of `.synchronized`.
- `URLSession` is now correctly initialized with appropriate credential storages via its configuration.
- Credentials are fetched appropriately from storage, and when a delegate is consulted about authentication fetched credentials are proposed as part of the auth challenge correctly. (If multiple credentials match, always propose the first in lexicographical order.)
- Interpret the disposition of a delegate if queried. If `.performDefaultHandling` is used, or if the task has no delegate, use the default proposed credential once automatically before giving up.
- When a task finishes, if a …
=> Parity: URLCredentialStorage

TestFoundation/HTTPServer.swift, TestFoundation/TestURLSession.swift
Some test were using external URLs. External URLs are not ideal for
testing for serveral reasons: they can change without warning, making
the test start failing, they take longer to resolve, and finally they
will not work if the test machine do not have internal access for
security reasons.
The commit modifies those URL to hit the in-memory HTTP server, setting
each request with a 5 second pause to allow to check the needed
behaviours of pausing and resuming.
/cc @pushkarnk @karthikkeyan
=> [test] Remove external URLs from tests.

CoreFoundation/Parsing.subproj/CFXMLInterface.c, Foundation/XMLNode.swift, TestFoundation/TestXMLDocument.swift
`struct _xmlNode` has two members related to namespace: `ns` and `nsDef`. CoreFoundation uses `ns` instead of `nsDef` in some situations and that causes some bugs such as [SR-10921](https://bugs.swift.org/browse/SR-10921). This PR fixes the issue.
Resolves [SR-10921](https://bugs.swift.org/browse/SR-10921).
(Partially resolves [SR-10764](https://bugs.swift.org/browse/SR-10764).)
=> SR-10921: Fix bugs related to XML Namespace.

Foundation/ByteCountFormatter.swift, Foundation/NumberFormatter.swift, TestFoundation/TestNumberFormatter.swift
- Add default values for properties that allow the properties to retain
user set values if the .numberStyle is changed.
- Match the default values to Darwin for improved compatibility.
- Allow some tests to be different on Darwin where the handing of Double
values is not quite the same, especially for small values.
=> Update NumberFormatter for better default values and Darwin compatibility

Foundation/URLSession/URLSessionConfiguration.swift
Bug: https://bugs.swift.org/browse/SR-10960
=> [SR-10960] URLSessionConfiguration.background(withIdentifier) method implemented

CoreFoundation/NumberDate.subproj/CFTimeZone.c
In the case the code ends up in the fallback that uses localtime_r (in
Unixes), the returned value in tm_zone is an abbreviation, but the code
that created the CFTimeZoneRef was not looking for abbreviations.
This code was hit in Android all the time (since it doesn't have an
Olson TZ file structure), but I didn't realized because my test machine
were using UTC instead of an actual time zone.
=> Look for abbreviations when creating time zones.

CoreFoundation/Base.subproj/CFPlatform.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, Foundation/Process.swift, TestFoundation/TestProcess.swift
Until recent API levels, Android haven't provide posix_spawn and other
functions from that family, so Process was not going to work with the
branches used for other POSIX OS.
Instead of creating an specific path for Android, which will probably be
forgotten by other changes, all the POSIX OS will use private CF
functions that wrap the posix_spawn functions. For Android, we try to
figure out if posix_spawn exist, and use it in that case, but  we
implement a subset of the posix_spawn family of functions for lower API
levels, using fork and exec underneath, and other functions from the
POSIX APIs. The already code in Process is only modified slightly to
adapt to the new names have to be modified.
The tests have to be modified slightly for working on Android. Many
changes are related to the …
=> [android] Implement Process and modify TestProcess to pass.

Foundation/URLSession/URLSessionTask.swift
Implement the progress object to return a non-indeterminate progress based on current expectations and reporting where possible.
=> Parity: URLSessionTask.progress

Foundation/Stream.swift
=> Parity: InputStream.getBuffer(…)

Foundation/URLAuthenticationChallenge.swift, Foundation/URLSession/URLSessionTask.swift
The class is mostly implemented, but there are several `NSUnimplemented()` that mark methods that, according to URLSession’s contract, are not meant to be invoked. Replace them with more verbose fatalErrors().
=> Parity: Networking: URLAuthenticationChallenge

Foundation/FileManager+POSIX.swift
The size reported by stat.st_size might not be the size of the contents
of the symlink, since it might include metadata. In Android at least the
size of a symlink seems to start at 18 bytes, even if the contents are
smaller.
The commit disables the st_size comparison against the contents
comparison for Android, and rewrites a little the function to use Swift
constructs like defer and guards.
This fixes `TestFileManager.test_contentsEqual` in Android.
PD: I don't know if the check is correct in many other file systems, but I don't think the test should be done at all. I only disabled it for Android because it is the only system where the symlinks doesn't seem to follow the pattern.
=> [android] Fix symlink comparison in Android.

CMakeLists.txt
The first parameter needs to be either `SET` or `GET`.  In this case, we
are trying to set the policy to NEW, so pass the correct parameter.
=> build: correct invocation of `cmake_policy`

CoreFoundation/String.subproj/CFString.c
When creating an immutable funnel, the code checks the value of "hasLengthByte" twice if it ends up being true. Checking for it once is all that is needed, as another branch can check for the other boolean statement in the if statement previously on line 1483. Differentiating the branches allows less redundant checks and does not introduce any side effects.
=> Refactored code to remove unnecessary checks

CoreFoundation/RunLoop.subproj/CFRunLoop.c
CoreFoundation keeps a Dictionary of threads to their runloops. On
Windows, it previously used the threads' Handle as keys into the
dictionary. However, this doesn't work, as if you are attempting to look
up or set the current thread's RunLoop using GetCurrentThread.
GetCurrentThread returns a psuedo handle (FFFFFFFE) rather than a real
handle to a thread which causes it to index incorrectly into the
dictionary.
This was causing the creation of multiple runloops per thread and then
causing dispatch queues not to be pumped leaving blocks to never be run.
The fix here is to use the thread id instead of a handle which is unique
on the system until the thread terminates.
=> Use GetThreadId instead of Storing Handles Directly

Foundation/FileHandle.swift, TestFoundation/TestFileHandle.swift
- Errors on Windows are in the WindowsError domain
- When a file handle for a directory is attemptted to be read, instead
of `ERROR_ACCESS_DENIED` as triggered by windows, intercept it and
return `ERROR_DIRECTORY_NOT_SUPPORTED` to emulate POSIX's `EISDIR`
instead.
=> Handle Windows Errors in FileHandle Tests

Foundation/NSCFDictionary.swift
Correctly bridge this call to make`CFDictionaryContainsValue(…)` work. Fixes https://bugs.swift.org/browse/SR-10394
=> Parity: NSDictionary: _CFSwiftDictionaryContainsValue

Foundation/URLProtectionSpace.swift
Remove the last NSUnimplemented() calls from this class. Since we can’t guarantee Darwin interoperability with coding, remove NSSecureCoding conformance from this class in swift-corelibs-foundation only. Note that certain authentication methods require support that’s not available in s-c-f; diagnose relevant symbols when used. Fixes https://bugs.swift.org/browse/SR-10376
=> Parity: URLProtectionSpace

Foundation/URLProtocol.swift
The only issue here was using NSUnimplemented() (“we still need to implement this”) instead of NSRequiresConcreteImplementation() (“this is an abstract method”). Fix it. Fixes https://bugs.swift.org/browse/SR-10377
=> Parity: URLProtocol

CMakeLists.txt, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/CMakeLists.txt, CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, CoreFoundation/Parsing.subproj/module.map, CoreFoundation/Parsing.subproj/module.modulemap, Docs/ReleaseNotes_Swift5.md, Foundation.xcodeproj/project.pbxproj, Foundation/NSError.swift, Foundation/NSObjCRuntime.swift, Foundation/NSSwiftRuntime.swift, Foundation/XML/Info.plist, Foundation/XMLDTD.swift, Foundation/XMLDTDNode.swift, Foundation/XMLDocument.swift, Foundation/XMLElement.swift, Foundation/XMLNode.swift, Foundation/XMLParser.swift, TestFoundation/TestImports.swift, TestFoundation/xdgTestHelper/main.swift
Split the portions of Foundation that depend on libxml2 into their own module, `FoundationXML`. This is the last module to be split off.
=> Split: FoundationXML

Foundation/NSString.swift, TestFoundation/TestNSString.swift
Implement those flags that do not require Darwin frameworks, and diagnose use of the rest.
=> Parity: NSString.enumerateSubstrings(…)

CMakeLists.txt
This was converted to a generator expression but the FoundationXML and
FoundationNetworking modules did not pass the parameter correctly.
=> build: correct passing `-DDEPLOYMENT_ENABLE_LIBDISPATCH`

CMakeLists.txt
GCD support is available on all targets, make it a hard dependency.
This was originally for ease of porting, but is no longer needed.
=> build: remove option to disable GCD support

CoreFoundation/StringEncodings.subproj/CFStringEncodingDatabase.c
The Windows codepath for CFSTringEncodingGetName was ifdefed out so it
always returned null.
=> Enable the Windows Path for String Encoding Conversion

Foundation/NSDictionary.swift
Implement it. Fixes https://bugs.swift.org/browse/SR-10396
=> Parity: NSDictionary: Non-keyed archiving marked as NSUnimplemented()

CoreFoundation/PlugIn.subproj/CFBundle.c, Foundation/JSONSerialization.swift, Foundation/NSCoder.swift, Foundation/NSKeyedUnarchiver.swift, Foundation/NSString.swift
`NSDebugDescriptionErrorKey` was added in #2102.
=> Replace literal "NSDebugDescription" error keys

Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/ftp/FTPURLProtocol.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/TestURLSession.swift
- Implement downloadTask(withResumeData…). We do not currently support resume data, so act as Darwin does when invalid data is fed to these methods.
- Implement uploadTask(withStreamedRequest:).
- Some cleanup, some testing.
=> Parity: Networking: URLUploadTask and URLDownloadTask

Foundation/URLSession/NativeProtocol.swift, Foundation/URLSession/URLSession.swift, Foundation/URLSession/URLSessionTask.swift, Foundation/URLSession/ftp/FTPURLProtocol.swift, Foundation/URLSession/http/HTTPURLProtocol.swift, TestFoundation/TestURLSession.swift
Reverts apple/swift-corelibs-foundation#2293 — temporarily un-fails the race seen in https://ci.swift.org//job/oss-swift-incremental-RA-linux-ubuntu-14_04/7837/consoleFull#1582003869ba62d58e-7248-467b-91e0-c7508d5cf947
=> Revert "Parity: Networking: URLUploadTask and URLDownloadTask"

CoreFoundation/Base.subproj/CFRuntime.c, CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h, CoreFoundation/Parsing.subproj/CFXMLInterface.c, CoreFoundation/Parsing.subproj/CFXMLInterface.h, Foundation/NSSwiftRuntime.swift, Foundation/XMLDTD.swift, Foundation/XMLDTDNode.swift, Foundation/XMLDocument.swift, Foundation/XMLElement.swift, Foundation/XMLNode.swift, Foundation/XMLParser.swift
This setups up indirection to access the CoreFoundation interfaces from
CFXMLInterface and Foundation.XML which is required for properly
isolating the CoreFoundation interfaces from Foundation.
=> FoundationXML: indirect CF accesses

CoreFoundation/String.subproj/CFCharacterSetData.S, CoreFoundation/String.subproj/CFUniCharPropertyDatabase.S, CoreFoundation/String.subproj/CFUnicodeData.S
This data was previously put into the default section, .text, which
is generally used for executable data.
This fixes a gold warning on IBM Z: "S/390 code fill of odd length
requested". This warning was triggered because executable
instructions on IBM Z must be 2-byte aligned and the data in one of
these sections is 1-byte aligned.
=> Place read-only data symbols in the .rodata section.

CMakeLists.txt, Foundation.xcodeproj/project.pbxproj, Foundation/NSObjCRuntime.swift, Foundation/Port.swift, Foundation/PortMessage.swift, Foundation/Process.swift, TestFoundation/TestSocketPort.swift, TestFoundation/main.swift
⚠️ Needs tests.
- Implement `Port` as a top-level abstract class, like Darwin’s.
- Implement `PortMessage`.
- Implement `SocketPort`, our only cross-platform port. Note that Distributed Objects is not available in s-c-f, and thus `NSConnection`-related functionality is not available nor implemented.
A few differences with Darwin:
- `PortCoder` is not available. Classes that ‘support coding only through a `NSPortCoder`’ do not conform to `NSCoding` in swift-corelibs-foundation.
- `MessagePort` is not available in s-c-f. It is noted as a to-avoid API in the documentation and relies on Mach ports, which are not available everywhere. The default implementation of `Port`’s initializer would return a `MessagePort` as a factory initializer on Darwin if invoked directly; this is not the case …
=> Parity: Port, PortMessage and SocketPort

Foundation/HTTPCookie.swift, TestFoundation/TestHTTPCookie.swift, TestFoundation/TestURL.swift
Fixes https://bugs.swift.org/browse/SR-11294
cc @weissi @spevans
=> [5.0.3] Backport 5.1 changes to HTTPCookie parsing.

Foundation/Port.swift
Fixes issues seen in https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=6297&view=logs&j=1d59321a-8fbc-5405-c03e-4696bd0a260e&t=1075a828-3280-5930-19a8-eb2ba31fb39b&l=805:
- `INADDR_ANY` is not necessarily available on Android.
- Cast `INADDR_*` values to `in_addr_t` before assignment.
- Android imports `SOCK_*` as untyped `Int32` values; do not invoke `.rawValue` on them in that case.
=> Port: Android build fixes

TestFoundation/TestURLSession.swift
This test fails nondeterministically. https://bugs.swift.org/browse/SR-11310
=> XFAIL: test_noDoubleCallbackWhenCancellingAndProtocolFailsFast

CMakeLists.txt
Until CMake 3.15, dependency tracking is not properly possible due to custom
commands for linking.  Provide an escape hatch in the form is a variable that
can be setup to force the linking of zlib.  We do not search for zlib, simply
allow the user specify a magic variable to permit them to inject the linking.
=> build: workaround hook for zlib dependency

CMakeLists.txt
The target reproduces the basic structure of the Xcode project and
allows other platforms to build easily and test.
The target is not installed intentionally. It is supposed to be a
development tool.
(This would have avoided a problem that was almost introduced in #2462)
=> [cmake] Create a GenerateTestFixtures targets in CMake.

CoreFoundation/Parsing.subproj/CFXMLInterface.c, Foundation/XMLNode.swift, TestFoundation/TestXMLDocument.swift
Runtime crash occurs when `XMLDocument`'s computed property `var name: String?` is called. This PR fixes the issue.
Resolves [SR-10776](https://bugs.swift.org/browse/SR-10776).
~~Note: This PR would conflict with [PR#2287](https://github.com/apple/swift-corelibs-foundation/pull/2287) and [PR#2313](https://github.com/apple/swift-corelibs-foundation/pull/2313). That's why it is a draft at the moment. This branch will be rebased after they are merged.~~
**EDITED**
#2287 has been merged. This PR seems not to conflict with #2313 after checking again. Sorry.
=> SR-10776: Fix runtime crash of calling XMLDocument's `var name: String?`

Foundation/RunLoop.swift, TestFoundation/TestRunLoop.swift
Implement with the same semantics as Darwin. Fixes https://bugs.swift.org/browse/SR-10368
=> Parity: RunLoop.add(Port…)/.remove(Port…)

Foundation/XMLDocument.swift
We’re out of time to add libxslt as a dependency. Note that XSLT is not available at compile time, for now, and remove the undue reference to coding.
Fixes https://bugs.swift.org/browse/SR-10420, https://bugs.swift.org/browse/SR-10420
=> Parity: XMLDocument: NSCoding, XSLT

Foundation/Port.swift
- WinSock doesn’t define the sa_* and in_* types.
- in_addr is a union on Windows instead of a scalar. Remove the reliance on that and copy the bytes over instead.
- IPPROTO_TCP is imported typed. Shim it as a scalar.
=> Port: Windows fixes

CMakeLists.txt, Foundation/NSData.swift
libdispatch is required by Foundation.  Remove the single case where we
depended on the flag to be set when building Foundation.
=> Foundation: remove unnecessary `-DDEPLOYMENT_ENABLE_LIBDISPATCH`

Foundation/URLAuthenticationChallenge.swift
For this release, do not support coding FoundationNetworking types (since their Darwin serialization setup is complex). Remove the conformance.
=> Parity: NSCoding: URLAuthenticationChallenge

Foundation/Operation.swift
According to the Xcode documentation, we should use isEmpty property to check whether your collection is empty.
[https://developer.apple.com/documentation/swift/array/1688398-isempty](https://developer.apple.com/documentation/swift/array/1688398-isempty)
> When you need to check whether your collection is empty, use the isEmpty property instead of checking that the count property is equal to zero. For collections that don’t conform to RandomAccessCollection, accessing the count property iterates through the elements of the collection.
=> Use Array.isEmpty instead of checking account property
