Foundation/CGFloat.swift
Foundation/Data.swift
Foundation/NSSwiftRuntime.swift

Update the Foundation implementation for Swift 5.1 syntax changes.  NFCI

5.1 Syntax Updates (NFCI)

---

Foundation/XMLDocument.swift
Foundation/XMLElement.swift
Foundation/XMLNode.swift
TestFoundation/TestXMLDocument.swift

Parity: XMLDocument.init(), XMLNode.init()

---

Foundation/CGFloat.swift
Foundation/Data.swift
Foundation/NSNumber.swift
Foundation/NSRange.swift
TestFoundation/TestNSNumber.swift

- #if arch() guard blocks are used for per architecture code paths, so
for unsupported architectures add an #else/#error message to ensure
the correct path is added.
- This fixes some initializers that may have otherwise been empty.
- Ignore blocks with just one architecture as this is usually a specific
targeted fix.
I think the message is correct for all cases but can be changed if necessary.

Consistently add #error when compiling on unsupported architectures.

---

Foundation/Stream.swift
TestFoundation/TestStream.swift

- Fix the base class to work like it does on Darwin.
- Allow scheduling input and output streams.
- Allow setting and retrieving properties.
Fixes https://bugs.swift.org/browse/SR-10369

Parity: Stream

---

TestFoundation/TestURLSession.swift

A merge issue when un-reverting a patch caused this test to be un-XFAIL’ed incorrectly. Fix that.

XFAIL: test_noDoubleCallbackWhenCancellingAndProtocolFailsFast (again)

---

Foundation/XMLDTD.swift
TestFoundation/TestXMLDocument.swift

Implement it to create an empty `.DTDKind` node, as it does on Darwin.

Parity: XMLDTD.init()

---

CoreFoundation/Parsing.subproj/CFXMLInterface.c
CoreFoundation/Parsing.subproj/CFXMLInterface.h
Foundation/XMLElement.swift
Foundation/XMLNode.swift
Foundation/XMLParser.swift

⚠️ Needs tests.
Fixes what `NSUnimplemented()` invocations remained in FoundationXML:
- Finish implementing namespace accessors.
- Finish implementing namespace utility methods for working with qnames;
- Note that XQuery is unavailable in s-c-f.

Parity: XMLElement: XML Namespaces (final part)

---

Docs/Testing.md
TestFoundation/FixtureValues.swift
TestFoundation/TestCachedURLResponse.swift
TestFoundation/TestCalendar.swift
TestFoundation/TestDateFormatter.swift
TestFoundation/TestDateIntervalFormatter.swift
TestFoundation/TestDecimal.swift
TestFoundation/TestFileManager.swift
TestFoundation/TestHTTPCookie.swift
TestFoundation/TestNSCalendar.swift
TestFoundation/TestNSString.swift
TestFoundation/TestObjCRuntime.swift
TestFoundation/TestPipe.swift
TestFoundation/TestScanner.swift
TestFoundation/TestSocketPort.swift
TestFoundation/TestTimeZone.swift
TestFoundation/TestURL.swift
TestFoundation/TestURLCache.swift
TestFoundation/TestURLCredentialStorage.swift
TestFoundation/TestURLRequest.swift
TestFoundation/TestURLResponse.swift
TestFoundation/TestURLSession.swift
TestFoundation/Utilities.swift
Tools/GenerateTestFixtures/GenerateTestFixtures/Utilities.swift

Instead of using an extension on Optional only available in Foundation,
we should start using the recently introduced XCTUnwrap available in
XCTest to perform the same job. The XCTest API would probably be more
known in other code bases, so people will be more willing to use it and
learn it.
The commit removes all the usages of unwrapped and replaces them with
XCTUnwrap. Additionally it marks unwrapped() as deprecated, so people
receive a clear message about the disappearance with a helpful hint of
what to use instead.

[gardening] Migrate from unwrapped() to XCTUnwrap()

---

CoreFoundation/CMakeLists.txt

Reduce some of the unnecessary duplication in the CoreFoundation build.
This also reorganises the rules some to group the operations together.
There is more than can be done here to reduce duplication and simplify
the rules, but some of that work requires coordinating changes with
libdispatch and can be done subsequently.

build: restructure CoreFoundation build rules

---

Foundation/NSGeometry.swift

Replace it with a calque of Darwin’s implementation.

Parity: NSIntegralRectWithOptions

---

CoreFoundation/CMakeLists.txt

Reverts apple/swift-corelibs-foundation#2489
We can put the changes back because we have CMake 3.15 getting built in CI

Revert "Revert "build: restructure CoreFoundation build rules""

---

TestFoundation/TestURL.swift

Windows doesn't have `/data` or `/usr`. Since Windows does not guarantee
a drive letter actually existing, defer to NSHomeDirectory to give us a
directory which should always exist.

[Windows] Fix test_reachable

---

TestFoundation/TestXMLParser.swift

Unless compiled with iconv support, libxml2 only supports
- UTF-8
- UTF-16, both little and big endian
- ISO-Latin-1 (ISO-8859-1)
- ASCII
See http://www.xmlsoft.org/encoding.html#Default for details

Remove Verification of UTF32 XML on Windows

---

TestFoundation/TestFileManager.swift

Windows doesn't conform to XDG so the tests are not applicable.

Disable FileManager XDG Tests on Windows

---

TestFoundation/TestHTTPCookieStorage.swift

Windows doesn't conform to XDG so the test isn't applicable

[Windows] Disable TestHTTPCookieStorage XDG Test

---

CoreFoundation/Preferences.subproj/CFPreferences.c

The current Windows implementation doesn't properly handle
kCFPreferencesAnyUsers, which causes it point to the same location as
kCFPreferencesCurrentUser which causes preferences to be loaded
incorrectly.
Instead, we should defer to CFKnownLocations as the non Windows
implementation already does

[Windows, CoreFoundation] Construct Preferences Using Known Locations

---

Foundation/FileManager+Win32.swift
Foundation/FoundationErrors.swift

On POSIX Foundation, removing  a file is considered writing to it and so
when the file to be removed isn't found, it throws fileNoSuchFile. Since
Windows instead checks for the file attributes first which is considered
a read, it throws there with fileReadNoSuchFile. In removeItem to match
that behavior, we catch the fileReadNoSuchFile and turn it into
fileNoSuchFile.

[Windows] Match error behavior of POSIX

---

CoreFoundation/NumberDate.subproj/CFTimeZone.c

Windows returns the bias in minutes, but CoreFoundation expects the
offset in seconds.

Fix timezone creation on Windows

---

CoreFoundation/Base.subproj/CFAsmMacros.h

Correct the else if macro usage, which was resulting in redefinition of macros
incorrectly.

CoreFoundation: correct typo in ASM Macros

---

Foundation/NSTimeZone.swift

Windows now has a database (the registry) and can handle GMT/UTC, so
this is irrelevant code.

Remove old Windows Code

---

CoreFoundation/URL.subproj/CFURLSessionInterface.c
CoreFoundation/URL.subproj/CFURLSessionInterface.h
Foundation/URLSession/libcurl/EasyHandle.swift
Foundation/URLSession/libcurl/MultiHandle.swift

This reverts commit 02656bf6637d75ead56d628960c02569330b99c8. Fixes SR-11557.

5.1: Revert 02656bf6637d75ead56d628960c02569330b99c8

---

TestFoundation/HTTPServer.swift
TestFoundation/TestURLSession.swift

Some cookie tests were depending on previously run tests to be
successful. Rewrite all the tests to be independent from each other.
The first change is that all the tests that deal with cookies try to
clean their cookie storages before starting the testing. This should
avoid previous state leaking into the current test.
Some other changes are made to clarify how the cookie tests are actually
performed. To check that the cookies are set by URLSession, an special
endpoint that echoes back the request header are used. To make it clear,
that endpoint has changed names.
In the cases that we were checking that the response headers were
setting the cookies, we actually check for the right headers to been
set, not some random data in the response (because for some reason, the
request headers were …

[test] Rewrite URLSession cookie tests to be independent.

---

TestFoundation/Utilities.swift
TestFoundation/main.swift

We are blocking master, apparently, so XFAIL the entire thing. This needs to be reverted as soon as humanly possible.

XFAIL the URLSession test suite

---

TestFoundation/TestBundle.swift

On Windows, dlls don't begin with "lib" so the tests should be searching
for "MyDLL.dll", not "libMyDLL.dll"

[Windows] Search for Dlls in Bundles Properly

---

Foundation/Process.swift
TestFoundation/TestProcess.swift
TestFoundation/xdgTestHelper/main.swift

Reverts apple/swift-corelibs-foundation#2485
We are seeing failure on Ubuntu 18.04: 
https://ci.swift.org/job/oss-swift-package-linux-ubuntu-18_04/2002/console
```
21:15:52 Test Case 'TestProcess.test_fileDescriptorsAreNotInherited' started at 2019-10-15 04:15:28.804
21:15:52 
/home/buildnode/jenkins/workspace/oss-swift-package-linux-ubuntu-18_04/swift-corelibs-foundation/TestFoundation/TestProcess.swift:587: error: TestProcess.test_fileDescriptorsAreNotInherited : XCTAssertTrue failed - 
21:15:52 /home/buildnode/jenkins/workspace/oss-swift-package-linux-ubuntu-18_04/swift-corelibs-foundation/TestFoundation/TestProcess.swift:588: error: TestProcess.test_fileDescriptorsAreNotInherited : XCTAssertEqual failed: ("5") is not equal to ("6") - 0
21:15:52 1
21:15:52 2
21:15:52 94
21:15:52 …
```

Revert "Process: do not inherit all file descriptors to child processes"

---

Foundation/Process.swift
TestFoundation/TestProcess.swift

- If .standardOutput or .standardError was set to nil or
FileHandle.nullDevice, stdin was set to /dev/null instead.

Process: Setting stdout or stderr to nil or nullDevice set stdin instead

---

Foundation/Process.swift
TestFoundation/TestFileManager.swift
TestFoundation/TestProcess.swift
TestFoundation/Utilities.swift

- currentDirectoryURL should be of type URL?
- Disallow setting either property to nil or a non-File URL,
to match Darwin.
- Dont set PWD environment variable, it should just be copied from the
current environment, to match Darwin.

Process: .currentDirectoryURL and .executableURL fixes

---

Foundation/FileManager+POSIX.swift

- Security mechanisms used in Linux VMs, eg libseccomp and
Docker's security policy may block certain system calls if they
are new and unknown to the library and ENOSYS may be returned
instead of EPERM.
- Update the use of statx() to disable future calls and fallback to
lstat() if ENOSYS is returned.

statx: fallback to lstat if ENOSYS is returned in errno.

---

Foundation/Process.swift
TestFoundation/TestProcess.swift

- Throw an error if run() is called more than once.

SR-11408: Foundation.Process: can invoke run() again without error

---

CoreFoundation/Locale.subproj/CFNumberFormatter.c
TestFoundation/TestNSNumber.swift
TestFoundation/TestNumberFormatter.swift

- ICU 62.1 icu4c DecimalFormat api now wraps the new NumberFormatter
api.
- Update currency spacing accoring to ICU changes
(http://bugs.icu-project.org/trac/ticket/6560)
- Disable tests that allowed different patterns for negative numbers,
http://icu-project.org/apiref/icu4c/classDecimalFormat.html states
that negative patterns serve only to specify the negative prefix
and suffix. The number of digits, minimal digits and other
characteristics are ignored in the negative subpattern.
Support for different negative patterns may need to be added as a
workaround.

Support ICU 62+

---

CoreFoundation/String.subproj/CFString.c

CFString's Get MaximumSizeForEncoding method is not clear in that the else branch ALWAYS following the rest of the method due to early returns.
Because the two top branches always return, I removed the else statement, and put encoding & 0xFFF in the switch statement itself instead of modifying the encoding directly.

Simplify CFString's Get MaximumSizeForEncoding so its program flow is clearer

---

Foundation/Scanner.swift
TestFoundation/TestScanner.swift

- Fix Scanner._scan(): Make the local result an Optional and dont
initalise it until a valid number has been found.

SR-11687: Scanner.scanDouble returns Optional(0.0) instead of nil on failure

---

Foundation/Process.swift
TestFoundation/TestProcess.swift

- Check the file descriptor passed to _CFPosixSpawnFileActionsAddClose()
is valid.

SR-11699: Process: Closing standardInput before calling run() aborts with EBADF

---

TestFoundation/TestBundle.swift

CoreFoundation doesn't have functionality to verify dlls, instead just
returning success. Since the preflight check doesn't throw, the test
fails.

[Windows] XFAIL Preflight Check Test

---

Foundation/CMakeLists.txt

This adjusts the prefix used for linking libraries.  This is needed to
ensure that the system libraries are linked properly on Windows.  This
has been fixed properly in CMake 3.16, adjust for 3.15.1.

build: add a workaround for CMake <3.16

---

CMakeLists.txt
Foundation/CMakeLists.txt
Tools/plutil/CMakeLists.txt

RPATH handling in CMake 3.15 was unsupported on Swift targets.  Adjust
the configuration to support it on CMake <3.16 and use that to set the
install RPATH to $ORIGIN rather than the workaround for the build RPATH.

build: honour and use RPATHs

---

DarwinCompatibilityTests.xcodeproj/project.pbxproj
DarwinCompatibilityTests.xcodeproj/xcshareddata/xcschemes/xdgTestHelper.xcscheme
DarwinCompatibilityTests/DarwinShims.swift
TestFoundation/TestFileHandle.swift
TestFoundation/TestPipe.swift
TestFoundation/TestProcess.swift
TestFoundation/TestScanner.swift
TestFoundation/Utilities.swift
TestFoundation/xdgTestHelper/main.swift

- offset(), read(upToCount:) readToEnd() and wite(contentsOf:)
are not currently available on Darwin so add wrappers and
remove #if gates in tests using them.
- Bump the deployment target to 10.15

DarwinCompatibilty: Add shims for missing FileHandle methods

---

TestFoundation/CMakeLists.txt

This repairs the TestFoundation build for CMake <3.16 which failed to
link against the import libraries on Windows.

build: add workaround for CMake <3.16

---

CoreFoundation/Base.subproj/CFPlatform.c

Setting `O_CREAT` and `O_EXCL` together should always force the creation
of a new file and fail otherwise, regardless of if O_TRUNC is set.
In addition, `O_EXCL` should only take effect if `O_CREAT` is set,
otherwise, the result is undefined behavior per the specification (in
our case, setting to OPEN_EXISTING).

[Windows] O_EXCL should override O_TRUNC

---

TestFoundation/TestJSONSerialization.swift

- Re-enable test_deserialize_allowFragments_withData() and
test_deserialize_allowFragments_withStream()
- Fix deserialize_allowFragments() to pass .allowFragments allowing
the tests to work correctly. Also test failure when .allowFragments
is not passed.
- Validate the tests against Darwin Foundation.
- SR-446: valgrind now shows no invalid read in JSONReader.parseNumber
in test TestJSONSerialization.test_deserialize_allowFragments()

SR-606: test_deserialize_allowFragments transacts upon uninitialized memory

---

CMakeLists.txt
TestFoundation/CMakeLists.txt

This adjusts the build to use the CMake config and export targets to
ensure that things are rebuilt when appropriate.  This also reduces the
use of custom variables.

build: use export targets for XCTest

---

CoreFoundation/PlugIn.subproj/CFBundle_Executable.c

For Android, the main bundle path is set to the executable directory, which is something like `/system/bin/app_process32`.  As a result, things like localized strings do not work.
This PR allows the bundle path to be set by the `CFFIXED_USER_HOME` environmental variable.
In my case, I set this in the Kotlin (or Java) initialization code as follows...
```
Os.setenv("CFFIXED_USER_HOME", mainActivity.filesDir.path, true)
```
I then copy the files from the asset manager into the files directory.  This includes `Info.plist` which configures the bundle identifier and development region, and `en.lproj/Localizable.strings` which contain the English strings.
Once these are in place, I can call `NSLocalizedString` to get the localized string.

[Android] Use CFFIXED_USER_HOME for bundle path

---

CMakeLists.txt

The static builds have dependencies on CoreFoundation which need to be
resolved when linking (not all platforms provide relocatable linking).
Install the CoreFoundation libraries during static builds.

build: install CoreFoundation libraries for static builds

---

CMakeLists.txt

Typo fix for https://github.com/apple/swift-corelibs-foundation/pull/2568

Fix typo in CMakeLists.txt 'CXFXMLInterface' => 'CFXMLInterface'

---

CoreFoundation/Locale.subproj/CFNumberFormatter.c
Foundation/NumberFormatter.swift
TestFoundation/TestNSNumber.swift
TestFoundation/TestNumberFormatter.swift

- ICU62+ changed how some of the NumberFormatter formats and properties
work. These tests also work differently in the Foundation supported by
macOS Catalina (10.15).
- Update the tests to work correctly when run using DarwinCompatibilityTests
on Catalina.
- Update NumberFormatter to make the tests work correctly on Linux with
ICU65.1
Note: Do not merge until ICU has been updated to 65.1

ICU: Update TestNumberFormatter tests to be compatible with ICU62+ and Darwin

---

CoreFoundation/RunLoop.subproj/CFRunLoop.c
TestFoundation/TestRunLoop.swift

When using `RunLoop.main.run(mode: .default, before: Date())` on Android, the call would not return.
This function, along with `limitDate` (which also would hang), calls `CFRunLoopRunInMode`.  According to the [documentation](https://developer.apple.com/documentation/corefoundation/1541988-cfrunloopruninmode), this should return immediately if seconds is 0.
I traced the problem to `__CFRunLoopRun` where there are a few platform specific cases for draining the message queue.  In the `TARGET_OS_LINUX` case, the polling condition was not being considered.
This PR fixes the parameter to be `poll ? 0 : TIMEOUT_INFINITY` as is done for the other platforms, which  allows polling to work on Android.

[Android][Linux] Fixed hang when using RunLoop.main.run with Date()

---

Foundation/CMakeLists.txt

CMake 3.15 doesn't properly include resource files when linking by being
passed a target which means Windows doesn't include the Olson timezone
data. Instead as a work around, link against the target object using
target_link_options.

Work around for CMake 3.15 Resource file linking

---

Foundation/NSSwiftRuntime.swift

This adds in a quick workaround to ensure that `_NSCFConstantString` is
properly bridged on platforms where the value witness tables are lazily
initialized.

Foundation: adjust initialization codepath for Windows

---

TestFoundation/xdgTestHelper/CMakeLists.txt

xdgTestHelper imports FoundationNetworking and FoundationXML but doesn't
have an explicit dependency on them which can cause a race condition
while building.

[cmake] Fix dependencies for xdgTestHelp

---

CoreFoundation/Base.subproj/CFLocking.h
CoreFoundation/Base.subproj/CFPriv.h
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Locale.subproj/CFDateIntervalFormatter.c
CoreFoundation/Locale.subproj/CFDateIntervalFormatter.h
CoreFoundation/Parsing.subproj/CFXMLInterface.h
CoreFoundation/PlugIn.subproj/CFPlugInCOM.h
Foundation/DateIntervalFormatter.swift

Adjust the headers to convert CoreFoundation into a module to enable
extricating it from the public interface for Foundation.  This adjusts
some of the declarations to be more standalone and others to use the
CoreFoundation types rather than C99.  These changes do not impact the
ABI of the declarations.

CoreFoundation: prepare for modularization (NFC)

---

Foundation/NSPathUtilities.swift
Foundation/NSURL.swift

While URLs get converted to forward slashes on Windows, strings are
handled as is and thus need to be able to handle \ separators. Since
many Windows apis also support /, we'll handle that as well, but default
to \ if required.

Add Support for '\' in Windows Paths

---

CoreFoundation/Base.subproj/CFFileUtilities.c

When set to true, CFIterateDirectory should append a platform specific
directory seperator to directories that it returns.
Not appending this slash leads to creating CFURL directories that are
not properly marked as such.

Respect appendSlashForDirectories on Windows in _CFIterateDirectory

---

TestFoundation/TestFileManager.swift

test_displayNames XCTAsserts that there are enough components in the
array, but if the test fails it still continues on, subtracting from
components.count and causing a negative number out of bounds access.
This doesn't prevent the test from failing since the GreaterThanOrEqual
check will still fail, but it does prevent the test from causing the
test suite to crash.

Fix TestFileManager Crash in test_displayNames

---

Foundation/Process.swift

Modified the error handling of launching a process in a non existing
working directory so that it matches POSIX behaviour. This causes all
the Process tests to pass on Windows now.

[Windows] Fix TestProcess.swift

---

Foundation/FileManager+Win32.swift
TestFoundation/TestFileManager.swift

Taking &wszPathNAmes[...] doesn't properly get the string and leads to
garbled data. Instead, compute the pointer address and pass that.

[Windows] Fix Interpretation of Volume Name Array

---

Foundation/NSPathUtilities.swift

PathIsRelativeW doesn't consider ~ to be an absolute path, so we special
case it in to match posix behaviour

[Windows] Special case ~ as an absolute path

---

Foundation.xcodeproj/project.pbxproj
Foundation/Unit.swift
TestFoundation/CMakeLists.txt
TestFoundation/TestUnitVolume.swift
TestFoundation/main.swift

This fixes Measurement values expressed in cubic centimeters and cubic millimeters.
I found the errors in the coefficients because I tested one of my libraries on Linux for the first time and a test was failing (see https://github.com/ole/Ampere/issues/25).
I considered adding unit tests that test some conversions to Foundation, but I'm not sure how useful they would be. A test for converting a Measurement from one unit to another would essentially repeat the code that's being tested; it seems it would be almost equally likely for a bug to be in the test as it would be in the code being tested.

SR-11766: Fix coefficients for UnitVolume

---

Foundation/FileHandle.swift
TestFoundation/TestFileHandle.swift

Since `func truncateFile(atOffset offset: UInt64)` has been deprecated, new function is introduced. However, the signatures are different between DarwinFoundation and SwiftFoundation.
Resolves [SR-11922](https://bugs.swift.org/browse/SR-11922).

SR-11922: [FileHandle] Make the function signature the same as DarwinFoundation.

---

CoreFoundation/RunLoop.subproj/CFRunLoop.c

In the case where Windows schedules timers too early and CoreFoundation
needs to rearm them, the deadlines need to be reset first else timers
will not be rearmed properly.

Properly Reset Deadlines when Rearming Timers

---

Foundation/Thread.swift
TestFoundation/TestThread.swift

`Thread.sleep(until date:)` and `Thread.sleep(forTimeInterval:)` are initializing `LONGLONG` (`Int64`) from `TimeInterval` (`Double`), cutting sleep time to whole seconds.
This moves "100ns" time units calculation prior to `LONGLONG` init.

[Windows] Thread.sleep(...) time interval precision loss

---

CoreFoundation/NumberDate.subproj/CFDate.c

Integer division rounds result to whole seconds. This forces floating point division.
Noticed the issue because `XCTest.measure` depends on this value (through `ProcessInfo.systemUptime`) and produces unreliable results.

[Windows] Fix precision loss in CFGetSystemUptime()

---

Foundation/Decimal.swift
TestFoundation/TestDecimal.swift

- This still requires some tests with a BinaryInteger larger
then UInt64.

Implement Decimal.init?<T : BinaryInteger>(exactly source: T)

---

Foundation/DateIntervalFormatter.swift

Explicitly convert the field to `Bool` from `DarwinBoolean` for encoding
to ensure serialisability.

Foundation: repair Darwin compatibility test suite

---

CoreFoundation/Base.subproj/CFInternal.h
CoreFoundation/Parsing.subproj/CFBinaryPList.c
CoreFoundation/String.subproj/CFString.c
CoreFoundation/StringEncodings.subproj/CFUniChar.c
CoreFoundation/StringEncodings.subproj/CFUnicodeDecomposition.c

- Add unaligned_load32() / unaligned_store32() and
unaligned_load{16,32,64}be() that load/store using byte access. On
supported architectures clang should convert these into single
load / store instructions.
- When allocating buffers on the stack using STACK_BUFFER_DECL() ensure
the length is > 0, as VLA (Variable Length Arrays) cannot be 0 length.

UBSan: Fix unaligned load/stores found by Undefined Behaviour Sanitizer.

---

Foundation/Process.swift
TestFoundation/xdgTestHelper/main.swift

Android and possibly other UNIX systems lack getdtablesize() so let's
try to use a better way of estimating the file descriptors we need to
close post-fork, pre-exec by listing /proc/self/fd. If that fails, we
fall back on getdtablesize or as a last resort a hard-coded 4096.

don't rely on getdtablesize()

---

CoreFoundation/Base.subproj/CFRuntime.c

__CFGetFullRetainCount contains an ifdef with symbol name
TARGET_RT64_BIT. This is likely a typo since otherwise,
__CFDoExternRefOperation is referenced, but is guarded by an ifdef with
name TARGET_RT_64_BIT instead, which then manifests as a missing symbol.
Other calls to __CFDoExternRefOperation are guarded by the same symbol.

[CF] Fix typo in TARGET_RT_64_BIT ifdef.

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/Collections.subproj/CFData.c
CoreFoundation/PlugIn.subproj/CFBundle_Resources.c
CoreFoundation/Preferences.subproj/CFXMLPreferencesDomain.c
CoreFoundation/String.subproj/CFBurstTrie.c

These particular uses should hopefully be uncontroversial.
* CFPlatform.c: to use the _CFIsMainThread pthread implementation; to
properly implement __CFTSDSetSpecific and __CFTSDGetSpecific with the
same pthread implementation as Linux (and Mac)
* CoreFoundation_Prefix.h: to exclude strlcpy and issetugid which is
normally available in the system; to include sys/param.h for the
MIN macro
* CFData.c: for the __CFPageSize implementation
* CFBundle_Resources.c: to include dirent.h symbols
* CFXMLPreferencesDomain.c: to define sleep for the platform
* CFBurstTrie.c: for mmap.

[CF] Add TARGET_OS_BSD in some places.

---

CoreFoundation/Base.subproj/ForFoundationOnly.h

If !DEPLOYMENT_RUNTIME_SWIFT, just defining STATIC_CLASS_REF is
insufficient, since CFBase refers to DECLARE_STATIC_CLASS_REF.

[CF] Define DECLARE_STATIC_CLASS_REF macro.

---

CoreFoundation/NumberDate.subproj/CFTimeZone.c

Before attempting to check if a timezone is an abbreviation or Olson
format, we should make sure we can't just query Windows for the
timezone. For example, CFTimeZoneCopyKnownNames will return UTC[-+XX]
timezones which should otherwise would fail on.

[CoreFoundation] Use a Windows Timezone if we are given one

---

CoreFoundation/Base.subproj/CFAvailability.h
CoreFoundation/Locale.subproj/CFDateComponents.h
Foundation/DateFormatter.swift
Foundation/DateIntervalFormatter.swift
Foundation/ISO8601DateFormatter.swift
Foundation/NSCalendar.swift
Foundation/NSCharacterSet.swift
Foundation/NSLocale.swift
Foundation/NSNumber.swift
Foundation/NSObjCRuntime.swift
Foundation/NSRegularExpression.swift
Foundation/NSString.swift
Foundation/NSTimeZone.swift
Foundation/NSURL.swift
Foundation/NumberFormatter.swift
Foundation/Process.swift
Foundation/PropertyListSerialization.swift
Foundation/RunLoop.swift
Foundation/Stream.swift

Windows wasn't going down the 64bit enum path in CoreFoundation which caused CFDateComponentUndefined to be 32bit and NSDateComponentUndefined and thus not match. Since changing this causes the enum behavior to change, I've rebased https://github.com/apple/swift-corelibs-foundation/pull/1729 and included it in this pull.

Enable Enum Imports and Synchronize Paths

---

CoreFoundation/Collections.subproj/CFArray.c

CFArray.c references __CFSwiftBridge which is defined behind
DEPLOYMENT_RUNTIME_SWIFT, so this needs to be behind that guard
as well when DEPLOYMENT_RUNTIME_SWIFT is not set.

[CF] Add missing DEPLOYMENT_RUNTIME_SWIFT guard.

---

CoreFoundation/Base.subproj/CFFileUtilities.c

Here we duplicate this extended conditional to not reference DT_WHT,
which is not available on OpenBSD. It is probably harmless to actually
remove DT_WHT entirely here unconditionally, but would require grokking
more context for a simple buildfix.
It also seems more readable to duplicate the entire line in the ifdef
despite being able to squish the ifdef in the clause.

[CF] DT_WHT is unavailable on OpenBSD.

---

CoreFoundation/Base.subproj/CFUtilities.c

As no specific logging is implemented for win platform, CFLog formats log message and then just drops it. Using stderr looks better than nothing.
cc @compnerd

[Windows] Redirect CFLog to stderr

---

TestFoundation/Resources/NSURLTestData.plist
TestFoundation/TestURL.swift

Since '|' is a valid character in a url on Windows as implemented by
CoreFoundation, on Windows, we should expect that `unescaped|pipe`
should be properly parsed.
This is hacky, but adds a test case on Windows, and disables it on other
platforms and vice versa.

[Windows] Fix TestURL/test_URLStrings

---

CoreFoundation/Locale.subproj/CFCalendar.c
CoreFoundation/Parsing.subproj/CFPropertyList.c

It appears that standardization on CF types versus C99 types was made,
but some changes were missing. As I understand it, on platforms where
Boolean (a.k.a. unsigned char, when !DEPLOYMENT_RUNTIME_SWIFT) is
convertible to bool, this doesn't cause a problem, but on OpenBSD,
bool (a.k.a., _Bool) is an enum, so causes an error.
That being said, it certainly appears intended that these should be
written as Boolean.

[CF] Match some declarations with their headers.

---

CoreFoundation/CMakeLists.txt

Support both the CMake package provided by CURL's build as well as the
fallback path when detecting CURL.  This should restore the ability to
use zlib for compression on Windows.

CoreFoundation: permit CURL's CMake package for configuration

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

In Prefix, declarations for the OSAtomic* family of functions and
OSMemoryBarrier are duplicated for Linux, BSD, and Windows. In this
commit, the declarations for OS* functions are made common, since they
are apparently identical for both targets.
Unifying the declarations for Windows is a separate task, since those
declarations use CF_EXPORT. There might be a nice way to go to just a
single set of OS* declarations, but that can come later.  This way,
this commit is just a structural change rather than a structural and
functional one.

[CF] Go from three sets of OS* decls to two.

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

strlcpy and strlcat implementations are required for:
* LINUX, but not ANDROID nor CYGWIN (since ANDROID and CYGWIN
are both LINUX),
* WIN32.
Instead of implementing strlcpy and strlcat once per TARGET_OS when
required, just write the implementation once and modify the conditional.
This does mean the ifdef conditional is a little complicated, but
overall that is outweighed by the removal of the obvious redundancy
and will eventually improve the handling of TARGET_OS_BSD.

[CF] Implement strlcpy and strlcat once in Prefix.

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

While we're here, remove these commented lines. These were here since
initial repo commit and are probably no longer relevant.

[CF] Cleanup commented block.

---

CoreFoundation/PlugIn.subproj/CFBundle.c

When loading an invalid bundle rather than failing as the Darwin path
does, it instead returns the parent directory of the given bundle as an
unloaded bundle.
This removes the hunk so that the Windows behavior matches the other
platforms.

[Windows] Remove Fallback Path with Loading Bundles

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

Linux (except Android or Cygwin) and Windows don't support extended
locales, so a number of preprocessor macros are in Prefix to default to
the standard API that uses the C locale. Both Linux and Windows have
some macros in common and some platform specialized definitions; here,
we split out the common macros and keep the platform-specific
definitions separate.
This will let us more simply extend support for different platforms that
also don't support extended locales in a future commit.

[CF] Unify common locale macros.

---

CMakeLists.txt
TestFoundation/CMakeLists.txt
cmake/modules/XCTest.cmake
cmake/modules/XCTestAddTests.cmake

At the moment, only one test was created for CTest, which would have run
all the test in TestFoundation, and would have reported the final result
as the test result, but without details of which test have failed.
Following the similar case of GTest and gtest_discover_tests, XCTest can
be used to list all the tests in the suite, and execute them as invidual
CTest. They will report as different tests in the output, and individual
failures will be shown. It will be also a little bit more resilient
against crashes, which will only affect one test, and not the full
suite.
At first I was thinking in doing the parsing in some scripting language,
but in order to be platform independent, and because the parsing is easy
enough, the parsing of the XCTest output is done in CMake.
Tested on Linux …

[test] Split TestFoundation in smaller tests for CTest reporting.

---

TestFoundation/TestURL.swift

The working directory was changed to /data/local/tmp on Android assuming that adb is being used, but this isn't necessary in the Termux app. Additionally the working directory was not reset back, so later tests were affected by the change.
Along with the still-unmerged #2145, this finally gets all the TestFoundation tests passing for me on Android.
Pinging @drodriguez, who did a lot of this Android porting work.

TestFoundation: change CWD to TMPDIR and restore previous CWD when test finishes

---

CoreFoundation/Base.subproj/CFInternal.h
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

OpenBSD is one of the platforms that doesn't have xlocale.h, so ensure
that the header is not used and the relevant macros are exposed.

[CF] OpenBSD doesn't have the xlocale header.

---

Foundation/URLSession/URLSession.swift
Foundation/URLSession/URLSessionTask.swift

I'd be happy to write tests, but what should we test here?
cc @parkera

Make URLSession and URLSessionTask more source-compatible with Darwin

---

Foundation/Process.swift
TestFoundation/TestProcess.swift
TestFoundation/xdgTestHelper/main.swift

This is a backport of #2542 & #2586 which together fix https://bugs.swift.org/browse/SR-11354 which is an important bug fix.
Same as #2608 but this one is for 5.2.

[5.2] SR-11354: Foundation.Process inherits file descriptors into the child process

---

Foundation/UserDefaults.swift

- The bridging from Any to AnyObject was fixed a while ago so use 'as'
instead of 'as?' casting and remove the redundant else case.

SR-8918: warning: conditional cast from 'Any' to 'AnyObject' always succeeds

---

Foundation/Process.swift
TestFoundation/TestProcess.swift
TestFoundation/xdgTestHelper/main.swift

This is a backport of #2542 & #2586 which together fix https://bugs.swift.org/browse/SR-11354 which is an important bug fix.
Same as #2607 but this one is for 5.1

[5.1] SR-11354: Foundation.Process inherits file descriptors into the child process

---

Foundation/NumberFormatter.swift
TestFoundation/TestNumberFormatter.swift

- For numberStyle .currency, when .currencyCode was set but
.currencySymbol was nil, the .locale.currencySymbol was used before
the .currencyCode.

SR-12036: Incorrect and Inconsistent NumberFormatter currency behavior on Linux

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

This is exposed for Linux, but also is needed for linking on BSD.
(Let me know if you think there should be one definition of mach_absolute_time in Prefix and the body ifdef'd between Windows and Linux/BSD. I thought to include that in this PR, but I'm not sure I like the look of it, so I omitted it. If you think it'd be worthwhile though, I'm happy to roll it in this PR.)

[CF] Expose mach_absolute_time for BSD.

---

TestFoundation/TestNSCalendar.swift

- Israel is deprecated in favor of Asia/Jerusalem
- Brazil/East is deprecated in favor of America/Sao_Paulo
- Asia/Chongqing is an alias for Asia/Shanghai

Use "Asia/Jerusalem" instead of "Israel"

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

This reorders the Windows header includes for `LARGE_INTEGER` after
PR #2612.

Base: reorder includes for Windows (NFCI)

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

This PR encloses two primarily mechanical commits that deal with the scoping of the implementations of two intrinsic/like functions.
* Prefix defines popcountll for Linux and Windows. The only references to
popcountll exist in CFBurstTrie, and the Prefix implementation is only
used there when TARGET_OS_WIN32. Therefore, there's no need to expose
this outside of Windows.
* flsl is available on FreeBSD (and thus macOS), but not OpenBSD. This
commit makes the implementation of flsl currently exposed to Linux and
Windows also available to OpenBSD.

[CF] Expose flsl and narrow scope of popcountll.

---

Foundation/NSCalendar.swift
TestFoundation/TestDateComponents.swift

- Call components(_:from:) using the correct calendar object with
the correct time zone.

SR-11569: DateComponents.isValidDate() ignores timeZone

---

Foundation/NumberFormatter.swift
TestFoundation/TestNumberFormatter.swift

- For numberStyle .currency, when .currencyCode was set but
.currencySymbol was nil, the .locale.currencySymbol was used before
the .currencyCode.
(cherry picked from commit 187d6b37249459b6353079564143200c2a7c0900)

[5.2] SR-12036: Incorrect and Inconsistent NumberFormatter currency behavior on Linux

---

Foundation/NSData+DataProtocol.swift
TestFoundation/TestNSData.swift

(cherry picked from commit 11ce11199e2fd563372adbf00f61fea5c8c1a5f6)
This fixes an invalid offset bug.

[5.2] Sync NSData+DataProtocol from the SDK overlay

---

Foundation/NSData+DataProtocol.swift
TestFoundation/TestNSData.swift

(cherry picked from commit 11ce11199e2fd563372adbf00f61fea5c8c1a5f6)
This fixes a bug with computing the offset.
cc @kevints

[5.1] Sync NSData+DataProtocol from the SDK overlay

---

Foundation/NumberFormatter.swift
TestFoundation/TestNumberFormatter.swift

- For numberStyle .currency, when .currencyCode was set but
.currencySymbol was nil, the .locale.currencySymbol was used before
the .currencyCode.
(cherry picked from commit 187d6b37249459b6353079564143200c2a7c0900)

[5.1] SR-12036: Incorrect and Inconsistent NumberFormatter currency behavior on Linux

---

Foundation/NSString.swift
TestFoundation/TestNSString.swift

I believe it was just a typo. There are other similar checks already, and all of them use `<=` comparison.
This was discovered as the reason of `paragraphRange(for:)` fail on whole string range. E.g, following code is crashing:
```
let s = "abc" as NSString
let range = NSRange(location: 0, length:3)
_ = s.paragraphRange(for: range) // <- crash
```
Test is also included.
Test checks paragraphRange on:
- whole string range
- every subrange in every single paragraph
- every subrange in every two consecutive paragraphs

NSString._getBlockStart - loose precondition check to avoid crash in edge case

---

CoreFoundation/URL.subproj/CFURL.c
Foundation/FileManager+Win32.swift
Foundation/FileManager.swift
Foundation/NSPathUtilities.swift
Foundation/NSURL.swift
TestFoundation/TestURL.swift

Modified the helper _getFileSystemRepresentation functions to return a
UTF16 Windows style path.
This makes URL.path return a RFC 1808 path on Windows as opposed to the `C:\...` path before. Since `.path` would no longer be valid to pass to win32 functions, it adds Windows specific file system standardization for `standardizingPath` and `getFileSystemRepresentation`. Paths should now be represented internally as RFC 1808 paths on Windows, and only converted when being passed to win32 functions.

Implemented _getFileSystemRepresentation for Windows

---

CoreFoundation/URL.subproj/CFURL.c
Foundation/FileManager+Win32.swift
Foundation/FileManager.swift
Foundation/NSPathUtilities.swift
Foundation/NSURL.swift
TestFoundation/TestURL.swift

Reverts apple/swift-corelibs-foundation#2366
@gmittert, I think that this is causing the tests to fail

Revert "Implemented _getFileSystemRepresentation for Windows"

---

Foundation/NSData.swift
TestFoundation/TestNSData.swift

- When writing the result to a Data() or String() buffer,
avoid doing a copy and use Data(bytesNoCopy:count:deallocator:)
and String(bytesNoCopy:length:encoding:freeWhenDone:) instead.
This also avoids an extra copy when doing the encoding.
- When encoding the 6bit value to an ASCII character, use a table
lookup instead of using base64EncodeByte() that was doing a slow
loop for each value.
- A copy to a buffer is still used as NSData.makeIterator() has
excessive overhead that needs to be fixed in the fuutre, this
will allow the copy to be eliminated at that point in time.
- This gives a speedup in the order of 10x.
Performance tests
Tests were performed using the Base64 module from swift-nio as a control
using the test code below, on a MacBook Pro (Retina, 15-inch, Mid 2015)
2.5 GHz …

SR-12021: Improve the performance of NSData Base64 Encoding.

---

Foundation.xcodeproj/project.pbxproj
Foundation/NSPathUtilities.swift
TestFoundation/TestNSString.swift
TestFoundation/Utilities.swift

- The test was slow for 2 reasons, NSPathUtilities.completePath() was
slow and the test directory used may already have an unknown number of
files in it.
- Use a subdirectory of NSTemporaryDirectory() to control number of
files in the directory. This stops the tests running on an unbounded
number of files which can increase test time.
- _getNamesAtURL(): Simplify the enumerator by making the filename test
predicates Optional.
- Keep the test disabled on Windows as it appears to have never worked.

SR-644: test_completePathIntoString can takes a long time on build servers

---

CoreFoundation/Collections.subproj/CFBasicHash.c
CoreFoundation/Collections.subproj/CFStorage.c

malloc introspection, as afforded by `malloc_size`, `malloc_usable_size`, or `_msize`, is nonportable (and thus not guaranteed to be present on all platforms), not guaranteed to be accurate (though certainly an upper bound), and is generally recommended for debugging.
For those reasons, the following commits are introduced in this PR:
* CFBasicHash.c: only expose `CFBasicHashGetSize`'s `total` branch when one or both of the debugging symbols `ENABLE_MEMORY_COUNTERS` or `ENABLE_DTRACE_PROBES` are true
* CFStorage.c: remove apparently unused function `__CFStorageEstimateTotalAllocatedSize`. If this is necessary for something, please let me know what constraints are required to avoid exposing the `malloc_size`call.

[CF] Avoid using malloc introspection.

---

Foundation/Process.swift

- The runLoopSource was holding a reference to self creating a retain
cycle. Set to nil after the child process has finished.

SR-6450: Leak in Process on Linux

---

CoreFoundation/Locale.subproj/CFLocaleKeys.c

These symbol aliases need to be exposed for TARGET_OS_BSD otherwise
undefined symbol errors will occur when linking.

[CF] Locale symbol aliases required for BSD.

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

malloc_default_zone is unavailable outside of macOS so requires
redefining in Prefix. We have a definition for Linux and Windows, but
this is also required for BSD, so move this to the common Linux, BSD,
and Windows block.

[CF] One malloc_default_zone macro for non-macOS.

---

CoreFoundation/RunLoop.subproj/CFSocket.c

Here we apply a few cursory cleanups for porting purposes. These changes
are as follows:
* move a TARGET_OS_CYGWIN block: it was nested under TARGET_OS_MAC,
which is probably not intended.
* include sys/socket.h for TARGET_OS_BSD: which should be provided.
* include netinet/in.h for !TARGET_OS_WIN32: which is required for
struct sockaddr_in; from memory, this is included transitively on
Linux, but not elsewhere.
* use TARGET_OS_BSD instead of TARGET_OS_UNIX: TARGET_OS_UNIX appears
no longer used; TARGET_OS_BSD is a synonym for __unix__ anyway.
* disuse pthread_setname_np for TARGET_OS_BSD: this doesn't appear in
the FreeBSD manuals, it's not available on OpenBSD, so let's just
disuse it.

[CF] Apply missing includes and cleanups.

---

CoreFoundation/Base.subproj/CFFileUtilities.c
Foundation/FileManager+POSIX.swift

- readdir_r() may be unsafe where NAME_MAX is unspecified as the
buffer length isnt passed in. This may cause NUL termination issues.
- glibc >= 2.24 deprecates readdir_r()
- POSIX.1-2008 doesnt require readdir() to be thread-safe but, in glibc,
calls with different directory streams are.
- Callers of readdir() using methods need to ensure synchronisation
if the same directory is read by multiple threads.

[POSIX] readdir_r() deprectated, replace with readdir()

---

TestFoundation/TestFileHandle.swift

`FALSE` and `TRUE` were converted to proper booleans and do not get
imported as custom names.  Update the tests.

TestFoundation: convert boolean check on Windows

---

Foundation/NSData.swift
TestFoundation/TestJSONSerialization.swift
TestFoundation/TestNSKeyedArchiver.swift
TestFoundation/TestNSValue.swift
TestFoundation/TestStream.swift

- When taking an UnsafePointer to an array etc, the array could be
deallocated whilst the pointer is still in use. This is fixed by
either:
1. Eliminating the pointer entirely and just passing the array or
&array to the function.
2. Creating and using the pointer inside a .withUnsafeBytes {}
or .withUnsafeMutableBytes {} closure.

Fix warning "initialization of '...' results in a dangling pointer"

---

TestFoundation/TestDateFormatter.swift

- This looks to be fixed by the latest upgrade to ICU.
- Re-enable other TestDateFormatter tests that were disabled on Linux
by setting the Locale to "en_US_POSIX" rather than it being set to
the locale where the tests were run.

SR-8994: DateFormatter returns UTC for GMT timezone

---

TestFoundation/CMakeLists.txt
TestFoundation/TestBundle.swift
TestFoundation/TestFileHandle.swift
TestFoundation/TestFileManager.swift
TestFoundation/TestObjCRuntime.swift
TestFoundation/TestThread.swift

- Disable TestThread.test_threadName() as some of the tests are
currently broken.

Set NS_FOUNDATION_ALLOWS_TESTABLE_IMPORT when ENABLE_TESTING is set.

---

Foundation/Operation.swift
TestFoundation/TestOperationQueue.swift

Fixed issue SR-11621.
When calling `start()` on a synchronous operation, the main was not called.

Fix Running Synchronous Operations Without a Queue

---

CoreFoundation/String.subproj/CFStringUtilities.c

- Any use of NSString.compare(_:options:range:locale:) with a non-nil locale
would leak on Linux.
- _CFCompareStringsWithLocale was leaking the collator on non-macOS
platforms.
- Use the collator cache on Linux and Win32 the same way that macOS does
and for other platforms ensure that any allocated collator is freed.

SR-11917: Using JSONEncoder's .outputFormatting = .sortedKeys has a memory leak on Linux

---

TestFoundation/TestRunLoop.swift

- Update the tests to pass on Darwin.
- Re-enable them to pass on Linux as well.

SR-399: RunLoop tests for runLoopMode do not pass on Darwin.

---

CoreFoundation/URL.subproj/CFURL.c
Foundation/FileManager+Win32.swift
Foundation/FileManager.swift
Foundation/NSPathUtilities.swift
Foundation/NSURL.swift
TestFoundation/TestFileManager.swift
TestFoundation/TestURL.swift

Update the `_getFileSystemRepresentation` helper to return a UTF-16
Windows style path.  This enables us to properly model the file system
representation of the path and the URL representation of the path.

Foundation: support `_getFileSystemRepresentation` on Windows

---

Docs/GettingStarted.md
Foundation.xcodeproj/project.pbxproj

Update the document to reflect current `cmake` usage.
@compnerd @millenomi This is based on the commands I use, do you have anything to add/alter?

SR-11411: Update GettingStarted.md

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Foundation/FileHandle.swift
Foundation/FileManager+Win32.swift
Foundation/FileManager.swift

Continue improving the FileManager handling of file paths.  This adjusts
various cases as identified by the test suite.

Foundation: continue Windows file system cleanup

---

TestFoundation/TestURL.swift

In Android /tmp doesn't exist, and the temporary directory is normally
/data/local/tmp. It is not a symlink. The tests were mostly working, but
because `resolvingSymlinksInPath` returns a trailing slash if the
directory actually exists, in Android it was returning without the final
trailing slash in some of the cases.
The changes split the large test into smaller pieces that test one of
the behaviours of `resolvingSymlinksInPath`, and tries not to use the
temporarl directory by itself or suppose anything about it.
There are, however, a couple of tests that check behaviours that are
only applicable to Darwin, so those tests are only performed in Darwin
platforms.
This is simply a rebase of #2145, as [@drodriguez asked me to do](https://github.com/apple/swift-corelibs-foundation/pull/2145#is …

[android] Replace URL tests that use hardcoded /tmp

---

Foundation/FileManager+Win32.swift

When the symbolic link points across a drive, querying the symbolic link
will provide a NT style path.  The NT style path is not valid for a
reparse point destination.  Use a hand-rolled canonicalization (removal
of the `\??\` prefix) for the path to get a path that we can use in the
symbolic link.  `NTPathToDosPath` is a possible approach to a more
robust solution but relies on undocumented kernel APIs.

FileManager: correct symbolic link handling on Windows

---

CoreFoundation/URL.subproj/CFURL.c

In the case that we were given a non-directory path terminating in `\`,
we would preserve the last path arc constructing a directory path
instead of a file path.  This manifested as test failure in the Swift
test suite when converting paths.

CoreFoundation: handle `isDirectory` properly in `WindowsPathToURLPath`

---

Foundation/JSONSerialization.swift
TestFoundation/TestJSONEncoder.swift

- If the array or dictionary is empty, do not add indention spacing.

SR-11410: Pretty printed, JSON encoded empty array or dictionary is different on Darwin vs Linux

---

TestFoundation/TestNotificationQueue.swift

- These tests work correctly on Linux and Darwin now so re-enable.
Reenabling to see if the underlying timeout issue has disappeared

SR-4280: Re-enable TestNotificationQueue tests

---

Foundation/FileManager+Win32.swift

Use a `try?` with a coalescing operator to avoid a guard + return x 2.

Foundation: slight cleanup of `FileManager+Win32` (NFC)

---

Foundation/FileManager.swift

This converts the previous re-encoding of the string to the file system
representation instead.

FileManager: use the proper FSR on Windows

---

Foundation/Process.swift

Use the file system representation of the path rather than encoding the
raw path as a UTF16 string.

Foundation: clear up string abuse on Windows

---

Foundation/NSData.swift

The memory in the `String` is not-being copied, and thus is more of a
view into the memory, not an owning reference.  Do not free this memory
after the destruction of the object.

Foundation: fix invalid free

---

Foundation/FileManager+Win32.swift

Use the file system representation instead of a raw path string encoded
as a UTF16 string.  This ensures that we get valid paths.

FileManager: cleanup string abuse in FileManager+Win32

---

Sources/Foundation/CMakeLists.txt

We package the OLSON database as a binary resource in Foundation.dll.
Unfortunately, something has caused a regression and OBJECT linking
does not function even with CMake 3.16.  Explicitly include the
objects from the resource.

build: reapir the bundling of the OLSON database on Windows

---

Sources/Foundation/FileManager+Win32.swift

Change the path that is used for the `NSError` as the invalid input is
material to the calculation of the proper error code.  When the
unresolved path is empty, the error code should be
`.fileReadInvalidFileName` rather than `.fileReadNoSuchFile`.  This
now matches the expectation.

Foundation: correct error code for invalid symlink on Windows

---

Tests/Foundation/Tests/TestURL.swift

The tests assumed that `S:\b` would exist, which is not required to
exist.  Explicitly indicate the type of path (directory vs
non-directory) as we cannot stat the path to check if the path is a file
or directory.

Foundation: remove file system assumptions

---

CoreFoundation/Base.subproj/CFFileUtilities.c

This adds the prefix support which I ended up needing.  This achieves
parity with the rest of the platforms.  The implementation is slightly
different, using the `CFStringAppendBuffer` to simply reduce the
complexity.

CoreFoundation: finish up file numeration Windows TODO

---

Foundation.xcodeproj/project.pbxproj
Tests/Foundation/FixtureValues.swift

- Add a dependancy on SwiftFoundation.
- Fix import to use SwiftFoundation if available, not Foundation.

GenerateTestFixtures: Fix building on Xcode

---

Tests/Foundation/Tests/TestURL.swift

Leading slashes were causing troubles before recent fixes. Now such cases are handled properly and this small subset of tests should pass.
cc @compnerd

[Windows] Test file URL with leading slash

---

Sources/FoundationNetworking/CMakeLists.txt

Since FoundationNetworking symbols are lazily resolved at runtime,
no symbol references to it are emitted.  On PE/COFF targets (i.e.
Windows), this will result in FoundationNetworking not being loaded and
linked against.  Use the force load symbol to ensure that the reference
is preserved.

build: use forced loading for FoundationNetworking

---

Docs/ReleaseNotes_Swift5.md
Sources/Foundation/NSData.swift
Sources/Foundation/NSString.swift

This reverts commit f3a6f50105ae4e922cc4146a25eb1a9313992a98.  It also
fixes the underlying issue of the heap corruption.
There is no guarantee that the underlying storage for an allocation is
done by `malloc`.  It is possible that the size may be small enough to
be pushed down to a stack allocation, which cannot be released by
`free`.  Buffers record how they are allocated and adjust the release
accordingly.  The safe way to release the memory is to use `deallocate`.
Although the initial approach fixed the heap corruption, it did so at
the single site, but this is a problem with a public interface.  Use the
`deallocate` method on the buffer when releasing the memory to ensure
that the correct mechanism is used for releasing the resources.
Thanks to Lily Vulcano for pressing me to …

Revert "Foundation: fix missing string terminator"

---

Tests/Foundation/Tests/TestProcess.swift

The Windows file system path representation `\` is a drive letter
relative path.  That is, the same path can be used across multiple
drives (similar to the concept of alternate roots).  We expect that
the path returned is `[[:letter:]]:` or `[[:letter:]]:[\\/]` rather
than the Unix `/`.  Adjust the expectation.

test: correct test assumption for Windows paths

---

Tests/Foundation/Tests/TestProcess.swift

Windows does not have the `PWD` environment variable.  The closest
analogue is the `%CD%` magic variable which is specific to the shell
rather than the environment.  Skip the test on Windows.

tests: disable a test on Windows

---

CoreFoundation/NumberDate.subproj/CFTimeZone.c

Unfortunately, Windows does not have full time zone information
available.  For many cases we can make do with the system information,
augmented with alternate names (the Olson-to-Windows conversion
database).  This papers over the inability to deserialize the full
information in the registry by falling back to ICU to get the
information for the DST time conversion.

TimeZone: delegate to ICU on Windows

---

Tests/Foundation/Tests/TestCodable.swift
Tests/Foundation/Tests/TestDate.swift

- .nanosecond is implemented so re-enable tests.
- .quarter doesnt crash but always returns 0 for now so also re-enable
in tests.

SR-5576: Calendar.dateComponents(_:from:) crashes using .nanosecond or .quarter

---

Tests/Foundation/Tests/TestFileManager.swift

- .creationDate may not be available on all Linux platforms due to
kernel version, Docker or other environment security settings etc
so only check its value if it is non-nil.
- Re-enable this test but allow for .creationDate possibly being nil.

SR-10512: TestFileManager .creationDate failed on Ubuntu 14.04

---

CoreFoundation/Base.subproj/SymbolAliases

- This is an alias for _$s15SwiftFoundation19_NSCFConstantStringCN
used while the mangling was being switched from $S to $s but is
not required anymore.

Remove old alias _$S15SwiftFoundation19_NSCFConstantStringCN

---

Foundation/NSCalendar.swift
TestFoundation/TestDateComponents.swift

- Call components(_:from:) using the correct calendar object with
the correct time zone.
(cherry picked from commit 64a7907f312fc8526be6112f863e4b7d7d95f2e0)
Backport of #2625  5.2 version #2627 
cc @weissi

[5.1] SR-11569: DateComponents.isValidDate() ignores timeZone

---

Foundation/Process.swift

- The runLoopSource was holding a reference to self creating a retain
cycle. Set to nil after the child process has finished.
(cherry picked from commit b15e4f43a8de844c44070a5987727ef1b864a426)
Back port of #2631 5.2 version is #2694

[5.1] SR-6450: Leak in Process on Linux

---

Foundation/Process.swift
TestFoundation/TestProcess.swift

- If .standardOutput or .standardError was set to nil or
FileHandle.nullDevice, stdin was set to /dev/null instead.
(cherry picked from commit dffe77420524dbd980edefeca93a0223274d49d7)
Backport of #2545 
cc @weissi

[5.1] Process: Setting stdout or stderr to nil or nullDevice set stdin instead.

---

CONTRIBUTING.md

Not sure if the wording is better, but the link should probably be updated to https://feedbackassistant.apple.com instead of https://bugreport.apple.com so that it goes directly to it rather than a page explaining Apple's update of the bug reporting system.

Feedback Assistant wording and link

---

Foundation/JSONSerialization.swift
TestFoundation/TestJSONSerialization.swift

[5.1.x] Limit the amount of recursion allowed while JSONSerialization parses.

---

CoreFoundation/PlugIn.subproj/CFBundle_Executable.c

On Windows, we would assume that the bundle path computed will exist.
However, it is possible to have an executable using Foundation without a
bundle.  In such a case, the main bundle would never be setup, and when
SwiftFoundation would attempt to access it, it would assume that it was
setup.  This would cause a failure due to the forced unwrapping.

CoreFoundation: ensure that the bundle path exists

---

Sources/Foundation/Port.swift
Sources/Foundation/PortMessage.swift
Tests/Foundation/Tests/TestSocketPort.swift

- Update method signatures to match Darwin.

Port, PortMessage: Rename sendBeforeDate(...) to send(before: Date...)

---

Sources/Foundation/String.swift
Tests/Foundation/Tests/TestNSString.swift

- Add bridging between Substring and NSString.

SR-12020: Cannot as-cast Substring to NSString on linux

---

CoreFoundation/Base.subproj/CFPlatform.c

One of the infinite loops has an immediate check to see if next == CF_DISPATCH_ONCE_DONE. If it is, the loop will break. However, this infinite loop is simple enough to be changed into a while loop. It looks better too and results in more readable code.

No need for a for loop

---

CoreFoundation/NumberDate.subproj/CFTimeZone.c

Discovered this when trying to compile Swift for CentOS 7. I'm not sure if this is the appropriate fix, but it fixes the problem on CentOS.

Don't try to follow relative links in __CFTimeZoneCreateSystem

---

Sources/Foundation/Thread.swift
Tests/Foundation/Tests/TestThread.swift

- Check the return value of _CFThreadGetName correctly

SR-11720: Thread.name leads to empty String on Linux

---

Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

Speeds up NSDecimalString(_:_:) function by about 25% reordering operations and avoiding redundant buffer zeroing

Speeds up NSDecimalString(_:_:) function

---

Sources/Foundation/JSONSerialization.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSKeyedUnarchiver.swift
Sources/Foundation/NSString.swift
Sources/Foundation/NSURL.swift
Sources/FoundationXML/XMLParser.swift
Tests/Foundation/FTPServer.swift

- use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead

Update from deprecated .withUnsafeBytes

---

CMakeLists.txt

This copies the UUID headers into the build tree and then sets up the
include paths for CoreFoundation using that.  This is needed to ensure
that `uuid/uuid.h` is found if not available on the system.

build: repair the android build

---

DarwinCompatibilityTests.xcodeproj/project.pbxproj
Foundation.xcodeproj/project.pbxproj
Sources/Foundation/Bridging.swift
Tests/Foundation/CMakeLists.txt
Tests/Foundation/Tests/TestBridging.swift
Tests/Foundation/Tests/TestNSNumberBridging.swift
Tests/Foundation/main.swift

In particular, printing a SwiftValue on Darwin will print the
contained value, not the generic type + address dump that
is implemented by NSObject.
This brings that same behavior to non-Apple platforms.

Give SwiftValue a tailored `description` property similar to Darwin's

---

Tests/Foundation/Tests/TestCalendar.swift
Tests/Foundation/Tests/TestDateFormatter.swift

- Add Calendar test
- Add DateFormatter test
Test Calendar and DateFormatter with new era name ([SR-10574](https://bugs.swift.org/browse/SR-10574)).
Related https://github.com/apple/swift/pull/24387.

[SR-10574] Add tests for new Japanese calendar era name

---

Tests/Foundation/Tests/TestOperationQueue.swift

Fixes tests of OperationQueue: 
result of assignment was immediately deallocated because of weak property

Fixes tests of OperationQueue

---

Tests/Foundation/Tests/TestURLSession.swift

- Darwin requires implementation of FailFastProtocol.canonicalRequest()
to override abstract method in URLProtocol
- Fix the error code from in the callback to be equal to NSURLErrorCancelled.
- This test now passes on Darwin and Linux but is currently left disabled.

Fix TestURLSession.test_noDoubleCallbackWhenCancellingAndProtocolFailsFast()

---

Sources/Foundation/NSString.swift

- String._guts._isContiguousUTF16 is deprecated and always returns
false.
- String._guts.startUTF16 is deprecated and aborts if called.
- _fastContents will always return nil as Swift Strings do not store
UTF-16 data so no valid pointer can be returned, only nil. So hardcode
this method to return nil.

NSString._fastContents: Remove use of deprecated UTF-16 String properties.

---

CoreFoundation/URL.subproj/CFURL.c

CFURLGetFileSystemRepresentation's implementation has TARGET_OS_MAC and
TARGET_OS_LINUX, but not TARGET_OS_BSD. Nothing here appears macOS or
Linux specific, and things seem to work okay with TARGET_OS_BSD, so
enable it here too.
This also requires CanonicalFileURLStringToFileSystemRepresentation to
be exposed.

[CF] TARGET_OS_BSD for FS representation behavior.

---

CoreFoundation/Base.subproj/CFAvailability.h
CoreFoundation/Base.subproj/CFBase.h

CoreFoundation gets built as a framework.  TargetConditionals.h is a
public header in this framework, so in order for the compiler to find
the header, it has to be referenced through the framework, that is,
<CoreFoundation/TargetConditionals.h>.
In CFBase.h, if we are building standalone (c.f. #2646), we are not
DEPLOYMENT_RUNTIME_SWIFT and so we try and look for TargetConditionals.h
with <TargetConditionals.h>. Presumably this is fine on macOS, since
perhaps this is included elsewhere on that system, but on other
platforms this won't be found and we get an error.
But it's actually unnecessary to reference any other
TargetConditionals.h that may be defined elsewhere, because
TargetConditionals.h is part of the CoreFoundation framework. It is then
similarly unnecessary to test for the …

[CF] Simplify including TargetConditionals.h.

---

Sources/FoundationNetworking/URLResponse.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/Tests/TestHTTPURLResponse.swift

- When initialising the HTTPURLResponse, store the header fields names
capitalised except for X- headers. This matches Darwin.
- This allows responses with lowercase fields names to be read correctly
and redirects to works if the field name is 'location' instead of
'Location'.
- Add missing function HTTPURLResponse.value(forHTTPHeaderField:).

SR-12300: URLSession.dataTask doesn't follow redirects with lowercased location

---

Tests/Foundation/Tests/TestBridging.swift

- This test crashes on macOS so make the test soft fail until it is
fixed properly.

TestBridging: Use XCTUnwrap instead of force-unwrap

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h

Fixes declaration of ` _NSCFXMLBridge` in `ForSwiftFoundationOnly.h` which cleans up 5 warnings in `CFRuntime.c`.

Fixes declaration of  _NSCFXMLBridge in ForSwiftFoundationOnly.h

---

Tests/Foundation/HTTPServer.swift

- Enhance the test HTTPServer by adding /head, /get, /post, /put and
/delete URLs that require the HTTP method to match the endpoint and
return the headers in the request as a JSON body.
- Add extra validation when parsing the request method token.

Test HTTPServer with urls that match the method

---

Sources/FoundationNetworking/URLSession/BodySource.swift
Tests/Foundation/Tests/TestURLSession.swift

- When passing a stream to a URLSession delegate, the stream must not
be open(). It is opened by the underlying URLSession.
- This makes usage of InputStreams compatible with Darwin.

URLSession: Fix InputStream usage

---

Foundation/Process.swift

- The runLoopSource was holding a reference to self creating a retain
cycle. Set to nil after the child process has finished.
(cherry picked from commit b15e4f43a8de844c44070a5987727ef1b864a426)
Backport of #2631

[5.2] SR-6450: Leak in Process on Linux

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

- Every .suspend() has to be balanced with a .resume() to resume a task
but multiple suspend()s or resume()s are allowed, so remove the check
that the suspend count was not going < 0.
- Enhance the test HTTPServer by adding /get, /post, /put URLs that
require the HTTP method to match the endpoint and return the headers
as a JSON body.

SR-12336: URLSessionTask should allow extras resume()'s

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLProtocol.swift

- urlProtocolDidFinishLoading may be called without a response being set
if the protocol needs to early abort, so remove the check for a valid
response.

SR-10652: URLProtocolClient.urlProtocolDidFinishLoading crashes with no response

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

- For all methods except GET, if the request _Body is .none then
set a length of 0. This will add a "Content-Length: 0" header.
- Fail any GET requests with a body, to match Darwin.

SR-12211: URLSession doesn't add Content-Length to empty body requests

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPMessage.swift

- Fixes "warning: enum case 'statusLine' has 3 associated values;
matching them as a tuple is deprecated".

Fix warning for matching enum with associated values as tuples.

---

Sources/FoundationNetworking/URLSession/NetworkingSpecific.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/Tests/TestNSData.swift

- _NSNonfileURLContentLoader.contentsOf(url:) Only return the body
response for certain HTTP codes, for others throw an error.

SR-12135: Data(contentsOf:) does not account for failed HTTP response codes.

---

Tests/Foundation/HTTPServer.swift

- Add support for URL parameters.
- Add status code URLs for /xxx to allow specifiing specific codes
including setting the Location header for 3xx codes.
This includes a workaround that caused the revert in #2740 to hopefully build on Windows without triggering the SIL bug.

Enhance Test HTTP Server

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

- 300 Multiple Choices: Do not follow the redirect, just return the body
from the response. However HEAD requests return no body.
- 301 Moved Permanently, 302 Found: Follow the redirect but send POST
requests as GET when following the redirect.
- 303 See Other: Follow the redirect but always send the request to the
new Location as a GET.
- 304 Not Modified: No special handling or redirects to follow since the
server decides whether to send a response based on the request headers
If-Modified-Since or If-None-Match.
- 305 Use Proxy, 306 Switch Proxy, 307 Temporary Redirect,
308 Permanent Redirect:
Follow the redirection but do not change the method, just repeat the
request to the new location.
- This fix applies for valid redirections in the range 300-308, other
3xx codes have no specific …

URLSession: Fix redirection response handling

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

Reverts apple/swift-corelibs-foundation#2744

Revert "URLSession: Fix redirection response handling"

---

CoreFoundation/Base.subproj/CFPlatform.c

Use newer Windows APIs (Windows Version 1607, RedStone 1, 10.0.14393) of
`SetThreadDescription` and `GetThreadDescription` rather than the
under-the-table hand-shake between Visual Studio and the runtime to use
a TLS slot for a thread description.  Although this bumps up the version
of the Windows requirements for setting the thread description, the
version requirements are already for an EOL-ed version of Windows.

CoreFoundation: adjust the thread name setting on Windows

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

Reverts apple/swift-corelibs-foundation#2746
I think that this change was incorrectly flagged as the cause.  Lets get this un-reverted and tested to prepare for restoration.

Revert "Revert "URLSession: Fix redirection response handling""

---

Sources/Foundation/NSSwiftRuntime.swift

Lazy initialization of the foreign class VWT requires that we explicitly
initialize the metadata.  This was previously relying on the compiler
not being able to optimize away the empty body.  Change this to call an
empty function instead.  This repairs the Windows build.

Foundation: ensure the `_NSCFRuntime` metadata is initialized

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

- Initial body stream was being passed as nil and not _Body.none when
creating a data task without a body. This caused the delegate's
urlSession(_:task:needNewBodyStream:) method to be called
unnecessarily.
- Add a test case and enhance the TestURLSession SessionDelegate to log
the callbacks as they are called to check the number and order.
Fixes a bug introduced in #2735

URLSession: Fix bug requiring a new Body Stream

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

- If the delegate calls the completionHandler with a nil response, then
return the 3xx redirection response and its body data to the caller as
the final response.
- If the delegate fails to call the completionHandler before the timeout
interval for the request has expired, then dont treat is as an error
and dont call urlSession(_:task:didCompleteWithError:).
- Fix TestURLSession.test_httpRedirectionWithDefaultPort() to work
correctly now that the HTTPRedirectionDataTask delegate needs to call
the completion handler with nil to cancel the redirect.
- This handling now matches Darwin.

URLSession: Better handling for willPerformHTTPRedirection delegate calls

---

CoreFoundation/String.subproj/CFStringUtilities.c

- Any use of NSString.compare(_:options:range:locale:) with a non-nil locale
would leak on Linux.
- _CFCompareStringsWithLocale was leaking the collator on non-macOS
platforms.
- Use the collator cache on Linux and Win32 the same way that macOS
does.
(cherry picked from commit 1112582e513f05258dc45f8b66f7e8bcc4add1f3)

[5.2] SR-11917: Using JSONEncoder's .outputFormatting = .sortedKeys has a memory leak on Linux

---

Foundation/NSCalendar.swift
TestFoundation/TestDateComponents.swift

- Call components(_:from:) using the correct calendar object with
the correct time zone.
(cherry picked from commit 64a7907f312fc8526be6112f863e4b7d7d95f2e0)

[5.2] SR-11569: DateComponents.isValidDate() ignores timeZone

---

Sources/Foundation/NSError.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/Tests/TestURLSession.swift

- If a POST request does not have a Content-Type set and the body has a
size greater than zero, then an entry is added to the headers with
type application/x-www-form-urlencoded.
This was not being done if the body was an InputStream, so add a fix
to ensure it is.
- Add missing URLError.Code cases for .dataLengthExceedsMaximum and
.appTransportSecurityRequiresSecureConnection

URLSession: Set default Content-Type for POST request.

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

- If the .httpBody is set to an empty Data() instance then treat this
as if there was no .httpBody set and do not attempt to send a zero
byte body to the remote server.
- Update TestURLSession.test_requestWithEmptyBody() and
TestURLSession.test_requestWithNonEmptyBody() to check the delegate
callbacks and the posted body sent back in the response.

URLSession: Dont try to send a body when URLRequest.httpBody is an empty Data()

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/Tests/TestURLSession.swift

- Ensure that the HTTP requests created when following redirects have
the same timeout as the original request.

SR-2682: URLSession redirect does not inherit request timeout value

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

- Avoid infinite redirect chains by having a hard limit of 16 redirects,
to match Darwin.

URLSession: Add a limit on the number of HTTP Redirects that are followed

---

Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

- urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)
was only sent to tasks of type URLSesisonUploadTask, but testing showed
it should be sent to all task types.
- Update tests that now see an extra delegate callback of this method.
- test_simpleUploadWithDelegateProvidingInputStream was flaky due to the
expectation sometimes being fulfilled multiple times as it was
fulfilled in the urlSession(_:dataTask:didReceive:) delegate.
- Migrate this test to the SessionDelegate and add extra tests to check
the response and delegate callbacks for each HTTP method.
- For HTTPUploadDelegate, add the expectation fulfilment to a delegate
callback for urlSession(_ :task:didCompleteWithError:) so that
test_simpleUploadWithDelegate() still works.

URLSession: Update all task types with the byte count of sent data

---

CoreFoundation/NumberDate.subproj/CFTimeZone.c
Tests/Foundation/Tests/TestTimeZone.swift

This fixes TestDateFormatter.test_expectedTimeZone either.

[Windows] Fix TimeZone display name and daylight saving time check

---

Sources/Foundation/JSONEncoder.swift
Sources/Foundation/JSONSerialization.swift
Tests/Foundation/Tests/TestJSONEncoder.swift
Tests/Foundation/Tests/TestJSONSerialization.swift

Also fixes  SR-12275: JSONEncoder on Linux can't encode number JSON fragments
- JSONEncoder now encodes fragments by default to match Darwin.
- JSONDecoder now allows fragments when decoding to match Darwin.
- Update the following TestJSONEncoder tests now that fragments encode,
these tests now pass on Darwin:
test_encodingTopLevelSingleValueEnum
test_encodingTopLevelSingleValueEnum
test_encodingTopLevelSingleValueClass

JSONSerialization: Add support for .withoutEscapingSlashes, .fragmentsAllowed

---

TestFoundation/TestProcess.swift

When building Swift in a docker via `docker build`, `stdin` returns `EOF` at each read and there is nothing we can do about it.
Because of this, the tests `test_terminate` and `test_preStartEndState` fail because the helper exits w/ code 0 before the swift `Process` can terminate it.
This PR fixes this problem by setting a `Pipe` stdin to the `Process`es.

Fix Process tests that fails when stdin is empty

---

Sources/Foundation/NSLock.swift

Currently an attempt to pass an `Int` fails on platforms where `time_t` is 64-bit, such as WASI with its [wasi-libc](https://github.com/WebAssembly/wasi-libc/blob/320054e84f8f2440def3b1c8700cedb8fd697bf8/basics/include/__typedef_time_t.h).
(cc @compnerd)

Use time_t.init directly when calling timespec

---

CoreFoundation/StringEncodings.subproj/CFUniChar.c

These branches in CFUniChar.c are identical.
(cc @spevans)

Collapse #if branches for macOS/Linux/BSD

---

CoreFoundation/Base.subproj/CFPlatform.c
Tests/Foundation/Tests/TestNotificationQueue.swift

Unlike pthread-based implementation, TLS/FLS on Windows doesn't return NULL when reading value after destructor call.
To avoid that we have to nullify value in destructor callback.
The implementation needs to store key along with user data to perform proper cleanup.
This fixes crashes in `NotificationQueue` and `OperationQueue` on Windows.
Also introduced small delay in helper func of `TestNotificationQueue` to avoid false positive/false negative results in `test_defaultQueue` and `test_notificationQueueLifecycle`.

[Windows] CFThreadSpecific implementation allows access to deallocated value

---

CoreFoundation/PlugIn.subproj/CFBundle_InfoPlist.c

The header is deprecated and removed in 5.5 of the kernel which causes Swift not to build.

Removed Linux use of sys/sysctl.h

---

CoreFoundation/PlugIn.subproj/CFBundle_Resources.c

My rebasing dropped `CoreFoundation/PlugIn.subproj/CFBundle_Resources.c` from [this PR](https://github.com/apple/swift-corelibs-foundation/pull/2771). Thanks to @buttaface for pointing it out.

Another file to only include sys/sysctl.h if macOS or BSD

---

Tests/Foundation/Tests/TestOperationQueue.swift

There are some issues in current implementation. To keep things simple, I'd like to extend
test coverage of problem area first. Not all of new tests are expected to fail, but I find them useful
to have.
CC @compnerd

More tests for OperationQueue/Operaion

---

Tests/Foundation/Tests/TestFileManager.swift

A small test to ensure that Windows FSRs don't regress

[Windows] Added a test for _getFilesystemRepresentation

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

This fixes typos in code responsible for counting operations in queue.
CC @compnerd

Fix OperationQueue counters

---

Tests/Foundation/Tests/TestCalendar.swift

CI runs in UTC time zone, and this affects the description of TimeZone being tested.
CC @compnerd

Adjust test_dateFromDoesntMutate expectations

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

`Operation._queue` internal property does release stored value on every getter call. In most scenarios it is accessed exactly once, and balanced by "leaking" same value to Thread Specific storage. But under some conditions `_queue` is accessed twice, and crash is inevitable.
I strongly believe that property accessor should not release its value. Kind of typo for me. Operation already has the pair of `_adopt(queue:schedule:)`/`_invalidateQueue()` functions intended to manage ownership of queue, and they are used in proper places.
This patch
- prevents releasing of stored value in `Operation._queue` property getter
- balances retain count after current queue removed from thread-specific storage
- enables all available Operation/OperationQueue tests (including lifecycle test to make sure …

Balance OperationQueue retain/release

---

Sources/Foundation/JSONEncoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

- This was missing and is required to match Darwin.

SR-12696: Add JSONEncoder.OutputFormatting.withoutEscapingSlashes for Linux

---

Sources/Foundation/DateFormatter.swift
Tests/Foundation/Tests/TestDateFormatter.swift

Noticed the difference between macOS and Windows test results in our codebase (we are heavily dependent on date parsing). I have not found any docs about this, but actual results and deep debugging left no doubt about the mechanics.
Apple implementation checks for unparsed content in source string.
**Any non-whitespace** leftover characters are considered as failure.
On the other hand, **whitespaces are permitted** and should not affect the result.
Related to #1822 (SR-9322).
This patch alters verification logic to be closer to Apple implementation.
Not sure about `preconditionFailure` check, but that's really unexpected condition.
cc @compnerd @spevans

Allow whitespaces after parsed content in DateFormatter.date(from:)

---

CoreFoundation/String.subproj/CFString.c

Reverts apple/swift-corelibs-foundation#2793. We shouldn't need this now.

Revert "Work around ICU version < 62"

---

Sources/Foundation/NSData.swift

- Allocate the output buffer with an alignment of 4 bytes. In the main
encoding loop, data is written out as a UInt32 using .copyMemory()
instead of .storeBytes() as the output position can become unaligned
if EOL markers are written as well.
- This allows removal of the appendByteToResult() lexically scoped
helper function which was called three times and thus being outlined
to a separate function. The extra state that needed to be passed to it
caused extra memory traffic and this has now been eliminated.
- When converting the final output buffer into a String, use
String(decoding:as:) in preference to
String(bytesNoCopy:length:encoding:freeWhenDone:) as it is slightly
faster for string conversion, and there is no chance of it returning
nil since the input is known to be valid ASCII.
- …

Base64: Speedup encoding

---

CoreFoundation/Base.subproj/CFRuntime.c

PR #2782 references symbol __kCFAllocatorTypeID_CONST in CFRuntime.c but
this was removed in #1708. After interpreting the commit, it looks like
this symbol was renamed to _kCFRuntimeIDCFAllocator. Therefore, make
this rename again.

[CF] Rename remaining __kCFAllocatorTypeID_CONST.

---

Tests/Foundation/Tests/TestFileManager.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

- lastPathComponent is a NSString method so bridge appropiately.
- JSONEncoder.OutputFormatting.sortedKeys requires macOS 10.13, add an
#available around it.

Test fixes for Darwin

---

Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift
Tests/Foundation/Tests/TestFileManager.swift

URL.resolvingSymlinksInPath() now recursively resolves symlinks as in Darwin.

[SR-7857] URL.resolvingSymlinksInPath() now recursively resolves symlinks

---

Sources/Foundation/NSData.swift

- Use a lookup table to convert input ASCII to byte values. This is
faster and simpler than scanning through multiple ranges in a loop
for each input byte.
- Padding character '=' and invalid inputs both have bit 6 set in their
decoded value so that both values can be tested together.
- Fix the estimate of the output buffer size which was estimating it at
2/3 of input buffer size, not 3/4.

Base64: Speedup decoding fix #1

---

Sources/Foundation/Process.swift

The pointer value of it is not changed, which with `var` currently leads to this warning:
```
/Sources/Foundation/Process.swift:828:13: 
warning: variable 'fileActions' was never mutated; consider changing to 'let' constant
var fileActions = _CFPosixSpawnFileActionsAlloc()
```

Make fileActions constant, not variable in Process.swift

---

Sources/Foundation/NSData.swift

- Change the output buffer of NSData.base64DecodeBytes() from a [UInt8]
to an UnsafeMutableRawBufferPointer to avoid copying the result when
initialising the NSData object.
There are some benchmarks for the decoding PRs @ http://si.org/posts/2020/05/base64-decoding.html

Base64: Speedup decoding fix 2

---

CoreFoundation/URL.subproj/CFURLComponents_URIParser.c

Using a mix of signed and unsigned types here caused a librt call to __mulito4 to be emitted instead of properly lowering the call.

Use arguments of same type with _CFMultiplyBufferSizeWithoutOverflow

---

Sources/Foundation/NSData.swift

- NSData.base64DecodeBytes(): Change the input buffer from a
Collection<UInt8> to an UnsafeMutableRawBufferPointer as it
is faster to access.

Base64: Speedup decoding fix 3

---

Sources/Foundation/RunLoop.swift

These are for XCTest use only for now. This is to support appropriate changes to https://github.com/apple/swift-corelibs-xctest/pull/304.

Add SPI for sources and observers to RunLoop

---

CoreFoundation/Collections.subproj/CFBasicHash.c

This appears to have gotten lost in the recent Catalina merge.

[CF] Reapply #2626 (do not call malloc_size).

---

Tests/Foundation/Tests/TestRunLoop.swift

This ensures CFRunLoop correctly serves main dispatch queue.
Due to event specifics on Windows there was possibility to break
RunLoop making it think that main queue always has pending
work. The issue is adressed in apple/swift-corelibs-libdispatch#542.

Add test for main dispatch queue processing in CFRunLoop

---

Sources/Foundation/Data.swift
Sources/Foundation/NSData.swift

- Pass UnsafeRawBufferPointers to NSData.base64EncodeBytes() and make
the Data.base64EncodedString() and Data.base64EncodedData() methods
call it directly.
- There is considerable overhead in forwarding the methods from Data to
NSData. Making the Data methods directly call NSData.base64EncodeBytes()
removes this overhead.

Base64: Speedup encoding fix 3

---

DarwinCompatibilityTests.xcodeproj/project.pbxproj
Foundation.xcodeproj/project.pbxproj
Sources/Foundation/NSURL.swift
Tests/Foundation/CMakeLists.txt
Tests/Foundation/Tests/TestNSURL.swift
Tests/Foundation/Tests/TestURL.swift
Tests/Foundation/main.swift

- When NSURL._resolvingSymlinksInPath() was creating a new URL(), it
would use the default logic of checking if the file was a directory.
Override this behaviour and use the .hasDirectoryPath property of the
original NSURL when creating the resultant URL.
- Modify NSURL.standardized to remove use of force-unwrap.
- Add TestNSURL.swift for NSURL tests.

SR-12366: URL: standardizedFileURL inconsistent behavior on macOS and Linux

---

Sources/Foundation/NSStringAPI.swift
Tests/Foundation/Tests/TestNSString.swift

- https://developer.apple.com/documentation/swift/string/1410075-init

SR-12450: Add missing String.init(_ cocoaString: NSString) initialiser

---

Sources/Foundation/Scanner.swift
Tests/Foundation/Tests/TestNSGeometry.swift
Tests/Foundation/Tests/TestScanner.swift

- Use Float and Double initialisers directly when converting String to
value.
- This makes parsing String to floating point consistent with other floating
point conversion functions.
- Resolves SR-443

Scanner: When parsing floating point, use appropiate initialiser.

---

Tests/Foundation/Tests/TestNSNumber.swift

- Converting Double.leastNonzeroMagnitude with a Locale would result
in the value '0E+00' instead of the correct '5E-324' in some versions
of ICU (62-66). Disable the test against '0E+00' so that it wont break
upgrading to ICU67.

ICU: Disable a test in preperation for upgrading to ICU67

---

Tests/Foundation/Tests/TestProcess.swift

- This test is believed to have broken due to thread issues when reading
from stdout/stderr of the child process.
- The threading issue was fixed in https://github.com/apple/swift-corelibs-foundation/pull/2523

SR-9930: Re-enable assertion in TestProcess.test_passthrough_environment()

---

Sources/Foundation/FileManager+POSIX.swift
Tests/Foundation/Tests/TestFileManager.swift

If another thread creates one of the same directories in the target path, the `!fileExists` check may pass while the `mkdir` call fails with `EEXIST`. However, if the existing file is a directory, then that should still be a success.
Fixes [SR-12272](https://bugs.swift.org/browse/SR-12272).

Return success from `FileManager` recursive directory creation even if a directory was created by another thread concurrently.

---

Tests/Foundation/Tests/TestJSONEncoder.swift
Tests/Foundation/Tests/TestNSString.swift
Tests/Foundation/Tests/TestStream.swift
Tests/Foundation/Tests/TestURLSession.swift

- Use 'let' instead of 'var' on some immutable variables.
- TestJSONEncoder: Change a test struct from Codable to Encodable
as the contents are constant and cant be used for Decoding.

Fix more warnings.

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

The `URLError` received upon `URLSessionTask` cancellation by a `URLSessionTaskDelegate` or completion handler has a blank `userInfo` dictionary. This is an inconsistency when compared with macOS's Foundation and it makes actual error handling harder than it could be.
This PR fills it out to match the fields filled out by macOS Foundation.
I previously reported this as https://bugs.swift.org/browse/SR-13017, and I believe this fixes that (if a fix is even desirable, that is.)

Flesh out URLError information upon URLSessionTask cancellation

---

Tests/Foundation/Tests/TestNumberFormatter.swift

This seems to be failing on Windows, identified through YAMS.  The test
case is reduced from a test case originally provided by JP Simard
(@jpsim).

tests: add a test case that breaks on Windows

---

Sources/Foundation/NSError.swift
Tests/Foundation/Tests/TestNSError.swift
Tests/Foundation/main.swift

The convenience accessors (such as `URLError.failingURL`) were always returning `nil` because they hashed the key using the `NSString` hashValue rather than the `String` hashValue. This PR fixes this, and adds simple test cases to exercise each accessor.
Thanks @spevans for feedback about this in https://github.com/apple/swift-corelibs-foundation/pull/2825.
This fixes https://bugs.swift.org/browse/SR-13037

fix convenience accessors on CocoaError and URLError

---

Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

Fix typo and logic error in the overflow check in `integerMultiply()`, which was screwing up Decimal calculations under certain conditions.
I was able to reproduce on Android and spent hours tracking this down on there. I'm guessing it only worked on macOS because this code is unused on there.

SR-13015: Decimal calculation incorrect on Linux

---

Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

[5.3] SR-13015: Decimal calculation incorrect on Linux

---

Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/JSONSerialization.swift
Tests/Foundation/Tests/TestURLSession.swift

- TestURLSession: URLError.userInfo is now [String: Any] so remove
unnecessary as? cast.

Fix more var/let warnings.

---

Sources/Foundation/Host.swift

Foundation's Host.swift uses `getifaddrs` and `freeifaddrs`, which currently causes Android 6.0 or below to fail to link.
This PR changes these functions so they are called using `dlsym`, which allows Android 6.0 to link while providing full support on later versions of Android.
This is a replacement for PR https://github.com/apple/swift-corelibs-foundation/pull/2439.

Fix for Foundation on Android 6.0

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

This is a rollup of three OperationQueue fixes, #2776 #2777 #2779 
This is done as one PR as the some tests are disabled then enabled and  the commits overlap otherwise.

[5.3] OperationQueue fixes

---

Sources/Foundation/FileManager+POSIX.swift
Tests/Foundation/Tests/TestFileManager.swift

If another thread creates one of the same directories in the target path, the `!fileExists` check may pass while the `mkdir` call fails with `EEXIST`. However, if the existing file is a directory, then that should still be a success.
Fixes [SR-12272](https://bugs.swift.org/browse/SR-12272).
(cherry picked from commit b6eea02e84ea46e8bc36588f250d36930fe2ee80)

[5.3] Return success from `FileManager` recursive directory creation even if a directory was created by another thread concurrently.

---

Sources/Foundation/NSDecimalNumber.swift
Sources/Foundation/NSNumber.swift
Tests/Foundation/Tests/TestDecimal.swift

- NSDecimalNumber: When compare(_:) / isEqual(_:) has a rhs which is an
NSNumber that cannot be cast as an NSDecimalNumber, use
NSNumber.compare() to test them.
- NSNumber: Add missing isEqual(to:)

NSDecimalNumber: Fix comparison with NSNumber

---

Sources/Foundation/NSError.swift
Tests/Foundation/Tests/TestNSError.swift
Tests/Foundation/main.swift

- fixes SR-13037 (https://bugs.swift.org/browse/SR-13037)
(previously merged to master in #2828)

[5.3] fix convenience accessors on CocoaError and URLError

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

- fixes SR-13017 (https://bugs.swift.org/browse/SR-13017)
(previously merged to master in #2825)

[5.3] improve URLError returned upon task cancellation

---

Foundation/JSONEncoder.swift
Foundation/JSONSerialization.swift
TestFoundation/TestJSONEncoder.swift
TestFoundation/TestJSONSerialization.swift

Backport of https://github.com/apple/swift-corelibs-foundation/pull/2713 to Swift 5.2
Resolves [SR-13173](https://bugs.swift.org/browse/SR-13173) Foundation.JSONEncoder + Swift 5.2.4 + .allowFragments difference between macOS and Linux
Please sanity check @millenomi, I don't think there's a reason to not backport this?
The mac behavior on 2.5.4 is already allowing this, it's just corelibs that doesn't on that version (and it's good since a while now on 5.3).
FYI @drexin 
Thanks!

[5.2] SR-12275: JSONEncoder on Linux can't encode number JSON fragments

---

Foundation/Decimal.swift
TestFoundation/TestDecimal.swift

From #2827, see explanation there.

[5.2] SR-13015: Decimal calculation incorrect on Linux

---

Foundation/URLSession/URLSessionTask.swift
TestFoundation/TestURLSession.swift

previously merged to master in https://github.com/apple/swift-corelibs-foundation/pull/2825

[5.2] improve URLError returned upon task cancellation

---

Foundation/NSError.swift
TestFoundation/TestNSError.swift
TestFoundation/main.swift

- fixes SR-13037 (https://bugs.swift.org/browse/SR-13037)
(previously merged to master in https://github.com/apple/swift-corelibs-foundation/pull/2828)

[5.2] fix convenience accessors on CocoaError and URLError

---

Sources/Foundation/NSURL.swift
Tests/Foundation/Tests/TestURL.swift

The `path` property of `NSURL` contains important code for handling absolute paths with drive letters.
This adds similar handling to `relativePath`. Otherwise URLs like `C:\Some\Path` would report invalid relative path starting with `/C:`.

[Windows] Fix NSURL.relativePath

---

CMakeLists.txt
CoreFoundation/Base.subproj/static/module.map
CoreFoundation/Parsing.subproj/static/module.map
CoreFoundation/URL.subproj/static/module.map

The static libraries need to link against additional dependencies, which are listed in the newly added modulemaps

Add modulemaps that work for statically compiled Foundation

---

Sources/UUID/CMakeLists.txt

When building the shared libs, this will be included in `libFoundation.so`, but when building the static libs, we have to install it with the other libraries, so it can be found when linking user binaries.

Install uuid when statically building Foundation

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt
cmake/modules/SwiftSupport.cmake

Add support for installation for macOS targets to the CMake
installation.  Centralise the logic for the installation of the files.
This properly handles the installation of the swiftdoc, swiftinterface,
swiftmodule and the runtime libraries across all the platforms in either
static or shared configurations.

build: centralise the install logic for the Swift modules

---

Sources/Foundation/NSData.swift
Sources/Foundation/NSPathUtilities.swift
Tests/Foundation/Tests/TestNSData.swift

**Problem**
`Data.write(to:)` is a only method in the Foundation that can create a
regular file.
However, it ignores `umask` and always set 0600 permission unlike
macOS Foundation, which respects process `umask`.
**Solution**
1. With `.atomic` write option
It uses `mkstemp(3)` in `_NSCreateTemporaryFile`, which is always
creating a file with 0600 permission, if the system follows
the latest POSIX specification or the permission is undefined.
On macOS Foundation, therefore `_NSCreateTemporaryFile` uses
`mktemp(3)` and `open(2)` instead to respect `umask`.
2. Without `.atomic` write option
It uses `0o600` even if it uses `open(2)` that respects `umask`.
Simply gives `0o666` instead.
This is a bug caused by previous commit in
apple/swift-corelibs-foundation#1876.
Swift JIRA is …

Create a file with permissions that respects umask

---

Sources/Foundation/URLComponents.swift

Gets rid of using deprecated String.Index(utf16Offset:in:) in URLComponents

Gets rid of using deprecated String.Index(utf16Offset:in:)

---

CoreFoundation/Base.subproj/CFAvailability.h

The syntax relied upon by CF_ENUM does not align with the intent of the C++ feature, and that correction extends to its use in C mode. Add a temporary fix that 'swallows' the user-supplied `typealias` by defining a dummy type, and then does a forward-definition-then-typedef-then-enum-opening dance to apply the correct syntax.

Make CF_ENUM compatible with -Welaborated-enum-base

---

CoreFoundation/Preferences.subproj/CFPreferences.c

Fixes memory leak in _CFPreferencesURLForStandardDomainWithSafetyLevel
Rename function according to convention to stop static analyzer complaining on overreleasing
Fix memory leak (extra retain) in function fetchVolatileValue
Remove not used variable from function CFPreferencesSetMultiple
Remove not used allocator in function _preferencesDirectoryForUserHostSafetyLevel

Fixes 5 static analyser issues in CFPreferences.c

---

CoreFoundation/Base.subproj/CFPlatform.c

Firstly, `_CFProcessPath` has no implementation for TARGET_OS_BSD. Indeed,
there is no portable implementation of this action across multiple
platforms. As an initial implementation for TARGET_OS_BSD, use the
environment to help us. Some shells set the environment variable "_" to
the path used to invoke the binary. This mirrors the implementation for
TARGET_OS_OSX, so add the same conditionals on `__CFProcessIsRestricted`.
Relying on the shell has drawbacks, including that the shell doesn't set
the full path to the current executable if it isn't part of the PATH
(or, of course, specified explicitly). Perhaps on some other platforms
there is some miscellaneous kernel trickery that could be done, but
let's defer that to the future and keep getenv("_") as a last resort.
Second, given that, …

[CF] Unify implementations of _CFProcessPath.

---

Sources/Foundation/RunLoop.swift

`me.hashValue` is `Int`, and `CFHashCode` is `UInt`, so they have the same size.

Avoid a crash when the hash value of a shimmed run loop source is negative

---

CoreFoundation/URL.subproj/CFURL.c

Do not attempt to read characters from this string if it's empty.

URL.appendingPathComponent("") crashes

---

Sources/FoundationNetworking/URLResponse.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift

- WWW-Authenticate must canonicalize with 'WWW' uppercase.
- The session delegate must be consulted for authentication even for tasks that have completion blocks.
https://bugs.swift.org/browse/SR-12676

Fix authentication through the session task delegate (SR-12676)

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

Remove the absolute path to the host toolchain's stdlib from the three Foundation shared libraries. Also, add it as a CMake `BUILD_PATH` to plutil, so that it's removed upon installation.
Otherwise, you see the following in the latest official 5.3 snapshot release for linux:
```
> readelf -d swift-5.3-DEVELOPMENT-SNAPSHOT-2020-05-04-a-ubuntu18.04/usr/lib/swift/linux/libFoundation*so swift-5.3-DEVELOPMENT-SNAPSHOT-2020-05-04-a-ubuntu18.04/usr/bin/plutil | ag "File:|runpath"
File: swift-5.3-DEVELOPMENT-SNAPSHOT-2020-05-04-a-ubuntu18.04/usr/lib/swift/linux/libFoundation.so
0x000000000000001d (RUNPATH)            Library runpath: [/home/buildnode/jenkins/workspace/oss-swift-5.3-package-linux-ubuntu-18_04/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:$ORIGIN]
File: …
```

[CMake] fix runpath for ELF platforms

---

CoreFoundation/Base.subproj/SwiftRuntime/TargetConditionals.h

These are required for WebAssembly and WASI support in CoreFoundation.

Add TARGET_{CPU_WASM32,OS_WASI} to TargetConditionals.h

---

CMakeLists.txt
CoreFoundation/Base.subproj/static/module.map
CoreFoundation/Parsing.subproj/static/module.map
CoreFoundation/URL.subproj/static/module.map

The static libraries need to link against additional dependencies, which are listed in the newly added modulemaps

[5.3] Add modulemaps that work for statically compiled Foundation

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

Remove the absolute path to the host toolchain's stdlib from the three Foundation shared libraries.
@millenomi, here you go.

[5.3][CMake] fix runpath for ELF platforms

---

CoreFoundation/Base.subproj/CFLocking.h

WebAssembly/WASI doesn't support multi-threading yet (as reported in SR-12097), so these primitives don't do anything in this single-threaded environment, but allow the rest of the code using them to compile.

Add locking primitives for TARGET_OS_WASI in CFLocking.h

---

Tests/Foundation/Tests/TestProcess.swift
Tests/Tools/XDGTestHelper/main.swift

Fix `TestProcess.test_passthrough_environment` fails when an environment variable has multiple lines.

Fix test fail triggered by multiline environment variables

---

Sources/Foundation/Bridging.swift

Currently bridging may crash on `as!` if you try to cast `[T]` to `NSArray` where T is not inherit from of NSObject
Before https://github.com/apple/swift-corelibs-foundation/pull/1526 such cases covered by boxing into __SwiftValue. This change restores that behavior

[RFC] Restore using __SwiftValue in store on Linux

---

Sources/Foundation/Port.swift
Sources/Foundation/RunLoop.swift
Sources/Foundation/Stream.swift

See https://forums.swift.org/t/formalizing-the-unavailability-of-core-foundation/40216 for details.

Remove all uses of CF from the framework's interface outside of Linux or Darwin.

---

CoreFoundation/Parsing.subproj/CFXMLInterface.c
Sources/FoundationXML/XMLParser.swift
Tests/Foundation/Tests/TestXMLParser.swift

SR-2301 was mostly fixed by pull request #700 (commit 30b17ed) in 2016.
The fix however still does not call the endDocument callback.
This pull request adds the necessary end of document signaling to SAX.
This pull also fixes several minor (rare) bugs like unchecked error conditions, incorrect handling of small chuncks, etc.
Please note the change in CFXMLInterface: I’m not  sure if this is the best place to handle this. The interface is undocumented and returning an error that the end of the document has been reached when you send the last piece of data was unexpected. Even more so since the meaning of the return values is undocumented and the internal (SAX) errors are not mapped to the ErrorCode enum of XMLParser (Leaving this for a different fix).

Adds missing call of endDocument, fixes SR-2301

---

Tests/Foundation/Tests/TestBridging.swift

I am getting crash when trying to perform dynamic cast like this:
```
let anyArray: Any = [TestClass()]
let maybeObject = anyArray as? NSObject
```
```
Could not cast value of type 'TestFoundation.TestBridging.(unknown context at $7ff798798298).(unknown context at $7ff7987982a0).TestClass' (00007FF7988CC248) to 'Foundation.NSObject' (00007FFD7253A528). 
```
While it is possibly a bug in new dynamic casting in compiler, I think it is good to cover it with test already.

Add failing test for dynamic cast

---

Sources/Foundation/Bridging.swift
Sources/Foundation/Bundle.swift
Sources/Foundation/DateIntervalFormatter.swift
Sources/Foundation/NSArray.swift
Sources/Foundation/NSAttributedString.swift
Sources/Foundation/NSCalendar.swift
Sources/Foundation/NSCharacterSet.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSDate.swift
Sources/Foundation/NSDictionary.swift
Sources/Foundation/NSError.swift
Sources/Foundation/NSLocale.swift
Sources/Foundation/NSNumber.swift
Sources/Foundation/NSSet.swift
Sources/Foundation/NSString.swift
Sources/Foundation/NSTimeZone.swift
Sources/Foundation/NSURL.swift

Windows is seeing deserialization errors when dealing with `_CFBridgeable`; the protocol was slated for removal anyway, and it can be removed now.
Note that `_cfObject` still exists for all objects that implemented that protocol. This merely removes the protocol, the conformance and reworks the constraints associated with it.

Remove _CFBridgeable

---

CoreFoundation/Base.subproj/CFInternal.h

Atomics are not supported on WASI due to SR-12097. `<xlocale.h>` header is also not available as WASI hosts do not ship locale or time zone files and it's a responsibility of applications to bundle that data.

Add support for WASI in CFInternal.h

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

Dispatch is not available on WASI due to SR-12097. Atomic shims such as `OSAtomicCompareAndSwapPtr` are made available as they would have a no-op implementation for compatibility in a separate PR.

Add WASI support in CoreFoundation_Prefix.h

---

Sources/Foundation/NSSet.swift
Tests/Foundation/Tests/TestNSSet.swift

This initializer exists in the macOS version of Foundation, but isn't present on Linux/Windows.
While it doesn't add any new functionality, it simplifies porting existing code to those platforms.

NSSet: add missing convenience initializer

---

Sources/Foundation/FileManager.swift

Ensure that we pass along the creation date from `stat` when querying
the attributes of an item.  This was being dropped resulting in the
creation date for files being unavailable.
Partially addresses SR-13617

Foundation: populate the `.creationDate` attribute on Windows

---

Sources/Foundation/NSError.swift

This is generally not a very helpful constant for Windows, however, it
can be passed from Dispatch in some cases.  Lets just provide the
mapping for the Windows version.

Foundation: map `ECANCELED` properly for Windows

---

Foundation.xcodeproj/project.pbxproj
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationNetworking/URLSession/URLSessionDelegate.swift
Sources/FoundationNetworking/URLSession/URLSessionTaskMetrics.swift

Starts fixing [SR-11518](https://bugs.swift.org/browse/SR-11518) and makes a port of [Alamofire](https://github.com/alamofire/alamofire) much easier.
This PR adds `URLSessionTaskMetrics` and its associated types (`URLSessionTaskTransactionMetrics`, etc.), as well as the `urlSession(_:task:didFinishCollecting:)` `URLSessionTaskDelegate` method. It does not include:
* Documentation
* (If there's a standard way of copying documentation, I'm happy to do that.)
* Tests
* Implementation

Add URLSessionTaskMetrics

---

Sources/Foundation/NSIndexSet.swift
Tests/Foundation/Tests/TestIndexSet.swift

We noticed that `NSIndexSet` is missing implementation of `hash` property. Not a big deal, as NSObject provides default hash, but there are some cons:
- Equal `NSIndexSet`s would have different hashes based on their object identifier
- `IndexSet` is backed by `NSIndexSet`, deriving same inconvenience
- This behavior is not consistent with Apple Foundation
After some experiments with NSIndexSet from macOS Foundation, these details were observed:
- Calculation complexity is O(1). No matter how many indexes/ranges is stored, `hash` is always fast.
- The only parameters affecting hash are: count of indexes, first and last index value. This explains constant complexity.
- Empty index set has hash equal to 0.
I think the most important detail here is calculation speed, because my first thoughts …

Hash implementation for NSIndexSet

---

Sources/Foundation/NSString.swift
Tests/Foundation/Tests/TestNSString.swift

This adds `CVarArg` protocol support to `NSString` and `String`.
```
print(String(format: "Testing %@ %@ %@", "One", "Two", "Three"))
Testing One Two Three
```
`NSString` support was easy since `%@` already exists for `CFString` in CoreFoundation.
`String` was a little bit more challenging, since `withVaList` doesn't provide an autorelease pool to retain the required `NSString` instance, which is needed for the `CFString`.
I solved this by using `OperationQueue` to schedule the release.  I'm not sure if there are any other options at this point.
This resolves [SR-957](https://bugs.swift.org/browse/SR-957).

Added CVarArg support to NSString and String

---

Sources/Foundation/RunLoop.swift

Making `cfSource` a member within the structure prevents allowing
overriding of the `open` class as the type it returns cannot be
deserialised.  Because the member is not a stored property, extract it
to an extension which removes it from the vtable.  This allows the use
of the private type in an external context.

Foundation: extract `cfSource` from `RunLoop._Source`

---

Sources/Foundation/JSONEncoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

Cherry-pick https://github.com/apple/swift-corelibs-foundation/pull/2781/commits to 5.3.
---
The underlying functionality for  `.withoutEscapingSlashes` is already in 5.3, but it is not currently exposed on JSONEncoder.  Add it to match Darwin.

[5.3] SR-12696: Add JSONEncoder.OutputFormatting.withoutEscapingSlashes for Linux

---

Tests/Foundation/Tests/TestJSONEncoder.swift

The value `2.7976931348623158e+308` is a perfectly valid JSON number
and should be accepted.  This test is only passing today because the Swift
standard library's `Double(_ String:)` initializer currently has a bug that
rejects numbers larger than the maximum Double value.
But we're getting ready to fix that bug in the Swift standard library,
(apple/swift#34339) which will break this test when it lands.
(After that PR lands, we should update this again to verify that this value
parses to `Double.infinity`.)

Remove an invalid numeric JSON test

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/NumberDate.subproj/CFDate.c

libdispatch uses `QueryUnbiasedInterruptTimePrecise` as base time source for timers. This changes CoreFoundation to use same source to schedule timers properly.
Current implementation is observed to work in most cases, because `QueryPerformanceCounter` could return same value as `QueryUnbiasedInterruptTimePrecise`. E.g. it provides reliable values on Windows VM hosted on my MacBook, as well as on cloud CI agents (GitHub Actions/Azure Pipelines). Perhaps virtualization affects the result. But on my Windows desktop these two sources return incomparably different values, making CFRunLoop unable to calculate correct timeout deadline.
The issue comes out as hang of `TestNotificationQueue.test_postNowForDefaultRunLoopMode` test. I also had similar problem with s-p-m, and this change fixes it as …

[Windows] Make mach_absolute_time implementation consistent with libdispatch

---

Sources/Foundation/NSAttributedString.swift
Tests/Foundation/Tests/TestNSAttributedString.swift

The current implementation of NSMutableAttributedString crashes if an attributed string change length while an enumeration
We expect similar behavior to Darwin Foundation's NSMutableAttributedString: enumeration should be continued
Also implemented NSAttributedString.description (similar to Darwin version)

Fix crashes in NSMutableAttributedString: modify in an enumeration

---

Sources/Foundation/FileManager.swift

rather than [repeating that logic](https://github.com/apple/swift-corelibs-foundation/blob/0f06824e7f81393614201fc67d1d740a8f913df7/Sources/Foundation/NSURL.swift#L2109)
The last case in stat.creationDate also works for Android.
Note that it uses `st_birthtimespec` instead on Darwin, let me know if that makes a difference. @compnerd, this pull redoes #2884 because it didn't work on Android and to reuse the existing logic, let me know what you think.

[FileManager] _attributesOfItem: use creationDate from the stat extension in NSURL

---

Sources/Foundation/FileManager.swift
Sources/Foundation/NSError.swift
Sources/Foundation/NSSwiftRuntime.swift
Sources/Tools/plutil/main.swift
Tests/Foundation/HTTPServer.swift

The Windows environment calls the library `CRT`.  Additionally, this
enables the removal of the `visualc` module from the Swift SDK overlay
for Windows.

Foundation: migrate to the new `CRT` module

---

Sources/Foundation/NSPathUtilities.swift
Tests/Foundation/Tests/TestFileManager.swift

NSTemporaryDirectory on Darwin returns path with trailing slash, and almost every test in TestFileManager counts on it.
Without slash tests are generating temporary paths like `C:\Users\user\AppData\Temptest_isReadableFile5004BFCF-4356-4000-8000-000000000000`, which is, obviously, out of Temp directory.
Non-Darwin and non-Windows platforms have already implemented similar workaround, so I just adapted existing solution for Windows.

[Windows] Add trailing slash to NSTemporaryDirectory result

---

Tests/Foundation/Tests/TestFileManager.swift

Staying inside the directory breaks cleanup on tear down. This is part 1 of 2 of FileManager tests cleanup improvements. Second part is not specific to Windows, so goes separately.

[Windows] Restore original working directory in TestFileManager.test_windowsPaths

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CFRuntime.c

CoreFoundation thread local storage on Windows is based on FLS API. FLS provides automatic cleanup of storage, and it is already got used. Old manual cleanup is not needed anymore.
We have observed often crashes in thread cleanup routines of CRT. Despite I didn't manage to extract the issue out of live project code, I suppose that mixing TLS and FLS in cleanup code could eventually corrupt the storage. Replacing `TlsGetValue` with `FlsGetValue` brings desired stability, but, as the code is obsolete, we could just remove it.

[Windows] Fix thread local storage cleanup

---

Sources/Foundation/FileHandle.swift

`acceptConnectionInBackgroundAndNotify(forModes:)` is already
unavailable on Windows.  This makes the helper functional also
unavailable on Windows as `SOCKET` is not a `FileHandle` on Windows.

Foundation: drop `acceptConnectionInBackgroundAndNotify` on Windows

---

Tests/Foundation/Tests/TestFileManager.swift

Most of tests in `TestFileManager` do cleanup of created content, but some are missing it. After several days of re-running Foundation test suite Temp folder is full of abandoned files. While it is not a big deal (this is temp folder after all), I think it is good to be tidy and do some trivial cleanup.
This change is complement to #2909

Improve cleanup in FileManager tests

---

Sources/Foundation/NSError.swift
Tests/Foundation/Tests/TestNSError.swift

Error->NSError conversion in Darwin Foundation fills `domain` and `code` even if provided Error does not conform to CustomNSError. This patch brings same behavior to swift-corelibs-foundation.

Improve Error to NSError conversion

---

Sources/Foundation/FileHandle.swift
Sources/Foundation/Process.swift

Add a SPI for Windows to get the raw `HANDLE` to enable use of `Pipe`
where a raw file descriptor may be needed.

Foundation: expose `_handle` from `FileHandle` on Windows

---

Tests/Foundation/Tests/TestFileManager.swift

Broken since #2910. `validPathSeps` is internal to SwiftFoundation
and can't be accessed from Compatibility tests.
I think it is ok to define expected values in local scope of test.

Fix Darwin Compatibility Tests build

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/NumberDate.subproj/CFDate.c

Copied from #2907. The diff is exactly same. Considered safe and worth to port to 5.3.

[5.3] Make mach_absolute_time implementation consistent with libdispatch

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h

Fixed lstat warning by including <sys/stat.h>.

Partially fixes SR-13831: Warnings while building on Linux.

---

Tests/Foundation/Tests/TestPipe.swift

The Windows CI was broken due to availability checks being supported in
the compiler causing the build to fail due to the `fileDescriptor` being
unavailable.

Tests: repair the Windows CI

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CFRuntime.c

Copied from #2902. The diff is exactly same. Considered safe and worth to port to 5.3.

[5.3] Windows, remove obsolete TLS finalization

---

Sources/Foundation/Data.swift
Sources/Foundation/NSLock.swift
Sources/Foundation/Thread.swift

These files rely on Glibc declarations in their public interface, even though they don’t import Glibc. Currently, these declarations are discovered through CoreFoundation, but due to implementation details, Swift canonicalizes the declarations and at the end uses declarations from Glibc (which is imported by other files in the module). This confuses `@_implementationOnly` checker to recognize these declarations as visible even though they shouldn't be.
This is fragile as Foundation now relies on implementation details of Glibc, which in fact we are trying to change in https://github.com/apple/swift/pull/32404.
This PR fixes the issue by explicitly importing Glibc in affected files.

Explicitly import Glibc in files that rely on it

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Locale.subproj/CFCalendar_Internal.h

This is exported as a C header but in C++ mode `ucal.h` will expose templates that aren't valid. This will hopefully fix the Linux build for https://github.com/apple/swift/pull/32721.

[cxx-interop] Fix two headers to be valid in C++ mode.

---

Sources/Foundation/NSPathUtilities.swift

- Fixes "warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'"

NSPathUtilities: Replace mktemp(3) with mkstemp(3)

---

Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

- The early check to return 0 if there were too many trailing zeros
before the decimal point (> UInt64.max) or too many leading zeros
after the decimal point didnt allow for a large enough negative
exponent.
- Also resolves SR-2980

SR-7236: NSDecimalNumber `.intValue` reporting 0 on numbers with many decimals

---

Sources/FoundationNetworking/URLProtectionSpace.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPMessage.swift
Sources/FoundationNetworking/URLSession/Message.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLProtectionSpace.swift

Basic implementation of "Www-Authenticate" parsing. Some real-life responses could crash previous implementation, as it doesn't work with realm in case insensitive way. We decided to modify existing (but unused) internal helper, considering that a good step in iterative improvement of FoundationNetworking.
This also fixes access to "Www-Authenticate" header in some places,
as HTTPURLResponse does capitalize headers after #2728.

Create URL Protection Space from HTTPURLResponse

---

Sources/Foundation/Process.swift
Tests/Foundation/Tests/TestProcess.swift
Tests/Tools/XDGTestHelper/main.swift

- Unify use of posix_spawnattr_t between Darwin and other platforms,
and set the POSIX_SPAWN_SETPGROUP attribute.
- This matches Darwin's behaviour.

SR-13861: Process should spawn a child process it its own process group.

---

CoreFoundation/URL.subproj/CFURLComponents.c
CoreFoundation/URL.subproj/CFURLComponents.h
Sources/Foundation/NSURL.swift
Sources/Foundation/URLComponents.swift
Tests/Foundation/Tests/TestURLComponents.swift

rdar://59439703 (URLComponents.percentEncodedQueryItems missing on linux)
resubmission of #2870 against `main`

Add support and tests for URLComponents.percentEncodedQueryItems

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

OperationQueue would crash or hang if we force "non-natural" execution order. E.g. when first operation depends on second.
The reason is how we work with internal operation lists in `OperationQueue._schedule()`. I believe the original intention was to adjust `__nextPriorityOperation`, but instead we are modifying `__nextOperation`. This has no sense and leads to crosslinking of the main operation list and corresponding priority operation list. Subsequent scheduling would try to read already finished operation and hang. Also, at this point queue doesn't hold operation object anymore, so trying to read dead object is pretty realistic scenario.
Suggested test case checks scenario described above, and ensures correct operation order as a bonus.

Fix OperationQueue scheduling logic to prevent disruption of operation lists

---

CoreFoundation/URL.subproj/CFURLComponents.c
CoreFoundation/URL.subproj/CFURLComponents.h

CoreFoundation changes to enable URLComponents.percentEncodedQueryItems
Fixes from @millenomi
- Constant strings must be correctly memory-managed in SCF.
- Do not associate API availability to CFURLComponents calls when compiling SCF on Darwin

CoreFoundation changes to enable URLComponents.percentEncodedQueryItems

---

Tests/Foundation/Tests/TestNSError.swift

FoundationTest build on macOS has been broken since #2912.
Compilation fails with error `cannot convert value of type 'SwiftError' to type 'NSError' in coercion`.
I guess we have to exclude related tests on Darwin platform, but leave them in DarwinCompatibilityTests.

Fix FoundationTest build on macOS

---

Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/NSDate.swift
Tests/Foundation/Tests/TestFileManager.swift

The `_updateTimes` function is multiplying by `1.0e9` as if for nanoseconds, but it should be using `1.0e6` for microseconds.
The `timeval.tv_usec` value will be too large, hence the `EINVAL` errno on Raspberry Pi OS (SR-13300).

[SR-13300] FileManager _updateTimes (microseconds)

---

Sources/Foundation/ProcessInfo.swift
Tests/Foundation/Tests/TestProcessInfo.swift
Tests/Foundation/Utilities.swift

- For Linux, take into account CFS quotes eg, if running under Docker.
- Based on swift-nio code, https://github.com/apple/swift-nio/pull/1518
Tested on a docker instance:
```
$ docker run -it --rm --privileged --cpus=1 swift-main-test /main-test/usr/bin/swift
Welcome to Swift version 5.3-dev (LLVM d6fb8423828a5e4, Swift 638d5e7be2d38c7).
Type :help for assistance.
1>  import Foundation; ProcessInfo.processInfo.activeProcessorCount
$R0: Int = 1
$ docker run -it --rm --privileged --cpus=2 swift-main-test /main-test/usr/bin/swift
Welcome to Swift version 5.3-dev (LLVM d6fb8423828a5e4, Swift 638d5e7be2d38c7).
Type :help for assistance.
1>  import Foundation; ProcessInfo.processInfo.activeProcessorCount
$R0: Int = 2
$ docker run -it --rm --privileged --cpus=5 swift-main-test …
```

SR-12833: processInfo.activeProcessorCount ignores CFS quotas

---

Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift
Tests/Foundation/Tests/TestJSONEncoder.swift
Tests/Foundation/Tests/TestJSONSerialization.swift

- If a Double is close but less than UInt64.max, then UInt64(value) can
crash. Add a check to provide the next closest value.
- Bounds check the exponent when converting a Double to Decimal.
This prevents initialising from Double values that cannot be
stored correctly.
- Add extra checks when passing _length and _exponent to initializers.

SR-13837: Swift Decimal type crashes on a specific double value

---

Sources/Foundation/Process.swift

I hit this when trying to cross-compile with apple/swift#33724 for Android with the Dec. 5 trunk source snapshot. I'm going to set up a CI soon for Android cross-compilation of the SDK and some Swift packages for both the trunk and release branches, which will catch such regressions faster.
I ran the tests natively on Android with the Dec. 11 source snapshot and this pull, got the same failing tests as with ~this pull~#2928 reverted (some URLComponents tests now trap unrelated to this pull).
@spevans, would be good to get this in before the 5.4 branch.

Process: Adapt #2928 for Android

---

Sources/Foundation/FileHandle.swift
Tests/Foundation/Tests/TestFileHandle.swift

- Setting closeOnDealloc to false seems to cause a stack Overflow on
Windows so disable the functionality of NOT closing the file, but only
on Windows.
#2932 Causes a stack overflow on windows so disable the  functionality and tests on Windows

SR-13822: FileHandle closeOnDealloc causes a Stack Overflow on Windows

---

Sources/Foundation/Boxing.swift
Sources/Foundation/NSKeyedArchiver.swift
Sources/Foundation/NSKeyedUnarchiver.swift
Sources/Foundation/NSObject.swift
Sources/Foundation/Port.swift
Sources/Foundation/Stream.swift
Sources/FoundationNetworking/URLSession/BodySource.swift
Sources/FoundationNetworking/URLSession/URLSession.swift
Sources/FoundationNetworking/URLSession/libcurl/EasyHandle.swift
Sources/FoundationXML/XMLParser.swift

- Fixes 'warning: using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead'

Convert protocol ... : class to protocol ... : AnyObject

---

Sources/Foundation/Stream.swift

- Make func stream(_ aStream: Stream, handle eventCode: Stream.Event)
public.
This was tested by building a local toolchain and then compiling the test file from https://bugs.swift.org/browse/SR-12981
```
$ cat test.swift 
class Foo: NSObject, StreamDelegate {}
$ ~/swift-DEVELOPMENT-SNAPSHOT-2020-12-14-a-ubuntu20.04/usr/bin/swiftc -o test1 test.swift 
test.swift:2:7: error: type 'Foo' does not conform to protocol 'StreamDelegate'
class Foo: NSObject, StreamDelegate {}
^
Foundation.StreamDelegate:2:10: note: protocol requires function 'stream(_:handle:)' with type '(Stream, Stream.Event) -> ()'
func stream(_ aStream: Stream, handle eventCode: Stream.Event)
^
$ ~/swift-build/toolchains/main-test/usr/bin/swiftc -o test1 test.swift
$
```

SR-12981: Foundation.StreamDelegate has required methods on Linux but not Darwin

---

Sources/Foundation/Date.swift
Tests/Foundation/Tests/TestDate.swift

(cherry picked from commit 65ca91c724dc744da4fe1f241dec04eb1df93531)

[5.3] Date: Add distance(to:) and advanced(by:) introduced in macOS 10.15

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

To be able to run operations concurrently OperationQueue needs concurrent underlying DispatchQueue. This patch uses `.concurrent` attribute to create DispatchQueues with required behavior.
This matches with Darwin.

Fix concurrent operations execution in OperationQueue

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

This is rebased version of #2497. Original request seems abandoned, but changes are useful. All credit goes to @dannliu.
Latest Foundation still has this issue: BlockOperation stores first execution block into the internal array along with a second execution block. As the result:
- unexpected value is returned by `executionBlocks`
- first block will be run twice.
Also `@convention(block)` specifier in `executionBlocks` makes dynamic cast crash on return. Looks like it could be safely removed.

Fix BlockOperation with multiple execution blocks

---

Sources/Foundation/FileHandle.swift
Tests/Foundation/Tests/TestFileHandle.swift

- Setting closeOnDealloc to false seems to cause a stack Overflow on
Windows so disable the functionality of NOT closing the file, but only
on Windows.
(cherry picked from commit 42a5b306e25458784796e606ba83ed4c7ef7d08f)

[5.4] SR-13822: FileHandle closeOnDealloc causes a Stack Overflow on Windows

---

Sources/Foundation/Stream.swift

- Make func stream(_ aStream: Stream, handle eventCode: Stream.Event)
public.
(cherry picked from commit 9bd879b16bd0f41b6d6dfcd0eb25a0cbcf7ca309)

[5.4] SR-12981: Foundation.StreamDelegate has required methods on Linux but not Darwin

---

Tests/Foundation/HTTPServer.swift

Leaving server running consumes one thread from Dispatch global thread pool per one started `LoopbackServerTest`. There are 5 such test cases at the moment.
On non-Darwin platforms thread pool size is extremely small (equals to the number of CPU cores), and TestFoundation test suite quickly becomes unstable on some machines (e.g. cloud VMs with 2-core CPUs).
This has no significant impact on current CMake-generated tests, as they are started as separate process each, but trying to run whole TestFoundation suite would hang or fail some trivial tests just because global queue is stuck.

TestFoundation: stop internal http server on test case tear down

---

Sources/Foundation/NSNumber.swift
Tests/Foundation/Tests/TestNSNumber.swift

- The previous behaviour was matching a buggy macOS implementation
but has been fixed in recent versions.

NSNumber: .boolValue should return true for Int64.min

---

Sources/Foundation/NSNumber.swift

- eg `NSNumber(value: 1.2) as! Int` would return 0 instead of trapping.
Exit with fatalError() if the bridging failed.
- This matches Darwin.
Cant add a test for trapping behaviour but a toolchain was tested v 5.3.1
```
$ cat bridge.swift 
let x = NSNumber(value: 1.2) as? Int
let y = NSNumber(value: 1.2) as! Int
print(x as Any, y)
$ ~/swift-5.3.1-RELEASE-ubuntu20.04/usr/bin/swift bridge.swift 
nil 0
$ ~/swift-build/toolchains/main-test/usr/bin/swift bridge.swift 
Foundation/NSNumber.swift:373: Fatal error: Unable to bridge NSNumber to Int
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
.
.
.
Illegal instruction (core dumped)
```

NSNumber: Forced bridging an invalid value would not trap.

---

Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

- If the exponent is too large for Int8 then return nil instead of NaN.
- This matches Darwin's behaviour.

Decimal: init?(string:) and scanDecimal() should return nil on error.

---

Sources/Foundation/FileManager+Win32.swift
Tests/Foundation/Tests/TestFileManager.swift

Use [`GetBinaryTypeW` function](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getbinarytypew) to judge whether a file is executable on Windows.

Judge executables with API on Windows

---

Tests/Foundation/Tests/TestJSONSerialization.swift

The `JSONSerializationTests` should indicate errors, if the `JSONSerialization` result is wrong, but they shouldn't crash.
- `do` `catch` blocks have been replaced with `XCTAssertNoThrow` and `XCTAssertThrows` to ensure the correct behaviour. 
- accesses to result arrays `result?[0]` have been replaced with `iterator?.next()`. Ensuring no crash if an empty array has been returned by `JSONSerialization`
- **No tests have been added or removed**
Sorry for the PR size.
⚠️ Please squash this pr before merging.

Refactor TestJSONSerialization to fail, but not to crash on wrong JSONSerialization results

---

Tests/Foundation/Tests/TestNSString.swift

- This isnt required on Linux or native macOS, but is just required on
macOS for test to compile.

macOS test: cast String to NSString to conform to CVarArg

---

DarwinCompatibilityTests.xcodeproj/xcshareddata/xcschemes/xdgTestHelper.xcscheme
Tests/Foundation/Tests/TestURLSession.swift
Tests/Foundation/main.swift

- Re-enable the TestURLSession tests which should no longer be flaky
however specifc tests are still disabled due to known issues.
- Enable the tests on DarwinCompatibilityTests also.
- Dont re-enable these tests on Windows yet as there are still random
crashes.
- Disable test_concurrentRequests() as this fails about 4% of the time.
- Disable test_getAllTasks() as this causes other tests to fail.
- Disable test_http0_9SimpleResponses() as this fails on Ubuntu20.04.
- Disable test_cancelledTasksCannotBeResumed() as this sometimes fails
on Ubuntu18.04.

TestURLSession: Re-enable tests on Linux

---

Tests/Foundation/Tests/TestURLSession.swift

- Running tests on macOS under DarwinCompatibilityTests would timeout
and fail as the .urlSession(_:dataTask:didReceive:completionHandler:)
method would not call the completion handler at all. Update the tests
to pass .allow.
- The tests pass on scl-f because URLSession is currently ignoring the
value passed to the completion handler and always continuing the task,
even though it should not be.
- The URLSession bug is logged as https://bugs.swift.org/browse/SR-14032

TestURLSession: Pass .allow in the completionHandler.

---

Tests/Foundation/Tests/TestXMLParser.swift

Fix weak reference lifetime.
XMLParser has a weak delegate. OSSA optimization destroys the delegate
before this parser test runs.
Fixes rdar://73046709 ([CanonicalOSSA] corelibs-foundation XMLTest;
fix weak reference lifetime)
This test is blocking OSSA development.

[CanonicalOSSA] fix corelibs-foundation XMLTest

---

Tests/Foundation/FTPServer.swift
Tests/Foundation/HTTPServer.swift

- Running some tests multiple times would eventually show an error on
Ubuntu20.04 (approx 5-12%). This seems due to using multiple writes on
the reply socket, so these are merged into one write in
writeData(header:bodyData).
- Add server debugging enabled by an environment variable
SCLF_HTTP_SERVER_DEBUG=YES
- Remove the ServerSemaphore and use a DispatchGroup() to wait for the
server thread to start. ServerSemaphore has been moved to FTPServer
but will be removed from there at some point.
- Simplify the writeData() function to remove the unused sending delays
and remove the now unneeded _send() function.

Test HTTPServer: Minor improvements and fix for errors on Ubuntu20.04

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

I’ve stumbled upon a problem in `URLSession` when a redirect occurs following a request with a request body (POST/PUT/PATCH).
Say we create a `URLRequest` with a httpBody and an httpMethod of "POST".
When the POST request is made, a [URLSessionTask is initialized with the httpBody from the URLRequest](https://github.com/apple/swift-corelibs-foundation/blob/bb511a3ac4aef1bb0c815f33efa72c38d0692a7a/Sources/FoundationNetworking/URLSession/URLSessionTask.swift#L263).
Later, when the server responds with a redirect to this request, a new request is made but the original task is reused. This involves calling `startNewTransfer`, which in turn [looks up any existing known body](https://github.com/apple/swift-corelibs-foundation/blob/bb511a3ac4aef1bb0c815f33efa72c38d0692a7a/Sources/FoundationNetwor …

Fix redirects following POST/PUT/PATCH requests

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

To be able to run operations concurrently OperationQueue needs concurrent underlying DispatchQueue. This patch uses .concurrent attribute to create DispatchQueues with required behavior.
This matches with Darwin.
(cherry picked from commit fdb1118, original PR #2937)

[5.4] Fix concurrent operations execution in OperationQueue

---

Sources/Foundation/Stream.swift

- Make func stream(_ aStream: Stream, handle eventCode: Stream.Event)
public.
(cherry picked from commit 9bd879b16bd0f41b6d6dfcd0eb25a0cbcf7ca309)

[5.3] SR-12981: Foundation.StreamDelegate has required methods on Linux but not Darwin

---

Sources/Foundation/ProcessInfo.swift
Tests/Foundation/Tests/TestProcessInfo.swift
Tests/Foundation/Utilities.swift

- For Linux, take into account CFS quotes eg, if running under Docker.
(cherry picked from commit 57bc80c1b32aad1cdef9192f3d867e97346bb707)

[5.3] SR-12833: processInfo.activeProcessorCount ignores CFS quotas

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

OperationQueue would crash or hang if we force "non-natural" execution order. E.g. when first operation depends on second.
The reason is how we work with internal operation lists in `OperationQueue._schedule()`. I believe the original intention was to adjust `__nextPriorityOperation`, but instead we are modifying `__nextOperation`. This has no sense and leads to crosslinking of the main operation list and corresponding priority operation list. Subsequent scheduling would try to read already finished operation and hang. Also, at this point queue doesn't hold operation object anymore, so trying to read dead object is pretty realistic scenario.
Suggested test case checks scenario described above, and ensures correct operation order as a bonus.
(cherry picked from commit 9f44ed3, original PR …

[5.3] Fix OperationQueue scheduling logic to prevent disruption of operation lists

---

Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestOperationQueue.swift

To be able to run operations concurrently OperationQueue needs concurrent underlying DispatchQueue. This patch uses `.concurrent` attribute to create DispatchQueues with required behavior.
This matches with Darwin.
(cherry picked from commit fdb1118, original PR #2937)

[5.3] Fix concurrent operations execution in OperationQueue

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Locale.subproj/CFCalendar_Enumerate.c
CoreFoundation/Locale.subproj/CFCalendar_Internal.h
Sources/Foundation/NSCalendar.swift
Tests/Foundation/Tests/TestCalendar.swift

- Annotate _CFCalendarEnumerateDates() with a _Nullable pointer used by
the block to allow better handling of a NULL CFDateRef.

SR-13979: Calendar.nextDate() segmentation fault

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Locale.subproj/CFCalendar_Enumerate.c
CoreFoundation/Locale.subproj/CFCalendar_Internal.h
Sources/Foundation/NSCalendar.swift
Tests/Foundation/Tests/TestCalendar.swift

- Annotate _CFCalendarEnumerateDates() with a _Nullable pointer used by
the block to allow better handling of a NULL CFDateRef.
(cherry picked from commit 46080e9276ceffe28db4844d607d0b4f6f5936d1)

[5.4] SR-13979: Calendar.nextDate() segmentation fault

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Locale.subproj/CFCalendar_Enumerate.c
CoreFoundation/Locale.subproj/CFCalendar_Internal.h
Sources/Foundation/NSCalendar.swift
Tests/Foundation/Tests/TestCalendar.swift

- Annotate _CFCalendarEnumerateDates() with a _Nullable pointer used by
the block to allow better handling of a NULL CFDateRef.
(cherry picked from commit 46080e9276ceffe28db4844d607d0b4f6f5936d1)

[5.3] SR-13979: Calendar.nextDate() segmentation fault

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Tests/Foundation/Tests/TestURLSession.swift

- Check if the session delegate conforms to URLSessionTaskDelegate
instead of using the task behaviour, as dataTask()s created with
a completion handler dont have a .callDelegate behaviour. This was
preventing the delegate method from being called.

SR-13028: URLSession does not call willPerformHTTPRedirection

---

Sources/FoundationXML/XMLDTD.swift
Sources/FoundationXML/XMLDTDNode.swift
Sources/FoundationXML/XMLDocument.swift
Sources/FoundationXML/XMLElement.swift
Sources/FoundationXML/XMLNode.swift
Sources/FoundationXML/XMLParser.swift

The CoreFoundation interfaces are not expected to be exposed.  Convert
the import of `CFXMLInterface` to `@_implementationOnly`.

FoundationXML: convert CFXMLInterface to ImplementationOnly

---

Sources/Foundation/Host.swift
Tests/Foundation/Tests/TestHost.swift

Host.current() looks up the hostname for its _info field, but then never
gives it to the user. As a result, .names is always empty for
Host.current().
This patch is a minimal-effort workaround: it simply throws the value of
gethostname() (or its Windows equivalent) into _names. We could probably
do better than that, but for now this is good enough.
Resolves SR-14197.

Store the hostname in _names for Host.current()

---

Sources/Foundation/FileManager+Win32.swift
Tests/Foundation/Tests/TestFileManager.swift

- Use `GetBinaryTypeW` to identify if the file is an executable file.
(cherry picked from commit 8a87b13)

[5.4] Judge executables with API on Windows

---

Sources/FoundationXML/XMLNode.swift
Sources/FoundationXML/XMLParser.swift

- This doesnt work on macOS for some reason, so just import it as a
normal import. This was breaking testing on macOS.
- This doesnt affect any other platform where it is actually required
to @_implementationOnly import.
This reverts #2979 on macOS

macOS: Dont import CFXMLInterface as @_implementationOnly as this breaks

---

Sources/Foundation/JSONEncoder.swift
Sources/Foundation/JSONSerialization.swift

This is a follow up pr to #2966.
It should significantly improve overall JSON performance, since we save on a lot of roundtrips through `NSArray` and `NSDictionary`.

JSON Decoding based on JSONValue

---

Sources/Foundation/JSONEncoder.swift
Sources/Foundation/JSONSerialization+Parser.swift

After #2966 and #2985, this is the last step to make JSON Encoding and Decoding much more performant on Linux.

JSON Encoding based on JSONValue

---

Sources/Foundation/JSONDecoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

- The behaviour of the floating point string parsing for Float and
Double was changed to return +/-infinity instead of nil on overflow.
(https://github.com/apple/swift/pull/34339)
- Add an isFinite check to ensure that the result of a floating point
conversion still fits in the type, matching current behaviour.

JSONDecoder: Check that a parsed float does not return infinity.

---

Tests/Foundation/Tests/TestURLSession.swift

They failed in an unrelated PR's smoke test. Tracking the disabling of the test here: https://bugs.swift.org/browse/SR-14433

mark two tests as flaky

---

Tests/Foundation/Tests/TestOperationQueue.swift

https://bugs.swift.org/browse/SR-14657

Disable flaky test test_CustomOperationReady

---

Sources/Foundation/Process.swift

Otherwise, we end up in a race condition where `isRunning` might still be `true` when accessed from inside the `terminationHandler`. If this is the case, accessing `terminationReason` or `terminationStatus` inside the termination handler crashes because their precondition that the task has finished are not satisfied.
We are experiencing this flaky behavior in [SourceKit-LSP’s](https://github.com/apple/sourcekit-lsp) crash recovery tests on Linux.
Fixes rdar://78035044

Set `isRunning` of `Process` to `false` before calling the termination handler

---

Sources/Foundation/Process.swift

Cherry-picks https://github.com/apple/swift-corelibs-foundation/pull/3000 to `release/5.5`.
---------------------
Otherwise, we end up in a race condition where `isRunning` might still be `true` when accessed from inside the `terminationHandler`. If this is the case, accessing `terminationReason` or `terminationStatus` inside the termination handler crashes because their precondition that the task has finished are not satisfied.
Fixes rdar://78035044

[5.5] Set `isRunning` of `Process` to `false` before calling the termination handler

---

Sources/Foundation/DataProtocol.swift
Tests/Foundation/Tests/TestNSData.swift

When the searched Data is empty, on macOS `nil` is returned, on Linux an empty Range is returned.
This PR fixes the discrepancy.

Make firstRange and lastRange mirror macOS Foundation more

---

Sources/Tools/plutil/CMakeLists.txt

Remove the absolute path to the host toolchain's stdlib from plutil, and add it as a CMake `BUILD_PATH`, so that it's removed upon installation.
The problem is that plutil on linux currently has this rpath:
```
> readelf -d swift-DEVELOPMENT-SNAPSHOT-2021-05-05-a-centos8/usr/bin/plutil |ag runpath
0x000000000000001d (RUNPATH)            Library runpath: [/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux]
```
I submitted this as part of #2783 earlier, but had to remove it because the linux CMake was too old and didn't support `BUILD_RPATH` then. With apple/swift#37517 updating the linux CMake, this should work now.

[CMake] fix plutil runpath for ELF platforms

---

Sources/Foundation/DataProtocol.swift
Tests/Foundation/Tests/TestNSData.swift

`DataProtocol`'s `firstRange(of:in:)` and `lastRange(of:in:)` return a wrong value or crash under some conditions because they handle indices incorrectly.
This PR fixes the issue.
Resolves [SR-10689](https://bugs.swift.org/browse/SR-10689).
-----
Note:
SR-10689 also says "`lastRange(of:)` returns `firstRange(of:in:)`", however, it has been already fixed by #2310.

SR-10689: Fix bugs of DataProtocol's firstRange(of:in:)/lastRange(of:in:).

---

Sources/Foundation/NSPathUtilities.swift
Tests/Foundation/Tests/TestFileManager.swift

This fixes an issue that would occur if the filename for a temporary file plus the `.tmp.<coda>` suffix was beyond the maximum path limit, but would be fine without it. This limits the temp filename to a maximum of 31 characters.
There will be follow-ups for other situations where long paths have similar issues, but this one specifically is also going to be nominated for 5.4.x and 5.5.
Fixes <https://bugs.swift.org/browse/SR-14823>.

Fix temporary filename coda going above the maximum path length in some cases

---

Sources/Foundation/NSPathUtilities.swift
Tests/Foundation/Tests/TestFileManager.swift

This fixes an issue that would occur if the filename for a temporary file plus the .tmp.<coda> suffix was beyond the maximum path limit, but would be fine without it. This limits the temp filename to a maximum of 31 characters.
There will be follow-ups for other situations where long paths have similar issues, but this one specifically is also going to be nominated for 5.4.x and 5.5.
Fixes <https://bugs.swift.org/browse/SR-14823>. This is a candidate PR cherry-pick of <https://github.com/apple/swift-corelibs-foundation/pull/3005>

[5.4] Fix temporary filename coda going above the maximum path length in some cases

---

Sources/Foundation/NSPathUtilities.swift
Tests/Foundation/Tests/TestFileManager.swift

This fixes an issue that would occur if the filename for a temporary file plus the .tmp.<coda> suffix was beyond the maximum path limit, but would be fine without it. This limits the temp filename to a maximum of 31 characters.
There will be follow-ups for other situations where long paths have similar issues, but this one specifically is also going to be nominated for 5.4.x and 5.5.
Fixes <https://bugs.swift.org/browse/SR-14823>. This is a candidate PR cherry-pick of #3005

[5.5] Fix temporary filename coda going above the maximum path length in some cases

---

Sources/Foundation/DateFormatter.swift
Tests/Foundation/Tests/TestDateFormatter.swift

`DateFormatter.copy()` returns the same instance not a copied one so far.
This PR adds an implementation of `copy()` in `DateFormatter` to behave expectedly(i.e. The same behavior with DarwinFoundation).
Resolves [SR-14108](https://bugs.swift.org/browse/SR-14108).

SR-14108: Implement `copy()` in `DateFormatter`.

---

Sources/Foundation/DateFormatter.swift
Tests/Foundation/Tests/TestDateFormatter.swift

This PR contains cherry-picks from #3008 for Swift 5.4 branch.
> DateFormatter.copy() returns the same instance not a copied one so far.
>This PR adds an implementation of copy() in DateFormatter to behave expectedly(i.e. The same behavior with DarwinFoundation).
> 
> Resolves SR-14108.

[5.4] SR-14108: Implement `copy()` in `DateFormatter`.

---

Sources/Foundation/DateFormatter.swift
Tests/Foundation/Tests/TestDateFormatter.swift

This PR contains cherry-picks from #3008 for Swift 5.5 branch.
> DateFormatter.copy() returns the same instance not a copied one so far.
>This PR adds an implementation of copy() in DateFormatter to behave expectedly(i.e. The same behavior with DarwinFoundation).
> 
> Resolves SR-14108.

[5.5] SR-14108: Implement `copy()` in `DateFormatter`.

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

Unfortunately, `Decimal.ulp` has never actually worked correctly. To make it short, users currently get an _invalid representation_ of an _incorrect result_—
1. The incorrect result: The implementation has never actually returned the "unit in the last place" as an IEEE floating-point type would. For instance, `print((0.1 as Decimal).ulp)` gives `0.1`, but it's obvious that the type has enough precision to be able to represent values between `0.1` and `0.2`. This is somewhat forgivable, though, because `Foundation.Decimal` isn't an IEEE decimal type.
2. The invalid representation: The implementation constructs a `Decimal` value explicitly with `_length` set to `8` but using a mantissa of only length `1`. This breaks `Foundation.Decimal` invariants and is not normalized by …

Partially fix Decimal.ulp to return a valid representation.

---

Sources/Foundation/PropertyListSerialization.swift

Fix memory leak in PropertyListSerialization

---

Sources/Foundation/PropertyListSerialization.swift

Reverts apple/swift-corelibs-foundation#3013
Reverting while we investigate a segfault that may have been caused by this change.

Revert "Fix memory leak in PropertyListSerialization"

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

This PR cherry-picks #3014 for the release/5.5 branch.

[5.5] Partially fix Decimal.ulp to return a valid representation.

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

This PR cherry-picks #3014 for the release/5.4 branch.

[5.4] Partially fix Decimal.ulp to return a valid representation.

---

Sources/Foundation/FileHandle.swift
Tests/Foundation/Tests/TestFileHandle.swift
Tests/Foundation/Tests/TestNSData.swift

- FileHandle.synchronize() would throw when calling fsync() on special
files. Ignore EINVAL and EROFS if fsync() fails, so that the behaviour
matches Darwin Foundation.

SR-14953: Data.write(to:) fails when writing to /dev/stdout

---

CONTRIBUTING.md
Docs/Testing.md

Update contributing docs

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

Resolve: [[SR-14536] Importing FoundationNetworking with -static-stdlib is broken with missing symbols on Linux - Swift](https://bugs.swift.org/browse/SR-14536)
Discussion: [Autolinking behavior of @_implementationOnly with static linking - Development / Core Libraries - Swift Forums](https://forums.swift.org/t/autolinking-behavior-of-implementationonly-with-static-linking/44393)
~~Blocked by [[Frontend] Add -public-autolink-library option by kateinoigakukun · Pull Request #35936 · apple/swift](https://github.com/apple/swift/pull/35936)~~
`Foundation` imports `CoreFoundation` with `@_implementationOnly` as a private dependency, and it doesn't emit `IMPORTED_MODULE` in swiftmodule.
Users of Foundation can link `libCoreFoundation.so` automatically when using dynamic linking because it's …

Fix autolink mechanism for static libraries on Linux

---

Sources/UUID/uuid.c

`/dev/urandom` is not available on WASI, it makes more sense to define `read_random` in terms of `getentropy` on that platform.

WASI: use getentropy to get randomized bytes

---

Sources/UUID/uuid.c

This makes `nanotime` implementation available for Wasm/WASI.

Add `|| TARGET_OS_WASI` to ifdef in `uuid.c`

---

CoreFoundation/Base.subproj/CFPlatform.c

This allows `_CFReallocf` function to be built for Wasm/WASI.

Add #if TARGET_OS_WASI to _CFReallocf definition

---

CoreFoundation/Base.subproj/CFPlatform.c

WASI doesn't support multi-threading and process info or environment variables. Here we `#ifdef` relevant code out, or replace with stubs that allow Foundation to be compiled for WASI.

Add `#ifdef` conditions to `CFPlatform.c` for WASI

---

Sources/BlocksRuntime/CMakeLists.txt

Sources in this directory are unused on most platforms, since Blocks are already included in libdispatch. Platforms, such as WASI, that don't have multi-threading support need to build BlocksRuntime bundled with Foundation.

Add `CMakeLists.txt` to `Sources/BlocksRuntime`

---

CoreFoundation/Base.subproj/CFUtilities.c

Processes, file access, platform info, and bundles aren't available on WASI, so these have to be disabled when compiling for that platform.

Add support for WASI in `CFUtilities.c`

---

CMakeLists.txt

Dispatch and Networking aren't available for Wasm and WASI. We should make these parts configurable to make it possible to turn them off when building for that platform.

Allow disabling Dispatch and Networking in `CMakeLists.txt`

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

Reverts apple/swift-corelibs-foundation#2996
The icui18n library that is linked against is not necessarily the same as the one used to build Foundation and Swift, so this is causing builds to fail.

Revert "Fix autolink mechanism for static libraries on Linux"

---

CoreFoundation/Collections.subproj/CFData.c
CoreFoundation/Locale.subproj/CFDateIntervalFormatter.c
CoreFoundation/Locale.subproj/CFLocale.c
CoreFoundation/Locale.subproj/CFLocaleKeys.c
CoreFoundation/NumberDate.subproj/CFNumber.c
CoreFoundation/NumberDate.subproj/CFTimeZone.c
CoreFoundation/Parsing.subproj/CFBinaryPList.c
CoreFoundation/Parsing.subproj/CFPropertyList.c
CoreFoundation/Parsing.subproj/CFPropertyList.h
CoreFoundation/String.subproj/CFBurstTrie.c
CoreFoundation/String.subproj/CFCharacterSet.c
CoreFoundation/String.subproj/CFString.c
CoreFoundation/String.subproj/CFStringEncodings.c
CoreFoundation/String.subproj/CFStringUtilities.c
CoreFoundation/StringEncodings.subproj/CFUniChar.c
CoreFoundation/URL.subproj/CFURL.c
CoreFoundation/URL.subproj/CFURLAccess.c

A lot of data structures, like strings, characters, data, locales, plists just need a proper check for `|| TARGET_OS_WASI` to be enabled on that platform and to use a suitable implementation. Some code related to filesystem access had to be disabled on WASI though.

Add support for CF data structures/utils on WASI

---

CoreFoundation/Base.subproj/CFPriv.h
CoreFoundation/Base.subproj/CFUtilities.c
CoreFoundation/Base.subproj/CoreFoundation.h
CoreFoundation/Base.subproj/ForFoundationOnly.h
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h

Filesystem (and thus `CFBundle` and `CFPreferences`), sockets,  and processes are unavailable on WASI. We should disable this code if ifdefs.

Disable file/process-related code in CF for WASI

---

CoreFoundation/CMakeLists.txt

`CFBundle`, plugins, preferences, streams, and run loops are not available when compiling to WASI/Wasm because of the lack of a meaningful filesystem access and multi-threading. These sources files should be excluded from the build in `CoreFoundation/CMakeLists.txt` when compiling for that platform.

WASI: Make some sources unavailable in CF CMake

---

CoreFoundation/CMakeLists.txt

Reverts apple/swift-corelibs-foundation#3038 — Caused the Windows CI build to go red: https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/130/consoleText

Revert "WASI: Make some sources unavailable in CF CMake"

---

Tests/Foundation/Tests/TestURLSession.swift

test_requestWithNonEmptyBody is failing consistently and blocking the Amazon Linux CI

---

Tests/Foundation/main.swift

It has been observed in CI that the stderr output is sometimes truncated
on failure.  Explicitly flush the output to ensure that we can see the
error messages.  This has been observed on Windows which does not do a
courtesy flush unlike Linux.

tests: explicitly flush `stderr` on exit

---

CoreFoundation/OlsonWindowsMapping.plist

Windows does not have the same timezone information available as the
other platforms.  We import a subset of the CLDR (due to duplicate
mappings) into Foundation to provide the translation.
`TestCalendar/test_nextDate` usees `US/Pacific` for a test case.
Explicitly add this to the Olson -> Windows mapping.  We cannot provide
a Windows -> Olson mapping entry for this value as that would have
multiple values for the canonical `America/Los_Angeles` key.  This
repairs the `TestCalendar/test_nextDate` test case on Windows.

CoreFoundation: add `US/Pacific` TimeZone mapping for Windows

---

Sources/Foundation/FileHandle.swift
Tests/Foundation/Tests/TestFileHandle.swift

TestFileHandle/test_synchronizeOnSpecialFile introduced a failure in the
Windows test suite.  The underlying problem here is that
`FlushFileBuffers` is not permitted on unbuffered file handles (such as
consoles).  Ensure that we do not treat errors on character devices as
flush errors.

FileHandle: improve the compatibility of `synchronize`

---

Tests/Foundation/Tests/TestNSData.swift

This test was added recently and regressed the test suite on Windows.
Windows does not have a devfs mounted at `/dev`.  Use the `CON` special
file which is roughly equivalent to `/dev/stdout` to emulate the desired
test behaviour.

tests: repair `TestNSData/test_writeToURLSpecialFile`

---

Tests/Foundation/Tests/TestFileManager.swift

Rather than creating a temporary directory, locate the application
support directory.  The temporary directory may be created under a
root that that is not an actual volume, but rather an aliased
mountpoint.  This is the case on the CI hosts where `T:` is a path
substitution rather than an actual disk volume.

Tests: make test_mountedVoumeURLs more robust

---

Sources/Foundation/FileManager+Win32.swift

The conditions here were over indented.  This corrects the misleading
indentation.

Foundation: correct misleading indentation

---

Sources/Foundation/FileManager+Win32.swift

`GetVolumeInformationW` is documented as taking the root directory of
the volume to describe as `lpRootPathName`. We attempt to compute the
location by determining the volume mount point where the specified
path is mounted. However, `GetVolumePathNameW` does always return the
path to the volume mount point, which is the root of the volume where
the specified path.  With a path substitution that is not rooted at a
volume root, the volume root with a relative path. As we need to get
to the root, force the stripping to the root via `PathCchStripToRoot`.
This should repair the
TestFoundation.TestFileManager/test_filesystemAttributes on Windows.

FileManager: correct API misuse on Windows

---

Tests/Foundation/Tests/TestURLSession.swift

Same as the main branch patch.
(cherry picked from commit 631abc69d45743bb241652552126fd010909a162)

[5.5] test_requestWithNonEmptyBody is failing consistently and blocking the Amazon Linux CI

---

CMakeLists.txt
CoreFoundation/CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

Re-land https://github.com/apple/swift-corelibs-foundation/pull/2996
ICU i18n library name is now resolved based on CMake package finding system. It allows to use `swift` suffixed ICU libraries.

Revert "Revert "Fix autolink mechanism for static libraries on Linux""

---

Sources/Foundation/ISO8601DateFormatter.swift
Tests/Foundation/Tests/TestISO8601DateFormatter.swift

As with #3008, `ISO8601DateFormatter` should also implement its own override of `copy()`.
Resolves SR-14933.

SR-14933: Implement `copy()` in `ISO8601DateFormatter`.

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift

Several improvements were made to the corelibs implementation of `Decimal` over the years which have not been in sync with the overlay. Most evidently, #2926 resolving [SR-13837](https://bugs.swift.org/browse/SR-13837) and #2574 implementing `init?(exactly:)` are lacking from the overlay. Credit goes entirely to @spevans for actually implementing these fixes.
This PR re-aligns the two implementations. Only very minor adjustments are made to the corelibs implementation, mostly where it uses private APIs that do not exist in the overlay, to better keep the two implementations in sync.
A minor change is made to both implementations in terms of diagnostic messages: where we state that `Decimal` does not "yet" conform to `FloatingPoint`, the "yet" is deleted because it misleadingly suggests a …

Synchronize `Decimal` overlay and corelibs-foundation implementations

---

CoreFoundation/Base.subproj/SwiftRuntime/TargetConditionals.h
Foundation.xcodeproj/project.pbxproj
Sources/Foundation/AttributedString/AttributedString+Locking.swift
Sources/Foundation/AttributedString/AttributedString.swift
Sources/Foundation/AttributedString/AttributedStringAttribute.swift
Sources/Foundation/AttributedString/AttributedStringCodable.swift
Sources/Foundation/AttributedString/AttributedStringRunCoalescing.swift
Sources/Foundation/AttributedString/Conversion.swift
Sources/Foundation/AttributedString/FoundationAttributes.swift
Sources/Foundation/Bridging.swift
Sources/Foundation/CMakeLists.txt
Sources/Foundation/Morphology.swift
Tests/Foundation/CMakeLists.txt
Tests/Foundation/Tests/TestAttributedString.swift
Tests/Foundation/Tests/TestAttributedStringCOW.swift
Tests/Foundation/Tests/TestAttributedStringPerformance.swift
Tests/Foundation/Tests/TestAttributedStringSupport.swift
Tests/Foundation/Utilities.swift
Tests/Foundation/main.swift

This patch introduces struct `AttributedString` and tests. Markdown support is not included in this patch as it will be introduced in a separate package.
See Apple's [documentation](https://developer.apple.com/documentation/foundation/attributedstring/) for more information.

Introduce AttributedString

---

Sources/Foundation/PropertyListSerialization.swift

rdar://80919378
Cherry-pick of #3013

[5.5] Fix memory leak in PropertyListSerialization

---

Sources/Foundation/ISO8601DateFormatter.swift
Tests/Foundation/Tests/TestISO8601DateFormatter.swift

Cherry-picks from #3009 for 5.4 branch.
> As with #3008, `ISO8601DateFormatter` should also implement its own override of `copy()`.
> 
> Resolves SR-14933.

[5.4] SR-14933: Implement `copy()` in `ISO8601DateFormatter`.

---

Sources/Foundation/NSTextCheckingResult.swift

The irony is fun, but particularly in the case of the placeholder API, it only serves its purpose if it's holding the right place.

Fix orthography of 'orthography'

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

Consider the following discrepancy:
```swift
let x: Int = 42
x.distance(to: 43) // 1
let y: Decimal = 42
y.distance(to: 43) // -1 (oops!)
```
The implementation of `distance(to:)` is incorrect for `Decimal`. This PR corrects the implementation (for both the overlay and swift-corelibs) and adds corresponding tests.
Resolves [SR-6785](https://bugs.swift.org/browse/SR-6785).

[SR-6785] Fix `Decimal` conformance to `Strideable`

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

This PR fixes <strike>two</strike> three newly discovered issues with `Decimal` implementations of APIs that deliberately mimic those of `FloatingPoint`.
First, as reported in SR-15132, `significand` shouldn't be negative, but `Decimal` returns a negative "significand" for a negative value:
```swift
let x = -42 as Double
x.significand.sign // plus
let y = -42 as Decimal
y.significand.sign // minus (!)
```
Second and not reported in a separate bug, for types conforming to `FloatingPoint`, the initializer `init(sign:exponent:significand:)` returns a value where the sign is determined by the following notional calculation:
```swift
(sign == .minus ? -1 : 1) * significand * radix ** exponent
```
In other words, the sign of the result is not determined by `sign` alone, but …

[SR-15132][SR-15134] Fix `Decimal` implementation of significand APIs

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

This issue has been present all along, and my previous fix in #3068 didn't address it because I didn't know of the problem--and (perhaps unsurprisingly) reproduced the same problem despite a totally new implementation of the initializer. Consider the following:
```swift
let x = Double.greatestFiniteMagnitude
Double(sign: .plus, exponent: 10, significand: x)
// +inf
Double(sign: .plus, exponent: .max, significand: x)
// +inf
let y = Decimal.greatestFiniteMagnitude
Decimal(sign: .plus, exponent: 10, significand: y)
// nan (correct, since `Decimal` has no representation of infinity)
Decimal(sign: .plus, exponent: .max, significand: y)
// runtime error (!)
```
This is because the implementation of `Decimal(sign:exponent:significand:)` converts between `Int` and an integer …

[SR-15156] Another fix for `Decimal(sign:exponent:significand:)`.

---

Darwin/Foundation-swiftoverlay-Tests/TestDecimal.swift
Darwin/Foundation-swiftoverlay/Decimal.swift
Sources/Foundation/Decimal.swift
Tests/Foundation/Tests/TestDecimal.swift

This PR is a follow-up to #3014, addressing the first issue outlined there and correspondingly addressing SR-14384 regarding `nextDown` and `nextUp`. Namely:
* The implementation of `ulp` does not currently actually return the "unit in the last place" as an IEEE floating-point type would, which should reflect the spacing between two consecutive representable numbers. Instead, the result currently reflects the idiosyncratic internal representation of `Decimal` values, with the consequence that the "unit in the last place" of `1` is allegedly `1`.
* Relatedly, `nextUp` is documented to give "the least representable value that is greater than this decimal," but `(1 as Decimal).nextUp` is allegedly `2`. (Similarly for `nextDown`.)
This behavior is discordant with that of binary floating-point …

[SR-14384][SR-14974] Fix `Decimal.ulp`, `nextUp`, `nextDown`

---

Sources/Foundation/NSString.swift
Sources/Foundation/NSSwiftRuntime.swift
Sources/Foundation/NSURL.swift
Sources/Foundation/PropertyListSerialization.swift
Sources/FoundationXML/XMLParser.swift

APIs related to file access (i.e. those depending on `NSCoding`) and multi-threading (those that require `NSRunLoop`) had to be disabled for WASI/Wasm to make this work.

Enable String, URL and XML-related types for WASI

---

CoreFoundation/Locale.subproj/CFListFormatter.c
CoreFoundation/Locale.subproj/CFRelativeDateTimeFormatter.c
CoreFoundation/String.subproj/CFAttributedString.c

`#import` is an ObjC extension, and unportable (`#import` imports a type
library on Windows).  Use the standard include directive.

[Build Fix] CoreFoundation: use `#include`

---

CoreFoundation/PlugIn.subproj/CFBundle_Resources.c

Add a crude first-pass approximation of `readlink` and `ssize_t`.

PlugIn: shim out the dependencies for wrapper style bundles

---

CoreFoundation/RunLoop.subproj/CFRunLoop.c

`typeinfo.h` is a non-standard header and not always available.  Guard
the inclusion with an availability check.

RunLoop: `typeinfo.h` was removed in VS2019 16.3

---

CoreFoundation/URL.subproj/CFURL.c

`assert.h` is universally available and required for the use of
`assert`.

URL: correct header inclusion

---

Sources/Foundation/CGFloat.swift
Sources/Foundation/CharacterSet.swift
Sources/Foundation/Data.swift
Sources/Foundation/JSONSerialization.swift
Sources/Foundation/NSArray.swift
Sources/Foundation/NSCalendar.swift
Sources/Foundation/NSCharacterSet.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSDictionary.swift
Sources/Foundation/NSIndexSet.swift
Sources/Foundation/NSKeyedArchiver.swift
Sources/Foundation/NSKeyedUnarchiver.swift
Sources/Foundation/NSLocale.swift
Sources/Foundation/NSLock.swift
Sources/Foundation/NSNumber.swift
Sources/Foundation/NSObject.swift
Sources/Foundation/NSPathUtilities.swift
Sources/Foundation/NSPlatform.swift
Sources/Foundation/NSRange.swift

Functionality related to Dispatch, run loops, and full filesystem access (other than stdio/stderr file handles) is not available on WASI/Wasm. As a follow-up to previous Core Foundation PRs, this one updates parts of Foundation to add support for that platform.

Disable file/dispatch-related code in Foundation for WASI

---

CoreFoundation/Base.subproj/CFAvailability.h

The syntax relied upon by CF_ENUM does not align with the intent of the C++ feature, and that correction extends to its use in C mode. Add a temporary fix that 'swallows' the user-supplied `typealias` by defining a dummy type, and then does a forward-definition-then-typedef-then-enum-opening dance to apply the correct syntax.
This patch was originally applied in d28b5470f27e961c029e5745ec03d1e10244e0d6, then was undone in d8e8a8b92b3a8af8381a11155328c1bba1c6bd2c. `-Welaborated-enum-base` is taking effect on the swift rebranch branch, so we will need to fix the syntax before that lands.
Failing CI job: https://ci.swift.org/view/Swift%20rebranch/job/oss-swift-rebranch-incremental-RA-linux-ubuntu-18_04/26/console

Reapply: Make CF_ENUM compatible with -Welaborated-enum-base

---

CoreFoundation/String.subproj/CFAttributedString.c

I think I've found the fix for the failing optimization on the main swift branch.
We should be able to re-enable optimizations once that merges.
The fixing merge is: https://github.com/apple/llvm-project/pull/3439

Re-enable string Optimizations

---

Sources/Foundation/PropertyListSerialization.swift
Tests/Foundation/Tests/TestPropertyListSerialization.swift

Handle where the plist is empty, and ```CFPropertyListCreateWithData()``` failed to parse the entry and return NULL.

Handle failing to parse plist

---

Sources/Foundation/NSLock.swift

The types `pthread_mutex_t` and `pthread_cond_t` were defined via both `SwiftGlibc` and `CDistpatch` but a clang fix should merge these decls and consider `CDispatch` as the true origin.
Let's first see if we still need the explicit reference to `Glibc` when referring to those types.
rdar://84677782

Prefer the pthread types from CDispatch

---

CoreFoundation/AppServices.subproj/CFUserNotification.c

Specifying a variable without a type is not Standard C, even for sizeof

Specify variable type in CUserNotifications

---

Sources/Foundation/FileManager.swift
Tests/Foundation/Tests/TestFileManager.swift

`setAttributes(_:ofItemAtPath:)` and friends should not `fatalError`
when encountering an attribute which cannot be set.  Instead, we should
ignore those to match the behaviour of the reference implementation.
This should allow us to properly enable some test cases in swift-driver.

FileManager: improve compatibility for `setAttributes`

---

Sources/Foundation/PropertyListSerialization.swift
Tests/Foundation/Tests/TestPropertyListSerialization.swift

[5.5] Handle where the plist is empty, and CFPropertyListCreateWithData() failed to parse the entry and return NULL.
@millenomi @tomerd

[5.5] Check for invalid plist error

---

CoreFoundation/Base.subproj/CFPlatform.c

This `memcpy` could potentially overflow if the source was smaller than
the destination.  We now trim this to the minimum of the source and dest
(similar to `strlcpy`).

CoreFoundation: ensure that we do not overflow the dest

---

Tests/Foundation/Tests/TestThread.swift

https://bugs.swift.org/browse/SR-15489

[test] Disable flaky test TestThread.test_sleepUntilDate

---

Sources/Foundation/Process.swift

This PR relaxes which thread / runloop `Process.waitUntilExit()` can be called from. Before this change, a different thread would return prematurely from `.waitUntilExit()` with `Process.isRunning` still true. This change fixes the problem by observing whether the `.runLoop` property matches `RunLoop.currentRunLoop`, and if it doesn't then it no longer calls `currentRunLoop.run(mode: .default, before: Date(timeIntervalSinceNow: 0.05))` which would always return `false` for this new thread. Instead, it simply calls `currentRunLoop.run(until: Date(timeIntervalSinceNow: 0.05))` and keeps checking the `.isRunning` property.

Allow `Process.waitUntilExit()` to be called from any thread

---

Sources/Tools/plutil/CMakeLists.txt

When CMAKE_Swift_FLAGS is empty, the string substitution will be empty,
resulting in insufficient parameters to the REPLACE operation.  The
quoting ensures that an empty string does not cause that failure.

build: allow building on Linux without Swift_FLAGS

---

Sources/Foundation/NSURLComponents.swift
Sources/Foundation/URLComponents.swift
Tests/Foundation/Tests/TestURLComponents.swift

Fixes SR-12340
fixed on main with https://github.com/apple/swift-corelibs-foundation/pull/3096
Please consider for including in an upcoming 5.5 bug fix release for platform using swift-corelibs-foundation.
cc @millenomi @tomerd

[5.5] Url components.percent encoded query items

---

CoreFoundation/Base.subproj/CFPlatform.c

This `memcpy` could potentially overflow if the source was smaller than
the destination.  We now trim this to the minimum of the source and dest
(similar to `strlcpy`).

[5.5] CoreFoundation: ensure that we do not overflow the dest

---

Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift

The moral equivalent to the inode is the FileID on Windows.  Populate
this properly into the FileInfo response from FileManager.  This was
identified by a failure in the swift-driver test suite failing to
recursively resolve response files.

FileManager: support querying file ids on Windows

---

Sources/Foundation/Process.swift

When a process terminates due to an unhandled exception via a `HRESULT`,
the process termination status will not have `0xC000_0000` or
`0xE000_0000` but rather `0x8000_0000` set.  This accounts for that and
properly classifies the exit as an abnormal exit.  This was identified
by the swift-driver test suite not properly detecting an abnormal exit
of the frontend.

Process: handle `HRESULT` exit codes properly

---

Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift

The moral equivalent to the inode is the FileID on Windows.  Populate
this properly into the FileInfo response from FileManager.  This was
identified by a failure in the swift-driver test suite failing to
recursively resolve response files.

[5.6] FileManager: support querying file ids on Windows

---

Sources/Foundation/Process.swift

When a process is run with `run`, a monitoring thread is setup by means
of a socketpair.  This socket is used to create a runloop source, which
will monitor the process for termination.  `waitUntilExit` will monitor
the `isRunning` ivar which is set by the source to indicate the process
termination having been observed.  We however would previously mark the
process as terminated before invalidating the runloop source to prevent
any new callouts on the source. However, the operation is multithreaded
the operation is not guaranteed to be serialized and the runloop source
may be `nil`'ed prior or during the invalidation which also releases as
the refcount is now 0.  This would result in the `runloopSource` passed
to `CFRunLoopSourceInvalidate` being `nil` and breaking the contract of
the …

Process: correct a subtle `runLoopSource` lifetime issue

---

Sources/Foundation/JSONEncoder.swift

Case accidentally included twice, remove a copy.

Remove additional/redundant case let as Date.

---

CMakeLists.txt
CoreFoundation/CMakeLists.txt

With the removal of the ICU data dependency in swiftCore, it is now
possible to statically link to the ICU, with static linking to the
ICU data as well.  This would allow us to remove the ICU dependency
from leaking into distributions which was previously required due to
the oversized cost of the ICU data.  With the single use now, it is
possible to statically link the data to avoid the distribution and
packaging.  In order to provide a migration path, this needs to be
optionalised, and as such, we only link the data if it is found (and
can be controlled through `-D ICU_DATA_LIBRARY_RELEASE=`

build: allow static linking against ICU data

---

Sources/FoundationNetworking/URLSession/BodySource.swift
Sources/FoundationXML/XMLParser.swift

When using @_implementationOnly, the dependencies do not get emited into the module files and static linking does not work. There is a proper fix in 5.6, so this is only a temporary solution for 5.5.

[5.5] Temporary fix for static linking on Linux

---

Sources/Foundation/Bundle.swift
Sources/Foundation/DateFormatter.swift
Sources/Foundation/DateIntervalFormatter.swift
Sources/Foundation/ISO8601DateFormatter.swift
Sources/Foundation/NSCalendar.swift
Sources/Foundation/NSCharacterSet.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSDate.swift
Sources/Foundation/NSError.swift
Sources/Foundation/NSKeyedUnarchiver.swift
Sources/Foundation/NSLocale.swift
Sources/Foundation/NSNumber.swift
Sources/Foundation/NSRegularExpression.swift
Sources/Foundation/NSTimeZone.swift
Sources/Foundation/NSURL.swift
Sources/Foundation/NSURLComponents.swift
Sources/Foundation/NotificationQueue.swift
Sources/Foundation/NumberFormatter.swift
Sources/Foundation/Port.swift
Sources/Foundation/Process.swift
Sources/Foundation/PropertyListSerialization.swift
Sources/Foundation/RunLoop.swift
Sources/Foundation/Stream.swift
Sources/Foundation/Thread.swift
Sources/Foundation/Timer.swift

These are not overridden and are private fields which do not need to be
emitted to the vtable.  This allows these members to not impact the
module serialization when `@_implementationOnly import`s are used for
CoreFoundation by removing them entirely from the serialization path.

Foundation: `final`-ize many bridgeable interfaces

---

Sources/Foundation/JSONEncoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

Darwin encodes these as an empty array (`[]`), but SCF was encoding an empty JSON object instead (`{}`). Fixes https://bugs.swift.org/browse/SR-15781.

[5.5] Prevent empty dictionary with non-String keys from encoding as a JSON object.

---

Sources/Foundation/JSONEncoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

Darwin encodes these as an empty array (`[]`), but SCF was encoding an empty JSON object instead (`{}`). Fixes https://bugs.swift.org/browse/SR-15781.

[5.6] Prevent empty dictionary with non-String keys from encoding as a JSON object.

---

Sources/Foundation/JSONEncoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

Darwin encodes these as an empty array (`[]`), but SCF was encoding an empty JSON object instead (`{}`). Fixes https://bugs.swift.org/browse/SR-15781.
This is for the `main` branch. Also:
- #3136
- #3137

Prevent empty dictionary with non-String keys from encoding as a JSON object.

---

Sources/Foundation/CMakeLists.txt

When linking Foundation, we were only passing `-licui18nswift` as a static library, but it depends on `icuucswift` and `icudataswift`, so make sure we static link against those as well.
Resolves: https://bugs.swift.org/browse/SR-15770 and rdar://problem/87991595

[cmake] Fix ICU static linking

---

Sources/Foundation/TimeZone.swift

This PR fix the missing `_ObjectiveCBridgeable` protocol conformance on `TimeZone` struct.
The API in Apple's Foundation declares `TimeZone` is marked as here:
So this seems a typo, not designed behavior.
Platform: Linux
Docker Image: swift/latest [d8708e4f244e2fa11eb9d1f4d718ee0a8481807f0070a7c5f9da5c2f853a94e5](https://hub.docker.com/layers/swift/library/swift/latest/images/sha256-d8708e4f244e2fa11eb9d1f4d718ee0a8481807f0070a7c5f9da5c2f853a94e5)
Swift Version: Swift version 5.5.2 (swift-5.5.2-RELEASE)
```
public protocol NSObjectBridgeable : _ObjectiveCBridgeable {}
extension TimeZone : NSObjectBridgeable {}
```
Build Success.
Build Failure. Showing:
```
error: conformance of 'TimeZone' to '_ObjectiveCBridgeable' can only be written in module 'Foundation'
extension TimeZone : …
```

Fix TimeZone does not conforms to _ObjectiveCBridgeable

---

Sources/Foundation/NSCharacterSet.swift
Sources/Foundation/NSCoder.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSDictionary.swift
Sources/Foundation/NSNumber.swift
Sources/Foundation/NSObject.swift
Sources/Foundation/Progress.swift
Tests/Foundation/Tests/TestNSData.swift

These ivars and functions are referenced elsewhere in Foundation.  We
were previously relying on the compiler exporting functions more
aggressively which would ensure that these were emitted even when not
meant to be used outside of the current module.  This marks these
interfaces as `internal` to ensure that references from other source
files are emitted with more aggressive internalization by the compiler.

Foundation: make some functions more visible

---

CMakeLists.txt
CoreFoundation/CMakeLists.txt
Sources/Foundation/CMakeLists.txt

When static linking Foundation, some of ICU's dependencies were not being explicitly linked against, so static linking failed for those platforms due to undefined references. This patch only affects the build rules for static linking.
Resolves: https://bugs.swift.org/browse/SR-15770 and rdar://87991595

[5.6] [cmake] Fix ICU static linking

---

Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/FoundationErrors.swift
Sources/Foundation/Port.swift
Sources/Foundation/Process.swift

This adjusts the types to be more explicit about types as appropriate.
These changes are required to enable building a 32-bit variant of
Foundation for Windows.  It also happens to clean up some constants
which were being formed oddly.  This enables building Windows x86
version of Foundation.

Foundation: adjust types for bit-width differences

---

Sources/Foundation/IndexPath.swift
Tests/Foundation/Tests/TestIndexPath.swift

(Re-open of accidentally closed #3152)
Subscripting of `IndexPath` using a range currently crashes when removing from the front if the result is a pair or single:
```
let path = IndexPath(indexes: [ 10, 20, 30, 40 ])
print(path[2...]) // Crash
```

Fix IndexPath slicing crash

---

CoreFoundation/Base.subproj/CFRuntime.c
CoreFoundation/CMakeLists.txt

Use the address of the function to get a module handle without bumping
the refcount of the module.  This avoids the need to hardcode the
library name and enables the use of CoreFoundation in a statically
linked fashion as well.  We can further reduce the logic by using the
PathCch routine to remove the trailing file specification.  This reduces
the complexity in the module location code and reuses the system
libraries for a small additional cost of an additional iteration of the
string path.

CoreFoundation: clean up module locator logic

---

CoreFoundation/Base.subproj/CFRuntime.c

The allocator on 32-bit platforms are not guaranteed to provide a
16-byte alignment.  This would cause an over-aligned request which would
be serviced by a different allocation path which needs to be paired with
an appropriate deallocation invocation.  Failure to do so resulted in a
heap corruption on Windows i686.

CoreFoundation: correct alignment mis-assumption

---

CoreFoundation/Locale.subproj/CFLocale.c

These objects have a real (live) retain count rather than being immortal on Swift; do not overretain as it is not a no-op. rdar://88461050

[5.6] Solve a memory leak in CFLocaleGetSystem()

---

Sources/Foundation/Thread.swift

The recent improvements in string handling in the compiler identified
poor handling of the symbol name.  Correct the logic for extracting the
symbol name from the result.  While in the area, correct the memory
binding for the symbol info pointer.

Foundation: correct invalid memory usage in `callStackSymbols`

---

CoreFoundation/Base.subproj/CFUUID.c

The Swift Runtime path always uses the UUID functions from the
statically linked UUID library.  However, the header was only included
in the non-Windows case.  The latest LLVM update makes implicit
declarations invalid as per the C99 standard.  Adjust the inclusion path
to also include `uuid.h` on Windows when building with the Swift
Runtime.

CoreFoundation: adjust `uuid.h` inclusion

---

CoreFoundation/URL.subproj/CFURLComponents_URIParser.c

Rebranch is currently failing with a missing declaration for `bzero` on
Windows. Add a definition as in other uses of `bzero`.

[Windows] Add an implementation for the missing `bzero` function

---

Sources/Foundation/NSStringAPI.swift
Tests/Foundation/Tests/TestNSString.swift

Mitigate an oob memory read issue due to pointer conversion, by
- adding overloads for `String.init?(cString:encoding:)` and `String.init?(utf8String:)`
- enforcing null-termination precondition when possible
- adding advisory deprecations for the obviously fixable cases
- clarifying the null-termination precondition in doc-comments
A similar issue was resolved in the standard library in https://github.com/apple/swift/pull/42002
addresses rdar://93255079

Mitigate an out-of-bounds memory read

---

Sources/Foundation/AttributedString/AttributedString.swift

Format AttributedString.swift

---

Sources/Foundation/DateInterval.swift
Tests/Foundation/Tests/TestDateInterval.swift

Resolves https://github.com/apple/swift-corelibs-foundation/issues/4588

[DateInterval] Fix `func contains(_:) -> Bool`.

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

asprintf exists on linux for quite a while, 2015 at least. do use it.
fixes https://bugs.swift.org/browse/SR-14935

asprintf exists on linux

---

Sources/Foundation/NSError.swift

Windows does not have a proper POSIX equivalent to `ECANCELED`.  The
closes equivalent appears to be `WSAECANCELLED` which is a WinSock error
code for a cancelled operation.  The Windows Error `ERROR_CANCELLED`
(0x04c7) is the ideal mapping even though the error code resides in a
different domain.  As long as the error code is compared via name, this
should be safe.

Foundation: rework handling for `ECANCELED`

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

This PR will define `asprintf` when `_GNU_SOURCE` is not set while building for Linux. The build system defines `_GNU_SOURCE` when building for Linux/Android here; https://github.com/apple/swift-corelibs-foundation/blob/main/CoreFoundation/CMakeLists.txt#L69-L70, but being pedantically correct will ensure there are no surprises.

Define `asprintf` when `_GNU_SOURCE` is not set on Linux

---

Sources/Foundation/NSError.swift

The `ERROR_CANCELLED` constant is imported as an `Int`, but `POSIXError` expects an `Int32`.  Explicitly cast the value to make the 32-bit builds clean.

Foundation: explicitly cast value on Windows for 32-bits

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h

Pull a couple of patches from main which improve handling for `asprintf` on Linux platforms.  `asprintf` is vended by the system libc for most platforms (including android) when `_GNU_SOURCE` is defined which we do set.  Backporting this ensures that we do not accidentally break the build due to re-definition of the symbol.

[5.6] backport some changes regarding `asprintf`

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/RunLoop.subproj/CFRunLoop.c
Sources/Foundation/RunLoop.swift

Dispatch uses kevent for its event loop backend. However, `CFRunLoop` in Foundation uses Mach ports. This means for other kevent-based platforms such as OpenBSD, new runloop functionality is required, which this omnibus pr implements. 
This pr must be considered in concert with apple/swift-corelibs-libdispatch#559 (see below).
Please feel free to request any or all to be split into multiple prs, though all these commits and the aforementioned Dispatch pr are required to properly implement `CFRunLoop` on this platform.
Notes:
* Some of the Mach-based implementation refers to `MACH_PORT_NULL`, for example, when we have symbols already defined like `CFPORT_NULL`. These are brought more into alignment for consistency.
* Each platform necessitates implementing the "backend" set of `__CFPort*` …

Omnibus to implement CFRunLoop with kevent.

---

Darwin/Foundation-swiftoverlay/NSStringAPI.swift

This is present on Apple's developer website: https://developer.apple.com/documentation/swift/string/init(bytes:encoding:)

Fix typo `ecoding` -> `encoding`

---

CoreFoundation/RunLoop.subproj/CFRunLoop.c

On Windows, __CFTSRRate is in units of 100 ns. To get a CFTimeInterval
from mach_absolute_time therefore, we should divide by 1.0E7, not 1.0E9.
But this suggests we should be dividing by __CFTSRRate anyway.
(Currently trying to test this now, so making this a draft pr for now to share since #3004 may be causing trouble for Windows.)

Attempt to unbreak test timeouts in Windows.

---

CoreFoundation/Base.subproj/CFPlatform.c

The user profile directory is not possible to access without the user
token for the `GetUserProfileDirectoryW`.  Instead, we can iterate the
users matching a particular filter (e.g. local users).  This allows us
to at least query some user home directory.  Unfortunately, this would
disallow querying of users from a domain controller.  This resolves an
immediate issue of SPM tests depending on the ability to query profile
information for a user.

Base: add support for querying user home directory on Windows

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

Tasks which request unsupported URL protocols, or which request `nil` URLs, should return "unsupported URL" errors rather than crash. Matches Darwin behaviour.

[URLSession] Do not crash for unsupported URLs

---

Sources/Foundation/NSString.swift
Tests/Foundation/Tests/TestNSString.swift

`NSString._getExternalRepresentation()` was not returning the string's external representation 👀.
For some reason, CF decides to only include the BOM in the external representation for encodings using the machine's local endianness (e.g. `.utf16`, `.utf32`) but not if you specify an explicit endianness (e.g. `.utf32BigEndian`). It does the same thing on Darwin Foundation -- I don't know why, and I don't agree with it, and it isn't documented anywhere AFAICT, but there it is.

Write string external representation in String.write(to: URL)

---

Sources/Foundation/JSONDecoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

On Darwin when you call `superDecoder` on the `JSONDecoder` keyed container and there is no associated value for the key passed in, it returns a new decoder that returns empty containers. On Linux it would throw a `DecodingError.keyNotFound` error.
This PR resolves this discrepancy by catching the `DecodingError.keyNotFound` error and returning a decoder that references a `JSONValue.null`.
The PR also adds a new test `test_notFoundSuperDecoder` to verify this fix.
This resolves apple/swift-corelibs-foundation#3169
cc: @fabianfett

Fix `JSONDecoder` superDecoder darwin/linux discrepancy

---

CoreFoundation/Base.subproj/CFRuntime.c

If they were NULL, the program would just exit so this check is not needed.

Remove unneeded check in CFRelease and CFRetain.

---

Sources/Foundation/AttributedString/AttributedString.swift
Tests/Foundation/Tests/TestAttributedString.swift

This corrects an issue in the `AttributedString.Runs` equality check when both collections are empty. Previously this led to an array out of bounds access when attempting to compare a run in the collection that did not exist. This also refactors the code a bit to make it more readable.
Resolves #4634

Fix logic error in AttributedString.Runs.== for empty collections

---

Sources/Foundation/JSONDecoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

On Darwin when you call `superDecoder` on the `JSONDecoder` keyed container and there is no associated value for the key passed in, it returns a new decoder that returns empty containers. On Linux it would throw a `DecodingError.keyNotFound` error.
This PR resolves this discrepancy by catching the `DecodingError.keyNotFound` error and returning a decoder that references a `JSONValue.null`.
The PR also adds a new test `test_notFoundSuperDecoder` to verify this fix.
This resolves apple/swift-corelibs-foundation#3169

[5.7] Fix JSONDecoder superDecoder darwin/linux discrepancy

---

CoreFoundation/Base.subproj/CFRuntime.c

This has been causing async functions to not return when using static linking.
rdar://96642321

Ensure libdispatch is always initialized before CoreFoundation

---

CoreFoundation/Base.subproj/CFRuntime.c

Backporting https://github.com/apple/swift-corelibs-foundation/pull/4666
This has been causing async functions to not return when using static linking.
rdar://96642321

[5.7] Ensure libdispatch is always initialized before CoreFoundation

---

Docs/Archiving.md
Sources/Foundation/NSGeometry.swift
Sources/Foundation/NSKeyedArchiver.swift
Sources/Foundation/NSKeyedUnarchiver.swift
Sources/Foundation/NSRange.swift
Sources/Foundation/NSSpecialValue.swift
Sources/Foundation/NSValue.swift
Tests/Foundation/Tests/TestNSKeyedArchiver.swift
Tests/Foundation/Tests/TestNSKeyedUnarchiver.swift

Originally when I implemented `NSValue`, I intended for it to be a class cluster with the concrete classes being `NSSpecialValue` or `NSConcreteValue`. At the time, Swift didn't support this pattern. Now it does support reassigning `self` (also see 00737ae0e), it makes sense to revisit this.
Also, make some other related code paths more idiomatically Swift, by eliminating force-unwrap and force-cast; at the time, I was less familiar with Swift.
Unfortunately since I [cannot build the TestFoundation target](https://forums.swift.org/t/cant-run-testfoundation-target-in-swift-corelibs-foundation-repository/50360/6) on macOS, it's not possible for me to run the tests (I don't have a Linux VM handy right now).

Foundation: more idiomatic Swift in NSKeyedArchiver

---

Sources/Foundation/NSURL.swift

On Windows, rather than recursively expanding a path component by component, perform a first pass resolution at the given path.  This potentially influences the path resolution as the component traversal would possibly fail to resolve cross-drive references.

Foundation: attempt a first pass symlink resolution

---

Sources/FoundationNetworking/NSURLRequest.swift
Tests/Foundation/Tests/TestNSURLRequest.swift
Tests/Foundation/Tests/TestURLRequest.swift

The URLRequest implementation previously allowed arbitrary CR and LF characters in header values. This change checks header values for invalid characters before setting or adding them to the request. It does allow for header line folding (CRLF followed by HTAB or SP), consistent with URLRequest on Darwin.

Check for invalid URLRequest header values

---

CoreFoundation/Parsing.subproj/CFXMLInterface.c
CoreFoundation/RunLoop.subproj/CFRunLoop.c

With the latest rebranch, the mismatched function pointer types raise an error rather than a warning.  Explicitly cast to the expected function pointer type rather than ignoring the warning.

CoreFoundation: explicitly cast to the proper fptr types

---

Tests/Foundation/Tests/TestNSString.swift

Use the `XCTAssert*` helpers to validate the state to get proper diagnostics emitted for test failures.  This should help debugging failures.

Tests: convert some assertions into XCTest forms

---

CoreFoundation/Base.subproj/CFPlatform.c

While we can enumerate the users using `NetUserEnum`, that does not guarantee that we get the full user information.  Perform an explicit `NetUserGetInfo` to query the user information to get the home directory.
Additionally, correct the `CFString` handling within the function where we were improperly using `CFStringCreateWithBytesNoCopy` which requires that the string is 8-bit encoded.  We now use
`CFStringCreateWithCharacters[NoCopy]` to properly create the `CFString` with unicode characters.

Base.subproject: correct home directory handling on Windows

---

Tests/Foundation/Tests/TestNSString.swift

Use `XCTAssertEqual` to assert equality to make it easier to diagnose and repair failures in the test suite.

Tests: convert assertions in test_expandingTildeInPath to XCTAssertEqual

---

Sources/Foundation/FileManager.swift

The `homeDirectory(forUser:)` is currently not functioning properly for users other than the current user.  Switch to directly using the CoreFoundation API which simplifies the logic and makes the functionality work on Windows.  This uses the forced unwrap for the return value, which was previously the case and resulted in a trap on Windows.

FileManager: repair `homeDirectoryForCurrentUser` on Windows

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Sources/FoundationNetworking/URLSession/WebSocket/WebSocketURLProtocol.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/Tests/TestDecimal.swift
Tests/Foundation/Tests/TestURLSession.swift

Two fixes required here:
- _WebSocketURLProtocol needs to detect a closing URL connection, and set its state to indicate this is a normal close of the connection
- URLSessionWebSocketTask needs to kick `doPendingWork()` if the connection is closed out due to an error, in order to respond to any pending Tasks parked in `receive()`

URLSessionWebSocketTask.receive() not finishing if server closes connection without a close packet

---

CoreFoundation/Base.subproj/CFPlatform.c

The profile directory for another user is considered private data and cannot be directly queried without an elevated privilege, the user's password, or a token with impersonation rights.  Resort to trawling through the registry to query the information.

Base: resort to more drastic means to query profile directory

---

CoreFoundation/Base.subproj/CFPlatform.c

The FLS destructors are required to be `__stdcall` calling convention rather than `__cdecl`.  Correct the definitions for them to repair the build on Windows x86 after a newer compiler identified this issue.  This attribute is ignored on non-x86 architectures and thus is safe to apply unconditionally.

Base: correct TLS handling on Windows x86

---

CoreFoundation/Parsing.subproj/CFXMLInterface.c

libxml2 added `const` to `xmlHashScanner` in v2.9.8. Wrap the call in a version check and cast for the non-const case.

Fix incompatible function pointer type

---

Sources/FoundationXML/XMLParser.swift

Final chunk of XML document was being skipped when parsing when in a WASI environment

Fix XML parsing in WASI environment

---

CoreFoundation/Base.subproj/CFBase.h
CoreFoundation/Base.subproj/CFOverflow.h
CoreFoundation/Base.subproj/ForFoundationOnly.h
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/PlugIn.subproj/CFBundle_Grok.c
Darwin/shims/FoundationOverlayShims.h

`_Bool` is not defined when importing Foundation with C++ interop enabled
resulting in the missing type. This patch defines `_Bool` to `bool` when
compiling for C++.
I'm not entire sure how to test this. The test itself is fairly simple, it's just
```
```
with the invocation `swiftc -Xcc -std=c++17 -enable-experimental-cxx-interop`, but I don't know how to tell XCTest to do that so I would like pointers there.
rdar://99713881

Add definition for _Bool in C++ mode

---

Sources/Foundation/Process.swift

Windows does not have a native `socketpair` interface and so we emulate that locally.  Furthermore, the use of `socketpair` on the other platforms uses an `AF_UNIX` (Unix Domain Socket) which is not guaranteed to be available on Windows.  As a result, we workaround that by using an `AF_INET` address family socket.  This will by default have Nagle enabled which can potentially cause some delays when processing a message.  We have observed occasional hangs in the process handling which may be possibly be attributed to the buffering.  Disable nagle on the sender side in the hopes of a more reliable connection.

Process: disable Nagle on Windows

---

Sources/Foundation/Data.swift
Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/Host.swift
Sources/Foundation/NSPathUtilities.swift
Sources/Foundation/NSURL.swift
Sources/Foundation/Process.swift
Sources/Foundation/ProcessInfo.swift
Sources/Foundation/Thread.swift

Add the missing imports for WinSDK and disambiguate the existing ones so resolve the issues identified when removing the SDK and using the `-vfsoverlay` flag to inject the overlay during the builds.

Foundation: add missing and disambiguation imports

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Locale.subproj/CFDateFormatter.c
CoreFoundation/Parsing.subproj/CFXMLInterface.c
CoreFoundation/Preferences.subproj/CFPreferences.c
CoreFoundation/URL.subproj/CFURL.c

This would save performance by removing unnecessary calls to CFStringCreateWithCString

Replace calls to CFStringCreateWithCString with constant CFStrings

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Locale.subproj/CFDateFormatter.c
CoreFoundation/Parsing.subproj/CFXMLInterface.c
CoreFoundation/Preferences.subproj/CFPreferences.c
CoreFoundation/URL.subproj/CFURL.c

Reverts apple/swift-corelibs-foundation#4694

Revert "Replace calls to CFStringCreateWithCString with constant CFStrings"

---

Sources/Foundation/ISO8601DateFormatter.swift

Fixes #4703.
[`ISO8601DateFormatter.Options`](https://github.com/apple/swift-corelibs-foundation/blob/7504fdfa4529ac01b77ab83bfee51a5f06e3e6d1/Sources/Foundation/ISO8601DateFormatter.swift#L14) currently uses `var` for its static properties. The properties should instead be declared using `let` to prevent accidental mutation and to let the compiler know that these properties are concurrency-safe.
Regarding the latter point, the following is an example error caused by this issue:
> error: reference to static property 'withInternetDateTime' is not concurrency-safe because it involves shared mutable state

Make `ISO8601DateFormatter.Options` static properties immutable

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CFRuntime.c
CoreFoundation/Locale.subproj/CFDateFormatter.c
CoreFoundation/Preferences.subproj/CFPreferences.c
CoreFoundation/URL.subproj/CFURL.c

This would save performance by removing unnecessary calls to CFStringCreateWithCString.
Note: Windows cannot CFSTR to private symbols, so CFXMLInterface is excluded from changes.

Replace calls to CFStringCreateWithCString with CFSTR macro

---

Tests/Foundation/Tests/TestProcess.swift

`test_multiProcesses` was failing in the Windows build when running under a substitute drive (mapping `S:` to `C:\foo\bar`) because it was expecting equality between `FileManager.default.currentDirectoryPath` and `FileManager.default.currentDirectoryPath.standardizePath()`, the latter of which resolves substitute drives.
See `xdgTestHelper`'s `--getcwd`:
https://github.com/apple/swift-corelibs-foundation/blob/5c1d6f67642ad7ce0d94b657bdb8a268fd18e570/Tests/Tools/XDGTestHelper/main.swift#L229
A different test, `test_pipe_stdout` was already doing this comparison properly:
https://github.com/apple/swift-corelibs-foundation/blob/5c1d6f67642ad7ce0d94b657bdb8a268fd18e570/Tests/Foundation/Tests/TestProcess.swift#L126

Fix incorrect test_multiProcesses path equality expectation

---

Docs/GettingStarted.md

Use proper shell markdown syntax so github's copy code block function works.
So copy/pasting into the shell doesn't require an edit first.
1. Changed  '\`\`\`' to ' \`\`\`sh'
2. Removed leading shell '%' symbol.
If this isn't against any style guides, I'd be willing to fix any other docs. I have the regex saved to clear it up globally.

Update GettingStarted.md so GitHub's 'copy' method works.

---

Tests/Foundation/Tests/TestURL.swift

Tests would break when the temporary directory included symlinks. This happens in the Windows build, which configures the temporary directory to be on a substituted drive.

Fix tests assuming that the temporary directory doesn't include symlinks

---

Sources/Foundation/JSONSerialization+Parser.swift
Sources/Foundation/JSONSerialization.swift

String(decoding:as:), which previously used by
JSONDecoder.readString() to make string from JSON bytes, would silently repair invalid UTF-8 sequence and not throw a error.
This commit uses String(bytes:encoding:) instead,
which will fail on invalid UTF-8 seqence.
This matches the behavior of Darwin Foundation.
(Some examples of invalid UTF-8: http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt)

JSONDecoder.readString(): throw on invalid UTF-8

---

Sources/Foundation/Unit.swift

not 100% sure this wasn't implemented elsewhere, but i didn't see these units

Foundation/Unit: add {m,u,p,n}second units to UnitDuration

---

CoreFoundation/Base.subproj/CFRuntime.c
Sources/Foundation/Process.swift

We've been seeing frequent (but not reproducible in isolation) failures in our builds where waitUntilExit returns but terminationStatus fails its precondition on hasFinished because isRunning is still true. This is a speculative fix, since I haven't been able to reproduce the failure in a self-contained test.
This should be safe since Process.waitUntilExit isn't spec'd to relate to RunLoop. In particular there is no guarantee that "stopping" a RunLoop should cause waitUntilExit to return before the monitored process has exited.
---
Unrelated to the above, the [second commit](https://github.com/apple/swift-corelibs-foundation/pull/4740/commits/5404e239d28e1ab32d7b58b5338980620cb5ea06) in this PR is required to unbreak XCTest's tests, which are run as part of this repo's CI (and so is …

waitUntilExit: ignore RunLoop.run()'s return value

---

Sources/Foundation/Bundle.swift
Tests/Foundation/Tests/TestBundle.swift

This was disabled due to the use of `dlsym` which has been removed in favour of CoreFoundation APIs.  Enable this code path and tweak the test to allow passing on Windows.  This function is required to support apple/swift-docc on Windows.

Foundation: implement `Bundle.init(for:)` on Windows

---

CoreFoundation/Base.subproj/CFBase.c

This saves us a lot of work is size is 0

Move the size check to be the first thing checked in CFAllocator functions

---

Sources/Foundation/CMakeLists.txt
Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/NSPathUtilities.swift
Sources/Foundation/WinSDK+Extensions.swift

The file attribute flags are used extensively in the file manipulation code.  Explicitly converting to the value to `DWORD` adds no value and clutters the code.  Provide an internal overload to translate the type appropriately.

Foundation: add some type conversion extensions for Windows

---

Sources/Foundation/NSURL.swift

This adjusts the file system representation accessor for a URL to support paths beyond `MAX_PATH`.  We do not know what the use of the file system representation is, so we cannot provide the NT style path (`\\?\`-prefixed).  Rather than using the filled in buffer, resolve the URL and then build the complete path copying that into a newly allocated buffer.  This ensures that we always have sufficient space for the path without having to grow the buffer.
Linux gets away with the current implementation by setting the `PATH_MAX` to page size (4096).  There may be some value in using the single implementation across the different platforms, but this will allow the Windows path to make progress even if it diverges from the reference implementation.
The issue was identified by the DocC test …

Foundation: support file system representation for long paths

---

Sources/Foundation/FileManager+Win32.swift

Reduce the conditional logic by unwrapping the handler rather than adding conditional case.  This should make it easier to perform a series of refactorings.

Foundation: simplify handler handling

---

Tests/Foundation/Tests/TestFileManager.swift

Windows uses a per-directory `NUL` rather than a global `/dev/null`. Adjust the test to use the appropriate spelling rather than potentially seeing a random drive-relative path which may exist as a deletable file.

Tests: correct spelling of `/dev/null` on Windows

---

Sources/Foundation/FileManager+Win32.swift
Tests/Foundation/Tests/TestFileManager.swift

The path that was being constructed would elide the penultimate arc in the path as the base URL was not marked as a directory.  As such, it was assumed to be a file URL, and making a URL relative to it would truncate the previously last arc.  Append the path component instead and explicitly indicate if it is a directory component when building the URL as we already have the information on hand.
This repairs the directory traversal on Windows.  The bug was identified by the DocC test suite on Windows.

Foundation: correct directory iteration on Windows

---

Sources/Foundation/FileManager+Win32.swift

Refactor directory iteration to avoid replicating the conversion to the
NT style paths everywhere.  The iteration logic can be done at a single
site with a callback to handle the iteration.
Improve handle long file paths on Windows when performing a `removeItem`
call.  Furthermore, correct a few areas where we were mishandling
junctions.  This would result in an early termination of the loop in
`removeItem` causing us to fail to clean up directories which we should
have been able to.  This improves the DocC test coverage on Windows.
Rework the file attribute reading on Windows operation to reformulate
the path to the absolute path representation and then into the NT form
before performing the operation.  This technically is a partial repair
as drive relative paths where the current …

Windows long paths support

---

Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager+Win32.swift

When constructing a `FileHandle` using a path, ensure that we use the NT file path representation on Windows.  This allows us to access files that may have greater than `MAX_PATH` length.

Foundation: support long file paths for `FileHandle` on Windows

---

Darwin/Foundation-swiftoverlay-Tests/TestCalendar.swift
Darwin/Foundation-swiftoverlay-Tests/TestDateInterval.swift
Darwin/Foundation-swiftoverlay-Tests/TestMeasurement.swift
Darwin/Foundation-swiftoverlay-Tests/TestPersonNameComponents.swift
Sources/Foundation/Operation.swift
Tests/Foundation/Tests/TestDateInterval.swift
Tests/Foundation/Tests/TestNSTextCheckingResult.swift

This PR replaces `OSX` with `macOS` in `available` attributes.

Fix `available` attributes

---

Sources/Foundation/FileManager+Win32.swift

Adjust the `_fileExists` implementation in `FileManager` for Windows to use NT style paths to exceed path limits of `PATH_MAX` and address the full paths lengths supported by Windows NT.

Foundation: adjust `_fileExists` for NT style paths

---

Tests/Foundation/Tests/TestFileHandle.swift

Fix a concurrency bug in the `TestFileHandle.test_readToEndOfFileAndNotify()` unit test.
This test fails to build when corelibs-xctest marks the expectation handler as `@Sendable`. The fix is to replace the use of a `Bool` value with a separate expectation.

Fix a concurrency bug in the TestFileHandle.test_readToEndOfFileAndNotify() unit test.

---

Sources/Foundation/RunLoop.swift

When processing events on the main runloop, we should unmask the Windows message pump events.  If we do not unmask these events, the main RunLoop is unable to process the UI events and the user has no mechanism for integrating the Windows message pump events into the run loop.
This is a slightly restrictive compromise to enable the use of RunLoop on Windows for pumping a UI application.  Because CoreFoundation is not a supported API surface a user cannot simply invoke the appropriate CoreFoundation function on the RunLoop's inner (CFRunLoop) object.  In order to not expose any new CoreFoundation APIs, we need to expose the functionality from the Swift layer.  This is motivated by the desire to minimise the divergence from the reference implementation of CoreFoundation.
The Swift API …

Foundation: unmask Windows events on the main RunLoop

---

Foundation.xcodeproj/project.pbxproj

This PR removes an invalid file reference in the project.
The 'TestNSProgressFraction.swift' file seems to no longer exist.

Remove an invalid file reference

---

Sources/Foundation/UserDefaults.swift
Tests/Foundation/Tests/TestUserDefaults.swift

This PR fixes `UserDefaults.string(forKey:)` behavior for number values. Resolves #3362.
https://developer.apple.com/documentation/foundation/userdefaults/1416700-string
```swift
UserDefaults.standard.set(true, forKey: "key1")
UserDefaults.standard.set(42, forKey: "key2")
UserDefaults.standard.set(12.34 as Float, forKey: "key3")
UserDefaults.standard.set(12.34, forKey: "key4")
UserDefaults.standard.set("1234", forKey: "key5")
// on macOS
UserDefaults.standard.string(forKey: "key1") // "1"
UserDefaults.standard.string(forKey: "key2") // "42"
UserDefaults.standard.string(forKey: "key3") // "12.34"
UserDefaults.standard.string(forKey: "key4") // "12.34"
UserDefaults.standard.string(forKey: "key5") // "1234"
// on Linux
UserDefaults.standard.string(forKey: "key1") // nil …
```

Fix `UserDefaults.string(forKey:)` behavior

---

Sources/Foundation/UserDefaults.swift
Tests/Foundation/Tests/TestUserDefaults.swift

This PR fixes `UserDefaults.integer(forKey:)` behavior for boolean and floating-point values.
https://developer.apple.com/documentation/foundation/userdefaults/1407405-integer
```swift
UserDefaults.standard.set(true, forKey: "key1")
UserDefaults.standard.set(42, forKey: "key2")
UserDefaults.standard.set(12.34 as Float, forKey: "key3")
UserDefaults.standard.set(12.34, forKey: "key4")
UserDefaults.standard.set("1234", forKey: "key5")
// on macOS
UserDefaults.standard.integer(forKey: "key1") // 1
UserDefaults.standard.integer(forKey: "key2") // 42
UserDefaults.standard.integer(forKey: "key3") // 12
UserDefaults.standard.integer(forKey: "key4") // 12
UserDefaults.standard.integer(forKey: "key5") // 1234
// on Linux
UserDefaults.standard.integer(forKey: "key1") // 0 …
```

Fix `UserDefaults.integer(forKey:)` behavior

---

Sources/Foundation/FileManager+Win32.swift

`MoveFileExW` does not permit moving directories across volumes. Account for this by checking the source and fallback to copy and delete.

Foundation: make `_moveItem` resilient to multiple volumes

---

Sources/Foundation/UserDefaults.swift
Tests/Foundation/Tests/TestUserDefaults.swift

This PR fixes `UserDefaults.float(forKey:)` behavior for missing number values.
https://developer.apple.com/documentation/foundation/userdefaults/1414027-float
```swift
UserDefaults.standard.set(true, forKey: "key1")
UserDefaults.standard.set(42, forKey: "key2")
UserDefaults.standard.set(12.34 as Float, forKey: "key3")
UserDefaults.standard.set(12.34, forKey: "key4")
UserDefaults.standard.set("1234", forKey: "key5")
// on macOS
UserDefaults.standard.float(forKey: "key1") // 1
UserDefaults.standard.float(forKey: "key2") // 42
UserDefaults.standard.float(forKey: "key3") // 12.34
UserDefaults.standard.float(forKey: "key4") // 12.34
UserDefaults.standard.float(forKey: "key5") // 1234
// on Linux
UserDefaults.standard.float(forKey: "key1") // 0
UserDefaults.standard.float(forKey: "key2") // 0 …
```

Fix `UserDefaults.float(forKey:)` behavior

---

Sources/Foundation/NSPathUtilities.swift

Prefer to use `withNTPathRepresentation` over the
`_fileSystemRepresentation` usage as the former will not convert to the NT UNC path representation which may break on long paths.

Foundation: adjust `_NSCleanupTemporaryFile` on Windows

---

Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/NSData.swift

We would previously use the FSR for the path, however, due to the expectations of FSR, we cannot support long paths with it.  Use the internal `withUnsafeNTPath` extension on `URL` to use a long path representation to support extended paths (>260 characters) on Windows.

Foundation: alter `NSData.contents(of:options:)` on Windows

---

Sources/Foundation/UserDefaults.swift
Tests/Foundation/Tests/TestUserDefaults.swift

This PR fixes `UserDefaults.double(forKey:)` behavior for missing number values.
https://developer.apple.com/documentation/foundation/userdefaults/1416581-double
```swift
UserDefaults.standard.set(true, forKey: "key1")
UserDefaults.standard.set(42, forKey: "key2")
UserDefaults.standard.set(12.34 as Float, forKey: "key3")
UserDefaults.standard.set(12.34, forKey: "key4")
UserDefaults.standard.set("1234", forKey: "key5")
// on macOS
UserDefaults.standard.double(forKey: "key1") // 1
UserDefaults.standard.double(forKey: "key2") // 42
UserDefaults.standard.double(forKey: "key3") // 12.34000015258789
UserDefaults.standard.double(forKey: "key4") // 12.34
UserDefaults.standard.double(forKey: "key5") // 1234
// on Linux
UserDefaults.standard.double(forKey: "key1") // 0 …
```

Fix `UserDefaults.double(forKey:)` behavior

---

Sources/Foundation/JSONDecoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

`JSONDecoder.decode(_,from:)` accepts  a generic parameter, but it does not use any concrete type in practice.
This PR fixes that use parameter `type` instead of `T.self`.
This PR solves #4806 
Example Code
```swift
class Base: Codable { }
class Child: Base { }
func dynamicType() -> Base.Type {
return Child.self
}
let data = "{}".data(using: .utf8)!
let classType = dynamicType()
let instance = try JSONDecoder().decode(classType, from: data)
print("type: \(instance) => \(type(of: instance))")
```
on macOS:
```
type: JSONDecoderExample.Child => Child
```
on Linux:
```
type: JSONDecoderExample.Base => Base
```

Fix JSONDecoder.decode(_,from:) behavior

---

Tests/Foundation/Tests/TestFileHandle.swift

**Explanation:** swift-corelibs-xctest is adopting some changes in 5.9 to improve concurrency support. This change fixes a unit test in this package that currently fails (due to a real bug in the test) when the XCTest changes are applied.
**Scope:** A fix to a unit test only. No effect on the primary package target.
**Issue:** #4787
**Risk:** No obvious risk.
**Testing:** Simply run the unit test and confirm it builds and passes.
**Reviewer:** @parkera _et al._

[5.9] Forward unit test concurrency fix from main

---

Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager+Win32.swift

On Apple platforms, the `FileManager` APIs `copyItem(atPath:toPath:)` and `copyItem(at:to:)` refuse to overwrite the destination file (or link, or directory) if it already exists; this behavior is even [explicitly](https://developer.apple.com/documentation/foundation/nsfilemanager/1407903-copyitematpath#discussion) [documented](https://developer.apple.com/documentation/foundation/nsfilemanager/1412957-copyitematurl#discussion). And indeed, any such attempt results in a `fileWriteFileExists` error.
However, on Linux and Windows, the destination is silently overwritten. This PR changes that behavior to match what's documented. On POSIX platforms, this is accomplished by adding the [`O_EXCL` flag](https://man7.org/linux/man-pages/man2/open.2.html#:~:text=O_EXCL%20Ensure) to the relevant …

Fix divergent overwrite behavior of FileManager.copyItem(at:to:) on Linux and Windows

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

The newer clang compiler prefers `module.modulemap` over `module.map`. This will result in us using the framework form of the module definitions for CoreFoundation. While this is fine for the compilation, the linker directive to link against the framework will also be emitted into the object files. This causes a linker failure on Windows as `-framework (CoreFoundation|CFURLInterface|CFXMLInterface)` is not a valid linker option. Use the swift control over the directives to avoid emitting the framework link directive to repair the build.

build: adjust the build for rebranch

---

Tests/Foundation/Tests/TestURL.swift

See: https://github.com/apple/swift-corelibs-foundation/pull/4723
Fixes failures hit in: https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/902/

Cherry pick fix to symlink url tests

---

Sources/Foundation/Date.swift
Sources/Foundation/DateComponents.swift
Sources/Foundation/DateInterval.swift

In https://github.com/apple/swift-corelibs-foundation/pull/4777, I made them `Sendable` in the overlay instead of the real `Foundation` module. This PR fixes that.

Make `Date`, `DateComponents` and `DateInterval` `Sendable`

---

Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager+Win32.swift

_This is a cherry-pick of #4821 to 5.10._
On Apple platforms, the `FileManager` APIs `copyItem(atPath:toPath:)` and `copyItem(at:to:)` refuse to overwrite the destination file (or link, or directory) if it already exists; this behavior is even [explicitly](https://developer.apple.com/documentation/foundation/nsfilemanager/1407903-copyitematpath#discussion) [documented](https://developer.apple.com/documentation/foundation/nsfilemanager/1412957-copyitematurl#discussion). And indeed, any such attempt results in a `fileWriteFileExists` error.
However, on Linux and Windows, the destination is silently overwritten. This PR changes that behavior to match what's documented. On POSIX platforms, this is accomplished by adding the [`O_EXCL` …

[5.10] Cherry-pick Fix divergent overwrite behavior of FileManager.copyItem(at:to:) on Linux and Windows

---

Tests/Foundation/Tests/TestURL.swift

Cherry-picks 6cbe5e0f0c7ca266d322a6d6ba7ad5209a5b31b3.
-----
Don't assume that the temporary directory doesn't include symlinks.

[5.9.1] Enable macros for Windows in 5.9.1

---

CoreFoundation/Locale.subproj/CFDateIntervalFormatter.c
CoreFoundation/PlugIn.subproj/CFBundle_Resources.c

Fixes issue #4642: Encountering "Constant strings cannot be deallocated" in Linux foundation
The reported error was an CFSTR("") which is later released. While this should not be a problem, the Linux implementation of CFSTR does not ignore dealloc on constant strings. Fixed this by calling CFRetain on the constant string.
Strictly speaking this is only a workaround. Issue #1351 has some hints how this could be fixed but the workaround is used a over the code so I think it is okay to use it here, too.
I found the same problem in CFDateIntervalFormatter.c where it appeared in a error handling code path that should never be called. Fixed anyways.

Fixes issue #4642: Encountering "Constant strings cannot be deallocated" in Linux foundation

---

CoreFoundation/URL.subproj/CFURLSessionInterface.c
CoreFoundation/URL.subproj/CFURLSessionInterface.h
Sources/FoundationNetworking/URLSession/FTP/FTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/libcurl/EasyHandle.swift

`URL` and `curl` should agree on the host. Otherwise, fail the transfer with `NSURLErrorBadURL`.

Ensure URLSession and curl agree on the host

---

Sources/Foundation/JSONEncoder.swift
Tests/Foundation/Tests/TestJSONEncoder.swift

This PR tries to fix `JSONEncoder.OutputFormatting.sortedKeys` behavior. Resolves #4702.
I estimated string comparison options by trying the following code on macOS.
```swift
let testValue = [
"2": "2",
"25": "25",
"7": "7",
"ａｌｉｃｅ": "ａｌｉｃｅ",
"bob": "bob",
"Charlie": "Charlie",
"日本": "日本",
"中国": "中国",
"韓国": "韓国",
]
let encoder = JSONEncoder()
encoder.outputFormatting = .sortedKeys
let data = try! encoder.encode(testValue)
let string = String(data: data, encoding: .utf8)!
print(string)
// {"2":"2","7":"7","25":"25","ａｌｉｃｅ":"ａｌｉｃｅ","bob":"bob","Charlie":"Charlie","中国":"中国","日本":"日本","韓国":"韓国"}
print(testValue.sorted { $0.key.compare($1.key, options: [.caseInsensitive, .diacriticInsensitive, .forcedOrdering, .numeric, .widthInsensitive]) == .orderedAscending }.map(\.key))
// ["2", "7", "25", …
```

Fix `JSONEncoder.OutputFormatting.sortedKeys` behavior

---

CoreFoundation/URL.subproj/CFURLSessionInterface.c
CoreFoundation/URL.subproj/CFURLSessionInterface.h
Sources/FoundationNetworking/URLSession/FTP/FTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/libcurl/EasyHandle.swift

Cherry-pick of #4836 to `release/5.10`
`URL` and `curl` should agree on the host. Otherwise, fail the transfer with `NSURLErrorBadURL`.

[5.10] Cherry-pick Ensure URLSession and curl agree on the host #4836

---

Sources/Foundation/NSLock.swift
Tests/Foundation/Tests/TestNSLock.swift

Fixes #4735.
Xcode 14 introduced the `NSLocking.withLock(_:)` method to the Darwin implementation of Foundation. This commit adds the new method to the open-source implementation.
(Note: The [documentation](https://developer.apple.com/documentation/foundation/nslocking/4059821-withlock) incorrectly specifies the availability of the method as iOS 16+, etc. but it is actually available on all OS versions because it is marked [`@_alwaysEmitIntoClient`](https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_alwaysemitintoclient). The documentation bug is tracked by [FB11968310](https://feedbackassistant.apple.com/feedback/11968310).)
I copied the implementation from `Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Lib …

Add `NSLock.withLock(_:)` method

---

CoreFoundation/RunLoop.subproj/CFRunLoop.c

The failure memory order cannot be release or acq_rel. Clang since https://github.com/llvm/llvm-project/commit/fed564432cef76f8b303c19ab1dfc0a14878fbc3 diagnoses an invalid argument.

[runloop] Fix the failure memory order argument to atomic_compare_exchange_strong_explicit

---

CoreFoundation/Locale.subproj/CFLocale.c
CoreFoundation/PlugIn.subproj/CFBundle_Locale.c

From Clang 15, nested static initializer inside statement-expression is no longer a constant-time expression (See https://reviews.llvm.org/D127201). OSS Foundation defines `CFSTR` as a macro rather than `__builtin___CFStringMakeConstantString` and it uses nested static initializer inside statement-expression, so we can't assume `CFSTR` itself is always a constant-time expression.
This patch removes some `static` qualifiers associated with `CFSTR` to make them acceptable with Clang 15 and later.
I confirmed there is no change at LLVM IR level between before/after this patch with Clang 14 and `-O3`, so I assume Clang 15 and later also can optimize those non-static variables to be static global rodata. So this fix does not cause any performance regression.
This issue was originally found in …

Stop assuming `CFSTR` is a constant-time expression with Clang 15

---

Foundation.xcodeproj/project.pbxproj

Xcode 15 no longer recognizes 10.12 as a valid deployment target and just falls back to 14.2, which is too new for our CI. XCTest side has already done a similar change https://github.com/apple/swift-corelibs-xctest/pull/459

Bump the macOS deployment target to 10.13 in the Xcode project.

---

Sources/BlocksRuntime/runtime.c

BlocksRuntime uses dlsym to find objc_destructInstance, which is not available on all platforms. This change adds a check for dlfcn.h and only uses dlsym if it is available and otherwise crashes the program.
The crash will not usually happen, as `_Block_use_RR` is only called from objc-auto, which is not available for such platforms.

[wasm] Port BlocksRuntime for no dlfcn.h platforms

---

Sources/Foundation/NSError.swift

Excluded the missing errno in WASI

[wasm] Port NSError.swift for WASI

---

CoreFoundation/Base.subproj/CFInternal.h
CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CFRuntime.c
CoreFoundation/Base.subproj/CFUtilities.c
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/Foundation/NSLock.swift

This change ports the thread-related APIs for the no thread platform by adding no-op implementations. Note that WASI is going to support threads in the near future, so this does not guard by `TARGET_OS_WASI` but by `!SWIFT_CORELIBS_FOUNDATION_HAS_THREADS` to make it easier for future WASI + threads support.

[wasm] Port thread-related APIs for no thread platform

---

CMakeLists.txt
CoreFoundation/Base.subproj/CFUtilities.c
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/CMakeLists.txt
Sources/BlocksRuntime/CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/Foundation/Data.swift
Sources/Foundation/FileHandle.swift
Sources/Foundation/Host.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSSwiftRuntime.swift
Sources/Foundation/NSURL.swift
Sources/Foundation/Process.swift
Sources/Foundation/Thread.swift
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt
Sources/Tools/plutil/CMakeLists.txt
Sources/Tools/plutil/main.swift
Sources/UUID/CMakeLists.txt
cmake/modules/FindLibRT.cmake
cmake/modules/SwiftSupport.cmake

A few fixes are needed for swift-corelibs-foundation to make it work with Musl and the new fully-static Linux support I’m adding to Swift.
As with swift-corelibs-dispatch, we need a way to set the Swift libdir name that isn’t just lowercasing `CMAKE_SYSTEM_NAME` (because that won’t always work).
Musl doesn’t have `strlcpy()` or `strlcat()`, so we need to handle that (we should get CMake to look for these). It also doesn’t have `__GLIBC_PREREQ` (since it isn’t Glibc).
Another issue is that in order to support static linking, we need to make sure we’re linking with all the dependencies we need (we need to add `libz`, `libcrypto` and `libssl` in a couple of places, as well as `libfts` in the case of Musl. We also need to locate `librt` when we’re statically linking.
rdar://123381867

Fix swift-corelibs-foundation for Musl compatibility

---

Foundation.xcodeproj/project.pbxproj

macOS build was broken by 3744d4d2df6b43f87fbc075b91296f4d0c94ab0f, which introduced a new constant definition but did not add it to the Xcode project.

Repair the macOS build by adding missing `-D` in Xcode project

---

CoreFoundation/Base.subproj/CFFileUtilities.c

This patch makes `CoreFoundation/Base.subproj/CFFileUtilities.c` compilation work with wasi-libc

[wasm] Port `CoreFoundation/Base.subproj/CFFileUtilities.c`

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/URL.subproj/CFURL.c

wasi-libc now has user-land implementations of `getcwd`, so we don't need to guard cwd-related APIs.

[wasm] Unlock cwd-related APIs

---

CoreFoundation/Base.subproj/CFRuntime.c

This patch makes a part of `CoreFoundation/Base.subproj/CFRuntime.c` compilation work with wasi-libc

[wasm] Port CoreFoundation/Base.subproj/CFRuntime.c

---

CoreFoundation/Base.subproj/CFPlatform.c

The `environ` variable in wasi-libc need to be accessed through the `__wasilibc_get_environ` function to ensure that it is initialized properly.

[wasm] Use `__wasilibc_get_environ` to get environ

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CFRuntime.c

Function signature cannot be inconsistent in Wasm platforms. This patch fixes the signature of `swift_retain` to return the retained object.

[wasm] Fix signatures of `swift_retain`

---

CoreFoundation/Base.subproj/CFPlatform.c
CoreFoundation/Base.subproj/CFPriv.h

This patch makes a part of `PocessInfo` APIs work with wasi-libc. On WASI, it gets program name from argv[0].

[wasm] Port ProcessInfo for WASI platform

---

Sources/Foundation/NSPathUtilities.swift

WASILibc's `errno` conflicts with Clang-imported `errno` in <errno.h>.

[wasm] Fix definition conflict of `errno`

---

CoreFoundation/StringEncodings.subproj/CFPlatformConverters.c
CoreFoundation/StringEncodings.subproj/CFStringEncodingConverter.c

This commit adds `TARGET_OS_WASI` as ICU supported platform in `#if` conditions under `StringEncodings.subproj`

[wasm] Port `CoreFoundation/StringEncodings.subproj`

---

Sources/Foundation/NSPathUtilities.swift

WASI does not have temp directories and wasi-libc does not provide `mkstemp`, so provide a stub implementation that throws `ENOTSUP`.

[wasm] Provide stub for `_NSCreateTemporaryFile` on WASI

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/NSData.swift

This unlocks most of FileManager APIs on WASI platform. WASI lacks the following concepts:
- Device numbers
- File ownership
Also wasi-libc does not provide the following functionalities at the moment:
- `realpath(3)` (This will be included in the next release https://github.com/WebAssembly/wasi-libc/pull/473)
- `fts(3)`

[wasm] Port FileManager for WASI platform

---

CoreFoundation/URL.subproj/CFURL.c

wasi-libc does not provide `syslog.h`, so we should only include it if it is available. syslog APIs are only used for debugging code guarded under `DEBUG_URL_MEMORY_USAGE`, so it is safe to exclude it.

[wasm] Include syslog.h only if available

---

CoreFoundation/Preferences.subproj/CFPreferences.c
CoreFoundation/Preferences.subproj/CFXMLPreferencesDomain.c

Fix compilation issues under the subproj for the WASI platform

[wasm] Port CoreFoundation/Preferences.subproj

---

CoreFoundation/PlugIn.subproj/CFBundle.c
CoreFoundation/PlugIn.subproj/CFBundle_BinaryTypes.h
CoreFoundation/PlugIn.subproj/CFBundle_InfoPlist.c
CoreFoundation/PlugIn.subproj/CFBundle_Internal.h
CoreFoundation/PlugIn.subproj/CFBundle_Resources.c

Just add WASI platform as a Unix-y platform

[wasm] Port CoreFoundation/PlugIn.subproj

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/String.subproj/CFCharacterSetData.S
CoreFoundation/String.subproj/CFString.c
CoreFoundation/String.subproj/CFStringUtilities.c
CoreFoundation/String.subproj/CFUniCharPropertyDatabase.S
CoreFoundation/String.subproj/CFUnicodeData.S

- LLVM's AsmParser for WebAssembly requires explicit data segment size in `.S`
- Add `TARGET_OS_WASI` branch as Unix-y platform

[wasm] Port CoreFoundation/String.subproj

---

Sources/Foundation/Data.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSPathUtilities.swift
Sources/Foundation/NSURL.swift

Those guards were added to prevent the build from failing on WASI, but they are too conservative and the latest wasi-libc is now providing enough support for these operations.

[wasm] Remove too conservative guards around file operations

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Sources/Foundation/FileManager+POSIX.swift

Unfortunately they are defined in the way ClangImporter can't handle them, so we need to grab them manually through function calls. Those calls are usually inlined, so the performance impact should be minimal.
This workaround can be removed after https://github.com/apple/swift/issues/43102 will be "fixed"

[wasm] Grab wasi-libc constants manually

---

CoreFoundation/Base.subproj/CFInternal.h
CoreFoundation/Stream.subproj/CFStream.h

To avoid the use of `libdispatch` types in the `CoreFoundation` module when unavailable

[wasm] Guard out the use of `libdispatch` types

---

CoreFoundation/NumberDate.subproj/CFDate.c

This commit adds `TARGET_OS_WASI` as ICU supported platform in `#if` conditions under `NumberDate.subproj`.

[wasm] Port CoreFoundation/NumberDate.subproj

---

CoreFoundation/Locale.subproj/CFLocale.c

* Remove no longer needed `#if !TARGET_OS_WASI`
* Add WASI to the list of ICU supported platforms

[wasm] Port CoreFoundation/Locale.subproj

---

CoreFoundation/Stream.subproj/CFStream.c

This patch guards the use of RunLoop, which is not available on no-dispatch platforms. `CFStream` is still useful without RunLoop integration to port some APIs like `PropertyListSerialization`.

[wasm] Port CFStream for no-dispatch platforms

---

CoreFoundation/CMakeLists.txt

* CFXMLInterface usually depends on BlocksRuntime through dispatch indirectly, so we need to link it explicitly for no-dispatch builds to include BlocksRuntime headers.
* Enable some wasi-libc emulations for building CF.

[wasm] Port CoreFoundation/CMakeLists.txt

---

CoreFoundation/RunLoop.subproj/CFRunLoop.c
CoreFoundation/RunLoop.subproj/CFSocket.c

Guard out the whole source code for no-dispatch platforms. Excluding them from the build at all is one of the options, but it introduces some complexities in CMake build script just for the specific target, so I prefer this way.

[wasm] Guard RunLoop.subproj sources with `__HAS_DISPATCH__`

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

This change enables wasi-libc emulations for Foundation and FoundationXML to properly import CoreFoundation, which includes those emulation libraries as a part of public interface.

[wasm] Enable wasi-libc emulations for Foundation

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Sources/Foundation/Data.swift
Sources/Foundation/FileHandle.swift

The `wasi_emulated_mman` module must be imported with `@_implementationOnly` to avoid requiring Foundation users to enable `_WASI_EMULATED_MMAN` by themselves. "private import" does not work here because it still imports private dependencies while building a module that import Foundation.

[wasm] Define `_WASI_EMULATED_MMAN` to replace imports

---

Sources/Foundation/FileHandle.swift

* Unsupport background read/write operations
* Unsupport Pipe

[wasm] Port Sources/Foundation/FileHandle.swift

---

Sources/Foundation/Host.swift
Sources/Foundation/NSCharacterSet.swift
Sources/Foundation/NSKeyedArchiver.swift
Sources/Foundation/NSPathUtilities.swift
Sources/Foundation/NSString.swift
Sources/Foundation/ScannerAPI.swift

* Removed too conservative guards
* Port `Host` class
* Add `arch(wasm32)` to 32-bit arch conditions

[wasm] Miscellaneous Foundation fixes

---

Sources/Foundation/NSObjCRuntime.swift

Excluded unavailable classes from `NSClassFromString` mapping table.

[wasm] Port Sources/Foundation/NSObjCRuntime.swift

---

CoreFoundation/Base.subproj/CFPriv.h
CoreFoundation/Base.subproj/CFRuntime.c
CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/Base.subproj/ForFoundationOnly.h
CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h

* Remove too conservative include guards
* Update class table to exclude unavailable classes
* Port mach_absolute_time to WASI platform
This is the final patch of the patch series for WebAssembly support.

[wasm] Miscellanous Base.subproj fixes

---

CoreFoundation/Stream.subproj/CFStream.c

This patch is a follow-up fix for
efc01825039b5d0c59310fc8b59ce483a4b57dd1 to fix undefined symbol reference against excluded CFRunLoop APIs.

[wasm] Follow-up dispatch fix for CFStream.c

---

CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
Sources/Foundation/FileManager+POSIX.swift

wasi-libc defines `d_name` as "flexible array member" which is not supported by ClangImporter yet. This patch replaces the use of `d_name` with a helper function `_direntName` to work around the issue.

[wasm] Port use of `dirent` for wasi-libc

---

CoreFoundation/Preferences.subproj/CFXMLPreferencesDomain.c

In __CFWriteBytesToFileWithAtomicity(), we first write the contents of the plist to an auxiliary copy file, and then move that copy to where the original used to be. Because that file needs to have the same owner as the original, we would use chown() to change ownership as the last step. This allows a race condition where the new file is in its final location, but doesn't have the correct permissions. To fix this, call chown() on the file before moving.
rdar://121597642

Fix race condition in CFPreferences

---

Docs/GettingStarted.md

https://www.swift.org/install/macos/#installation-via-swiftorg-package-installer

[Docs/GettingStarted] Update macOS toolchain installation link

---

Package.swift

This points the `package` branch at the `main` branch of Apple's swift-foundation repo. I use the `revision:` here instead of `branch: "main"` to ensure that the checkout has a new-enough commit of swift-foundation for the support needed.
I confirmed this builds on linux locally

Make package SCF depend on Apple swift-foundation repo

---

Package.swift

This updates our dependency on swift-foundation to the latest commit on `main`, and also relaxes the swift-foundation-icu dependency to allow future minor version changes. With this dependency update, we now have no test failures when testing on linux!
```
Test Suite 'All tests' passed at 2024-04-02 17:32:35.224
Executed 1893 tests, with 30 tests skipped and 0 failures (0 unexpected) in 71.168 (71.168) seconds
```

Update dependencies to latest swift-foundation/swift-foundation-icu

---

Sources/Foundation/NSLock.swift

As per issue: https://github.com/apple/swift-corelibs-foundation/issues/4941  and forum discussion: https://forums.swift.org/t/sendable-conformance-of-nslock-on-linux/71506
Resolves #4941

add Sendable conformance to NSLock

---

Sources/Foundation/NSStringAPI.swift

This removes a handful of `String` APIs that currently call into `NSString` but are already being re-exported from swift-foundation so we can remove them. All tests pass on linux with this change

Remove String APIs currently implemented in swift-foundation

---

Package.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/NSArray.swift
Sources/Foundation/NSCharacterSet.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSDictionary.swift
Sources/Foundation/NSError.swift
Sources/Foundation/NSString.swift
Sources/Foundation/NSURL.swift
Sources/Foundation/NSURLComponents.swift
Sources/Foundation/URL.swift
Sources/Foundation/URLComponents.swift
Sources/FoundationNetworking/URLSession/NetworkingSpecific.swift
Tests/Foundation/TestBundle.swift
Tests/Foundation/TestDataURLProtocol.swift
Tests/Foundation/TestFileManager.swift
Tests/Foundation/TestURL.swift
Tests/Foundation/TestURLSession.swift

This PR removes the `URL` type in favor of the `URL` type provided by swift-foundation. It contains a few minor test adjustments to account for the new URL parser (which can behave slightly differently).
This disables one test which we'll come back to soon to update for the new parsing behavior (cc @jrflat), otherwise all but 2 tests pass and those two failures will be fixed by https://github.com/apple/swift-foundation/pull/602 which contains a bug-fix for `URL`s created from relative paths. I'll update the dependency's commit hash once that PR is merged

Remove URL in favor of swift-foundation's URL

---

CoreFoundation/Locale.subproj/CFLocale.c
CoreFoundation/PlugIn.subproj/CFBundle_Locale.c

From Clang 15, nested static initializer inside statement-expression is no longer a constant-time expression (See https://reviews.llvm.org/D127201). OSS Foundation defines `CFSTR` as a macro rather than `__builtin___CFStringMakeConstantString` and it uses nested static initializer inside statement-expression, so we can't assume `CFSTR` itself is always a constant-time expression.
This patch removes some `static` qualifiers associated with `CFSTR` to make them acceptable with Clang 15 and later.

🍒[Swift 5.10] Stop assuming `CFSTR` is a constant-time expression with Clang 15

---

CoreFoundation/Base.subproj/CoreFoundation_Prefix.h
CoreFoundation/CMakeLists.txt

Some newer builds of glibc have strlcpy and strlcat defined, resulting in build failures on newer Linux distros. Rather than try to hard-code whether or not each version of each platform has strlcat and strlcpy, this patch has CMake check to see if it's available after including string.h. If they are, then we should not redefine them.
This is a targeted change pulling the fix from the patch set merged in 5a1db791ab824e29dc45ce08f729d3541f0517d0.

🍒 [5.10] Check for strlcpy/strlcat

---

Sources/Foundation/Bundle.swift

CFBundle, which this is a wrapper for, is thread safe, and NSBundle is marked as Sendable on Darwin. Since swift package manager inserts references to Bundle when using resources, it is important to make sure this type doesn't produce any warnings in Swift 6 mode.

Mark Bundle as Sendable

---

CoreFoundation/URL.subproj/CFURLSessionInterface.c
CoreFoundation/URL.subproj/CFURLSessionInterface.h
Sources/FoundationNetworking/URLSession/libcurl/MultiHandle.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/Tests/TestURLSession.swift

To avoid issues described in #4791 we have to follow `DispatchSource` cancel procedures in the first place. I.e. we have to prevent underlying socket close until `DispatchSource` calls a cancel handler.
Everything becomes complicated a bit, because we have multiple cases for socket and `DispatchSource` lifecycle. Cancelling Dispatch Source is asynchronous operation (with control points at the start and at the end of the process), and other actions, despite being simple and synchronous, become more complicated due to their dependency on cancel operation. Some of basic cases:
- Socket could (but not necessary would) outlive its owning `easy_handle`, as CURL caches connections in `multi_handle`
- 99% of time DispatchSource cancels quickly, but sometimes some other work on the queue squeezes …

Cancel `DispatchSource` before closing socket (#4791)

---

Sources/FoundationNetworking/URLSession/libcurl/MultiHandle.swift

CURL documentation (https://curl.se/libcurl/c/CURLMOPT_TIMERFUNCTION.html) explicitly says that the timer should be non-repeatable. We basically have to follow CURL requests for setting, resetting and disarming such timers.
Current logic eventually leaves a 1ms repeating timer forever, because CURL assumes it fires once, and may not ask us to remove it explicitly. Which is bad for app power consumption, I suppose.
Also, being used as request timeout trigger, this timer also has no sense to be repeated.

Make `_MultiHandle` timeout timer non-repeatable

---

Package.swift
Sources/Foundation/NSNumber.swift
Tests/Foundation/TestFileManager.swift

This allows the changes in https://github.com/apple/swift-foundation/pull/641 to initialize NSNumbers in FoundationEssentials

Add upcall for FoundationEssentials to initialize NSNumbers

---

Sources/Foundation/NSURLQueryItem.swift
Sources/Foundation/URLQueryItem.swift

`URLQueryItem` is already implemented in `FoundationEssentials`.

Remove URLQueryItem from swift-corelibs-foundation in favor of FoundationEssentials.URLQueryItem

---

CoreFoundation/RunLoop.subproj/CFSocket.c
Tests/Foundation/Tests/TestSocketPort.swift

Fixes https://github.com/apple/swift/issues/73532.
On Windows, socket handles in a `fd_set` are not represented as bit flags as in Berkeley sockets. While we have no `fd_set` dynamic growth in this implementation, the `FD_SETSIZE` defined as 1024 in `CoreFoundation_Prefix.h` should be enough for majority of tasks.
This also includes a test for `SocketPort` which uses `CFSocket` internally. This test fails (hangs or crashes with memory corruption error) without the fix.

[Windows] Use `fd_set` according to Winsock2 specifics

---

Sources/Foundation/NSData.swift

This removes the various options structs defined in an extension on `NSData` in favor of type aliases pointing to the "true" option structs provided by FoundationEssentials

NSData options should typealias to Data options

---

Darwin/Foundation-swiftoverlay-Tests/TestTimeZone.swift
Tests/Foundation/Tests/TestCalendar.swift
Tests/Foundation/Tests/TestNSCalendar.swift
Tests/Foundation/Tests/TestTimeZone.swift

Linux distros that have picked up newer copies of the `tzdata` database have dropped some of the timezones tested in corelibs-foundation. Removing them, or replacing with the equivalent timezone replacement, according to the contents of `/usr/share/zoneinfo` on Ubuntu 23.10.
Removed timezones include:
- Israel               -> Asia/Jerusalem
- US/Pacific      -> America/Los_Angeles
- Brazil/East     -> America/Sao_Paulo
- Europe/Kiev     -> Europe/Kyiv

[5.10] Removing checks for deleted timezones

---

Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSURL.swift
Tests/Foundation/TestFileManager.swift
Tests/Foundation/TestNSData.swift

This PR removes more FileManager code that is duplicated from swift-foundation. It removes a handful of functions that are no longer necessary, removes the private `._userImmutable` file attribute since it is the same as the API `.immutable` attribute, and updates the private file attribute fetching/setting functions to call down to the public API functions to handle all API attributes instead of duplicating code for the API attributes.
All tests pass locally on linux with this change

Remove additional unnecessary FileManager code

---

Sources/FoundationNetworking/DataURLProtocol.swift
Sources/FoundationNetworking/URLSession/FTP/FTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Sources/FoundationNetworking/URLSession/TaskRegistry.swift
Sources/FoundationNetworking/URLSession/URLSession.swift
Sources/FoundationNetworking/URLSession/URLSessionDelegate.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

Cherry-pick of #4970 for `release/6.0`

[6.0] Add async URLSession methods

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

Because the test server sends a close message shortly after sending a pong, the connection might close before our task handles the pong and calls its completion handler. In this case, the pong completion handler is never called, so `try await task.sendPing()` hangs indefinitely.
This PR cleans up `pongCompletionHandlers` on error/close and minimally fixes the test to allow the case where the server closes the connection before the pong is handled.

Fix test_webSocket hang

---

Sources/Foundation/NSData.swift

This fixes https://github.com/swiftwasm/swift/issues/5584.
This PR does not affect platforms other than WASI.

[wasm] Do not set permissions in `Data.write`

---

Sources/CoreFoundation/CFSocket.c
Sources/Foundation/NSData.swift
Sources/FoundationNetworking/DataURLProtocol.swift
Sources/FoundationNetworking/URLSession/FTP/FTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Sources/FoundationNetworking/URLSession/TaskRegistry.swift
Sources/FoundationNetworking/URLSession/URLSession.swift
Sources/FoundationNetworking/URLSession/URLSessionDelegate.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Sources/FoundationNetworking/URLSession/libcurl/MultiHandle.swift
Sources/_CFURLSessionInterface/CFURLSessionInterface.c
Sources/_CFURLSessionInterface/include/CFURLSessionInterface.h
Tests/Foundation/HTTPServer.swift
Tests/Foundation/TestSocketPort.swift
Tests/Foundation/TestURLSession.swift

Incorporate latest updates from `main` into `package`.

Merge the main branch into package

---

Sources/Foundation/Bundle.swift

Cherry-pick of https://github.com/apple/swift-corelibs-foundation/pull/4963 for Swift 6.

[Swift 6.0] Mark Bundle as Sendable

---

Sources/CoreFoundation/internalInclude/CoreFoundation_Prefix.h

This fixes a Windows build failure I encountered when building a Windows toolchain with this branch. We use `CF_EXPORT` within a windows-only code path of `CoreFoundation_Prefix.h` and `CF_EXPORT` is defined in `CFBase.h`. `CFBase.h` is included from this file on the `main` branch, so this PR restores that include which should correct this build failure.
The project still builds successfully for linux with this change

Include CFBase.h in CoreFoundation_Prefix.h

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/Tests/TestURLSession.swift

Cherry-pick of #4973 for `release/5.10` to unblock 5.10 toolchain build on Fedora40

[5.10] Fix test_webSocket hang

---

Package.swift

This is the same as https://github.com/apple/swift-foundation/pull/694, but for SCL-F. This adds a mode that will allow a full toolchain build to use SwiftPM to build all of Foundation but using the locally checked out versions rather than fetching from GitHub

Add SWIFTCI_USE_LOCAL_DEPS build mode

---

Sources/CoreFoundation/CMakeLists.txt

This copies the public headers to a known location in the build tree so that direct clients (before installation) can specify that directory as an include path when not building via a CMake dependency

[CMake] Copy headers to known directory for direct client test builds

---

CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

We should use build IDs on Linux so that we can identify the built artefacts, and also so that we can match them up with debug information should we choose to separate it.
rdar://130582768

[Linux] Enable build-ids.

---

CMakeLists.txt
Sources/CoreFoundation/include/CFRunLoop.h
Sources/CoreFoundation/include/CFString.h
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/CoreFoundation/include/module.modulemap
Sources/CoreFoundation/internalInclude/CFInternal.h
Sources/Foundation/FileManager+Win32.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/NSUUID.swift

This updates SCL-F to make it build on Windows successfully for inclusion in the Windows toolchain

[CMake] Fix Windows Build

---

CMakeLists.txt

The GNUInstallDirs module sets `CMAKE_INSTALL_BINDIR` which is used on Windows as the destination for installed `.dll` files. This addresses issues that I saw when building a Windows toolchain where the `.dll` files were not installed into the toolchain previously, but with this change are correctly installed into the bin directory.

[CMake] Include GNUInstallDirs

---

Sources/Foundation/Process.swift

Within `Process`, the `launchPath` here is equivalent to `executableURL.path`. Just before launching the process, we call `.withCString(encodedAs: UTF16.self)` to convert the invocation to UTF-16. However, now that `URL` is re-cored on swift-foundation's `URL`, Windows paths are represented following RFC8089 which contains a leading `/` before a drive letter. The various file system representation functions remove this preceding slash before calling to an SDK API, however `Process` did not do this resulting in a path such as `/C:/Users/jmschonfeld/foo.exe` being passed to `CreateProcessW` which failed to find the file. This standardizes the path to its file system representation before it is combined with the various arguments and converted to UTF-16 later.
This fixes a failure that …

Use FSR for Process executable path on Windows

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationNetworking/HTTPCookieStorage.swift
Sources/FoundationNetworking/URLSession/BodySource.swift
Sources/FoundationNetworking/URLSession/FTP/FTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPMessage.swift
Sources/FoundationNetworking/URLSession/HTTP/HTTPURLProtocol.swift
Sources/FoundationNetworking/URLSession/NativeProtocol.swift
Sources/FoundationNetworking/URLSession/TaskRegistry.swift
Sources/FoundationNetworking/URLSession/TransferState.swift
Sources/FoundationNetworking/URLSession/URLSession.swift
Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Sources/FoundationNetworking/URLSession/URLSessionTaskMetrics.swift
Sources/FoundationNetworking/URLSession/WebSocket/WebSocketURLProtocol.swift
Sources/FoundationNetworking/URLSession/libcurl/EasyHandle.swift
Sources/FoundationNetworking/URLSession/libcurl/MultiHandle.swift
Sources/FoundationNetworking/URLSession/libcurl/libcurlHelpers.swift
Sources/FoundationXML/CMakeLists.txt
Sources/FoundationXML/XMLDTD.swift
Sources/FoundationXML/XMLDTDNode.swift
Sources/FoundationXML/XMLDocument.swift
Sources/FoundationXML/XMLElement.swift
Sources/FoundationXML/XMLNode.swift
Sources/FoundationXML/XMLParser.swift
Sources/_CFURLSessionInterface/CMakeLists.txt
Sources/_CFXMLInterface/CMakeLists.txt

CoreFoundation expects to only be linked from Foundation itself. This resulted in linker failures where CoreFoundation failed to find certain symbols provided by Foundation when it was statically linked into FoundationNetworking on Windows. This removes CoreFoundation from the linked libraries list of FoundationNetworking/FoundationXML, but does add CoreFoundation's include paths to those targets so that it can use headers that have macros defined.

Avoiding linking CF from outside of Foundation

---

CMakeLists.txt

This resolves a warning encountered on windows by ensuring that we pass `/clang:-fcf-runtime-abi=swift` on windows instead of accidentally dropping the `/clang:` part which restores the behavior present on the `main` branch.

[CMake] correctly apply -fcf-runtime-abi=swift on Windows

---

Sources/Foundation/NSURL.swift

As the `String.withCString` function provides utf-8 encoded content, we should not use `String.count` for receiving buffer length. `NSURL.fileSystemRepresentation` is used in `FileHandle(forReadingFrom:)`, and it fails with file urls containing non-ascii (e.g. cyrillic) characters.

Allocate buffer of correct size in `NSURL.fileSystemRepresentation` on Windows

---

Sources/Foundation/Port.swift

We have been running into modularization issues on newer versions of various Linux distros, resulting in the compiler saying that the Glibc module doesn't have a SOCK_STREAM or SOCK_DGRAM. From some poking around, the definition is now coming from the CoreFoundation module as far as Swift is concerned. This is ultimately because our modulemap for Glibc is bad, but also means that I can't bring up Swift 6 on all of the Linux distros that 5.10 has support for.
This workaround removes the explicit module name from `SOCK_STREAM` and renames it to `FOUNDATION_SOCK_STREAM` to avoid an ambiguous name, and completely removes `SOCK_DGRAM`.
Both SOCK_STREAM and SOCK_DGRAM are fileprivates, so changing them will have no visible external effect. It is true that if another header somewhere defines …

[Swift-6.0] Workaround broken glibc modulemap

---

Sources/CoreFoundation/include/ForSwiftFoundationOnly.h

Amazon Linux, at least, and probably others, requires the `fcntl.h` include to use the various constants in `statx`.

Add fcntl.h include, required for some linux platforms

---

CMakeLists.txt
Package.swift
Sources/Foundation/NSStringAPI.swift
Tests/Foundation/TestDataURLProtocol.swift

This removes some String APIs in SCL-F in favor of those in swift-foundation and removes some `!DEPLOYMENT_RUNTIME_SWIFT` paths that are no longer relevant in this project. This depends on https://github.com/apple/swift-foundation/pull/739, so I'll update the commit hash in the package manifest and cmake files once that is merged before merging this

Re-core some String APIs on swift-foundation

---

Sources/FoundationNetworking/URLSession/URLSession.swift

We've seen various crashes in `libcrypto` that occur following `URLSession._MultiHandle.deinit`. The crash was particularly frequent on Amazon Linux 2 (see https://github.com/swiftlang/swift-package-manager/pull/7624), and generally follows a similar pattern to this backtrace:
```
0      0x0000ffffa4e4b948 getrn + 136 in libcrypto.so.1.0.2k
1 [ra] 0x0000ffffa4e4bddc lh_delete + 55 in libcrypto.so.1.0.2k
2 [ra] 0x0000ffffa4e4eaac int_thread_del_item + 123 in libcrypto.so.1.0.2k
3 [ra] 0x0000ffffa4e4f564 ERR_error_string + 151 in libcrypto.so.1.0.2k
4 [ra] 0x0000ffffa5316d68 Curl_close + 135 in libcurl.so.4.8.0
5 [ra] 0x0000ffffa52c2374 Curl_conncache_close_all_connections + 371 in libcurl.so.4.8.0
6 [ra] 0x0000ffffa52f8884 curl_multi_cleanup + 215 in libcurl.so.4.8.0
7 [ra] …
```

Use a shared queue for URLSessions to prevent crash during _MultiHandle.deinit

---

Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt
Sources/plutil/CMakeLists.txt

Just like https://github.com/apple/swift-foundation/pull/742, we need to make the same changes to the SCL-F modules. We retain the compiler-added rpaths for libraries in the build folder and now overwrite them with `$ORIGIN` when installing, and we also add a public auto link to `swiftSynchronization` to ensure that our libraries pull in `libswiftSynchronization.a` in the static swift SDK.

Enable importing the Synchronization module

---

Package.swift

This adds a `DISPATCH_INCLUDE_PATH` environment variable that allows specifying the location at which the package build can find dispatch headers. On linux/android this path still defaults to `/usr/lib/swift`. This will allow us to build the tests of this package via SwiftPM in the toolchain build where we build against a just-built toolchain (and `/usr/lib/swift` doesn't exist).

Allow custom dispatch include path in SwiftPM package build

---

Package.swift
Tests/Foundation/TestDataURLProtocol.swift

Now that swift-foundation has support for `isoLatin1` and `macOSRoman`, we can enable this piece of the test that relied on those encodings.

Re-enable tests requiring isoLatin1/macOSRoman

---

CMakeLists.txt
Sources/CoreFoundation/CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/_CFURLSessionInterface/CMakeLists.txt
Sources/_CFXMLInterface/CMakeLists.txt

This updates our CMake files to make it possible to build this project locally via CMake without building the entire toolchain. This required 2 main changes:
1. When `dispatch_DIR` is not provided, find dispatch headers from the SDK (looking at `DISPATCH_INCLUDE_PATH` and falling back to `/usr/lib/swift` for linux). This mirrors how the SwiftPM build finds dispatch.
2. Explicitly provide paths to the clang module map files so that the compiler does not encounter ambiguity when the module also exists in the SDK. This mirrors what SwiftPM does today.

Fix local CMake build

---

CMakeLists.txt
Sources/CoreFoundation/CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/_CFURLSessionInterface/CMakeLists.txt
Sources/_CFXMLInterface/CMakeLists.txt

Explanation: Allows building the project via CMake outside of the toolchain
Scope: Should only resolve an issue in local, non-toolchain CMake builds
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5032
Risk: Minimal - minor change to CMake that has been tested
Testing: Testing done via swift-ci toolchain builds and local, standalone CMake builds
Reviewer: @iCharlesHu

[6.0] Fix local CMake build

---

Package.swift

Cherry pick for release/6 of https://github.com/apple/swift-corelibs-foundation/pull/5025

[6.0] Allow custom include path for Dispatch

---

CMakeLists.txt
Package.swift

When building this package via SwiftPM on Windows, we need to include dispatch headers from the appropriate directory in the SDK. We cannot rely on an absolute path such as `/usr/lib/swift` on linux, so instead we use a reasonable default based on the SDKROOT environment variable. I believe this environment variable should be set automatically in a VS developer shell with Swift installed to point to the `Windows.sdk` directory within the currently active swift installation. This allows us to find dispatch in many cases and get closer to a working package build on Windows (while still allowing manual overriding via the `DISPATCH_INCLUDE_PATH` environment variable)

[Windows] Add default dispatch header search path to standalone builds

---

Tests/Foundation/TestDateFormatter.swift
Tests/Foundation/TestTimeZone.swift

These tests are failing on amazon linux with:
```
Test Case 'TestDateFormatter.test_setTimeZoneToNil' started at 2024-07-30 02:30:52.313
TestFoundation/TestDateFormatter.swift:337: error: TestDateFormatter.test_setTimeZoneToNil : XCTAssertEqual failed: ("Optional(GMT)") is not equal to ("Optional(Etc/UTC)") - 
TestFoundation/TestDateFormatter.swift:340: error: TestDateFormatter.test_setTimeZoneToNil : XCTAssertEqual failed: ("Optional(GMT)") is not equal to ("Optional(Etc/UTC)") - 
Test Case 'TestDateFormatter.test_setTimeZoneToNil' failed (0.0 seconds)
Test Case 'TestTimeZone.test_systemTimeZoneUsesSystemTime' started at 2024-07-30 02:30:03.140
TestFoundation/TestTimeZone.swift:167: error: TestTimeZone.test_systemTimeZoneUsesSystemTime : XCTAssertEqual failed: ("GMT") is not equal to …
```

Disable tests failing on amazon linux

---

Sources/Foundation/Process.swift

Do not re-add sources to the run loop for each call to `setup`. Regression from #5000.

Make sure that the once used for Process is static

---

Sources/FoundationNetworking/URLSession/URLSessionTask.swift
Tests/Foundation/TestURLSession.swift

Completion-based [send](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask/3281790-send) and [receive](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask/3281789-receive) are public in Apple Foundation.
Perhaps, availability should be added to the containing type, but I added it here for consistency with async counterparts.

Make completion-based send/receive functions public in `URLSessionWebSocketTask`

---

Sources/Foundation/Process.swift

[6.0] Make sure that the once used for Process is static

---

Sources/CoreFoundation/CMakeLists.txt

The CoreFoundation target had a hard-coded module install path of `lib/swift/CoreFoundation`, instead of conditionalizing it for the static build (which goes to `lib/swift_static`). While we don't expect clients to use `CoreFoundation` directly (and they shouldn't), this restores the module to unbreak existing clients that are doing this.
This resolves https://github.com/apple/swift-http-types/issues/61

Fix CoreFoundation module install path for static build

---

CMakeLists.txt
Package.swift

Explanation: Allows building the standalone project on Windows without pre-building corelibs-libdispatch
Scope: Should only modify standalone, local builds on Windows
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5033
Risk: Minimal - minor change to CMake/package manifest that only affects local, standalone builds
Testing: Testing done via swift-ci toolchain builds and local, standalone CMake/SwiftPM builds
Reviewer: @iCharlesHu

[6.0] Fix SwiftPM build dispatch include path on Windows

---

Sources/CoreFoundation/CMakeLists.txt

Explanation: Re-adds the CoreFoundation module to the static swift SDK
Scope: Should only change the static swift build and fixes a regression
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5037
Risk: Minimal - minor change to fix a regression that should effectively be additive
Testing: Testing done via swift-ci toolchain builds and local, standalone CMake builds
Reviewer: @iCharlesHu

[6.0] Fix CoreFoundation install path

---

Sources/Foundation/NSNumber.swift

In https://github.com/apple/swift-foundation/pull/756 we transitioned the `FoundationEssentials` --> `FoundationInternationalization` upcalls from `_typeByName` to `@_dynamicReplacement` functions to avoid accidentally looking up types from the toolchain in local builds. In that PR, I also added a `dynamic` function for `Foundation` to override for its `NSNumber` initializer. This PR implements that dynamic replacement so that we can remove the final `_typeByName` lookup in `FoundationEssentials`

Update to use dynamic replacement for _NSNumberInitializer

---

Sources/Foundation/NSNumber.swift

Explanation: Removes a `_typeByName` lookup in a FoundationEssentials up-call that can result in confusion between the toolchain and local builds
Scope: Should only impact up-calls from `FileManager` in `FoundationEssentials` to initialize `NSNumber`s
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5045
Risk: Low - small in scope and covered by unit tests
Testing: Testing done via swift-ci testing
Reviewer: @parkera

[6.0] Update to use dynamic replacement for _NSNumberInitializer

---

Tests/Foundation/TestURLSession.swift

`TestURLSession.test_connectTimeout` was failing on Ubuntu 22.04 CI and I also reproduced the failure on Amazon Linux 2. It generally only fails when all `TestURLSession` cases are run together, and I think it's related to stopping and starting the server during the test. Disable it for now while we figure out another way to test this specific connect timeout (a similar request timeout is still being tested by the test case above).

Disable test_connectTimeout for flakiness on Linux

---

.gitignore

These files are created by SourceKit-LSP when background indexing is enabled.

NFC: Add `.index-build` to `.gitignore`

---

Package.swift
Sources/FoundationNetworking/URLSession/NetworkingSpecific.swift
Tests/Foundation/TestURL.swift

This implements the hook added in https://github.com/apple/swift-foundation/pull/820 to support reading from a remote URL, and also adds a unit test to verify the behavior is functional.

Implement hook for data reading from remote URL

---

Package.swift

This patch allows SWIFTCI_USE_LOCAL_DEPS to be either `1` (use `..`) or a string to be prepended to the path.
It also moves from the deprecated `swiftLanguageVersion` to `swiftLanguageMode`.
Both of these are required to work with [this benchmarking update in swift-foundation](https://github.com/apple/swift-foundation/pull/810).

Allow for more flexibility in what path SWIFTCI_USE_LOCAL_DEPS means

---

Package.swift
Sources/FoundationNetworking/URLSession/NetworkingSpecific.swift
Tests/Foundation/TestURL.swift

Explanation: Implements the hook defined in https://github.com/apple/swift-foundation/pull/826 to allow for `Data(contentsOf:)` to fetch from a remote URL when FoundationNetworking is loaded
Scope: Should only impact calling Data(contentsOf:) with a non-file URL, turning an error into non-regressed behavior
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5049
Risk: Minimal - fixes a regression where the current behavior is just to throw, and fairly limited scope
Testing: Testing done via swift-ci testing and local testing
Reviewer: @iCharlesHu @parkera

[6.0] Implement Data reading hook for remote content

---

CMakeLists.txt

This enables whole module optimization for Foundation, FoundationNetworking, and FoundationXML for release builds. We've found that this added optimization results in a significant performance improvements for FoundationEssentials (https://github.com/apple/swift-foundation/pull/832) and will be applying the same optimization to the SCL-F suite of libraries

Enable WMO for release builds

---

Tests/Foundation/TestURLSession.swift

Cherry picked from https://github.com/apple/swift-corelibs-foundation/pull/5046
Explanation: Disable flaky test on Linux while we investigate a more robust way to test connection timeout
Scope: Disables one TestURLSession test case
Risk: Minimal
Testing: swift-ci and local package testing on Ubuntu 22.04 and Amazon Linux 2
Reviewer: @parkera

[6.0] Disable test_connectTimeout

---

CMakeLists.txt

Explanation: Enables WMO in release builds
Scope: Should only impacts release builds for non-Windows
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5059
Risk: Minimal - enables WMO as a performance optimization, behavior should not change
Testing: Testing done via swift-ci testing and local testing
Reviewer: @glessard

[6.0] Enable WMO for release builds

---

Sources/XCTest/Public/XCTestMain.swift

The option `--list-test` is incorrect. The correct option is [`--list-tests`](https://github.com/apple/swift-corelibs-foundation/blob/9c8bac47f032a431dde757112591e3dd60dba461/Sources/XCTest/Private/ArgumentParser.swift#L60).
This is the same as https://github.com/apple/swift-corelibs-xctest/pull/499.

Fix incorrect help documentation of XCTestMain

---

Sources/Foundation/NSPathUtilities.swift

As we have fixed the conflict in the WASILibc overlay module while porting swift-foundation, we can remove the workaround from corelibs-foundation too.

Remove the workaround for WASI errno conflict

---

Sources/Foundation/NSError.swift

This more closely matches Darwin behavior, and makes it significantly easier to debug issues like "File was not found" which presently include no reference whatsoever to the actual file path.

Include userInfo in Error descriptions

---

CMakeLists.txt
Sources/Foundation/Port.swift
cmake/modules/FindLibRT.cmake

Putting back definitions and flags that were dropped when doing the Swift-Foundation re-core that are necessary when building for the static SDK. This is primarily checks for symbol availability.

Fixing post-swift-foundation corelibs-foundation static SDK builds

---

CMakeLists.txt
Sources/Foundation/Port.swift
cmake/modules/FindLibRT.cmake

Putting back definitions and flags that were dropped when doing the Swift-Foundation re-core that are necessary when building for the static SDK. This is primarily checks for symbol availability.
This will not affect SwiftPM builds, which will continue to define `strlcpy` and `strlcat` everywhere, even on systems that define them in the libc, resulting in build failures. The CMake build will work in these environments.
6.0: https://github.com/apple/swift-corelibs-foundation/pull/5060

[main] Fixing post-swift-foundation corelibs-foundation MUSL static SDK builds

---

Package.swift
Sources/CoreFoundation/CFRuntime.c
Sources/_CFURLSessionInterface/CFURLSessionInterface.c
Tests/Foundation/TestBundle.swift
Tests/Foundation/TestFileManager.swift
Tests/Foundation/TestHTTPCookieStorage.swift
Tests/Foundation/TestProcess.swift

We currently run unit tests via SwiftPM on linux, but have not yet enabled this on Windows due to the Windows build failing. This is a large step forward towards getting the Windows build working via SwiftPM as it resolves a few main issues:
1. Dependencies like libxml2 and curl (which depends on zlib) are found via `pkgconfig` on Linux, however the same functionality does not exist on Windows operating systems. Additionally, we cannot find these libraries in the toolchain like Dispatch because, unlike libdispatch, curl/libxml2 are not distributed in the toolchain (they only exist as static libraries linked into FoundationNetworking/FoundationXML respectively. Instead, on windows we require that the header include and library search paths are provided via environment variables. While this …

Repair the Windows SwiftPM build

---

Package.swift
Sources/Foundation/NSPathUtilities.swift
Tests/Foundation/TestBundle.swift
Tests/Foundation/TestFileManager.swift
Tests/Foundation/TestNSString.swift
Tests/Foundation/TestProcess.swift
Tests/Foundation/TestProcessInfo.swift
Tests/Foundation/TestThread.swift
Tests/Foundation/TestURL.swift
Tests/Foundation/TestURLSession.swift

This addresses some test failures where the tests need to be updated for the re-core on Windows. In some cases, the underlying code was changed and the test should be updated to reflect the new and/or correct behavior - in other cases the tests may have been lucky before but are incorrect and need to be changed or removed.

Fix up tests for Windows

---

Package.swift
Sources/Testing/Testing.swift

Now that swift-testing is present in the toolchain, SwiftPM builds of the test target in this package will automatically import `Testing`, causing our test target to link the `Testing` library in the toolchain. This is problematic, because the `Testing` module links Foundation (from the toolchain) which results in a variety of issues and crashes when running our tests caused by the presence of two Foundations (classes of the same name are indistinguishable and one implementation is nondeterministically picked leading to failures when bridging). To resolve this, we will use the same solution we found for XCTest - to vendor a small copy of the library within our project that will be picked up instead of the toolchain version. In our case, we only need a small stub because we don't actually …

Add stub for Testing module

---

CMakeLists.txt
Package.swift
Sources/CoreFoundation/CFBundle.c
Sources/CoreFoundation/CFString.c

Cherry picked from https://github.com/apple/swift-corelibs-foundation/pull/5052
**Explanation**: these patches restore support for WASI that was available in `swift-corelibs-foundation` before it was recored.
**Scope**: Isolated to WASI codepaths.
**Risk**: Low due to isolated scope.
**Testing**: Tested manually for WASI, on CI with the existing test suite for other platforms.
**Issue**: rdar://133231577
**Reviewer**: @kateinoigakukun, @jmschonfeld

[6.0] build: Repair the build on WASI platform

---

Tests/Foundation/TestDate.swift

`isLeapMonth` is a component in `Date`. Add one more XCTAssert for `isLeapMonth` in `test_recreateDateComponentsFromDate`.

Add one more XCTAssert for isLeapMonth in TestDate.swift

---

Sources/CoreFoundation/include/ForFoundationOnly.h

`__CFAllocatorRespectsHintZeroWhenAllocating` has two declarations in different headers: `ForFoundationOnly.h` and `ForSwiftFoundationOnly.h`. One of the declarations was under `extern "C"` block, the other one wasn't. Clang accepts this in C language mode, but it is a hard compiler error in C++ language mode due to a linkage mismatch.
This was blocking clients from using CoreFoundation in Swift projects that enable C++ interoperability.
This change makes sure that both declarations of `__CFAllocatorRespectsHintZeroWhenAllocating` are under `extern "C"` blocks.

Fix compiler error in CoreFoundation when building in C++ mode

---

Tests/Foundation/TestXMLDocument.swift

Use the `XCTAssertEqual` check for the equality over an inline equal check. This allows the message to describe both sides of the comparison and helps identify the issue more easily.

Tests: prefer `XCTAssertEqual` over `XCTAssertTrue`

---

Sources/FoundationXML/XMLParser.swift
Tests/Foundation/TestXMLParser.swift

Instead of thread-local storage, use `TaskLocal` to store the current
parser. This solves three issues:
1. If someone calls `XMLParser.parse()` with a new parser instance in
a delegate method call, it overwrote the current parser and wrote
it back after the call as `nil`, not the previous current parser.
This reentrancy issue can be a problem especially when someone uses
external entity resolving since the feature depends on the current
parser tracking. Using `TaskLocal` solves this issue since it tracks
values as a stack and restores the previous value at the end of the
`withValue` call.
2. Since jobs of different tasks can be scheduled on the same thread,
different tasks can refer to the same thread-local storage. This
wouldn't be a problem for now since the `parse()` method doesn't …

[XMLParser] Fix reentrancy issue around `currentParser`

---

Package.swift
Sources/Testing/Testing.swift

Explanation: A test-only change that repairs our SwiftPM test build so that we can run tests on the release/6.0 branch (we only expect to be able to run tests locally on linux on this branch, but this allows us to continue doing so)
Scope: Only impacts building for testing via SwiftPM
Original PR: https://github.com/apple/swift-corelibs-foundation/pull/5077
Risk: Minimal - this only impacts testing and will have no impact on the normal build
Testing: Testing done via local testing and testing in swift-ci
Reviewer: @compnerd @itingliu

[6.0] Add stub for Testing module

---

CMakeLists.txt
Sources/CoreFoundation/CMakeLists.txt
Sources/_CFXMLInterface/CMakeLists.txt

CMake recently introduced a new variable `WASI` to check if the target platform is WASI (https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9659). However, the change led to `WASI` being expanded as a variable, which is not what we want in checking the platform name.
To have compatibility with older and newer versions of CMake, we should quote the string `WASI` to prevent it from being expanded as a variable.

CMake: Fix accidental variable expansion of `WASI`

---

Sources/CoreFoundation/CFPlatform.c
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/Foundation/Process.swift

posix_spawn_file_actions_addchdir_np is the official way to set the working directory of a spawned process and is supported on both macOS and glibc (Linux, etc.). This makes Process.currentDirectoryURL thread-safe, as the current approach will result in the working directory being nondeterministically assigned when spawning processes across multiple threads, using different working directories.

Add a thread-safe implementation of Process.currentDirectoryURL

---

Sources/Foundation/Process.swift

Swift still needs to support Amazon Linux 2 until it EoLs in mid-2025. So restore the thread-unsafe fallback for systems with glibc older than version 2.29, which was removed in #4981.

Restore thread-unsafe fallback for setting the Process working directory

---

Sources/Foundation/FileManager.swift

When attempting to save a document multiple times the closing bracket was missing in the printed message   
This fixes [Issue 953](https://github.com/swiftlang/swift-foundation/issues/953)
(had some time at my hands bc am waiting for login credentials from my workplace)

Update FileManager.swift to include bracket in save message

---

CMakeLists.txt
Sources/CoreFoundation/CFPlatform.c
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

We need a handful more autolink arguments; these were in a previous PR, but seem to have gone missing at some point during the re-core.
Additionally, Musl has the `posix_spawn_file_actions_addchdir_np()` function rather than the non-`_np()` version.
Fixes #5089.

[Musl] Add missing autolink arguments, fix CFPosixSpawnFileActionsChdir.

---

Sources/CoreFoundation/CFPlatform.c
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/Foundation/Process.swift

posix_spawn_file_actions_addchdir_np is the official way to set the working directory of a spawned process and is supported on both macOS and glibc (Linux, etc.). This makes Process.currentDirectoryURL thread-safe, as the current approach will result in the working directory being nondeterministically assigned when spawning processes across multiple threads, using different working directories.
---
This already landed in main via #4981 (and amendment in #5090) and it's pretty disruptive for us so I'd like to get it into 6.0.2 if possible.

[6.0.2] Add a thread-safe implementation of Process.currentDirectoryURL

---

Sources/_CFXMLInterface/CMakeLists.txt

The include path for libxml2 should be being set automatically by CMake because of the `target_link_libraries()` call; there is no need to add it explicitly.
rdar://137567628

[CFXMLInterface] Remove spurious include path.

---

Sources/FoundationNetworking/URLSession/HTTP/HTTPMessage.swift
Tests/Foundation/TestURLProtectionSpace.swift

Without the fix:
```
swift test --filter TestURLProtectionSpace.test_createWithInvalidAuth
Test Suite 'Selected tests' started at 2024-10-11 21:04:24.085
Test Suite 'TestURLProtectionSpace' started at 2024-10-11 21:04:24.095
Test Case 'TestURLProtectionSpace.test_createWithInvalidAuth' started at 2024-10-11 21:04:24.095
Swift/StringIndexValidation.swift:143: Fatal error: Substring index is out of bounds
^C*** Signal 5: Backtracing from 0xffff95642744... failed ***
```
With the fix:
```
Test Suite 'Selected tests' started at 2024-10-11 21:19:30.602
Test Suite 'TestURLProtectionSpace' started at 2024-10-11 21:19:30.612
Test Case 'TestURLProtectionSpace.test_createWithInvalidAuth' started at 2024-10-11 21:19:30.612
Test Case 'TestURLProtectionSpace.test_createWithInvalidAuth' passed (0.005 …
```

Fix bounds checking error when parsing WWW-Authenticate field

---

Sources/Foundation/CharacterSet.swift
Sources/Foundation/NSCFCharacterSet.swift

`CharacterSet` was the one remaining type in swift-corelibs-foundation using a wrapper type to handle moving between immutable/mutable and handling uniqueness checks. By removing the wrapper and simplifying the usage, we can also remove the leak from mismanaging an "Unmanaged" CF type reference.
rdar://137806932

Fix a leak when mutating CharacterSet by moving away from _SwiftNSCharacterSet wrapper

---

Sources/Foundation/NSError.swift
Tests/Foundation/TestNSError.swift

This PR addresses an infinite loop issue that occurred when force casting `NSError` to `CocoaError`. The problem arose because `_forceBridgeFromObjectiveC` was calling `_unconditionallyBridgeFromObjectiveC`, and in turn, `_unconditionallyBridgeFromObjectiveC` was calling `_forceBridgeFromObjectiveC`, causing a recursive loop.

Fix infinite loop when force casting NSError to CocoaError

---

Sources/CoreFoundation/CFBigNumber.c
Sources/CoreFoundation/CFFileUtilities.c
Sources/CoreFoundation/CFLocale.c
Sources/CoreFoundation/CFLocaleIdentifier.c
Sources/CoreFoundation/CFPlatform.c
Sources/CoreFoundation/CFSocketStream.c
Sources/CoreFoundation/CFString.c
Sources/CoreFoundation/CFStringEncodings.c
Sources/CoreFoundation/CFSystemDirectories.c
Sources/CoreFoundation/CFURL.c
Sources/CoreFoundation/internalInclude/CoreFoundation_Prefix.h

These can _use_ `strlcpy` and `strlcat` if we have them, but we mustn't go defining `strlcpy` or `strlcat` because (a) those names are reserved, and (b) doing so without explicitly testing for their presence runs the risk of build failures from trying to define them when they already exist.
rdar://137567627

[CoreFoundation] Replace use of strlcpy/strlcat with our own functions.

---

Sources/Foundation/NSError.swift
Tests/Foundation/TestNSError.swift

Cherry-picked from #5115 for 6.0
(cherry picked from commit bf7369a3909583c82f36b901917a92ea0d639a9f)

Fixed an infinite loop caused by force casting NSError to CocoaError

---

Sources/Foundation/NSCharacterSet.swift

(follow up to #5107) cherry-picked from #5118 for Swift 6.0.2
rdar://138005684
(cherry picked from commit 592f015760cc760b2298ee29d3639969b480d044)

Ensure that NSCharacterSet always returns an NSObject on copy

---

Sources/Foundation/NSCharacterSet.swift

(follow up to #5107), cherry-picked from #5118 for Swift 6.0
rdar://138005684
(cherry picked from commit 592f015760cc760b2298ee29d3639969b480d044)

Ensure that NSCharacterSet always returns an NSObject on copy 

---

Sources/CoreFoundation/CFPlatform.c
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/Foundation/Process.swift

posix_spawn_file_actions_addchdir_np is the official way to set the working directory of a spawned process and is supported on both macOS and glibc (Linux, etc.). This makes Process.currentDirectoryURL thread-safe, as the current approach will result in the working directory being nondeterministically assigned when spawning processes across multiple threads, using different working directories.
This already landed in main via https://github.com/swiftlang/swift-corelibs-foundation/pull/4981 (and amendment in https://github.com/swiftlang/swift-corelibs-foundation/pull/5090) and it's pretty disruptive for us so I'd like to get it into 6.0.x if possible.

[6.0.x] Add a thread-safe implementation of Process.currentDirectoryURL

---

Sources/CoreFoundation/CFBase.c
Sources/CoreFoundation/include/ForFoundationOnly.h
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/CoreFoundation/internalInclude/CFInternal.h

Move __CFAllocatorRespectsHintZeroWhenAllocating to a CF-internal header to avoid confusion over its linkage. Resolves #5125

Move __CFAllocatorRespectsHintZeroWhenAllocating

---

Tests/Foundation/TestFileManager.swift

`TestFileManager.test_emptyFilename` has been failing flakily on Windows with the following error:
```
TestFoundation/TestFileManager.swift:1361: error: TestFileManager.test_emptyFilename : XCTAssertEqual failed: ("Optional(FoundationEssentials.CocoaError.Code(rawValue: 512))") is not equal to ("Optional(FoundationEssentials.CocoaError.Code(rawValue: 4))")
```
This test itself does not create `/tmp` or `/tmp/t`, so it's suspected that another test might be creating one of these (or perhaps these files existed previously), changing the error thrown. This PR changes usage of `/tmp/t` to a unique, non-existent file name `/test_emptyFilename_nonExistent` instead.
Update: That did not fix the issue, so we're disabling the test while we continue to investigate.

Disable TestFileManager.test_emptyFilename on Windows

---

Sources/CoreFoundation/CFBase.c
Sources/CoreFoundation/include/ForFoundationOnly.h
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/CoreFoundation/internalInclude/CFInternal.h

Move __CFAllocatorRespectsHintZeroWhenAllocating to a CF-internal header to avoid confusion over its linkage. Resolves #5125 (cherry picked from #5126 for 6.x).
(cherry picked from commit b1b460325cd4b2932220356a1a50ef64fc947bc1)

Move __CFAllocatorRespectsHintZeroWhenAllocating (6.0)

---

Sources/Foundation/DateComponents.swift
Sources/Foundation/Notification.swift

This PR updates fatalError messages in the bridging methods of DateComponents and Notification to maintain a consistent message format across similar methods.
These changes enhance debugging clarity and ensure a uniform error message format throughout the codebase. Although these fatalError statements are not expected to be executed in practice, having consistent and clear error messages helps maintain code readability and aids potential debugging.

Align fatalError messages in Objective-C bridging methods for consistency

---

Sources/FoundationNetworking/URLSession/WebSocket/WebSocketURLProtocol.swift
Tests/Foundation/TestURLSession.swift

The previous code expected all `URLSessionWebSocketTask` to have a delegate, so using a WebSocket task from `URLSession.shared` caused a `fatalError`. This PR updates that expectation so that having a delegate is not enforced.
Resolves #4730

Fix crash when using WebSockets with URLSession.shared

---

Sources/FoundationNetworking/URLSession/WebSocket/WebSocketURLProtocol.swift
Tests/Foundation/TestURLSession.swift

**Explanation:** Prevents a `fatalError` when using a `URLSessionWebSocketTask` from `URLSession.shared`.
**Scope:** Only impacts `URLSessionWebSocketTask`.
**Original PR:** #5128 
**Risk:** Low - Small change to not `fatalError` in a supported config.
**Testing:** Added unit test, local testing with websocket-enabled curl, swift-ci
**Reviewer:** @parkera 
Resolves #4730 for `release/6.0`

[6.0.x] Fix crash when using WebSockets with URLSession.shared

---

Sources/Foundation/NSError.swift

Optimized `CustomNSError.errorDomain` calculation.
`String(reflecting:)` for `Any.Type` objects eventually calls `_type(:qualified:)`. But `String(reflecting:)` call has overhead because of `as?` checks. 
All details are listed in [issue](https://github.com/swiftlang/swift-foundation/issues/1031).

Improve CustomNSError.errorDomain calculation

---

Sources/FoundationNetworking/URLResponse.swift
Tests/Foundation/TestHTTPURLResponse.swift
Tests/Foundation/TestURLResponse.swift

The property `suggestedFilename` is documented with:
>This method always returns a valid filename.
The default initializer `init(url:mimeType:expectedContentLength:textEncodingName:)` had a correct implementation, but the required `init?(coder:)` was unsafe.
This is the same PR as #2643 created in February 2020, but for the **main** branch.
This is the same PR as #2897 created in October 2020, but it was closed for being unreviewed for too long.

suggestedFilename always returns a valid filename

---

Sources/Foundation/FileManager+Win32.swift

On Darwin + Linux, the default error handler for `FileManager.enumerator(at:)` continues on error (and this is the documented behavior as well) however on Windows the default error handler stops enumeration at an error. This updates the Windows behavior to match the Darwin + Linux behavior.

[Windows] FileManager.enumerator(at:) default error handler should continue rather than exiting

---

Sources/Foundation/NSGeometry.swift

fix https://github.com/swiftlang/swift-corelibs-foundation/issues/3443

CGPoint, CGSize, CGRect Conforms Hashable

---

Sources/Foundation/FileManager+Win32.swift

- **Explanation**: Updates windows default behavior of `FileManager.enumerator(at:)` when continuing after an error to match that of Darwin + Linux
- **Scope**: Only affects this API on Windows
- **Issues**: https://github.com/swiftlang/swift-corelibs-foundation/issues/5135
- **Original PRs**: https://github.com/swiftlang/swift-corelibs-foundation/pull/5136
- **Risk**: Low, it's uncommon for enumeration to hit errors (main cause is paths exceeding max path length currently) and the scope is limited
- **Testing**: Tested via swift-ci testing and local testing
- **Reviewers**: @compnerd

[6.1] [Windows] FileManager.enumerator(at:) default error handler should continue rather than exiting

---

CMakeLists.txt
Sources/CoreFoundation/CFPlatform.c
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt

We need a handful more autolink arguments; these were in a previous PR, but seem to have gone missing at some point during the re-core.
Additionally, Musl has the `posix_spawn_file_actions_addchdir_np()` function rather than the non-`_np()` version.
Fixes #5089.
rdar://140914176

[Musl] Add back missing autolink arguments, fix CFPosixSpawnFileActionsChdir.

---

Tests/Foundation/TestFileManager.swift
Tests/Foundation/TestNSString.swift

This reverts the swift-corelibs-foundation unit tests to the previous expectations to match the behavior correction in https://github.com/swiftlang/swift-foundation/pull/1072

Home directory for non-existent user should not fall back to /var/empty or %ALLUSERSPROFILE%

---

Package.swift
Sources/CoreFoundation/CFPlatform.c

@jakepetroules, looks like you added that new C function, please take a look.

[android] Fix package manifest and one Bionic function's API version

---

Tests/Foundation/TestFileManager.swift
Tests/Foundation/TestNSString.swift

- **Explanation**: Updates unit tests to match the new behavior of https://github.com/swiftlang/swift-foundation/pull/1073
- **Scope**: Only impacts unit tests
- **Original PRs**: https://github.com/swiftlang/swift-corelibs-foundation/pull/5142
- **Risk**: Minimal - unit test only change
- **Testing**: swift-ci testing, local testing
- **Reviewers**: @kperryua @jrflat @compnerd

[6.1] Home directory for non-existent user should not fall back to /var/empty or %ALLUSERSPROFILE%

---

CMakeLists.txt
Sources/CoreFoundation/include/ForSwiftFoundationOnly.h
Sources/CoreFoundation/internalInclude/CoreFoundation_Prefix.h
Sources/Foundation/CGFloat.swift
Sources/Foundation/FileHandle.swift
Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/Host.swift
Sources/Foundation/NSData.swift
Sources/Foundation/NSError.swift
Sources/Foundation/NSLock.swift
Sources/Foundation/NSPathUtilities.swift
Sources/Foundation/NSPlatform.swift
Sources/Foundation/NSSwiftRuntime.swift
Sources/Foundation/NSURL.swift
Sources/Foundation/Port.swift
Sources/Foundation/Process.swift
Sources/Foundation/Thread.swift
Sources/FoundationNetworking/HTTPCookie.swift
Sources/plutil/main.swift
Sources/xdgTestHelper/main.swift
Tests/Foundation/FTPServer.swift
Tests/Foundation/HTTPServer.swift
Tests/Foundation/TestFileHandle.swift
Tests/Foundation/TestNSData.swift
Tests/Foundation/TestProcess.swift
Tests/Foundation/TestSocketPort.swift
Tests/Foundation/TestTimeZone.swift
Tests/Foundation/TestURL.swift

Requires https://github.com/apple/swift-foundation/pull/757

Add android support, that uses new swift-foundation for Android

---

Sources/CoreFoundation/CFPlatform.c
Sources/CoreFoundation/include/CoreFoundation.h
Sources/CoreFoundation/internalInclude/CFBundle_Internal.h
Sources/Foundation/FileManager+POSIX.swift
Sources/Foundation/FileManager.swift
Sources/Foundation/Host.swift
Sources/Foundation/NSLock.swift
Sources/Foundation/NSPlatform.swift
Sources/Foundation/Port.swift
Sources/Foundation/Process.swift
Sources/Foundation/Thread.swift

Various fixes to enable building on FreeBSD.
Fixed an issue that warning messages from libthr can be emitted to stderr when thread specific data is used. This is due to CoreFoundation setting the TSD to `CF_TSD_BAD_PTR` even after `PTHERAD_DESTRUCTOR_ITERATIONS` iterators of dtor calls. This causes libthr to emit a warning to stderr about left-over non-null TSD after max destructor iterations.

[FreeBSD] Fix FreeBSD build

---

Sources/CoreFoundation/include/ForFoundationOnly.h

This fixes a longstanding bug in which when multiple threads race calling `__CFStringGetEightBitStringEncoding()` for the first time. When some threads that lose the race (but make the call before the winning thread finishes executing its call) will the losing threads receive a return value of `kCFStringEncodingInvalidId` instead of a valid string encoding. This is because `__CFStringGetEightBitStringEncoding()` ignores the return value of `__CFStringComputeEightBitStringEncoding()` and instead always returns the value in the global `__CFDefaultEightBitStringEncoding`. However, when a thread loses the race, `__CFStringComputeEightBitStringEncoding()` returns a temporary value (ASCII) without setting the global (since another thread is working on calculating the global). This fixes the …

Fix race condition in __CFStringGetEightBitStringEncoding

---

Sources/CoreFoundation/CFPlatform.c

OpenBSD, as the comment string in _CFPosixSpawnFileActionsChdir says, doesn't have posix_spawn_file_actions_addchdir. Therefore, don't link against it; just return ENOSYS like other similarly situated platforms do.

Fix OpenBSD clause.

---

Sources/CoreFoundation/include/ForFoundationOnly.h

- **Explanation**: Fixes a small behavior issue caused by a race condition in `__CFStringGetEightBitStringEncoding`
- **Scope**: Impacts many of the low-level `CFString` functions that use CoreFoundation's "eight bit" string encoding
- **Issues**: https://github.com/swiftlang/swift-corelibs-foundation/issues/5152
- **Original PRs**: https://github.com/swiftlang/swift-corelibs-foundation/pull/5155
- **Risk**: Medium - this is a low level function that is called from a lot of places in CoreFoundation, but the change is very small and is not supposed to change behavior here aside from the window of the race condition.
- **Testing**: Local testing at desk
- **Reviewers**: @parkera

[6.1] Fix race condition in __CFStringGetEightBitStringEncoding

---

Sources/Foundation/NSError.swift
Sources/Foundation/NSURLError.swift
Sources/FoundationNetworking/NSURLRequest.swift
Sources/FoundationNetworking/URLProtectionSpace.swift
Sources/FoundationNetworking/URLRequest.swift
Sources/FoundationNetworking/URLSession/URLSessionConfiguration.swift
Sources/FoundationNetworking/URLSession/URLSessionTaskMetrics.swift

Adding a flag to enable the new HTTP stack in URLSession

New HTTP loader for URLSession

---

Tests/Foundation/TestNSData.swift

The new base64 implementation (https://github.com/swiftlang/swift-foundation/pull/1157) caused this SCL-F test to start failing. Disable the test while we decide if the test is faulty or the new implementation.

Disable a base64 test while we investigate

---

Sources/Foundation/Process.swift

This was added a couple months ago and [when I pointed out it will fail, I was told it would be fixed by some upstream changes and here later](https://github.com/swiftlang/swift-corelibs-foundation/pull/5024#discussion_r1881514022). I haven't heard anything in that comment thread since, so let's at least get this fixed in trunk and 6.1 for now, and we can adjust to Bionic upstream whenever that change is in.
@hyp, let me know if you're okay with just fixing this for now, as [I currently have to do on my Android CI](https://github.com/finagolfin/swift-android-sdk/blob/903ae7c96e71a405911a85c4d98ac627530c78f9/swift-android-foundation-except-release.patch#L33).

Remove incorrect `guard` check for Android

---

Sources/Foundation/Process.swift

__Explanation:__ This `guard` check currently always fails on Android because `spawnAttrs` is set to `nil` on Android just two lines above. There was [some talk of making changes to the Android NDK upstream or nullability annotations instead by @hyp a couple months ago](https://github.com/swiftlang/swift-corelibs-foundation/pull/5024#discussion_r1881514022), which is why we left this in temporarily, but nothing came of it and he hasn't responded in months, so let's just fix this for now.
__Scope:__ Only affects Android
__Issue:__ None
__Original PR:__ #5171
__Risk:__ None
__Testing:__ I apply [this patch on my Android CI for the last couple months](https://github.com/finagolfin/swift-android-sdk/commit/903ae7c96e71a405911a85c4d98ac627530c78f9#diff-c0556429517b8d4c11433e9f45f106cbf88de41f90 …

[6.1] Remove incorrect `guard` check for Android (#5171)

---

Sources/Foundation/Process.swift

This is required as while `posix_spawnattr_init` permits a nullable type, `posix_spawnattr_setflags` properly expects a non-null parameter. Unwrap the newly minted spawnattr or abort if the allocation failed.

Process: unwrap the `posix_spawnattr_t` on Android

---

Sources/CoreFoundation/CFRuntime.c

The SPI declaration for `libdispatch_init` was not attribtued properly. The result of this omission was an improper reference to the function on Windows when disaptch is _not_ linked statically. Correct the declaration by re-using the `DISPATCH_EXPORT` macro to decorate the declaration with the appropriate DLLStorage as necessary.
This was caught by running the Foundation tests with SPM with a refactoring of the toolchain layout during the build.

CoreFoundation: adjust declaration of private SPI

---

Sources/CoreFoundation/CFRuntime.c

The SPI declaration for `libdispatch_init` was not attribtued properly. The result of this omission was an improper reference to the function on Windows when disaptch is _not_ linked statically. Correct the declaration by re-using the `DISPATCH_EXPORT` macro to decorate the declaration with the appropriate DLLStorage as necessary.
This was caught by running the Foundation tests with SPM with a refactoring of the toolchain layout during the build.
(cherry picked from commit 853b68167d1ea012b732aa19eecebfbd9e3b10fd)
- **Explanation**: Correct the inline declaration for a libdispatch SPI.
- **Scope**: This changes the CPP declaration for the libdispatch SPI in just the implementation of a single translation unit in CoreFoundation. The resulting difference is limited to the Windows platform. …

[6.1] CoreFoundation: adjust declaration of private SPI

---

CMakeLists.txt

There is no early swift-driver build for the Windows toolchain. As a result, swift-collections fails to build properly when CMP0157 is set to NEW due to object files not being generated.
This sets CMP0157 to OLD when targetting Android until the early swift-driver is available on Windows.

Set CMP0157 to OLD for Android

---

Sources/Foundation/Process.swift

This is required as while `posix_spawnattr_init` permits a nullable type, `posix_spawnattr_setflags` properly expects a non-null parameter. Unwrap the newly minted spawnattr or abort if the allocation failed.
Cherry pick commit https://github.com/swiftlang/swift-corelibs-foundation/pull/5179

[6.1] Process: unwrap the posix_spawnattr_t on Android

---

Sources/Foundation/NSConcreteValue.swift
Sources/Foundation/NSSpecialValue.swift
Sources/Foundation/NSString.swift
Sources/Foundation/NSStringAPI.swift
Tests/Foundation/TestNSString.swift

The extension on `String` to provide a C string works well enough on Darwin, when used with an `autoreleasepool { }`. However, on other platforms where we have no autorelease pools, it simply leaks. Even though this API is useful on Darwin, we should deprecate it in swift-corelibs-foundation because it has repeatedly been the source of some confusing behavior.
https://github.com/swiftlang/swift-corelibs-foundation/issues/3885

Deprecate cString on non-Darwin (#3885)

---

Sources/CoreFoundation/CFPlatform.c

The refactoring in #5160 moved a comment around such that it appeared as if QNX supports this function - it does not. Clarify the situation.

Fix the comment about the posix_spawn_file_actions_addchdir support state

---

CMakeLists.txt

- **Explanation**:
There is no early swift-driver build for the Windows toolchain. As a result, swift-collections fails to build properly when CMP0157 is set to NEW due to object files not being generated.
This sets CMP0157 to OLD when targetting Android until the early swift-driver is available on Windows.
- **Scope**:
The changes are limited to the Android build on Windows.
- **Issues**:
swiftlang/swift-foundation#1222
- **Original PRs**:
#5180
- **Risk**:
Very low.
- **Testing**:
Fixes the Swift CI 6.1 build.
- **Reviewers**:
@finagolfin

Set CMP0157 to OLD only for Windows hosts

---

Sources/Foundation/NSString.swift
Tests/Foundation/TestNSString.swift

Fixes #5193 by adding a dynamic replacement for the FoundationEssentials extensions on `String` to use when handed an encoding that only CoreFoundation knows how to deal with.

Add callout for FoundationEssentials to handle non-UTF encodings (#5193)

---

Sources/CoreFoundation/CFPlatform.c

Currently executable importing Foundation may crash when launched with certain shell as a platform specific way to get the path of the process's executable is not defined. This PR implements this missing piece to fetch the process path via `sysctl`

[FreeBSD] lookup process path via sysctl

---

Sources/Foundation/NSData.swift
Sources/Foundation/NSString.swift

`Data.WritingOptions.atomic` is now unavailable on WASI https://github.com/swiftlang/swift-foundation/pull/992, so we need to gate them behind platform checks

[wasm] Gate atomic write option usages behind platform check

---

Sources/plutil/PLUContext_KeyPaths.swift

Recently, `FoundationEssentials` began importing the `RegexBuilder` module. While it's an `internal` import, since we don't have the `MemberImportVisibility` feature flag enabled, this import affected overload resolution of this call to `split`. Eventually, we should enable that feature flag to avoid these types of issues, but for now we make the argument explicitly `Character` to pick the stdlib overload instead of the `RegexBuilder` overload to fix linking failures.

Avoid implicitly linking RegexBuilder symbol

---

CMakeLists.txt
Sources/Foundation/CMakeLists.txt
Sources/FoundationNetworking/CMakeLists.txt
Sources/FoundationXML/CMakeLists.txt
Sources/plutil/CMakeLists.txt

This is required for $ORIGIN rpath processing here (without having to fiddle with workarounds like LD_LIBRARY_PATH).

Add -z,origin linker flag on OpenBSD.

---

Sources/CoreFoundation/include/CFBase.h

Fix “error: import of C++ module 'ptrauth' appears within extern "C" language linkage specification”
LLVM upstream makes  ptrauth  a module on this commit https://github.com/swiftlang/llvm-project/commit/0481f049c37029d829dbc0c0cc5d1ee71c6d1c9a.
Swift 6.1 release introduced such change into the toolchain.
Close #5211

Fix ptrauth C++ module include issue between extern

---

Sources/CoreFoundation/CFPlatform.c

@jakepetroules, following on the similar swiftlang/swift-llbuild#985, this gets Foundation building with older Android APIs too, which I've had to [patch otherwise on my Android CI](https://github.com/finagolfin/swift-android-sdk/blob/43b07babb7e27bf48dc5afe0b9be56398fe22805/swift-android.patch#L101) that builds against API 24.

[android] Support building `_CFPosixSpawnFileActionsChdir()` for older Android APIs too

---

Sources/CoreFoundation/CFRunLoop.c
Sources/Foundation/RunLoop.swift

This patch enables CFRunLoop for FreeBSD.
Related libdispatch PR: https://github.com/swiftlang/swift-corelibs-libdispatch/pull/861

[FreeBSD] Enable CFRunLoop support

---

Sources/CoreFoundation/CMakeLists.txt

When building statically, define `CF_WINDOWS_EXECUTABLE_INITIALIZER` to ensure that the runtime constructor is registered and invoked properly. This is required to initialise CoreFoundation and `Foundation.Bundle`.

build: define `CF_WINDOWS_EXECUTABLE_INITIALIZER`

---

Sources/CoreFoundation/CFPlatform.c

This function is now duplicated or soon to be duplicated across approximately 4 different places throughout the Swift project. Format it stylistically to standardize it everywhere for easier comparison and copy-pasting.

Stylistic changes to _CFPosixSpawnFileActionsChdir implementation

---

Sources/Foundation/NSError.swift

- **Explanation**: Accessing `localizedDescription` on a class that conforms to `Error` but does not inherit from `NSError` causes a crash on Linux.
- **Scope**: Non-Darwin platforms only
- **Issue**: https://github.com/swiftlang/swift-corelibs-foundation/issues/5221
- **Original PR**: #5222
- **Risk**: Seems low to me and the current crash is definitely not desirable
- **Testing**: n/a 
- **Reviewer**: @jmschonfeld on https://github.com/swiftlang/swift-corelibs-foundation/pull/5222

[6.2] Use a regular downcast instead of an unsafe downcast for Error to NSError conversion (#5221) (#5222)

---

Sources/FoundationXML/XMLNode.swift

Fixes #5230 by force setting the name for XMLNodes when they're XMLDTDs as the regular _CFXMLNodeSetName function doesn't account for them with future versions of libxml2

Add case within XML Node's name setter for DTDKind (#5230)

---

Sources/Foundation/Decimal.swift

This PR depends on https://github.com/swiftlang/swift-foundation/pull/1471 (which exposes Decimal.pow() as a public API)
Resolves: https://github.com/swiftlang/swift-foundation/issues/1455

Remove Decimal.pow() in favor of the one defined in FoundationEssentials
