swiftlang/swift-corelibs-foundation

- Foundation/NSString.swift
- TestFoundation/TestNSString.swift
This depends on the bug fix in #83 and should be merged after merging that PR.
> [NSString] Add implementation of `integerValue` and tests

- Foundation/NSHTTPCookie.swift
Added some of the basic implementation of NSHTTPCookie
> Add some implementation of NSHTTPCookie

- Foundation/NSString.swift
> Fix NSString.compare

- Foundation.xcodeproj/project.pbxproj
- Foundation/NSNotification.swift
- TestFoundation/TestNSNotificationCenter.swift
- TestFoundation/main.swift
Re-submitting this pull request, so it has only one commit. Discussion is here: https://github.com/apple/swift-corelibs-foundation/pull/62
> Implement NSNotification and NSNotificationCenter

- TestFoundation/TestNSString.swift
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/apple/swift-corelibs-foundation/115)
> Add full-width romaji testcases to uppercase/lowercase strings.

- Foundation/NSArray.swift
- Foundation/NSObjCRuntime.swift
- TestFoundation/TestNSArray.swift
Implement NSArray.indexOfObject(inSortedRange:options:usingComparator) and add test cases for it.
> Implement NSArray.indexOfObject(inSortedRange:options:usingComparator)

- Foundation/NSGeometry.swift
- TestFoundation/TestNSGeometry.swift
Implemented various NSRect-related functions from NSGeometry, that test geometric relationships: `NSUnionRect`, `NSIntersectionRect`, `NSOffsetRect`, `NSPointInRect`, `NSMouseInRect`, `NSContainsRect`, `NSIntersectsRect`.
> Implemented various NSRect-related functions from NSGeometry

- CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
- Foundation.xcodeproj/project.pbxproj
- Foundation/NSProcessInfo.swift
- TestFoundation/TestNSProcessInfo.swift
- TestFoundation/main.swift
Resubmission of #106 after I messed up a rebase.
> Implemented NSProcessInfo's processName and tests.

- Foundation/NSXMLParser.swift
- Use `guard let` and return early.
- Remove needless parenthesis.
- combiine several `if let`
> Improve control flow and some fix

- Foundation/NSObject.swift
Just a trivial fix. Sorry for my code mysophobia.
> Remove empty line in NSObject.swift

- Foundation/NSHost.swift
- Foundation/NSXMLParser.swift
- TestFoundation/TestNSCharacterSet.swift
This gets rid of eight (almost deprecated 😀) old style for loops.
> Get rid of c-style for loops

- Foundation/NSArray.swift
- TestFoundation/TestNSArray.swift
Issue was method ignored range argument.
> NSArray sorted array from range fix

- Foundation/NSPathUtilities.swift
- TestFoundation/TestNSString.swift
Implement NSString.completePathIntoString. Tests included.
> Implement NSString.completePathIntoString.

- Foundation/NSPathUtilities.swift
- TestFoundation/TestNSString.swift
> Implement NSUserName(), NSHomeDirectory(), NSHomeDirectoryForUser()

- Docs/Issues.md
improve swift code syntax highlighting
> swift code syntax

- Foundation/NSArray.swift
- Foundation/NSDictionary.swift
- Foundation/NSSet.swift
- TestFoundation/TestNSArray.swift
- TestFoundation/TestNSDictionary.swift
- TestFoundation/TestNSSet.swift
Defined isEqual and hash value getters for `NSArray`, `NSDictionary` and `NSSet`
> Defined isEqual and hash value getters for various collection classes

- CoreFoundation/RunLoop.subproj/CFRunLoop.h
- Foundation.xcodeproj/project.pbxproj
- Foundation/NSTask.swift
- TestFoundation/TestNSTask.swift
- TestFoundation/main.swift
NSTask can now launch processes using a launch path and arguments, as well as trigger a termination handler.
> Baseline work on NSTask

- Docs/Design.md
Add Swift and C code style highlighting
> improve code highlighting

- Foundation.xcodeproj/project.pbxproj
- Foundation/NSOrderedSet.swift
- TestFoundation/TestNSOrderedSet.swift
- TestFoundation/main.swift
This is a fairly large class, so I've gone through and only implemented basic functionality. If the implementation approach makes sense, I can continue to fill this out.
Tested on OS X and Ubuntu 14.04.
> Initial implementation of NSOrderedSet

- CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
> [SR-431] expose _CFWriteStreamCreateFromFileDescriptor

- Foundation/NSPathUtilities.swift
> [SR-432] temporary file creation API

- Foundation/NSOrderedSet.swift
- TestFoundation/TestNSOrderedSet.swift
This pass implements a variety of mutation functions.
> Continue to fill out NSOrderedSet

- Foundation.xcodeproj/project.pbxproj
- Foundation/NSNotificationQueue.swift
- Foundation/NSThread.swift
- TestFoundation/TestNSNotificationQueue.swift
- TestFoundation/main.swift
Initial implementation of the NSNotificationQueue. Supports NSPostingStyle.PostNow style only.
> Initial implementation of the NSNotificationQueue

- Foundation/NSFileManager.swift
first commit, since I've been told I need to commit more in my life. Minor change, removes a little redundancy. Shouldn't break anything.
> slight refactor to remove redundancy

- CoreFoundation/Base.subproj/CFBase.h
- CoreFoundation/RunLoop.subproj/CFMachPort.c
- CoreFoundation/RunLoop.subproj/CFRunLoop.h
- TestFoundation/TestNSString.swift
Fix a bunch of compile warnings.
> [SR-440] warnings cleanup

- Foundation/NSSet.swift
- TestFoundation/TestNSSet.swift
Enabled the NSSet convenience initializers, implemented unit tests.
> NSSet convenience initializers

- Foundation/NSData.swift
- TestFoundation/TestNSData.swift
add the missing implementation of rangeOfData and tests : https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20160111/000352.html
> implementation of NSData rangeOfData(options:range:)

- README.md
Link has probably been changed since the creation of the file.
> Corrected bad wrong link to API design guidelines

- Foundation/NSFileManager.swift
Reverts apple/swift-corelibs-foundation#245
(https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-15_10/2046/)
> Revert "Fix key's typo to NSFileGroupOwnerAccountName"

- TestFoundation/TestNSCharacterSet.swift
> Added few tests for NSMutableCharacterSet

- Foundation.xcodeproj/project.pbxproj
- Foundation.xcodeproj/xcshareddata/xcschemes/CoreFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/plutil.xcscheme
resolved a few warnings that show up in Xcode
> Xcode warnings cleanup

- Foundation/NSRunLoop.swift
> [NSRunLoop] Use Swift 3 enum values on OS X/iOS

- Foundation/NSFileManager.swift
- Foundation/NSGeometry.swift
- Foundation/NSKeyedUnarchiver.swift
- Foundation/NSString.swift
- Foundation/NSXMLParser.swift
- Foundation/String.swift
Manually made changes to fix the errors we were seeing.
> Fixed lingering SE-0046 changes

- Foundation/NSHTTPCookie.swift
- Foundation/NSURLError.swift
- Foundation/NSURLRequest.swift
- Foundation/NSURLResponse.swift
> Convert ObjC comments into Swift documentation markup.

- Foundation/NSJSONSerialization.swift
- TestFoundation/TestNSJSONSerialization.swift
Fix for my bug report https://bugs.swift.org/browse/SR-1250
> Parse non-floating point numbers into Int instead of Double

- Foundation/NSPredicate.swift
- TestFoundation/TestNSPredicate.swift
I didn't complete these in my initial PR for NSPredicate (only did NSArray), so I thought I'd finish the job for the other collection types.
> Implement filter with predicate methods on foundation collections

- Foundation.xcodeproj/project.pbxproj
Xcode cannot run the tests as a missing TestCase is being referenced.
> Added missing file to workspace

- Foundation/NSURL.swift
- TestFoundation/TestNSURL.swift
Added implementation of NSURLComponents.URLRelativeToURL()
> implementation for NSURLComponents.URLRelativeToURL API

- Foundation/NSArray.swift
- Foundation/NSCalendar.swift
- Foundation/NSDate.swift
- Foundation/NSDictionary.swift
- Foundation/NSIndexPath.swift
- Foundation/NSIndexSet.swift
- Foundation/NSObjCRuntime.swift
- Foundation/NSOperation.swift
- Foundation/NSOrderedSet.swift
- Foundation/NSString.swift
- Foundation/NSTask.swift
- TestFoundation/TestNSArray.swift
- TestFoundation/TestNSDate.swift
- TestFoundation/TestNSNumber.swift
- TestFoundation/TestNSOrderedSet.swift
- TestFoundation/TestNSString.swift
Changed API of NSComparisonResult, NSQualityOfService, NSSortOptions and NSEnumerationOptions to match Darwin version
> Changed API of comparison/sort/enumeration/qos options to match Darwin version

- Foundation/NSDate.swift
Align the `#else` with the `#if` and `#endif`.  NFC.
> NSDate: tweak whitespace

- Foundation/NSJSONSerialization.swift
- TestFoundation/TestNSJSONSerialization.swift
Reverts apple/swift-corelibs-foundation#373
> Revert "Changes done to NSJSONSerialization to align with darwin code"

- Foundation/NSKeyedArchiver.swift
- Foundation/NSOperation.swift
- Foundation/NSSwiftRuntime.swift
- Foundation/NSTask.swift
- Foundation/NSThread.swift
- Foundation/NSXMLNode.swift
This is related to the changes in https://github.com/apple/swift/pull/2537
> For SE-0017, remove use of OpaquePointer

- Foundation/NSBundle.swift
- TestFoundation/TestNSBundle.swift
- TestFoundation/TestNSData.swift
- TestFoundation/main.swift
Please note that this change should be merged along with the pull request - https://github.com/apple/swift-corelibs-xctest/pull/119 else XCTest and TestFoundation will fail to build"
> Changing NSBundle api to match the Darwin version

- CoreFoundation/Base.subproj/CFInternal.h
There were six different variants with minor tweaks to the macro definition.
Use a few more macros to abstract out the retain count initializer, the tag
name, and the const-ness of the struct.  This allows the variants to be
collapsed into a single definition.
> CoreFoundation: clean up CF_CONST_STR macro definition

- Foundation/String.swift
This change must be merged with apple/swift#3268.
> Update for new string index inits

- Foundation.xcodeproj/project.pbxproj
- Foundation/Unit.swift
- TestFoundation/TestUnitConverter.swift
- TestFoundation/main.swift
Hi everyone,
This is an implementation for UnitConverter and all its related classes.
I would love to receive your feedbacks.
Should I split in several commits for code reviewing?
Thanks,
> Add implementation for UnitConverter and its related classes

- TestFoundation/TestNSBundle.swift
- TestFoundation/TestNSFileManager.swift
- TestFoundation/TestNSJSONSerialization.swift
- TestFoundation/TestNSNotificationQueue.swift
- TestFoundation/TestNSString.swift
- TestFoundation/TestNSTask.swift
Address the various set of unused result warnings in the test suite.  NFC.
> test: address a number of unused result warnings

- Foundation/NSDateFormatter.swift
- Foundation/NSLocale.swift
- Foundation/NSNumberFormatter.swift
- Foundation/NSScanner.swift
- Foundation/NSString.swift
- Foundation/String.swift
- TestFoundation/TestNSKeyedArchiver.swift
> [NSLocation] Updated to match Darwin version

- Foundation/NSFileManager.swift
- Foundation/NSHTTPCookie.swift
- Foundation/NSOrderedSet.swift
- Foundation/NSURL.swift
- Foundation/NSUserDefaults.swift
- Foundation/NSXMLParser.swift
This is a mechanical change addressing a number of
"warning: expected 'let' in conditional"
warnings from the current compiler.  NFC.
> Foundation: address a number of warnings

- Foundation/NSArray.swift
- Foundation/NSConcreteValue.swift
- Foundation/NSDictionary.swift
- Foundation/NSKeyedCoderOldStyleArray.swift
- Foundation/NSString.swift
- Foundation/NSTask.swift
This coincides with the apple/swift PR:
https://github.com/apple/swift/pull/3585
> Update for SE-0107, rename initializeFrom.

- Foundation/NSObjCRuntime.swift
Depends on https://github.com/apple/swift/pull/3658
> Update for SE-0102 -- @noreturn attribute replaced with Never type

- Foundation/NSBundle.swift
- Foundation/NSHost.swift
- Foundation/NSJSONSerialization.swift
- Foundation/NSKeyedArchiver.swift
- Foundation/NSObjCRuntime.swift
- Foundation/NSRegularExpression.swift
- Foundation/NSString.swift
- Foundation/NSXMLParser.swift
This pull request and apple/swift#3761 must be merged in concert with each other.
> Minor update for SE-0089

- Foundation/NSArray.swift
- Foundation/NSDictionary.swift
- Foundation/NSError.swift
- Foundation/NSIndexSet.swift
- Foundation/NSJSONSerialization.swift
- Foundation/NSXMLNode.swift
- Foundation/NSXMLParser.swift
- TestFoundation/TestNSCompoundPredicate.swift
For more information, see https://github.com/apple/swift/pull/3895
> Updates for SE-0110 Part I

- Foundation/NSBundle.swift
- TestFoundation/TestNSBundle.swift
- TestFoundation/TestNSData.swift
- TestFoundation/TestNSKeyedUnarchiver.swift
- TestFoundation/TestNSPropertyList.swift
- TestFoundation/TestNSString.swift
- TestFoundation/TestNSURL.swift
- TestFoundation/TestNSXMLDocument.swift
* `open class func main()` → `open class var main`
* Method naming
> Foundation API Conformance Update: Bundle

- Foundation/NSJSONSerialization.swift
> Foundation API Conformance Update: JSONSerialization

- Foundation/Data.swift
- TestFoundation/TestNSData.swift
- Use calloc() instead of malloc()
> Fix Data(count:) to correctly zero the data

- Foundation/NSLog.swift
To maintain API consistency with Darwin, this PR proposes NSLog and NSLogv be
made public functions.
> Making NSLog and NSLogv public

- Foundation/NSPathUtilities.swift
- Foundation/NSProcessInfo.swift
- TestFoundation/TestNSProcessInfo.swift
- TestFoundation/TestNSURL.swift
- Tools/plutil/main.swift
to align with recent changes on Darwin (Xcode 8)
> change ProcessInfo.processinfo() class func to processinfo static let

- Foundation/Data.swift
- Foundation/NSString.swift
- TestFoundation/TestNSData.swift
- TestFoundation/TestNSJSONSerialization.swift
- TestFoundation/TestNSStream.swift
- This matches the Foundation API in Darwin
> Fix Data(capacity:) and Data(count:) to return non-optional

- CoreFoundation/StringEncodings.subproj/CFStringEncodingConverter.c
This PR is to resolve performance bottleneck while converting strings using NSString.data(using:) API concurrently. Performance degradation is exponential to no.of concurrent conversion. This API boils down to __CFGetConverter() function of CFStringEncodingConverter.c
__CFGetConverter returns converter which is costly operation based on the encoding passed. Hence, this function cache converter(s) in static map/dictionary and static double pointer for common case like kCFStringEncodingUTF8, kCFStringEncodingMacRoman | kCFStringEncodingWindowsLatin1, __defaultEncoding. So, it make use of lock(s) to avoid multiple threads working with static variables.
```
const _CFEncodingConverter **commonConverterSlot = NULL;
static _CFEncodingConverter *commonConverters[3] = {NULL, NULL, NULL}; // UTF8, …
```
> Fix performance bottleneck with __CFGetConverter

- Foundation/NSJSONSerialization.swift
- TestFoundation/TestNSJSONSerialization.swift
Reverts apple/swift-corelibs-foundation#540
> Revert "[SR-2151]NSJSONSerialization.data produces illegal JSON code"

- Foundation/NSArray.swift
- Foundation/NSCache.swift
- Foundation/NSComparisonPredicate.swift
- Foundation/NSCompoundPredicate.swift
- Foundation/NSError.swift
- Foundation/NSExpression.swift
- Foundation/NSFileHandle.swift
- Foundation/NSFileManager.swift
- Foundation/NSMeasurementFormatter.swift
- Foundation/NSNotification.swift
- Foundation/NSNumberFormatter.swift
- Foundation/NSPersonNameComponents.swift
- Foundation/NSPersonNameComponentsFormatter.swift
- Foundation/NSPredicate.swift
- Foundation/NSString.swift
- Foundation/NSThread.swift
- Foundation/NSTimer.swift
- Foundation/NSUserDefaults.swift
- Foundation/PersonNameComponents.swift
- TestFoundation/TestNSArray.swift
- TestFoundation/TestNSCompoundPredicate.swift
- TestFoundation/TestNSDictionary.swift
- TestFoundation/TestNSFileManager.swift
- TestFoundation/TestNSNumberFormatter.swift
- TestFoundation/TestNSPredicate.swift
- TestFoundation/TestNSString.swift
- TestFoundation/TestNSTimer.swift
- TestFoundation/TestNSUserDefaults.swift
Reverts apple/swift-corelibs-foundation#567, blocked by https://github.com/apple/swift-package-manager/pull/611
> Revert "Foundation API Conformance Update: Miscellaneous"

- Foundation/NSNotification.swift
- Foundation/NSNotificationQueue.swift
- Foundation/Notification.swift
- TestFoundation/TestNSNotificationCenter.swift
- TestFoundation/TestNSNotificationQueue.swift
Bring the API names to match Swift 3 Darwin for Notification/NSNotification and NotificationCenter
> Swift 3 Darwin API Parity: Notification and friends

- Foundation/NSAttributedString.swift
- Foundation/NSOrderedSet.swift
- Foundation/NSSet.swift
- TestFoundation/TestNSAttributedString.swift
- TestFoundation/TestNSOrderedSet.swift
Set
OrderedSet
CountedSet
AttributeString
and their cousins have now been auditted.
> Further Swift 3 Darwin API Parity

- Foundation/CGFloat.swift
https://github.com/apple/swift-corelibs-foundation/pull/585 added CGFloat.swift.  I'd like to add s390x as a platform so we can build it.
> Adding s390x to CGFloat

- Foundation/UUID.swift
Resolves https://bugs.swift.org/browse/SR-2470
> Remove the dep on CUUID for Foundation

- Foundation/NSJSONSerialization.swift
- Foundation/NSStream.swift
- Foundation/NSSwiftRuntime.swift
- Foundation/NSURLSession/NSURLSession.swift
- Foundation/NSURLSession/NSURLSessionDelegate.swift
- Foundation/NSURLSession/NSURLSessionTask.swift
- TestFoundation/TestNSJSONSerialization.swift
- TestFoundation/TestNSStream.swift
Bring `NSOutputStream` in line with `InputStream` (and change some missed `NSInputStream` → `InputStream` in comments as well)
> Rename NSOutputStream to OutputStream

- Foundation/NSProgress.swift
NFC. Also, not much attempt to fix up the comments yet.
No tests because nothing is actually implemented yet.
> Update API of NSProgress to Progress

- Foundation/Locale.swift
Reported in [SR-3032](https://bugs.swift.org/browse/SR-3032)
> [SR-3032] Fix comment in Locale

- Foundation/NSDecimalNumber.swift
- TestFoundation/TestNSDecimal.swift
Add implementations for NSDecimalNumber methods that are
not yet implemented.
> Implement the rest of NSDecimalNumber

- Foundation/NSHTTPCookie.swift
I have tried to match the description string of HTTPCookie on Darwin.
> Implementation of description string for HTTPCookie

- Foundation/Data.swift
Reverts apple/swift-corelibs-foundation#774
> Revert "Revert "Update for new rules on @inline(__always) function bodies""

- Foundation/URL.swift
This matches the Darwin version.
> [URLResourceValues] Remove redundant NSCoding protocol from some existential types

- Docs/Status.md
The `NSCopying` work has been done in #746.
> [Docs] Update NSPersonNameComponents status to Complete

- Foundation/Data.swift
- Foundation/NSData.swift
- Foundation/NSStringAPI.swift
- Foundation/NSURLSession/HTTPBodySource.swift
- Foundation/NSURLSession/TaskRegistry.swift
This is the same as https://github.com/apple/swift/pull/6521.
> [gardening] prefer '-> Void' over '-> ()'

- Foundation/NSNotificationQueue.swift
https://developer.apple.com/reference/foundation/notificationqueue.notificationcoalescing/1415826-none
> [NotificationQueue] Add missing `none` to NotificationCoalescing

- Foundation/NSData.swift
- Foundation/NSURLSession/NSURLSession.swift
- Foundation/NSURLSession/NSURLSessionTask.swift
- Foundation/NSURLSession/TaskRegistry.swift
- TestFoundation/TestNSURLSession.swift
> [URLSession] Replace remaining NSError usages with Error

- CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
- Foundation/NSHost.swift
Cherry picks #803. See https://github.com/apple/swift-corelibs-xctest/pull/185#issuecomment-274221790 and https://github.com/apple/swift-corelibs-foundation/pull/803#issuecomment-274233858.
cc @parkera @briancroom
> [3.1] Fix building NSHost.swift on macOS

- Foundation/NSKeyedUnarchiver.swift
- Foundation/NSStream.swift
- Foundation/NSURLAuthenticationChallenge.swift
- NSKeyedUnarchiver.swift
- NSStream.swift
- NSURLAuthenticationChallenge.swift
> Reduce NSError usages (to match the Darwin version)

- Foundation/NSCache.swift
- Foundation/NSDecimal.swift
- Foundation/NSDecimalNumber.swift
- Foundation/NSDictionary.swift
- Foundation/NSError.swift
- Foundation/NSHTTPCookieStorage.swift
- Foundation/NSLocale.swift
- Foundation/NSNotification.swift
- Foundation/NSObject.swift
- Foundation/NSSortDescriptor.swift
- Foundation/NSString.swift
- Foundation/NSURLProtocol.swift
Depends on #808. I'll rebase this once that pull request is merged.
> Rename to NSSortDescriptor to match the Darwin version

- Foundation/NSObject.swift
Reverts apple/swift-corelibs-foundation#828
> Revert "[gardening][NSObject] Move operators into types"

- Foundation/NSFileManager.swift
- TestFoundation/TestNSFileManager.swift
Original pull request was #660.  This just adds the tests that were requested.
Don't know if creating a separate pull request was the thing to do here.  Is it possible to modify a pull request if you are not the owner/maintainer??
> copyItem Implementation with Tests.

- Foundation/Calendar.swift
- TestFoundation/TestNSCalendar.swift
Implement `CustomReflectable` protocol for `Calendar` and update its `description` and `debugDescription` implementation to match the Darwin version.
> [Calendar] Implement CustomReflectable protocol

- Foundation/NSString.swift
Minor refactoring for the implementation in #744.
> [String] Fast paths for `hasPrefix` and `hasSuffix`

- Foundation/NSLocale.swift
Reverts apple/swift-corelibs-foundation#840
https://github.com/apple/swift-corelibs-foundation/pull/833#issuecomment-277047371
> Revert "Revert "[gardening][NSLocale] Move operators into types""

- CoreFoundation/Collections.subproj/CFData.c
Related PR on master branch https://github.com/apple/swift-corelibs-foundation/pull/890 for [Commit : a39d6c3f86104ca474086c599a88806b419ee875]
> [Swift 3.1] Performance regression in NSMutableData [SR-3966]

- Foundation/NSString.swift
- TestFoundation/TestNSString.swift
Cherry picking https://github.com/apple/swift-corelibs-foundation/pull/647
> [cherry-pick]Fix for a crash in String.substring(with:)

- Docs/Status.md
ByteCountFormatter is now largely implemented.
> Update ByteCountFormatter status

- Foundation/NSURLSession/NSURLSessionTask.swift
@parkera Though this is not critical, we have complains about this message causing a lot of noise. Can we have it in 3.1 please?
> [cherry-pick][urlsession]pull request #903 from pushkarnk/print-debug

- Foundation/NSRegularExpression.swift
> Fix typo. currentRnage -> currentRange

- Foundation/NSOperation.swift
- TestFoundation/TestNSOperationQueue.swift
Cherry-pick #836 for `swift-3.1-branch`.
> [3.1] Operation: add willChangeValue() and didChangeValue()

- build.py
> [Cherry Pick] Fix building on RasPi

- Docs/Status.md
> Add ISO8601DateFormatter to Status.md

- Foundation/NSURLSession/NSURLSessionTask.swift
- TestFoundation/main.swift
The corresponding commit on master:
https://github.com/apple/swift-corelibs-foundation/pull/982/commits/a4497372448ed388d507028b7d7a68fc333a491c
PR: https://github.com/apple/swift-corelibs-foundation/pull/982
> [Swift 3.1] Fix for the intermittent URLSession Test Failures on async wait.

- Foundation/NSURLSession/MultiHandle.swift
Please don't merge for now. URLSession tests are disabled. We'll first have to get them enabled.
> [cherry-pick 3.1]Fix for a race condition in URLSession

- Foundation/NSURLSession/NSURLSession.swift
The corresponding commit on master: https://github.com/apple/swift-corelibs-foundation/pull/983/commits/6f7ea2c843cad986852f66640d1eb5019735dc67
PR: https://github.com/apple/swift-corelibs-foundation/pull/983
> [Swift 3.1] Make urlSession delegate queue serial as per the spec.

- Foundation/NSGeometry.swift
- Foundation/NSRange.swift
- Foundation/NSScanner.swift
- TestFoundation/TestNSScanner.swift
https://developer.apple.com/reference/foundation/scanner/1412801-isatend
> [Scanner] Rename `atEnd` to `isAtEnd` to match the Darwin version

- Foundation/NSDecimal.swift
Related commit in apple/swift#8804
> Remove for loop in computing mantissa double value

- Foundation/NSURLProtocol.swift
- Foundation/NSURLSession/http/HTTPURLProtocol.swift
- TestFoundation/TestNSURLSession.swift
Including the regression fix ( #1049) on 3.1
> [3.1][regression]Fix for test_finishTaskAndInvalidate failure

- Foundation/NSLengthFormatter.swift
- Foundation/NSMassFormatter.swift
- TestFoundation/TestNSLengthFormatter.swift
> Revert 1043

- Foundation/ExtraStringAPIs.swift
- Foundation/NSRange.swift
- Foundation/NSStringAPI.swift
- Foundation/URLComponents.swift
https://github.com/apple/swift-evolution/blob/master/proposals/0180-string-index-overhaul.md
> Updates for acceptance of SE-0180 (Cross-project merge only!)

- Foundation/Operation.swift
- TestFoundation/TestNSOperationQueue.swift
`OperationQueue.current` implemented
> OperationQueue.current implemented

- Foundation/NSNotification.swift
- TestFoundation/TestNSNotificationCenter.swift
`NSNotification` observing on specific queue implemented.
> NSNotification observing on specific queue implemented.

- Foundation/NSPersonNameComponents.swift
- TestFoundation/TestNSPersonNameComponents.swift
`NSPersonNameComponents.isEqual` implemented
> NSPersonNameComponents.isEqual implemented

- Foundation/NSURLSession/http/HTTPMessage.swift
> More adjustments in support of Swift PR 11088

- Foundation/NSTextCheckingResult.swift
- TestFoundation/TestNSTextCheckingResult.swift
- resultByAdjustingRangesWithOffset() -> adjustingRanges(offset:)
> NSTextCheckingResult: Rename method to match Darwin

- Foundation/IndexSet.swift
As per https://github.com/apple/swift/commit/42968b206963ae62a1be7f7e1dcaf83c37a3bc9c.
> IndexSet: update MARK comment

- TestFoundation/TestProcess.swift
- Handle differences in output from /bin/cat on Linux/macOS when
printing an error.
-  test_pipe_stdout_and_stderr_same_pipe(): Dont pass malloc debug
flags to subprocesses when debugging under Xcode.
- runTask(): return stdout and stderr as separate values so the malloc debug is captured separately.
> Process: Uncomment disabled tests and make compatible with Darwin

- Foundation/HTTPCookieStorage.swift
- TestFoundation/TestHTTPCookieStorage.swift
Cherry pick of #1182 to the 4.0 branch.
> [4.0] Fix HTTPCookieStorage threading issues

- Foundation/ByteCountFormatter.swift
- Foundation/JSONEncoder.swift
- Foundation/NSNotification.swift
- Foundation/NSTextCheckingResult.swift
- Foundation/Stream.swift
- TestFoundation/TestByteCountFormatter.swift
- TestFoundation/TestJSONEncoder.swift
- TestFoundation/TestNSTextCheckingResult.swift
Cherry-pick various API fixups to the Swift 4.0 branch.
- https://github.com/apple/swift-corelibs-foundation/commit/0df89455239a9fa4bf96b04d109d2dd622080c4c NSNotification
- https://github.com/apple/swift-corelibs-foundation/commit/b672401cb741b6da100986709b175abd1aed2dc5 NSTextCheckingResult
- https://github.com/apple/swift-corelibs-foundation/commit/e676cd7aeeeadeec96f0d1eef78ef93e5ba5f234 ByteCountFormatter
- https://github.com/apple/swift-corelibs-foundation/commit/7e617e2dc130f0c98fc2d17f0a13ab4012a94358 JSONEncoder.Data[En|De]codingStrategy
- https://github.com/apple/swift-corelibs-foundation/commit/84bc0e7f0f4845d7d25502419f3505c679f20de6 StreamDelegate
> [4.0] Darwin API compatibility fixes

- Foundation/NSArray.swift
- Foundation/NSCFArray.swift
- TestFoundation/TestNSArray.swift
- addObjectsFromArray() -> addObjects(from:)
- replaceObjects(in:withObjectsFromArray) ->
replaceObjects(in:withObjectsFrom:)
- sort() -> sort(comparator:)
> NSMutableArray: Rename methods to match Darwin

- TestFoundation/TestCharacterSet.swift
- TestFoundation/TestNSData.swift
- TestFoundation/TestNSDictionary.swift
These test now work on both macOS and Linux.
> Re-enable tests that now work.

- Foundation/UserDefaults.swift
basic whitespace fix, was bugging me
> Whitespace fix in UserDefaults

- Foundation/Unit.swift
> Fix power prefix in Unit.swift

- Foundation/NSString.swift
Another case that SE-0054 disallows.
> Fix another IUO that appears in a type.

- build.py
The current code emits: `- I  { S Y S R O O T } / u s r / i n c l u d e / c u r l   - I  { S Y S R O O T } / u s r / i n c l u d e / l i b x m l 2`
> [build.py] swift_cflags is an array

- Foundation/AffineTransform.swift
- Foundation/Data.swift
- Foundation/Dictionary.swift
- Foundation/FileManager.swift
- Foundation/Host.swift
- Foundation/JSONSerialization.swift
- Foundation/NSArray.swift
- Foundation/NSCFDictionary.swift
- Foundation/NSCFSet.swift
- Foundation/NSCoder.swift
- Foundation/NSConcreteValue.swift
- Foundation/NSDictionary.swift
- Foundation/NSGeometry.swift
- Foundation/NSKeyedCoderOldStyleArray.swift
- Foundation/NSLock.swift
- Foundation/NSOrderedSet.swift
- Foundation/NSRange.swift
- Foundation/NSSet.swift
- Foundation/NSString.swift
- Foundation/NSSwiftRuntime.swift
- Foundation/NSUUID.swift
- Foundation/Process.swift
- Foundation/Set.swift
- Foundation/String.swift
- Foundation/Thread.swift
- TestFoundation/TestNSKeyedArchiver.swift
This reverts commit 1b12e8368fb5930f5e7cc0b6136e9a87a479f77d, reversing
changes made to c13b850c9351e3d98cef8f39d4d0e506e3ef315f.
> Revert "Merge pull request #1247 from kelvin13/se-0184a"

- CoreFoundation/NumberDate.subproj/CFTimeZone.c
- DarwinCompatibilityTests.xcodeproj/project.pbxproj
- DarwinCompatibilityTests/DarwinShims.swift
- DarwinCompatibilityTests/Info.plist
- Foundation.xcodeproj/project.pbxproj
- Foundation/NSError.swift
- Foundation/NSLock.swift
- Foundation/URLSession/BodySource.swift
- Foundation/URLSession/http/HTTPURLProtocol.swift
- Foundation/URLSession/http/TransferState.swift
- TestFoundation/TestBundle.swift
- TestFoundation/TestCodable.swift
- TestFoundation/TestHTTPCookieStorage.swift
- TestFoundation/TestJSONEncoder.swift
- TestFoundation/TestJSONSerialization.swift
- TestFoundation/TestNSArray.swift
- TestFoundation/TestNSData.swift
- TestFoundation/TestNSKeyedArchiver.swift
- TestFoundation/TestNSLock.swift
- TestFoundation/TestNSProgressFraction.swift
- TestFoundation/TestThread.swift
- TestFoundation/TestUserDefaults.swift
- TestFoundation/TestXMLParser.swift
- build.py
This is a manual merge to resolve a conflict.
> Merge master into swift-4.1-branch

- Foundation/NSNumber.swift
- TestFoundation/TestNSNumberBridging.swift
Resolves [SR-4634](https://bugs.swift.org/browse/SR-4634) and [SR-6322](https://bugs.swift.org/browse/SR-6322).
> [WIP] Improve consistency in NSNumber bridging

- Foundation/NSError.swift
Reverts apple/swift-corelibs-foundation#1322
> Revert "Revert "Adapt to renaming of _getDefaultErrorCode() SPI.""

- Foundation/URLSession/TransferState.swift
- Foundation/URLSession/http/HTTPURLProtocol.swift
This PR is part of the #1355 which was raised to  move the common implementation to _NativeProtocol.
TransferState has 1-on-1 relationship with EasyHandle and is independent of protocol and hence the extensions of ```_HTTPURLProtocol``` have been moved to ```_NativeProtocol```
> Move common TransferState implementation to _NativeProtocol

- Foundation/NSAttributedString.swift
- TestFoundation/TestNSAttributedString.swift
This pull request finishes up unimplemented methods in `NS[Mutable]AttributedString`.
>  Finishing up NS[Mutable]AttributedString

- Foundation/URLProtectionSpace.swift
This is one of the pre-reqs for an upcoming implementation of basic auth with URLSession. URLProtectionSpace is a simple class with a handful of read-only properties which are initialised using one of the two initialisers - I am not sure if there's value in adding tests here (however, I am open to suggestions!)
> Initial implementation of URLProtectionSpace

- Foundation/URLAuthenticationChallenge.swift
Another pre-req for basic authentication with URLSession.
> Initial implementation of URLAuthenticationChallenge

- Foundation/NSURL.swift
replaced precondition if with guard to exit earlier
> [gardening] Replace precondition if with guard in NSURL

- Foundation/Data.swift
- Foundation/IndexSet.swift
Apply same CountableRange changes as in apple/swift#12913
> Remove references to CountableRange

- Foundation/NSRange.swift
This file contains changes required to build and use it on ppc64le platform.
> ppc64le port.

- TestFoundation/TestNSString.swift
This reverts commit e51fb9b10a79ecf319a736ca95d1643dea175dc1.
> Revert "revert string comparison changes"

- Foundation/NSIndexSet.swift
- TestFoundation/TestIndexSet.swift
> [4.1] Fix IndexSet/NSIndexSet range merging

- Foundation/Data.swift
- Foundation/JSONEncoder.swift
- Foundation/NSArray.swift
- Foundation/UserDefaults.swift
Refs: https://github.com/apple/swift/pull/15335, https://github.com/apple/swift/pull/15326
> [gardening] Prefer `isEmpty` over `count` check

- Foundation/FileManager.swift
Typo fix.
Credit to @Coeur for finding it.
> Typo on provied

- Foundation/Boxing.swift
- Foundation/Data.swift
- Foundation/IndexSet.swift
- Foundation/NSStringAPI.swift
- Foundation/NSSwiftRuntime.swift
Ref: https://github.com/apple/swift/pull/15594
> [SE-0193] Rename the attributes to their final names

- Foundation/UserDefaults.swift
> Marked UserDefaults.synchronize() as @discardableResult

- Foundation/Calendar.swift
Cherry-pick of
https://github.com/apple/swift/commit/68e76535bc1dc1b126dd7d81dfe8b1de68924e21
> Calendar: remove unnecessary return assignments

- Foundation.xcodeproj/project.pbxproj
- This is required by the change made in #1559.
> Add CFInternal.h into Header list when compiling in Xcode

- Foundation/EnergyFormatter.swift
This pull request refactors the TODO in Energy Formatter, as Locale.regionCode is now implemented.
> Refactor usesCalories in EnergyFormatter

- CoreFoundation/Locale.subproj/CFCalendar.c
> CFLocale: correct an invalid check for CFRelease

- Foundation/URLSession/URLSessionTask.swift
Cherry-pick of #1625 as requested.
> [4.2] make sure writes to URLSession.taskRegistry happen on work queue

- Foundation/NSArray.swift
Make result discardable as it is on Darwin
> Add @discardableResult to NSArray.write* methods

- CMakeLists.txt
- CoreFoundation/CMakeLists.txt
- CoreFoundation/cmake/modules/FindICU.cmake
- This allows building with a non system libicu.
- Required to build https://github.com/apple/swift/pull/19860
> Update CMake build to pass -I ICU_INCLUDE_DIR

- Foundation/Unit.swift
> Mark litersPer100Kilometers public.

- CMakeLists.txt
Replace some hard tabs with spaces.
> build: cleanup whitespace (tab -> spaces) (NFC)

- Foundation/NSLock.swift
Remove the POSIX-iness of the typenames to make the Windows port feel
more natural.
> Foundation: rename some internal variables (NFC)

- Foundation.xcodeproj/project.pbxproj
https://bugs.swift.org/browse/SR-9674
> SR-9674:Add TestUUID.swift to Foundation.xcodeproj/project.pbxproj

- TestFoundation/TestURL.swift
Refs:
- #1829 
- https://github.com/apple/swift-corelibs-foundation/pull/1834#discussion_r249191460
> Fix Xcode build in TestURL.swift

- Foundation/NSStringAPI.swift
Cherry-pick of #1861 to `swift-5.0-branch`.
> [5.0] NSString: sync with overlay

- Foundation/JSONEncoder.swift
- TestFoundation/TestJSONEncoder.swift
- Implement .convertToSnakeCase key encoding.
> SR-9828: JSONEncoder keyEncodingStrategy does not work on Linux

- Foundation/JSONEncoder.swift
- TestFoundation/TestJSONEncoder.swift
- Implement .convertToSnakeCase key encoding.
(cherry picked from commit c0feda6fd56e9878a2323275889321e290e10b08)
> [4.2] SR-9828: JSONEncoder keyEncodingStrategy does not work on Linux

- Docs/ReleaseNotes.md
- Docs/ReleaseNotes_Swift5.md
This patch contains release notes for the new API in `Scanner` and `FileHandle`.
> Add Swift 5.x release notes

- Foundation/NSPathUtilities.swift
In `NSTemporaryDirectory()`, `confstr()` is used to retrieve `_CS_DARWIN_USER_TEMP_DIR`. However, it does so in what is technically an incorrect fashion. This PR adds additional error checking to better diagnose various extremely rare and unlikely error conditions. If nothing else, it's a decent example of how finicky POSIX APIs can be.
> Better handle possible confstr() errors

- CMakeLists.txt
- CoreFoundation/Base.subproj/CFRuntime.c
- CoreFoundation/Base.subproj/CFRuntime_Internal.h
- CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
- CoreFoundation/CMakeLists.txt
- CoreFoundation/Locale.subproj/CFDateIntervalFormatter.c
- CoreFoundation/Locale.subproj/CFDateIntervalFormatter.h
- Foundation.xcodeproj/project.pbxproj
- Foundation/DateIntervalFormatter.swift
- TestFoundation/TestDateIntervalFormatter.swift
- TestFoundation/main.swift
This is a bug-for-bug rendition of the equivalent Darwin class, plus a port of the relevant tests. Not all SPIs have been ported because they rely on ICU past 61.
> Implement DateIntervalFormatter

- Foundation/NSDate.swift
We have a blessed API for this already, prefer that to the SPI.
> Foundation: remove unnecessary SPI

- CoreFoundation/Base.subproj/CFFileUtilities.c
We did not pass the file handler the absolute path to the file.  This
would break as it expected a non-NULL absolute path.  This is needed for
the Bundle tests to work.
> CFFileUtilties: correct directory iteration for Windows

- Docs/GettingStarted.md
Change latest version of macOS SDK to 10.14.
> [Docs] Update Getting Started instructions.

- cmake/modules/SwiftSupport.cmake
Passing all of the swift source files to the swift compiler causes the
command line to go over Window's 32767 character limit command length.
This now writes the source file lists to response files to get around that.
I'm a CMake newb (it took me far too long to figure out how to join a list into a string), so it's fairly likely there's a better way of doing this.
> Use Response Files in CMake

- Foundation/URLSession/BodySource.swift
- init(fileURL:workQueue:dataAvailableHandler:) was using the closure
argument for the buffer pointer outside of the closure, after
.deallocate() was called.
> _BodyFileSource: Fix use after free in init()

- Foundation/URLSession/URLSessionTask.swift
- TestFoundation/HTTPServer.swift
- TestFoundation/TestURLSession.swift
Cherry picked  from a6226abf50fe547a558ead11f7ff84d77e2bb87b
> [5.0][SR-10281] URLSession crash while handling basic authentication

- Foundation/NumberFormatter.swift
- TestFoundation/TestNumberFormatter.swift
- Ensure .format returns the full format string including .zeroSymbol.
> SR-10245: NumberFormatter: Implement .positiveFormat and .negativeFormat

- Docs/Status.md
- Also misc formatting tidyups.
> Status.md: Update the implementation status of various types

- TestFoundation/TestBundle.swift
Ensure TestBundle imports using `@testable import`.
> Build fix: TestBundle

- Foundation/NSMeasurement.swift
- Foundation/NSObject.swift
- Implement `NSMeasurement`
- Implement `NSObject`’s `.isKind(of:)`, `.isMember(of:)`, `.isSubclass(of:)` and `.superclass`.
> Parity: NSMeasurement, NSObject class methods

- TestFoundation/TestFileHandle.swift
Windows does not provide `pipe` but has an equivalent `CreatePipe` API.
Adjust the test for this.
> TestFileHandle: make the pipe construction work on Windows

- TestFoundation/TestThread.swift
Fixes a build break where a merge happened without me reinvoking tests on it. (Whoops.)
> Build fix: XCAssertEqual -> XCTAssertEqual

- Foundation/NSPathUtilities.swift
- TestFoundation/TestNSString.swift
Fixes https://bugs.swift.org/browse/SR-10364
> NSPathUtilities: Implement NSString.fileSystemRepresentation

- Foundation/Scanner.swift
- TestFoundation/TestScanner.swift
Fixes https://bugs.swift.org/browse/SR-10390
> Scanner: Implement localizedScanner(with:)

- Foundation/FileManager+Win32.swift
Alrighty, take 3. This time, it just changes FileManager+Win32.swift.
> Implemented _removeItem on Windows

- TestFoundation/TestURL.swift
Update TestURL to use FileManager for the file system work rather than
dropping down to the C/POSIX interfaces which are not universally
available.
> TestFoundation: port TestURL to FileManager

- Foundation.xcodeproj/project.pbxproj
- Foundation.xcodeproj/xcshareddata/xcschemes/CoreFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/plutil.xcscheme
> Xcode 10.2: Update to recommended settings

- Foundation/NSNotification.swift
- TestFoundation/TestNotification.swift
https://developer.apple.com/documentation/foundation/nsnotification/name/1924168-init
> Add missing `NSNotification.Name.init(_:)`

- Foundation/Host.swift
Depends on apple/swift#24286
The implementation of Host was disabled for Android, probably because
Glibc didn't include one header (netdb.h) which was needed to compile
this file. But changing Glibc is not enough, because the Android
implementation of that function and other bits differ slightly from
Linux implementation. For those cases private overrides are provide, to
keep the code unchanged.
There's also a little bit of formatting in one of Windows parts, which
was missing two spaces of indentation (probably checking without
whitespace enabled is good for this diff).
> [android] Enable Foundation.Host

- CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
- CoreFoundation/URL.subproj/CFURL.c
- CoreFoundation/URL.subproj/CFURL.h
- Foundation/Bundle.swift
- Foundation/FileManager+POSIX.swift
- Foundation/FileManager+Win32.swift
- Foundation/FileManager.swift
- Foundation/NSSwiftRuntime.swift
- Foundation/NSURL.swift
- Foundation/URL.swift
- TestFoundation/TestURL.swift
Implement resource values at the Swift layer, leveraging the FileManager implementations and partially moving them closer to completion.
> Parity: NSURL resource values.

- Foundation/NSData.swift
- Foundation/NSPathUtilities.swift
- rename doesn't work on Windows if the target already exists, instead
use ReplaceFile/MoveFile depending on if the target exists
- open() doesn't properly set sharing permissions, use CreateFile
instead
- fds must be closed before attempting to move their target file on
Windows
```swift
print(FileManager.default.createFile(atPath: "Foo.txt", contents: Data(), attributes: nil))
print(FileManager.default.createFile(atPath: "Foo.txt", contents: Data(), attributes: nil))
```
didn't work before, now it does.
> Fix FileManager.createFile on Windows

- Foundation/Process.swift
The function was renamed but not all references were.
> Foundation: make build after PR2189

- CoreFoundation/Base.subproj/CFPlatform.c
On Windows, open() doesn't set FILE_SHARE_DELETE by default meaning that
if another handle requests deletion privileges, it will always fail
unless the original handle is closed.
An example of where this happens is
```swift
{
guard let fh = FileHandle(forWritingAtPath: somePath) else { ... }
defer { try! FileManager.default.removeItem(atPath: somePath) }
fh.write()
}
```
Without FILE_SHARE_DELETE, the defer happens before the FileHandle's deinit occurs, causing removeItem to fail because it can't open somePath for deletion.
> [Windows] Ensure files open with FILE_SHARE_DELETE

- Foundation/FileHandle.swift
- TestFoundation/TestPipe.swift
Fix incorrect usage of `@testable import`.
> Build fix: TestPipe

- CMakeLists.txt
- Foundation.xcodeproj/project.pbxproj
- Foundation/URLSession/Message.swift
- Foundation/URLSession/TransferState.swift
- Foundation/URLSession/URLSession.swift
- Foundation/URLSession/URLSessionConfiguration.swift
- Foundation/URLSession/ftp/FTPURLProtocol.swift
- Foundation/URLSession/http/HTTPURLProtocol.swift
- TestFoundation/FTPServer.swift
- TestFoundation/TestURLSessionFTP.swift
- TestFoundation/main.swift
- build.py
This PR includes the FTP data task implementation along with the FTPTestServer implementation .
> Initial Implementation of FTP Data task

- Foundation/URLSession/libcurl/MultiHandle.swift
We would cast the CURL socket type to an Int and back during the
MultiHandle setup.  This does not work properly for Windows.  Given that
the interfaces are internal, keep the type sugar as far as possible
before handing off to libdispatch.
> Foundation: correct handle management on URLSession

- Foundation/NSPathUtilities.swift
- Foundation/NSURL.swift
This update is to match Darwin
> Update NSString.path(withComponents:) API

- Foundation/HTTPCookieStorage.swift
> Refactor `HTTPCookieStorage.sortedCookies` using the return value of `DispatchQueue.sync`

- TestFoundation/TestFileManager.swift
https://bugs.swift.org/browse/SR-10819
> Disable FileManager.test_replacement since it is failing on 18.04

- Foundation/FileManager+Win32.swift
- FindFirstFileW should be given a directory with \\* else it will only
return the given directory
- . and .. should be excluded from the results
> Fix up _contentsOfDir on Windows

- TestFoundation/TestURLSessionFTP.swift
https://bugs.swift.org/browse/SR-10922
> Disable test_ftpDataTask crashing occasionally in CI

- Foundation/FileManager+Win32.swift
If a file is not found, rather than failing, we should use
GetFullPathNameW which doesn't resolve symlinks, but will work on paths
that don't exist.
> Fallback to GetFullPathNameW for Windows _canonicalizedPath

- Foundation.xcodeproj/project.pbxproj
- Add TestNSSortDescriptor.swift into the TestFoundation target.
> Fix Xcode build

- Foundation/Process.swift
Attempt to interpret NTSTATUS and signal errors on Windows so that we
can indicate when a process crashed.
> Interpret Process Exit Codes on Windows

- Foundation/FileHandle.swift
`DispatchIO.read(fromFileDescriptor:maxLength:runningHandlerOn:)` is not
viable on Windows as the fileDescriptor is not available as we cannot
convert the handle to a file descriptor.  Extract the operation into a
local closure and dispatch from the right function in DispatchIO.
> FileHandle: fix readInBackgroundAndNotify for Win32

- Foundation/DateInterval.swift
Add Conformance of 'DateInterval' to protocol 'Decodable'  to match Darwin.
> Add Conformance of 'DateInterval' to protocol 'Decodable'

- Foundation/NSCharacterSet.swift
It is safe for this class to inherit decoding from its superclass.
> Parity: NSCoding stragglers: NSMutableCharacterSet

- CoreFoundation/URL.subproj/CFURLSessionInterface.c
- CoreFoundation/URL.subproj/CFURLSessionInterface.h
- Foundation/URLSession/libcurl/EasyHandle.swift
- Foundation/URLSession/libcurl/MultiHandle.swift
This reverts commit 02656bf6637d75ead56d628960c02569330b99c8. Fixes SR-11557.
> master: Cherry-pick revert of 02656bf6637d75ead56d628960c02569330b99c8

- Foundation/Process.swift
- TestFoundation/TestProcess.swift
- Fix compile error on Windows when using .currentDirectoryURL
#2525 Broke compiling on windows, this should fix it.
> Process: Match Darwin more closely for handling of .currentDirectoryPath and .currentDirectoryURL

- Foundation.xcodeproj/project.pbxproj
- Foundation.xcodeproj/xcshareddata/xcschemes/CFURLSessionInterface.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/CoreFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/SwiftFoundationNetworking.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/TestFoundation.xcscheme
- Foundation.xcodeproj/xcshareddata/xcschemes/plutil.xcscheme
Note: I haven't enabled the `CODE_SIGNING_IDENTITY` setting
> Updated Xcode project settings to 11.3 recommendations

- Foundation/JSONSerialization.swift
- TestFoundation/TestJSONSerialization.swift
> [5.2] Limit the amount of recursion allowed while JSONSerialization parses.

- Sources/Foundation/JSONSerialization.swift
- Tests/Foundation/Tests/TestJSONSerialization.swift
> Limit the amount of recursion allowed while JSONSerialization parses.

- Sources/Foundation/Codable.swift
Refactors _typeDescription function of DecodingError using switch for type casting
> Refactors _typeDescription function of DecodingError

- Sources/FoundationNetworking/URLSession/URLSession.swift
Support asynchronous large file upload
> feat: improve uploadTask fromFile

- Tests/Foundation/HTTPServer.swift
- _TCPSocket is now only used for 1 socket, either a listener or client
connection.
- _HTTPServer now listens for a connection and returns a new _HTTPServer with
the client connection.
- Client _HTTPServer sub-servers are run in a Dispatch async() block to
provide conncurrency for incoming connections.
- When reading the request from the socket, _SocketDataReader() is now used to
read, as `Data` not `String`, and look for appropiate HTTP separators (\r\n).
- When reading chunked requests check for the length of each chunk and look for
the terminating 0 byte chunk.
Note: This doesn't enable any tests and the current tests for `TestURLSession` are still disabled but following PRs will enable them.
> HTTPServer: Update the Test server to be concurrent and improve reading requests

- Tests/Foundation/HTTPServer.swift
Reverts apple/swift-corelibs-foundation#2734
> Revert "Test HTTPServer with urls that match the method"

- Docs/Status.md
> Fix table header typo 'statues' -> 'status'

- Docs/API Surface.tasks
This file tracks what symbols are missing on purpose (and generally why), vs. what symbols are missing that we would like to have.
> Add the API Surface tasks file to the documentation.

- Sources/Foundation/NSStringAPI.swift
Syncs with https://github.com/apple/swift/pull/31687
> Remove unnecessary Optional unwrapping

- Sources/Foundation/NSData.swift
- In the main loop that reads input bytes, where there at least 3 bytes
left, read them directly instead of using .next() and use a simpler
processing loop that can avoid checks for end of input. This allows
removal of any branches inside the main loop. The end of input is
handled separately since at most it is run once at the end.
- Rename the input buffer index from `index` to `inputIndex` to avoid
confusion with the newly added `outputIndex`.
There are some benchmarks for the encoding PRs @ http://si.org/posts/2020/05/base64-encoding.html
> Base64: Speedup encoding 2

- Sources/Foundation/Process.swift
- When setting up the subprocess in run(), any errors should be signaled
by throwing an NSError, not calling fatalError().
> Process: Dont call fatalError() for errors in run()

- CoreFoundation/NumberDate.subproj/CFDate.c
The Linux/BSD branches are fully compatible with WASI here.
> Add support for WASI in CFDate.c

- Foundation.xcodeproj/project.pbxproj
- Sources/FoundationNetworking/CMakeLists.txt
- Sources/FoundationNetworking/URLSession/URLSessionDelegate.swift
- Sources/FoundationNetworking/URLSession/URLSessionTaskMetrics.swift
This PR cherry picks the commits from my [previous PR](https://github.com/apple/swift-corelibs-foundation/pull/2886) to the release branch.
> [5.3] Add URLSessionTaskMetrics

- Sources/Foundation/Process.swift
This is a cherry-pick of be83f8d from the main branch. It is completely safe as it only reorganizes the code for Android and changes nothing on non-Android.
> [5.4] Process: Adapt #2928 for Android

- Tests/Foundation/Tests/TestURLSession.swift
- Add a timeout to the DispatchGroup wait().
- Re-enable the test.
> TestURLSession: Fix test_concurrentRequests()

- CoreFoundation/Base.subproj/SwiftRuntime/TargetConditionals.h
These seemed to be unintentionally undefined in some cases, so I added them
> Added missing `TARGET_OS_CYGWIN` defines to TargetConditionals.h

- Sources/Foundation/PropertyListSerialization.swift
> Fix memory leak in PropertyListSerialization

- Sources/Foundation/PropertyListSerialization.swift
rdar://80919378
Cherry-pick of #3013
> [5.4] Fix memory leak in PropertyListSerialization

- Docs/GettingStarted.md
This pull request updates links in the getting started documentation.
> Fix getting started links

- Sources/Foundation/NSCharacterSet.swift
- Sources/Foundation/NSCoder.swift
- Sources/Foundation/NSData.swift
- Sources/Foundation/NSNumber.swift
- Sources/Foundation/NSObject.swift
- Sources/Foundation/Progress.swift
- Tests/Foundation/Tests/TestNSData.swift
This mostly reverts commits c6148cfb3d7d5bffdefc6dc5ef76577154d8ab75,
6548e5092f55b15b9fabf9c75f739773fc236daf,
60c738abdceba9e604f42fabcb160e14ba2b6c9d.
> Revert a set of changes increasing visibility.

- CoreFoundation/PlugIn.subproj/CFBundle_Internal.h
This avoids an annoying warning in the Windows path that was introduced
with the last update to Foundation.  This implements the functionality
on Windows as well.
> CoreFoundation: implement mapping from file descriptor to binary

- Sources/Foundation/Thread.swift
We would previously print invalid strings due to invalid memory
pointers.  This corrects that and takes the opportunity to simplify some
of the deallocation handling by using a temporary allocation.
> Foundation: correct `Thread.callStackSymbols` on Windows

- Sources/Foundation/Thread.swift
We would previously print invalid strings due to invalid memory usage.
The string name is not guaranteed to be nul-terminated, and the
`String(cString:)` initializer requires that guarantee.  Explicitly do
the alloc + init approach using `strncpy` to initialize the string in
place. This corrects that and takes the opportunity to simplify some of
the deallocation handling by using a temporary allocation.
> [5.7] Foundation: correct `Thread.callStackSymbols` on Windows

- Sources/FoundationNetworking/URLSession/URLSessionTask.swift
- Tests/Foundation/Tests/TestURLSession.swift
Cherry-pick of #3154 
@tomerd @parkera
> [5.7][URLSession] Do not crash for unsupported URLs

- Sources/FoundationNetworking/URLSession/URLSessionTask.swift
An alternative to rolling back WebSocketTask support (PR #4660)
> Move from POSIXError to URLError for URLSessionWebSocketTask

- Sources/FoundationNetworking/NSURLRequest.swift
- Tests/Foundation/Tests/TestNSURLRequest.swift
- Tests/Foundation/Tests/TestURLRequest.swift
> Check for invalid URLRequest header values

- CoreFoundation/Base.subproj/CFPlatform.c
- CoreFoundation/Base.subproj/ForSwiftFoundationOnly.h
- Sources/Foundation/Process.swift
- Tests/Foundation/Tests/TestProcess.swift
Reverts apple/swift-corelibs-foundation#4606
> Revert "Do not chdir before calling posix_spawn"

- Sources/Foundation/FileManager+Win32.swift
Give `_moveItem(atPath:toPath:isURL:)` the long path treatment on Windows.  This ensures that we are able to move items that may be deeply nested.  This helps improve the test pass rate on DocC a small amount.
> Foundation: adjust `moveFile` to support long paths on Windows

- Darwin/Foundation-swiftoverlay/Date.swift
- Darwin/Foundation-swiftoverlay/DateComponents.swift
- Sources/Foundation/Data.swift
- Sources/Foundation/UUID.swift
This cherry picks this PR: https://github.com/apple/swift-corelibs-foundation/pull/4777
> [5.9] Cherry pick "Add Sendable to Date, DateComponents, Data and UUID" 

- Sources/Foundation/Date.swift
- Sources/Foundation/DateComponents.swift
- Sources/Foundation/DateInterval.swift
Make `Date`, `DateComponents` and `DateInterval` `Sendable`
> Cherry pick #4827

- Sources/Foundation/Bundle.swift
Merge the main branch into package, bringing the Bundle Sendable fix over.
> Merge main into package

- Sources/FoundationNetworking/URLSession/URLSessionTask.swift
- Tests/Foundation/Tests/TestURLSession.swift
Cherry-pick of #4973 for `release/6.0`
> [6.0] Fix test_webSocket hang

- CMakeLists.txt
- Package.swift
- Sources/CoreFoundation/CFBundle.c
- Sources/CoreFoundation/CFString.c
Cherry picked from https://github.com/apple/swift-corelibs-foundation/pull/4934
> build: Repair the build on WASI platform

- Sources/Foundation/NSError.swift
- Sources/Foundation/NSURLError.swift
- Sources/FoundationNetworking/NSURLRequest.swift
- Sources/FoundationNetworking/URLProtectionSpace.swift
- Sources/FoundationNetworking/URLRequest.swift
- Sources/FoundationNetworking/URLSession/URLSessionConfiguration.swift
- Sources/FoundationNetworking/URLSession/URLSessionTaskMetrics.swift
Backport of https://github.com/swiftlang/swift-corelibs-foundation/pull/5162
> [6.1] New HTTP loader for URLSession

- Sources/Foundation/CGFloat.swift
- Sources/Foundation/FileHandle.swift
- Sources/Foundation/FileManager+POSIX.swift
- Sources/Foundation/FileManager.swift
- Sources/Foundation/Host.swift
- Sources/Foundation/NSData.swift
- Sources/Foundation/NSError.swift
- Sources/Foundation/NSLock.swift
- Sources/Foundation/NSPathUtilities.swift
- Sources/Foundation/NSPlatform.swift
- Sources/Foundation/NSSwiftRuntime.swift
- Sources/Foundation/NSURL.swift
- Sources/Foundation/Port.swift
- Sources/Foundation/Process.swift
- Sources/Foundation/Thread.swift
- Sources/FoundationNetworking/HTTPCookie.swift
- Sources/Testing/Testing.swift
- Sources/XCTest/Public/XCTestMain.swift
- Sources/plutil/main.swift
- Sources/xdgTestHelper/main.swift
> always @preconcurrency import Glibc/Musl/Android/Bionic/WASILibc [6.1]

- CMakeLists.txt
Equivalent of https://github.com/swiftlang/swift-foundation/pull/1220 for libraries produced by swift-corelibs-foundation
> Pass -fno-omit-frame-pointer on Linux
